### ISSUE TITLE
RSS生成的atom.xml乱码问题

### ISSUE THREAD

**Issue by shliujing** [iissnan/hexo-theme-next#1000]
### Expected behavior (预期行为)

![](http://7xncbk.com1.z0.glb.clouddn.com/useless/1.png)
### Actual behavior (实际行为)

![](http://7xncbk.com1.z0.glb.clouddn.com/useless/2.png)
### Steps to reproduce the behavior (重现步骤)

见[我的博客订阅](http://www.iamlj.com/atom.xml)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release ✔ 
-  Old version  

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces ✔ 
### Other Informations (Like Browser, System, Screenshots)

这是编码问题，我安装了feed插件。配置文件设定`rss: /atom.xml` 或者留空也都是这样的情况。

**Comment by ivan-nginx** [comment]
@shliujing dont understand u, write in English if not solved. If solved, close it please. Thank's!
