### ISSUE TITLE
可以设置添加广告栏吗？

### ISSUE THREAD

**Issue by Javen205** [iissnan/hexo-theme-next#1002]
### Expected behavior (预期行为)

在文章的底部或者首页的底部添加广告栏
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release ✔ 
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces ✔

**Comment by xovel** [comment]
当然可以。自行修改头部文件和底部文件即可。在主题目录下的`layout`目录里的相应`.swig`文件中。

**Comment by Javen205** [comment]
广告要引入js以及html代码   怎么操作  是直接添加到相应.swig文件中吗？  有详细的介绍博客或者案例吗？   @xovel

**Comment by zhangnew** [comment]
`next\layout\post.swig`  找到下面这段代码，在这段代码后添加 js 代码即可在文章结尾显示广告。（我只知道 Google 广告只需要添加 js 代码即可，html 自己研究一下）

      {% if theme.jiathis %}
        {% include '_partials/share/jiathis.swig' %}
      {% elseif theme.baidushare %}
        {% include '_partials/share/baidushare.swig' %}
      {% elseif theme.add_this_id %}
        {% include '_partials/share/add-this.swig' %}
      {% elseif theme.duoshuo_shortname and theme.duoshuo_share %}
        {% include '_partials/share/duoshuo_share.swig' %}
      {% endif %}

**Comment by ivan-nginx** [comment]
@Javen205 dont understand u, write in English if not solved. If solved, close it please. Thank's!
