### ISSUE TITLE
about页面404not found

### ISSUE THREAD

**Issue by yzitao** [iissnan/hexo-theme-next#1003]
### Expected behavior (预期行为)

想要做一个about的页面
### Actual behavior (实际行为)

然后就hexo new page about
并且修改了next主题中的conflg.ymf
把#about：/about取消注释
### Steps to reproduce the behavior (重现步骤)

本地浏览没有问题
就是hexo deploy之后
about页面显示404 not found
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by lijun820** [comment]
同问

**Comment by sunshinevita** [comment]
我直接本地都米有about页面

**Comment by deweixu** [comment]
在博客的`source`目录下新建一个`about`目录，然后再`about`目录下新建`index.md`文件，编辑`index.md`文件后面生成的就是`关于`页面
`hexo clean`
`hexo g`
