### ISSUE TITLE
请问如何单独更改文章外链的样式

### ISSUE THREAD

**Issue by Jeffrey95** [iissnan/hexo-theme-next#1004]
### Expected behavior (预期行为)

文章内外链的样式与其它链接的样例分离，即文章中外链是指定颜色，与其它链接的颜色不同，以提高区分度。
### Actual behavior (实际行为)

文章中外链的和博客里其他地方的链接共用同一个css，可是感觉文章中外链的辨识度不高，想单独更改外链的颜色，但不知如果把它单独分出来。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master✔ 
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse✔ 
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

![链接](http://7xjfag.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-07-26%20%E4%B8%8A%E5%8D%8812.45.09.png)
例如这里我想要把`这里`指定为蓝色，而下面博客自带链接部分不变。

**Comment by xovel** [comment]
~~仅供参考~~
~~~css
.post a[rel~="external"]{ color:#C12121; }
~~~

**Comment by wuxubj** [comment]
你要的大概就是[这个效果](http://www.wuxubj.cn/)吧
要修改链接文本颜色但又不影响文章标题，需要修改``.post-body``样式
[这是教程](http://www.wuxubj.cn/2016/08/13/Hexo-nexT-build-personal-blog/#修改文章内链接文本样式)

**Comment by flyflyflyingfish** [comment]
在哪里修改？ 上面的那个教程内部服务器错误。

**Comment by wuxubj** [comment]
近期网站正在备案，所以工作日早9:00到晚5:00服务器关闭，其他时间段可正常访问。

**Comment by ivan-nginx** [comment]
@Jeffrey95 dont understand u, write in English if not solved. If solved, close it please. Thank's!
