### ISSUE TITLE
不知道作者可不可以提供主题的纯HTML模板？

### ISSUE THREAD

**Issue by HuberyLee** [iissnan/hexo-theme-next#1005]
### Expected behavior (预期行为)
非常喜欢作者开发的next主题，想在自己的博客中使用，不知作者是否方便提供纯HTML模板，谢谢！

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by xovel** [comment]
~~可以直接查看页面源代码进行获取...~~

**Comment by iissnan** [comment]
其实，我也没有这个纯 HTML 模板...
