### ISSUE TITLE
每个数学公式的结尾都多个竖线是为什么？

### ISSUE THREAD

**Issue by shijiebei2009** [iissnan/hexo-theme-next#1006]
### Expected behavior (预期行为)

公式结尾无竖线
### Actual behavior (实际行为)

公式结尾有竖线
### Steps to reproduce the behavior (重现步骤)

参考链接中的公式结尾

[异常公式](http://codepub.cn/2015/07/03/Python-implementation-of-the-longest-common-subsequences/)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release  ✔
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist  ✔
-  Pisces

**Comment by ivan-nginx** [comment]
@shijiebei2009 dont understand u, write in English if not solved. If solved, close it please. Thank's!
