### ISSUE TITLE
为什么我的menu的about选项设置了，却不显示啊。

### ISSUE THREAD

**Issue by sunshinevita** [iissnan/hexo-theme-next#1008]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by HugHoo** [comment]
@sunshinevita 
```bash
$ hexo new page "about"
```

**Comment by ivan-nginx** [comment]
@sunshinevita dont understand u, write in English if not solved. If solved, close it please. Thank's!
