### ISSUE TITLE
Pisces 站点下 Disqus评论不能加载

### ISSUE THREAD

**Issue by deweixu** [iissnan/hexo-theme-next#1009]
Pisces 站点下 Disqus评论不能加载

`count.js`、`embed.js` 加载失败

给站点`disqus.com`开socks5代理就能加载成功

**Comment by deweixu** [comment]
Disqus 被墙

**Comment by leejiajun** [comment]
@deweixu 翻墙后还是无法加载，为什么呢？

**Comment by deweixu** [comment]
@leejiajun 你可以开浏览器控制看看是什么错误

**Comment by leejiajun** [comment]
@deweixu 我这里只有https://的头才能访问Disqus的js文件，不翻墙也似乎可以获取。诡异的是，成功加载一次后，后面就是
> We were unable to load Disqus. If you are a moderator please see our troubleshooting guide. 
据说问题是ID不对，可是我怎么都设置不对。

**Comment by He110te4m** [comment]
同问，我也是这个问题
