### ISSUE TITLE
我的博客的css样式路径丢失，怎么破。

### ISSUE THREAD

**Issue by sunshinevita** [iissnan/hexo-theme-next#1010]
### Expected behavior (预期行为)

网站的显示应该是正常的
### Actual behavior (实际行为)

网站显示css样式找不到路径

但是，在我的github里，那些丢失的路径的文件都在
### Steps to reproduce the behavior (重现步骤)

hexo  d -g命令之后
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@sunshinevita dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by 6061960** [comment]
I have the same issue.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
