### ISSUE TITLE
主题如何平稳升级

### ISSUE THREAD

**Issue by twiceyuan** [iissnan/hexo-theme-next#1011]
### Expected behavior (预期行为)

使用这个主题很久了，最近发现添加了 Pisces 这种样式，想使用发现自己的版本没有这个，想升级却没有找到合适的方法，请问有没有推荐的升级方法
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master ✔
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes ✔
-  Muse
-  Mist
-  Pisces

**Comment by TypeLee** [comment]
我也想知道用什么命令升级

**Comment by ivan-nginx** [comment]
@twiceyuan dont understand u, write in English if not solved. If solved, close it please. Thank's!
