### ISSUE TITLE
不蒜子统计问题

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1012]
不蒜子统计，http://www.ehlxr.me 和 http://ehlxr.me 统计结果不一样

**Comment by Everfighting** [comment]
我这边点击过去是貌似是一样的。
不知道楼主是不是指的PV不一样？
后点击的那个页面pv增加了一个，是因为多浏览了一次。

**Comment by ehlxr** [comment]
你用的chrome浏览器吧，chrome浏览器访问http://www.ehlxr.me 它会自动跳到 http://ehlxr.me ，所以结果是一样的

**Comment by Everfighting** [comment]
恩 我没用其他浏览器试过，但是chrome我试了下没问题

**Comment by KevinL-94** [comment]
请问数据显示不准确怎么解决啊？访客数和总浏览量都有10多万

**Comment by ivan-nginx** [comment]
@ehlxr dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by hotYan** [comment]
When I refresh the page once, the PV statistics add 2. Pv statistics should theoretically add 1. What's the problem?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
