### ISSUE TITLE
Fontawesome icon失效

### ISSUE THREAD

**Issue by C0deZLee** [iissnan/hexo-theme-next#1015]
### behavior

在_config.yml里定义social_icons之后，github, stackoverflow, twitter均不能显示，显示为默认的地球状icon，不知道是为什么。
所以想请问一下作者next theme使用的**fontawesome是什么版本**，是不是icon的名字换了，以及**如何自己更新fontaswsome**。
感谢！
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master 5.0.1

NexT Scheme Using:
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

Chrome 53

**Comment by zhanghuai** [comment]
同求

**Comment by wuxubj** [comment]
NexT theme 中没有说使用的是 fontawesome 的什么版本，在[这个网站](http://fontawesome.dashgame.com/)可以查找 fontawesome 图标和名字的对应关系。

想知道是不是icon的名字换了，只需要查看``themes\next\source\vendors\font-awesome\css\font-awesome.css``文件中是否有该图标名。

NexT主题的 fontawesome 存储在``themes\next\source\vendors\font-awesome``文件夹中，如需更新，到[官网](http://fontawesome.io/)下载，解压后替换该文件夹即可。

**Comment by ivan-nginx** [comment]
@C0deZLee dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by jkzhao** [comment]
I find under every article, posted and updated do not display icon, i do not know why.

**Comment by ivan-nginx** [comment]
@jkzhao try to update FontAwesome icons or full update theme NexT.

**Comment by hxer7963** [comment]
pay attention to the case-senstive, May be the GitHub spell to Git**h**ub?
