### ISSUE TITLE
狐火浏览器图标不显示

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1016]
### Steps to reproduce the behavior (重现步骤)
火狐浏览器访问 http://ehlxr.me/ 图标不显示

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  ✔All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
是指 Favicon ? 清浏览器缓存后再试试
