### ISSUE TITLE
怎么添加一个新的归档，可以显示指定标签的

### ISSUE THREAD

**Issue by AloneMonkey** [iissnan/hexo-theme-next#1017]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by AloneMonkey** [comment]
hexo new page 只能用已存在的模板

**Comment by ivan-nginx** [comment]
@AloneMonkey dont understand u, write in English if not solved. If solved, close it please. Thank's!
