### ISSUE TITLE
如何将标签和分类全部显示在侧边栏？

### ISSUE THREAD

**Issue by leejiajun** [iissnan/hexo-theme-next#1018]
如何将标签和分类全部显示在侧边栏？

**Comment by Javen205** [comment]
设置一下主题的样式 你想要的是这个效果吗？http://javen205.oschina.io/

**Comment by leejiajun** [comment]
@Javen205 感谢回复，但不是我想要的风，我已经改变方案了。

**Comment by zhangnew** [comment]
@Javen205 你那个分类都不能点

**Comment by zhangnew** [comment]
@leejiajun  添加下面代码到 sidebar.swig 文件中适当的位置即可，标签同理，使用 list_tags 函数即可

见 Hexo API：https://hexo.io/zh-cn/docs/helpers.html#list-categories

		<div class="category-all-page">
			<div class="category-all">
			  {{ list_categories({depth: 1}) }}
			</div>
		</div>

**Comment by leejiajun** [comment]
赞

**Comment by ivan-nginx** [comment]
@leejiajun solved?
