### ISSUE TITLE
[QUESTION] 请问可以按修改时间排序吗？

### ISSUE THREAD

**Issue by lilonghe** [iissnan/hexo-theme-next#1019]
我想做成持续更新形式的，而不是一件事情水好多篇
请问可以做到吗？

**Comment by lilonghe** [comment]
目前使用到的方法：node_modules\hexo-generator-archive\lib
修改 generate.js
```
var allPosts = locals.posts.sort('-date'); -> var allPosts = locals.posts.sort('-updated');
```

**Comment by lilonghe** [comment]
已整理解决方法：https://www.lilonghe.net/archives/website-changelog.html

**Comment by asdf2014** [comment]
@lilonghe 你好，俺的博客 [yuzhouwan.com](http://yuzhouwan.com)也是采用的持续更新一篇的形式，，想知道你是怎么记录 每次更新的内容的呢

就是每次更新内容之后，怎么让读者知道 我做了哪些改动呢，，目前没想到什么好办法，总不能在留言区 自己留言说明吧~~

**Comment by lilonghe** [comment]
@asdf2014 没有办法
只能类似知乎形式，手动分割

**Comment by asdf2014** [comment]
@lilonghe 恩，这也是个办法

**Comment by geekrainy** [comment]
https://github.com/iissnan/hexo-theme-next/issues/1895

**Comment by xmzcl** [comment]
我也遇到了这个问题，不过我自己解决了，写了一篇博文，可以说比较完美解决了这个问题！应该算是现在最好的解决方法吧！我的博客地址：https://zealot.top 欢迎一起交流！
