### ISSUE TITLE
如何在页面底部显示百度统计数据？

### ISSUE THREAD

**Issue by szhupeng** [iissnan/hexo-theme-next#1022]
### Expected behavior (预期行为)

将_config.yml中的baidu_analytics:   xxxxxxxxxxxxxxxxxxxxxxxxx
填入百度统计给出的序列号以后应该在底部会出现类似于"总访问量×××次  |  您是第×××个访客"
### Actual behavior (实际行为)

什么都没有，但是我的百度统计那里有数据了
### Steps to reproduce the behavior (重现步骤)

将_config.yml中的baidu_analytics:   xxxxxxxxxxxxxxxxxxxxxxxxx
填入注册百度统计以后给出的那串序列号，接下来要在footer.swig中做什么来显示百度统计数据
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master  ✔
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces  ✔

**Comment by Everfighting** [comment]
everfighting.club 这个是我页面，你可以看下页脚的样式，是不是你想要的？
如果是这种，楼主可以添加不蒜子代码试试，简单方便，页面能够正常显示来访人数，跟页面访问量。

百度统计我也添加了，但是是在后台看的，在页面中并没有显示。

**Comment by ivan-nginx** [comment]
@szhupeng dont understand u, write in English if not solved. If solved, close it please. Thank's!
