### ISSUE TITLE
5.1的主题不知道如何使用algolia搜索呢？

### ISSUE THREAD

**Issue by remove** [iissnan/hexo-theme-next#1023]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release ✔
-  Old version - 

NexT Scheme:
-  All schemes ✔
-  Muse
-  Mist
-  Pisces

**Comment by eurusd** [comment]
同样等待中.....

**Comment by mritd** [comment]
关注中。。。本地搜索太空坑爹。。3M 文件加载。。。

**Comment by iissnan** [comment]
请参考 [第三方服务集成 - Algolia](http://theme-next.iissnan.com/third-party-services.html#algolia-search)

**Comment by mritd** [comment]
已经切换到了 jekyll....

**Comment by iissnan** [comment]
哈哈，强

**Comment by mritd** [comment]
https://mritd.me  我发现jekyll 全站 https ，然后 github 自动生成也更友好一点，自己写了一个 docker image，然后 在 vps 上镜像部署了 :yum:
