### ISSUE TITLE
"文章发表时间"显示格式的问题

### ISSUE THREAD

**Issue by qinzhongjie** [iissnan/hexo-theme-next#1024]
## 如何让时间显示为红色字体表示的格式，我看大家的都是显示正常的，请问在哪里配置

![正确显示文章发表时间](http://ob9qd20l4.bkt.clouddn.com/5~EQATPIC%5B~QYKZ%259NS%5BEQC.png)

**Comment by wuxubj** [comment]
**站点**配置文件``_config.yml``中将``date_format``修改为：
```yml
date_format: YYYY-MM-DD
```

**Comment by guardLtw** [comment]
请问一下你的发表时间后的时间是怎么取消的，每次更新一下那个时间就会变一下

**Comment by guardLtw** [comment]
请问一下，你的发表时间后面的那个时间 怎么取消的，每次更新那个时间都会改变

![time](https://cloud.githubusercontent.com/assets/20943036/20637804/6a62cff4-b3cd-11e6-9e34-c0eb0411bc46.png)

**Comment by ivan-nginx** [comment]
@qinzhongjie dont understand u, write in English if not solved. If solved, close it please. Thank's!
