### ISSUE TITLE
Pisces中单独修改subtitle字体以及移动端menu bar的颜色修改

### ISSUE THREAD

**Issue by shure22** [iissnan/hexo-theme-next#1025]
1. 请问该如何单独修改site-subtitle的字体？
   我在site-meta.styl的subtitle中，加了font-family
   `.site-subtitle {
                       margin-top: 10px;
                       font-size: $subtitle-font-size;
                       color:  #CDB38B;
                       font-family: Gloria Hallelujah;
   }`
   但是无法显示，只有填的和Title一致时，才可以修改字体。请问该如何解决？
2. 在Pisces的mobile端，请问隐藏和展开菜单的白色的按钮该在哪里修改颜色？

Thx！

**Comment by ivan-nginx** [comment]
@shure22 dont understand u, write in English if not solved. If solved, close it please. Thank's!
