### ISSUE TITLE
请问如何在about页面也自动抓取目录呢？

### ISSUE THREAD

**Issue by lixin4306ren** [iissnan/hexo-theme-next#1027]
### Expected behavior (预期行为)

希望在about页面也可以抓取目录，about我用来做个人简历
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by lixin4306ren** [comment]
已解决
front-matter里添加layout: post即可

例如：
---
title: about
date: 2016-08-02 14:34:03
comments: false
layout: post
---

**Comment by ivan-nginx** [comment]
@lixin4306ren dont understand u, write in English if not solved. If solved, close it please. Thank's!
