### ISSUE TITLE
如何才能安装流程图、时序图插件？

### ISSUE THREAD

**Issue by Cat7373** [iissnan/hexo-theme-next#1028]
流程图：https://github.com/adrai/flowchart.js
Githun.io：http://flowchart.js.org/
时序图：https://github.com/bramp/js-sequence-diagrams
Githun.io：https://bramp.github.io/js-sequence-diagrams/

作为程序员，在博客上画这两种图很常见，我在一个论坛上看到他们可以通过下面的方式调用这两个插件：
`流程图`

``````
``` flow
start=>start: Start:>http://bbs.xjcraft.org[blank]
end=>end:>http://http://bbs.xjcraft.org
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes or No?
io=>inputoutput: catch something...
start->op1->cond
cond(yes)->io->end
cond(no)->sub1(right)->op1
```
``````

`时序图`

``````
``` seq
A->B: Normal line
B-->C: Dashed line
C->>D: Open arrow
D-->>A: Dashed open arrow
```
``````

但不知如何才能在 Hexo + Next 下安装并支持这种调用形式。
求大神帮助 0.0

**Comment by Haocen** [comment]
如果只需要在特定的帖子里面支持，那 hexo 是可以支持直接插入 html 标签的。

**Comment by ivan-nginx** [comment]
@Cat7373 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Cat7373** [comment]
未解决，但我已经不需要它了，谢谢
Not solved, but I don't need it anymore, thanks
