### ISSUE TITLE
跟着官方文档走出现的问题

### ISSUE THREAD

**Issue by xu455255849** [iissnan/hexo-theme-next#1029]
我添加了多说应用 
打开网站控制台输出
GET https://static.duoshuo.com/embed.js net::ERR_CONNECTION_REFUSED

然后就是今天突然发现博客的归档和标签突然失效了

GET http://xu455255849.github.io/categories/ net::ERR_CONNECTION_RESET

求解

**Comment by AlbertKnag** [comment]
遇到一样的问题  安装文档配置好后，发现分类和标签都不好使，点击进去是空白
同时问一下，如何配置一篇文章既有分类，又有标签？

**Comment by beiweiqiang** [comment]
你好 我也出现了这种问题，我也是托管在github上的
