### ISSUE TITLE
具体某个分类的文章列表页，无文章显示

### ISSUE THREAD

**Issue by viaNull** [iissnan/hexo-theme-next#103]
版本：
hexo: 3.0.1
os: Darwin 13.4.0 darwin x64
http_parser: 1.0
node: 0.10.28
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.27
zlib: 1.2.3
modules: 11
openssl: 1.0.1g

如：http://blog.vianull.com/categories/linux%E8%AE%B0%E5%BD%95/  页面下文章无显示
换用默认的Landscape 该页无问题。

问题可能出在哪里呢 多谢

**Comment by xirong** [comment]
我的也是这样子的，http://ixirong.com/categories/，为什么呢？

**Comment by iissnan** [comment]
修复了 :smile:

**Comment by xirong** [comment]
done !  :satisfied:
