### ISSUE TITLE
为什么手机上完全看不到

### ISSUE THREAD

**Issue by fastzhong** [iissnan/hexo-theme-next#1030]
### Expected behavior (预期行为)

电脑浏览器正常，手机浏览器不正常
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔ Master
  ✔  Latest Release
  ✔  Old version - 

NexT Scheme:
-  All schemes
-  Muse
  ✔  Mist
  ✔  Pisces
### Other Informations (Like Browser, System, Screenshots)

![img_2903](https://cloud.githubusercontent.com/assets/195016/17462216/be2d0d30-5cd8-11e6-8ba1-bf4cbda6b777.PNG)

**Comment by ivan-nginx** [comment]
@fastzhong dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by fastzhong** [comment]
我修改了一些源代码，还原后OK啦，应该还是有bug。
