### ISSUE TITLE
微信等移动端浏览器访问滚动问题

### ISSUE THREAD

**Issue by gumutianqi** [iissnan/hexo-theme-next#1031]
@iissnan 
### Expected behavior (预期行为)

在移动端访问能够图片浏览适配微信或者直接显示，而无须启用finybox。
### Actual behavior (实际行为)

滚动是finybox不断弹出，影响阅读体验。
### Steps to reproduce the behavior (重现步骤)

图片较多的文章中即可重现。

打赏插件同样在移动端当中出现finybox原因而导致体验很差。

**Comment by ivan-nginx** [comment]
@gumutianqi dont understand u, write in English if not solved. If solved, close it please. Thank's!
