### ISSUE TITLE
生成的HTML 源码里太多空格，格式排版很乱

### ISSUE THREAD

**Issue by zhuziyi1989** [iissnan/hexo-theme-next#1033]
如图这个截的作者官网的源代码：
![]( http://ww4.sinaimg.cn/large/69b05e0ajw1f6mj2i744dj21kw16a45a.jpg)

**Comment by zhangjh** [comment]
你需要这个：
http://www.5941740.cn/2016/02/19/gulp-minify-blog/

**Comment by zhuziyi1989** [comment]
#665
