### ISSUE TITLE
Git 多账户

### ISSUE THREAD

**Issue by FraserYu** [iissnan/hexo-theme-next#1035]
配置了Hexo应用next主题，用的是git的全局global账户，现有一个GitLab上的项目，所以需要配置另外一个账户，按照网上的教程，最终配置了.ssh 目录下的config文件，加了github和gitlab上的两个host， 可是在windows环境， 一旦命令行窗口关闭重新启动，就需要手动执行命令：
[ssh-agent bash
ssh-add ~/.ssh/id_rsa_work](url)

有什么办法永久的就加入id_rsa_work 这个秘钥， 因为ssh默认是读取id_rsa 这个文件

**Comment by fourstring** [comment]
```bash
Host xx
HostName xx
User xx
Port xx
**IdentityFile xx**
```
