### ISSUE TITLE
首页文章缩略页标题被换行 

### ISSUE THREAD

**Issue by Everfighting** [iissnan/hexo-theme-next#1037]
### Expected behavior (预期行为)

首页文章缩略图，标题应该在一行内显示完毕
### Actual behavior (实际行为)

缩略图有些标题会出现两行显示的情况
### Other Informations (Like Browser, System, Screenshots)

![](http://7xsxjz.com1.z0.glb.clouddn.com/%E6%8D%A2%E8%A1%8C%E9%97%AE%E9%A2%98.png)
多个博文都出现类似情况，

不知道哪里出了问题？

**Comment by ivan-nginx** [comment]
@Everfighting dont understand u, write in English if not solved. If solved, close it please. Thank's!
