### ISSUE TITLE
建议放弃使用多说，改用其他评论系统

### ISSUE THREAD

**Issue by Smalldy** [iissnan/hexo-theme-next#1040]
### Expected behavior (预期行为)
评论系统个可以正常使用

### Actual behavior (实际行为)
多说核心脚本static.duoshuo.com/embed.js不支持https访问！
在使用github搭建的博客中，多说多上述链接进行了HTTPS访问
代码如下：
ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
然而https下，无法获取到这个脚本，导致多说完全失效，多说分享也必然跟着中枪！

### Steps to reproduce the behavior (重现步骤)
满足两个条件：
1.https站点
2.使用多说评论系统

故障发生

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
搜狗浏览器
WIN10 1366*768

**Comment by fourstring** [comment]
https://n4l.pw
并没有出现你说的多说不能使用。如果https不能请求到，那么按照chrome的策略是禁用HTTP加载。
但是我的站完全正常使用多说

**Comment by Smalldy** [comment]
@fourstring 这是我访问你的网站时 一篇文章结尾时的情况:
图片:http://img18.poco.cn/mypoco/myphoto/20160812/10/18333124820160812102810044.png?699x452_130
可以看到..分享和评论都挂了

**Comment by fourstring** [comment]
然而我的浏览器完全正常使用多说，就在你说的那篇文章下面
这篇文章有11条评论，这些用户使用的浏览器有Firefox47、48 chrome46、52，使用的操作系统有win7也有win10，我自己是OS X10.11.6 chrome54
你是不是该升级一下浏览器版本

**Comment by Smalldy** [comment]
chrome浏览器确实可以正常的访问https://static.duoshuo.com/embed.js获得脚本
但是 搜狗浏览器 却不嗯呢该访问 https://static.duoshuo.com/embed.js 必须使用http://static.duoshuo.com/embed.js才能返回这个脚本

看上去是浏览器的问题

**Comment by geekrainy** [comment]
next主题内置了disqus和多说系统。多说的https在搜狗浏览器的问题应该是浏览器对证书的支持有问题。不过disqus时常由于网络原因无法加载。仁者见仁智者见智咯。

**Comment by fourstring** [comment]
@geekrainy 是的，disqus经常无法打开，在我这里已经被q了

**Comment by xovel** [comment]
然而据我所知，多说是支持https的、

**Comment by Smalldy** [comment]
@xovel 当时https怎么也访问不了 现在却可以了
