### ISSUE TITLE
Pisces主题的侧边栏内友情链接排版错乱

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#1041]
### Expected behavior (预期行为)

友情链接在侧边栏中两个为一行紧凑排布。若文字过长则单个为一行排布。
### Actual behavior (实际行为)

即使链接的文字并未占满一行，它们也会错开。并且以一种及其不自然的方式，文字与开头的符号错开。
### Steps to reproduce the behavior (重现步骤)

将scheme修改至Pisces，添加多条友情链接至侧边栏。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  ✔ Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  ✔ Pisces
### Other Informations (Like Browser, System, Screenshots)

```
Linux ShaX-Precision 4.4.6-gentoo-ShaX #16 SMP PREEMPT Thu Aug 11 12:06:24 CST 2016 x86_64 Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz GenuineIntel GNU/Linux
Google Chrome   52.0.2743.82 (正式版本) （64 位）
```

Following is my screenshot.

![cut](https://cloud.githubusercontent.com/assets/8444615/17609352/db527124-5ff9-11e6-924d-5cfba3eeef37.png)

**Comment by eurusd** [comment]
没问题的路过。

**Comment by saccohuo** [comment]
我有同样的问题。请问楼主有解决吗？

**Comment by iissnan** [comment]
Fixed. #1483
