### ISSUE TITLE
hexo搭建github 多说评论模块无法显示

### ISSUE THREAD

**Issue by SRaddict** [iissnan/hexo-theme-next#1042]
hexo搭建github博客，用的是next主题，用国内的网多说评论模块无法显示，用国外vpn访问就有 0.0不知道怎么回事，有大神知道么？

**Comment by Smalldy** [comment]
方法一:等几天
方法二:换个浏览器试试比如谷歌
方法三:搬迁到国内coding.net 他也有pages服务

**Comment by geekrainy** [comment]
这是多说的锅。这几天访问一直不那么稳定。

**Comment by ivan-nginx** [comment]
@SRaddict dont understand u, write in English if not solved. If solved, close it please. Thank's!
