### ISSUE TITLE
多图功能 图片不能放大

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#1043]
使用多图，图片不能放大，想放大，有办法吗？
{% gp 1-3 %}
图1
图2
图3
{% endgp %}

**Comment by Maples7** [comment]
+1

**Comment by xuecat** [comment]
@eurusd  你这个功能能用？我这里简直没法用，我想多图并排都没法！！你是在post上面用的吗？

**Comment by ivan-nginx** [comment]
@eurusd dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by chenmo1996** [comment]
@eurusd 你好
在``` /next/source/js/src/utils.js```中修改代码如下
```
wrapImageWithFancyBox: function() {
    $('.content img')
      .not('[hidden]')
      // .not('.group-picture img, .post-gallery img')
      .each(function() {
```
注意那两个斜杠，就是把那一句注释掉，问题就解决了~

**Comment by chenmo1996** [comment]
@Maples7 如上

**Comment by loremwalker** [comment]
@chenmo1996 think you very much :smiley:

**Comment by loremwalker** [comment]
@chenmo1996 对了，请问怎样只让文章图片不放大？

**Comment by redn3ck** [comment]
@xuecat 
`themes\next\source\css\_common\components\tags\group-pictures.styl`
中的样式为改为
```
.page-post-detail .post-body .group-picture-column {
  // float: none;
  margin-top: 10px;
  // width: auto !important;
  img { margin: 0 auto; }
}
```

**Comment by stevenjoezhang** [comment]
Will be fixed: https://github.com/theme-next/hexo-theme-next/pull/667
