### ISSUE TITLE
手机端归档和关于打不开，显示错误—47

### ISSUE THREAD

**Issue by kangseven7** [iissnan/hexo-theme-next#1044]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by kangseven7** [comment]
已解决
修改主题配置文件
在menu选项后面的目录加上“/”
##menu:
  home: /
  categories: /categories/
  archives: /archives/
  tags: /tags/
  guestbook: /guestbook/
  about: /about/
  #commonweal: /404.html/

**Comment by ivan-nginx** [comment]
@kangseven7 dont understand u, write in English if not solved. If solved, close it please. Thank's!
