### ISSUE TITLE
MarkdownPad 中的样式表问题

### ISSUE THREAD

**Issue by Smalldy** [iissnan/hexo-theme-next#1046]
本人使用上述软件进行写作 但是发现上述软件对markdown的实时预览效果与主题解析出来的效果有一些不同
最明显的就是代码部分
'''
//code.......
''''
这样的语法在我的软件中会导致代码不换行一直连下去 很乱 
在这个软件中 可以选择ccs文件;来支持不同的markdowv语法风格
我想,在主题中是否有这样的文件呢,如果有的话 应用到这个软件中 就可以得到一致的效果了

我也不知道ccs样式表是否能影响上述问题..................

**Comment by geekrainy** [comment]
Markdown本身是无样式的。样式解析取决于软件的规定。如果要获得一致效果你可以尝试吧主题中的css剥离出来应用到MarkdownPad中。不过用hexo更推荐的做法不应该是在hexo s中预览吗？而且是实时的。:)

**Comment by Smalldy** [comment]
已经解决!
在软件中更改渲染器即可
