### ISSUE TITLE
在Safari下，鼠标移动到标题上时，整个页面内容都会闪烁

### ISSUE THREAD

**Issue by zhen-ke** [iissnan/hexo-theme-next#1047]
### Expected behavior (预期行为)

鼠标移动到标题上时，标题下面出现横条。
### Actual behavior (实际行为)

鼠标移动到标题上时，出现横条的同时，整个内容页面也跟着闪烁
### Steps to reproduce the behavior (重现步骤)

在Safari下尝试把鼠标移动到标题链接上
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

![gif](http://ww2.sinaimg.cn/large/71ff35eagw1f6wkg1hqwrg20w70kbdlm.gif)

**Comment by ivan-nginx** [comment]
@zhen-ke dont understand u, write in English if not solved. If solved, close it please. Thank's!
