### ISSUE TITLE
Hexo+pg-github搭载的博客无法加载https://static.duoshuo.com/embed.js，求解决

### ISSUE THREAD

**Issue by kangseven7** [iissnan/hexo-theme-next#1048]
博客无法加载https://static.duoshuo.com/embed.js 多说无法显示 我用的是Hexo+github搭建的博客，用的next主题，配置后在本地可以用多说，embed.js和样式都可以加载。 但是部署到博客github了之后就无法加载多说，打开控制台看到一个错误提示： GET https://static.duoshuo.com/embed.js net::ERR_ADDRESS_UNREACHABLE (anonymous function) @ (index):673 (anonymous function) @ (index):674 请问这是什么问题，怎么解决。求解决方案。

**Comment by ivan-nginx** [comment]
@kangseven7 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by wqh0109663** [comment]
same problem , have you fixed it ?
