### ISSUE TITLE
怎么在文章里使用icon呢？

### ISSUE THREAD

**Issue by laughinging** [iissnan/hexo-theme-next#105]
网页小白求助。。

next模板最下面那个“powered by” 后面有个很好看的爱心，查了HTML源代码用的是"icon-heart"
我想在我的about me里也能加上一些icon. 就在我的.md文件里加了好多"icon-heart"这样的语句，但是运行完了这些图标都不见了。。

我用在线的https://www.zybuluo.com/mdeditor这个生成器就能生成那些icon，我猜可能是markdown的引擎不一样？ 我想了两个方法但是不知道怎么下手，求助。。
一个是直接生成HTML页面（反正about me改动也不多），但是不知道生成的网页应该放在哪。。
另一个是在某个markdown生成HTML的地方加上icon支持，但是我不太了解swig也不知道加在哪里。。
参见这里http://fortawesome.github.io/Font-Awesome/3.2.1/get-started/

求助，麻烦啦~

**Comment by minoscc** [comment]
比較簡單的方法是在你使用的字體基礎上添加上新的icon
/next/_config.yml -> icon_font: linecons  當前用的字體
/next/source/fonts/icon-linecons 找到字體

然後在你about的md文件中使用`<i class="icon-heart"></i>`   `icon-`是必須的後面是跟你定義icon的名字

**Comment by minoscc** [comment]
編輯icon字體
https://icomoon.io/#hi

**Comment by laughinging** [comment]
多谢~
按你的方法貌似只能使用/next/source/fonts/icon-linecons里现有的图标，对吗？
加入我想加一些其他图标，应该编辑哪个文件呢？

**Comment by iissnan** [comment]
@laughinging 可以自定义图标，过程比较繁琐。

https://github.com/iissnan/hexo-theme-next/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89LOGO%E4%BB%A5%E5%8F%8A%E4%B8%BB%E9%A2%98%E5%9B%BE%E6%A0%87

**Comment by laughinging** [comment]
@iissnan 
多谢~ 按照你的步骤我已经能在自己的电脑上生成想要的html文件了，但是用hexo deploy到github上的时候，我自定义的图标显示还是框框。。
http://laughinging.github.io/about/
我检查了一下public/fonts里面我自定义的字体已经生成了。不知道问题出在哪。。。求助。

**Comment by laughinging** [comment]
已解决~
貌似是github这边服务器要慢一拍的缘故
