### ISSUE TITLE
修改scheme后发布不起作用

### ISSUE THREAD

**Issue by aiplay** [iissnan/hexo-theme-next#1050]
我将scheme由Muse改为Pisces，hexo s后在浏览器输入 http://localhost:4000/ 显示没有问题。
但是执行hexo d发布后发现显示还是Muse的主题，并且有一些错乱。
我用的是chrome浏览器，在mac系统上。

**Comment by aiplay** [comment]
是不是hexo g后，在重新hexo d就可以重新提交，貌似还是不行。

**Comment by wuxubj** [comment]
可能是css没有更新，建议删除``public/css/main.css``后，重新``hexo g``，``hexo d``

**Comment by aiplay** [comment]
好的，谢谢。

**Comment by tutucoo** [comment]
建议本地更新重新执行hexo s,更新就可以看到了。
