### ISSUE TITLE
用七牛镜像存储解决https加载不出多说embed.js脚本时，出现hook-duoshu.js第6行报错

### ISSUE THREAD

**Issue by kangseven7** [iissnan/hexo-theme-next#1051]
hook-duoshuo.js:6 Uncaught TypeError: Cannot set property 'onload' of undefined(anonymous function) @ hook-duoshuo.js:6

($('#duoshuo-script')[0].onload = hookTemplate);

**Comment by ivan-nginx** [comment]
@kangseven7 dont understand u, write in English if not solved. If solved, close it please. Thank's!
