### ISSUE TITLE
关于移动端的一些问题~

### ISSUE THREAD

**Issue by pinkomeo** [iissnan/hexo-theme-next#1052]
首先感谢大牛这么好看的主题~

然后PC端基本ok了
然后用手机看了一下= =
首先是侧边栏没有了也没啥
然后搜索按钮点了不管用
我是使用的最新版本的next，然后搜索使用的是本地搜索

还有就是评论系统我是用的是多说，
我发现safari打开准备评论的时候，微信登录无法跳转
只能显示 请在微信客户端打开连接
不知道大牛知不知道这个是什么问题~

其他的移动端问题还没发现 继续查询中~

最后再感谢一次这么好看的主题 很爱！

**Comment by flashlab** [comment]
关于搜索，如果你用的是iphone，参考这个 #694

**Comment by ivan-nginx** [comment]
@pinkomeo dont understand u, write in English if not solved. If solved, close it please. Thank's!
