### ISSUE TITLE
通过Dropbox+vps+hexo搭建的，文章都没有标题？怎么解决

### ISSUE THREAD

**Issue by thomas0612** [iissnan/hexo-theme-next#1053]
通过Dropbox把.md文件同步到post文件夹，然后vps的脚本自动hexo g，但是访问博客的时候所有的文章都没有标题，怎么处理？

**Comment by alonecong** [comment]
@thomas0612  我的也是这个问题，愁人啊。

**Comment by thomas0612** [comment]
@alonecong 需要在文章头部插入模版代码。还在寻找办法中~~~

**Comment by alonecong** [comment]
@thomas0612 我现在也是这么解决的

**Comment by ivan-nginx** [comment]
@thomas0612 dont understand u, write in English if not solved. If solved, close it please. Thank's!
