### ISSUE TITLE
https自动转换成了http导致页面打不开

### ISSUE THREAD

**Issue by liutf** [iissnan/hexo-theme-next#1055]
### Expected behavior (预期行为)

  https://liutf.github.io/

   我首页可以打开,我点击分类的时候,页面打不开了. (文件都生成了,已Push.本机可以打开).

    看了一圈貌似*.github.io 的blog都有这样的问题,绑定域名的都ok,不知如何解决,求解!

### Actual behavior (实际行为)
 点击菜单的分类 , 页面打不开, "无法显示页面".

  按钮上显示的链接本应该是:https://liutf.github.io/categories/

  点击实际URL变为:http://liutf.github.io/categories/.

 另外几个菜单都是:  分类/标签/关于/归档 几个按钮都是一样的情况.

### Steps to reproduce the behavior (重现步骤)

首页 -> 点击菜单按钮( 分类/标签/关于/归档) 任意点一个

### NexT Informations

NexT Version:
  -  Master

NexT Scheme:
  -  Mist

### Other Informations (Like Browser, System, Screenshots)
-win10 , QQ浏览器(chrome47.x)

**Comment by liwei721** [comment]
我也碰到了这个问题，怎么解决的
