### ISSUE TITLE
正文表格的问题/MarkDown显示样式的问题

### ISSUE THREAD

**Issue by tianziyao** [iissnan/hexo-theme-next#1056]
你好 我很喜欢你的主题 我的文章之前是通过本地写好同步到farbox 
最近使用了NexT主题 发现在表格显示上面有些问题 
每个单元格是等宽的 而不是按文本长度决定单元格的宽度 请问这个问题该怎么解决呢？

下面是编辑软件的截图
![2222](https://cloud.githubusercontent.com/assets/20643362/17838812/9cb7cfce-6808-11e6-8e32-d84d03e64c29.png)

下面是NexT正文截图
![11111](https://cloud.githubusercontent.com/assets/20643362/17838813/9cf27908-6808-11e6-8f8d-fc57c5d6b5c2.png)

**Comment by tianziyao** [comment]
用html做表格了。

**Comment by Master-Wang** [comment]
@tianziyao  可以尝试将 `source/css/_common/scaffolding/tables.styl` 中的 `table-layout: fixed;`
 改为 `table-layout: auto;`
