### ISSUE TITLE
photos

### ISSUE THREAD

**Issue by tiramisutes** [iissnan/hexo-theme-next#1057]
请问下这个主题为什么不能用photos这个功能
title: Gallery Test
comments: true
date: 2014-11-13 10:27:53
photos: 
- /images/flume-plugins-project.png
- /images/structure.png
  categories:
  tags:
  ---
  blah blah

**Comment by ivan-nginx** [comment]
There is [Thumbs plugin](https://github.com/leviwheatcroft/hexo-thumbnails) for Hexo.

**Comment by ivan-nginx** [comment]
@tiramisutes dont understand u, write in English if not solved. If solved, close it please. Thank's!
