### ISSUE TITLE
怎么自定义菜单的图标?

### ISSUE THREAD

**Issue by liutf** [iissnan/hexo-theme-next#1058]
加了个菜单"留言板" , 显示的图标是个问号 , 求教怎么自定义?

**Comment by FeeAlan** [comment]
@liutf 到这里找http://www.fontawesome.com.cn/faicons/
例如:点赞图标，网站提示 ` <i class="fa fa-thumbs-up"></i>` 然后在主题的配置文件设置menu_icons为 
menu_icons:
....
like :  thumbs

注意空格

**Comment by iissnan** [comment]
Please see: http://theme-next.iissnan.com/getting-started.html#menu-settings
