### ISSUE TITLE
社交站点无法显示，[已PR]AddThis无法显示

### ISSUE THREAD

**Issue by Mr-Binary** [iissnan/hexo-theme-next#1059]
### Expected behavior (预期行为)
--语言为英文
--已经在配置文件里增加了社交站点的链接，twitter和github, 根据文档应该可以渲染出来
--**[改问题已修复，已PR]** AddThis的code也增加了， 根据文档应该也可以渲染出来

### Actual behavior (实际行为)
社交站点是无论social icons还是social links都看不到，最终页面也没有渲染这个
AddThis据前述，已经找到并且修复

### NexT Version:

  -  Master

### NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
Chrome
OS X 10.11.6

**Comment by Mr-Binary** [comment]
社交站点是我理解有误，以为上下是分离关系，原来是对应关系...

**Comment by linwhitehat** [comment]
在chrome最新版浏览器仍然无法显示addthis，但是firefox可以，求助
