### ISSUE TITLE
gist line number error

### ISSUE THREAD

**Issue by pingoat** [iissnan/hexo-theme-next#106]
使用gist的代碼的時候貌似有問題~   行數字顯示不全~   
highlight應該本來就不行的吧？
![screen shot 2015-04-13 at 11 22 46](https://cloud.githubusercontent.com/assets/1515069/7109437/fdc521a6-e1cf-11e4-9424-37dd5d09c60a.png)

**Comment by iissnan** [comment]
我这 gist 好久都没法打开。。挂代理都不行。我还以为 gist 挂了

**Comment by iissnan** [comment]
去除了 NexT 中关于 Gist 的自定义样式，测试了一个超过 600 行的 gist，并未发现问题。

如果有问题，请重新再开 issue。
