### ISSUE TITLE
菜单栏icon 显示问题

### ISSUE THREAD

**Issue by liutf** [iissnan/hexo-theme-next#1061]
![image](https://cloud.githubusercontent.com/assets/14069370/17879192/881c4a02-6922-11e6-90ed-3a188b172dbe.png)

  如图

**Comment by ivan-nginx** [comment]
@liutf dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by JiangTJ** [comment]
同样遇到了，master上的存在问题，5.1.2上没问题，我搜了menu_icons.enable，找到5.1.2上的代码拷贝回去临时解决的

**Comment by ivan-nginx** [comment]
Yeah, master branch and future 5.1.3 version will include dynamic menu and icons. See this pull: #1830.
