### ISSUE TITLE
音乐iframe  在本地可以显示在站点访问不能显示是什么问题？

### ISSUE THREAD

**Issue by zhanghao-blog** [iissnan/hexo-theme-next#1063]
谢谢  题主   主题很简约美观

**Comment by jaytangchn** [comment]
你好，我遇到了和你一样的问题，我的解决方法是把音乐资源的url改成https就好了。希望能帮到你！

**Comment by yangxiaoge** [comment]
为什么网易云音乐的不能播放啊,点击没有效果![image](https://cloud.githubusercontent.com/assets/12471093/18703368/318c038c-8018-11e6-83b2-a1cb15e9ab55.png)

**Comment by Jan9th** [comment]
请问改完 https 协议之后，有设置 center 节点失效的解决方案么？

**Comment by Jan9th** [comment]
@yangxiaoge 请问这种歌单或者专辑是如何操作的

**Comment by ivan-nginx** [comment]
@zhanghao-blog dont understand u, write in English if not solved. If solved, close it please. Thank's!
