### ISSUE TITLE
能否整合一下百度的站内搜索到主题里

### ISSUE THREAD

**Issue by Diefishfish** [iissnan/hexo-theme-next#1064]
看到主题里支持swiftype但是之前申请的key今天发现404了,然后去官网结果告诉我大概是试用过期了,而且国外的swiftype在国内访问速度也不是很快,于是找了百度站内搜索http://zn.baidu.com/
不知道能不能整合进去

**Comment by ivan-nginx** [comment]
@Diefishfish dont understand u, write in English if not solved. If solved, close it please. Thank's!
