### ISSUE TITLE
markdown渲染``里的内容有问题

### ISSUE THREAD

**Issue by tomoya92** [iissnan/hexo-theme-next#1065]
```
如果 `` 里有{{}} 就会报错，比如

`{{xx}}` 渲染的时候就会报错

```

**Comment by ivan-nginx** [comment]
@tomoya92 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by tomoya92** [comment]
you need google translate

2016年提交的issues，现在给了回答问我解决了没，我还真不知道，因为早就忘了，而且现在也从hexo换到jekyll了

你要是不想它是打开状态，可以自己把它关了

**Comment by ivan-nginx** [comment]
@tomoya92 i have google translate but it not always translate what peoples meaning.
And i think u need to write this issue to relevant place, e.g. to `hexo-renderer-marked` or in Hexo issues.
