### ISSUE TITLE
关于多说热评，

### ISSUE THREAD

**Issue by fangheart** [iissnan/hexo-theme-next#1067]
### Expected behavior (预期行为)

点击热评文章跳转，应该在我的博客内跳转到正确的地址。
### Actual behavior (实际行为)

实际却跳转到 www.yoursite.com/xxxxx
### Steps to reproduce the behavior (重现步骤)

我已经重新修改了hexo的_config.yml的url为我自己的域名，并且重新clean,生成，但是仍然是这个问题
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by aqsong** [comment]
站点配置文件里，_config.yml，里边搜索url：，要设置成你自己的blog地址，不能用默认的yoursite.com

**Comment by aqsong** [comment]
已经生成到多说的就只能在多说后台手动改了

**Comment by ivan-nginx** [comment]
@fangheart dont understand u, write in English if not solved. If solved, close it please. Thank's!
