### ISSUE TITLE
公式无法正确解析

### ISSUE THREAD

**Issue by guantau** [iissnan/hexo-theme-next#1068]
### Expected behavior (预期行为)

显示一个两行公式
### Actual behavior (实际行为)

$$
\begin{align}
L_m &=(P+F)\cdot(1+\alpha)^m+x\cdot (1+\alpha)^{m-1}+\cdots+x\
&=(P+F)\cdot(1+\alpha)^m+x\cdot\frac{(1+\alpha)^m-1}{\alpha}
\end{align}
$$
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@guantau dont understand u, write in English if not solved. If solved, close it please. Thank's!
