### ISSUE TITLE
表格无法正常显示

### ISSUE THREAD

**Issue by guantau** [iissnan/hexo-theme-next#1069]
### Expected behavior (预期行为)

正常显示表格
### Actual behavior (实际行为)

|年数|持有成本(万元)|收益（万元）
|:—-|:—-|:—|
|0|452.95|-20.8|
|1|467.59|-8.794|
|2|482.02|5.0819|
|3|496.20|20.941|
|4|510.13|38.904|
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@guantau dont understand u, write in English if not solved. If solved, close it please. Thank's!
