### ISSUE TITLE
permalink: :title/ 如何指定目录

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#107]
永久地址设置为permalink: :title/  文章全跑根目录了，太难看，难管理了，有何办法，指定一个目录？
谢谢

**Comment by iissnan** [comment]
这个问题在主题内目测是无法解决

**Comment by eurusd** [comment]
有什么好的方法？我现在是 年/月/日／文章名称

**Comment by iissnan** [comment]
选择哪个 `permalink` 我觉得没有太大的影响，内容才是本质

**Comment by eurusd** [comment]
懂了 谢谢
