### ISSUE TITLE
关于固定图片大小的问题

### ISSUE THREAD

**Issue by ruijun** [iissnan/hexo-theme-next#1071]
markdown里面使用
```
<img src="im.png"  width = "300" height = "200" />
```
来固定图片大小，markdown预览有效果，部署之后图片显示不出来。

**Comment by kaneren** [comment]
图片放在图床，我试了是可以的

**Comment by ruijun** [comment]
@kaneren 我的图片是放到本地的,不知道是不是这个引起的.我使用hexo g部署后,再hexo s,查看发现图片显示不出来.

**Comment by skybluefly** [comment]
src的路径错了吧

**Comment by kaneren** [comment]
@ruijun 你看是不是src路径错误，博客头像最后的路径是 `yoursite/images/avatar.png`，你放在images里的图片应该也类似。不过建议用图床啊，方便很多。

**Comment by ruijun** [comment]
@kaneren 是的，src路径错了，markdwon中使用了相对路径`src="../img/im.png"`，预览的时候没问题，部署的时候就加载不出图片。后来看了下，正常的路径应该是`src="/img/im.png"`。

还有个问题要请教下你的，next主题不支持图片并排显示的？

**Comment by kaneren** [comment]
#686 你看这个，貌似还没解决办法
