### ISSUE TITLE
如何水平显示多个图片？

### ISSUE THREAD

**Issue by xuecat** [iissnan/hexo-theme-next#1073]
### Expected behavior (预期行为)
楼主，我想在，水平居中显示多个图片。

### Actual behavior (实际行为)
让我伤心的试，我尝试了所有html的img格式去指定图片的水平居中，都无法达到预期效果。

唯一能让图片水平居中的却只有你的photos属性，但是我想在内容中水平显示而不是标题。

熬夜到3点了，都没弄好（楼主的库简直让我玩到不想睡）。
最后希望楼主能提示帮助，万谢！！！！！

**Comment by ehlxr** [comment]
你是想要 http://ehlxr.me/ 这个效果吗？

**Comment by xuecat** [comment]
嗯呢，恩，我就算用了group-pictures属性，都无法显示，才急的我发问！！！！！
@ehlxr  求解，万分感谢!!

**Comment by songmao123** [comment]
@ehlxr 在blog中怎样实现多张图片并排显示呀？

**Comment by ehlxr** [comment]
可以参考：
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#八、图片模式

**Comment by songmao123** [comment]
你这种方式在博客正文好像还是不行吧？

**Comment by ehlxr** [comment]
恩
