### ISSUE TITLE
categories和tags在本地服务器访问还可以，一上传git访问就挂！！

### ISSUE THREAD

**Issue by xuecat** [iissnan/hexo-theme-next#1074]
我有hexo new tags categories
也有修改menu tags categories

本地hexo s访问的页面正常，但是git上访问就挂！！！我看了生成了index.html了，git上也有，就是访问问题！！

这如何解决？？

**Comment by XueCat** [comment]
这是错误：

无法访问此网站

连接已重置。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_RESET

**Comment by xuecat** [comment]
楼主，我经过一天的测试，发现问题了。点击menu按钮时候跳转的网页没有“https：”前缀，url直接变成了name.github.io/tags；（哭死我了，终于发现问题了）。
但是我无力修改，因为我不是很懂前端，请楼主赶紧给条活路！！！！！！！！

**Comment by xuecat** [comment]
楼主不在吗？在线等呀！！

**Comment by xuecat** [comment]
真的没有人吗？好伤心.....

**Comment by lengthmin** [comment]
![Screenshot_2016-08-28-15-35-33-29.png](https://ooo.0o0.ooo/2016/08/28/57c2946b71d6a.png)
![Screenshot_2016-08-28-15-35-45-12.png](https://ooo.0o0.ooo/2016/08/28/57c2947514dc4.png)

没有问题呀

**Comment by xuecat** [comment]
恩！！！我昨天测试了很多次。我估计可能我的网（某城的网络）又做了网页缓存！！！导致的错误。公司网络就很好！
