### ISSUE TITLE
新建页面的文章对 Markdown 支持不完善

### ISSUE THREAD

**Issue by iTofu** [iissnan/hexo-theme-next#1076]
### Expected behavior (预期行为)

执行 `hexo new page "somepage"` 新建一个页面，然后打开 index.md 写文章。
### Actual behavior (实际行为)

不支持 Markdown 的 `*` / `-` 符号生成列表，而通过 `hexo new "a"` 出来的页面，是支持 `*` / `-` 生成列表的。

问题预览：http://note.leodev.me/honor/ ，中间名单部分。
### Steps to reproduce the behavior (重现步骤)

`hexo new page "somepage"` -> 编辑 index.md -> 输入类似以下片段：

``` markdown
* 小明

* 小白
```

执行 `hexo s` 预览该页面，本来应该是这样的：
- 小明
- 小白

而实际上却是这样的：

　　小明

　　小白
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master ✔
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces ✔
### Other Informations (Like Browser, System, Screenshots)
- mac OS 10.11.6
- Chrome 52.0.2743.116 (64-bit)

**Comment by iTofu** [comment]
对了，也不支持主题提供的 打赏 功能。

**Comment by kkxujq** [comment]
# 打赏功能
reward_comment: 经不住似水流年 逃不过此间少年
  wechatpay: /uploads/wechat.jpg
  alipay: /uploads/alipay.jpg
目前5.0.1以上的版本是支持的

**Comment by kkxujq** [comment]
# 打赏功能
reward_comment: 经不住似水流年 逃不过此间少年
  wechatpay: /uploads/wechat.jpg
  alipay: /uploads/alipay.jpg
目前5.0.1以上的版本是支持的

**Comment by ivan-nginx** [comment]
@iTofu dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by ivan-nginx** [comment]
#1697 (PART 5. Refactor wechat, reward and copyright features & added bitcoin donate.).
