### ISSUE TITLE
关于Pisces主题边距的问题

### ISSUE THREAD

**Issue by ruijun** [iissnan/hexo-theme-next#1077]
如下图所示，感觉两侧空白地方太多了，想调整下边距，要怎样修改呢？

![](http://i4.buimg.com/567571/f581fab8acb97aec.png)

**Comment by ivan-nginx** [comment]
@ruijun u can do it in file `themes/next/source/css/_variables/custom.styl`
Just add this lines:
```
$main-desktop			= 90%
$content-desktop		= calc(100% - 260px)
```
hexo clean && hexo g

**Comment by ruijun** [comment]
@ivan-nginx I do this, but the page appear

![](http://i1.buimg.com/567571/e0fc497910786778.png)

**Comment by ivan-nginx** [comment]
@ruijun also, need to change in `source/css/_schemes/Pisces/_layout.styl` file at the top
from
```
.header {
  position: relative;
  margin: 0 auto;
  width: 960px;
```
to
```
.header {
  position: relative;
  margin: 0 auto;
  width: $main-desktop;
```

Also, i'm not sure what i undestand what u want.
My google translate inaccurate. =)

**Comment by ruijun** [comment]
@ivan-nginx Thank you.  It's fine for me.

**Comment by jiezhongmath** [comment]
想请教一下，大家都是用的Pisces主题，为什么我的是两栏呢，而大家都是很简洁的一栏，网站名字在顶部？

**Comment by ruijun** [comment]
@jiezhongmath 

能截图看看一栏的主题界面吗？

**Comment by jiezhongmath** [comment]
自己搞定了，原来是跟屏幕的宽度有关。
多谢了！
