### ISSUE TITLE
地址栏中会出现多余的斜杠“/”

### ISSUE THREAD

**Issue by tufu9441** [iissnan/hexo-theme-next#108]
今天想尝试一下主题next，第一次进入首页，地址栏显示的是没问题的，即完整的域名或者localhost:4000；在点击顶部导航栏的任意一个按钮进入其它页面后，再从导航栏点进首页，地址栏中显示的变成"localhost:4000//"（部署到服务器后情况类似），有时候会出现3个斜杠，这时再从首页进入文章页面，地址栏显示的也是localhost:4000//categories/title.html。

其实在第一次从导航栏进入其它页面以后，将鼠标悬停在导航栏的其它按钮上，浏览器状态栏中显示出的目标也是localhost:4000//categories或者tags，只不过点进去以后地址栏中显示的变回localhost:4000/categories/，只有在点击首页按钮后地址栏中出现多余的斜杠。

我看了其它使用next主题的用户大部分没有这个问题，但我在http://androidperformance.com 这个站点看到了跟我描述的完全一致的问题。

**Comment by smilexiamo** [comment]
我的博客也有此问题

**Comment by tufu9441** [comment]
@smilexiamo 我看你的http://doublemine.tk/ 没有这个问题啊

**Comment by iissnan** [comment]
看了下 http://androidperformance.com/，在 分类/标签 页面的链接是 `..//categories`。

能贴下你站点的 `_config.yml` 中关于 `URL` 部分的配置吗？

**Comment by tufu9441** [comment]
@iissnan 
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://haomwei.com
root: /
permalink: :category/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
about_dir: about
history_dir: history
archive_dir: archives
guestbook_dir: guestbook
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

**Comment by iissnan** [comment]
看起来没有问题。。

**Comment by tufu9441** [comment]
@iissnan 对啊，我也觉得看上去没问题，用之前的主题就不会出现这个问题……

**Comment by smilexiamo** [comment]
@tufu9441 看错了，我以为是标题栏出现//

**Comment by tufu9441** [comment]
@iissnan 请问找到原因了没有呢？这个解决不了的话我也没法用next哦……

**Comment by qizhihere** [comment]
@tufu9441  是吗？我也遇到了这个问题，将external_link设置为false后还是一样呢

**Comment by tufu9441** [comment]
@qizhihere 我打错了，应该是relative_link设置为false……

**Comment by qizhihere** [comment]
@tufu9441 ok，已搞定 :)

**Comment by iissnan** [comment]
@tufu9441 :+1:

**Comment by iissnan** [comment]
https://github.com/hexojs/hexo/pull/1251
