### ISSUE TITLE
如何在博客首页添加背景音乐？还有如何添加Fork me on gitHub

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1080]
如何在**博客首页**添加背景音乐？还有如何添加Fork me on gitHub

**Comment by ehlxr** [comment]
自己研究了一下，在 themes\next\layout\_layout.swig 末尾添加 网易云音乐链接，设置 width=0 height=0 即可添加全局背景音乐。添加 GitHub Ribbons 代码即可添加Fork me on gitHub。
效果：http://ehlxr.me

**Comment by flaski** [comment]
还是不太懂怎么弄

**Comment by weqeo** [comment]
同不懂，求详细教程，靴靴！

**Comment by ehlxr** [comment]
@flaski @weqeo 这有个详细的教程http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#七、背景效果

**Comment by ehlxr** [comment]
可以替换这个文件，然后把文件末尾的注释去掉就好了
https://github.com/ehlxr/ehlxr-Hexo/blob/master/themes/next/layout/_layout.swig

**Comment by weqeo** [comment]
@ehlxr 多谢，我是这样做的，也可以实现了，不过还是非常感谢：http://weqeo.com/2016/10/11/Hexo%E4%B8%AD%E6%92%AD%E6%94%BE%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9A%84%E5%AE%9E%E8%B7%B5/

**Comment by ivan-nginx** [comment]
@ehlxr dont understand u, write in English if not solved. If solved, close it please. Thank's!
