### ISSUE TITLE
【求助】如何让百度收录网站

### ISSUE THREAD

**Issue by cyang812** [iissnan/hexo-theme-next#1082]
### Expected behavior (预期行为)
从百度可以搜索到网站cyang.tech
目前可以从谷歌搜索到。

**Comment by lengthmin** [comment]
github pages不允许百度爬虫抓取。
可以部署到自己的服务器上或者部署到其他pages服务

**Comment by cyang812** [comment]
有同时部署在coding上。在换这个主题之前，也是可以从百度搜索到的。

**Comment by lengthmin** [comment]
那就不太清楚了。。
***
**题外话:**
请问是怎么设置ns服务的cname的呢？国内外分流?

**Comment by cyang812** [comment]
对，分流。但是测试国外IP访问自己的域名是无法打开，出现github page 404,只能访问github.io。所以这样其实什么用。国外不能访问，而国内是连的coding

**Comment by lengthmin** [comment]
我知道为什么你的博客国外打不开了，
想部署在github pages上需要在source/下创建一个CNAME文件，里面填上你的一级域名。
刚刚查看了一下你的仓库，没有发现这个文件

**Comment by cyang812** [comment]
我已在source/创建这个文件。文件内容为http://cyang.tech。目前测试国外IP依然github的404.请问是我的文件内容不对吗？

**Comment by lengthmin** [comment]
不加http试试，直接写cyang.tech
还有就是，你打错字了。
是CNAME不是CHAME，检查一下。

**Comment by cyang812** [comment]
添加后，访问正确没有出现404。可是现在的问题是，我在github的其他仓库部署的静态网页，比如cyang812.github.io/Home，现在会自动变成cyang.tech/Home。导致我其他的网页不能正常访问。请问怎么解决？

**Comment by lengthmin** [comment]
抱歉，没有听懂是什么意思，不过按理来说可以访问的。。

**Comment by cyang812** [comment]
谢谢啊。这个问题我已经解决了。还是想问问那个百度收录的问题。因为我这个项目同时也部署在Coding上，那怎么做才能让百度收录。

**Comment by iissnan** [comment]
试试 [Baidu Push](https://github.com/iissnan/hexo-theme-next/pull/741)
