### ISSUE TITLE
超大图片点击查看后，关闭查看窗口后图片消失

### ISSUE THREAD

**Issue by Tomyail** [iissnan/hexo-theme-next#1083]
### Expected behavior (预期行为)
图片还在文章中

### Actual behavior (实际行为)
图片消失

### Steps to reproduce the behavior (重现步骤)

进入我的[博客](http://blog.tomyail.com/how-to-read-book/),点击第一张图片，然后点击关闭。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Latest Release

NexT Scheme:
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

看了下图片其实还在dom中，不过被显示的加上了{display:none}，所以被隐藏了。

**Comment by xuecat** [comment]
我不是楼主，但是我这里看是正常的。

**Comment by Tomyail** [comment]
问题找到了，看来和图片尺寸没有关系，是我markdown写法有问题，有问题的写法如下
```
[![][image-1]]()

[image-1]:	http://7xqh45.com1.z0.glb.clouddn.com/how-to-read-book.png "如何阅读思维图"
```
这个markdown转换成html后变成了
```
<a href="" class="fancybox" rel="group" title="如何阅读思维图">
   <img src="http://7xqh45.com1.z0.glb.clouddn.com/how-to-read-book.png" alt="" title="如何阅读思维图">
   <p class="image-caption">如何阅读思维图</p>
</a>
```

正确的写法应该是
```
![][image-1]

[image-1]:	http://7xqh45.com1.z0.glb.clouddn.com/how-to-read-book.png "如何阅读思维图"

```

转换成html后的：

```
<a href="http://7xqh45.com1.z0.glb.clouddn.com/how-to-read-book.png" class="fancybox" rel="group" title="如何阅读思维图">
   <img src="http://7xqh45.com1.z0.glb.clouddn.com/how-to-read-book.png" alt="" title="如何阅读思维图">
   <p class="image-caption">如何阅读思维图</p>
</a>
```
