### ISSUE TITLE
多图展示不成功！！

### ISSUE THREAD

**Issue by xuecat** [iissnan/hexo-theme-next#1086]
### Expected behavior (预期行为)

```
{% gp 2-2%}
  ![](/image-1.png)
  ![](/image-2.png)
{% endgp %}
```
### Actual behavior (实际行为)

![default](https://cloud.githubusercontent.com/assets/5563220/18054198/6f5a7e22-6e35-11e6-96e7-fdb7fb818203.PNG)

**Comment by ehlxr** [comment]
是不是没有加type啊，可以看看这个：
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#八、图片模式

**Comment by xuecat** [comment]
@ehlxr  楼主你博客好屌！！！等我晚上回去再细细研究，谢了！！

**Comment by monster-gump** [comment]
@xuecat 
@ehlxr 
两位好，我目前的问题和 @xuecat 之前的类似，也是解析不出图片。
看了两位的 blog 和解说，然而还是不太 work
我目前想做出的效果是 https://xuecat.github.io/about/ 这样的，但我看到 @xuecat 似乎是 hexo new 之后出来的文章页面替代了 about？在我的页面里没有 “发表于 2016-09-08” 的字样
而 @ehlxr 给的建议里也是 新建博文 然后再调整
我目前就是想做出 @xuecat 的about页面 那样，不知道两位有没有什么意见呢？谢谢

**Comment by xuecat** [comment]
是的，我about页面确实是新建的，记录：https://xuecat.github.io/2016/08/29/177/

ehlxr的图片用的是gh属性，这个属性我也记录了，你可以看下。

**Comment by xuecat** [comment]
新建页面加个layout:post，再使用photos就好了。这是我的做法，现在我都用gh和img了，不想折腾了。
这篇文章第四点有误：可以直接用 ````` 来代替

**Comment by xuecat** [comment]
是gp不是gh

**Comment by monster-gump** [comment]
@xuecat 不好意思, 我看了一下你的这个记录，还是没有太明白是怎么回事
请问你是否方便发一下你 about 的原 md 文件给我看看呢？以及你 about 那一页是怎么链接去对应的博文上的呢？
比如你说
> ‘% gp 5-3 %’ //这里去掉了大括号改成引号，因为hexo老是去解析它
> //这句里，图片数必须超过2，不然就显示错误。就算只有俩个图源，也没关系，可以正常显示。
这个地方改成引号我感觉 hexo 就会报错
但是不改之后 里面用 
```html
{% gp 3-3 %}
<img src="fake1.png">
<img src="fake2.png">
{% endgp %}
```
的形式时，实际上不能达到并排的效果，还请指教一二 谢谢

**Comment by xuecat** [comment]
。。。。。。。。
。。。。。
你想啥呢！！！！！！

加图方式：
1、像我的about页面那种。直接改about模板
```
title: Naruto-Pictures
categories: [图片]
tags: [picture,naruto]
date: 2016-09-02 14:36:04
layout: post
photos: 
- ./picture/1.png
- ./picture/2.png
```

2. 像ehlxr那种显示方式。
{% gp 3-3 %}
![](http://oapjp6spr.bkt.clouddn.com/18210.jpg)
![](http://oapjp6spr.bkt.clouddn.com/18210.jpg)
{% endgp %}

3. 使用html方式
<img src="http://oapjp6spr.bkt.clouddn.com/18210.jpg">

别人的博客、官方文档都没看清就乱问。你有努力吗？

**Comment by monster-gump** [comment]
@xuecat 
sorry，因为你给的和他的网站我都看了，官方文档我也看过了都不 work，所以才想说直接看看你是怎么写的，然后对比一下我写的究竟有什么问题。（毕竟我觉得你 about 里面的内容在博客都能直接看到，那这个也就不涉及 privacy 什么的了吧）

我只是觉得这样比较方便，唐突了不好意思。
感谢耐心回答，谢谢。

**Comment by xuecat** [comment]
@monster-gump 
没事，如果还是不成功。那就等我晚上回去了才能给你发我的配置文件。

**Comment by jarvan4dev** [comment]
@xuecat 我成功了，但是我想问下能不能把他做成动态的？

**Comment by xuecat** [comment]
@jarvan4dev  啥动态的？gif？
那直接加gif文件就行了，它是支持gif的。

如果你想图片布局动态变化的话，我能力有限，你就可以求作者或者自己改。

hexo官方网站倒是有好几个可以随意换图片布局的模板。只是你要翻墙才能看到。

**Comment by jarvan4dev** [comment]
@xuecat  另外我想问下
```
---
type: "gallery"
keywords: picture,naruto
layout: post
photos: 
- http://oapjp6spr.bkt.clouddn.com/18210.jpg
- http://oapjp6spr.bkt.clouddn.com/196232.jpg
- http://oapjp6spr.bkt.clouddn.com/224147.jpg
- http://oapjp6spr.bkt.clouddn.com/199301.jpg
- http://oapjp6spr.bkt.clouddn.com/213318.jpg
- http://oapjp6spr.bkt.clouddn.com/18210.jpg
- http://oapjp6spr.bkt.clouddn.com/196232.jpg
- http://oapjp6spr.bkt.clouddn.com/224147.jpg
- http://oapjp6spr.bkt.clouddn.com/199301.jpg
---
```

这样似乎不能给fancybox加title，图片下面也没有title，不知道能不能加

**Comment by xuecat** [comment]
这个你要问作者，作者多图一直感觉没做好似的！！！     反正上面无论哪种模式，都有鸡肋般的存在！！！！反正我是坐等他更新。

**Comment by ehlxr** [comment]
进入页面后显示效果丢失的问题已经解决了，效果参考 http://ehlxr.me/2016/09/02/Naruto-Pictures/
修复方法参考 http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#八、图片模式
8.3 修复图片展示

**Comment by xuecat** [comment]
@ehlxr  啧啧，这个可以有。。

**Comment by ivan-nginx** [comment]
@xuecat dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by ming71** [comment]
> @xuecat 另外我想问下
> 
> ```
> ---
> type: "gallery"
> keywords: picture,naruto
> layout: post
> photos: 
> - http://oapjp6spr.bkt.clouddn.com/18210.jpg
> - http://oapjp6spr.bkt.clouddn.com/196232.jpg
> - http://oapjp6spr.bkt.clouddn.com/224147.jpg
> - http://oapjp6spr.bkt.clouddn.com/199301.jpg
> - http://oapjp6spr.bkt.clouddn.com/213318.jpg
> - http://oapjp6spr.bkt.clouddn.com/18210.jpg
> - http://oapjp6spr.bkt.clouddn.com/196232.jpg
> - http://oapjp6spr.bkt.clouddn.com/224147.jpg
> - http://oapjp6spr.bkt.clouddn.com/199301.jpg
> ---
> ```
> 
> 这样似乎不能给fancybox加title，图片下面也没有title，不知道能不能加

请问您解决了吗？怎样加上title啊?
