### ISSUE TITLE
为何swiftype搜索只是个按钮，而不是编辑框？

### ISSUE THREAD

**Issue by xuecat** [iissnan/hexo-theme-next#1087]
### Expected behavior (预期行为)

如题，我添加swiftype的key后就发现搜索框一直是个按钮，没有编辑框。无论我在swiftype上面如何修改 “search field”那项都无法。求教！！！

**Comment by wuxubj** [comment]
参考[添加swiftype搜索并自定义搜索框](http://www.wuxubj.cn/2016/05/Hexo-build-personal-blog-advance/#添加swiftype搜索并自定义搜索框)

**Comment by xuecat** [comment]
@wuxubj  啊啊！！居然有人回复我！！！！！ありがとう、感謝に堪えない

**Comment by xuecat** [comment]
@wuxubj  骗子，，不行！我代码都一个一个确认了！！我的感情还来！！！。

**Comment by xuecat** [comment]
@wuxubj  我看了下，好像是我menu太多了，掩盖了搜索框。搜索框如何右移？

**Comment by wenthywang** [comment]
Switftype  好像用不了了现在 在官网都没有爬出内容

**Comment by geekrainy** [comment]
Swiftype 已改为付费使用。

**Comment by ivan-nginx** [comment]
@xuecat dont understand u, write in English if not solved. If solved, close it please. Thank's!
