### ISSUE TITLE
多说分享有个小bug

### ISSUE THREAD

**Issue by wuxubj** [iissnan/hexo-theme-next#1089]
### Actual behavior (实际行为)
多说分享点击“分享到”会出现“缺少service参数”
下拉分享按钮有些是undefined
演示：[http://notes.iissnan.com](http://notes.iissnan.com/2016/publishing-github-pages-with-travis-ci/)

### 建议
在 duoshuo.swig 中引用多说开发版js ：embed.unstable.js
多说官网使用的是开发版的js，稳定版估计没人维护了
修改后的[ duoshuo.swig](https://github.com/wuxubj/hexo-theme-next/commit/96c2d5d9938fb233d9a64292e0f729b446c1af0f)
修改后的效果参见[多说官方博客](http://dev.duoshuo.com/threads/549a781ff07c81f20daba426)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔-  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  ✔-  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
开发版会导致 评论 UA 功能失效
