### ISSUE TITLE
侧边栏的分类和标签无法跳转

### ISSUE THREAD

**Issue by askingwindy** [iissnan/hexo-theme-next#109]
您好，侧边栏的分类和标签有时无法跳转，但是menu的标签和分类并没有问题

**Comment by askingwindy** [comment]
刚刚发现，如果把menu里的#tags注释掉，那么侧边栏的tags就没法跳转
categories同理

**Comment by iissnan** [comment]
嗯，是的。

是这样考虑的，因为 tags 和 categories 并不是 Hexo 内建支持的，所以在主题内只能根据是否在 menu 中开启了 tags/categories 页面来判断是否需要加链接。
如果 menu 中没有启用 tags/categories，这时候的链接可能是无效的，侧栏的展示就变成纯粹的数据统计展示。

**Comment by eurusd** [comment]
手机浏览 四个页面 不会乱    能否支持5个面页?

**Comment by iissnan** [comment]
如果菜单超过四个 item，估计要考虑做成收缩式菜单。
