### ISSUE TITLE
随机化的一些问题

### ISSUE THREAD

**Issue by pinkomeo** [iissnan/hexo-theme-next#1094]
求大神帮忙解决一些随机化的问题
1.比如说 上面的banner 现在是灰色的背景
如果我想每次加载的时候随机一张图片背景怎么办捏？

2.比如说现在在config里面有一个变量 调用的时候是{{theme.XXX}}这种
但如果我想随机显示呢？就是XXX我给一个数组 每次随机选一个

实现我说的这个是不是要学ruby语言啊= =

**Comment by iissnan** [comment]
用 JavaScript 就可以
