### ISSUE TITLE
如何在主页点击标题直接跳转新的地址

### ISSUE THREAD

**Issue by kangseven7** [iissnan/hexo-theme-next#1095]
问题是这样的
比如我想转载一篇别人的文章，我hexo new “test”，什么都不写，就只有一个自动生成的标题（test）。怎么样才能在我的首页点击标题（test）就直接跳转到别人的文章地址？

**Comment by ivan-nginx** [comment]
@kangseven7 dont understand u, write in English if not solved. If solved, close it please. Thank's!
