### ISSUE TITLE
多说评论不显示

### ISSUE THREAD

**Issue by SawyerSun** [iissnan/hexo-theme-next#1097]
### Expected behavior (预期行为)

显示多说评论
### Actual behavior (实际行为)

不现实多说评论，div为空
### Steps to reproduce the behavior (重现步骤)

无
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master  ✔ 
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces  ✔ 
### Other Informations (Like Browser, System, Screenshots)

![12](https://cloud.githubusercontent.com/assets/13533065/18193924/c409bdca-7114-11e6-9fd6-143a174f6769.png)
该div元素为空。
![13](https://cloud.githubusercontent.com/assets/13533065/18193952/e6dff314-7114-11e6-8bf7-7ca424847351.png)
网页源码中相关js，最后getElementById选择元素都为footer。
而多说官网为head和body。
![14](https://cloud.githubusercontent.com/assets/13533065/18193997/315319bc-7115-11e6-8e14-28f1efcc180e.png)

**Comment by SawyerSun** [comment]
修改模板中js后，问题解决。
![144](https://cloud.githubusercontent.com/assets/13533065/18194246/e635c270-7116-11e6-9f88-35045073d0b5.png)

**Comment by ivan-nginx** [comment]
@SawyerSun dont understand u, write in English if not solved. If solved, close it please. Thank's!
