### ISSUE TITLE
无法生成tag页面

### ISSUE THREAD

**Issue by sgoal** [iissnan/hexo-theme-next#110]
我总共有4个tag，public/tag目录下生成了4个子文件夹,但是tag/index.html上没有相关显示。

**Comment by iissnan** [comment]
需要手动建立一个 tags 页面，见：[Wiki - 创建标签云页面](https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E6%A0%87%E7%AD%BE%E4%BA%91%E9%A1%B5%E9%9D%A2)

**Comment by sgoal** [comment]
好的，谢谢~我自己搞错了~
对了~我的关于没有多说的评论框，其他的有。这正常吗？

**Comment by iissnan** [comment]
正常的

**Comment by sgoal** [comment]
慷慨解答，谢谢~
