### ISSUE TITLE
需求：希望可以自定义代码高亮引擎

### ISSUE THREAD

**Issue by ChuanleiGuo** [iissnan/hexo-theme-next#1100]
## 问题：Next现在使用的代码高亮的引擎对Swift的支持很差，只能高亮部分变量声明的代码。

<img width="667" alt="screen shot 2016-09-02 at 18 15 43" src="https://cloud.githubusercontent.com/assets/5415054/18200831/57949136-7139-11e6-82c8-69eeb49767f5.png">
<img width="669" alt="screen shot 2016-09-02 at 18 16 01" src="https://cloud.githubusercontent.com/assets/5415054/18200834/58aada9e-7139-11e6-976b-174ee74fb55b.png">

效果见上图。

**Comment by xovel** [comment]
自定义高亮代码可自行配置`marked`的高亮函数：`options.highlight`

~~貌似next主题是支持highlight.js的，对swift支持不太友好这锅是highlight.js的~~
