### ISSUE TITLE
主页标签好像不能调到https 现在http不能范围

### ISSUE THREAD

**Issue by gnaixx** [iissnan/hexo-theme-next#1101]
主页标签好像不能调到https 现在http不能范围

**Comment by ForgetAll** [comment]
+1  不知道这是不是浏览器的问题，跳转标签页面不补全https的话是不能访问的，有解决的方法吗。

**Comment by li-haoran** [comment]
+1 跳转标签页面不补全https的话是不能访问的，有解决的方法吗。

**Comment by gnaix92** [comment]
```bash
menu:
  home: /
  categories: https://gnaix92.github.io/categories/
  archives: https://gnaix92.github.io/archives/
  tags: https://gnaix92.github.io/tags/
```

我目前的解决办法倒是可以，就是在主题的配置中 把连接地址补全

**Comment by ForgetAll** [comment]
买了个域名，现在好像可以了……

**Comment by ivan-nginx** [comment]
@gnaixx dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by gnaixx** [comment]
this issue is solved
