### ISSUE TITLE
如何实现分类的多级显示

### ISSUE THREAD

**Issue by SiriusHsh** [iissnan/hexo-theme-next#1102]
点击"分类"后，页面里呈现出这种效果
![1](https://cloud.githubusercontent.com/assets/20510239/18223750/dc470a7a-71f3-11e6-8f87-fc00d4fde27f.png)
或者这种
![2](https://cloud.githubusercontent.com/assets/20510239/18223751/df82cb02-71f3-11e6-815b-f9f94a876a28.png)
请问能够实现吗？

**Comment by ThinerZQ** [comment]
同问，这种需求

**Comment by nolongerwait** [comment]
这个在当前模块下应该无法实现吧，因为侧边栏目录是静态配置。。。。想要强行达到这种效果估计得自己写样式了。。。。（我也在折腾这个二级目录。

**Comment by sunshineLing** [comment]
同求，感觉现在这样有点杂乱。

**Comment by ivan-nginx** [comment]
@SiriusHsh dont understand u, write in English if not solved. If solved, close it please. Thank's!
