### ISSUE TITLE
代码过长无法自动换行

### ISSUE THREAD

**Issue by fengguoqing** [iissnan/hexo-theme-next#1105]
### Expected behavior (预期行为)

当一行代码超过页面显示长度以后可以自动换行。
### Actual behavior (实际行为)

当一行代码超过页面显示长度以后不会换行，而是出现横向的滚动条。
![image](https://cloud.githubusercontent.com/assets/2252432/18231524/2ba482f0-72ee-11e6-994a-5d364d11ddfa.png)
### Steps to reproduce the behavior (重现步骤)

在文章中写入以下内容

``` C
static struct sock_diag_handler *sock_diag_handlers[AF_MAX];  //可以看出,这个指针数组最大为AF_MAX AF_MAX = 40.
```
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  ✔Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-   ✔Pisces

**Comment by whynotyes** [comment]
同求 解决方案，滚动条看着实在难受

**Comment by flaski** [comment]
我也想知道

**Comment by aixiu** [comment]
同求方案。。

**Comment by xovel** [comment]
... 代码块本身的处理方式就是这个样子。如果需要自动换行，可以自行修改代码的css样式。

`white-space: normal;` 

~~这样子操作会使得某些代码高亮工具的行号发生错乱~~

**Comment by wangerniu** [comment]
可以自动修改换行但是觉得这个应该放到官方文件中比较好。

**Comment by ehlxr** [comment]
希望 @iissnan 能够瞧瞧，帮忙实现一下代码换行

**Comment by ivan-nginx** [comment]
@fengguoqing dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by maoshengyang** [comment]
@fengguoqing 嗨，您有找到什么解决方案了吗？谢谢您！我也被这个问题困扰了很久呢~

**Comment by fengguoqing** [comment]
@maoshengyang 上面说到的修改CSS样式你可以试试。
`white-space: normal;`

**Comment by ivan-nginx** [comment]
> 这样子操作会使得某些代码高亮工具的行号发生错乱
That's right! Are u crazy, guys? This is code, code always copy from blog and paste into console, for example. And if it will be line breaking, code will not work. This is too easy to do. This will have nice appearance, yeas, but this is will kicked out your users from your blogs after copying this code by they. Just think about it, what is better: beauty or stability?

**Comment by maoshengyang** [comment]
@ivan-nginx Understand. Also with 'white-space: normal' in line style directly will cancel the line indention indeed. I may try to give up my proposals. Thanks a lot!

**Comment by zhuzhuyule** [comment]
you can see this style, create a scroll that folat in code area bottom always !

open this [blog](http://zhuzhuyule.xyz/2017/09/05/skill/jqGrid%E4%B8%ADJson%E7%9A%84%E8%A7%A3%E6%9E%90/), then **double click** `second  code` block and scroll change !

**Comment by ivan-nginx** [comment]
@zhuzhuyule wow! This is pretty close to fix this problem. Can u do pull with this feature?

**Comment by zhuzhuyule** [comment]
@ivan-nginx  OK, wait me to sort out !

**Comment by maoshengyang** [comment]
@zhuzhuyule 
非常美观！！！
但是我按照您的blog中“HEXO下的语法高亮拓展修改”的文章进行修改之后发现并没有达到您博客中的效果。如图所示，可以正确加入代码的标题，但是行号和代码分别占用了一整行。
<img width="626" alt="2017-11-25 11 54 26" src="https://user-images.githubusercontent.com/24741375/33227126-6fca0fe2-d1d7-11e7-9629-d00c0e524acc.png">
以下是我生成的代码

```
<figure class="highlight python">
  <figcaption><span class="caption">Python code</span></figcaption>
  <div class="figcode">
    <div class="gutter">
      <pre>
        <div class="line">1</div>
        <div class="line">2</div>
        <div class="line">3</div>
        <div class="line">4</div>
        <div class="line">5</div>
      </pre>
    </div>
    <div class="code">
      <pre>
        <div class="line"><span class="keyword">import</span> numpy <span class="keyword">as</span> np</div>
        <div class="line"><span class="keyword">import</span> keras</div>
        <div class="line">...</div>
        <div class="line"><span class="keyword">import</span> keras.backend <span class="keyword">as</span> K  <span class="comment"># backend is Tensorflow</span></div>
        <div class="line">K.set_image_data_format(<span class="string">'channels_last'</span>)</div>
      </pre>
    </div>
  </div>
</figure>
```

我查看了以下您博客中代码段的html代码和这个应该是一样的，但是显示出来的效果完全不一样。我是不是漏掉了什么东西呀！最近刚开始搞自己的博客，问的问题比较傻，见谅哈！

**Comment by maoshengyang** [comment]
@zhuzhuyule
原来的代码是生成了一个一行两列的<table>。但是看更新的代码是生成了两个<div>，然后两个<div>分别占据了一整行的空间。

**Comment by zhuzhuyule** [comment]
@maoshengyang 样式没有引用进来。

不要意思，'[HEXO下的语法高亮拓展修改](http://zhuzhuyule.xyz/2017/09/09/HEXO/HEXO%E4%B8%8B%E7%9A%84%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE%E6%8B%93%E5%B1%95%E4%BF%AE%E6%94%B9/)'教程一步，需要在  `.\themes\next\source\css\_custom\highlight.styl` 中添加
```
@import highlight;
```

**Comment by maoshengyang** [comment]
@zhuzhuyule 感谢！我也发现了需要import这个样式。

我看了您的blog，文章中的code block非常酷炫。我按照您的方法实现到了如下图的程度：可以加标题，底部有固定的scrollbar等等。

<img width="636" alt="2017-11-25 5 02 28" src="https://user-images.githubusercontent.com/24741375/33229066-8cf9b038-d202-11e7-87bf-a5474d34d339.png">

我注意到您的博客中，将鼠标移到code block中时，这个block可以自动变长，把以前显示不完全的代码行显示完整。我觉得这个太漂亮了。能否教我一下实现这个功能啊。

另外我有下载你的repo，hexo-blog-modify。我有尝试把themes_modify/next下的layout，source和scripts复制合并到我的博客文件夹下，但是发现会改变我原有的一些排版。我只想要实现您博客中的code block的功能。

万分感谢啦！
