### ISSUE TITLE
打赏是否能支持给单独文章配置？

### ISSUE THREAD

**Issue by luxiaoming** [iissnan/hexo-theme-next#1107]
不是全部的都出现打赏功能，这个怎么做呢？

**Comment by wenthywang** [comment]
选择性？

**Comment by wenthywang** [comment]
可以在打赏的模板reward. swig  进行修改 在post里添加属性

**Comment by luxiaoming** [comment]
多谢回复。我看下去。这个刚接触，学习中。

**Comment by kulley** [comment]
你可以修改 `layout/post.swig` 中的
```
      <div>
        {% if not is_index %}
          {% include 'reward.swig' %}
        {% endif %}
      </div>
```
为
```
    {% if post.reward %}
      <div>
        {% if not is_index %}
          {% include 'reward.swig' %}
        {% endif %}
      </div>
    {% endif %}
```

这样在文章的头部加上 `reward: true` 便能对单个文章开启打赏功能

**Comment by ivan-nginx** [comment]
@luxiaoming dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by JewSaten** [comment]
修改主题下的layout/_macro的 reward.swig

{% if page.reward %}
{% if theme.alipay or theme.wechatpay %}
  <div style="padding: 10px 0; margin: 20px auto; width: 90%; text-align: center;">
    <div>{{ theme.reward_comment }}</div>
    <button id="rewardButton" disable="enable" onclick="var qr = document.getElementById('QR'); if (qr.style.display === 'none') {qr.style.display='block';} else {qr.style.display='none'}">
      <span>赏</span>
    </button>
    <div id="QR" style="display: none;">
      {% if theme.wechatpay %}
        <div id="wechat" style="display: inline-block">
          <img id="wechat_qr" src="{{ theme.wechatpay }}" alt="{{ theme.author }} WeChat Pay"/>
          <p>微信打赏</p>
        </div>
      {% endif %}
      {% if theme.alipay %}
        <div id="alipay" style="display: inline-block">
          <img id="alipay_qr" src="{{ theme.alipay }}" alt="{{ theme.author }} Alipay"/>
          <p>支付宝打赏</p>
        </div>
      {% endif %}
    </div>
  </div>
{% endif %}
{% endif %}
post文章里面添加是否开启打赏
开启
---
title: 打赏
reward: true
---

关闭
---
title: 打赏
---

**Comment by ivan-nginx** [comment]
#1697 (PART 5. Refactor wechat, reward and copyright features & added bitcoin donate.).
