### ISSUE TITLE
文章目录样式

### ISSUE THREAD

**Issue by axu4github** [iissnan/hexo-theme-next#1108]
感谢为我们带来这么优秀的主题
我在看你的官方文档中，发现很多优秀的设计:
1. 在"开始章节"中，对于"引用"的使用（最左侧）是可以分颜色的，比如有"蓝，绿，黄，红"等。
2. 在"开始章节"中，对于"主题配置文件"，“站点配置文件”，“5.0.0”等字，都是可以有带颜色的方框框起来的。
3. 整体的文章目录样式（个人觉得在主题中的文章目录样式有点死板）。
对于这些优秀的设计，可以把它们扩展到你的主题中么，或者可以写一遍如何扩展主题样式的教程。
再次感谢。

**Comment by ivan-nginx** [comment]
@axu4github dont understand u, write in English if not solved. If solved, close it please. Thank's!
