### ISSUE TITLE
设置社交页面后主页和其他部分页面显示会变成空白

### ISSUE THREAD

**Issue by AaronZJP** [iissnan/hexo-theme-next#1111]
### Expected behavior (预期行为)

正常显示
### Actual behavior (实际行为)

无法正常显示，显示为空白
### Steps to reproduce the behavior (重现步骤)

修改主题配置如下
# Social Links
# Key is the link label showing to end users.
# Value is the target link (E.g. GitHub: https://github.com/iissnan)

social:
   GitHub: https://**********
   Weibo: http://************
# Social Links Icons
# Icon Mapping:
# Map a menu item to a specific FontAwesome icon name.
# Key is the name of the item and value is the name of FontAwsome icon. Key is case-senstive.
# When an globe mask icon presenting up means that the item has no mapping icon.

social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocalItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  # Twitter: twitter
  Weibo: weibo
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master 
-  Latest Release  ✔
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces  ✔
### Other Informations (Like Browser, System, Screenshots)

还有个问题就是我设置了代码高亮 但是在网页上没有任何代码高亮。希望能说下原因。指正一下

**Comment by ivan-nginx** [comment]
@AaronZJP dont understand u, write in English if not solved. If solved, close it please. Thank's!
