### ISSUE TITLE
标题自动编号

### ISSUE THREAD

**Issue by maxchendt** [iissnan/hexo-theme-next#1112]
正在学习写博客，请问如何实现自动编号，例如 https://maxchendt.github.io/2016/09/02/instHexo/   采用 https://github.com/3meng/3meng.github.io/issues/1 的方法，在 landscape theme 下实现了。

在 next 主题中，请问 如何实现？

**Comment by maxchendt** [comment]
昨天晚上好好睡了一个晚上，早上继续看代码，虽然半懂不懂的
先google, 发现 https://stackoverflow.com/questions/6341191 提示要先导入 `jquery.min.js` ， 在生成的 html 代码中，找 `jquery`， 发现 如下行

    <script type="text/javascript" src="/vendors/jquery/index.js?v=2.1.3"></script>

嗯，对比 https://developers.google.com/speed/libraries/ 感觉就是了，只是这里不是用托管在 ajax.googleapis.com  上的

    grep -R --include="*.swig" 'index.js' ./themes/next

发现在 ./themes/next/layout/_scripts/vendors.swig 中，因此，在该文件的最后加入
```
<script type="text/javascript">
$(document).ready(function(){
  var $article = $(".post-body");
  var count = [0, 0, 0, 0, 0, 0];
  var mark = [0, 0, 0, 0, 0, 0];

  (function setMark(){
    var hTag = ["h1", "h2", "h3", "h4", "h5", "h6"];
    var index = 0;
    for (var i = 0; i < 6; ++i) {
      if ($article.children(hTag[i]).length > 0) {
        ++index;
        mark[i] = index;
      }
    }
  })();

  $article.children(":header").each(function(){
    var t = $(this);
    var pos = 0;
    switch (t[0].tagName) {
      case "H1": pos = 0; break;
      case "H2": pos = 1; break;
      case "H3": pos = 2; break;
      case "H4": pos = 3; break;
      case "H5": pos = 4; break;
      case "H6": pos = 5; break;
    }

    var len = mark[pos];
    if (len < 6) { count[len] = 0; }
    count[len - 1]++;

    var listStr = count[0] + "";
    for (var i = 1; i < len; ++i) { listStr += "." + count[i]; }
    listStr += " ";
    t.html(listStr + t.html());
  });
});
</script>
```
注意 `var $article = $(".post-body");` 要对应next主题使用的 `post-body` 对象

**Comment by sanyucz** [comment]
能否问下，您最后是怎么解决代码块之后的行不自动缩进的呢？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
