### ISSUE TITLE
站内搜索的search.xml文件总出现编码错误，配置文件没问题。

### ISSUE THREAD

**Issue by vinoZHU** [iissnan/hexo-theme-next#1115]
### Actual behavior (实际行为)

```
This page contains the following errors:

error on line 9 at column 37: Input is not proper UTF-8, indicate encoding !
Bytes: 0x10 0x3C 0x63 0x6F
Below is a rendering of the page up to the first error.
```
### Steps to reproduce the behavior (重现步骤)

http://vinoit.me/search.xml
### NexT Informations

NexT Version:
- 5.0.1

NexT Scheme:
-  Mist
### Other Informations (Like Browser, System, Screenshots)

上次通过定位到文章的具体行，然后重新编辑文章，才搞定了这个错误。这次新写了一篇文章，又出现了这个问题。

**Comment by flashlab** [comment]
修改generator插件去掉所有html标记试试

**Comment by vinoZHU** [comment]
`generator.js`和`search.ejs`这两个吗？该如何修改@flashlab ,求教。

**Comment by Neveryu** [comment]
https://neveryu.github.io/guestbook/
编码和文件开头都要设置

**Comment by Neveryu** [comment]
ds.charset = 'UTF-8';
加上就好了，不懂可以问我
https://neveryu.github.io/guestbook/

**Comment by vinoZHU** [comment]
`ds.charset = 'UTF-8';`这句加在哪里?@Neveryu

**Comment by ivan-nginx** [comment]
@vinoZHU dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by vinoZHU** [comment]
@ivan-nginx  I'm sorry for forgetting to close it.

**Comment by ivan-nginx** [comment]
Don't worry, i'll fix this soon. =)

**Comment by vinoZHU** [comment]
@ivan-nginx Thank's!

**Comment by MuYunyun** [comment]
@vinoZHU @Neveryu 请教博主是如何解决这个问题的呢？我遇到了和您描述一样的情况 [demo](http://muyunyun.cn/search.xml)
```js
This page contains the following errors:
error on line 53 at column 35: Input is not proper UTF-8, indicate encoding !
Bytes: 0x08 0x50 0x79 0x74
Below is a rendering of the page up to the first error.
```

**Comment by cq674350529** [comment]
Recently, I have came across the same problem. Where should I add the `ds.charset = 'UTF-8'`?  @vinoZHU @Neveryu @MuYunyun 
Thanks in advance!

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
