### ISSUE TITLE
mac下无问题，travis-ci报ERROR Asset render failed

### ISSUE THREAD

**Issue by zzgo** [iissnan/hexo-theme-next#1116]
### Expected behavior (预期行为)

预期应该成功渲染
### Actual behavior (实际行为)
```
$ hexo generate
INFO  Start processing
INFO  Files loaded in 1.12 s
ERROR Asset render failed: css/main.css
TypeError: /home/travis/build/zzgo/zzgo.github.io/themes/next/source/css/main.styl:45:26
   41| 
   42| 
   43| // Custom Layer
   44| // --------------------------------------------------
   45| @import "_custom/custom";
--------------------------------^
Path must be a string. Received undefined
````
### Steps to reproduce the behavior (重现步骤)

下面CI的记录虽然是pass，但是在可以看到渲染时候有问题。
找了一下资料，也没有看到对症的问题。从报错来看，是字符串格式的问题？

https://travis-ci.org/zzgo/zzgo.github.io

### NexT Informations

我在自己Mac的环境没有问题的，很好用。
但是在travis-ci下，就出问题了。

NexT Version:
  -  Latest Release

NexT Scheme:
  -  Mist

**Comment by zzgo** [comment]
已解决，是hexo设置问题。非next问题

**Comment by LABELNET** [comment]
@zzgo  怎么解决的 ，我的ubuntu下没问题，其他主题没问题，使用next主题，出错，没内容生成！

**Comment by zzgo** [comment]
我是在Travis-CI改了一下hexo的版本。你hexo生成的时候，有什么报错吗

**Comment by LABELNET** [comment]
修改为next主题后，没有出错，内容没生成! 可以帮忙看下这个有问题不？
[https://github.com/LABELNET/blog/blob/master/_config.yml](https://github.com/LABELNET/blog/blob/master/_config.yml)

**Comment by LABELNET** [comment]
好像知道了 ， next 主题文件打不开

**Comment by zzgo** [comment]
刚刚看了一下，这里要注意除了默认的theme，其他的theme其实是一个链接。。你得把next主题作为一个submodule，用git来初始化并管理更新
