### ISSUE TITLE
多说评论框同时出现两个！

### ISSUE THREAD

**Issue by Zaynex** [iissnan/hexo-theme-next#1118]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/13745971/18415823/6a9aca0c-7832-11e6-9f7c-10f3d0ab2c06.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/13745971/18415817/2e88ba06-7832-11e6-8b19-3de9b38148af.png)
![image](https://cloud.githubusercontent.com/assets/13745971/18415821/519c0cd2-7832-11e6-9b22-690bd1f5888a.png)

### Steps to reproduce the behavior (重现步骤)
1.在站点文件配置自己的 duoshuo_name
2.在themes/next/layout/_partials/comments.swig
中代码如下
```
{% if page.comments %}
 <div class="comments" id="comments">
   <div class="ds-thread" data-thread-key="{{ page.path }}"
           data-title="{{ page.title }}" data-url="{{ page.permalink }}">
      </div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"zaynex"};
  (function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] 
     || document.getElementsByTagName('body')[0]).appendChild(ds);
  })();
  </script>
  </div>

{% endif %}
```

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master

NexT Scheme:
  -  Mist

**Comment by Neveryu** [comment]
https://neveryu.github.io/guestbook/
帮你弄成这样可以吗

**Comment by Zaynex** [comment]
很不错，不过我还是希望有评论功能，不然被别人发现博客有错误也难改正了

**Comment by iissnan** [comment]
配置 `duoshuo_shortname` 就可以了，模板不用改
