### ISSUE TITLE
webfont加载缓慢，怎么解决

### ISSUE THREAD

**Issue by hjrhclan** [iissnan/hexo-theme-next#1120]
### NexT Informations

NexT Version:

 ✔  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
 ✔  -  Pisces

**Comment by Neveryu** [comment]
https://neveryu.github.io/guestbook/

使用CDN，很快的

**Comment by hjrhclan** [comment]
@Neveryu 怎么使用CDN呢？

**Comment by iissnan** [comment]
http://theme-next.iissnan.com/advanced-settings.html

给 `fontawesome` 设置 CDN 地址即可
