### ISSUE TITLE
怎么隐藏让侧边栏的“3 \r\n 日志”，因为这个功能本身就在archive包含了

### ISSUE THREAD

**Issue by LionWY** [iissnan/hexo-theme-next#1121]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by Neveryu** [comment]
https://neveryu.github.io/guestbook/
去掉Spring

**Comment by LionWY** [comment]
spring 在哪个文件里面？

**Comment by ivan-nginx** [comment]
@LionWY dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by RocStone** [comment]
@ivan-nginx 
let me be the transistor
He think he already have the archive on the top bar, so he want to hide the archive at sidebar.
I think you didn't make thing function yet.
Still I think you are very friendly and nice and smart, wish you happy and keep being lucky.

**Comment by ivan-nginx** [comment]
@RocStone still don't und what u meaning..

**Comment by RocStone** [comment]
@ivan-nginx 
![image](https://user-images.githubusercontent.com/13502763/34947183-57d74324-fa44-11e7-9d56-99b94392582d.png)
One and Two come to the same page, he want to remove the Two for concisen

**Comment by ivan-nginx** [comment]
@RocStone @LionWY already was implemented in [NexT 6.0.1](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.1) and detailed in [this issue](https://github.com/theme-next/hexo-theme-next/issues/8) (`site_state: false` option).
