### ISSUE TITLE
k

### ISSUE THREAD

**Issue by Neveryu** [iissnan/hexo-theme-next#1122]

**Comment by snovey** [comment]
请配置一台反向代理服务器。
像这样：[反向代理 GitHub Pages 并配置博客 HTTPS 访问](https://imciel.com/2016/05/09/github-pages-reverse-proxy-https/)

**Comment by Neveryu** [comment]
可是我没有服务器啊 。。。

**Comment by snovey** [comment]
尝试下 Cloudflare 或者 GitLab

**Comment by djyde** [comment]
本 issue 和 theme 无关

**Comment by snovey** [comment]
close it
