### ISSUE TITLE
没有页面跳转方式的配置项，非顶级域名直接本标签页跳转，这不是预期的

### ISSUE THREAD

**Issue by lovesasha** [iissnan/hexo-theme-next#1123]
### Expected behavior (预期行为)

新标签页打开链接
### Actual behavior (实际行为)

本标签页进行跳转
### Steps to reproduce the behavior (重现步骤)

markdown写的链接，非顶级域名直接在本标签页跳转，顶级域名会在新窗口打开，这好像是Hexo的默认行为，希望增加如yilia的open_in_new配置项
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
✔  -  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by xovel** [comment]
本来就有配置项：

```yml
external_link: true # Open external links in new tab
```

**Comment by ivan-nginx** [comment]
@lovesasha dont understand u, write in English if not solved. If solved, close it please. Thank's!
