### ISSUE TITLE
logo的字体不生效

### ISSUE THREAD

**Issue by SiriusHsh** [iissnan/hexo-theme-next#1124]
### Expected behavior (预期行为)

![03](https://cloud.githubusercontent.com/assets/20510239/18573838/fe344296-7bf9-11e6-8b27-26b9f87fc223.png)
在本地预览有效果
### Actual behavior (实际行为)

![02](https://cloud.githubusercontent.com/assets/20510239/18573849/0c172d2e-7bfa-11e6-9e4d-6e1fb45cc016.png)
发布到远程仓库里后就失效了
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  ✔ Pisces
### Other Informations (Like Browser, System, Screenshots)

```
  # 外链字体库地址 Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host: 
```

**没有设置字体外链**

```
  logo:
    external: true
    family: Lobster Two
    size: 24
```

**logo字体设置**

**Comment by iissnan** [comment]
执行 `hexo clean` 后重新部署试试

**Comment by magicKen** [comment]
执行`hexo clean`后可以生效。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
