### ISSUE TITLE
优化标题出现错误

### ISSUE THREAD

**Issue by dnf5320** [iissnan/hexo-theme-next#1125]
在 hexo/themes/hexo-theme-next/layout/ 修改 index.swig 文件
`{% block title %} {{ config.title }} {% endblock %}`
改为：
`{% block title %} {{ config.title }} - {{ theme.description }} {% endblock %}`

提交 git 后出现
Error: Block "title" defined more than once.
改回来后还是错误。

**Comment by aixiu** [comment]
`{% block title %} {{ config.title }} - {{ theme.description }}{% endblock %}`
试试这个。

**Comment by ivan-nginx** [comment]
@dnf5320 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by ivan-nginx** [comment]
```yml
# If true, will add site-subtitle to index page, added in main hexo config.
# subtitle: Subtitle
index_with_subtitle: true
```
