### ISSUE TITLE
字体设置中posts字号设置不生效

### ISSUE THREAD

**Issue by ly11tea** [iissnan/hexo-theme-next#1126]
### Expected behavior (预期行为)

设置posts标签下size后字体变大
### Actual behavior (实际行为)

字体不变
### Steps to reproduce the behavior (重现步骤)

  posts:
    external: true
    family: 
    size: 29
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master

NexT Scheme:

  ✔  Pisces
### Other Informations (Like Browser, System, Screenshots)

  logo:
    external: true
    family:
    size: 27
只有logo下的修改是生效的
![image](https://cloud.githubusercontent.com/assets/21007482/18582763/4e3cc53a-7c39-11e6-93cb-fbfbeb269410.png)

**Comment by chensifang** [comment]
尽快修复啊

**Comment by ivan-nginx** [comment]
@ly11tea dont understand u, write in English if not solved. If solved, close it please. Thank's!
