### ISSUE TITLE
行间距大得好难看 

### ISSUE THREAD

**Issue by chensifang** [iissnan/hexo-theme-next#1128]
行间距太大了, 不知道能修改吗?怎么改呢?

**Comment by Foair** [comment]
我也觉得行间距太大了，都已经超过标题到正文的距离了。

**Comment by dophin459** [comment]
在themes/next/source/css/_custom/custom.styl中增加以下代码：
```
p { margin: 0 0 10px 0; }
```
即可调整段间距。

**Comment by qzi** [comment]
> 行间距太大了, 不知道能修改吗?怎么改呢?

我发现现在的版本也是行间距大的很难看，但是这个方法已经不管用了

**Comment by llht** [comment]
@qzi 请问你解决了吗，我也发现了，代码块行间距很大，非常丑

**Comment by qzi** [comment]
> @qzi 请问你解决了吗，我也发现了，代码块行间距很大，非常丑

在 source/_data/styles.styl 添加css进行修改

我不是前端，我大概就是勉强改改CSS，你可以参考我的站点，https://leonvision.online

**Comment by llht** [comment]
> > @qzi 请问你解决了吗，我也发现了，代码块行间距很大，非常丑
> 
> 在 source/_data/styles.styl 添加css进行修改
> 
> 我不是前端，我大概就是勉强改改CSS，你可以参考我的站点，https://leonvision.online

@qzi 更改行间距参数吗，你看看我的这个代码块显示https://hantong.me/fat12-analysis/，大的一批

**Comment by qzi** [comment]
> > > @qzi 请问你解决了吗，我也发现了，代码块行间距很大，非常丑
> > 
> > 
> > 在 source/_data/styles.styl 添加css进行修改
> > 我不是前端，我大概就是勉强改改CSS，你可以参考我的站点，https://leonvision.online
> 
> @qzi 更改行间距参数吗，你看看我的这个代码块显示[https://hantong.me/fat12-analysis/，大的一批](https://hantong.me/fat12-analysis/%EF%BC%8C%E5%A4%A7%E7%9A%84%E4%B8%80%E6%89%B9)

真的大的尴尬，我看下你那个文章的代码块，好像是 tr#td#pre

我那个没你这个那么大

**Comment by llht** [comment]
@qzi 你说的source/_data是哪个文件夹下呀，我没有找到，打扰了

**Comment by qzi** [comment]
> @qzi 你说的source/_data是哪个文件夹下呀，我没有找到，打扰了

{HEXO_ROOT}/themes/theme_next/_config.yml 下面要解开这个 {HEXO_ROOT}/source/_data/styles.styl 的引用注释

**Comment by llht** [comment]
@qzi 感谢解答，我可以说我完全没找到吗，咱们的next版本是不是不太一样。。。。_config.yml有关style的内容看起来与要解决的东西完全不相关

**Comment by qzi** [comment]
> @qzi 感谢解答，我可以说我完全没找到吗，咱们的next版本是不是不太一样。。。。_config.yml有关style的内容看起来与要解决的东西完全不相关

自己创建，我的版本是hexo 4.1

**Comment by Eminem-x** [comment]
我将解决问题的办法 comment 在新仓库的 issue 下了，链接：https://github.com/theme-next/hexo-theme-next/issues/1703
