### ISSUE TITLE
default language

### ISSUE THREAD

**Issue by zsp1987** [iissnan/hexo-theme-next#113]
without setting in main _config, default language shows 繁体字.

**Comment by callmewhy** [comment]
https://github.com/iissnan/hexo-theme-next/issues/57

**Comment by callmewhy** [comment]
需要设置

    language: zh-Hans

**Comment by dereklin** [comment]
为什么我用了language: en-US， 还是看到 “ 首頁 ”。。。？ 我要怎么改才能看到“Home"...? 我想全用 英文。

**Comment by callmewhy** [comment]
在 languages 文件夹里有当前支持的语种。如果要用英文可以设为 default 。文件夹里的目录目前如下：

```
default
fr-FR
ru
zh-Hans
zh-hk
zh-tw
```


具体可以打开自己看，如果不能满足再手动调整即可：）

**Comment by dereklin** [comment]
谢谢了！

**Comment by zsp1987** [comment]
我觉得问题主要是:如果 _config.yml 的language 留空 应该默认应用Default模板.

**Comment by iissnan** [comment]
@zsp1987 `language` 留空默认应该是英文，也就是 default。但正如 #57 中提到的，Hexo 在选择语言时貌似有问题。

**Comment by zsp1987** [comment]
copy 了 default.yml 到 en.yml， 然后把language：设置成en解决了， 看起来的确是hexo不会默认选择default.yml
