### ISSUE TITLE
support related-popular-posts

### ISSUE THREAD

**Issue by gasolin** [iissnan/hexo-theme-next#1130]
### Expected behavior (预期行为)

Since next theme already have google analytics column, it will be great to support related-popular-posts
https://github.com/tea3/hexo-related-popular-posts
### NexT Informations

NexT Version:
-  Master ✔

NexT Scheme:
-  All schemes ✔

**Comment by viniciusarcanjo** [comment]
It'd be great! +1

**Comment by tea3** [comment]
@gasolin Thank you for introducing my plugin. 

Recently, content analysis has also been added. 

Unfortunately I can't support Chinese by lack of ability, but I am sincerely looking forward to all for kind cooperation.

**Comment by ivan-nginx** [comment]
@gasolin @viniciusarcanjo added in [NexT 6.0.4 release version](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.4).
