### ISSUE TITLE
两个问题求解答

### ISSUE THREAD

**Issue by poetries** [iissnan/hexo-theme-next#1131]
Theme  version: 0.4.5.2

1、首页站点底部的统计图标怎么显示出来

2、如何在每篇的文章页面增加打赏功能呢

**Comment by Neveryu** [comment]
这个还是比较好弄的，看这里：
https://neveryu.github.io/guestbook/

在主题的配置文件中添加
`reward_comment:打赏提示语`
打赏提示语，你可以自定义

**Comment by ivan-nginx** [comment]
@poetries https://github.com/iissnan/hexo-theme-next/issues/1130
