### ISSUE TITLE
向谷歌提交站点及 失败

### ISSUE THREAD

**Issue by Yodeser** [iissnan/hexo-theme-next#1132]
### Expected behavior (预期行为)
能够直接通过搜索引擎搜索到站点

### Actual behavior (实际行为)

![image](https://cloud.githubusercontent.com/assets/18223970/18607497/9d7476ee-7d00-11e6-9b66-f478f33e75aa.png)

NexT Version:
  -  Master

NexT Scheme:
  -  All schemes

### Other Informations (Like Browser, System, Screenshots)

我的站点已经建立一段时间了，然而不知为何谷歌和百度无法收录（只能采用dns服务商添加CNAME标记的方法通过验证）。很奇怪是什么原因，希望能够得到解决，谢谢。

**Comment by Yodeser** [comment]
# 二. 其次是站点地图提交问题

**Comment by Yodeser** [comment]
## - 问题背景
我的博客采用github（国外）+coding（国内）分流。域名解析采用DNSPOD，为方便解决问题，我愿意贴出我的解析记录。
![image](https://cloud.githubusercontent.com/assets/18223970/18607570/0838b826-7d03-11e6-810d-59d9e89ed5fe.png)

**Comment by Yodeser** [comment]
艾特几个露面比较多的朋友，如有打扰，请谅解。@wuxubj @耿玉坤 @franktly @tengj @ForgetAll

**Comment by ForgetAll** [comment]
之前向google提交自己的站是成功了，地图啥的还没弄过，再去看看- -

**Comment by Yodeser** [comment]
@ForgetAll 感谢你的回复，通过你的回复我结合自己的站点解析记录监控发现：由于是国内外分流，google貌似不知道为什么访问到的应该是我github pages对应的博客原文，因此我尝试着修改记录，使得国内外针对我域名的访问都转到coding。如图
![image](https://cloud.githubusercontent.com/assets/18223970/18607747/7f8dff9e-7d08-11e6-9638-c9b2dbbab46a.png)
结果刚刚一试果然就行了
![image](https://cloud.githubusercontent.com/assets/18223970/18607763/d7449bbc-7d08-11e6-8406-eb52ccb93226.png)
，可是这到底是什么原因呢？google为什么无法识别我放置github pages上的网页，这不是意味着国外IP访问我的博客时将无法访问。。。。那我这分流算是白做了

**Comment by Yodeser** [comment]
hah~真心谢谢各位，已经解决问题了。问题原因是我自己，不小心把pages的域名设置好，导致国外访问域名到404，真是抱歉，是我自己的问题，感谢各位的帮助。

**Comment by cylong1016** [comment]
我也遇到了这个问题，博客放在github上的，没有看懂你的解决办法，可以详细和我说一下么？感激不尽。我的[站点地图](http://www.cylong.com/sitemap.xml)

**Comment by Yodeser** [comment]
你好，我的原因是github pages 配置处未设置好绑定的域名，导致无法谷歌/百度无法获取到sitemap/baidusitemap文件。

2017-04-10 1:19 GMT+08:00 陈云龙 <notifications@github.com>:
