### ISSUE TITLE
Pisces主题下导航栏在mobile模式下打开会消失

### ISSUE THREAD

**Issue by clatisus** [iissnan/hexo-theme-next#1133]
google chrome浏览器未全屏时打开网站

![a](https://cloud.githubusercontent.com/assets/15963765/18615432/9d0efb82-7dd9-11e6-9082-c603fda5c468.png)

导航栏会消失

![b](https://cloud.githubusercontent.com/assets/15963765/18615436/ae082dc8-7dd9-11e6-97b5-b3b4e3db22de.png)

当浏览器全屏时重新加载则恢复正常
![c](https://cloud.githubusercontent.com/assets/15963765/18615439/b9debe46-7dd9-11e6-89ee-3b299d618ef0.png)

**Comment by Neveryu** [comment]
这个是响应式的问题，
也可以这样处理
https://neveryu.github.io/guestbook/

**Comment by clatisus** [comment]
@Neveryu 感谢你的回复，不过我没有太明白你的意思，这个问题没法解决吗？

**Comment by geekrainy** [comment]
为了适应小屏幕设备，默认当屏幕宽度小于992px时，将侧栏隐藏。

**Comment by ivan-nginx** [comment]
@clatisus https://github.com/iissnan/hexo-theme-next/issues/1130
