### ISSUE TITLE
Google Analytics无法正常使用，请修复

### ISSUE THREAD

**Issue by ArthurFree** [iissnan/hexo-theme-next#1134]
Google Analytics 跟踪代码已更新，当前默认是  ‘//www.google-analytics.com/analytics.js’

应修改为  'https://www.google-analytics.com/analytics.js'

修改之后可以正常使用

请更新，谢谢

**Comment by Neveryu** [comment]
请问这个是在哪里改，主题配置还是站点配置
https://neveryu.github.io/guestbook/

**Comment by ArthurFree** [comment]
在主题配置里

**Comment by maxchendt** [comment]
layout/_scripts/third-party/analytics/google-analytics.swig

**Comment by iissnan** [comment]
Fixed in #1430
