### ISSUE TITLE
需求：移动端不显示侧栏目录的时候，想在文章顶部显示目录，如何实现？

### ISSUE THREAD

**Issue by wuxubj** [iissnan/hexo-theme-next#1135]
### Expected behavior (预期行为)

移动端在文章顶部显示目录TOC
### Actual behavior (实际行为)

文章顶端无目录显示
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
- ✔   Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  ✔  All schemes
-  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

个人认为，一篇文章中目录还是比较重要的，所以希望能够在移动端文章顶部添加目录。请问如何实现？
目前的主要问题是，不知道如何获取文章目录，仿照`sidebar.swig`中的toc，没有成功获取文章目录，对 swig 相关语法不熟悉，不知道问题出在哪里。

**Comment by Neveryu** [comment]
移动端顶部有菜单栏，再来个目录，不知道是否还有空间，以及排版样式如何。。。
