### ISSUE TITLE
INDEX file has empty lines

### ISSUE THREAD

**Issue by mCapricornus** [iissnan/hexo-theme-next#1137]
So I configured Hexo and NexT theme, and after
``` bash
hexo g
```
All the generated index.html (like index.html, about/index.html and archives/2016/09/index.html) have strange empty lines inside, which is not expected.

>Visit [this site](https://github.com/mCapricornus/mcapricornus.github.io/blob/master/index.html) to see the content of my index.html file, with a lot of strange empty lines in it.

I don't know whether it's [*Hexo*](http://hexo.io/) or [*NexT theme*](http://theme-next.iissnan.com/) that is responsible for this.
Thanks if you could help me!

**Comment by Neveryu** [comment]
@mCapricornus ,

About this question ,  The anthor need time to solution.

Thanks for your issues and support.

https://neveryu.github.io/guestbook/


![](https://cloud.githubusercontent.com/assets/14313328/18782956/98f44eea-81bb-11e6-8d79-935f1b5fe0b1.png)

**Comment by mCapricornus** [comment]
多谢答主！
