### ISSUE TITLE
代码高亮缩进问题

### ISSUE THREAD

**Issue by LuZhQ** [iissnan/hexo-theme-next#1138]
![image](https://cloud.githubusercontent.com/assets/20197088/18779114/1b3c67d2-81aa-11e6-8bbc-7e5246e9a724.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  - ✔   Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -✔    Mist
  -  Pisces

这个怎么处理啊
@iissnan

**Comment by Neveryu** [comment]
在贴代码之前请将格式排好， @LuZhQ   ，

**Comment by geekrainy** [comment]
用 Hexo 的代码块标签格式试试，制定代码语言。[标签插件](https://hexo.io/zh-cn/docs/tag-plugins.html#代码块)

**Comment by LuZhQ** [comment]
解决了，是我贴进去的格式有点问题
