### ISSUE TITLE
想问下,怎么让图片并排显示呢 有时候需要直观的左右对比.

### ISSUE THREAD

**Issue by sh1tge** [iissnan/hexo-theme-next#1139]
### Expected behavior (预期行为)

图片并排显示
### Actual behavior (实际行为)

自动换行了且居左
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  ✔ Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
- ✔  Mist
-  Pisces

**Comment by ehlxr** [comment]
可以参考这个
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#八、图片模式

**Comment by ehlxr** [comment]
Mist下可以啊
![image](https://cloud.githubusercontent.com/assets/11313370/18901582/c531ee88-857e-11e6-9f56-617d0b0519d7.png)

**Comment by mengxianliang** [comment]
同问 正文里怎样显示横排图片

**Comment by iissnan** [comment]
You can override the "block" behavior of images by using `<img>` html tag with `style` attribute, for example:

```
<img src="/uploads/image-1.jpg" alt="image-1" style="display: inline-block" />
<img src="/uploads/image-2.jpg" alt="image-2" style="display: inline-block" />
```

**Comment by mengxianliang** [comment]
<img src="https://github.com/mengxianliang/ImageRepository/raw/master/Test/1.png" width=500 height=293 />
<img src="https://github.com/mengxianliang/ImageRepository/raw/master/Test/2.png" width=500 height=400 />

按照iissnan所说的方法在编译器里显示的是并排的效果
但是在博客正文中依旧会居中显示 且会加上一个灰色的边框（我猜应该是next主题里会自动给图片居中然后添加点击放大的方法）
请问还有别的方法能解决这个问题么 ；或者怎样取消next主题中这个自动使图片居中的功能，从而让图片能够在博客正文中并列显示

**Comment by xuecat** [comment]
人家 ehlxr 早就给了方案了，你们不认真看。。。上面都还有链接，，，，浪费人家回复呀！！！

多图方案早就可以玩了！！！！！！

**Comment by mengxianliang** [comment]
@xuecat 他的连接我看过也按照教程写过，但是他的多图是在博客列表里显示的，我问的是博客“正文”中怎样实现多图并排显示；我也在他的那篇博客下评论过，他本人也回复说暂无方法实现“正文”中的图片并排显示；next里的Issues关于并排图片的问题我都翻了一遍了，没发解决方案我才问的。

**Comment by xuecat** [comment]
你好好试试看。。。
![default](https://cloud.githubusercontent.com/assets/5563220/24040739/6500861c-0b45-11e7-9b42-eddc672ad8e7.PNG)

**Comment by mengxianliang** [comment]
@xuecat   又按照他的方法重新弄了一遍，果然好使了，是我之前疏忽了，不好意思。

**Comment by meijieru** [comment]
@xuecat 你好，我按照你的方法试了一下，结果是两张图片上下排列，都居中，请问是什么问题呢？

**Comment by xuecat** [comment]
@meijieru  你帖子都还没看完吧！！ 
上面就已经说了很多次了，先要照ehlxr 的教程把next的几处源码改了，再使用这方法才有效。。。

如果还是无效，就无能为力了。

**Comment by ivan-nginx** [comment]
@sh1tge dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by guopengd** [comment]
@ehlxr 您好，使用这个功能之后，图片点击无法放大预览，请问怎么解决呢？

**Comment by stevenjoezhang** [comment]
@guopengd 请使用新版：https://github.com/theme-next/hexo-theme-next
