### ISSUE TITLE
使用table标签，会出现大面积空白

### ISSUE THREAD

**Issue by Comee** [iissnan/hexo-theme-next#114]
![qq 20150418152345](https://cloud.githubusercontent.com/assets/5416227/7214474/84a06a46-e5e0-11e4-9f80-932666a4272d.jpg)
![qq 20150418153332](https://cloud.githubusercontent.com/assets/5416227/7214473/849bc91e-e5e0-11e4-839b-77f5f39cdc66.jpg)

**Comment by Comee** [comment]
查看生成的文件发现多了很多<br>标签

**Comment by Comee** [comment]
http://comee.github.io/2015/04/14/Javadoc-Documentation-Comments/

具体效果可以看这里的最后面 表格 部分，大面积空白，之前不小心关掉了

**Comment by iissnan** [comment]
我记得这好像在 Hexo 那边有一个类似问题的 issue ，解析 Markdown 中的 HTML 存在这个问题。

**Comment by Comee** [comment]
这个 后来发现怎么解决了，即使用table的时候不要使用回车键，因为一个回车键就会生成一个&lt;br/&gt;。这样唯一的缺陷是，表格太难维护了。

**Comment by iissnan** [comment]
@Comee 可以尝试使用 GitHub Flavored Markdown 的表格写法：https://help.github.com/articles/github-flavored-markdown/#tables

**Comment by Comee** [comment]
@iissnan 恩恩

**Comment by zhuimiao** [comment]
http://tool.oschina.net/jscompress?type=2
html table compressed into a row
it work for me

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
