### ISSUE TITLE
Gulpfile compiler error ,缺少符号

### ISSUE THREAD

**Issue by zhaoy875** [iissnan/hexo-theme-next#1141]
### Actual behavior (实际行为)
Gulpfile.coffee  compiler error,i found the file missing comma .

‘hook-duoshuo.js ’  behind the lack of a comma

`return gulp.src([
    './source/js/src/utils.js',
    './source/js/src/motion.js',
    './source/js/src/hook-duoshuo.js'
    './source/js/src/bootstrap.js',
    './source/js/src/post-details.js',
    './source/js/src/schemes/pisces.js'
  ]).pipe jshint()`

### Steps to reproduce the behavior (重现步骤)

screenshot截图
!(screenshot)[http://od6ri688q.bkt.clouddn.com/gulpQQ%E6%88%AA%E5%9B%BE20160925211740.png]

**Comment by Neveryu** [comment]
Thanks for your cooperation

**Comment by Neveryu** [comment]
https://neveryu.github.io/guestbook/

**Comment by geekrainy** [comment]
![2016092902](https://cloud.githubusercontent.com/assets/7333266/18941368/28c9b254-8643-11e6-91f9-73ff32851e12.png)
Ubuntu 下却没有报错，提交了pull request.
