### ISSUE TITLE
couldn't use Markdown todo list feature

### ISSUE THREAD

**Issue by zhangtianle** [iissnan/hexo-theme-next#1142]
when I use hexo, and the next theme to write my [blog ](http://tianle.me/about/), but the Markdown`- [ ] TODO`  feature dosen't work.  
#### expect like this:
- [x] tode  

#### but the result is: 
` [ ] todo` 

Could you tell me what causes it, Thank you!

**Comment by iissnan** [comment]
The Markdown parser that Hexo used does not support this feature.

**Comment by zhangtianle** [comment]
Thank you! I use HTML tags instead of the Markdown to sovle this problem.
