### ISSUE TITLE
打赏按钮

### ISSUE THREAD

**Issue by gaobb** [iissnan/hexo-theme-next#1143]
### Expected behavior (预期行为)

打赏按钮如何能设计圆形，单击时动画形式？
比如当单击时候会有一个颜色的渐变。圆形的形状也要比方形好看点！
例如这种样式： http://zhangliliang.com/2016/04/05/paper-note-hypernet/
### Actual behavior (实际行为)

打赏按钮为方形，单击颜色无渐变
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by Neveryu** [comment]
yes，the basic style is this , but you can custom your style like this.
https://neveryu.github.io/guestbook/

**Comment by MyLeoLan** [comment]
看网页源码，修改/layou/_macro/reward.swig文件，把原来的替换掉

**Comment by ivan-nginx** [comment]
@gaobb dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Cazaea** [comment]
<span style="display: inline-block; width: 50px; height: 50px; border-radius: 100%; color: rgb(255, 255, 255); font-style: normal; font-variant: normal; font-weight: 50; font-stretch: normal; font-size: 25px; line-height: 50px; font-family: microsofty; background: rgb(236, 96, 0);" onmouseout="this.style.color='#fff';this.style.background='rgb(236,96,0)'" onmouseover="this.style.color='rgb(236,96,0)';this.style.background='rgb(204,204,204)'">{{ __('reward.donate') }}</span>
