### ISSUE TITLE
点击顶部菜单分类，下面什么都不显示

### ISSUE THREAD

**Issue by LionWY** [iissnan/hexo-theme-next#1144]
### Actual behavior (实际行为)

_**新建一个文章，然后在md下添加categories：笔记，侧边栏显示分类数目为2，点击之后的页面为空，并没有显示笔记**_

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
you must add type on categories page.
```
title: 分类
date: 2014-12-22 12:39:04
type: "categories"
---
```
like this : https://neveryu.github.io/guestbook/
