### ISSUE TITLE
网站标题自定义

### ISSUE THREAD

**Issue by LionWY** [iissnan/hexo-theme-next#1145]
### Expected behavior (预期行为)

网站标题只显示 作者名称， 不显示关键字，不显示description
![qq20160928-2](https://cloud.githubusercontent.com/assets/5524753/18899778/111f21e6-856e-11e6-8c4e-2fa114ec3155.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
You can design your site title like this .
https://neveryu.github.io/guestbook/
In site config.

**Comment by LionWY** [comment]
就是看了你的博客，在哪里进行设置啊？site config  where ？

**Comment by gaobb** [comment]
我看了最近的issues, Neveryu几乎都有回复，只是列出自己的博客地址，并没有针对性的解决问题。这算不算恶意回复？

**Comment by Neveryu** [comment]
In themes\next\layout\index.swing.
You can find 
```
{% block title %} {{ config.title }} {% endblock %}
```
This is default setting.

You can change it to 
```
{ %block title % } {{ config.title }} - {{ theme.description }} { % endblock % }
```
or you can custom any style if you want.

Thanks for your cooperation.
@LionWY 
If you has any other questions , you can write me a message on https://neveryu.github.io/guestbook/
