### ISSUE TITLE
站内搜索search.xml文件越来越大如何解决

### ISSUE THREAD

**Issue by vinoZHU** [iissnan/hexo-theme-next#1146]
文章数量越多，search.xml内容越多，加载超级慢，该如何解决？

**Comment by Neveryu** [comment]
In new version , we can user contain search server.This way not use search.xml。
https://neveryu.github.io/guestbook/

**Comment by mritd** [comment]
已经对 hexo 无爱.....https://mritd.me

**Comment by hzlpy** [comment]
@mritd 你这个也挺好的，请问是怎么制作的？

**Comment by mritd** [comment]
@hzlpy 用的 jekyll，直接找个主题 就行，ruby写的，Github 目前用的就是这个；感觉 Hexo 不太友好，遇到很多次 都是环境没法复现，比如在这个版本能用，从别的电脑上用新版本重建一个就会出现各种莫名奇怪的错误，而且社区感觉 也并不是太活跃

**Comment by vinoZHU** [comment]
不想再去折腾`jekyll`或者其他什么的了，就退而求其次，修改下插件吧。修改`hexoblog/node_modules/hexo-generator-search`的`search.ejs`文件，将其中的`post.content`和`pages.content`改成`post.title`和`pages.title`。然后原先由50篇文章生成的`search.xml`从800+kb瞬间变成10+kb,至少短期内应该没问题了。

```
<?xml version="1.0" encoding="utf-8"?>
<search>
  <% var url = config.url + config.root %>
  <% if(posts){ %>
    <% posts.each(function(post){ %>
    <entry>
      <title><%-: post.title | cdata %></title>
      <url><%- encodeURI(post.permalink) %></url>
      <content type="html"><%-: post.title | cdata %></content>
    </entry>
    <% }) %>
  <% } %>
  <% if(pages){ %>
    <% pages.each(function(page){ %>
    <entry>
      <title><%-: page.title | cdata %></title>
      <url><%- encodeURI(page.permalink) %></url>
      <content type="html"><%-: page.title | cdata %></content>
    </entry>
    <% }) %>
  <% } %>
</search>
```

**Comment by hausen1012** [comment]
> 已经对 hexo 无爱.....https://mritd.me
请问搜索用什么做的

**Comment by LauArmy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
