### ISSUE TITLE
从文章中的分类能访问分类页面，但从左侧菜单访问该分类则无法显示。

### ISSUE THREAD

**Issue by zonas0574** [iissnan/hexo-theme-next#1147]
从文章中的分类能访问，但从左侧菜单访问则无法显示。本地 hexo s 两者都可以，这是为什么。
地址：https://zonas0574.github.io/
javase （java 基础）这个标签

试过删除db.json、.deploy_git ，并hexo clean，都没用

**Comment by zonas0574** [comment]
放弃了，不用自定义标签。

**Comment by Neveryu** [comment]
看一下是不是需要改一下配置文件。
https://neveryu.github.io/guestbook/

**Comment by zonas0574** [comment]
知道问题在哪，点左侧菜单链接，移上去是https带头，但点击后自动变成http，如果手动改为https就能访问，但这是为什么，浏览器的问题吗

**Comment by wanderingpuppy** [comment]
怎么解决的，同样的问题
