### ISSUE TITLE
二级目录站点分页时首页链接为 / 目录

### ISSUE THREAD

**Issue by his1devil** [iissnan/hexo-theme-next#115]
求教二级目录站点分页问题：
网站地址 http://webiste.com/blog，page1链接为http://webiste.com, 这个page link怎么修改，其他页面都正常 /blog/page/n
感谢

**Comment by iissnan** [comment]
看上去像是 [Hexo Paginator](http://hexo.io/docs/helpers.html#paginator) 的一个 bug

**Comment by ivan-nginx** [comment]
@his1devil don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by his1devil** [comment]
@ivan-nginx  Sorry about that, it's solved, thank u , closed~
