### ISSUE TITLE
怎么设置首页的keywords啊？文章里面是标签自动生成keywords

### ISSUE THREAD

**Issue by LuZhQ** [iissnan/hexo-theme-next#1150]
怎么设置首页的keywords啊？文章里面是标签自动生成keywords @iissnan

**Comment by LuZhQ** [comment]
知道怎么设置了，在主题配置文件有个keywords配置项 @iissnan

**Comment by yusmile** [comment]
@luzhq  请问在哪里？能否帮菜鸟指点下吗？

**Comment by luzhq** [comment]
![image](https://cloud.githubusercontent.com/assets/20197088/23091682/9a09a410-f5f6-11e6-9769-631fbdf1e771.png)
next主题下的_config.yml文件 @yusmile
