### ISSUE TITLE
menu  栏会跳转到 http 而不是 https, 而 http 找不到网页

### ISSUE THREAD

**Issue by bowenli86** [iissnan/hexo-theme-next#1152]
我遇到的问题跟这里面描述的问题一样 https://www.v2ex.com/t/302180

> 现象描述： 我在配好了之后，本地 hexo s 看效果；恩！不错，一切正常，完成。 于是上传 github 之后（尼玛坑爹的来了），点击 menu （就是 tags 、 categories 那些按钮）跳转的页面全他妈找不到。
> 
> 发现过程： 于是我找呀找呀，问呀问呀！！尝试了所有的；最后发现了，气人；
> 
> 那些按钮的跳转地址是直接“网名+目录”，并不是"url + 目录"，确实 https 头； 也是说，我访问 git 主页 url 是： https://name.github.io/是对的，而那些按钮的跳转 url 地址却直接就是:name.github.io/tags ，正确的地址该是： https://name.github.io/tags 。
> 
> 解决办法（当然我至今没解决，这些事尝试）： 对那些页面的 md 添加点代码进行 url 重定位。然而 archives 却不行，因为 NexT 对 archives 的处理是默认的，不允许 md 文件处理。
> 
> 所以，这坑爹问题依旧没解决。头疼死了！！若有大大可以帮助的，就帮下！！！！
> 
> https://xuecat.github.io/ （欢迎大家点击“归档” menu 按钮，亲身体验下）
### Expected behavior (预期行为)

点击 "分类"会跳转到 https://xuecat.github.io/categories/
### Actual behavior (实际行为)

点击 "分类"会跳转到 http://xuecat.github.io/categories/
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master  ✔  
-  Latest Release  ✔  
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse  ✔  
-  Mist
-  Pisces

**Comment by pengshp** [comment]
我也遇到和你一样的问题，查了下，现在Github Pages官方更新支持`https`了，
参考：<https://github.com/blog/2186-https-for-github-pages>
以及如何让网站变成https
<https://help.github.com/articles/securing-your-github-pages-site-with-https/>
按照上面的说法，有一步要把文件中引用到`http`的地方全变为`https`，希望主题中能更新一下@iissnan

**Comment by phoenixjiangnan** [comment]
请问您是在 Next 主题里改了哪个文件? @pengshp

**Comment by pengshp** [comment]
我现在改了也没成功，我对网页开发不熟悉，思路就是把所有引用到外链的地方的`http`改成`https`，我现在是在火狐浏览器中使用<https://www.eff.org/https-everywhere>插件强制把所有的http转为`https`访问，这样博客就可以正常访问了。只能等更新了

**Comment by Neveryu** [comment]
我没搞什么链接，也没出什么问题啊？
什么情况？
https://neveryu.github.io/guestbook/

**Comment by iissnan** [comment]
@phoenixjiangnan 我看你的站点现在菜单链接协议都是 `https` 是正确的。奇怪的是，在页面上 NexT 菜单使用的相对路径，协议应该是没有关联的。

**Comment by iissnan** [comment]
@paicha  查了下，百度分享和 JiaThis 都不支持 https，除了自建托管的方式似乎没有很好的方法解决这两个分享服务的问题。

**Comment by pengshp** [comment]
@Neveryu 现在博客直接用http直接访问不了，你试试你的<http://neveryu.github.io/guestbook/>如果博客中引用了http的外链，没加SSL证书有时加载不了,比如七牛图床不能使用https，图片加载不了

**Comment by uncleyy** [comment]
解决方法,在项目配置文件里,修改两个属性
root: https://uncleyy.github.io/
relative_link: false

**Comment by GoldyMark** [comment]
@uncleyy  试了你的方法，发现打开的url变成`https://xx.github.io/https://xx.github.io/categories/...`。

目前发现只有`menu`才有这个问题，首页的文章链接是没问题的。
而且查看生成的html发现，`menu`的`href`地址也是正确的（带https），但实际点击时却实际跳转到`http://xx.github.io/...`。

发现以下几种情况下访问是正常的：
+ 翻墙；
+ safari；

想知道当点击`menu`时会调用什么函数？ @iissnan

**Comment by GISering** [comment]
我在Macbook中使用任何浏览器（Safari, Firefox, Chrome）tags和categories页面都打不开，而在Win7中都能打开！！！

**Comment by lugavin** [comment]
我也遇到同样的问题，请问你解决没有？

**Comment by ivan-nginx** [comment]
@bowenli86 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by bowenli86** [comment]
I'm not using hexo-theme-next anymore, so I don't know if it's working or not. Please feel free to close it.
