### ISSUE TITLE
如何让 Youtube iframe 不 Responsive

### ISSUE THREAD

**Issue by maxchendt** [iissnan/hexo-theme-next#1153]
https://github.com/iissnan/hexo-theme-next/issues/824  之后，发现 

```
<iframe width="320" height="180" src="https://www.youtube.com/embed/RiF6m3InMRM" frameborder="0" allowfullscreen></iframe>
```

得到的效果如 `{% youtube RiF6m3InMRM %}`， 自动调整大小，而不是大小固定为 320x180

请问如何将 视频框的大小设定为给点大小？

**Comment by maxchendt** [comment]
我不能确定代码是否正确，但在 `themes/next/source/js/src/utils.js` 文件的  `var newDimension;` 语句之后加入

``` javascript
if (this.src.search('youtube.com') > 0 && $iframe.width() != 300) return true;
```

重新生成页面，发现 `{% youtube RiF6m3InMRM %}` 得到的是自动大小的，而 `<iframe width="320"  ...` 得到的是固定大小的

**Comment by maxchendt** [comment]
终于能出现 https://maxchendt.github.io/Blog/20161007NextSet.html  里面的文字环绕 youtube 视频框

**Comment by iissnan** [comment]
Cool

**Comment by ivan-nginx** [comment]
@maxchendt dont understand u, write in English if not solved. If solved, close it please. Thank's!
