### ISSUE TITLE
升级Ｎext 后，Code 样式变得没有以前好看

### ISSUE THREAD

**Issue by gaobb** [iissnan/hexo-theme-next#1157]
### Expected behavior (预期行为)

希望代码高亮能够显示出和给定Demo 一样的效果
![2016-10-14 12-40-12](https://cloud.githubusercontent.com/assets/9379079/19375903/7ebda34a-920b-11e6-9aaf-7f55e3151a4d.png)
### Actual behavior (实际行为)

刚升级了Next主题后，发现Code 显得很难看：
![2016-10-14 12-37-40](https://cloud.githubusercontent.com/assets/9379079/19375861/17719070-920b-11e6-879e-d82c5dd41112.png)

我的主题配置是：
`codes:
    external: true
    family: PT Mono
    size: 29
highlight_theme: night eighties`
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@gaobb dont understand u, write in English if not solved. If solved, close it please. Thank's!
