### ISSUE TITLE
移动端多说样式在哪里修改？

### ISSUE THREAD

**Issue by XIJINIAN** [iissnan/hexo-theme-next#1158]
### Expected behavior (预期行为)

我用的是最新版，为了使PC端的多说样式更符合个人审美，就在多说官网改变了多说CSS样式，PC端的确变得更符合本人审美啦！
### Actual behavior (实际行为)

遗憾的是在移动端的显示效果十分诡异，我不知道在哪里更改。
### Steps to reproduce the behavior (重现步骤)

可以去 http://xijinian.xyz 看一下哈
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master

NexT Scheme:
-  Mist

**Comment by iissnan** [comment]
PC 和 Mobile Devices 使用的是同一份样式，在同一个地方改，你可以使用 Media Query 来设定不同设备上的显示。

**Comment by XIJINIAN** [comment]
感谢回复，手动比心，虽然听不太懂，但我会努力学习争取听懂哒~html、css、js之类的都没学过，边google边猜。。。
还有我是在多说官方网站上自定义的CSS样式的，不知道next主题中具体是在那个文件里面定义多说样式。
我的博客在移动端的跟电脑上显示是不一样的，譬如我在电脑上去掉了多说评论框的左边的头像并且将评论框左边的空隙都去掉了，但是在移动端依然有这个空隙；我在电脑上浏览的时候评论框的左边和文章的左边是对齐的，但是移动端不是对齐的；还有就是在移动端我每篇文章的下面的评论框 和 “留言”这个page 下面的多说评论框依然是不一样的，一宽一窄，我猜测了一些原因，但是感觉都不太靠谱。
最后拜谢作者的主题，我用Hexo取代简书的原因只是因为这个next主题实在是太漂亮啦！爱你~

**Comment by ivan-nginx** [comment]
@XIJINIAN dont understand u, write in English if not solved. If solved, close it please. Thank's!
