### ISSUE TITLE
When setting duoshuo_shortname, I get a mistake window .

### ISSUE THREAD

**Issue by Andrew-liu** [iissnan/hexo-theme-next#116]
I have set duoshuo_shortname in config file, but when I open my blog, which will show a window **"你还没有设置多说域名(duoshuoQuery.short_name)" **forever

---

Thanks!

**Comment by Andrew-liu** [comment]
问题已经搞定了, 有一个新的问题, about下面为什么不现实disqus的评论窗口

**Comment by zodiacg** [comment]
Page的layout里好像没有开启comments

**Comment by iissnan** [comment]
嗯， Page 没有使用 comments。有必要在 Page 使用 comments 吗？

**Comment by zodiacg** [comment]
在跟posts不同的url结构上做特定的展示就需要用page。如果展示的内容需要进一步的讨论和反馈那就需要comments。虽然有了alias但是跟page的作用还是明显不同的。
而且page有comments的开关，做一下判断选择加不加comments的区域还是比较容易的。

另外与此多少有些相关的就是next的menu部分如果需要添加自定义的链接的话，就需要手动在语言文件里加入对应的翻译项，不然生成的时候会是menu.XXX。
我自己喜欢给博客加个留言本，就遇到了这两个问题。

**Comment by Andrew-liu** [comment]
我从前的博客, 会在about me的页面设置comment, 这样别人浏览博客建立的时候顺手就留言了或者希望加友联的

**Comment by Witype** [comment]
楼主是如何解决这个问题的，我使用NexT的时候也遇到了同样的问题，感谢！

**Comment by BrightTsai** [comment]
怎么搞定的?? 我也遇到这个问题.

**Comment by iissnan** [comment]
@BrightTsai 多说的 shortname 是否正确？

**Comment by BrightTsai** [comment]
@iissnan 现在没问题了,可能是我操作有问题... 谢谢!

**Comment by Deeer** [comment]
你还没有设置多说域名--->请问这个问题是如何解决的？

**Comment by BrightTsai** [comment]
@Deeer 按照教程走就行了,duoshuo_shortname: 你的多说账号, 注意冒号后面需要加空格..
