### ISSUE TITLE
NexT Pisces主题如何定义custome logo

### ISSUE THREAD

**Issue by qiufengyu** [iissnan/hexo-theme-next#1163]
在主题的_config.yml中说明只有Muse主题可以设置，简单粗暴地把./themes/next/layout/_partials/headers.swig
`{% if theme.custom_logo.image and theme.scheme === 'Muse' %}`
改为
`{% if theme.custom_logo.image and theme.scheme === 'Pisces' %}`
并设置了custome logo图片，但是实际情况header中site-nav部分（首页、分类、关于、归档的那个小部件）由于图片的存在，被下面的site-author motion遮盖了。
实际效果：
![1](https://cloud.githubusercontent.com/assets/7643212/19304622/0a5c5774-90a0-11e6-901f-1f41c7a9e64c.PNG)
期望效果：
![2](https://cloud.githubusercontent.com/assets/7643212/19304631/13d1418e-90a0-11e6-9cab-1422447d6f01.PNG)

尝试修改了很多css相关的文件也没有效果，目前的情况可以访问：qiufengyu.github.io chrome浏览器有一些智能，似乎可以自动调整，但不是总有效。Safari第一次访问能显示nav，但是刷新就又不显示了。

对css样式、网页元素只略懂一些，但是强迫症表示很难受，希望各位大大教做人！

**Comment by qiufengyu** [comment]
Safari渲染以后显示：
`<aside id="sidebar" class="sidebar" style="margin-top: 307px; display: block;">`
并不能找到对应的margin-top在哪里修改。。。

**Comment by Neveryu** [comment]
@qiufengyu  
首先，在浏览器中找到这个`margin-top`的css，应该会显示哪个css文件的哪一行，你直接找到源文件去改就行了。
如果这一个办法你搞不定的话，那就自己写css样式啊。id是sidebar，这已经很明确很好写了，你想怎么写就怎么写。
我的这篇博客里面也有很多我自己写的css样式，[https://neveryu.github.io/2016/09/03/hexo-next-one/](https://neveryu.github.io/2016/09/03/hexo-next-one/)

**Comment by qiufengyu** [comment]
@Neveryu Hi, 感谢你的回答，在main.css中修改了sidebar的margin-top属性，但是依旧没有效果，chrome即使不做如上设定也可以，刷新几下偶尔不稳定；Safari就不行，昨天测试了一下，Win10的Edge似乎能够显示。现在仍在测试中，考虑对site-nav的样式进行设定，不知道能不能奏效。
感谢你的博客，学习中！

**Comment by iissnan** [comment]
Pisces 的 Sidebar 定位是通过脚本设定的（`source/js/schemes/pisces.js`），他会根据 Header 的内容高度设定 `margin-top` 的值。你看到的不稳定的现象是因为在脚本计算的时候，图片可能加载完成也可能没有加载完成，从而导致 Header 高度的计算出现问题。

一个最简单的修改方法，是给那张图标指定大小即可。

**Comment by qiufengyu** [comment]
@iissnan 
Thx! 得到官方的回复，非常感谢！这种方法可以直接指定图片大小，margin-top可以改变，目前可以搞定啦！此外，秉持作死精神，根据您的回复，我重新捣鼓了一下，在 `themes/next/source/css/_schemes/Pisces` 中仿照其他两个 Scheme 添加了一个 `_logo.styl` : 
``` stylus
.custom-logo {
  .site-meta-headline { text-align: center; }

  .brand { background: none; }

  .site-title {
    margin: 10px auto 0;
    font-size: 24px;
    a { border: none; }
  }
}

.custom-logo-image {
  margin: 0 auto;
  max-width: 240px;
  height: ???px; // 根据实际图片调整
  background: white;
}
```
这样 Header 的 height 似乎就能加上这个值了，基本也不会出现不稳定的情况。
直接修改 js 文件中`margin-top` 属性感觉太死板了，不过效果一样棒！
总之很感谢，个人也在一直折腾这个主题，挺有意思的！

**Comment by ivan-nginx** [comment]
@qiufengyu dont understand u, write in English if not solved. If solved, close it please. Thank's!
