### ISSUE TITLE
links-of-author 随机背景颜色

### ISSUE THREAD

**Issue by maxchendt** [iissnan/hexo-theme-next#1164]
每次 `hexo g`时，发现 `css/main.css` 都被改变，查看了下，发现 是 `.links-of-author a:before` 里的 背景颜色设置`background` 是随机的，即 `/source/css/_common/components/sidebar/sidebar-author-links.styl` 里面

``` styl
background: rgb(random-color(0, 255) - 50%, random-color(0, 255) - 50%, random-color(0, 255) - 50%);
```

为什么要设置成随机的呢？

**Comment by Neveryu** [comment]
@maxchendt 
厉害了，我的哥，这都被你发现了
这个样式是用于侧边栏社交链接中，每一项前面有一个小点的颜色。
这样的话，每次部署后的小点的颜色都不一样，同时还能做版本，避免缓存的影响。
@iissnan 真是棒棒的。

**Comment by xxf1995** [comment]
@Neveryu 你怎么用背景色覆盖canvas-nest动画的啊。。在mist主题下没找到方法

**Comment by xxf1995** [comment]
nvm I found the way
added `.post-block { background: #ffffff; }`
to `source/css/_common/components/post/post.styl`
