### ISSUE TITLE
点击搜索（local search）没反应啊啊啊

### ISSUE THREAD

**Issue by Sanfordy** [iissnan/hexo-theme-next#1165]
### Actual behavior (实际行为)
[点击没反应啊？？？](http://oevlxqp42.bkt.clouddn.com/16-10-13/32892999.jpg)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
@Sanfordy  没明白你的意思

**Comment by flashlab** [comment]
刚测试了下，最新版本没有问题

**Comment by Sanfordy** [comment]
http://sanfordy.com

**Comment by Sanfordy** [comment]
@Neveryu  http://sanfordy.com你进我博客点下搜索试试，点了没反应啊啊啊

**Comment by Sanfordy** [comment]
我都是按照教程走的啊啊

**Comment by Neveryu** [comment]
@Sanfordy 搜索的页面都没有，你玩个锤子啊。
[Hexo-NexT搭建个人博客（一） ](https://neveryu.github.io/2016/09/03/hexo-next-one/)

**Comment by Sanfordy** [comment]
@Neveryu 啊，我知道原因了，因为我的的search.xml太大了。现在我把大多数博文都删了，可以用了。

**Comment by flashlab** [comment]
确实有可能是xml文件太大，我在想办法通过改进generator限制它的大小，应该很快就能push到npm server

**Comment by yun-percy** [comment]
今天也遇到了，我有些文章是html代码嵌到markdown里面，导致了xml无法解析，我把那几篇文章拿掉就可以了……

**Comment by flashlab** [comment]
@yun-percy 可以给个sample吗？我没有遇到这个问题。

**Comment by zhongjun96** [comment]
@flashlab  昨天也遇到了点击搜索框没有反应的问题, 尝试访问zhome.online/search.xml   提示xx行xx列解析错误. 发现markdown文件名带"&"符号就会无法解析  删除"&"符号后就正常使用了

**Comment by flashlab** [comment]
@zhongjun96 理论上不会出现这种情况，可以给个例子吗？

**Comment by zhongjun96** [comment]
@flashlab  特地复现了这个问题,你可以访问zhome.online/search.xml  查看。markdown文件名带有& 符号就会这样，点击搜索没反应。网站源码在我github上,随时可以查看.需要别的资料可以邮件或者QQ联系.点击zhome.online 的侧边栏可以查看我的邮箱和QQ

**Comment by flashlab** [comment]
@zhongjun96 解决这个问题有两个地方需要修改，一个见 #1198 ，另一个在https://github.com/flashlab/hexo-generator-search/commit/d8fb1619c96e73c3309ceb8e44e1ffd586721403
顺便解决了root没有带前缀导致链接字串重复的问题~

**Comment by yusmile** [comment]
@SanFordy 请问你后来怎么解决的呢？
