### ISSUE TITLE
hexo-browsersync 畫面空白

### ISSUE THREAD

**Issue by jackypan1989** [iissnan/hexo-theme-next#1166]
版本 3.2
一切正常，但要加入 live reload (hexo-browsersync) 後
頁面會全白

不知道各位如何處理
或是有其他 live reload 的方案

**Comment by Neveryu** [comment]
@jackypan1989 
我使用(hexo-browsersync)开发的时候没有任何问题。
[Hexo-NexT搭建个人博客（一）](https://neveryu.github.io/2016/09/03/hexo-next-one/)
也不清楚你是什么问题，可以交流

**Comment by iissnan** [comment]
我这边也没有问题

**Comment by jackypan1989** [comment]
@Neveryu 

我的只要加入 hexo-browsersync (latest)
就會出現 .use-motion {opacity: 0}
使得畫面全白

雖然把 use-motion 改成 false
就能正常顯示
但也沒有成功啟動 hexo-browsersync  (body 沒看到 script)
想問一下各位，有需要在 _config 底下加入什麼額外設定嗎
我加了 plugins: hexo-browsersync 也沒用

**Comment by Harvesty** [comment]
我碰到了类似的问题。
我正写一篇博文，写着写着页面就空白了
![space](https://cloud.githubusercontent.com/assets/1993503/19547597/b7c69bb4-96cb-11e6-9bb9-a343d40bc51c.PNG)
页尾显示：
![space-bottom](https://cloud.githubusercontent.com/assets/1993503/19547602/c56706e6-96cb-11e6-8875-69294ed6f79f.PNG)
我试着删除了几行，又能正常显示了。我以为什么地方没有转义，后来发现那几行不删除，在首页也能正常显示。下图首页显示效果：
![normal](https://cloud.githubusercontent.com/assets/1993503/19547771/d818e290-96cc-11e6-845c-20f56886d291.PNG)
就是进入那篇博文就显示空白。
在首页，我继续写博文，也一切正常。
然后我去掉hexo-browsersync ，然后生成，手动刷新，点击那篇博文，一切正常。

**Comment by ivan-nginx** [comment]
@jackypan1989 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by jackypan1989** [comment]
@ivan-nginx 
it shows blank when we use ```hexo s```
and we found some css ```.use-motion {opacity: 0}```

**Comment by ivan-nginx** [comment]
I do refactoring on motion styles. U can check latest master branch or latest release version, it must work fine.

**Comment by jackypan1989** [comment]
still blank in index page

repo:
https://github.com/sovmedcare/hexo

some discovering:
when I remove all code block, it works

**Comment by ivan-nginx** [comment]
@jackypan1989 can u create new issue step by step to reproducte with version's info in English? Need to check it.

**Comment by jackypan1989** [comment]
https://github.com/iissnan/hexo-theme-next/issues/1896

**Comment by ivan-nginx** [comment]
Ok, i close that issue to reference #1896.
