### ISSUE TITLE
虚惊一场，sidebar toggle icon 消失，原来是屏幕不够宽

### ISSUE THREAD

**Issue by maxchendt** [iissnan/hexo-theme-next#1169]
今天早上，突然发现 sidebar toggle icon 没有了，侧栏无法显示 (因为主题设置里面设置为 hide)。 进行如下尝试

* 重新初始化 hexo 目录，新安装 NexT 主题，chrome 还是看不到侧栏
* 采用 firefox， 可以看到侧栏
* 升级 chrome (gc) 到最新，还是看不到 侧栏
* 排查中，最大化了 gc 窗口，侧栏按钮出现

chrome 浏览器可是 40 多天没有关闭，以前调试的时候是有侧栏的。也不知道是哪儿修改了。虚惊一场，浪费了一个上午。因为我以前录制了视频，https://youtu.be/q9V9Dj4ttJw ， 视频里是有侧栏的

最后发现，gc 窗口拉宽，侧栏按钮出现

**Comment by Neveryu** [comment]
@maxchendt :flushed::flushed::flushed:
大哥，你最近划水好严重啊 。

**Comment by djyde** [comment]
所以你的问题是什么

**Comment by maxchendt** [comment]
哈哈，最近不是在忙着学习使用吗？
要是浏览器窗口下有 scroll bar 提示窗口太窄，也许就不会找不到侧栏按钮了

**Comment by djyde** [comment]
你可以提一个 issue 来**清晰**，**明确**地提出你的需求。
