### ISSUE TITLE
disqus issue

### ISSUE THREAD

**Issue by CICISUN** [iissnan/hexo-theme-next#117]
disqus couldn't load on my website: cicisun.github.io

Here's my site config file_config.yml

```yml
# Disqus
disqus_shortname: sunbingjie
```

Please kindly advise:)

**Comment by minoscc** [comment]
先檢查這個
https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22

**Comment by iissnan** [comment]
It seems there is something wrong with your Disqus domain settings.
Please refer to the URL @minoscc mentioned above to check:

1. Trusted-domain settings.
2. Disqus shortname
3. Domain you used when registered Disqus
