### ISSUE TITLE
[404.html]自定义404页面。

### ISSUE THREAD

**Issue by mapan2020** [iissnan/hexo-theme-next#1170]
### Expected behavior (预期行为)

想自定义一个404.html
在blog/source/文件夹下创建了404.html
### Actual behavior (实际行为)

实际可以跳转到这个页面，但是header、sidebar、还有多说评论框都叠加在原来的html页面上。

NexT Version:
-  Master

NexT Scheme:
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

win10  google & firefox 浏览器

**Comment by Neveryu** [comment]
@mapan2020 
我也是这样单独做的一个404，好像没什么问题啊。
我的博客：[https://neveryu.github.io/guestbook/](https://neveryu.github.io/guestbook/)
但是如果我输入一个不存在的页面，就会去到404
比如：[https://neveryu.github.io/fffff](https://neveryu.github.io/fffff)，就会来到404，
你可以把你的问题详细跟我说明一下吗，我还没太明白你遇到了什么问题。

**Comment by mapan2020** [comment]
已经解决
文件头添加
layout: false
title: "404"
---

**Comment by mapan2020** [comment]
嗯呢，现在问题已经解决了。我的博客 http://www.mapan.win 欢迎互换友链

在 2016-10-14 15:30:50，"Neveryu" <notifications@github.com> 写道：


@mapan2020
我也是这样单独做的一个404，好像没什么问题啊。
我的博客：https://neveryu.github.io/guestbook/
但是如果我输入一个不存在的页面，就会去到404
比如：https://neveryu.github.io/fffff，就会来到404，
你可以把你的问题详细跟我说明一下吗，我还没太明白你遇到了什么问题。

**Comment by colorwin** [comment]
@mapan2020

指的是这样加？
[这篇文章](http://jiji262.github.io/2016/04/15/2016-04-15-hexo-github-pages-blog/)指出github pages 二级域名不支持。

```
---
layout: false
title: "404"
---
```

**Comment by optcheng** [comment]
@colorwin 
我今天也是遇到类似的问题, 尝试了一下发现是这样(我的 NexT 版本是: `5.1.0`, 浏览器: `Chrome` ): 
```html
title: "your title" 
comments: false
layout: false 
---
<!DOCTYPE HTML>
<html>
<head>
  <title> 404 页面无法找到</title>
  .........
```
`title` / `comments` / `layout` / `date` 都是可选字段, 如下简单说明 ( 不明白可以具体尝试一下即可) :
`title: "xxx"` 浏览器标签页和文章的标题
`comments: false` 隐藏评论插件(如 多说)
`layout: false` 不使用 Hexo 的主题样式

我尝试了几次, 腾讯公益的 404 界面使用不了

但是,  文本风格的和这种风格的 ( [戳这里](http://zhihu.com/question/21650209/answer/93785474) )就可以使用
