### ISSUE TITLE
怎么把Next主题分类和标签合并成一页

### ISSUE THREAD

**Issue by CPUdream** [iissnan/hexo-theme-next#1177]
1. 分类和标签这两页内容太少了，想把他们两页合并成一页，把分类页的东西放到标签页下面，中间用分割线分割开就好了。
2. 本人博客：http://blog.liuyufeng.tech
   3.求大神指导，本人纯小白，生命不止折腾不息！！！

**Comment by Neveryu** [comment]
@CPUdream 
哈哈，看来兄弟项目还是做少了啊

**Comment by CPUdream** [comment]
@Neveryu 帮我改改把，我没有学过这个html，但是喜欢折腾，

**Comment by kulley** [comment]
@CPUdream 你修改的这个首页文章显示能共享下吗

**Comment by jcx70100** [comment]
@CPUdream 请问您的首页中文章分割线是怎么修改的啊？ 原版的分割线太短了，我也是小白，求指教

**Comment by ivan-nginx** [comment]
@CPUdream dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by AlynxZhou** [comment]
我觉得这是个hexo内建的功能吧，就算能把这两个页面合并起来，生成的时候也不好让hexo把他俩合到一起，那就麻烦了。
/* 所以说解决的办法是多创建标签和分类来占位置嘛23333 */
