### ISSUE TITLE
Mist主题如何安装呢?

### ISSUE THREAD

**Issue by Anoxia** [iissnan/hexo-theme-next#118]
我装完是默认的next,小弟很喜欢mist那个主题.

**Comment by Anoxia** [comment]
已经搞定了。

**Comment by kaito-kidd** [comment]
怎么安装mist，求方法。

**Comment by derekhe** [comment]
我在根目录中的_config.yml加入了scheme: Mist，但还是老样子，没搞明白为啥。

**Comment by iissnan** [comment]
@kaito-kidd 
主题的 `_config.yml` 中有一句 scheme: Mist，将其前面的注释去掉即可。

@derekhe 可能是主题的配置覆盖了站点的配置。

**Comment by iissnan** [comment]
@Anoxia 头像不错

**Comment by Anoxia** [comment]
@iissnan，还是你的牛一点
