### ISSUE TITLE
部署博客后,电脑和苹果手机访问正常,安卓手机访问样式没有加载

### ISSUE THREAD

**Issue by zk-** [iissnan/hexo-theme-next#1182]
### Expected behavior (预期行为)
部署博客后,手机访问效果一致正常

### Actual behavior (实际行为)
苹果手机访问都正常
安卓手机访问样式没有加载出来
![screenshot_2016-10-19-10-06-20](https://cloud.githubusercontent.com/assets/10862962/19503146/45166d20-95e4-11e6-9c9c-259845743860.jpeg)

### Steps to reproduce the behavior (重现步骤)
安卓手机访问
[我的博客](http://zk-.github.io/)

实在是很困惑,因为同事用的一样的却是正常的
[我的部署器](https://github.com/zk-/hexo_zk)

**Comment by zk-** [comment]
麻烦各位大大为小弟解决一下疑惑,谢谢各位!

**Comment by Neveryu** [comment]
@zk- ，这个谁知道是什么原因啊，只能推荐两篇优质博文给你看一下，你找一下问题原因
[Hexo-NexT搭建个人博客（一）](https://neveryu.github.io/2016/09/03/hexo-next-one/)
[Hexo-NexT搭建个人博客（二） ](https://neveryu.github.io/2016/09/30/hexo-next-two/)
，我看了一下你的博客，好多配置都没有跟上，建议你先学习一下

**Comment by zk-** [comment]
@Neveryu 谢谢你,搞了一天,把5.0.1的主题换成5.0.0就好了,也不知道哪里出了问题,在这里通知下
![qq 20161019174041](https://cloud.githubusercontent.com/assets/10862962/19513697/7216670a-9623-11e6-9f46-cbcfc0c05ea3.png)
