### ISSUE TITLE
每次在本地修改了index.html文件，远程提交总是会被模板覆盖，怎么解决

### ISSUE THREAD

**Issue by xxxxxxttt817** [iissnan/hexo-theme-next#1183]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
@xxxxxxttt817 你这个index.html是啥？
如果是README文件的话，可以参照[Hexo-NexT搭建个人博客（二）](https://neveryu.github.io/2016/09/30/hexo-next-two/#8-%E7%BB%99Github%E6%B7%BB%E5%8A%A0README)

**Comment by yizhilee** [comment]
@xxxxxxttt817 如果是页头或者页脚的话，直接写入模板文件就好了，这样所有的 index.html 都会有了。

**Comment by xxxxxxttt817** [comment]
@yizhilee 模板的index.html文件路径在哪里

**Comment by yizhilee** [comment]
@xxxxxxttt817 你做了什么修改？

**Comment by xxxxxxttt817** [comment]
@yizhilee 
<a href="/"  class="brand" rel="start">
      <span class="logo-line-before"><i></i></span>
      <span class="site-title">Hexo</span>
      <span class="logo-line-after"><i></i></span>
    </a>
在本地把这个标签和title标签的“Hexo” 改了，git上来就全部被还原了

**Comment by xxxxxxttt817** [comment]
@yizhilee 
      <span class="site-title">Hexo</span>
      
  在本地把这个标签和tittle标签的“Hexo”改了，提交上来就被还原了，应该是被默认模板给覆盖了，就是不知道模板的index在哪里

**Comment by xxxxxxttt817** [comment]
@yizhilee 
```<span class="site-title">Hexo</span>`
在本地把这个标签和tittle标签的“Hexo”改了，提交上来就被还原了，应该是被默认模板给覆盖了，就是不知道模板的index在哪里

**Comment by yizhilee** [comment]
@xxxxxxttt817 tittle 是可以直接在主题配置文件当中修改的。

**Comment by xxxxxxttt817** [comment]
@yizhilee 
`````
<a href="/"  class="brand" rel="start">
      <span class="logo-line-before"><i></i></span>
      <span class="site-title">Hexo</span>
      <span class="logo-line-after"><i></i></span>
    </a>
```
这个A标签 应该是主页的那个Hexo标题吧，我想把这个也给改了

**Comment by yizhilee** [comment]
@xxxxxxttt817 https://hexo.io/zh-cn/docs/configuration.html#网站

**Comment by Edmonds01** [comment]
同问 有人解答下吗
