### ISSUE TITLE
修改NexT的内置多说样式

### ISSUE THREAD

**Issue by lnaif** [iissnan/hexo-theme-next#1184]
目前NexT使用的多说是原版的默认样式，与NexT的简洁优雅格格不入。

**Comment by SCP-028** [comment]
这个好像没有考虑移动端？另外个人感觉回复评论的缩进可以加大一点，现在不太明显。
很棒的改进！

**Comment by lnaif** [comment]
@SCP-028 多说原本就是带有响应式的，所以不用考虑移动端，不过在移动端下表情栏有些超出屏幕

**Comment by ivan-nginx** [comment]
@lnaif dont understand u, write in English if not solved. If solved, close it please. Thank's!
