### ISSUE TITLE
这个是为什么了

### ISSUE THREAD

**Issue by CPUdream** [iissnan/hexo-theme-next#1185]
hexo g
INFO  Start processing
INFO  Files loaded in 1.53 s
WARN  No layout: 404.html
WARN  No layout: about/index.html
WARN  No layout: categories/index.html
WARN  No layout: resume/index - 副本.html
WARN  No layout: resume/index.html
WARN  No layout: tags/index.html
WARN  No layout: talks/index.html
WARN  No layout: resume/haha.html
WARN  No layout: 2016/10/12/Linux_qur/index.html
WARN  No layout: 2016/09/26/svn_git_sunny/index.html
WARN  No layout: 2016/09/25/android_service/index.html

**Comment by Neveryu** [comment]
这个我也不知道你做了什么，能说详细一点吗
或者是版本的升级变化?

**Comment by iissnan** [comment]
No layout 一个可能的原因是主题配置里填写的主题名字与主题目录未对应上。

例如，主题配置文件里写的是 `next`；而存放的目录名字是 `next-master`。

**Comment by CPUdream** [comment]
thx, 已经解决了

**Comment by lijiangwei** [comment]
@CPUdream 这个问题你是怎么解决的，我也遇到这个问题了，本地的代码没问题，从github源码取一份新的执行hexo g就报这个错误？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
