### ISSUE TITLE
是否有博文置顶的功能?

### ISSUE THREAD

**Issue by ErQi** [iissnan/hexo-theme-next#1186]
在使用说明,进阶内容,常见问题等中没有找到置顶的相关信息.
是否支持置顶功能?
若不支持时候考虑后续增加此功能?

**Comment by ehlxr** [comment]
可以自己修改一下
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#十、博文置顶

**Comment by ivan-nginx** [comment]
@ErQi dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by stevenjoezhang** [comment]
Fixed in hexojs/hexo-generator-index#51
