### ISSUE TITLE
部署到github后点击菜单栏跳转至http而非https

### ISSUE THREAD

**Issue by GoldyMark** [iissnan/hexo-theme-next#1187]
https://goldymark.github.io/

如上，是我部署的blog，点击`Program`后会跳转至`http`开头的url地址，而不是https，搜了一下`issues`，发现都没有解决这个问题，请问怎样才能正常访问？谢谢。

**Comment by Neveryu** [comment]
为什么我这边看没问题。好僵

**Comment by GoldyMark** [comment]
目前发现只有menu才有这个问题，首页的文章链接是没问题的。
而且查看生成的html发现，menu的href地址也是正确的（带https），但实际点击时却实际跳转到http:/xx.github.io/...。

发现以下两种情况下访问是正常的：

翻墙；
safari；

想知道当点击menu时会调用什么函数？ @Neveryu

**Comment by Neveryu** [comment]
@GoldyMark  你的博客哪有menu？

**Comment by GoldyMark** [comment]
由分类生成的menu
**themes/next/_config.yml**
```
menu:
  home: /
  program: /categories/program
  "music-drink": "/categories/music-drink"
  yiyan: /categories/一言
  categories: /categories
  archives: /archives
```
@Neveryu

**Comment by Neveryu** [comment]
@GoldyMark  我看了呀，我点进去都是 https ，没问题呀

**Comment by GoldyMark** [comment]
我用chrome和FF访问都有问题，safari则无问题。

或者我开了lantern或ss之后访问，也是无问题的。

感觉跟GFW或浏览器策略有关。

所以想从点击menu时调用的函数入手看看能不能解决。

**Comment by pengshp** [comment]
我的safari访问你的有问题啊！我的网站也是这样<https://pengshp.github.io>
![](http://ww1.sinaimg.cn/large/005QRDyvgw1f98ev8lilij30gg03z3yy.jpg)
或许你可以试试这个插件，装了访问就没问题了<https://www.eff.org/https-everywhere>
@GoldyMark

**Comment by GoldyMark** [comment]
好吧，我现在用safari访问自己的blog也有问题了……

这个插件只能让装了插件的人访问正常，但没装的访问还是有问题，不能治本。
@pengshp

**Comment by toutoudnf** [comment]
@Neveryu  我的是https://toutoudnf.github.io/，也存在这个问题。。不知该如何定位或者解决哈~

**Comment by toutoudnf** [comment]
btw~我是使用了shadowsocks，浏览器是chrome54.0.2840.71 m

**Comment by zonas0574** [comment]
我提过两个和这个相关，其中重装主题解决，过段时间又问题
这两个被我关，没人能解决
https://github.com/iissnan/hexo-theme-next/issues/1147
https://github.com/iissnan/hexo-theme-next/issues/1151

**Comment by toutoudnf** [comment]
@zonas0574 
我修改了配置文件如下：
`menu:
  home: https://toutoudnf.github.io
  categories: https://toutoudnf.github.io/categories
  about: https://toutoudnf.github.io/about
  archives: https://toutoudnf.github.io/archives
  tags: https://toutoudnf.github.io/tags
`
这样在github上就可用了

**Comment by zonas0574** [comment]
@toutoudnf 我试过，还是一样，除非浏览器强制https，但我在其他电脑打开还是一样，我不能保证看的人都强转了。
改不改这个配置，菜单跳转先到https，我chrome f12 查看过，它请求是https，返回code 301 Moved Permanently (from disk cache) ，然后跳转到http

**Comment by GoldyMark** [comment]
采用你的方案终于可以解决问题了！THX @zonas0574

**Comment by zonas0574** [comment]
解决就好~哈哈

**Comment by gdutxiaoxu** [comment]
zonas0574 
···java
menu:
  home: /
  #categories: /categories
  #about: /about
  archives: https://gdutxiaoxu.github.io/archives/
  tags: https://gdutxiaoxu.github.io/archives/tags
  #sitemap: /sitemap.xml
  #commonweal: /404.html

···
是修改成这样吗

**Comment by gdutxiaoxu** [comment]
@zonas0574
···java
menu:
home: /
#categories: /categories
#about: /about
archives: https://gdutxiaoxu.github.io/archives/
tags: https://gdutxiaoxu.github.io/archives/tags
#sitemap: /sitemap.xml
#commonweal: /404.html

···
是修改成这样吗

**Comment by tonydeng** [comment]
貌似，在github上进行配置就好了

Your Project-> Settings -> Enforce HTTPS




发件人: 徐俊 <notifications@github.com>
回复: iissnan/hexo-theme-next <reply@reply.github.com>
日期: 2016年12月9日 at 上午11:17:05
至: iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>
主题:  Re: [iissnan/hexo-theme-next] 部署到github后点击菜单栏跳转至http而非https (#1187)  

@zonas0574
···java
menu:
home: /
#categories: /categories
#about: /about
archives: https://gdutxiaoxu.github.io/archives/
tags: https://gdutxiaoxu.github.io/archives/tags
#sitemap: /sitemap.xml
#commonweal: /404.html

···
是修改成这样吗

**Comment by gdutxiaoxu** [comment]
@tonydeng 
![](http://7xvjnq.com2.z0.glb.qiniucdn.com/public/16-12-9/3837120.jpg)
我的project是这样的，现在不能设置，还是访问不了

**Comment by GoldyMark** [comment]
@gdutxiaoxu 
在url末尾加上`/`，如下：
```yaml
menu:
home: /
#categories: /categories/
#about: /about/
archives: https://gdutxiaoxu.github.io/archives/
tags: https://gdutxiaoxu.github.io/archives/tags/
#sitemap: /sitemap.xml
#commonweal: /404.html
```

**Comment by gdutxiaoxu** [comment]
好的，我试一下，谢谢
