### ISSUE TITLE
hexo g 执行崩溃

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#1188]
分支：master／v5.0.1/v5.1.0
1.拉下代码不做主题配置
2.hexo clean & hexo g  报错

> [error] HexoError: Render failed: css/main.css
> TypeError: /Users/lee/blog/themes/next/source/css/_variables/base.styl:60
>    56| // --------------------------------------------------
>    57|
>    58|
>    59| get_font_family(config) {
> 
> > 60|   custom_family = hexo-config('font.' + config + '.family')
> >    61|   return custom_family is a 'string' ? custom_family : null
> >    62| }
> >    63|
> 
> Cannot read property 'family' of undefined
> 
> ```
> at getProperty (/Users/lee/blog/node_modules/hexo-renderer-stylus/index.js:11:20)
> at Evaluator.<anonymous> (/Users/lee/blog/node_modules/hexo-renderer-stylus/index.js:19:12)
> at Evaluator.invokeBuiltin (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:979:30)
> at Evaluator.visitCall (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:488:16)
> at Evaluator.Visitor.visit (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
> at Evaluator.visit (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:157:18)
> at Evaluator.visitExpression (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:620:26)
> at Evaluator.Visitor.visit (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
> at Evaluator.visit (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:157:18)
> at Evaluator.visitIdent (/Users/lee/blog/node_modules/hexo-renderer-stylus/node_modules/stylus/lib/visitor/evaluator.js:528:22)
> ```

代码拉回到dev－5.0.0 正常

> leeMacBook-Pro:blog lee$ hexo -version
> hexo: 2.8.3
> os: Darwin 14.5.0 darwin x64
> http_parser: 2.6.0
> node: 5.5.0
> v8: 4.6.85.31
> uv: 1.8.0
> zlib: 1.2.8
> ares: 1.10.1-DEV
> icu: 56.1
> modules: 47
> openssl: 1.0.2e

**Comment by Neveryu** [comment]
感觉是版本升级带来的问题

**Comment by ivan-nginx** [comment]
@taoyuanxiaoqi dont understand u, write in English if not solved. If solved, close it please. Thank's!
