### ISSUE TITLE
dev/5.0.0分支 站内搜索配置功能异常

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#1189]
### Expected behavior (预期行为)

配置了搜索项之后 页面出现搜索按钮 点击搜索按钮 应当弹出搜索框 执行站内搜索功能
### Actual behavior (实际行为)

按照说明文档配置“Swiftype 站内搜索”后 出现了搜索按钮 但是点击按钮页面无明显变化 地址栏自动多出一个 # 符号  在localhost下显示 “localhost:4000/#”
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by Neveryu** [comment]
能看一下你的swiftype的配置吗，或者你注册了swiftype吗？
阅读一下这篇文章吧[Hexo-NexT搭建个人博客（二）](https://neveryu.github.io/2016/09/30/hexo-next-two/)

**Comment by taoyuanxiaoqi** [comment]
我之前功能都是好的 升级主题代码之后才出的问题

**Comment by Neveryu** [comment]
@taoyuanxiaoqi  那看来是版本升级带来的问题。  :smiley_cat:

**Comment by ivan-nginx** [comment]
@taoyuanxiaoqi dont understand u, write in English if not solved. If solved, close it please. Thank's!
