### ISSUE TITLE
busuanzi统计挂了？

### ISSUE THREAD

**Issue by WuXiaolong** [iissnan/hexo-theme-next#1192]
busuanzi统计似乎挂了，文章的阅读量和底部的访客量都显示不出来了

**Comment by tjuzl** [comment]
你好，不蒜子统计是正常的，也许是你设置出点问题，请参照官方文章验证。

**Comment by asdf2014** [comment]
这次是真挂了~~~

**Comment by asdf2014** [comment]
![image](https://user-images.githubusercontent.com/8108788/32991707-b8c75f3e-cd7b-11e7-9247-2a58b94bf446.png)

**Comment by ice1000** [comment]
我也发现了。。

**Comment by ice1000** [comment]
我这里也是502，然后显示不出点击量。但是
https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js
还是打得开。

**Comment by asdf2014** [comment]
哎，已经紧急切换到 learn cloud 了~~~

**Comment by asdf2014** [comment]
3年了，几十万的 pv 统计一夕之间全没了，，https://yuzhouwan.com/

![image](https://user-images.githubusercontent.com/8108788/32992383-edb9fc48-cd84-11e7-9853-c68d183b2e77.png)

**Comment by ice1000** [comment]
@asdf2014 卜算子现在修复了。

**Comment by asdf2014** [comment]
@ice1000 恩，谢谢告知哈，表示不敢用了，毫无征兆~~ 准备后面一直用 learn cloud 了~~

**Comment by ice1000** [comment]
其实是被攻击了

**Comment by ice1000** [comment]
开发者说的

**Comment by asdf2014** [comment]
好的吧，你是在哪里看到的哇，，可以理解，那我切换回来吧~~

**Comment by ice1000** [comment]
我给他发了邮件desuwa

**Comment by asdf2014** [comment]
@ice1000 哇，厉害，，是什么攻击，数据还在应该不是被提权了，是 DDoS 攻击么

**Comment by hzz1989** [comment]
learncloud 其实更不稳定，时不时会展示不出来。

**Comment by asdf2014** [comment]
@hzz1989 是的，第二天就回归 不蒜子 了~~ [https://yuzhouwan.com/posts/18517/](https://yuzhouwan.com/posts/18517/)
![image](https://user-images.githubusercontent.com/8108788/33410398-0a0e8cc2-d5bb-11e7-993e-429ce81be382.png)

**Comment by xu-song** [comment]
不同平台的pv统计能共享吗

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
