### ISSUE TITLE
多说分享用不了 ，链接是  yoursite.com

### ISSUE THREAD

**Issue by w698** [iissnan/hexo-theme-next#1193]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by Neveryu** [comment]
@w698  兄弟你怎么搞的啊，我这边好好的呀。[【转】在2016年学JavaScript是一种什么样的体验 ](https://neveryu.github.io/2016/10/16/how-it-feels-to-learn-javascript-in-2016/)
要不，你试试

**Comment by iissnan** [comment]
站点配置文件 _config.yml 里改下 `url` 的值
