### ISSUE TITLE
blockquote 配色修改

### ISSUE THREAD

**Issue by JonyFang** [iissnan/hexo-theme-next#1195]
![image](https://cloud.githubusercontent.com/assets/12381169/19711270/21380c6e-9b67-11e6-9f2a-c8b148740286.png)

上图箭头所指的位置，Markdown 内容为：
"> 第一种方式"
"> 对于单例类，一个类只有一个实例，在第一次访问实例的时候初始化这个实例，之后的访问直接获取已经创建好的实例即可"

这里我想修改 blockquote 区域的配色，可以在哪里修改 ~.~

**Comment by Neveryu** [comment]
@JonyFang 改的话应该还是很好改的，首先你要找到样式文件在哪，然后修改即可，
当然，你也可以参照 [这篇文章](https://neveryu.github.io/2016/09/03/hexo-next-one/) 里面的框框样式，因为我现在已经不再使用 `> xxxx` 了。

**Comment by JonyFang** [comment]
找到解决方法了
../next/source/css/_common/scaffolding/base.styl  line: 85中修改下 blockquote 就可以了。

不过还是感觉这样的 blockquote 太僵尸了... 

你博客中用的是自定义的 blockquote 吧 ~.~
