### ISSUE TITLE
怎么套用别人博客的模板？

### ISSUE THREAD

**Issue by songyibin** [iissnan/hexo-theme-next#1196]
我觉得默认的排版两边空白太多，所以照着[issue#759
](https://github.com/iissnan/hexo-theme-next/issues/759#issuecomment-202242848)修改好了，但是发现在移动端浏览器不适应，不知怎么设置，想知道能否用别人的当做模板套用，是直接看main.css吗？

**Comment by Neveryu** [comment]
@songyibin 可以看别人的 main.css 文件之后，然后尝试着自己实现。
如果实在不会，可以尝试询问别人能否提供源码

**Comment by songyibin** [comment]
@Neveryu 我找了一个和我网站设置差不多的[css文件](https://github.com/skycrown/skycrown.github.io/blob/master/css/main.css)，很长，不知怎么用到我的网站上，直接粘贴源码吗？

**Comment by Neveryu** [comment]
@songyibin  NO NO NO ， 你说的那个 css文件，是生成后的文件，是由源文件生成来的。
你需要的是源文件，然后执行 `hexo g` 就会生成一份你自己的css文件。
还有不明白的地方请看这里：[Hexo-NexT搭建个人博客（一）](https://neveryu.github.io/2016/09/03/hexo-next-one/)
或者给我留言也可以

**Comment by zhongjun96** [comment]
@Neveryu  访问了你的博客, 请问多说分享怎么设置的?  我的是这种 ,怎么修改成你那样不要展开的  而且我的右下角有重叠  ,你知道怎么修改吗?
![baidushurufa_2016-10-26_23-28-12](https://cloud.githubusercontent.com/assets/18225577/19732701/34065068-9bd4-11e6-817d-49522250d6db.png)
