### ISSUE TITLE
增加了文章宽度，在手机上无法横向显示

### ISSUE THREAD

**Issue by songyibin** [iissnan/hexo-theme-next#1197]
按照[issue#759](https://github.com/iissnan/hexo-theme-next/issues/759#issuecomment-202242848)加宽了文章宽度，在桌面端测试良好，但是在手机上显示不佳，要如何设置呢？
我的网站是songyibin.github.io

**Comment by Neveryu** [comment]
@songyibin  移动端请使用百分比，谢谢。
可以关注我的博客[https://neveryu.github.io/](https://neveryu.github.io/)文章，
后续会有内容更新，解决问题

**Comment by ivan-nginx** [comment]
@songyibin dont understand u, write in English if not solved. If solved, close it please. Thank's!
