### ISSUE TITLE
请问css发布失败，怎么拯救？

### ISSUE THREAD

**Issue by ljw-bigtail** [iissnan/hexo-theme-next#1199]
我改了css，hexo g，hexo s，之后可以在localhost：4000正常预览，但是hexo d之后我的样式就不见了，这是为什么？应该怎么解决？谢谢。

**Comment by Neveryu** [comment]
@ljw-bigtail   `hexo d` 这个命令执行成功了吗？有报错吗？

**Comment by ljw-bigtail** [comment]
执行成功，只是报了几个版本旧了的问题，但是可以正常发布。
我今天发现是浏览器缓存的问题。
现在可以正常浏览了。
谢谢。
