### ISSUE TITLE
新版本的很小问题？

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#120]
1 新版本在`苹果4S`下浏览  `发表时间``分类于``评论` 这三项，有些错位，不成一横排。就是间距变大了，希望改回来。
2 希望增加分享功能。
说真的next现有功能，对我来说真的够用了，但是好象习惯了，没事就上github看看next的情况.

**Comment by iissnan** [comment]
我会找个 iPhone 4s 测试下。分享预计会使用百度提供的分享服务。

**Comment by eurusd** [comment]
http://7xih93.com1.z0.glb.clouddn.com/001.png
在苹果4S下 不成一排,另起一排.   新版本才出现.

**Comment by minoscc** [comment]
![screen shot 2015-04-24 at 16 37 59](https://cloud.githubusercontent.com/assets/1515069/7315475/50fbd38c-eaa0-11e4-9125-e06e1ca8330a.png)

**Comment by eurusd** [comment]
minoscc 我现在用的不是新版本！

**Comment by iissnan** [comment]
分类的名称 或者 评论数 都可以可能导致换行。有一个方案是将评论换另一种展现形式

**Comment by eurusd** [comment]
哪种展现形式？

**Comment by iissnan** [comment]
Mobile 上现在已将菜单收缩。
分享支持 JiaThis 与 多说分享
