### ISSUE TITLE
多说评论框重叠

### ISSUE THREAD

**Issue by zhongjun96** [iissnan/hexo-theme-next#1200]
[演示地址](http://zhome.online/about/)
![baidushurufa_2016-10-26_23-33-18](https://cloud.githubusercontent.com/assets/18225577/19732804/9960760a-9bd4-11e6-8062-765dd15730ca.png)

**Comment by zhongjun96** [comment]
用IE访问发现分享框不存在了  
![baidushurufa_2016-10-26_23-19-55](https://cloud.githubusercontent.com/assets/18225577/19733023/4ef95d88-9bd5-11e6-87c3-7a213bc29218.png)

**Comment by zhongjun96** [comment]
需要登录后才能看到效果

**Comment by zhongjun96** [comment]
问题已经解决,在多说控制台自定义样式 `#ds-thread 
#ds-reset .ds-post-options .ds-sync {
    right: 110px;
}`

**Comment by ivan-nginx** [comment]
@zhongjun96 dont understand u, write in English if not solved. If solved, close it please. Thank's!
