### ISSUE TITLE
建议增加主题版本更新方案

### ISSUE THREAD

**Issue by Wangjunyu** [iissnan/hexo-theme-next#1201]
Master中主题的版本和Realse的版本不同，建议增加如何通过代码升级主题的方案到文档中。

**Comment by manyang901** [comment]
同建议

**Comment by Maples7** [comment]
#1290

**Comment by ivan-nginx** [comment]
@Wangjunyu dont understand u, write in English if not solved. If solved, close it please. Thank's!
