### ISSUE TITLE
tags页面打不开

### ISSUE THREAD

**Issue by itfanr** [iissnan/hexo-theme-next#1202]
我新建了tags页面。

在hexo server没问题，但是在github上会跳转到http，导致404。https://itfanr.github.io/
如何默认跳转到https？

谢谢！

**Comment by Neveryu** [comment]
@itfanr 
![](http://7xrn7f.com1.z0.glb.clouddn.com/16-10-27/43097526.jpg)

**Comment by itfanr** [comment]
@Neveryu  难道是我浏览器问题？

**Comment by Neveryu** [comment]
@itfanr 
应该我长的比较帅吧

**Comment by xiangcl** [comment]
@itfanr 你的tags页面是怎么设置的，我的啥显示都没有

**Comment by itfanr** [comment]
@xiangcl  需要new一个tags类型的post

**Comment by unsky** [comment]
这个问题我也遇到了，刚开始只有tags的时候是没问题的，但是自从我加上categories目录之后就挂了，再本地是没有问题的，但是deploy之后在github上就挂了。
后来检索了一下gothub上面的目录发现，不知道为啥他会pull上两个tag的文件夹，一个叫Tags,一个叫tags， 使用https://****.github.io/Tags/目录是正常的，但是使用https://****.github.io/tags/就会转到git404..
 
所以我在搞不清为啥会pull两个文件夹的情况下，做出如下的修改：
在_config.yml 里面将
menu:
  home: /
  categories: /categories
 # about: /about
  archives: /archives
  tags: /tags
强制修改为：
menu:
  home: /
  categories: /categories
 # about: /about
  archives: /archives
  tags: /Tags

对于根本原因，希望作者给一个原因
@iissnan

**Comment by itfanr** [comment]
@unsky 很赞啊！

**Comment by ZjVirus** [comment]
new 一个之后怎么写？ @itfanr

**Comment by itfanr** [comment]
@ZjVirus 

```
---
title: 标签
date: 2016-10-25 19:53:03
type: "tags"
comments: false
---

```

**Comment by OHLIA** [comment]
@itfanr 
为什么我
hexo new page "tags"

编辑
---
title: 标签
date: 2016-10-25 19:53:03
type: "tags"
comments: false
---

仍然是一片空白

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
