### ISSUE TITLE
主页显示文章遍数在那调

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#1205]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by dpast** [comment]
这位同学，建议这样的问题问问谷歌百度。答案如图
![](http://ww2.sinaimg.cn/mw690/006tuvCijw1f9bjjd9ofaj30s00iowg1.jpg)

**Comment by iissnan** [comment]
http://theme-next.iissnan.com/faqs.html#setting-page-size
