### ISSUE TITLE
如果打开主页时宽度小于991px，那么拉伸到991px+，菜单栏也不会出现

### ISSUE THREAD

**Issue by Jim-Zenn** [iissnan/hexo-theme-next#1208]
### Expected behavior (预期行为)

![screen shot 2016-10-31 at 10 03 13](https://cloud.githubusercontent.com/assets/7279131/19863392/509147a8-9f51-11e6-857f-b1043d286f82.png)

### Actual behavior (实际行为)

![screen shot 2016-10-31 at 10 03 06](https://cloud.githubusercontent.com/assets/7279131/19863399/55f4196e-9f51-11e6-8dc0-dc9ce83681c3.png)

### Steps to reproduce the behavior (重现步骤)

1. 在宽度小于 991px 的浏览器窗口打开
2. 将窗口宽度拉伸至 992px 以上，菜单栏（左侧，不显示）

![screen shot 2016-10-31 at 10 03 06](https://cloud.githubusercontent.com/assets/7279131/19863500/acf484b0-9f51-11e6-943f-560ac61eeb0d.png)

![screen shot 2016-10-31 at 10 02 55](https://cloud.githubusercontent.com/assets/7279131/19863472/9360c8ce-9f51-11e6-8fff-9e1a7f8eae0b.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

**Comment by ivan-nginx** [comment]
@Jim-Zenn dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by ivan-nginx** [comment]
Already fixed in 5.1.3.
