### ISSUE TITLE
新建的文章不能生成分类

### ISSUE THREAD

**Issue by kcoewoys** [iissnan/hexo-theme-next#1209]
### Expected behavior (预期行为)
在文章标题下面和分类页面下生成类

### Actual behavior (实际行为)
没有生成

### Steps to reproduce the behavior (重现步骤)
vi source/_posts/5_Raspberrypi系统安装.md
```
---
title: Raspberrypi系统安装
date: 2016-11-01 09:42:07
tags: [raspberrypi]
categoreis: [linux,raspberrypi,sldfa,aslf]

---
```
vi source/categories/index.md
```
---
title: categories
type: categories
comments: false
date: 2016-10-24 14:56:25

---
```

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  - ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  ✔Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
win7 64位 chrome ubuntu16.04虚拟机
```
# Theme version
version: 5.0.2
```
试了很多次，就是不生成，tags生成正常，现在改老log的类，可以正常生成分类；新建上一篇的时候也是不生成类，后来改名等等什么的，不知道怎么就好了

**Comment by kcoewoys** [comment]
我每次生成是用的命令
```
rm db.json
hexo clean && hexo g
```

**Comment by xitoe** [comment]
你这 `categoreis: [linux,raspberrypi,sldfa,aslf]` 还真多.....

在 `source/categories/index.md` 里 `type: categories` 改成 `type: "ategories" 试试？？加引号

**Comment by kcoewoys** [comment]
@xitoe 一样的，在`public/categories/`还是没有生成我要的类的文件；增加以前文章的类都可以正常生成，但是新的文章不行；我觉得问题应该不在这几个配置文件了

**Comment by kcoewoys** [comment]
好伤心啊
没人遇到这个问题吗
http://kcoewoys.top

**Comment by iissnan** [comment]
`categoreis: [linux,raspberrypi,sldfa,aslf]`

`categoreis` -> `categories`

**Comment by kcoewoys** [comment]
好笨啊   哈哈哈

**Comment by kcoewoys** [comment]
我改了模板文件，里面可能拼错啦
