### ISSUE TITLE
post 内文章转换后非 HTML文件,无文件类型, `hexo g -d` 正常

### ISSUE THREAD

**Issue by xitoe** [iissnan/hexo-theme-next#1211]
之前是正常的，增加 coding 路线部署后开始出现这问题
已按搭建流程重新来过，问题依旧

**问题具体情况**：

* `hexo g -d` 过程信息正常
* 转换后的文件内容为正常的 html 文件格式，但文件类型 **非 HTML**，**无文件后缀**
* 其他目录 md 文件处理正常，仅 `_post` 中 md 文章有问题

不好意思哈各位，英语不好，不好意思把问题放 hexo issue那，只好跑这儿了

**Comment by kcoewoys** [comment]
本地生成看一下：
```
rm db.json
hexo clean && hexo g
```

**Comment by xitoe** [comment]
@kcoewoys 试过了，问题依旧，public 目录下文章文件还是无类型的

**Comment by kcoewoys** [comment]
@xitoe 哈哈哈哈 我只是路过；按理说增加coding 路线部署只是和`hexo d`有关吧，这样假设的话，你就肯定还改了其它的；顺便求看一下我的问题啊 [1209](https://github.com/iissnan/hexo-theme-next/issues/1209)
