### ISSUE TITLE
Failed to Deploy Generated Site

### ISSUE THREAD

**Issue by shuokay** [iissnan/hexo-theme-next#1213]
### Expected behavior (预期行为)
The online site should be same with local generated by command `hexo server -s`

### Actual behavior (实际行为)
Nothing showed in the online site. But if I change to the default `landscape` theme, everything goes well. Even the default NeXT config also comes to this problem.

### Steps to reproduce the behavior (重现步骤)

1. Set the theme to next

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  ✔All schemes
  -  ✔Muse
  -  ✔Mist
  -  ✔Pisces

### Other Informations (Like Browser, System, Screenshots)

Browser: chrome, firefox. Both are latest version.
System: Ubuntu 16.04 LTS
Screenshots: Using Pisces.
![image](https://cloud.githubusercontent.com/assets/5029591/19955425/476130e0-a1bc-11e6-97d2-79878e705fbb.png)

**Comment by unsky** [comment]
和我遇到的问题一样。。。昨天没问题，今天就不行了。。是不是ｇｉｔｈｕｂ　ｐａｇｅｓ　有什么更新

**Comment by johanzhu** [comment]
我今天也遇到这个问题了。。

**Comment by FerminYang** [comment]
+1

**Comment by funaihui** [comment]
+1

**Comment by iissnan** [comment]
Please see #1214

**Comment by iissnan** [comment]
Please update NexT theme to the latest commit.
