### ISSUE TITLE
本地预览没问题，deploy后主页显示大面积空白

### ISSUE THREAD

**Issue by unsky** [iissnan/hexo-theme-next#1214]
本地预览没问题，但是deploy到github之后，主页，只显示个空白背景，还有几个字,　
我的主页，　unsky.github.io
昨天还好好的，今天就挂了，尝试换了别的主题deploy没问题，一换NexT就挂..

**Comment by unsky** [comment]
求救。。

**Comment by FerminYang** [comment]
和我的问题一样http://blog.dongderu.net，似乎是vendors目录在github pages下都变成404了，但是文件确实在repo里。

**Comment by Neveryu** [comment]
@unsky 兄弟你好，你这个问题应该是在部署的时候文件上传存在丢失造成的，建议重试。
详情：(Hexo-NexT搭建个人博客（二）)[https://neveryu.github.io/2016/09/30/hexo-next-two/]
(Hexo-NexT搭建个人博客（一）)[https://neveryu.github.io/2016/09/03/hexo-next-one/]

**Comment by FerminYang** [comment]
@Neveryu 应该不是文件丢失，文件在REPO里，估计是github pages更新了。

**Comment by MoHenYunJi** [comment]
我的也是,next主题空白，折腾一上午，你换成原始的那个landscape就好了

**Comment by xiaoxionglaoshi** [comment]
我擦 我的也是这样  今天上午突然就成这样了  重建了好几遍也没用,换别的主题就没事

**Comment by caiyue1993** [comment]
+1，今天早上更新文章时也出现同样的情况

**Comment by funaihui** [comment]
我的也是，今天更新文章出现的问题

**Comment by funaihui** [comment]
http://www.wizardev.com只显示一点点

**Comment by funaihui** [comment]
http://www.wizardev.com

**Comment by funaihui** [comment]
我的也是这种情况

**Comment by solverpeng** [comment]
我也是这样的情况。

**Comment by solverpeng** [comment]
https://solverpeng.github.io/

**Comment by solverpeng** [comment]
求救啊啊啊啊啊！

**Comment by meilihu** [comment]
+1

**Comment by robocoderhan** [comment]
我的[github pages](https://robocoderhan.github.io/)也出现了这种情况

**Comment by jzy476731162** [comment]
+1

**Comment by jzy476731162** [comment]
我刚才切了一下别的主题.然后generate并且deploy上去.之后又切回来clean了一下重新g,d就可以了.哎呦沃日,真恶心呢

**Comment by zfmy** [comment]
https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

 Jekyll now ignores the vendor and node_modules directories by default.

**Comment by Littlombie** [comment]
+1，这是主题的问题么？

**Comment by iissnan** [comment]
是

**Comment by iissnan** [comment]
不清楚为什么 GitHub Pages 过滤掉了 `source/vendors` 目录的访问。我提交了一个更新到 `master` 分支上，修正这个问题，可以更新下。

也可以手动将 `source/vendors` 目录修改成 `source/lib` （或者其他的名称，只是 lib 我测试了可以使用）；同时，修改下主题配置文件`_config.yml`， 将 `_internal: vendors` 改成你所修改的名字，例如 `
_internal: lb`。

**Comment by Littlombie** [comment]
亲测，按照上边的方法试了 ，好了

**Comment by solverpeng** [comment]
nice

**Comment by henryhoo** [comment]
@iissnan 添加了还是不行，只能把头像显示出来 用的是Pisces主题。也试过https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3中添加include的方法，还是不行

**Comment by Ryancheung91** [comment]
@henryhoo  改成lib后我测试测试是好的，你再试一下

**Comment by Gong-Elory** [comment]
找到解决方案了。。 根据作者的提示 @iissnan ，首先修改source/vendors为source/lib，然后修改_config.yml， 将 _internal: vendors修改为_internal:lib 然后修改next底下所有引用source/vendors路径为source/lib。这些地方可以通过文件查找找出来。主要集中在这几个文件中。1. Hexo\themes\next.bowerrc 2. Hexo\themes\next.gitignore 3. Hexo\themes\next.javascript_ignore 4. Hexo\themes\next\bower.json 。修改完毕后，刷新重新g一遍就ok啦。 @FerminYang @Neveryu @MoHenYunJi @xiaoxionglaoshi @unsky

**Comment by itabas016** [comment]
大部队原来在这里😂😂😂

**Comment by yhhwpp** [comment]
@Gong-Elory 这么麻烦。 直接更新作者的master分支就行了。

**Comment by kcoewoys** [comment]
有些人把`.deploy_git`，`.gitignore`删掉了，不能更新；
照着作者的提交改 [Rename source/vendors to source/lib](https://github.com/iissnan/hexo-theme-next/commit/565c09f6a45c75ffb8f74c88270b72fbe6e1a6e0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28)
不要忘了改文件夹名字

**Comment by crazy-canux** [comment]
Perfect.

**Comment by chping2125** [comment]
改了一上午，没找到问题出在哪里。想到过可能是github不让读该文件了，由于不熟悉next的主题源码，就没改。朋友今天一说，果然在这找到大神膜拜。

**Comment by chping2125** [comment]
改了一上午，没找到问题出在哪里。想到过可能是github不让读该文件了，由于不熟悉next的主题源码，就没改。朋友今天一说，果然在这找到大神膜拜。

**Comment by crazy-canux** [comment]
5.0.0 升级到5.0.2后， 有几个问题，第三方的工具都没有了。

多说评论不见了。
swiftype搜索不能用了。
cnzz统计不见了。

不过jiathis可用。

**Comment by Lision** [comment]
- -今天更了一篇文章就白屏了，偶尔还404……，换了主题就好了

**Comment by lhp9916** [comment]
昨晚这个问题弄了好几个小时，原来是github的问题，先把主题切换回去了，希望作者早点解决问题。谢谢

**Comment by AlphaGao1993** [comment]
手动将 source/vendors 目录修改成 source/lib ；同时，修改下主题配置文件_config.yml， 将 _internal: vendors改成_internal: lib
然后 clean g d来一边搞定了

**Comment by leofee** [comment]
前几天我配置了webpack，昨天更新文章的时候就是好多404，我还以为是hexo跟wabpack冲突了，我重装了系统，又重装了hexo，结果还是不行，结果就在网上找错误代码，结果就顺藤摸瓜到这了，原来大部队在这啊~终于解决了~

**Comment by caoqiwen2001** [comment]
我的也是，重新生成之后source/vendors 这个文件夹都不见了，奇怪了。

**Comment by hellozjf** [comment]
更新主题后已解决问题，多谢楼上各位

**Comment by Gong-Elory** [comment]
@yhhwpp 我修改了一些CSS样式的，如果更新他的分支的话，我的样式不就被覆盖了啊。

**Comment by veryitman** [comment]
吓屎了, 还以为我欠费了.

**Comment by enderdzz** [comment]
在这里终于找到解决方法了，thx！

**Comment by carlosfu** [comment]
leancloud 变为了401 403 有人知道怎么回事吗

**Comment by veryitman** [comment]
按照作者的说法.我的问题解决了.
解决步骤如下:
1. 备份原来的 next 目录.
1. 在 next 目录, 执行 git pull, 如果出现文件冲突(你修改),请先记录自己修改过的文件.
2. git pull 结束后, 重新 hexo g hexo d
3. 等会打开自己的网站.

**Comment by yhhwpp** [comment]
@Gong-Elory  要提前备份下

**Comment by uniqueyehu** [comment]
终于找到解决的办法了，赞一个！

**Comment by NoahDragon** [comment]
似乎是最近Jekyll更新造成的，可以通过添加.nojekyll文件来解决。
https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

**Comment by lijianfeigeek** [comment]
@AlphaGao1993 正解~

**Comment by shuangziliuyun** [comment]
终于找到大部队了，正解啊，确实解决了这个问题

**Comment by tmirun** [comment]
找了半天原来问题在这里, 先给上面解决问题的的小伙伴们赞一个

**Comment by Hclmaster** [comment]
已经解决了，多谢分享方法~

**Comment by suregm** [comment]
+1

**Comment by xjpz** [comment]
有部署到Coding.net的朋友吗，按照上面的办法还是没有解决。

**Comment by lixiansky** [comment]
@xjpz 我部署的Coding 没有问题啊 版本是5.0.0

**Comment by MIAOXIAOGE** [comment]
能说的都被你们说了，我就静静地看把。。。

**Comment by hhstore** [comment]
## 坑:

- 妈蛋, github 好坑.
- 昨天晚上发布博客, 一更新,全挂了, 页面刷不出来. chrome 看一下, 不少404.
- 以为是 github CDN 的问题, 等等吧.
- 结果然并卵...


## 魔怔:

然后就开始下述循环了:

> 重装 next 插件, 然并卵...
> 重装 hexo, 然并卵...
> 重装 nodejs, 然并卵...
> 升级 nodejs, 然并卵...
> 中间又碰到 hexo 高版本的问题, 坑爹...

> 昨天搞了一天啊! WTF!
> 今天又搞了1上午哇!
> 今天又想去 coding.net 上部署下,对比看看原因, 结果 coding.net 的演示服务,暂时关停. WTF!
> 
> 然后, 就在刚刚, 用 chrome 仔细看了下报的 error.
> 发现那几个 vendor 下的 css,js 文件, 明明在 github 仓库里. WTF!
>
> 然后就知道操蛋了... 
> 昨天没有留意这个 issue 哇. 今天又浪费了一上午.

**Comment by yhhwpp** [comment]
@hhstore 所以一出现问题，第一时间查看issue。

**Comment by hhstore** [comment]
@yhhwpp 

- 初以为是自己的问题.
- 主要是最近 Mac 清理了 IDE 的索引, 结果部分项目的 lib 应该是被误删除.
- 导致很多项目, 都挂了, 又重新配置的项目环境.

> 不巧的是 blog 项目也是, hexo 命令, 一上来就不好使.
> 我也没在意, git 有记录, 重新装下 hexo 呗.
> 然后, 想都没想, 就推了.
> 推上去, 一片空白, 这还不是最糟糕的, 后面我手贱, 验证问题原因, 把 `.deploy_git` 目录删了.
> 再推, 发现github 上, blog 项目的 commit 提交记录, 给清空了! 30多条 commit, 变2条!
>
> so 叼!
> 想想本地有 git 管理, 忍了!

> 跑上来, 根据报错, 看了几个 issue, 可惜没看到这条.
> 刚刚搜索才看到这条. ==!

**Comment by hhstore** [comment]
@iissnan  @yhhwpp @unsky 


## 目前最简单的解决办法:

- 参考: issue: https://github.com/iissnan/hexo-theme-next/issues/1220

- 步骤:
    - `.deploy_git` 目录, 添加 `.nojekyll ` 空文件
    - `source`目录, 添加`.nojekyll` 空文件
    - 修改 Hexo 上层`_config.yml`配置文件, 添加

```
include:
  - .nojekyll

```

- 重新部署推送: `hexo d -g`

**Comment by czhzero** [comment]
按楼上的方法，我在github pages上面实验成功了，但是coding.net上面托管的博客还是不行，有人知道什么原因么

**Comment by absentm** [comment]
@iissnan Thanks a lot, I got it. fixed:  vendors ---> lib

**Comment by zouzls** [comment]
@hhstore nice！
看来以后只要是hexo next的问题来大本营就能找到解决方案了。
博客已恢复：http://zouzls.github.io/

**Comment by lihongxiangleo** [comment]
终于中找到了解决办法，我擦Google大法好啊！折腾了我一上午了！

**Comment by TracerLee** [comment]
@hhstore 你的答案最中肯！

**Comment by errorlife** [comment]
@hhstore ths,然后请问怎么创建一个空的文件，提示必须键入文件名，所以我直接download你的下来了。
我的博客也恢复了: http://steffan.cn

**Comment by haoyuanliu** [comment]
赞一个赞一个  终于恢复了！

**Comment by ictar** [comment]
@hhstore 真是太太太太感谢了！！！！！

**Comment by laogangde** [comment]
只有我在IE下出现这个问题么？用的是5.1.0版本主题，IE9下本地和GitHub都显示大面积空白。chrome内核浏览器没问题。

**Comment by unsky** [comment]
@laogangde  清清浏览器缓存

**Comment by laogangde** [comment]
@unsky 依旧。我在想，是我曾经修改过哪里么。[ http://519wm.cn]( http://519wm.cn)[]

**Comment by unsky** [comment]
@laogangde  在我win10自带的ie上你的网站是正常的

**Comment by laogangde** [comment]
@unsky thanks，我win7 IE9不行，360兼容模式也不行。就这样吧，不折腾了。反正也没打算给多少人看。自留地

**Comment by crazy-canux** [comment]
PC端的更新后确实没有问题了，但是移动端貌似还是看不到内容。
any idea?

**Comment by ZhouShisong** [comment]
已经没有source/vendors这个目录了，然而提交到github还是不行啊，没有样式折腾好久了

**Comment by errorlife** [comment]
@ZhouShisong 你可以看看@hhstore 的第一条

**Comment by Agenric** [comment]
<img width="254" alt="2017-07-08 2 23 56" src="https://user-images.githubusercontent.com/11513056/27971262-9377bc3a-6384-11e7-9982-054f4934e67d.png">

![image](https://user-images.githubusercontent.com/11513056/27971311-d09bbd28-6384-11e7-9171-84a86a971c23.png)


xxx.com/tags 显示内容不正常，但是xxx.com/tags/xxx 显示正常，证明索引已经建立，但是tags主页不显示，想问一下大概怎么回事？

**Comment by HarleyWang93** [comment]
我的情况是：本地预览正常，在线预览只有文本，无样式，查看network有很多JS没有获取到。
我跟@ZhouShisong应该是一样的情况。
现在应该已经不存在vendors这个问题了。

**Comment by onlyfly34** [comment]
原來也是遇到一片空白的問題，後來發現是_config.yml沒配置好
URL部分設定成https://xxxx.github.io/Repository-Name
root設定成/Repository-Name/
解決!

**Comment by Georginaaaa** [comment]
我也出现这样的问题//clean g d了很多次   最后d没有显示任何问题  但就是没有效果
但是我没有用jekyll。。可以直接用hexo的？

**Comment by MARGI3** [comment]
同样的问题，现在的配置已经是  source/lib 了，但是 git push之后lib目录里面的 js css文件 还是不见了，本地都是ok的

**Comment by liuli1735** [comment]
@MARGI3 我也是同样的问题，还没解决

**Comment by MARGI3** [comment]
@liuli1735  去新的 issue 地址下留言吧，https://github.com/iissnan/hexo-theme-next/issues/2066#issuecomment-356619545   。 难受

**Comment by monster-gump** [comment]
一个一个看 总还是有解决办法的

解决办法总结贴

1.  @iissnan 作者本人提出的，按理来说最新版本的 hexo 应该没有这个问题
可以手动将 source/vendors 目录修改成 source/lib （或者其他的名称，只是 lib 我测试了可以使用）；同时，修改下主题配置文件_config.yml， 将 _internal: vendors 改成你所修改的名字，例如 _internal: lib。

2. @hhstore 贡献，上次我出错使用这个方式，主要会显示几个 css js 文件找不到
步骤:
.deploy_git 目录, 添加 .nojekyll 空文件
source目录, 添加.nojekyll 空文件
修改 Hexo 上层_config.yml配置文件, 添加
include:
  - .nojekyll

重新部署推送: hexo d -g

3. 这次除了问题之后尝试了1， 然后更新了 hexo 和 next 的版本，最后 hexo clean 暂时解决了

为什么说是暂时呢，因为还是有几个图片没找到_(:з」∠)_ 挂的很莫名，下次再看了

https://monster-gump.github.io/

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
