### ISSUE TITLE
文章页标题的问题

### ISSUE THREAD

**Issue by ansediao** [iissnan/hexo-theme-next#1215]
### Expected behavior (预期行为)

文章页中 使用 ## 表示一级标题 #### 表示二级标题

### Actual behavior (实际行为)

这样混排时，目录部分会发生混乱。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
似乎是一个已存在的 Hexo bug。

**Comment by yhhwpp** [comment]
这个 我也经常遇到  一级 与二级标题间 不能跳跃。比如一级 为 # 标示 那么二级就用 ##。

**Comment by ivan-nginx** [comment]
@ansediao dont understand u, write in English if not solved. If solved, close it please. Thank's!
