### ISSUE TITLE
挂载在域名子目录 下的博客，搜索结果路径问题

### ISSUE THREAD

**Issue by laoqiren** [iissnan/hexo-theme-next#1216]
### Expected behavior (预期行为)
next主题搜索功能，搜索内容打开，博客挂载在子目录如:xxxx.com/code，预期搜索文章路径为:
http://xxx.com/code/2016/08/22/xxxxxxx

### Actual behavior (实际行为)
搜索帖子的连接为http://xxx.com/code/code/2016/08/22/xxxxxxx

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Latest Release 

NexT Scheme:
  -  All schemes

**Comment by flashlab** [comment]
插件更新下试试

**Comment by ivan-nginx** [comment]
@laoqiren dont understand u, write in English if not solved. If solved, close it please. Thank's!
