### ISSUE TITLE
博客中js无法加载

### ISSUE THREAD

**Issue by monsterLin** [iissnan/hexo-theme-next#1217]
### Expected behavior (预期行为)
博客应该正常加载

### Actual behavior (实际行为)
现在博客主题无法正常加载

### Steps to reproduce the behavior (重现步骤)
添加了新博客，无法正常加载

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master 
  -  Latest Release ✔  
  -  Old version 

### Other Informations (Like Browser, System, Screenshots)

我的网站是：http://monsterlin.com

**Comment by monsterLin** [comment]
我的博客的js错误信息：
![错误信息](http://images.cnblogs.com/cnblogs_com/boy1025/689108/o_QQ%E6%88%AA%E5%9B%BE20161103222254.png)

**Comment by monsterLin** [comment]
本地测试没问题，提交到github就出现这个问题

**Comment by SpadeRoy** [comment]
我是这样，挂载到网络上就不行了，本地可以 @iissnan

**Comment by Gong-Elory** [comment]
我也遇到这样的问题了啊  不知道什么原因

**Comment by Gong-Elory** [comment]
我的博客http://gelory.me   遇到跟前面几位一样的问题。貌似和我的操作没有关系啊

**Comment by BBBOND** [comment]
同样也是这个问题，无法加载js

**Comment by Gong-Elory** [comment]
找到解决方案了。。 @BBBOND @monsterLin @SpadeRoy 根据作者的提示 @iissnan ，首先修改source/vendors为source/lib，然后修改_config.yml， 将 _internal: vendors修改为_internal:lib 然后修改next底下所有引用source/vendors路径为source/lib。这些地方可以通过文件查找找出来。主要集中在这几个文件中。1. Hexo\themes\next\.bowerrc  2. Hexo\themes\next\.gitignore 3. Hexo\themes\next\.javascript_ignore 4. Hexo\themes\next\bower.json 。修改完毕后，刷新重新g一遍就ok啦。

**Comment by yhhwpp** [comment]
我也是前天好好的，发布了一篇博客 vendors下的静态资源全都加载不了了……

**Comment by yhhwpp** [comment]
@Gong-Elory  为何要把 vendors 重命名为 lib 才可以呢。前几天好好的

**Comment by yhhwpp** [comment]
已经 看到 #1214 的解决方案了

**Comment by Gong-Elory** [comment]
作者说是禁用了这个路径的访问，改成其他路径就行了，也可以取别的名字

发件人:
发送时间: 2016年11月4日 9:48
收件人: iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>
抄送: Zhiqiang Gong <elory0513@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [iissnan/hexo-theme-next] 博客中js无法加载 (#1217)


@Gong-Elory<https://github.com/Gong-Elory> 为何要把 vendors 重命名为 lib 才可以呢。前几天好好的
