### ISSUE TITLE
有关博客传到github css js 404的问题 解决方案！！！

### ISSUE THREAD

**Issue by imkratos** [iissnan/hexo-theme-next#1220]
Thanks for reaching out! We recently updated to Jekyll v3.3, which ignores the vendor folder by default. If you're not using Jekyll, you can add a .nojekyll file to the root of your repository to disable Jekyll from building your site. Once you do that, your site should build with your vendor folder.

各位，这是我给github官方邮件，他们的回复，就是在根目录下加一个.nojekyll 资源就可以访问了。
但是如果.nojekyll加在source文件夹内，不会被hexo 生成出来，不知道各位谁有解决办法？

**Comment by monsterLin** [comment]
那你就放到public 文件夹下试试

**Comment by BBBOND** [comment]
我试过了 但是发现.nojekyll没有被push上来@monsterLin

**Comment by imkratos** [comment]
@BBBOND  所以我现在暂时的解决方案是手动在github上加。。。hexo d 之后，手动在github页面创建

我还没时间去研究一下源码，不知道各位谁知道呢，哈哈哈。

**Comment by BBBOND** [comment]
我在public 和 .deploy_git 里都加上了.nojekyll 然后 deploy 就可以了@imkratos

**Comment by imkratos** [comment]
@BBBOND 恩，我明白了，因为. deploy_git 里的东西是要往git上push的，所以添加了.nojekyll之后，hexo程序并不会处理，但是会提交上来，哈哈。多谢。

**Comment by guoyiang** [comment]
可以在source目录里加入`.nojekyll`文件，然后更改**Hexo**的`_config.yml`加入以下配置：
```yaml
include:
  - .nojekyll
```
这样在`hexo -g`的时候就会包含`.nojekyll`文件了

**Comment by linkcd** [comment]
@guoyiang 这样的确可以保证public文件夹里面有.nojekyll文件, 但是最后在git_deploy文件夹里面，这个文件还是没有被拷贝过去。我还在找解决方法

**Comment by imkratos** [comment]
@linkcd  现在最简单的办法是更新一下主题 next的代码，源码已经改名了，改成lib目录了，如果更新代码不方便的话，我现在的做法是把这个文件加在.develop_git目录里，现在是可以用的。

**Comment by MisterZhai** [comment]
在.deploy_git 里加上了.nojekyll 后，就可以上传上去了，我的现在可以了

**Comment by yuqirong** [comment]
请问 .nojekyll 文件里面要写什么东西吗？还是一个空文件？

**Comment by imkratos** [comment]
@yuqirong 空文件就可以。

**Comment by monster-gump** [comment]
不得不说这个真是太坑了 我还以为我自己配置哪里出了问题 折腾了大半天 deploy 几十次最后只好换 landsacpe 了_(:з」∠)_ 现在再试试看

**Comment by SimleCp** [comment]
@imkratos 请教一下如果更新next主题的代码, 更新后, 原来的配置和数据是否会丢失?

**Comment by SimleCp** [comment]
@imkratos 请教一下如何更新next主题的代码?     更新后, 原来的配置和数据是否会丢失?

**Comment by imkratos** [comment]
@SimleCp 这个就是git的基本使用问题啊，如果你改了和源码里有冲突的话，是更新不下来的，git会提示让你提交你的修改，然后再更新。

**Comment by SimleCp** [comment]
@imkratos  直接更新了代码 已经弄好了. 忘记当时是怎么安装主题了 所以才问的怎么更新主题代码.  ^-^

**Comment by kaito-kidd** [comment]
在.deploy_git里加上.nojekyll，部署是有效的。

**Comment by CPUdream** [comment]
我加进去也不行，怎么回事了，有点懵逼了

**Comment by fgcui1204** [comment]
同问，加进去了也不行。

**Comment by imkratos** [comment]
@CPUdream @fgcui1204 能提供更详细的信息吗，你们查看下github 分支上 那个文件在根目录了吗

**Comment by fgcui1204** [comment]
@imkratos 已找到解决方案，根据 #1214

**Comment by ivan-nginx** [comment]
@imkratos dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by segmafrontend** [comment]
我的情况是这样：
问题：本地预览正常，部署到github，无法显示头像、图标等，打开控制台显示加载lib目录下的文件404
分析：public下的lib目录和next/source下的lib目录内容一致，next目录指向另一个git，且next目录下的.gitignore文件下设置了对next/source/lib目录下一些文件的忽略导致未上传到github
解决：删除next目录下的.git文件夹，删除next目录下.gitignore里面和next/source/lib有关的部分
有关hexo的安装、自动打包部署、评论插件，欢迎来我的博客交流，[西格马技术分享](https://segmafrontend.github.io/)
