### ISSUE TITLE
菜单项的 首页 分类 留言 标签点击都不起作用

### ISSUE THREAD

**Issue by Douylon** [iissnan/hexo-theme-next#1223]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Douylon** [comment]
在谷歌浏览器的F12 查看 ，那几个是空连接。但是我都是按照要求新建的 也在主题文件下边设置了

**Comment by zhongjun96** [comment]
新建了这些文件夹吗

**Comment by tjuzl** [comment]
提供的信息不足

**Comment by imkratos** [comment]
参见这几个https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E5%88%86%E7%B1%BB%E9%A1%B5%E9%9D%A2，我就是根据wiki调好的，一开始我的也是找不到标签页，按这个wiki就搞好了。

**Comment by tankgit** [comment]
我也有这个问题，不过不知道和你情况是否完全一样，我已经有自己的解决方案，见 [issue #1280](https://github.com/iissnan/hexo-theme-next/issues/1280)

**Comment by gauxonz** [comment]
有人有解决方案了嘛？

**Comment by ivan-nginx** [comment]
@Douylon dont understand u, write in English if not solved. If solved, close it please. Thank's!
