### ISSUE TITLE
MarkDown 搭配 html 会产生宽的分隔符

### ISSUE THREAD

**Issue by BBBOND** [iissnan/hexo-theme-next#1224]
### Expected behavior (预期行为)
能够在markdown内容后，紧接着显示html

### Actual behavior (实际行为)
能够在markdown内容后，有一大块留白，然后才显示html

### Steps to reproduce the behavior (重现步骤)
在md文件中写类似如下内容：
```
* xxxxxxxxx

<table>
  <tr>
    <th>xxx</th>
    <th>XXX</th>
  </tr>
</table>
```

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Master 

NexT Scheme:
  -  All schemes

**Comment by BBBOND** [comment]
@iissnan

**Comment by BBBOND** [comment]
找到解决方法了，得要把table里面的所有换行和空格都去掉，否则会产生大量留白。

**Comment by iissnan** [comment]
这是 Hexo 的一个问题。
