### ISSUE TITLE
不能在无序列表内嵌套有序列表

### ISSUE THREAD

**Issue by ImVictorCheng** [iissnan/hexo-theme-next#1226]
### Actual behavior (实际行为)
我的markdown代码：

    -   aaa
        aaaa
    -   bbb
        1.  bbbb
        2.  bbbbb

![1](https://cloud.githubusercontent.com/assets/20416460/20037867/de6eb6d4-a463-11e6-9cad-a9713317641e.JPG)
显示结果：
![2](https://cloud.githubusercontent.com/assets/20416460/20037866/de362f44-a463-11e6-95d5-becd89066ae0.JPG)
换别的主题没有问题，所以应该不是Hexo本身的bug
另外在有序列表内嵌套无序列表，或者在有序列表内嵌套有序列表都没问题

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
✔  -  Latest Release
  -  Old version - 

NexT Scheme:
✔  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
Chrome浏览器和Edge浏览器都有问题，win 10系统

**Comment by tjuzl** [comment]
暂时不要加空格以满足需求吧

**Comment by ImVictorCheng** [comment]
但是不加空格就不是嵌套了吧
        - a
        aa
        aaa
        1. aaaa
        2. aaaaa
        bbb
        3. bbbb
![image](https://cloud.githubusercontent.com/assets/20416460/20044493/6d62b85c-a4d4-11e6-8868-fb5bdb25e2d5.png)
![image](https://cloud.githubusercontent.com/assets/20416460/20044500/755b89ee-a4d4-11e6-89f4-1e7c7b467d4c.png)

**Comment by tjuzl** [comment]
...那只有再多加点空格符了

**Comment by ImVictorCheng** [comment]
所以就是假造一个列表的意思嘛。。。

**Comment by tjuzl** [comment]
要不就试试换 Markdown 的渲染引擎？但我不知道在哪里

**Comment by CalvinNeo** [comment]
+1，而且类似这样的似乎也不能正常处理
```
1. a
    text for a
    1. a1
    2. a2
    
    text for a
    1. a3
    2. a4
2. b
3. c
```
渲染后是
![image](https://cloud.githubusercontent.com/assets/5670241/20460384/4e5c160a-af1b-11e6-9855-38494a8f6393.png)

**Comment by ivan-nginx** [comment]
@ImVictorCheng dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by silencial** [comment]
@ivan-nginx nesting an ordered list in unordered list can't produce expected outcome

for example, we want the outcome of the following

    - aaa
        1. bbb

to be 
- aaa
    1. bbb

however it is
- aaa
    - bbb

**Comment by ivan-nginx** [comment]
@silencial can u please recreate same issue in [NexT repo](https://github.com/theme-next) if this issue in this repo still exist?

**Comment by stevenjoezhang** [comment]
请升级到新版：https://github.com/theme-next/hexo-theme-next
此问题已被修复
