### ISSUE TITLE
关于最近部署后空白的问题，请问怎么更新next主题呢？

### ISSUE THREAD

**Issue by Michael728** [iissnan/hexo-theme-next#1227]
请教，更新next主题的命令是什么呢？

**Comment by Neveryu** [comment]
git pull https://github.com/iissnan/hexo-theme-next themes/next

**Comment by Michael728** [comment]
执行这个更新，会把之前的配置项覆盖吗？担心需要重新配置

**Comment by imkratos** [comment]
不更新主题的解决方案[#1220](https://github.com/iissnan/hexo-theme-next/issues/1220)

**Comment by unsky** [comment]
https://github.com/iissnan/hexo-theme-next/issues/1214

**Comment by Michael728** [comment]
我知道已经说得解决方案，就是将主题文件夹下的source文件夹的文件夹改为lib，还有配置文件也改为lib，我想请教的是，git pull https://github.com/iissnan/hexo-theme-next themes/next 更新主题，会将我的主题配置文件覆盖吗？担心不备份的情况下，会将之前的配置丢失了

**Comment by flashlab** [comment]
@Michael728 备份一下总是没错的

**Comment by imkratos** [comment]
@Michael728 博主，我说的方案你看了吗？那个并不是改文件夹名的，是加一个.nojekyll文件在根目录，这样也不用更新主题的源码的。

**Comment by ivan-nginx** [comment]
@Michael728 dont understand u, write in English if not solved. If solved, close it please. Thank's!
