### ISSUE TITLE
有可供选择的markdown渲染主题吗?

### ISSUE THREAD

**Issue by deweixu** [iissnan/hexo-theme-next#1228]
默认的渲染主题颜色都很素雅比如：超链接和`` 这个两种语法的渲染

**Comment by yhhwpp** [comment]
修改主题颜色 可以在  `/source/css/_variables/base.styl`里修改

**Comment by deweixu** [comment]
`// Global link color.
$link-color                   = $black-light
$link-hover-color             = $black-deep
$link-decoration-color        = $grey-light
$link-decoration-hover-color  = $black-deep`

我修改了这里，菜单栏的链接和文章的标题链接都变了，我只想要文章内容里面的链接改变

@yhhwpp

**Comment by yhhwpp** [comment]
通过css 控制。 加上前缀试试。

**Comment by ivan-nginx** [comment]
@deweixu dont understand u, write in English if not solved. If solved, close it please. Thank's!
