### ISSUE TITLE
侧边栏的文章目录有问题

### ISSUE THREAD

**Issue by ererermao** [iissnan/hexo-theme-next#1229]
### Expected behavior (预期行为)
1. 一级标题1
  1.1 二级标题1
2. 一级标题1
  2.1 二级标题1

### Actual behavior (实际行为)
1. 一级标题1
  1.1 二级标题1
- 2. 一级标题1
  2.1 二级标题1

### 其他情况
当只有一级标题的时候就是正常的

**Comment by ererermao** [comment]
@iissnan  求助

**Comment by ererermao** [comment]
找到原因了，是由于一级标题和二级标题用的#个数问题，详细参考[#1215](https://github.com/iissnan/hexo-theme-next/issues/1215)

**Comment by pthtc** [comment]
最后怎么解决的?

**Comment by ererermao** [comment]
@pthtc  一级 与二级标题间 不能跳跃。比如一级 为 # 标示 那么二级就用 ##。

**Comment by pthtc** [comment]
@ererermao 修改之后依然后有这个问题

**Comment by iissnan** [comment]
标题的嵌套不能跳级
