### ISSUE TITLE
HTTPS下点击页面自动跳转HTTP

### ISSUE THREAD

**Issue by shidangai** [iissnan/hexo-theme-next#123]
这个应该不是issue，但是我不知道怎么解决。。。
进入blog后是开启https的，但是此时点击任意一个page(比如about)，跳转过去链接就会换成http。
如果直接输入https:..../about却又可以开启https访问。
不知哪位能指点一下，先谢过了:)

**Comment by eurusd** [comment]
请问，https如何加上的？谢谢。 我用的是hexo+github=blog
有教程吗？

**Comment by shidangai** [comment]
github的链接自带https。
但是如果是自己的域名就不行。

eur <notifications@github.com> 於 2015年4月23日 星期四寫道：

**Comment by shidangai** [comment]
@eurusd 
github的链接自带https。
但是如果是自己的域名就不行。

**Comment by eurusd** [comment]
懂了

**Comment by iissnan** [comment]
主题内的链接都是协议无关的。 GitHub Pages 在页面跳转的时候做了一次 301，不知道用意如何。我找到了一个方案，使用脚本来强制跳转，详见： https://github.com/sunlightlabs/congress/commit/6426761a671d46df6fc5d2526bdaf506c39d789c

**Comment by shidangai** [comment]
@iissnan 我猜是给服务器减负。GitHub本意也不是提供hosting吧。
请问。。这个是要修改哪个文件？唯一的default.html并不在theme文件夹下。

**Comment by iissnan** [comment]
可以在 `layout/_scripts` 目录下加一个 script，然后在 `layout/_layout.swig` 中 `include` 进去。

**Comment by shidangai** [comment]
@iissnan 不知为何还是没有解决。。我也懒得弄了。麻烦你了，谢谢。

**Comment by rumusan** [comment]
你好，这个问题解决了吗，我也遇到了。

**Comment by ftdejo** [comment]
之前遇到这个问题消失了现在又莫名其妙这样了··求官方解决方案

**Comment by ftdejo** [comment]
同遇到这个问题，有官方解决方案吗？
