### ISSUE TITLE
使用next出现问题

### ISSUE THREAD

**Issue by qianlongo** [iissnan/hexo-theme-next#1230]
### 如图

![sdafadf](http://odssgnnpf.bkt.clouddn.com/E5F2DFCB-739B-42E2-98C0-5F2EC8249381.png)

请问这是怎么回事。

**Comment by thundertrick** [comment]
+1
出现同样问题，现在暂时换成landscape以保证网站正常访问。
盼解决。

**Comment by iissnan** [comment]
#1214 和 #1220
