### ISSUE TITLE
Next主题，hexo d上传github pages，页面变成空白

### ISSUE THREAD

**Issue by flystarhe** [iissnan/hexo-theme-next#1231]
### Expected behavior (预期行为)
hexo s，本地测试内容正常显示
hexo d，提交后github pages也应该显示正常才对

### Actual behavior (实际行为)
github pages页面显示为空白
示例：https://flystarhe.github.io/

### Steps to reproduce the behavior (重现步骤)
访问：https://flystarhe.github.io/

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by cp0000** [comment]
我也遇到同样的问题了，请问你找到解决方法了么

**Comment by djyde** [comment]
我看了你 blog 没有问题啊

**Comment by thundertrick** [comment]
看看log，应该是 [#issue1230](https://github.com/iissnan/hexo-theme-next/issues/1230) 吧。

P.S.
我看了你的博客也没问题。

**Comment by newleidy** [comment]
怎么解决的，看来要换主题了。

**Comment by zhongjun96** [comment]
@newleidy  更新源码就行了

**Comment by thundertrick** [comment]
@zhongjun96 使用最新源码，测试了master和5.1.0分支，现在可以显示内容了，但是渲染全无。console仍然提示`vendors/` 下部分js找不到。同见 #1230

**Comment by thundertrick** [comment]
解决办法： #1220

**Comment by innote** [comment]
@thundertrick 5.1.0, 那裡可以下載？ 能給個網址？

**Comment by yhhwpp** [comment]
#1224

**Comment by flystarhe** [comment]
我琢磨了很久，最后把旧的删除，把主题目录全部更新了一遍（就好了）
具体问题我也不清楚
 @djyde @thundertrick

**Comment by flystarhe** [comment]
@cp0000 删除主题目录，重新下载一份新的

**Comment by thundertrick** [comment]
@innote 5.1.0当前代码库的一个分支，我理解既然单独分出来那应该是开发完了？

**Comment by thundertrick** [comment]
@flystarhe 最近的版本已经把`vendors`目录改名为`libs`目录，所以不会有白屏问题。我的博客不好拉最新节点，所以直接在`.deploy_git/`目录下创建一个`.nojekyll`的空文件即可。博客说明：http://zhishuo.info/2016/11/04/使用hexo生成博客在github-js-css-404解决方案/

**Comment by innote** [comment]
@thundertrick， 我問的是那裏可以找到5.1.0的下載點， 而不是分不分支！

**Comment by thundertrick** [comment]
@innote 5.1.0是当前`iissnan/hexo-theme-next.git`的一个分支，获取方法：
博客根目录下运行
```
git clone https://github.com/iissnan/hexo-theme-next.git themes/next510
cd themes/next510
git checkout 5.1.0
```

**Comment by innote** [comment]
@thundertrick 謝謝！。。。

**Comment by pthtc** [comment]
直接vender改为lib就好
