### ISSUE TITLE
cloudapp图床私密链接无法显示,普通链接可以显示

### ISSUE THREAD

**Issue by nianxiaoge** [iissnan/hexo-theme-next#1232]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@nianxiaoge dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
This issue is about a image hosting service named cloudapp. No valuable info is provided.
