### ISSUE TITLE
不可以设置中文标签和中文分类吗？

### ISSUE THREAD

**Issue by maxmeng93** [iissnan/hexo-theme-next#1233]
### Expected behavior (预期行为)
设置好中文标签和中文分类，hexo server下预览是正确的。

### Actual behavior (实际行为)
但是上传到服务器后显示

>Not Found
>The requested URL /index.php was not found on this server.

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by unsky** [comment]
在_config.yml里面设置
language: zh-Hans 就行了

**Comment by yhhwpp** [comment]
可以的，如上楼操作

**Comment by maxmeng93** [comment]
![](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lnhjy8raj308403374l.jpg)
已经设置了。具体情况是这样子：
可以看到分类中已经有中文了，但是点进去就出问题了：
![](http://ww2.sinaimg.cn/large/005VWk7Ogw1f9lnj9grhmj30s70em0tx.jpg)
![](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lnkkmwf3j30jo0a1my1.jpg)

**Comment by maxmeng93** [comment]
![设置](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lnhjy8raj308403374l.jpg)

**Comment by maxmeng93** [comment]
已经设置了：
![](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lnhjy8raj308403374l.jpg)
具体情况是这样子：
下图可以看到分类中已经有中文了
![](http://ww2.sinaimg.cn/large/005VWk7Ogw1f9lnj9grhmj30s70em0tx.jpg)
但是点击，进入就会出错
![](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lnkkmwf3j30jo0a1my1.jpg)

请问，这是怎么回事？ @yhhwpp @unsky @

**Comment by unsky** [comment]
刚刚看了你以下你博客仓库里面得文件，发现你得tags，categories 都没有生成。
正常情况下得文件夹应该是：
![image](https://cloud.githubusercontent.com/assets/15643995/20125700/2e435388-a66a-11e6-8c7c-96bf8efe7cb8.png)
建议执行
hexo clean
hexo g
hexo s -p3600
再本地查看之后看效果。
之后deploy.
再执行hexo g 时候，你可以看看public文件夹里
是否有
![image](https://cloud.githubusercontent.com/assets/15643995/20125752/8fbd0c26-a66a-11e6-81e2-1d4bb759bb14.png)
如果没有，说明你已经把主题改胡了，建议更新作者主题。

**Comment by yhhwpp** [comment]
`hexo clean` 并且删除.deploy_git文件夹之后，然后重新编译发布试试。

**Comment by maxmeng93** [comment]
@unsky 那些文件夹都有了，因为英文的分类是没有错误的，只有中文的会发生错误。
@yhhwpp 重新编译发布了，还是不行。
我刚刚发现问题了，打开ftp看了看上传到服务器上的文件，中文乱码了。
![](http://ww3.sinaimg.cn/large/005VWk7Ogw1f9lotf0itnj30fk0aimzd.jpg)

**Comment by yhhwpp** [comment]
是不是编码的问题，新建md文件时， 设置 utf-8试试

**Comment by maxmeng93** [comment]
文件没有问题，是上传的时候出问题了，我把ftp的字符集改为强制 UTF-8，就可以了。 @yhhwpp

**Comment by yhhwpp** [comment]
恩 还是编码的问题。已经解决了吧？

**Comment by unsky** [comment]
@maxmeng93  额 我都是用git bash 上传，编辑器用得atom, 不支持utf-8的工具就会造成乱码，，

**Comment by maxmeng93** [comment]
因为这里是要上传的自己的服务器，所以没有用命令行工具。一般我是在webstorm设置好ftp的地址，然后上传到空间，我现在要研究下，是服务器不支持UTF-8还是webstorm上传时出错了。 暂时是有解决方法了，但是麻烦点，看看有没有一劳永逸的方法。 @unsky @yhhwpp

**Comment by yhhwpp** [comment]
应该是服务器的问题。因为你本地 `hexo s`是正常的。

**Comment by maxmeng93** [comment]
webstrorm里的ftp里的编码设置为UTF-8就好了。
