### ISSUE TITLE
local-search挂掉了，看调试是括号不匹配

### ISSUE THREAD

**Issue by yun-percy** [iissnan/hexo-theme-next#1234]
报错报在 hexo-theme-next/layout/_scripts/third-party/localsearch.swig的 158行

(index):790 Uncaught SyntaxError: Unexpected token )

**Comment by flashlab** [comment]
可是没有这么多行= =  可以贴下完整信息吗？

**Comment by yun-percy** [comment]
5.1.0分支的159行

**Comment by yun-percy** [comment]
好像掉了还不止一个括号……一共52个"{"但是只有48个"}"

**Comment by flashlab** [comment]
是有问题，你可以用主分支的文件替换掉

**Comment by yun-percy** [comment]
希望尽快fix。不清楚里面的逻辑，还是很希望用上新功能:)

**Comment by iissnan** [comment]
已在 Master 分支修正
