### ISSUE TITLE
一样一样的

### ISSUE THREAD

**Issue by yanlee26** [iissnan/hexo-theme-next#1237]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
这是什么意思啊 。。。

**Comment by innote** [comment]
@Neveryu 他是說， Muse，Mist，Pisces 這三個主題都一樣。

**Comment by Neveryu** [comment]
@innote 你这样我就很尴尬了呀，NexT才能称之为主题好么

**Comment by innote** [comment]
@Neveryu 哈哈。。我打錯。。主題裏的三個布景 都一樣

**Comment by lixiansky** [comment]
确实是

**Comment by iissnan** [comment]
hexo clean 后再试试
