### ISSUE TITLE
正文页面宽度怎么加大

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#124]
博客正文内容宽度太小了，sidebar关掉之后看着别扭。开了sidebar也看到旁边白边过宽，不是很舒服。怎么加大一点？谢谢！

**Comment by eurusd** [comment]
进入`themes\next\source\css\_variables\base.styl`  修改$content-desktop                = 700px的值

**Comment by wongxingjun** [comment]
OK，多谢
