### ISSUE TITLE
代码高亮宏无效

### ISSUE THREAD

**Issue by Grapedge** [iissnan/hexo-theme-next#1240]
### Expected behavior (预期行为)
对C++ 代码进行高亮

### Actual behavior (实际行为)
#include 或 #define 等语言特有关键字无法正常高亮

### Steps to reproduce the behavior (重现步骤)
开启代码高亮并测试如下代码
```cpp
#include <cstdio>
#define maxn 1001

int main () {
    printf ("Hello, Next\n");
}
```

### NexT Informations

NexT Version: 5.0.1

**Comment by Neveryu** [comment]
:tada:

**Comment by iissnan** [comment]
似乎 Hexo 内置的 highlight.js 对于 C/C++ 的高亮支持并不是很好。

**Comment by ivan-nginx** [comment]
@Grapedge dont understand u, write in English if not solved. If solved, close it please. Thank's!
