### ISSUE TITLE
deploy后github 仓库老是生成不存在的文件夹，见鬼了~~~

### ISSUE THREAD

**Issue by unsky** [iissnan/hexo-theme-next#1241]
hexo 本地生成的文件是正常的 只有tags 没有Tags.
![image](https://cloud.githubusercontent.com/assets/15643995/20175013/c2a0b9aa-a77b-11e6-9632-5058124046f7.png)
上传到github 之后
![image](https://cloud.githubusercontent.com/assets/15643995/20175057/ec7c04aa-a77b-11e6-88f2-698e19698790.png)
就会莫名生成Tags文件夹，
在
![image](https://cloud.githubusercontent.com/assets/15643995/20175080/0564f1b6-a77c-11e6-93b8-07f5bf22ed9e.png)
本地d的 deploy.git里面也是不存在Tags的。
这就导致了在打开 在博客***.github.io/tags 会404
但是打开 ***.github.io/Tags 是正常的。。
这到底什么鬼，会怎懂生成Tags这个文件夹。。

**Comment by unsky** [comment]
进一步的发现原因，在本地的时候tags文件夹里有index.html 和各种标签的文件， 但是在上传的到github之后，tags被拆分为两块，一块是index.html 被存在Tags里，一块是标签文件，存在 tags文件里。。。这是肿么了....

**Comment by iissnan** [comment]
把你本地的 .deploy_git 目录删掉再重新 deploy

**Comment by unsky** [comment]
已经删掉了，没有毛用。。。@iissnan

**Comment by ivan-nginx** [comment]
@unsky dont understand u, write in English if not solved. If solved, close it please. Thank's!
