### ISSUE TITLE
建议：修改侧边栏标签和分类链接的显示逻辑。

### ISSUE THREAD

**Issue by Wangjunyu** [iissnan/hexo-theme-next#1242]
# 现状
如果要想让[侧边栏](http://blog.junyu.pro/)的“分类”、“标签”变成链接。就必须在设置好分类与标签的页面之后，在上方的菜单显示才可以。

我尝试过如果把菜单的“分类”、“标签”隐藏，右侧侧边栏的分类和标签不再能够点击。

# 建议
建议把两者的关联取消，只要建立了分类、标签的页面，右侧就可以点击链接进入对应的页面

# 原因
如果一定要两边同时设置，会显得累赘，破坏整个博客的美感。

**Comment by Neveryu** [comment]
主题只是一个普遍的设计，你的这个需求可以自己动手，自定义来实现，具体做法可以参考文章：[Hexo-NexT搭建个人博客（二）](https://neveryu.github.io/2016/09/30/hexo-next-two/)

**Comment by iissnan** [comment]
为了描述方便，我将侧栏的分类和标签信息 称为 **分类信息**，将菜单中的分类和标签称为 **分类菜单“。

从你的建议来说，**分类信息**带链接的唯一条件是建立了分类/标签页面。但分类/标签这两个页面并非 Hexo 内置的，是用户自己创建的，也就意味着这两个页面的地址实际上是变数（例如 `hexo new page cats`），主题并不知道这两个页面的确切地址。

因此从代码角度来看，目前**分类信息**的链接是依赖于 **分类菜单** 链接的设置（即让用户自己指定这两个页面的地址）。

**Comment by Pkuflint** [comment]
参考 Neveryu 博客中的办法：[https://neveryu.github.io/2016/11/11/hexo-next-three/]()
把theme-next-layout-macro-slider.swig 里面的这段代码：
```         
          {% if site.categories.length > 0 %}
            <div class="site-state-item site-state-categories">
              {% if theme.menu.tags %}<a href="{{ url_for(theme.menu.tags) }}">{% endif %}
                <span class="site-state-item-count">{{ site.categories.length }}</span>
                <span class="site-state-item-name">{{ __('state.categories') }}</span>
              {% if theme.menu.tags %}</a>{% endif %}
            </div>
          {% endif %}
```
改为：
```
          {% if site.categories.length > 0 %}
            <div class="site-state-item site-state-categories">
             <a href="{{ url_for(theme.menu.tags + '/categories') }}">
                <span class="site-state-item-count">{{ site.categories.length }}</span>
                <span class="site-state-item-name">{{ __('state.categories') }}</span>
              </a>
            </div>
          {% endif %}
```

删除掉原来的 if 语句，同时需要在 url_for 语句里面，补充添加上'/tags' 和'/categories'。不然实际改完后，链接是主页本身。在原来的代码里，url_for 的语句也是依赖 menu 的设置的。

类似的，tags 页面也是这样改。

**Comment by Wangjunyu** [comment]
@iissnan  明白了。
@Neveryu  @Pkuflint  感谢建议，已经调整完毕: [浚宇的博客](http://blog.junyu.pro)

@iissnan  建议更新到 官方文档，方便大家自己手动调整。

**Comment by Wangjunyu** [comment]
@iissnan 

是否可以考虑修改判断逻辑，如果已经存在tags、categories 页面，侧边栏就链接到对应的页面。如果不存在则保持无链接的状态，而不是通过menu是否新增对应的页面来判断？

**Comment by iissnan** [comment]
@Wangjunyu 你说的对。我更新了判断条件，只要检测到有 `type: categories` 的页面存在，就以此检索结果的第一个页面作为链接附加到 **分类信息** 上。标签信息同理。
