### ISSUE TITLE
hexo s后预览空白

### ISSUE THREAD

**Issue by Forecheng** [iissnan/hexo-theme-next#1246]
### Expected behavior (预期行为)
hexo s后，能在本地看到完整页面

### Actual behavior (实际行为)
hexo s后，只能看到底部信息，页面全白，slideBar单击不了，能看到分类和标签页面，就是看不到文章。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.1.0

  -  Master
 

NexT Scheme:

  -  Mist

### Other Informations (Like Browser, System, Screenshots)
Browser：chrome
System ：win10

**Comment by auroraflash** [comment]
#1214 
主题的_config.yml 
将 _internal: vendors 改成_internal: lib

**Comment by richardweiu** [comment]
使用 --debug  参数之后可以看到 vendors 下的 js 基本都是 404，昨天看到一个 issue 说的是作者已经将修改提交到 master 了，不知道为啥还是没有改

**Comment by Forecheng** [comment]
@auroraflash 感谢，明白了。

**Comment by Neveryu** [comment]
@richardweiu 不知道你是用的哪种处理方式，你可以看下我的这种处理方式，简单易操作 :v:

**Comment by simincai1996** [comment]
我的在本地预览成功，但github.io页面空白，采用了这个方法，也可以。
这种方法的原理是什么啊

**Comment by iissnan** [comment]
@richardweiu 我合并 5.1.0 分支时候造成的问题，目前已修复了。
@simincai1996 详见 #1214
