### ISSUE TITLE
文章发表时间显示了两遍

### ISSUE THREAD

**Issue by yuan-ji** [iissnan/hexo-theme-next#1249]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/19479448/20245227/25016310-a99d-11e6-94c3-2da842f967c4.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/19479448/20245252/971fe782-a99d-11e6-8bce-b918aa70372b.png)

### Steps to reproduce the behavior (重现步骤)
每新建一个文档时间就显示两遍；
更换scheme无效
换回landscape日期正常

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master： 5.1.0

NexT Scheme:

  -  Pisces

**Comment by kovlento** [comment]
我也遇到这问题了

**Comment by innote** [comment]
@yuan-ji 其實是對的， `Posted on 2016-11-04  |  2016-11-04  ` 第一個日期， 是你`create`， 第二個日期是你有沒有`modify` 過你的文章。

**Comment by kovlento** [comment]
@innote 那如果不想显示modify的时间呢？

**Comment by yuan-ji** [comment]
@innote 可是参见其他人都是只显示一次啊，有可以屏蔽modify的选项么

**Comment by innote** [comment]
@yuan-ji 5.1.0 才會有， 其它版本不會看到

@kovlento 如果你要拿掉， 可以去`layout/_macro` 裏面的`post.swig`， 
有一段關於
```
 </span>
            <time title="{{ __('post.modified') }}" itemprop="dateModified" datetime="{{ moment(post.updated).format() }}">
              {{ date(post.updated, config.date_format) }}
            </time>
```
delete 掉。 就可以了

**Comment by yuan-ji** [comment]
@innote 嗯，问题解决，十分感谢！

**Comment by kovlento** [comment]
@innote 问题解决了 THX！！

**Comment by iissnan** [comment]
加了一组 setting：

```yml
# Post meta display settings
post_meta:
  created_at: true
  updated_at: false
  categories: true
```
