### ISSUE TITLE
正文左右对齐出现问题

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#125]
有时候正文段落不能完全居中对齐，右边参差不齐，@iissnan博客也有这种情况http://notes.iissnan.com/2015/code-and-pray/      ，影响美感，怎么修正一下？

**Comment by eurusd** [comment]
同感。

**Comment by wongxingjun** [comment]
有办法没？我觉得这个主题风格不错，但是不喜欢默认字体，再有就是我提出的两个问题。

**Comment by eurusd** [comment]
https://github.com/iissnan/hexo-theme-next/issues/111 字体修改。

**Comment by iissnan** [comment]
```
.post-body { text-align: justify }
```

**Comment by wongxingjun** [comment]
无效啊

**Comment by iissnan** [comment]
正文文本已设置成 `justify`，请更新试试。

**Comment by wongxingjun** [comment]
感谢@iissnan问题已经解决
