### ISSUE TITLE
更改博客标题的黑色背景样式

### ISSUE THREAD

**Issue by GuaiShu** [iissnan/hexo-theme-next#1251]
![image](https://cloud.githubusercontent.com/assets/14322982/20246367/72427d50-a9f0-11e6-979a-c223adb3bbc9.png)
怎么更改这个标题的黑色背景，比如四个角是不规则的曲线。我在网上看到过一次那种样式。
NexT Version:
  -  Latest

NexT Scheme:
  -  Muse

**Comment by Neveryu** [comment]
这种需求，完全可以自己写css来实现。
:dango:

**Comment by GuaiShu** [comment]
@Neyeryu,具体点呢。我刚用hexo。不了解文件结构。这个主题对应的css样式应该在哪里修改？谢啦！

**Comment by Neveryu** [comment]
@GuaiShu 打开浏览器，F12，查看元素，就可以知道这个标题的样式在哪了，可以修改源码样式，改成你想要的样式，也可以单独再写样式，覆盖源码中的样式。:smile:

**Comment by iissnan** [comment]
你看到可能是很早的版本或者自定义过的版本，主题的 CSS 都在 `source/css` 目录下。
