### ISSUE TITLE
代码块高亮的问题还是没有解决 只是部分颜色发生改变 怎么样才能和Sublime上显示的一样 万分感谢解答

### ISSUE THREAD

**Issue by guardLtw** [iissnan/hexo-theme-next#1253]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by xovel** [comment]
代码高亮模块不是该主题核心关注的部分，你的需求可以通过自定义代码高亮库完成。

**Comment by supertiny99** [comment]
'''[对应的代码语言]
'''
例如：
'''javascript
'''

**Comment by ifelseboyxx** [comment]
'''
例如：
'''javascript
'''
这么设置代码高亮后

` 文本 `

这样设置的也跟着高亮了，怎么能不跟着？

**Comment by ivan-nginx** [comment]
@guardLtw dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by JewSaten** [comment]
站点配置文件_config.yml
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

主题的配置文件_config.yml
修改你想要的高亮风格
# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night bright

文章里面
```
code
```
