### ISSUE TITLE
mist怎样不让显示categoties英文和改变分类的排列方式？

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#1255]
怎样在分类按钮下，不让显示“categories”英文，并且改变分类的排列方式成类似以下
不懂前端，还望高人指教。
![image](https://cloud.githubusercontent.com/assets/6941795/20309430/e543c79e-ab82-11e6-98b4-eb294fa0fb0f.png)
![image](https://cloud.githubusercontent.com/assets/6941795/20309468/05db84d8-ab83-11e6-87cf-96f700938cc0.png)

**Comment by innote** [comment]
@wongxingjun 你有把`language`在`站点配置文章` 改成華文嗎？

```
language: en
```
如果你要華文， 把`en`改成`zh-Hans`， 你也可以參考這[篇文章](http://theme-next.iissnan.com/getting-started.html#select-language)

**Comment by wongxingjun** [comment]
有在站点配置中文的，但是还是显示英文categories，中文也有，就像只要中文，不要英文的

**Comment by innote** [comment]
@wongxingjun, 可以給我看下你的blog嗎？ 如果你已經改了， 應該是ok的。

**Comment by wongxingjun** [comment]
找到问题了，应该是language下的menu取名问题，主题包里是category: 分类，应该是categories，我觉得新版不太满意，还是改回旧版了，blog就我的github page

**Comment by innote** [comment]
@wongxingjun 對不起呀， 沒幫到忙。 新版改了少許東西，還要一小段時間去適應。

**Comment by wongxingjun** [comment]
没事，还是多谢
