### ISSUE TITLE
本地预览没问题，hexo d部署到GitHub上就显示不出来

### ISSUE THREAD

**Issue by vainfeng** [iissnan/hexo-theme-next#1256]
### Expected behavior (预期行为)
本地预览和部署到gitpage上显示一样才对

### Actual behavior (实际行为)
本地预览没有问题，但是使用hexo d部署到git上去的时候，就是一片白屏

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:  3.2.2

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme: Pisces
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by innote** [comment]
@vainfeng 這個問題很多人發布了， 你尋下就有解決的發布文了。

**Comment by Neveryu** [comment]
@vainfeng #1220 
或者看我的博客中的解答：[关于github屏蔽vendors ，导致页面空白的解决方案](https://neveryu.github.io/2016/11/11/hexo-next-three/#%E4%B8%89%E3%80%81%E5%85%B3%E4%BA%8Egithub%E5%B1%8F%E8%94%BDvendors-%EF%BC%8C%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)
