### ISSUE TITLE
NEXT目录标题显示错误

### ISSUE THREAD

**Issue by pthtc** [iissnan/hexo-theme-next#1259]
### Expected behavior (预期行为)

标题栏按序显示

### Actual behavior (实际行为)

标题2可跳转正确位置，只是显示错误

![](https://d17oy1vhnax1f7.cloudfront.net/items/0I1E0J2g0z1C2m0x2x08/屏幕快照%202016-11-15%20下午2.25.05.png?v=4a1b65e5)

### Steps to reproduce the behavior (重现步骤)

按照[#1215](https://github.com/iissnan/hexo-theme-next/issues/1215)修改，按次序排列标题，但是没有任何改变

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes

**Comment by xovel** [comment]
是不是bug这里就不说了，说一下解决方案：

修改博客markdown源代码，避免出现**跨级标题结构**。

> 这里的*跨级*指的是不能从一个一级标题直接跟三级标题；二级标题后紧跟的子标题级别必须是三级标题。

这个问题是因为`hexo`在处理目录生成的时候调用的底层代码来自于一个叫做[`cheerio`](https://github.com/cheeriojs/cheerio)的插件，~~该插件不能愉快的处理跨级标题的情况~~。（目录的具体代码在`...\node_modules\hexo\lib\plugins\helper\toc.js`，如有兴趣，可以留言继续讨论。）

> 刚才去看了一下你的博客源码，你的这一篇文章中，正文的第一条一级目下的，最后一个三级目录，跟在后面的是五级目录，所以在解析成HTML代码的时候已经出现了差错。

-----

另外提供另一种**不建议采用**的处理方案：修改侧边栏的样式效果。强行指定右侧目录下面的所有元素都带有`text-align: left`的样式。

`...\themes\***\source\css\_common\components\sidebar\sidebar-toc.styl`（***为你采用的主题名称），添加这一句代码：

```styl
.post-toc *{ text-align: left!important; }
```

> 不建议使用这样的方式，修改markdown来的更加直接，也更加直观。

**Comment by pthtc** [comment]
@xovel 多谢，已经修改标题，确实是我的问题

**问题解决O(∩_∩)O**

**Comment by swordspoet** [comment]
我设置了side-bar隐藏，那么我可以让目录在文章里面显示吗？

**Comment by iissnan** [comment]
@swordspoet Obviously not. But you can customize the post template to support toc.

**Comment by JohnnyLuv** [comment]
嗯，我也遇到了这个问题，已经解决了，
我的一级标题用的 ##
二级标题用的是 ####
导致文章目录导航不能正常显示。
☆⌒(*＾-゜)v THX!!
