### ISSUE TITLE
tag出现问题

### ISSUE THREAD

**Issue by readpan** [iissnan/hexo-theme-next#1260]
### Actual behavior (实际行为)

出现  "Cannot GET /tags/"的页面

### Steps to reproduce the behavior (重现步骤)
点击标签后

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Latest Release

NexT Scheme:
  -  All schemes

**Comment by readpan** [comment]
我对web前端不太了解，哪位能帮我下呢

**Comment by iissnan** [comment]
http://theme-next.iissnan.com/theme-settings.html#tags-page

**Comment by readpan** [comment]
额,貌似是我没有手动添加tags的html文件,但是还有个小问题请教一下, 这个手动添加,是在generate之前添加还是在之后的release中添加呢?

**Comment by readpan** [comment]
@iissnan 感谢您的回答, 貌似是我没有手动添加tags的html文件,但是还有个小问题请教一下, 这个手动添加,是在generate之前添加还是在之后的release中添加呢?

**Comment by readpan** [comment]
@iissnan 感谢您的回答

**Comment by ivan-nginx** [comment]
@readpan dont understand u, write in English if not solved. If solved, close it please. Thank's!
