### ISSUE TITLE
Muse主题，在移动/平板布局下，点击汉堡菜单超过6个项目时，下拉框样式错误，未遮盖标题

### ISSUE THREAD

**Issue by dreampiggy** [iissnan/hexo-theme-next#1263]
### Expected behavior (预期行为)
如图：

![](http://7xsf4p.com1.z0.glb.clouddn.com/images/screenshot/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-11-16%20%E4%B8%8A%E5%8D%889.33.42.png)

### Actual behavior (实际行为)
如图：

![](http://7xsf4p.com1.z0.glb.clouddn.com/images/screenshot/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202016-11-16%20%E4%B8%8A%E5%8D%889.51.31.png?attname=)

### Steps to reproduce the behavior (重现步骤)

在站点配置文件中设置总计超过6个首页菜单项目（归档、标签、关于、搜索等），然后切换至移动/平板布局下，点击页面上方的汉堡菜单

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master  ✔
  -  Latest Release: 5.1.0 ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse ✔
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

PR: #1262

**Comment by dreampiggy** [comment]
#1262

**Comment by iissnan** [comment]
已 Merge，Thanks
