### ISSUE TITLE
侧边栏的头像、链接、图标都不显示了

### ISSUE THREAD

**Issue by OCNYang** [iissnan/hexo-theme-next#1264]
### Expected behavior (预期行为)  
在hexo s 的时候能够 正常显示。

### Actual behavior (实际行为)
hexo d 提交后，侧边栏的头像、链接、图标都不能正常显示。  

![效果图](http://obbu6r1mi.bkt.clouddn.com/hexo/QQ%E6%88%AA%E5%9B%BE20161116095803.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

NexT Scheme:
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

现在还没有调整好：大家可以到 [我的站点](http://ocnyang.com/) 看实际问题。

**Comment by iissnan** [comment]
vendors 路径无法访问，参考 #1214 和 #1220 ，做下修改就行

**Comment by Neveryu** [comment]
同意楼上，或者看这里[关于github屏蔽vendors ，导致页面空白的解决方案](https://neveryu.github.io/2016/11/11/hexo-next-three/#三、关于github屏蔽vendors-，导致页面空白的解决方案)

**Comment by ivan-nginx** [comment]
@OCNYang dont understand u, write in English if not solved. If solved, close it please. Thank's!
