### ISSUE TITLE
Menu顶部菜单、侧边栏都不显示，本地服务测试却正常

### ISSUE THREAD

**Issue by fangheart** [iissnan/hexo-theme-next#1265]
### Expected behavior (预期行为)
侧边栏，顶部菜单都有，并且文章可见。

### Actual behavior (实际行为)
侧边栏，顶部菜单全部消失，且文章不可见，但是下面却有翻页内容。

### Steps to reproduce the behavior (重现步骤)

重现生成过静态页面，依旧本地测试有效，上传后无效，无法显示。 [我的网站实际情况](http://fangheart.top/)，貌似显示无法载入accessibility-menu.js这是什么情况，怎么解决。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔ 
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces✔

**Comment by Neveryu** [comment]
@fangheart #1220 
或者[关于github屏蔽vendors ，导致页面空白的解决方案](https://neveryu.github.io/2016/11/11/hexo-next-three/#%E4%B8%89%E3%80%81%E5%85%B3%E4%BA%8Egithub%E5%B1%8F%E8%94%BDvendors-%EF%BC%8C%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

**Comment by fangheart** [comment]
@Neveryu 谢谢，按照你的博客已解决。
