### ISSUE TITLE
使用Chrome插件AutoPagerize，加载更多页出现空白

### ISSUE THREAD

**Issue by naijoug** [iissnan/hexo-theme-next#1267]
### Actual behavior (实际行为)
我Chrome浏览器安装了AutoPagerize的插件，滚到页面底部可以自动加载下一页的数据。

### Steps to reproduce the behavior (重现步骤)
我使用NexT皮肤后，首页滚到最底加载更多分页数据会出现空白，效果可以看如下图片。
<img width="699" alt="qq20161116-0 2x" src="https://cloud.githubusercontent.com/assets/5566978/20342536/c840321a-ac25-11e6-9c51-f19e965b9273.png">

不知道这个问题是NexT皮肤的问题，还是Hexo的问题？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
插件的问题 :sake:

**Comment by naijoug** [comment]
@Neveryu  那需要怎么解决呢？

**Comment by Neveryu** [comment]
那就不用这个插件了吧
