### ISSUE TITLE
代码区域可以设定折叠么？

### ISSUE THREAD

**Issue by tjuzl** [iissnan/hexo-theme-next#1269]

**Comment by tjuzl** [comment]
已解决

**Comment by Andiedie** [comment]
请问你是如何解决代码折叠的呢 : )

**Comment by tjuzl** [comment]
http://blog.tangxiaozhu.com/p/45374067/#折叠代码或文字

**Comment by Andiedie** [comment]
Thanks

**Comment by bbappyuanyuan** [comment]
请问你是如何解决代码折叠的？（上面的网址已失效）

**Comment by x22x22** [comment]
https://github.com/heytxz/blog/issues/20#%E6%8A%98%E5%8F%A0%E4%BB%A3%E7%A0%81%E6%88%96%E6%96%87%E5%AD%97

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
