### ISSUE TITLE
为文章正文添加 License

### ISSUE THREAD

**Issue by hcoona** [iissnan/hexo-theme-next#127]
现在 License 信息只在侧边栏中出现，而且只有一个非常小的图标，太不明显了，希望能够提供一个选择，在每篇文章最后添加一个 License 区域，谢谢！

**Comment by iissnan** [comment]
@hcoona License 的内容有什么建议吗？

**Comment by hcoona** [comment]
就现在用的 CC 的那个协议就行吧
不过最好留有一定定制的空间，毕竟那个在国内不具备法律效果……

On 周三, 5月 13, 2015 at 17:38, Vi <notifications@github.com> wrote:
@hcoona [https://github.com/hcoona] License 的内容有什么建议吗？

—
Reply to this email directly or view it on GitHub
[https://github.com/iissnan/hexo-theme-next/issues/127#issuecomment-101594753] .[https://github.com/notifications/beacon/AAre8efwjw4ROoCbl_u3nlFac7dTe5mHks5oIxMMgaJpZM4EH9bz.gif]

**Comment by iissnan** [comment]
涉及到多种语言，单纯写一个中文或者英文的 License 信息似乎不太妥当，所以还是给用户自己定义吧。
