### ISSUE TITLE
如何在自定义新页面生成多篇文章

### ISSUE THREAD

**Issue by lesoleil** [iissnan/hexo-theme-next#1271]
想独立出一个跟主页布局一样的页面，在该页面下可以显示特定分类的博文，而在主页不显示该类博文，有什么解决妙招吗？

**Comment by Neveryu** [comment]
@lesoleil 看源码，找逻辑，修改逻辑代码
I trust you can .
:smile:

**Comment by o1xhack** [comment]
good idea

**Comment by zhuzhuyule** [comment]
我也有这个需求，打算有空试试。
目前已知在优化 next主题，自定义。

**Comment by ivan-nginx** [comment]
@lesoleil dont understand u, write in English if not solved. If solved, close it please. Thank's!
