### ISSUE TITLE
[Question] Does Next Muse support featured image?

### ISSUE THREAD

**Issue by viniciusarcanjo** [iissnan/hexo-theme-next#1276]
Guys, I'd like to know if the Next Muse theme supports featured image. Could you guys shed some light on it? I've tried installing both `hexo-featured-image` and `hexo-generator-json-content`, however it does not show up when I use the variable "featured_image" in the yaml variables (meta tags) of the post. 

I'd appreciate if you guys could confirm if it's possible or not. Much appreciated.

I love this theme. Thanks!

**Comment by ivan-nginx** [comment]
@viniciusarcanjo i think u need `full-image` tag placed in `next/scripts/tags`.
If solved, close it please.

**Comment by viniciusarcanjo** [comment]
@ivan-nginx awesome. thank you!
