### ISSUE TITLE
algolia搜索配置成功，但無法跳轉到結果。

### ISSUE THREAD

**Issue by cogitoxin** [iissnan/hexo-theme-next#1277]
配置algolia成功，但是搜索後點擊結果會出現404，地址欄顯示的地址是：https://name.github.io/undefined
請問如何解決？

**Comment by cogitoxin** [comment]
problem solved：[1084](https://github.com/iissnan/hexo-theme-next/issues/1084)

**Comment by ivan-nginx** [comment]
@cogitoxin solved, but not closed...
