### ISSUE TITLE
怎么为每个页面添加一段相同的script代码

### ISSUE THREAD

**Issue by maxmeng93** [iissnan/hexo-theme-next#1278]
### Expected behavior (预期行为)
想为每个页面添加百度链接自动提交的一段js代码。现在官方只提供了百度统计的，没有链接自动提交。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by imkratos** [comment]
在主题文件夹下的_config.yml，中找到baidu_push: true 修改为true就可以了，我开了之后，页面的源码里也有了，但是百度站长那边却显示没有文章推送，不知道是不是哪里没设置对。

**Comment by ivan-nginx** [comment]
@maxmeng93 dont understand u, write in English if not solved. If solved, close it please. Thank's!
