### ISSUE TITLE
Sidebar position not working 侧边栏位置选择不工作

### ISSUE THREAD

**Issue by lixiangtnt** [iissnan/hexo-theme-next#1279]
from theme  _config_.yml

sidebar:
  #Sidebar Position, available value: left | right
  position: left
  #position: right

侧边栏永远是默认在右边，修改参数为左边无效。
Always 'right', can not be positioned at left

**Comment by Neveryu** [comment]
:smile_cat:

**Comment by geekrainy** [comment]
此配置只适用于 Pisces，在 Mist 和 Muse 下无效。

**Comment by ivan-nginx** [comment]
@lixiangtnt solved?
