### ISSUE TITLE
主题Muse，header部分的导航菜单链接为空

### ISSUE THREAD

**Issue by tankgit** [iissnan/hexo-theme-next#1280]
网页头部的 Home Archives...等导航无效，检查页面元素发现href没有赋值。

进入主题目录，检查layout文件，./layout/_partials/header.swig，我猜测该文件里面关于导航相关内容中，生成href链接用到的url_for(path)函数可能没有返回值。

不知道别人是不是这样，不过我自己的解决方案是：把url_for删掉，直接用path变量作为路径，这样其实也能用吧。

**Comment by Neveryu** [comment]
:+1:

**Comment by gauxonz** [comment]
同出现这样的问题。有没有更好的解决方案？

**Comment by tankgit** [comment]
@gauxonz 目前我就只这样做了，在主题的_config文件里写全路径感觉也还好。我不是搞web的也没去深究为什么url_for()没有返回值，估计里面的参数对他来说不合法吧。我是在自己的服务器上搭的博客，可能在很多人托管在github上就没这么多事儿了？

**Comment by gauxonz** [comment]
@tankgit  我就是托管在github上的。不知什么时候起出现了这个问题。问题不在托管于哪里，而在于generate的时候就没有生成链接。

**Comment by geekrainy** [comment]
未复现。

**Comment by ivan-nginx** [comment]
@tankgit dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by tankgit** [comment]
@ivan-nginx Sorry, I forget this issue in my mail list...it was fixed long ago.
I mentioned this problem and proposed a possible solution.
