### ISSUE TITLE
next修改展示：改了很多，用了许多插件，写了12篇博文详细讲解

### ISSUE THREAD

**Issue by Wangjunyu** [iissnan/hexo-theme-next#1282]
感谢主题的创作者和社群的贡献者，我在[博客](http://blog.junyu.pro/)的[挑选和初步配置Hexo主题](http://blog.junyu.pro/posts/0003-choose-a-theme-you-like.html)写到：

>### 我的选择
>根据不同的个人喜好，每个人会有不同的选择。我选择时主要考虑：可供性强、界面简洁、素雅、交互设计、移动适配、文档技术支持完善程度等。最终选择了[Next.Mist](http://theme-next.iissnan.com/getting-started.html)。
>### 主题故事
>iissnan在主题一周年的时候写下了当时设计主题的[故事](http://notes.iissnan.com/2015/something-about-next/)
>> 我用了一圈就没一个对的上眼的主题。我要的其实很简单啊（遇到说这种话的客户，请直接拒绝，不要问我为什么），只要显示文章内容就好了啦，不要侧边栏啦，不要社交啦，最好字体好看点，排版优美点，颜色搭配舒服点，整体大气点，访问速度快一点，动画特效多一点。于是就有了 Notes（果然记录什么的这种事情不重要）。
>> 在制作 NexT 的过程中，第一要素是保证其易用性。如果一个功能超级炫丽，但难于使用，那宁可不做（真是漂亮的借口）。这一点可以追溯到偶像诗人白居易，他的诗可以通俗到妇孺皆知，确实有一定手段。那么 NexT 目标亦即如此，谨慎对待自己使用都觉得麻烦的功能。比如说，自定义 Icon Font 这个功能，其实我自己都觉得修改很麻烦，所以一直想把这个功能去除掉（在最近的一个版本中，我终于克服拖延症把它给去掉了）。 

>这就是我想要的主题，和当初我选择它的原因如出一辙，有一种莫名的激动。

作为一个IT行业里的技术小白，一点一滴折腾到今天，把折腾的过程认真整理成了[十二篇博客](http://blog.junyu.pro/categories/hexo/)，后续还会继续“折腾”。**希望经过一段时间积累，能够补充一个Hexo基于NexT主题的使用教程**。过程里查询了很多人写的资料，特别是官方文档，一并表示感谢。

以下是技术博文列表，欢迎大家多交流。
- [从零开始了解Hexo博客](http://blog.junyu.pro/posts/0001-start-blog-with-hexo.html)
- [从零开始新建Hexo博客](http:/blog.junyu.pro/posts/0002-start-blog-with-hexo.html) 
- [挑选和初步配置Hexo主题](http:/blog.junyu.pro/posts/0003-choose-a-theme-you-like.html)
- [Hexo博客配置文件说明](http:/blog.junyu.pro/posts/0004-hexo-config-settings.html) 
- [Next主题配置文件说明](http:/blog.junyu.pro/posts/0005-next-theme-settings.html) 
- [Q&A：基于Markdown的博文写作](http:/blog.junyu.pro/posts/0006-qa-posts-based-on-markdown.html) 
- [重建Hexo的教训](http:/blog.junyu.pro/posts/0007-a-mistake-rebuilt-hexo-blog.html) 
- [让更多人看到你的博客](http:/blog.junyu.pro/posts/0008-blog-seo.html) 
- [NexT主题个性化修改与调试方案](http:/blog.junyu.pro/posts/0009-hexo-next-theme-modify.html) 
- [Hexo博客设置进阶](http:/blog.junyu.pro/posts/0010-hexo-learn-from-Never-yu.html) 
- [Hexo实现Math公式撰写的实验报告](http:/blog.junyu.pro/posts/0011-hexo-math-plugin-test-report.html) 
- [Git的Hexo博客搭建和运维实例讲解-初级](http://blog.junyu.pro/posts/0012-hexo-git-apply-primary.html)

**Comment by imkratos** [comment]
所有链接都是404

**Comment by Wangjunyu** [comment]
@imkratos  最后的列表链接已修复，前面的链接都是OK的。

**Comment by zhongjun96** [comment]
不错

**Comment by hzlpy** [comment]
标题与链接过来的文章没对上吧？

**Comment by ehlxr** [comment]
又改代码自动换行吗

**Comment by Wangjunyu** [comment]
@hzlpy  已修改，之前批量处理，顺序正好反了

@ehlxr 没听懂问题

**Comment by ehlxr** [comment]
代码高亮，太长的代码自动换行

**Comment by Wangjunyu** [comment]
@ehlxr  高亮在```符号后面增加对应的语言即可。
代码自动换行没有做，个人觉得并不需要。

**Comment by Wangjunyu** [comment]
更新，第十三篇文章:[Q&A：科学写作中的基本工具和用法
](http://blog.junyu.pro/posts/0013-qa-posts-about-science.html)。
建议通过[分类](http://blog.junyu.pro/categories/hexo/)查看

**Comment by hyhajnal** [comment]
next主题怎么修改js代码  试了一下不生效

**Comment by ivan-nginx** [comment]
@Wangjunyu dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by David-Wey** [comment]
我想学习关于写作格式方面的教程，能够给出md文件我学习学习？

**Comment by hellowqw** [comment]
mark
