### ISSUE TITLE
广告屏蔽插件竟然也会使页面空白

### ISSUE THREAD

**Issue by kcoewoys** [iissnan/hexo-theme-next#1284]
### Expected behavior (预期行为)
正常

### Actual behavior (实际行为)
chorme 和 firefox 出现页面空白等现象，或者随机出现正常页面

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔  
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse ✔  
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
ubuntu16.04  64位 win7 64位

之前更新了vendors问题后，没几天就出现页面卡死，出现空白，不知道是什么问题，后来换浏览器发现firefox偶尔也会出现这个问题，但是ie是正常的，也就没再纠结这个问题

刚刚发现竟然是广告屏蔽插件惹得祸，下面是测试图
**chorme:**
![](http://ofat4idzj.bkt.clouddn.com/chorme.gif)
**firefox:**
![](http://ofat4idzj.bkt.clouddn.com/firefox.gif)

**Comment by ivan-nginx** [comment]
@kcoewoys dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
This issue about user's adblock extension installed on his browser caused website with next theme not to show properly, I doubt there is anything we can do about it.
