### ISSUE TITLE
怎么修改当代码过长时自动换行

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1285]
怎么修改当代码过长时自动换行？不想要那个横向滚动条

**Comment by Neveryu** [comment]
要不咋们手动换行吧
或者找到办法告诉我吧，:smile:

**Comment by xxxlee** [comment]
+1

**Comment by ivan-nginx** [comment]
@ehlxr in English, please.

**Comment by Haocen** [comment]
This request should go to https://github.com/chriskempson/tomorrow-theme
Next theme depend on tomorrow-theme to highlight and format code.
