### ISSUE TITLE
最新版本不显示评论数目

### ISSUE THREAD

**Issue by vitahlin** [iissnan/hexo-theme-next#1287]
### Expected behavior (预期行为)
当没有评论时，文章页面显示暂无评论或者其他。

### Actual behavior (实际行为)
不显示文字提示，并且不蒜子的阅读统计合起来显示有误。

### Steps to reproduce the behavior (重现步骤)
直接安装即可。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Latest Release

NexT Scheme:
  -  Mist

### Other Informations (Like Browser, System, Screenshots)
Google Chrome，macOS 10.12.1.
![d92517bd-6937-4720-aed1-7020b74ae164](https://cloud.githubusercontent.com/assets/6998610/20844251/e9ac6b72-b8f9-11e6-844c-743d2a22645f.png)

**Comment by vitahlin** [comment]
已经解决，自定义多说css出现问题，当自定义多说css为如下代码时，不显示评论数目：
```c
.ds-share-icons-16,.ds-thread-count,.ds-sync,.ds-comments-tabs {
display: none !important;
}
.ds-share-inline {
display:none !important;
} //隐藏分享按钮
.ds-login-buttons {
display:none !important;
} //隐藏社交账户登录
.ds-comments {
margin-bottom: 25px !important;
} //调整评论区与输入框间距
```

**Comment by vitahlin** [comment]
再次出现改问题，已删除多说的自定义样式，应该是主题本身问题。
显示错误如下：
![a0692be3-87be-4bfc-9c7f-5152b62b17eb](https://cloud.githubusercontent.com/assets/6998610/20989960/ac10e524-bd11-11e6-851c-5f56d183ebcf.png)

**Comment by Jucongyuan** [comment]
怎么解决？

**Comment by Maples7** [comment]
这两天突然出现了这个问题：[maples7.com](maples7.com)

**Comment by Jucongyuan** [comment]
我今天出现的

**Comment by Maples7** [comment]
作者自己的站也出现了这个问题：http://notes.iissnan.com/

我猜是不是多说改了某个接口什么的……

@iissnan 求大神解决~

**Comment by newleidy** [comment]
同遇到了，求解决。http://lucia.vicp.io/
post-comments-count div中只显示了两个nbsp

**Comment by vitahlin** [comment]
在该问题还未解决时，可以尝试如下折中方案，直接设置为不显示评论数目，强迫症专用：[http://www.vitah.net/posts/20f300cc/#文章评论数目不显示](http://www.vitah.net/posts/20f300cc/#文章评论数目不显示)

**Comment by jetyu** [comment]
我的也不显示了。。。

**Comment by jetyu** [comment]
@newleidy  @vitahlin 如何解决啊。。。

**Comment by Jucongyuan** [comment]
已经恢复正常了

**Comment by vitahlin** [comment]
@Jucongyuan 知道是什么原因吗

**Comment by vitahlin** [comment]
@Jucongyuan @iissnan 是否知道是什么原因，明确原因的话，这个issue将关闭。

**Comment by Maples7** [comment]
什么都没变化自然就好了，那显然是多说那边的问题了。

**Comment by Maples7** [comment]
2016.12.11 21:57 现在又出现了同样的问题。

**Comment by cogitoxin** [comment]
disqus也有类似的问题……

**Comment by vitahlin** [comment]
@iissnan 不知道这个是否还在维护，针对这个问题是否可以改为，当接口错误或者返回数据有误，直接不显示评论数目而不是显示一个分隔符。

**Comment by Maples7** [comment]
#1294

**Comment by Maples7** [comment]
#1155

**Comment by ivan-nginx** [comment]
@vitahlin it already fixed in closed #1281 and opened #1303.

**Comment by Maples7** [comment]
@ivan-nginx 主要不是图标的问题，主要是多说服务不稳定的问题

**Comment by PaulLuv** [comment]
5.1.2配置hypercomments_id 无法显示评论系统，还需要其他配置吗？
