### ISSUE TITLE
algolia在5.1.0配置完成后点击搜索无法弹出

### ISSUE THREAD

**Issue by fangheart** [iissnan/hexo-theme-next#1288]
### Expected behavior (预期行为)
点击后弹出搜索框
### Actual behavior (实际行为)
点击无反应
### Steps to reproduce the behavior (重现步骤)
1.站点信息配置algolia相关
2.更新index
3.配置主题配置文件
4.测试
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by cogitoxin** [comment]
见 https://github.com/iissnan/hexo-theme-next/issues/1084 回复。

**Comment by ivan-nginx** [comment]
@fangheart solved?
