### ISSUE TITLE
[Question]如何不加载 lato 字体？

### ISSUE THREAD

**Issue by hcoona** [iissnan/hexo-theme-next#129]
Lato 字体每次访问都需要下载，加载速度太慢，有什么办法能够不加载这个字体吗？

**Comment by iissnan** [comment]
自定义字体：https://github.com/iissnan/hexo-theme-next/issues/111

**Comment by hcoona** [comment]
似乎还是会加载 Lato-Bold.woff 和 icomoon.woff，尽管前者没有用到

**Comment by iissnan** [comment]
看了下你的博客，目前是没有加载 Lato-Bold.woff

**Comment by hcoona** [comment]
Yes, I comment the line `@import "_fonts/lato";` in `main.styl`. Is it the best way?
