### ISSUE TITLE
已经更新到5.10正式版了么？

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1290]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
😄 还没使用新版本吗

**Comment by aixiu** [comment]
@Neveryu   昨天发现了，今天已经更新了!!

**Comment by sanyucz** [comment]
就是想问下，Git没有了，而且我自己修改了些样式（比如说头像变园，鼠标放上去旋转之类的），现在要是升级，怎样才能安全升级？

**Comment by amoyiki** [comment]
@sanyucz 替换文件的时候可以吧自己修改过的文件与更新后的文件diff比对，然后修改。如果你有fork项目，可以参考[更新fork项目](https://segmentfault.com/q/1010000002457936).
更新日志可以直接看commit日志

**Comment by aixiu** [comment]
对，先git fetch下来，然后和你的当前分支合并，有冲突就改一下，完事，挺简单的。

**Comment by aixiu** [comment]
@amoyiki @sanyucz 对，先git fetch下来，然后和你的当前分支合并，有冲突就改一下，完事，挺简单的。

**Comment by sanyucz** [comment]
@aixiu @amoyiki 

因为我对整个博客（包括主题、文章）全部用Git做了备份，所以，单独的主题目录是没有仓库。

也就是说，在主题的文件目录下，是不能 `git pull` 或者 `git diff`，请问在这种情况下，怎么更新比较好？

**Comment by Maples7** [comment]
要是自己改了主题感觉 conflicts 会比较多，不知有没有什么更优雅简单的方案。   https://github.com/iissnan/hexo-theme-next/issues/1201

**Comment by geekrainy** [comment]
@Maples7 新建一个分支，pull 只更新到 master,然后从 master 合并到自己的分支。

**Comment by Maples7** [comment]
@geekrainy thx, I'll have a try

**Comment by Maples7** [comment]
成功升级，目前还没发现什么问题。
解决冲突还是需要点时间的，说一下我的流程：

1. 把自己本地的 theme/next 文件夹拷贝到一个新目录；
2. 在这个目录 git init -> git add . -> git commit -m 'init'；
3. git remote add downstream git@github.com:iissnan/hexo-theme-next.git；
4. git fetch downstream v5.1.0；
5. git checkout master && git merge --no-ff FETCH_HEAD；
6. Shell 会输出哪些文件有冲突，耐心的一个文件一个文件的解决冲突（主要是自己对原主题有改动的地方要格外小心取舍）；
7. 解决完冲突之后可以直接把这个新建的目录下的所有文件拷贝到原博客项目目录下的 theme/next 下；
8. hexo s -d 查看 localhost:4000 具体页面上有哪些变动（明显比如自定义页面在顶部比原来多了标题）；
9. 没有问题即可 hexo clean && hexo g -d 了；
10. 之后对于源代码该备份就备份，该 push 就 push。
