### ISSUE TITLE
FontAwesome 的图标未能全部支持

### ISSUE THREAD

**Issue by OscarGong** [iissnan/hexo-theme-next#1291]
### Expected behavior (预期行为)
使用 FontAwesome 中的 **Telegram**

### Actual behavior (实际行为)
无法显示

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  ✔Latest Release
  -  Old version - 

NexT Scheme:
  -  ✔All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
好像是有少部分的图标显示不了

**Comment by ivan-nginx** [comment]
@OscarGong dont understand u, write in English if not solved. If solved, close it please. Thank's!
