### ISSUE TITLE
多说现在怎么登陆不了

### ISSUE THREAD

**Issue by gdutxiaoxu** [iissnan/hexo-theme-next#1294]
打开这个网址一直打开不了
http://duoshuo.com/

**Comment by shijiebei2009** [comment]
已经倒闭，莫等了。

**Comment by gdutxiaoxu** [comment]
好的，谢谢

**Comment by vitahlin** [comment]
仍然可以正常打开，跟这个项目无关，这个问题就不要发在这里了。

**Comment by Maples7** [comment]
有什么好的替代方案吗？

**Comment by Maples7** [comment]
https://www.hypercomments.com/ 
Seem good.

5.1.0 似乎已经有相关配置，不知道能不能用

**Comment by Maples7** [comment]
#1155

**Comment by jinfang134** [comment]
hypercomments是国外的，延迟可能会比较大，我写了一个友言的插件，正等待合并。详细请看我的博文。http://jinfang.oschina.io/2016/12/23/hexo/%E4%B8%BAhexo%E6%B7%BB%E5%8A%A0%E5%8F%8B%E8%A8%80%E8%AF%84%E8%AE%AE%E6%94%AF%E6%8C%81/
