### ISSUE TITLE
We were unable to load Disqus. 

### ISSUE THREAD

**Issue by gdutxiaoxu** [iissnan/hexo-theme-next#1295]
We were unable to load Disqus，If you are a moderator please see our troubleshooting guide.这是什么问题

**Comment by vitahlin** [comment]
国内不支持Disqus，建议用多说。

**Comment by Neveryu** [comment]
[用多说吧](https://neveryu.github.io/)

**Comment by ivan-nginx** [comment]
U may choose other comments system.
See #1303.
