### ISSUE TITLE
如何设置一篇文章置顶显示？谢谢！

### ISSUE THREAD

**Issue by winterrain5** [iissnan/hexo-theme-next#1296]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by aixiu** [comment]
最简单的就是把这篇文章的发布时间，改为2016年当前日期以后，比如2116年。

**Comment by ehlxr** [comment]
可以看看这篇教程
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#十、博文置顶

**Comment by ivan-nginx** [comment]
@winterrain5 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by stevenjoezhang** [comment]
Fixed in hexojs/hexo-generator-index#51
