### ISSUE TITLE
Local search 搜出的页面网址错误

### ISSUE THREAD

**Issue by ipreacher** [iissnan/hexo-theme-next#1298]
### Expected behavior (预期行为)
用 Local search 搜出的页面网址应为：
https://ipreacher.github.io/2016/12/06/restart/

### Actual behavior (实际行为)
实际搜索出的网址为：
https://ipreacher.github.io/%2F2016%2F12%2F06%2Frestart%2F

### Steps to reproduce the behavior (重现步骤)
在 Home 页面，直接在 Search 中搜索，点击搜索结果

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
除去在 Home 页面可以正常搜索，在 About 、Archives 、Tags 页面点击 Search 用 Local search 时，可以正常出现搜索结果，但点击结果后出现 404.

已经发现 ipreacher.github.io/search.xml 中的 URL 有问题，但不知道如何改正.

我的博客地址为： https://ipreacher.github.io
这是我的仓库地址：https://github.com/ipreacher/ipreacher.github.io
小白在此求助，谢谢各位了.

**Comment by flashlab** [comment]
更新主题到最新版

**Comment by ipreacher** [comment]
@flashlab 已经是最新版了，还是没有解决

**Comment by ipreacher** [comment]
@flashlab 已经搞定，谢谢啦

**Comment by youngxhui** [comment]
@ipreacher 出现同样的问题，请问是如何解决的？

**Comment by ipreacher** [comment]
@youngxhui 更新至最新版本后，没有做其他修改，自动解决了，，
