### ISSUE TITLE
增加页面,如何调用CSS

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#130]
比如我增加一个页面,如何在CSS加填加,不然手机浏览,不自动适应.
谢谢
http://eurusd.cn/sj/

**Comment by ioliu** [comment]
> <img src="/image-url" class="full-image" />

可以这样试一下~

还有
><blockquote class="blockquote-center">blah blah blah</blockquote> 

这个也可以的，貌似 ^_^

**Comment by eurusd** [comment]
这两种方法 都是不行的。
