### ISSUE TITLE
如何禁止每次刷新页面的JS效果？

### ISSUE THREAD

**Issue by chenzomi12** [iissnan/hexo-theme-next#1302]
每次点击进入另外一个页面的时候总是等1-2秒才有东西出来，侧边栏什么的可以直接出来吗？不要效果或者效果时间变短，具体代码在哪里改呢

**Comment by aixiu** [comment]
@chenzomi12 https://github.com/iissnan/hexo-theme-next/issues/441#issuecomment-150070011

**Comment by Neveryu** [comment]
修改主题配置，找到 use_motion 更改为 false
:smile:

**Comment by r12f** [comment]
修改了use_motion为false之后，侧边栏就不自动出来了，希望能解决这个问题。

**Comment by iissnan** [comment]
Fixed.

**Comment by ivan-nginx** [comment]
@chenzomi12 solved?

**Comment by Haocen** [comment]
This issue is related with an option `use_motion` in the config.yml of the theme, it has been sovled.
