### ISSUE TITLE
多说又挂了，是否能加入其他三方评论？

### ISSUE THREAD

**Issue by jetyu** [iissnan/hexo-theme-next#1305]
### Expected behavior (预期行为)
当没有评论时，文章页面显示暂无评论或者其他。多说经常挂，disqus国外服务，不稳定。。能不能加入其他三方评论啊？？谢谢了

### Actual behavior (实际行为)
不显示文字提示

### Steps to reproduce the behavior (重现步骤)
直接安装即可。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  Mist

### Other Informations (Like Browser, System, Screenshots)

Google Chrome，Windows 7

**Comment by aixiu** [comment]
三天两头的挂。这是啥节奏。

**Comment by Maples7** [comment]
#1294

**Comment by Maples7** [comment]
#1155

**Comment by geekrainy** [comment]
#1301 增加了网易云跟贴。https://gentie.163.com 待合并。: )

**Comment by jinfang134** [comment]
因为不能注册，逼得我特地写了一个友言的插件，正等待合并。详细请看我的博文。http://jinfang.oschina.io/2016/12/23/hexo/%E4%B8%BAhexo%E6%B7%BB%E5%8A%A0%E5%8F%8B%E8%A8%80%E8%AF%84%E8%AE%AE%E6%94%AF%E6%8C%81/

**Comment by jinfang134** [comment]
@geekrainy 早点看到你的，可能就不会写了。:joy:

**Comment by JohnnyLuv** [comment]
网易云跟帖8月要停止服务了。。。

**Comment by ivan-nginx** [comment]
@JohnnyLuv yeah, we know it: #1745.
