### ISSUE TITLE
博客文章显示有问题，直接显示###，不显示加粗效果

### ISSUE THREAD

**Issue by dexiangjoy** [iissnan/hexo-theme-next#1306]
第一个问题：刚搭好博客，用MarkdownPad2编辑了第一篇文章，语法没错。比如我想加粗的就用"###"放在一段文字前面。在MarkdownPad2里预览时是有加粗效果的，当hexo g -d后却直接显示###这个符号本身。

第二个问题：我插入了一段网易云音乐的代码在文章第一段，可以显示，但点击播放按钮没有效果。

**Comment by aixiu** [comment]
第一个问题是###后边有一个空格。而你没有。

**Comment by Neveryu** [comment]
[音乐的问题请看这里](https://neveryu.github.io/)

**Comment by dexiangjoy** [comment]
@aixiu 谢谢，这个问题解决了

**Comment by dexiangjoy** [comment]
@Neveryu 谢谢
