### ISSUE TITLE
关于多图展示的问题

### ISSUE THREAD

**Issue by monster-gump** [iissnan/hexo-theme-next#1307]
### Expected behavior (预期行为)
利用如下语法做到 **文章内页/关于页面** 的多图并排效果
```html
{% gp 3-3 %}
<img src="pic1.png">
<img src="pic2.png">
{% endgp %}
```

### Actual behavior (实际行为)

仅在首页预览时可以达到多图并排的情况
进入内页后失效
其实就是想在 关于 这个页面放置多图，作为今后 portfolio 的放置和解说

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master 
  -  Latest Release
  -  Old version - 5.0.2✔ 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔ 
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

Mac + Chrome

**Comment by Neveryu** [comment]
怎么搞的

**Comment by monster-gump** [comment]
@Neveryu 就是在页面内的时候这种 layout 失效
比如可以参考这个页面
http://ehlxr.me/categories/%E5%9B%BE%E7%89%87/
进入后就没有这样的排版了

**Comment by jarvan4dev** [comment]
@monster-gump 你解决了吗？

**Comment by ehlxr** [comment]
@monster-gump 问题已经解决了，效果参考 http://ehlxr.me/2016/09/02/Naruto-Pictures/

**Comment by monster-gump** [comment]
@ehlxr 好的谢谢

**Comment by monster-gump** [comment]
@jarvan4dev 我用了一个比较奇怪的方式 - - 而且我是另外新建的页面，类似于 about 这样，并不是在博文里面展示的
你可以看看楼下 ehlxr 的

**Comment by toxicbug** [comment]
为什么我的博客不显示多图？http://xbay.top 
谢谢

**Comment by toxicbug** [comment]
设置了type: "picture" 和
{% gp 4-3 %}
![](http://p.xbay.top/2017-02-08-0FE14AF5-1AA1-4FA5-BB0D-DB82FEBC8C1A.JPG)
![](http://p.xbay.top/2017-02-08-IMG_3544.JPG)
![](http://p.xbay.top/2017-02-08-IMG_2364.JPG)
![](http://p.xbay.top/2017-02-08-IMG_2383.JPG)
{% endgp %}
不行，也按8.3注释掉两行，同样不行   郁闷了

**Comment by jarvan4dev** [comment]
@toxicbug 我修改了部分源码，改成如下形式，请看我的博客相册部分 dev-heaven.com

**Comment by toxicbug** [comment]
@jarvan4dev 感谢回复，说实话《长发及腰》这篇文章写得好，音乐配得到位👏🏻。
唐突问下，可以把你修改的部分发我看看吗？谢谢，你博客里图片带框效果是ps结果还是css效果？可以分享一下吗，谢谢。

**Comment by Dingxuewen** [comment]
关注这个问题

**Comment by mengxianliang** [comment]
请问怎样横向排列图片

**Comment by ivan-nginx** [comment]
@monster-gump dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by jarvan4dev** [comment]
@mengxianliang visit my site, the gallery module  ======> https://www.dev-heaven.com

**Comment by mengxianliang** [comment]
@jarvan4dev 好的 谢谢!

**Comment by cutelittleturtle** [comment]
想跟进一下，用了ehlxr提示的办法后可以解决显示问题，但我在设置文章类型为 picture后文章标题无效，请问是默认效果吗？

**Comment by cutelittleturtle** [comment]
还有，这个主题能和[lightgallery](https://github.com/sachinchoolur/lightgallery.js)一起使用吗?
