### ISSUE TITLE
小米前端博客，欢迎大家来踩

### ISSUE THREAD

**Issue by liuxiaomin922** [iissnan/hexo-theme-next#1308]
0313.name
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by zhoujiealex** [comment]
没看懂 这个issue是啥意思  广告？

**Comment by quxiaofeng** [comment]
网站挂了……

**Comment by ivan-nginx** [comment]
@liuxiaomin922 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
It is very unkind to spam issue list in order to advertise your personal blog, for link exchange or list your blog in the demo section please consider contact maintainer, issue list is for issues.
