### ISSUE TITLE
关于Swiftype站内搜索的问题

### ISSUE THREAD

**Issue by iVanPan** [iissnan/hexo-theme-next#131]
添加Swiftype站内搜索后，在右下脚Swiftype 搜索按钮会与回到头部的按钮重叠，还有搜索框出现在了首页，归档等菜单栏的左侧很不美观，能不能改善一下搜索栏的位置，同时添加一个快关来控制要不要显示搜索栏

**Comment by eurusd** [comment]
没有好位置。很难找到不影响美观的位置加搜索功能。

**Comment by iVanPan** [comment]
@eurusd  可以不显示搜索栏，但在右下角显示Swiftype的搜索按钮， @iissnan 发现在Safari下面不会显示回到top的按钮,而chrome上面会显示。是兼容性问题吗？

**Comment by flashlab** [comment]
@iVanPan 可以参考[这里](http://zzbd.org/2015/04/22/custom-search-btn/)我的修改办法

**Comment by lzlun129** [comment]
@iVanPan Swiftype可以改成OverPlay样式。另外我现在换成了tinysou，你可以看一下,[链接](http://lizhuolun.com)

**Comment by CodingMonkeyzh** [comment]
建议添加订部搜索栏是否显示参数

**Comment by mingmings** [comment]
这边不知道新版本更新后，我的搜索出现了问题，不知道啥子情况，就是没法搜索

**Comment by iissnan** [comment]
@mingmings 是否跟这个 https://github.com/iissnan/hexo-theme-next/pull/132 有关联。Swiftype 好像升级到 v2 了。

**Comment by imcoddy** [comment]
不知道有没有人觉得现在的搜索框比较小呢？
在搜索的时候 Swiftype 自动补全时的显示是和搜索框宽度相同的，因此我加了个 focus 后自动扩大的效果。不知道有没有人对此也有兴趣 :)

https://imcoddy.github.io

**Comment by alfredtofu** [comment]
我的一直提示Our crawler hasn’t downloaded any pages yet，不知道你们是否有这个问题？

**Comment by alfredtofu** [comment]
我的一直提示Our crawler hasn’t downloaded any pages yet，不知道你们是否有这个问题？Swiftype没法怕我的信息下来，此外，百度站长也是，我不太懂这方面的东西，求赐教。[github](https://github.com/alfredtofu/alfredtofu.github.io)，[blog](http://cvmarcher.com/)

**Comment by iissnan** [comment]
@iVanPan 我今天刚安装了 Swiftype，我发现底部没有那个搜索按钮。
@CodingMonkeyzh 如果有没有配置 Swiftype 或者 tinysou，就不会有搜索栏，所以不需要什么开关吧。如果是指底部的那个搜索按钮，我会将他强制隐藏（但我安装后就没看到。。），没有什么必要。

@imcoddy 效果不错。不过我将菜单往左推了（有搜索的时候），所以空间上还是足够的，就不做这个动画效果了。

@alfredtofu 没有碰到你提到的问题。

**Comment by alfredtofu** [comment]
@imcoddy 我尝试这替换tinysou的，不成功，您能否帮忙改一下？

**Comment by imcoddy** [comment]
@alfredtofu 抱歉我没用过 tinysou 也不是太了解呢，应该是没配置对的原因吧？这个到网上找一下教程更好些。

**Comment by iissnan** [comment]
搜索样式已更新，欢迎反馈

**Comment by DemoJameson** [comment]
@alfredtofu 估计你 GitHub Pages 绑定的是根域名导致的这个问题。可以看看：http://theo.im/blog/2014/05/14/resolve-302-redirection-on-github-pages/
