### ISSUE TITLE
希望增加全局配色方案

### ISSUE THREAD

**Issue by seymourtang** [iissnan/hexo-theme-next#1310]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

希望增加全局配色方案，现在版本黑色太单调了。

**Comment by Neveryu** [comment]
你如果有比较好的方案可以尝试提交PR

**Comment by ivan-nginx** [comment]
@seymourtang dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by xiaotan828** [comment]
@ivan-nginx His meaning is the current colors of the theme are just black and white and it's too boring. Actually I have the same thought with him, and I feel confused to change the color code in base.styl. I cannot find codes for some position to change the color.
