### ISSUE TITLE
favicon设置无效，版本5.1.0

### ISSUE THREAD

**Issue by weixinbing** [iissnan/hexo-theme-next#1314]
按文档中的操作:
>将你的 favicon 放置到 站点 的 source 目录下，与站点的配置文件同级

刷新，强制刷新，清楚缓存都没有效果

**Comment by newleidy** [comment]
favicon.ico放在主题的source\images下
修改主题配置文件：的favicon为images/favicon.ico

**Comment by Shens998** [comment]
实测上面说的方法有效

**Comment by 631068264** [comment]
按照官方文档不行 @newleidy 点赞
