### ISSUE TITLE
修改h1 h2等字体大小后，手机端字体变的非常小，比正文还小

### ISSUE THREAD

**Issue by lzyroot** [iissnan/hexo-theme-next#1315]
请问需要修改哪里呢，电脑上显示正常

**Comment by ivan-nginx** [comment]
Screen?

**Comment by lzyroot** [comment]
mobile
<img src='http://p1.bpimg.com/1949/b28d1bca733525fc.png'>
computer
<img src='http://p1.bpimg.com/1949/e2097907adebe16f.png'>

**Comment by ivan-nginx** [comment]
@lzyroot can u, please, explain your issue in English language? And give full screen with website on desktop/mobile and/or give link on this site with with issue?

Also, any h1-h6 tags may defined in custom style: `source/css/_custom/custom.styl`
``` css
h1 {
	font-size: 1.7em;
}
h2 {
	font-size: 1.5em;
}
```

**Comment by lzyroot** [comment]
I'm sorry to think you are Chinese,Thank you！

**Comment by DeppWang** [comment]
```styl
// source/css/_custom/custom.styl
h1 {
  font-size: 2em !important;
}

h2 {
  font-size: 1.5em !important;
}
```
