### ISSUE TITLE
多说微信分享失败

### ISSUE THREAD

**Issue by jingtalk** [iissnan/hexo-theme-next#1319]
### Expected behavior (预期行为)
集成多说分享后，点击分享到微信，扫码查看文章

### Actual behavior (实际行为)
扫码后微信提示“已停止访问该网页”

站点配置文章如下：
duoshuo_shortname: jingtalk
duoshuo_share: true

Tips: 感觉是多说账号里面有什么地方没有配置导致的，有遇到相同情况的吗

**Comment by jinfang134** [comment]
多说最近老是挂，有可能是系统不稳定吧，我特地写了一个友言的插件，正等待合并。详细请看我的博文。http://jinfang.oschina.io/2016/12/23/hexo/%E4%B8%BAhexo%E6%B7%BB%E5%8A%A0%E5%8F%8B%E8%A8%80%E8%AF%84%E8%AE%AE%E6%94%AF%E6%8C%81/

**Comment by ivan-nginx** [comment]
@jingtalk dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
The problem is about sharing blog to WeChat, a chatting app similar with WhatsApp, this issue is inappropriate to open in this repository.
