### ISSUE TITLE
想给博客添加canvas-nest.js的效果，但是不知道该怎么添加

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#1325]
### Expected behavior (预期行为)
根据[canvas-nest.js](https://github.com/hustcc/canvas-nest.js)的方法首先要添加一个js到主题内部，然后在每个页面的 `</body>` 前都要有一个 `<script type="text/javascript" color="0,0,0" opacity='0.7' zIndex="-2" count="99" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>` 的标签，不知道应该怎样修改主题才能把它整合进去呢？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by jinfang134** [comment]
这个很容易做的。我一会帮你开一个分支解决吧，

**Comment by jinfang134** [comment]
已经解决了。

**Comment by jinfang134** [comment]
效果嘛，请看我的博客http://jinfang.oschina.io/，我感觉效果挺炫酷，但是也显得有点杂乱

**Comment by AlynxZhou** [comment]
谢谢喵～感觉这个特效蛮不错的，杂乱的话……我用的是Pisces主题，正好除了文章和侧边栏的底下比较空，所以想着加上这个会比较好一点。谢谢dalao这么快弄了一个，本猹马上去学习一下。

**Comment by AlynxZhou** [comment]
为什么不直接吧canvas-nest.min.js加入到lib里呢？毕竟主题的大部分js都没有用CDN，我开一个PR试试吧

**Comment by AlynxZhou** [comment]
我搞定啦，现在是按照NexT默认的方式导入了这个js，在config里可以开启，也可以添加外部CDN，然后这个标签的添加也是按照next的划分写在了vendors.swig里面，谢谢你给的方法啊。

**Comment by jinfang134** [comment]
好的，你来吧，这个我也才开始用，也不是太熟悉他的目录结构。
----- 原始邮件 -----
发件人：请叫我喵 Alynx <notifications@github.com>
收件人：iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>
抄送人：jinfang134 <jinfang134@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[iissnan/hexo-theme-next]_想给博客添加canvas-nest.js的效果，但是不知道该怎么添加_(#1325)
日期：2016年12月25日 19点40分

为什么不直接吧canvas-nest.min.js加入到lib里呢？毕竟主题的大部分js都没有用CDN，我开一个PR试试吧

&mdash;

**Comment by AlynxZhou** [comment]
窝也是收到了你的pr之后才开始看它的，大概看懂了它的逻辑，然后就弄了一下，我只弄了这个背景，你那里面友言评论之类的我也不太会弄……毕竟我是猹

**Comment by jinfang134** [comment]
其实也不难的，我写了一篇文章，介绍了一下next用的swig模板引擎的语法，你大概看看就知道他是怎么回事了。http://jinfang.oschina.io/posts/124966c9/

**Comment by shibenli** [comment]
@jinfang134 你好，你博客的好像有个背景透明的是吧。这个能配置吗？还是说得自己改next的代码
