### ISSUE TITLE
求救!如何把目录设置为不渲染

### ISSUE THREAD

**Issue by Gh0stKnow** [iissnan/hexo-theme-next#1329]
### Expected behavior (预期行为)
点击"关于"跳转到一个新的页面
页面路径放在source/about下

实际上是impress.js

![](https://ww1.sinaimg.cn/large/006tKfTcgw1fb5h6s6ilkj31330qjwgc.jpg)

### Actual behavior (实际行为)
跳转后是一个嵌入Hexo-Next主题的页面
![](https://ww1.sinaimg.cn/large/006tKfTcgw1fb5h7axidmj312p0qoq63.jpg)

主题配置文件如下
menu:
  home: /
  about: /about
  archives: /archives
  tags: /tags

# skip_render: about/**
设置了skip_render为何还是会渲染?

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔  
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes✔  
  -  Muse 
  -  Mist 
  -  Pisces

**Comment by ivan-nginx** [comment]
@Gh0stKnow dont understand u, write in English if not solved. If solved, close it please. Thank's!
