### ISSUE TITLE
Mist 无法启用

### ISSUE THREAD

**Issue by archink** [iissnan/hexo-theme-next#133]
修改了scheme: Mist， 也尝试了hero clean，但还是没有解决。 有什么其他原因，呃？

**Comment by archink** [comment]
确认下是修改next目录下的_config.yml文件里面的scheme么？

**Comment by YikaJ** [comment]
可以使用，只需要取消注释即可

**Comment by iissnan** [comment]
Seems you have found out the way to enable Mist.

**Comment by archink** [comment]
Sure, I found that it was  the problem of my own MAC ☺
