### ISSUE TITLE
本地预览正文页面一片空白，发布到github上正常

### ISSUE THREAD

**Issue by lw900925** [iissnan/hexo-theme-next#1332]
hexo新手，刚刚搭建好自己的博客，遇到了一个问题，困扰了我好久。

我用Markdown编写了一篇博文，当我尝试在本地预览时，首页可以正常显示，但是点击到正文时出现一篇空白，控制台没有报任何错误。

一开始我怀疑是我的文章Markdown语法有错误，我尝试用各种Markdown编辑器预览，结果都是成功，没有语法问题。我又尝试将hexo的主题设置成默认的landscape，本地预览成功。

但是我将生成好的博客网站发布到github上时，文章却能正常显示。我用的是Travis CI配置的持续集成，查看Travis CI的构建日志，也没有任何错误信息。并且，我将生成好的public页面发布到本机Tomcat中，博客正文也是可以正常显示的。

我的博客地址为 [https://lw900925.github.io](https://lw900925.github.io)

下面中是我的博客Markdown源文件，github issues不能发md格式的文件，所以我将扩展名改为txt。

[java8-lambda-expression.txt](https://github.com/iissnan/hexo-theme-next/files/676510/java8-lambda-expression.txt)

**Comment by Neveryu** [comment]
[https://neveryu.github.io/2016/11/11/hexo-next-three/#%E4%B8%89%E3%80%81%E5%85%B3%E4%BA%8Egithub%E5%B1%8F%E8%94%BDvendors-%EF%BC%8C%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88](https://neveryu.github.io/2016/11/11/hexo-next-three/#%E4%B8%89%E3%80%81%E5%85%B3%E4%BA%8Egithub%E5%B1%8F%E8%94%BDvendors-%EF%BC%8C%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

**Comment by Neveryu** [comment]
如果还有问题，私聊
