### ISSUE TITLE
footer的不蒜子统计没有居中

### ISSUE THREAD

**Issue by seymourtang** [iissnan/hexo-theme-next#1334]
### Expected behavior (预期行为)
不蒜子统计居中

### Actual behavior (实际行为)
不蒜子统计没有居中

### Steps to reproduce the behavior (重现步骤)
5.1

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes ✔
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

![qq 20161229200803](https://cloud.githubusercontent.com/assets/19689979/21543694/bbbf044e-ce03-11e6-9adb-73a4fff37f28.png)

**Comment by Neveryu** [comment]
你自己的问题，我的没问题。[https://neveryu.github.io/](https://neveryu.github.io/)
