### ISSUE TITLE
希望footer增加备案编号的 空间

### ISSUE THREAD

**Issue by seymourtang** [iissnan/hexo-theme-next#1335]
### Expected behavior (预期行为)

footer有备案编号的 空间
### Actual behavior (实际行为)
footer有备案编号的 空间
### Steps to reproduce the behavior (重现步骤)

5.1
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes✔
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
难道没有备案号的空间吗？ 你的意思是在配置文件中添加备案号的配置？？  你还是自己写在footer里面去吧

**Comment by seymourtang** [comment]
自己写的空间还是有的，希望能够添加到配置文件。

发自我的 iPhone

在 2016年12月30日，16:04，Yu <notifications@github.com<mailto:notifications@github.com>> 写道：


难道没有备案号的空间吗？ 你的意思是在配置文件中添加备案号的配置？？ 你还是自己写在footer里面去吧

―

**Comment by Neveryu** [comment]
哈哈，我就知道你是这个意思

**Comment by ivan-nginx** [comment]
@seymourtang dont understand u, write in English if not solved. If solved, close it please. Thank's!
