### ISSUE TITLE
希望增加相册页面

### ISSUE THREAD

**Issue by dyh333** [iissnan/hexo-theme-next#1336]
类似这个主题的相册功能页面 http://litten.me/photos/

**Comment by Neveryu** [comment]
每个主题的侧重点不一样吧 
[https://neveryu.github.io/](https://neveryu.github.io/)

**Comment by jinfang134** [comment]
mark,有空可以实现一下，

**Comment by ivan-nginx** [comment]
@dyh333 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by dyh333** [comment]
@ivan-nginx . i means hope hexo-theme-next can add a photo wall page, just like this page: http://litten.me/photos/  .  thanks

**Comment by ivan-nginx** [comment]
@dyh333 but `group-pictures.js` (Image Gallery) does not support it?
