### ISSUE TITLE
Bug: 主页当前页只有一篇文章时，访客数统计错误

### ISSUE THREAD

**Issue by IceHe** [iissnan/hexo-theme-next#1337]
## Context
主页页面（is_index == true），如果当前页只有一篇文章。

## Bug
这篇文章就不会显示访客数，而且还会给这篇文章增加访客数。

## Why
见源码 `layout/_scripts/third-party/lean-analytics.swig` 
``` js
if ($('.leancloud_visitors').length == 1) {
    addCount(Counter);
} else if ($('.post-title-link').length > 1) {
    showTime(Counter);
}
```

## 其它
对 Hexo、Next 现有的代码不够熟，短时间没有找到一个自己满意的解决方案，所以懒得提 Pull Request 修复了

**Comment by Lizhooh** [comment]
写两篇以上吧 。\("▔□▔)/

**Comment by IceHe** [comment]
@Lizhooh 你搞错了… 假如博客一页显示 8 篇文章，你写了 9 篇文章，那么第二页就只有一篇文章了。

**Comment by ivan-nginx** [comment]
@IceHe dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by IceHe** [comment]
I'm not sure whether is solved or not.
But I am busy recently.
If I found it unfixed, I will create a new issue written in English.

**Comment by IceHe** [comment]
@ivan-nginx I'm not sure whether is solved or not.
But I am busy recently.
If I found it unfixed, I will create a new issue written in English.

**Comment by IceHe** [comment]
@ivan-nginx I'm not sure whether is solved or not.
But I am busy recently.
If I find it still unfixed, I will create a new issue written in English.

**Comment by ivan-nginx** [comment]
@IceHe ok, thank's. Then i close it right now.
