### ISSUE TITLE
在md里使用<!-- more -->后，点击阅读全文后，滚动条滚到<!-- more -->处?

### ISSUE THREAD

**Issue by Lizhooh** [iissnan/hexo-theme-next#1338]
### Expected behavior (预期行为)
在md里使用后，点击“阅读全文”后，滚动条应该在**顶端**才对。

### Actual behavior (实际行为)
在md里使用后，点击”阅读全文“后，滚动条滚到的位置，而不是在**顶端**

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.1.0

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:

  -  Pisces

**Comment by Lizhooh** [comment]
问题解决了。原来把 scroll_to_more 设置为 true 了

**Comment by Neveryu** [comment]
@Lizhooh  THK
