### ISSUE TITLE
如何置顶文章？

### ISSUE THREAD

**Issue by monsterLin** [iissnan/hexo-theme-next#1339]
### Expected behavior (预期行为)

置顶文章
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
@monsterLin  手动修改文章的发表时间是一个不错的选择

**Comment by monsterLin** [comment]
@Neveryu Thanks :1st_place_medal:

**Comment by ehlxr** [comment]
参考这个
http://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#十、博文置顶

**Comment by monsterLin** [comment]
@ehlxr Thanks ， 非常感谢，博主你的博客写的很nice，借鉴了 👍

**Comment by asdf2014** [comment]
![image](https://cloud.githubusercontent.com/assets/8108788/24834488/db66a486-1d19-11e7-851d-3e878223abdf.png)
是不是 因为 abbrlink的原因？

**Comment by stevenjoezhang** [comment]
Fixed in hexojs/hexo-generator-index#51

**Comment by stevenjoezhang** [comment]
Fixed in hexojs/hexo-generator-index#51
