### ISSUE TITLE
2017了, 奈何底下的版权时间没有+1

### ISSUE THREAD

**Issue by otherfish** [iissnan/hexo-theme-next#1341]
### Expected behavior (预期行为)

© 2015 -2017

### Actual behavior (实际行为)

© 2015 - 2016

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

必须自己手动改站点配置文件吗？ 希望大佬给个解释，顺祝大佬新年快乐，感谢奉献如此好的主题。

**Comment by ehlxr** [comment]
因为博客是静态html，所以需要重新生成一下。hexo d g
