### ISSUE TITLE
文章的post信息栏图标怎么去掉啊

### ISSUE THREAD

**Issue by pandaSLP** [iissnan/hexo-theme-next#1344]
### 文章的post信息栏图标怎么去掉啊，如下图：

![tool-editor](https://github.com/pandaSLP/MarkdownPhotos/raw/master/photos/test.png)

**Comment by pandaSLP** [comment]
-----
help!

**Comment by iissnan** [comment]
目前无法通过参数关闭，下个版本将提供此选项。

**Comment by pandaSLP** [comment]
多谢啦，这个问题之前已经解决了，我把这个文件（themes\next\layout_macro\post.swig）里涉及到的span内容给注释掉了，忘记关闭了。^_^
