### ISSUE TITLE
如何修改模板的背景色？

### ISSUE THREAD

**Issue by monsterLin** [iissnan/hexo-theme-next#1345]
### Expected behavior (预期行为)

希望更改模板的背景色

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by sirlh** [comment]
next 的配色文件
\Hexo\themes\next\source\css\_variables\base.styl
附：
添加body背景图
在hexo\themes\next\source\css\_custom\custom.styl  
文件的最上方加上一代码 body { background:url(‘/xxx/xxx.jpg   (你的图片路径)   ’);} 
添加header背景
在Hexo\themes\hexo-theme-next\source\css\_common\components\header
修改.header { background: $head-bg; }为.header { background: url('.xx/xx/xxx.jpg   (你的图片路径)   '); }

**Comment by ivan-nginx** [comment]
@monsterLin solved?

**Comment by xxf1995** [comment]
@sirlh is there a way to cover the `canvas-nest` animation with `body background color`? Right now the js renders animation on top of post's bg color, really distracting.

**Comment by xxf1995** [comment]
nvm I found the way
added `.post-block { background: #ffffff; }`
to `source/css/_common/components/post/post.styl`

**Comment by ladychili** [comment]
@sirlh  试了一下，没反应啊。你说的是live preview里Muse scheme里的第一个blog  [XiaMo](https://notes.wanghao.work/)那种效果吗
 ？

**Comment by sirlh** [comment]
@ladychili 并不是那个修改动画，而是直接添加了背景图片，如果添加动画，在使用文档中有详细的说明。

**Comment by ladychili** [comment]
@sirlh Umm.. 我就是说添加header背景图片，之前是我路径弄错了，照你的说的已经弄好了。非常感谢～ >.<

**Comment by juventusryp** [comment]
刚研究了下，如果想更改全部的背景色，需要修改以下几处：
1、themes/next/source/css/_variables/Pisces.styl
$body-bg-color                = #ffffff

2、source/css/_common/components/post/post.styl
.post-block { background: #ffffff; }

3、themes\next\source\css\_schemes\Pisces\_layout.styl
.content-wrap
background: #ffffff;
.header-inner
background: #ffffff;

4、themes\next\source\css\_schemes\Pisces\_sidebar.styl
.sidebar-inner
background: #ffffff;

**Comment by monsterLin** [comment]
@ivan-nginx ok , I had solved , thanks

**Comment by monsterLin** [comment]
@sirlh thanks
