### ISSUE TITLE
能够加入网易云评论的模块吗？

### ISSUE THREAD

**Issue by skyrocketup** [iissnan/hexo-theme-next#1346]
### Expected behavior (预期行为)
网易云评论

### Actual behavior (实际行为)
多说评论

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
网易出了一个网易云评论的插件,看着还不错。而且现在多说也没有更新了，官网也没人管。

**Comment by xbotao** [comment]
怎么用？
