### ISSUE TITLE
首页阅读次数一直为1

### ISSUE THREAD

**Issue by peishanShirley** [iissnan/hexo-theme-next#1347]
### Expected behavior (预期行为)
首页阅读次数与文章阅读次数一致

### Actual behavior (实际行为)
首页阅读次数一直为1，文章阅读次数能正常显示

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@peishanShirley dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Vincentqyw** [comment]
求问解决了咩？
