### ISSUE TITLE
请问是否有加入手机浏览器支持的计划？

### ISSUE THREAD

**Issue by cgoder** [iissnan/hexo-theme-next#1349]
目前好像并不适配移动端浏览器，看起来挺费力的。
请问是否有适配计划？

**Comment by cgoder** [comment]
补充，用的mist

**Comment by cgoder** [comment]
mist模板下

**Comment by geekrainy** [comment]
是适配的吧，发个图看看。

**Comment by ivan-nginx** [comment]
@cgoder dont understand u, write in English if not solved. If solved, close it please. Thank's!
