### ISSUE TITLE
deploy到github pages以后，英文单词显示不全

### ISSUE THREAD

**Issue by castial** [iissnan/hexo-theme-next#135]
本地访问博客正常，但是deploy到github上就会出现英文单词显示不全或者不显示，有没有和我一样的?  

详情请看我的博客：[Hyyy's Blog](http://castial.github.io)  

（正文空白处没显示出来的就是英文单词）

**Comment by minoscc** [comment]
貌似没发现现实不出~

**Comment by Beenking** [comment]
我的电脑显示也会单词显示不全，但在别的电脑就可以了，不知道为什么。

**Comment by castial** [comment]
win下和mac下都出现过这样的问题，感觉要么是网络问题，要么是英文字体问题。

**Comment by Beenking** [comment]
应该不是网络的问题，我在本地也显示不全，估计是bug

**Comment by iissnan** [comment]
Lato 字体可能有问题，可以考虑自己定义下字体，参考 [issue 111](https://github.com/iissnan/hexo-theme-next/issues/111)
