### ISSUE TITLE
请问：代码高亮没法用是怎么回事？

### ISSUE THREAD

**Issue by tianxieao** [iissnan/hexo-theme-next#1350]
### Expected behavior (预期行为)

![](http://p1.bqimg.com/567571/2ccbec973fd9f9ef.png)
### Actual behavior (实际行为)
![](http://p1.bqimg.com/567571/43eda7b82abb83f4.png)

### Steps to reproduce the behavior (重现步骤)
![](http://p1.bqimg.com/567571/3b1c9dffb262df03.png)

NexT Scheme:
   Mist

**Comment by tianxieao** [comment]
主题下的config文件已经修改，但还是没用
![](http://i1.piimg.com/567571/c7c6fb6969489f6a.png)
![](http://i1.piimg.com/567571/9b500ba4a2521d09.png)
![](http://i1.piimg.com/567571/f4910e96ade77f04.png)
![](http://i1.piimg.com/567571/f1756ccbdfa07e1a.png)

**Comment by tianxieao** [comment]
已经在issues中搜到答案，谢谢

**Comment by Shens998** [comment]
@tianxieao 你说说你的解决办法吗?我在issues里面没找到
