### ISSUE TITLE
期望主题可支持uml相关markdown

### ISSUE THREAD

**Issue by nickylin** [iissnan/hexo-theme-next#1352]
### Expected behavior (预期行为)
可以通过markdown书写渲染uml的类图、序列图等功能

### Actual behavior (实际行为)
相关语法显示为代码，非渲染成类图图片效果

### Steps to reproduce the behavior (重现步骤)
有无可用的插件可以支持这种渲染显示
~~~

~~~

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔  
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔  
  -  Pisces

**Comment by ivan-nginx** [comment]
@nickylin dont understand u, write in English if not solved. If solved, close it please. Thank's!
