### ISSUE TITLE
顶部菜单栏 “关于我” 点击后浏览器选项卡显示问题

### ISSUE THREAD

**Issue by luzhq** [iissnan/hexo-theme-next#1353]
![qq 20170104175823](https://cloud.githubusercontent.com/assets/20197088/21638718/88e11bea-d2a7-11e6-93d2-08abd1b2c7fb.png)

![image](https://cloud.githubusercontent.com/assets/20197088/21638650/24c26808-d2a7-11e6-8607-fed505bd7a96.png)

@iissnan

**Comment by welliu** [comment]
在 source/about/index.md 文件下 修改title内容：
title: 关于我

**Comment by LuZhQ** [comment]
font{
        line-height: 1.5;
    }


    非常感谢，已经改好！！



    
        在2017年01月5日 14:42，
                
                        wel liu
                        <notifications@github.com>
                    写道：
                
        
    


在 source/about/index.md 文件下 修改title内容：
title: 关于我
