### ISSUE TITLE
Algolia搜索按钮第二次点击无响应

### ISSUE THREAD

**Issue by ncepuwanghui** [iissnan/hexo-theme-next#1354]
### Expected behavior (预期行为)
首页`搜索`按钮第一次点击时正常,弹出搜索框。关闭弹出的搜索框，重新点击`搜索`按钮，正常情况下也能弹出搜索框

### Actual behavior (实际行为)

首页`搜索`按钮第一次点击时正常,弹出搜索框。关闭弹出的搜索框，重新点击`搜索`按钮，无法弹出搜索框，页面无响应。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔ 

### Other Informations (Like Browser, System, Screenshots)

NexT版本 v5.1.0
```
$ hexo -v
hexo: 3.2.2
hexo-cli: 1.0.2
os: Linux 4.4.0-58-generic linux ia32
http_parser: 2.3
node: 0.12.18
v8: 3.28.71.20
uv: 1.6.1
zlib: 1.2.8
ares: 1.10.0-DEV
modules: 14
openssl: 1.0.1u
```
右键打开`Inspect`模式，发现如下错误：
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.success ((index):994)
    at j (index.js?v=2.1.3:2)
    at Object.fireWith [as resolveWith] (index.js?v=2.1.3:2)
    at x (index.js?v=2.1.3:4)
    at XMLHttpRequest.<anonymous> (index.js?v=2.1.3:4)
```
hexo后台日志提示:
```
/lib/algolia-instant-search/instantsearch.min.js.map 404 8.355 ms - 64
```
尝试如下方法后还是存在该问题。
**尝试方法一：** 重装algolia。执行`npm remove hexo-algolia`卸载algolia，删除 ～/.npm和node_modules/hexo-algolia目录。执行`npm install --save hexo-algolia`重装Algolia，执行`hexo algolia`更新Algolia Index，执行`hexo clean && hexo s --debug `，经测试问题仍然存在。
**尝试方法二：** 升级algolia版本，查看发现algolia版本为0.1.1，卸载后重新安装0.2.0版本`npm install --save hexo-algolia@0.2.0`，经测试问题仍然存在。

@iissnan

**Comment by ncepuwanghui** [comment]
问题已经找到了，由于同时装了`hexo-generator-searchdb`和`algolia`的原因，导致algolia第二次点击搜索时出错。

**Comment by itvincent-git** [comment]
我跟你一样的情况，不过我卸载了hexo-generator-searchdb ，还是不行

**Comment by itvincent-git** [comment]
我是第一次搜索就出这个异常了，但能弹出窗口，第二次就不出窗口了

**Comment by Acris** [comment]
Fixed by #1453

**Comment by ivan-nginx** [comment]
@ncepuwanghui solved?
