### ISSUE TITLE
首页透明，分页有问题

### ISSUE THREAD

**Issue by mrhaoxiaojun** [iissnan/hexo-theme-next#1356]
为啥，我分页之后就首页就变成透明的了，，而且，如果我没有进行分页，如果有一个.md文件写的很长也会发生这样的情况
.posts-expand .post{
opacity:0
}
头和尾部也透明的
我的hexo的配置文件是这么写的
# Pagination 
## Set per_page to 0 to disable pagination
per_page: 3 	
pagination_dir: page

**Comment by ivan-nginx** [comment]
@mrhaoxiaojun dont understand u, write in English if not solved. If solved, close it please. Thank's!
