### ISSUE TITLE
网站的首页显示评论数量不准

### ISSUE THREAD

**Issue by monsterLin** [iissnan/hexo-theme-next#1357]
### Expected behavior (预期行为)

显示评论数量准确

### Actual behavior (实际行为)

我的网站出现暂无评论，甚至显示评论数量直接显示了所有的评论数量

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@monsterLin dont understand u, write in English if not solved. If solved, close it please. Thank's!
