### ISSUE TITLE
怎样在【分类】和【标签】页面显示所有文章的分类和标签集合？

### ISSUE THREAD

**Issue by CygLin** [iissnan/hexo-theme-next#1358]
### Expected behavior (预期行为)
在分类页 显示文章的所有分类

### Actual behavior (实际行为)
点击菜单上的分类，页面可以打开，但是空白的。

### Steps to reproduce the behavior (重现步骤)
用 hexo new page 生成了分类页和标签页，写了一篇文章，为其添加了分类和Tag。打开文章可以显示分类和所加的标签。但是在菜单上的分类和标签页链接点开后都是空白的。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
检查一下是否有字母单词拼错的情况？:smile:

**Comment by welliu** [comment]
用hexo clean命令清除之后再试一下

**Comment by imxw** [comment]
我的也是这个问题，如何解决

**Comment by leogcry22** [comment]
同样的问题，目前找不到解决办法

**Comment by leogcry22** [comment]
检查一下生成的分类和标签页中是否有对应的type？

**Comment by ivan-nginx** [comment]
@CygLin dont understand u, write in English if not solved. If solved, close it please. Thank's!
