### ISSUE TITLE
小屏幕下菜单按钮css样式bug

### ISSUE THREAD

**Issue by Dec-F** [iissnan/hexo-theme-next#1359]
![image](https://cloud.githubusercontent.com/assets/20250430/21741224/3848240c-d50a-11e6-83d6-1ed89086b5ce.png)

> ### 点击后
![image](https://cloud.githubusercontent.com/assets/20250430/21741229/572ccfa8-d50a-11e6-967d-3daf7c99ceab.png)

> ### 错误的css样式
![image](https://cloud.githubusercontent.com/assets/20250430/21741244/88d303ec-d50a-11e6-84b7-617e91a12b7e.png)

> ### 改为
![image](https://cloud.githubusercontent.com/assets/20250430/21741267/e5b36070-d50a-11e6-9d75-27fe86260e3b.png)

> ### 效果
![image](https://cloud.githubusercontent.com/assets/20250430/21741278/717d8388-d50b-11e6-9154-0a499567b492.png)

**Comment by Stark2Chen** [comment]
遇到同样的问题

**Comment by ivan-nginx** [comment]
@Dec-F dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Dec-F** [comment]
@ivan-nginx Sorry, I'm closed
