### ISSUE TITLE
english language detection (possible fix inside)

### ISSUE THREAD

**Issue by jacksgt** [iissnan/hexo-theme-next#136]
I installed Hexo with NodeJS on a clean debian server.
After selecting the theme "next" and also selecting the language "en" (in the main _config.yml), most of the letters on the website were still chinese. It seems Hexo doesn't autodetect that "en" translates (in this case) to *default.yml*.

This behaviour can be fixed however by symlinking (or copying) *default.yml* to *en.yml* in the languages folder.

**Comment by minoscc** [comment]
set blog/_config.yml -> language: default

**Comment by jacksgt** [comment]
That works, yes.
But shouldn't "language: en" also work?

**Comment by minoscc** [comment]
You should ask theme's author, Hexo no language.

**Comment by iissnan** [comment]
As I know, Hexo will use `default` language when the language you set does not exist. But Hexo has an issue on handling this fallback. So NexT contains an `en.yml` which is the same as default. To avoid incorrect default language detection by Hexo, you should specify the `language` to an extractly one, such as `en`, `zh-Hans`.
