### ISSUE TITLE
最新的commit之后，“显示更多”的按钮存在问题

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#1360]
### Expected behavior (预期行为)

白底黑字，鼠标移上去淡入成黑底白字

### Actual behavior (实际行为)

没有移上去，就是黑底白字，移上去了也没有变化，而且按钮弧度也没有了。
查看_variables下面的base.styl文件发现默认指定的颜色变量和弧度变量都存在问题，修改后似乎可以解决，但是查看了历史这个文件没有进行过相关改动，推测是以前某个地方的设置覆盖了这里的设置，之后这次更新重构的时候覆盖被取消。

### Steps to reproduce the behavior (重现步骤)

拉取最新的主题，然后生成页面。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

**Comment by AlynxZhou** [comment]
推测是错误的，是否存在其它地方影响到这里最终的css？

**Comment by AlynxZhou** [comment]
有关Pisces的地方没有问题，那到底是哪里出问题了呢？

**Comment by Neveryu** [comment]
> 有关Pisces的地方没有问题，那到底是哪里出问题了呢？

是否你自己有写css覆盖了这个样式呢？

**Comment by AlynxZhou** [comment]
我没有写过这方面的css啊，改的都是一些字体啦间距啦之类的调整，跟这个有关的没有碰过啊。

**Comment by hidaris** [comment]
我重新建了一份干净的blog来测试，确认存在这个问题。

**Comment by AlynxZhou** [comment]
所以是哪里的改动出了问题呢？

**Comment by AlynxZhou** [comment]
@iissnan 是最近的某个提交有问题吗？

**Comment by yohole** [comment]
同样存在这个问题

**Comment by hidaris** [comment]
Fix by [#1397](https://github.com/iissnan/hexo-theme-next/pull/1397) @iissnan
