### ISSUE TITLE
这句话有配置项目改吗？“OK! 目前共计 x 篇日志。 继续努力。”

### ISSUE THREAD

**Issue by CSGrandeur** [iissnan/hexo-theme-next#1361]
不太严肃。。想改个自己的。貌似在`archive.swig`文件可以改，但是毕竟不太正规。。

**Comment by Neveryu** [comment]
> 不太严肃。。想改个自己的。貌似在archive.swig文件可以改，但是毕竟不太正规。。

就是这样改的

**Comment by cwyaml** [comment]
https://cwyaml.github.io/

**Comment by welliu** [comment]
> 不太严肃。。想改个自己的。貌似在archive.swig文件可以改，但是毕竟不太正规。。

这还不严肃，我的都改成了：“非洲人! 目前共计 52 篇日志， まだまだ”

**Comment by ivan-nginx** [comment]
@CSGrandeur dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by mapan2020** [comment]
这个在...\Blog\themes\next\languages\zh-Hans.yml文件
