### ISSUE TITLE
设置了百度分享和jiathis但是没有效果

### ISSUE THREAD

**Issue by Shens998** [iissnan/hexo-theme-next#1363]
### Expected behavior (预期行为)
设置百度分享或者jiathis之后应该出现分享按钮

### Actual behavior (实际行为)

实际没有没出现

**Comment by swordspoet** [comment]
我的也是

**Comment by jetyu** [comment]
同样的问题。

**Comment by mkitby** [comment]
me too, version: 5.1.0

**Comment by jetyu** [comment]
@mkitby 我也一样，升级到5.1.0，百度分析不好使 @iissnan

**Comment by zhuzixian** [comment]
嗯，米吐。

**Comment by rangerzhou** [comment]
# Share
jiathis: true
# Warning: JiaThis does not support https.
#add_this_id:
5.1.1也不行，可能就不支持吧 JiaThis does not support https.

**Comment by shenzekun** [comment]
jiathis不支持http

**Comment by ivan-nginx** [comment]
@Shens998 issue solved?

**Comment by youngjuning** [comment]
My site is note https，but jiathis does'n work
