### ISSUE TITLE
什么时候考虑增加文章列表中缩略图的显示？

### ISSUE THREAD

**Issue by tmcyfy** [iissnan/hexo-theme-next#1364]
### Expected behavior (预期行为)
什么时候考虑增加文章列表中缩略图的显示？

### Actual behavior (实际行为)
希望增加缩略图的显示，没有缩略图，少了一些乐趣。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by nickylin** [comment]
支持

**Comment by tmcyfy** [comment]
有没有可以参考的地方，一直没有找到在哪里开启。

**Comment by ivan-nginx** [comment]
@tmcyfy dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by vinurs** [comment]
dose it support now？

**Comment by ivan-nginx** [comment]
@vinurs i don't understand what he's talking about and will close this issue.

**Comment by vinurs** [comment]
@ivan-nginx He means that does this theme support article thumbnail in Home page.

**Comment by onlyfly34** [comment]
Will NeXT support article thumbnail?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
