### ISSUE TITLE
请问next模板如何添加resume简历？

### ISSUE THREAD

**Issue by wanghansong** [iissnan/hexo-theme-next#1366]
next模板如何添加resume简历？

**Comment by wanghansong** [comment]
类似这样的http://blog.zanlabs.com/about/resume.html

**Comment by xbotao** [comment]
创建一个About 静态页面，用md写就可以了

**Comment by wanghansong** [comment]
那怎么去掉页面头尾呢？

**Comment by xbotao** [comment]
你也可以自己添加一个html 页面，

**Comment by ivan-nginx** [comment]
@wanghansong dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by linjinjin123** [comment]
@ivan-nginx  The question is that how to create a custom page such as a resume page without next-theme layout, for example, if we have a resume-button in the menu, then when we click the about-button, it jump to a new page which doesn't have the layout(e.g., sidebar) of next-theme but written by ourselves

**Comment by ivan-nginx** [comment]
@wanghansong thank's for translate, and as i see, answer was given: `layout: false`.
