### ISSUE TITLE
About页面没有title，求解答

### ISSUE THREAD

**Issue by SimpleBrightMan** [iissnan/hexo-theme-next#1367]
遇到一个很尴尬的处境。
我的About页面上
如果没有设置title属性
网页的标题就没有了！如下图：
![2017-01-15 00-09-54](https://cloud.githubusercontent.com/assets/16462374/21956247/79d795bc-dab7-11e6-89d3-33362efc2dcb.png)
页面上也没有About字样
![2017-01-15 00-23-49](https://cloud.githubusercontent.com/assets/16462374/21956297/ea02407a-dab8-11e6-81c7-212529a0464f.png)
——————————————————————————
如果设置title属性为：About
网页的标题有了！如下图：
![2017-01-15 00-17-42](https://cloud.githubusercontent.com/assets/16462374/21956274/4a4f09be-dab8-11e6-839b-37d0b358f992.png)
但是关于的页面上多了About字样
![2017-01-15 00-18-11](https://cloud.githubusercontent.com/assets/16462374/21956289/9af062d2-dab8-11e6-9bf4-a7deb510f52c.png)
————————————————————
有什么方法网页标题有About，但是页面上没有About字样？

**Comment by ctianlong** [comment]
修改文件`/themes/next/layout/page.swig`，将其中第19行代码注释掉或删掉。
之前：
`{% include '_partials/page-header.swig' %}`
注释后：
`{# {% include '_partials/page-header.swig' %} #}`

**Comment by SimpleBrightMan** [comment]
it's work!
Thanks
