### ISSUE TITLE
如何禁用所有文章评论

### ISSUE THREAD

**Issue by xbotao** [iissnan/hexo-theme-next#1368]
### Expected behavior (预期行为)

不想再文章中使用评论系统，每篇文章添加 评论为false太麻烦，怎样可以全部禁止评论？

由于有留言板功能，所以扔需要设置评论系统

**Comment by Neveryu** [comment]
> 不想再文章中使用评论系统，每篇文章添加 评论为false太麻烦，怎样可以全部禁止评论？

不麻烦

**Comment by xbotao** [comment]
原先的文章需要每篇再添加一遍。。。
还有一个问题就是，我是使用`Hexo-admin`插件来管理文章的，文章标头是自己管理的。

**Comment by iissnan** [comment]
这个场景，直接改模板是最快最简单的方式。

https://github.com/iissnan/hexo-theme-next/blob/master/layout/_partials/comments.swig#L1

将 这个判断改成 `如果是留言板` 页面就启用。

**Comment by xbotao** [comment]
Thanks！
