### ISSUE TITLE
大家在使用的时候有没有发现加载慢的问题, 在手机或者PC加载网页都比较慢

### ISSUE THREAD

**Issue by Andrew-liu** [iissnan/hexo-theme-next#137]
经常markdown代码出来了, 但是没有标题和问题, 在手机更加严重

> 是CDN问题? 还是我自己网速问题

**Comment by iissnan** [comment]
应该是在加载 Lato ，你可以尝试将 Lato 字体去掉试试会不会快一些

**Comment by Rearcher** [comment]
我用chrome inspect了一下，确实是Lato最慢，小白一只，还望赐教如何去掉Lato字体

**Comment by iissnan** [comment]
@Rearcher [issue 111](https://github.com/iissnan/hexo-theme-next/issues/111)
