### ISSUE TITLE
创建的分类页面不显示分类的内容

### ISSUE THREAD

**Issue by SkyHive** [iissnan/hexo-theme-next#1370]
创建的分类页面里没有显示我创建的那些分类，但是分类的路径什么的都生成了，这是什么原因导致的啊

**Comment by AsanZhang** [comment]
@SkyHive 你这个问题解决了么，我也遇到的相同的问题

**Comment by SkyHive** [comment]
@AsanZhang 还没

**Comment by ivan-nginx** [comment]
@SkyHive dont understand u, write in English if not solved. If solved, close it please. Thank's!
