### ISSUE TITLE
怎么在简介里现实图片？

### ISSUE THREAD

**Issue by leinov** [iissnan/hexo-theme-next#1371]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/6204210/21976801/88f53d62-dc0e-11e6-9388-757734e591f4.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/6204210/21976749/4366fab0-dc0e-11e6-88f6-ffc97b039eb5.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by leinov** [comment]
我知道了，在第一个图片的下面添加就行了

**Comment by vinnyxiong** [comment]
看你的 More 写在什么地方了

**Comment by sit-in** [comment]
在第一个图片下面 添加 `<!-- more -->` 就可以了
