### ISSUE TITLE
admin_enable设置为true后无法显示“博主”

### ISSUE THREAD

**Issue by yohole** [iissnan/hexo-theme-next#1372]
### Expected behavior (预期行为)
在多说评论中，博主的回复应该带有【博主】
UA能正确显示
### Actual behavior (实际行为)
没有出现【博主】

### Steps to reproduce the behavior (重现步骤)
admin_enable设置为true
版本为5.1.0
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔   Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

### Other Informations (Like Browser, System, Screenshots)
重现该步骤应该很简单，开发人员自己回去自己Hexo回复一下就行了

**Comment by Neveryu** [comment]
> admin_enable设置为true

你好，你虽然这一项设置了为true，开启了显示博主的功能，但是还需要设置，究竟谁是博主，
详情请看[这里的283-287行](https://github.com/Neveryu/Blog/blob/master/themes/next/_config.yml#L283-L287)
这个user_id是我的，你需要改成你自己的就行。

**Comment by yohole** [comment]
这个在出现这个BUG之前，我已经改成自己的了，但依然不行

**Comment by Dingxuewen** [comment]
我的也是显示不了。。

**Comment by jetyu** [comment]
我的升级到最新版本5.1，不显示了。

**Comment by Doublemine** [comment]
这个问题目前可能没有什么探讨的价值了，建议尽快迁移到其他评论平台。参见[多说即将关闭](http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241?from=timeline)

**Comment by Dingxuewen** [comment]
这个问题我解决了，才有空出来说下。其实next主题没有错，而是用户配置的时候没弄好。
解决方法：用 '' 符号，即单引号包围你的多说ID即可。
希望能解决大家的问题。

**Comment by iissnan** [comment]
Closing as the service would be removed in the next release.
