### ISSUE TITLE
关于页面，同样的markdown语法，但显示有问题

### ISSUE THREAD

**Issue by coyawa** [iissnan/hexo-theme-next#1374]
### Expected behavior (预期行为)

![image](https://cloud.githubusercontent.com/assets/4596255/22000617/208433be-dc0e-11e6-940a-eb10681971d3.png)

### Actual behavior (实际行为)
![2017-01-16 17 05 49](https://cloud.githubusercontent.com/assets/4596255/22000621/245c7ca8-dc0e-11e6-869e-bd61d34b98c5.jpg)

### Steps to reproduce the behavior (重现步骤)
用了同样的
- xxx
   - xxx

请问这样是合理的吗？如何解决，谢谢

**Comment by o1xhack** [comment]
同问，无需列表在 new page 里面无法显示，但是文章中可以。

**Comment by aqsong** [comment]
也在纠结这个问题，在哪里设置呢？

**Comment by aqsong** [comment]
解决了，之前有人问过这个问题，在custom.styl文件中增加
ul {
list-style-type: circle;
}
暂时解决。
实际的设置位置暂未发现

**Comment by aqsong** [comment]
补充一下，最好写成这样，不然sidebar的友链也会显示小圆圈
.content ul {
list-style-type: circle;
}

**Comment by seymourtang** [comment]
5.1新版已经解决了这个问题。
