### ISSUE TITLE
点击“标签”分类，页面打不开，显示Cannot GET /tags/

### ISSUE THREAD

**Issue by ouyangalex** [iissnan/hexo-theme-next#1375]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by llxxee** [comment]
是不是没有设置tag页面？ 
命令行输入`hexo new page tags` 
然后在`source/tag/`中修改`index.md`(即标签页面)

**Comment by ouyangalex** [comment]
ok，那我之前建立的标签如何移植到新的主题中呢？我现在打开标签页就出现一个tags

发自我的 iPhone

**Comment by He110te4m** [comment]
不用移植呀，不是自动生成的吗？
