### ISSUE TITLE
标签迁移问题

### ISSUE THREAD

**Issue by iEricOuyang** [iissnan/hexo-theme-next#1376]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
每篇文章中都要配置它的tags和值

**Comment by ivan-nginx** [comment]
@iEricOuyang dont understand u, write in English if not solved. If solved, close it please. Thank's!
