### ISSUE TITLE
Fancybox会出现空白图片

### ISSUE THREAD

**Issue by chy9002** [iissnan/hexo-theme-next#1377]
### Expected behavior (预期行为)
Fancybox会遍历文章中的图片

### Actual behavior (实际行为)
在遍历后会出现一次空白，首页会出现N次。

### Steps to reproduce the behavior (重现步骤)
1. 点击任意图片打开Fancybox
2. 点击下一张直到出现空白图片

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

![](https://ww1.sinaimg.cn/large/006tNbRwgy1fbtlz1oh0yj31kw0uu0zl.jpg)

**Comment by wangziling** [comment]
你打开控制台，搜索fancybox 或者 fancybox.image   有一个style="display"的span标签，他的itemprop="logo"，是这个下面的img标签的问题。   暂时没找到为什么有这个。 这个img也会被fancybox读到，它没有引用图片，所以显示白板或者提示“The requested content cannot be loaded.Please try again later.“   希望作者能修复吧， 不然使用markdown自带的引用图片语法 ![]() 或者使用hexo的{% xxx %}都会出现这个问题，只有在photo模式下（也就是在Front-matter 里面写photos: -xxxx）才不会这样，才不会生成那个多余的span标签     @iissnan

**Comment by wangziling** [comment]
哦，这个logo的图片。 当没有在主体设置里面开启custom_logo时，自动生成的。开启后也会有这个。当然就不是display none了。 这个也一样会被fancybox拿到。 不把这个弄上class= "fancybox"就应该可以了吧

**Comment by chy9002** [comment]
这个问题我也一直拖着，不过最近自己博客升级Fancybox3.0时才着手解决这个问题。应该是utils.js在处理img标签的时候没有把custom_logo排除出去。
我的处理是在`layout/_marco/post.swig`里面给logo增加class
```html
    <span class="logospan" style="display:none" itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
      <img style="display:none;" itemprop="url image" alt="{{ config.title }}" src="{{ theme.custom_logo.image }}">
    </span>
```
然后`source/js/src/utils.js`第8行`$('.content img').not()`里增加`.logospan img`

**Comment by iissnan** [comment]
已修复

**Comment by zy943453722** [comment]
> 这个问题我也一直拖着，不过最近自己博客升级Fancybox3.0时才着手解决这个问题。应该是utils.js在处理img标签的时候没有把custom_logo排除出去。
> 我的处理是在`layout/_marco/post.swig`里面给logo增加class
> 
> ```
>     <span class="logospan" style="display:none" itemprop="logo" itemscope itemtype="http://schema.org/ImageObject">
>       <img style="display:none;" itemprop="url image" alt="{{ config.title }}" src="{{ theme.custom_logo.image }}">
>     </span>
> ```
> 
> 然后`source/js/src/utils.js`第8行`$('.content img').not()`里增加`.logospan img`

请问给logo增加class具体是往哪一行里面加呢？新手不太懂，谢谢

**Comment by chy9002** [comment]
@zy943453722 ,这个问题已经修复过了吧，至少在6里面已经没问题了，因为我已经迁移到其它框架，所以不使用next了，新的代码也不是很了解，建议你更新一下next的版本试试。
