### ISSUE TITLE
设置代码高亮后，文本也跟着高亮了，怎么只设置代码高亮？

### ISSUE THREAD

**Issue by ifelseboyxx** [iissnan/hexo-theme-next#1379]
我设置这种 代码高亮后：
https://segmentfault.com/img/bVIjBz?w=125&h=63

这么设置的东西也跟着高亮了:
https://segmentfault.com/img/bVIjBA?w=70&h=34

类似这样：
https://segmentfault.com/img/bVIjBg?w=749&h=635

能保持代码高亮效果，但是文本高亮是那种默认的样子吗？而不是黑色的
https://segmentfault.com/img/bVIjCP?w=631&h=305

**Comment by ifelseboyxx** [comment]
搞定了

**Comment by weiweikong** [comment]
@ifelseboyxx 请问是在哪里修改设置，达到文本不高亮的呢？谢谢
