### ISSUE TITLE
大家有遇到过标签问题吗

### ISSUE THREAD

**Issue by calvinliu** [iissnan/hexo-theme-next#138]
点击标签后，就出现Cannot GET /tags/ ，请问大家有遇到这个问题吗？

**Comment by fangd123** [comment]
我也遇到了同样的问题。

**Comment by Cookiezby** [comment]
我也遇到了

Wenda Fang <notifications@github.com>于2015年5月7日星期四写道：

**Comment by fangd123** [comment]
找到了解决方案，标签页默认是没有的，需要自行添加，可以参考文档<https://github.com/iissnan/hexo-theme-next/wiki/创建标签云页面>，之前文档没有仔细看。

**Comment by Cookiezby** [comment]
嗯，谢谢！

2015年5月7日木曜日、Wenda Fang<notifications@github.com>さんは書きました:

**Comment by xiaoci** [comment]
@fangd123 按照步骤自行添加以后还是不行

**Comment by calvinliu** [comment]
谢谢，已解决！

**Comment by flyher** [comment]
谢谢,已解决.

**Comment by jimbray** [comment]
谢谢，已解决
