### ISSUE TITLE
现在偶尔会出现个广告，看的很郁闷？

### ISSUE THREAD

**Issue by ifelseboyxx** [iissnan/hexo-theme-next#1382]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
大兄弟，哪有广告啊，让我也看看啊

**Comment by seymourtang** [comment]
这是你被运营商劫持了吧！！！
