### ISSUE TITLE
新建的page，能否在sidebar显示目录呢？

### ISSUE THREAD

**Issue by hxhb** [iissnan/hexo-theme-next#1383]
### Expected behavior (预期行为)
通过`hexo new page`新建的一个页面，想要在sidebar显示目录。
类似于这个页面：http://imzlp.me/notes/

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@hxhb dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by hxhb** [comment]
closed.
