### ISSUE TITLE
英文正常显示，中文无法显示。

### ISSUE THREAD

**Issue by local-ring** [iissnan/hexo-theme-next#1384]
md文件中用中文写的发布之后，显示不出来，而英文正常。
已经设置了zh-Hans。

### NexT Informations

NexT Version:

  -  Master
  ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  ✔ Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
Chrome, Windows 10

**Comment by ivan-nginx** [comment]
@local-ring dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by yangfanv** [comment]
应该是，你的编码问题，开始我也是记事本编辑hexo配置文件，最后我用一个程序编辑器解决的，如果说是显示不了中文，一定是编码问题。
