### ISSUE TITLE
如何让文章图片默认以 50% 宽高显示，以适配 Retina 屏幕？

### ISSUE THREAD

**Issue by fysly** [iissnan/hexo-theme-next#1386]
需求是：先让图片以 50% 宽高显示，如果没有超出文章宽度，则直接显示（完美）；如果 50% 仍然超出，则被进一步缩小到与文章同宽（和默认一样大小）。

之所以有这个需求，是因为我有大量屏幕截图，尤其是一些不宽、但比较长的截图，它们在文章里看上去太大了，很不美观，也使点击放大的功能显得毫无必要。因为不太懂前端，所以我自己瞎改，尝试在 `post-expand.styl` 里修改 `img`，在其第一行增加了 `width: 50%`，但它实际上是在图片已经被限制到文章宽度同宽的基础上，再进一步缩小为 50%，所以是文章宽度的 50%（那就太小了）。

那么，我应该怎样改，才能实现需求呢？

**Comment by toxicbug** [comment]
我也有这个需求，希望大神给个解决方案，谢谢

**Comment by ivan-nginx** [comment]
@fysly dont understand u, write in English if not solved. If solved, close it please. Thank's!
