### ISSUE TITLE
Next 文章页能否优化

### ISSUE THREAD

**Issue by He110te4m** [iissnan/hexo-theme-next#1388]
文章页能否直接显示站点概览而不是文章目录？

**Comment by Neveryu** [comment]
> 文章页能否直接显示站点概览而不是文章目录？

你是希望去掉侧边栏中的文章目录 or 先显示站点概览？

**Comment by He110te4m** [comment]
我希望能优先显示，因为感觉目录的作用不是很大，更希望显示成站点概览

**Comment by Neveryu** [comment]
@He110te4m 
那你就去掉这一行吧
 [https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/layout/_macro/sidebar.swig#L13](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/layout/_macro/sidebar.swig#L13)

**Comment by He110te4m** [comment]
@Neveryu ,这样的话连站点概览也没了

**Comment by Neveryu** [comment]
有的

**Comment by He110te4m** [comment]
@Neveryu，改完全没了，整个侧边栏都不见了

**Comment by Neveryu** [comment]
下面是我自己测试的，打开文章之后的侧边栏，没有目录。
![image](https://cloud.githubusercontent.com/assets/14313328/22204352/836e3ed6-e1ac-11e6-93d2-c391fe8fb09e.png)

**Comment by He110te4m** [comment]
这是我测试的：
![default](https://cloud.githubusercontent.com/assets/16161582/22207129/e6e36f8e-e1b8-11e6-9286-6890f0e0f463.png)

**Comment by He110te4m** [comment]
这是我测试的：
![default](https://cloud.githubusercontent.com/assets/16161582/22207171/072709ae-e1b9-11e6-91fe-67a61beace7f.png)

**Comment by Neveryu** [comment]
你能不能把右下角的菜单点一下子？看下里面的内容还有没有目录这一项

**Comment by ivan-nginx** [comment]
@He110te4m dont understand u, write in English if not solved. If solved, close it please. Thank's!
