### ISSUE TITLE
修改github仓库名后,用新的地址不能访问

### ISSUE THREAD

**Issue by SimleCp** [iissnan/hexo-theme-next#1389]
已解决

**Comment by Neveryu** [comment]
> 尝试更改github的仓库名

大哥，你就别瞎折腾了。
**建立与你用户名对应的仓库，仓库名必须为【your_user_name.github.io】**

**Comment by SimleCp** [comment]
@Neveryu 傻逼了....忘记是必须用户名了.....去年搞的博客, 今年换了新域名, 心血来潮想改下仓库名,哈哈.谢谢啦.
