### ISSUE TITLE
修改页面以后必须强刷才行，还有标签问题

### ISSUE THREAD

**Issue by xiaoci** [iissnan/hexo-theme-next#139]
我这边修改页面以后hexo clean; hexo g; hexo d，之后必须强刷，不然页面还是显示之前的文章
还有，标签问题，按照标签云的做法进行以后，还是404

**Comment by xiaoci** [comment]
我这边生成了两个tags文件夹，一个里面是index.html，另一个就是标签文件夹，这两个应该是合并在一起的啊

**Comment by iissnan** [comment]
好像问题已经解决了？

**Comment by xiaoci** [comment]
@iissnan 强刷好像还没解决，标签问题，我又重新装了一遍，然后马上hexo new "tags"就可以了。强刷是怎么回事

**Comment by iissnan** [comment]
强刷 这个问题我也不太清楚
