### ISSUE TITLE
看到一个很棒的disqus免翻墙的方式，next是否考虑整合一下？

### ISSUE THREAD

**Issue by skyue** [iissnan/hexo-theme-next#1391]
http://blog.fooleap.org/happy-birthday-to-great-grandmother.html

网上看到上面 fooleap 的博客，基于 api 使用 disqus，貌似可以不用登录使用 disqus，next 是否考虑整合一下。

多说没有通知，而且近期稳定性堪忧，用的不爽啊。

**Comment by He110te4m** [comment]
多说不稳定且接口不支持 https，已经放弃了

**Comment by HJHL** [comment]
挺有意思的，希望大神能添加进去

**Comment by cyang812** [comment]
资磁

**Comment by ivan-nginx** [comment]
@skyue in English, please.

**Comment by geekrainy** [comment]
这个接口需要用自有的服务器进行反向代理，主题可以提供接口，但是服务器的可靠性和稳定性需要自己配置解决吧。
