### ISSUE TITLE
多说有一个thread-key，能自定义为文章某个属性吗？

### ISSUE THREAD

**Issue by skyue** [iissnan/hexo-theme-next#1392]
多是从ghost博客牵过来的，不知道能不能定义这个key，保证以前的评论可用。

**Comment by iissnan** [comment]
目前使用的 key 在： https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/post.swig#L124

**Comment by ivan-nginx** [comment]
@skyue don't understand u, write in English if not solved. If solved, close it please. Thank's!
