### ISSUE TITLE
使用第三方社会评论——来必力，无法在文章标题下方显示评论条数

### ISSUE THREAD

**Issue by wanzhiyu** [iissnan/hexo-theme-next#1393]
由于多说插件日益不稳定，所以选择了[来必力](https://livere.com/)插件。
我直接将来必力生成的代码复制到comments.swig文件中，每篇文章的最底下的确可以实现评论功能，但是文章标题下方不能像多说那样显示“n条评论”。请问这个功能应该在哪里添加？谢谢！

**Comment by iissnan** [comment]
来必力的文档太少了，目前还无法得知如何显示评论数

**Comment by wanzhiyu** [comment]
@iissan 谢谢开发者！

**Comment by ivan-nginx** [comment]
@wanzhiyu don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by dhengyi** [comment]
Has this problem not been solved yet?

**Comment by stevenjoezhang** [comment]
为什么不直接向来必力寻求帮助呢？
