### ISSUE TITLE
代码多行注释显示不正确

### ISSUE THREAD

**Issue by hippo-jessy** [iissnan/hexo-theme-next#1394]
<img width="638" alt="screen shot 2017-01-23 at 10 59 24 pm" src="https://cloud.githubusercontent.com/assets/24545028/22209323/0ebf1e42-e1c1-11e6-92f8-454a98211a48.png">

如图，多行注释时只有第一行会以正常颜色显示，后几行注释颜色都不对

**Comment by ivan-nginx** [comment]
@hippo-jessy don't understand u, write in English if not solved. If solved, close it please. Thank's!
