### ISSUE TITLE
希望增加对来必力Livere社会化评论插件的支持

### ISSUE THREAD

**Issue by wanzhiyu** [iissnan/hexo-theme-next#1396]
经过几天的使用，发现来必力Livere社会化评论插件比多说稳定多了，邮件提醒也很人性化，请问有计划支持Livere吗？

**Comment by iissnan** [comment]
已支持，详见：[第三方服务 - 来必力](http://theme-next.iissnan.com/third-party-services.html#livere)

**Comment by yelunightroad** [comment]
@iissnan 使用5.1.3版本，配置livere_uid后，來必力并未加载

**Comment by sli1989** [comment]
Return address of livere is 404.html? Does anyone have this problem?
