### ISSUE TITLE
多说的博主显示问题

### ISSUE THREAD

**Issue by skyue** [iissnan/hexo-theme-next#1398]
一开始，ua_enable、admin_enable和user_id都设置了，能正常显示UA和博主信息。

后来觉得UA内容太多不必要，将ua_enable设置为false，另外两个不变，但博主信息也不显示了。

难道ua和admin必须同时使用吗？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
> 后来觉得UA内容太多不必要，将ua_enable设置为false，另外两个不变，但博主信息也不显示了。

ua_enable 是一个总开关，你把它关了，还怎么显示啊 。

**Comment by skyue** [comment]
@Neveryu 设置的时候大概也猜到了。但还是想知道能否改为分开设置，「博主」信息比较有用，ua不太必要（偏偏还是大长串，略显臃肿）。

**Comment by Neveryu** [comment]
@skyue  你可以写css，不显示 ua 这一块即可。

**Comment by ivan-nginx** [comment]
@skyue don't understand u, write in English if not solved. If solved, close it please. Thank's!
