### ISSUE TITLE
会自动生成一个README.html?

### ISSUE THREAD

**Issue by vinnpc** [iissnan/hexo-theme-next#14]
##### 1
`hexo generate` 的时候会在根节点将类似首页的 Layout 生成一个 [README.html](https://github.com/vinnpc/vinnpc.github.io/blob/master/README_bak.html) ，有些意义不明？

##### 2
最好分开说明一下，在 `/_config.yaml` 中配置 `duoshuo_shortname` / `disqus_shortname` 中是为了 首页的 Comment Count，在 `theme/next/_config.yaml` 中配置  `duoshuo_shortname` / `disqus_shortname`  是为了文章/页面评论。

##### 3
另外 `README.md` 中的 

>使用 Disqus
>编辑站点的 `_config.yml` ，添加 `duoshuo_shortname` 字段，设置如下”

应该为

>使用 Disqus
>编辑站点的 `_config.yml` ，添加 **`disqus_shortname`** 字段，设置如下”

都是些鸡毛蒜皮 XD

**Comment by iissnan** [comment]
@vinnpc 

我在本地使用 Hexo 2.8.3 ，并没有出现 `README.html` 这个文件。是否是在你的站点目录下包含 `README.md` 文件？我这边生成之后的 `public` 目录：https://github.com/iissnan/notes

第二个，无论在站点的 `_config.yml` 或者在主题的 `_config.yml`， 都会应用于首页的 `Comment Count`  以及 文章/页面的评论的控制。 `theme.*` 是继承于 `site.config`，所以他们是没有分别的。

我稍后修复第三个问题。

谢谢你的反馈：）
