### ISSUE TITLE
请问标签 能否增加多级目录功能

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1400]
### Expected behavior (预期行为)
类似https://github.com/pengloo53/Hexo-theme-light_cn里面的多级目录，
 ![](http://7xr5a7.com1.z0.glb.clouddn.com/2%E6%97%A0%E6%A0%87%E9%A2%98.PNG)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by yusmile** [comment]
这两天发现不少hexo的博客下都有两级目录，但是不知道怎么设置的，有知道的达人能指点下吗？

**Comment by hippo-jessy** [comment]
在写catergories的时候按照下面的规则
categories: [一级目录, 二级目录]
比如位于"技术->Git"子目录下的文章则为：
categories: [技术, Git]

**Comment by yusmile** [comment]
@hippo-jessy 我去试试，谢谢你的回复
