### ISSUE TITLE
执行"npm install hexo-generator-searchdb --save"后出错

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1401]
### Actual behavior (实际行为)
 ![](http://7xr5a7.com1.z0.glb.clouddn.com/%E5%87%BA%E9%94%99.PNG)
请问这是为什么？
 应该怎么办呢？

**Comment by flashlab** [comment]
这不是错误，忽略就行

**Comment by yusmile** [comment]
谢谢楼上的回复
