### ISSUE TITLE
没百度到怎么解决乱码问题，求助！

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1402]
### Actual behavior (实际行为)
站点设置中：
 language: zh-Hans
但还是下面的结果：
![](http://7xr5a7.com1.z0.glb.clouddn.com/%E9%94%99%E8%AF%AF2.PNG)

**Comment by yusmile** [comment]
不管本地预览还是打开网站 都是这样的乱码，我是按教程设置的啊，怎么解决呢？

**Comment by amoyiki** [comment]
@yusmile 这应该跟Hexo 或 next主题无关，因为next自带的中文显示都是很正常的。你可以检查一下你的.md文本是不是utf-8的格式。然后我看正文内容的格式好像是有错的，否则不应该出现title，category等关键字，其中data 应该是 date才对

**Comment by yusmile** [comment]
@amoyiki 谢谢回复，奇怪的是我是按教程走的啊，但是主页也是乱码，要不我把hexo都卸载再试试

**Comment by Neveryu** [comment]
编辑器编码选择UTF-8无BOM

**Comment by djyde** [comment]
浏览器编码设置问题

**Comment by yusmile** [comment]
不用系统自带笔记本打开，问题已解决，谢谢！@djyde  @Neveryu

**Comment by Zhang21** [comment]
编码问题，我今天也遇到了，windows上记事本的锅！另存为的时候选择UTF-8覆盖源文件
