### ISSUE TITLE
NexT使用文档问题

### ISSUE THREAD

**Issue by am1006** [iissnan/hexo-theme-next#1404]
[使用文档](http://theme-next.iissnan.com/)
内部无法切换标签

<html>
<body>
<a href="http://p1.bpimg.com/4851/fa8399058e4a6e54.png" title="点击显示原始图片"><img src="http://p1.bpimg.com/4851/fa8399058e4a6e54t.jpg"></a>
</body>
</html>

就是这个
点了没有用

----
OS: WINDOWS  chrome 55

----

谢谢！

**Comment by yusmile** [comment]
是的 几个地方都是这样，我这边点击了也没变化

**Comment by am1006** [comment]
还有一些标注“ ”也没有显示出来

**Comment by Neveryu** [comment]
:smile:

**Comment by xovel** [comment]
资源被墙的问题。翻个墙就好了。

**Comment by iissnan** [comment]
已修复

**Comment by am1006** [comment]
谢谢。
