### ISSUE TITLE
在64位WIN7系统下安装HEXO出现错误

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1406]
我是在64位WIN7系统下安装的：
1.安装Git
到[官网]https://git-scm.com/download/win)下载 Git，一路默认选项安装。使用的是Git-2.11.0.3-64-bit
2.安装Node.js
到官网下载 Node.js，保持默认设置即可，一路Next。使用的是node-v6.2.0-x64
3.安装Hexo
Git 和 Node.js 都安装好后,首先创建一个用于存放博客文件的文件夹(比如取名 hexo），然后进入 hexo 文件夹，下面开始安装并使用 Hexo。右键选择Git Bash Here，弹出Git Bash窗口；执行命令：
npm install hexo-cli -g
**出现两个错误**
npm WARN optional Skipping failed optional dependency /hexo-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
![](http://upload-images.jianshu.io/upload_images/4542536-6145c6bd23de90dd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
**这是怎么回事呢？有没前辈能帮忙看下？**

**Comment by Adiwon** [comment]
不用理会它们，你已经安装成功了。

**Comment by sky-admin** [comment]
不要在意警告……错误才需要考虑……

**Comment by yusmile** [comment]
@Adiwon   @sky-admin 谢谢两位的回复
