### ISSUE TITLE
guestbook 访客头像错误

### ISSUE THREAD

**Issue by bojackchen** [iissnan/hexo-theme-next#1409]
[留言板](https://bojackchen.github.io/guestbook)

### Expected behavior (预期行为)
guestbook 页本来应该显示访客留言和头像

### Actual behavior (实际行为)
guestbook 页头像和留言显示不正常
Chrome Warning 信息：
Mixed Content: The page at 'https://bojackchen.github.io/guestbook/' was loaded over HTTPS, but requested an insecure image 'http://.../...'. This content should also be served over HTTPS.

### Steps to reproduce the behavior (重现步骤)
不知道这是 next theme 的问题还是多说的问题，所以希望检查一下。谢谢！

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

### Other Informations (Like Browser, System, Screenshots)
win7 Chrome 56.0.2924.76
[留言板](https://bojackchen.github.io/guestbook)

**Comment by Neveryu** [comment]
这只是一个警告而已，图像依旧会正常显示

**Comment by bojackchen** [comment]
可是。。。真的不能显示了
[留言板](https://bojackchen.github.io/guestbook/)
