### ISSUE TITLE
本地预览正常，发布到github上一片空白

### ISSUE THREAD

**Issue by edonyM** [iissnan/hexo-theme-next#1410]
### Expected behavior (预期行为)
正常发布到github上

### Actual behavior (实际行为)
github上显示一片空白，但是本地预览的时候正常

### Steps to reproduce the behavior (重现步骤)
怀疑是我自己配制哪里有问题

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release  ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔

### Other Informations (Like Browser, System, Screenshots)
Chrome和Safari都有这个问题，macOS 10.12.3
地址：https://edonym.github.io/

* 发布到github：
<img width="1434" alt="screen shot 2017-02-03 at 23 02 28" src="https://cloud.githubusercontent.com/assets/7744664/22596041/e8ccbe5e-ea64-11e6-8fcb-4117f1abe313.png">

* 本地预览：
<img width="1142" alt="screen shot 2017-02-03 at 23 04 18" src="https://cloud.githubusercontent.com/assets/7744664/22596094/290ea1bc-ea65-11e6-8723-0be9aa1ecbc5.png">

**Comment by amoyiki** [comment]
@edonyM 这应该是 GitHub Pages过滤了 source/vendors的问题。[#1214](https://github.com/iissnan/hexo-theme-next/issues/1214) 
然后作者给出的方案是
> 不清楚为什么 GitHub Pages 过滤掉了 source/vendors 目录的访问。我提交了一个更新到 master 分支上，> 修正这个问题，可以更新下。
> 也可以手动将 source/vendors 目录修改成 source/lib （或者其他的名称，只是 lib 我测试了可以使用）；> 同时，修改下主题配置文件_config.yml， 将 _internal: vendors 改成你所修改的名字，例如 _internal: lib。

**Comment by Neveryu** [comment]
> github上显示一片空白，但是本地预览的时候正常
> 
> Steps to reproduce the behavior (重现步骤)
> 
> 怀疑是我自己配制哪里有问题


在根目录添加.nojekyll文件.

**Comment by edonyM** [comment]
@amoyiki @Neveryu 已经是最新的master分支的代码了，也添加了.nojekyll文件，但是还是没有解决。
目录结构如下所示，这个根目录是指./，还是指themes/next，我看https://github.com/iissnan/hexo-theme-next/issues/1214里面有提到需要修改配置里面的include: .nojekyll，这个修改是hexo的配置文件还是next主题的配置文件。
.
├── _config.yml
├── db.json
├── node_modules
├── package.json
├── public
├── source
└── themes

**Comment by Neveryu** [comment]
最新版的应该解决这个问题了吧，把那个.nojekyll去掉吧

**Comment by amoyiki** [comment]
@edonyM 其实你可以F12打开chrome的调试，看看是具体哪些资源没有加载成功

**Comment by jetyu** [comment]
当时我写了一篇guide，你可以参考一下。https://jetyu.me/%E6%8A%80%E6%9C%AF/20161104.html

**Comment by ivan-nginx** [comment]
@edonyM don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Bodemon** [comment]
解决了吗

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
