### ISSUE TITLE
如何插入 svg 图片？

### ISSUE THREAD

**Issue by ipreacher** [iissnan/hexo-theme-next#1411]
### Expected behavior (预期行为)
svg 图片中加入了链接，希望点击图片可以跳转到特定网页

### Actual behavior (实际行为)
点击图片后是查看放大的图片

### Steps to reproduce the behavior (重现步骤)
我的博客中，这篇文章的底部有八个 svg 图片：https://ipreacher.github.io/2017/svg/

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
Browser：Safari、Chrome
System：OS X 10.10.5 
有遇到过类似问题的同学吗，求解决

**Comment by iissnan** [comment]
图片默认都加上了 Fancybox 的特性，因此无法点到图片内部的内容。两种解决方案：

1. 禁用 Fancybox
2. 修改 `source/js/src/utils.js` 文件的 `wrapImageWithFancyBox` 函数。将包含 `svg` 格式的图片过滤掉：

```js 
$('.content img')
  .not('.group-picture img, .post-gallery img')
  .not(function () { return /\.svg$/.test(this.src); })
```

**Comment by Leo-Mu** [comment]
你是如何在 Hexo 中插入 SVG 图片的？我这里试了标签插件，直接报错， Markdown 显示不出来。
我开启了资源文件夹，但是根据[文档](https://hexo.io/zh-cn/docs/asset-folders.html#%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84%E5%BC%95%E7%94%A8%E7%9A%84%E6%A0%87%E7%AD%BE%E6%8F%92%E4%BB%B6)应该都可以啊。
