### ISSUE TITLE
百度快照不显示内容

### ISSUE THREAD

**Issue by fupengzhan** [iissnan/hexo-theme-next#1413]
### Expected behavior (预期行为)
显示页面内容

### Actual behavior (实际行为)
显示网页框架，但没有内容

### Steps to reproduce the behavior (重现步骤)
百度搜索，点击页面快照

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by CPUdream** [comment]
同求这个问题

**Comment by ivan-nginx** [comment]
@fupengzhan don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by fupengzhan** [comment]
惊到我了，作者原来不会中文啊。我是不会英文，看来这个问题是解决不了了。

**Comment by fupengzhan** [comment]
I can not speak English, only to close the case. This sentence is translated by Google.
