### ISSUE TITLE
主题main.css文件在哪？

### ISSUE THREAD

**Issue by 3cheng** [iissnan/hexo-theme-next#1414]
在source找了半天没找到

**Comment by Neveryu** [comment]
在这里啦，
[https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/main.styl](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/main.styl)

**Comment by djyde** [comment]
https://github.com/iissnan/hexo-theme-next/blob/master/source/css/main.styl

**Comment by menhu** [comment]
我的css目录里面,产生的是main.styl 文件，但是页面引用的是 main.css文件。所以页面没有样式。请问这个问题是怎么解决。
