### ISSUE TITLE
请问下如何删除旧文章？

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1416]
### Expected behavior (预期行为)
1、如果曾经发布了博客，可否修改博客发布的时间？
2、想删除已经发布的文章，并清除该文章生成的分类和标签，应当怎么操作呢？

**Comment by xovel** [comment]
首先，这个问题非主题相关功能。

----

参考解决方案：
1. 博客发布时间，通过具体文章的markdown文件中的Front-matter指定。里面的date对应的就是文章的发布时间。
2. 直接删除即可，清除该文章生成的分类和标签请使用`hexo clear`命令重置数据库文件即可。

**Comment by duanego** [comment]
test
