### ISSUE TITLE
配置leanclound 报这样的错误： hexo-theme-next/layout/_scripts/schemes/.swig

### ISSUE THREAD

**Issue by guoshimeihua** [iissnan/hexo-theme-next#1417]
在config.yml配置如下内容：
# 阅读次数统计
leancloud_visitors: 
  app_id: x6gb9sUmgwMDjS8rk9t7dWfa-gzGzoHsz
  app_key: 9fDlDQ7AKUTm7vrfBdCULgAz
  enable: true

然后报no such file or directory, open hexo-theme-next/layout/_scripts/schemes/.swig这样的错误，如果不配置阅读次数统计，则正常。

scheme配置如下：
# Schemes
#scheme: Muse
scheme: Mist
#scheme: Pisces

**Comment by peipeiguo** [comment]
最好找个 YAML Lint 验证下 _config.yml 是否有问题。
可以在线 Lint 工具：[YAML Validator](http://codebeautify.org/yaml-validator)

**Comment by tonydeng** [comment]
[YAML Validator](http://codebeautify.org/yaml-validator)不是太好用。

推荐使用 [YAMLlint](http://www.yamllint.com/)

**Comment by ivan-nginx** [comment]
@guoshimeihua don't understand u, write in English if not solved. If solved, close it please. Thank's!
