### ISSUE TITLE
Pisces主题下header里的菜单toggle按钮位置不对

### ISSUE THREAD

**Issue by BubblyPoker** [iissnan/hexo-theme-next#1419]
### Actual behavior (实际行为)
在小屏下(width <= 991px)下 顶部的menu展开后，menu的toggle按钮位置错位

.site-nav-toggle {
  left: 20px;
  top: 50%;
  top: calc(50% - 3px);
  ...
}

menu展开后50%的高度就变了，这个时候toggle按钮的top也变了

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  ✔ Pisces

### Other Informations (Like Browser, System, Screenshots)
windows10 Chrome 55

**Comment by xoyofan** [comment]
同，我也发现这个问题了。

**Comment by zhyt0520** [comment]
同样问题

**Comment by zhyt0520** [comment]
是这个引起的，请作者改一下吧，就一行代码
commit 1c5ea7064ef72a1d293ae52c2edc3e44362fd7a3
![](http://wx2.sinaimg.cn/mw690/6cae667fly1fcrmuk4twxj20cu0audg8.jpg)
问题效果图，蓝色框是错位的 Nav
![](http://wx2.sinaimg.cn/mw690/6cae667fly1fcrmukne56j207307z3yc.jpg)

**Comment by Acris** [comment]
已修复。
https://github.com/iissnan/hexo-theme-next/pull/1439
