### ISSUE TITLE
底部访客统计未居中

### ISSUE THREAD

**Issue by to2false** [iissnan/hexo-theme-next#1420]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔ 

### Other Informations (Like Browser, System, Screenshots)
![wechatimg1](https://cloud.githubusercontent.com/assets/21302817/22728756/9657a026-ee1a-11e6-8b79-825e21c82a84.jpeg)

**Comment by Neveryu** [comment]
改了什么后引起的？

**Comment by to2false** [comment]
@Neveryu 我就导入主题，就更改了配置参数开启了些功能，没更改其他部分

**Comment by ivan-nginx** [comment]
@to2false in standart apperance we can not do what we see on your screen. This was custom manipulates in css styles and, yeap, may be just centered block div style?
