### ISSUE TITLE
第三方搜索服务bug

### ISSUE THREAD

**Issue by maxmeng93** [iissnan/hexo-theme-next#1421]
### Expected behavior (预期行为)
我的博客按照文档配置了Algolia 搜索，可以得到正确的搜索结果，但是搜索结果的文章链接错误

### Actual behavior (实际行为)
点击搜索结果后，无法跳转到正确的页面。图片中可以看到搜索得到的链接都是undefined
![](http://ww1.sinaimg.cn/large/005VWk7Ogy1fck7ejx4p8j30ri0f6tae)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by itvincent-git** [comment]
看这个 https://github.com/iissnan/hexo-theme-next/issues/1084#issuecomment-260630348 要修改command.js文件

**Comment by itvincent-git** [comment]
不过这样的方式不是很好，我看到algolia是有index完整url的，https://github.com/iissnan/hexo-theme-next/issues/1084#issuecomment-260630348 这种方式其实是重复了index

**Comment by iissnan** [comment]
hexo-algolia 最新的版本（0.1.1）将 `path` 字段移除了，代替的是 `permalink` 字段，因此出现了这个问题。

最新的 NexT 解决了这个问题。另外一种方法是，使用 hexo-algolia 0.2.0 这个版本。
