### ISSUE TITLE
使用algoia搜索，第二次点击不弹窗

### ISSUE THREAD

**Issue by itvincent-git** [iissnan/hexo-theme-next#1422]
### Expected behavior (预期行为)
第一次打开搜索菜单，弹出algolia搜索框
关闭搜索框
再点击搜索菜单，再次弹出algolia搜索框

### Actual behavior (实际行为)
第一次打开搜索菜单，弹出algolia搜索框，显示js错误
关闭搜索框
再点击搜索菜单，不弹出algolia搜索框，显示一个黑色的蒙层。

### Steps to reproduce the behavior (重现步骤)
打开搜索菜单，弹出algolia搜索框，显示js错误
关闭搜索框
再点击搜索菜单

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist✔
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
chrome,mac

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.success (localhost/:989)
    at j (index.js:2)
    at Object.fireWith [as resolveWith] (index.js:2)
    at x (index.js:4)
    at XMLHttpRequest.<anonymous> (index.js:4)
```

**Comment by itvincent-git** [comment]
每次都会加载localsearch.swig，搜索代码发现_layout.swig会加载，没有作判断，把localsearch.swig去掉就正常了

**Comment by flashlab** [comment]
@itvincent-git 有判断，在`/layout/_partials/search.swig`
你需要在配置文件里删除search字段

**Comment by itvincent-git** [comment]
@flashlab 一开始就是这样改的，奇怪的是我把search删除了，仍然会执行到search.swig里面的逻辑
