### ISSUE TITLE
不蒜子访客统计数量不准

### ISSUE THREAD

**Issue by KevinL-94** [iissnan/hexo-theme-next#1423]
启动不蒜子统计的时候直接就有1万多的访客和2万多的访问量，请问如何清0呢？

**Comment by KevinL-94** [comment]
发现原来只有本地端测试的时候统计才有问题，部署后显示是正常的

**Comment by Neveryu** [comment]
🤐

**Comment by taosean** [comment]
请问您这个问题是怎么解决的？我也遇到了这个问题。本地起hexo server就会乱显示。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
