### ISSUE TITLE
请问能否在主页显示每篇文章发表的具体时间

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1424]
### Expected behavior (预期行为)
比如显示到几点几分发表的该文章？

**Comment by Neveryu** [comment]
将这一行
https://github.com/Neveryu/Neveryu.github.io/blob/resource/_config.yml#L56
修改为：
`date_format: YYYY-MM-DD HH:mm:ss`

**Comment by yusmile** [comment]
@Neveryu 还想请教下，原来在post模板中添加了更新时间，后面已经在post模板删除更新时间这条语句，但是为什么现在建新的文章，仍然显示更新时间呢？应当如何屏蔽文章中的更新时间？

**Comment by Acris** [comment]
@yusmile 修改主题配置文件，将`updated_at`设置为`false`。
详见：https://github.com/iissnan/hexo-theme-next/blob/master/_config.yml#L218
