### ISSUE TITLE
创建的文章的文件名是中文的，显示在页面上“未命名”

### ISSUE THREAD

**Issue by youxunlong** [iissnan/hexo-theme-next#1425]
### Expected behavior (预期行为)
文章的文件名能正常显示中文

### Actual behavior (实际行为)
实际显示“未命名”

### Steps to reproduce the behavior (重现步骤)
我是直接将以前写的md文件放入了`E:\Hexo\source\_posts`
比如：`小游戏.md`
1. `hex clean`
2. `hex g`
3. `hex s`
然后网站上文章的内容能够正常显示，但是文件名显示`未命名`

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Latest Release

NexT Scheme:

  -  Muse

**Comment by iissnan** [comment]
文章的标题并不是 Markdown 文件的名字，而是在 [Front-matter](https://hexo.io/zh-cn/docs/front-matter.html) 里指定的，例如：

```
title: Hello World
date: 2013/7/13 20:46:25
---
```

**Comment by shijiebei2009** [comment]
`---
title: XXXXX
date: 2015-10-07 14:40:32
tags: [Tools]
categories: Skill
---
`
一样的问题，部署之后显示未命名
