### ISSUE TITLE
按照文档来做可是tags页面还是显示不正确

### ISSUE THREAD

**Issue by PARADISELIN** [iissnan/hexo-theme-next#1427]
### Actual behavior (实际行为)
tags页面只有正中间显示一个“tags”

### Steps to reproduce the behavior (重现步骤)
文章头部：
```markdown
---
title: 浅谈立即执行函数表达式（IIFE）
type: "tags"
tags: 
  - JavaScript
date: 2017-02-10 14:08:21
---
```
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
`type: "tags"`
去掉这个吧。

**Comment by shepherdlazy** [comment]
参见 #1434 我的回复
