### ISSUE TITLE
next主题怎么添加最新文章，随机文章等widget?

### ISSUE THREAD

**Issue by hjrhclan** [iissnan/hexo-theme-next#1428]
next主题
怎么在侧边栏
添加最新文章，随机文章等widget?

**Comment by ivan-nginx** [comment]
@hjrhclan don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by MeteorVE** [comment]
He mean how to create some widget in sidebar, and the widget contains a article or achieve, etc.
I have the same problem.

**Comment by stevenjoezhang** [comment]
THIS REPO IS NOT SUPPORTED ANYMORE!
DON'T NEED CREATE ISSUE HERE!
NEXT MOVED HERE: https://github.com/theme-next/hexo-theme-next

NexT is rebased into organization repo https://github.com/theme-next
If you want new feature, fix, or support, create new issue in NexT v6.x repo (desirable in English).

There is instructions
on English: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md
or Chinese: https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md
how to update from v5.1.x to v 6.x

You also may read this for details: #2061

该工程已不再提供任何支持与维护！
请大家不要再在这里创建issue了！
NexT主题仓库已移动到此处: https://github.com/theme-next/hexo-theme-next

NexT已经rebase到theme-next组织(https://github.com/theme-next) 的repo中.
如果你想要求新的特性，bug修复或其他支持，请在新的v6.x的仓库下创建新issue（最好用英文，谢谢）

英文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)
或中文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md)
如何从 v5.1.x 更新到 v 6.x

**Comment by MeteorVE** [comment]
@stevenjoezhang 
謝謝，幾分鐘前回覆了這篇因為剛好搜到相關的 issue，就直接在下面做回覆了
會移轉到新 repo 去做討論的

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/awesome-next/issues/13
