### ISSUE TITLE
有页面构建成功完成,但返回下列警告，是因为我的设置问题吗？

### ISSUE THREAD

**Issue by yusmile** [iissnan/hexo-theme-next#1431]
### Actual behavior (实际行为)
The page build completed successfully, but returned the following warning:

Your site's DNS settings are using a custom subdomain, cometrue.top, that's not set up with a correct CNAME record. We recommend you set this CNAME record to point at yusmile.github.io. For more information, see https://help.github.com/pages/.

![我的域名解析设置](http://upload-images.jianshu.io/upload_images/4542536-00eb2fad41e273b2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by ivan-nginx** [comment]
@yusmile not need CNAME in DNS records. Only A with www and without www:
www A 192.30.252.153
@ A 192.30.252.153

And CNAME need to create in Github on the Settings project page.
