### ISSUE TITLE
「建议」将Fancybox 更新到3.0

### ISSUE THREAD

**Issue by chy9002** [iissnan/hexo-theme-next#1432]
`「建议」` 将Fancybox 更新到3.0，Fancybox2似乎已经没有更新了，建议升级到3.0，而且3.0对移动设备更友好。

**Comment by ivan-nginx** [comment]
@chy9002 don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by chy9002** [comment]
I just suggest upgrade Fancybox 2 to Fancybox 3.

**Comment by ivan-nginx** [comment]
@chy9002 this is already backloged, thank's.
