### ISSUE TITLE
标签的数量有正确显示，可是页面一个标签都没有

### ISSUE THREAD

**Issue by PARADISELIN** [iissnan/hexo-theme-next#1434]
### Actual behavior (实际行为)

标题头写法：
```
---
title: 浅谈立即执行函数表达式（IIFE）
type: "tags"
categories:
- JavaScript
tags:
- JavaScript
date: 2017-02-10 14:08:21
---
```
### Steps to reproduce the behavior (重现步骤)

<img width="958" alt="wx20170216-181224 2x" src="https://cloud.githubusercontent.com/assets/17696492/23017333/d2a5c41c-f474-11e6-969d-8ddffd7096e8.png">

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
去掉type

**Comment by PARADISELIN** [comment]
去掉type还是不行

**Comment by Mine-MuYan** [comment]
改成这样试试：
```
---
title: 浅谈立即执行函数表达式（IIFE）
tags: JavaScript
categories: JavaScript
date: 2017-02-10 14:08:21
---
```

**Comment by shepherdlazy** [comment]
1. 首先请检查你tags 页面的问题，确认 tags page 的 yaml 头是否是如下,如果不是改成这样
fileName: source/tags/index.md
```
---
title:
date: 2017-02-17 17:19:25
type: "tags"
---
```

2. 如果上面的检查通过了，如果还是不行，那就是文章页面 yaml 头的问题，将下面的三段代码分别替换后尝试直到，出现正确的预期结果。在你的 hexo 目录下执行指令 `hexo list tag` 确认是否正确解析了 YAML 头，然后打开 tags 页面确认是否有了。

```
---
title: 浅谈立即执行函数表达式（IIFE）
categories:
  - JavaScript
tags:
  - JavaScript
date: 2017-02-10 14:08:21
---
```
或
```---
title: 浅谈立即执行函数表达式（IIFE）
categories: ["JavaScript"]
tags: ["JavaScript"]
date: 2017-02-10 14:08:21
---```
或
```---
title: 浅谈立即执行函数表达式（IIFE）
categories: JavaScript
tags: JavaScript
date: 2017-02-10 14:08:21
---```

**Comment by PARADISELIN** [comment]
@shepherdlazy 非常感谢！！！

**Comment by LYgui** [comment]
成功了，thx
