### ISSUE TITLE
404页面不能正确跳转

### ISSUE THREAD

**Issue by Mine-MuYan** [iissnan/hexo-theme-next#1435]
### Expected behavior (预期行为)
在站内访问错误的网址的时候，打开的页面应该是设置的404页面。
![image](https://cloud.githubusercontent.com/assets/23254569/23051468/2e2ba5f6-f504-11e6-99a1-369228308725.png)

#### 本地上在站内访问错误的网址的时候，显示的是这样：
![image](https://cloud.githubusercontent.com/assets/23254569/23051528/c5ed53b2-f504-11e6-8369-6bfe49f98071.png)
### NexT Version:
  hexo: 3.2.2
  hexo-cli: 1.0.2
  os: Windows_NT 6.1.7601 win32 x64
  http_parser: 2.7.0
  node: 6.9.5
  v8: 5.1.281.89
  uv: 1.9.1
  zlib: 1.2.8
  ares: 1.10.1-DEV
  icu: 57.1
  modules: 48
  openssl: 1.0.2k

### NexT Scheme:
  -  Mist

#### 404页面的设置方法
![image](https://cloud.githubusercontent.com/assets/23254569/23051619/661006d2-f505-11e6-9b4a-27d664542bcc.png)

**弄了半天没没弄好，特来求助...**

**Comment by iissnan** [comment]
你的站点启用了 https，腾讯公益 404 的脚本是 http 协议，因此这段脚本被阻止了。

解决的方法是将页面里的 `script` 换成如下：

```html
  <script type="text/plain" src="http://www.qq.com/404/search_children.js"
          charset="utf-8" homePageUrl="/"
          homePageName="回到我的主页">
  </script>
  <script src="https://qzone.qq.com/gy/404/data.js" charset="utf-8"></script>
  <script src="https://qzone.qq.com/gy/404/page.js" charset="utf-8"></script>
```

**Comment by Mine-MuYan** [comment]
我之前查了很多，后来发现是因为没有绑定域名，404页面需要在一级域名下才能实现，因为近期没有买域名的打算，所以也没再问，都20天了才发现你的回复，不好意思。

我试了，你说的那种方法，站内访问错误页面可以跳转到404页面，不过css没了。
![image](https://cloud.githubusercontent.com/assets/23254569/23685703/7ea08a70-03e0-11e7-9344-34b530fcaee7.png)

这是404页面的内容：
```html
<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="content-type" content="text/html;charset=utf-8;"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="robots" content="all" />
  <meta name="robots" content="index,follow"/>
</head>
<body>

  <script type="text/plain" src="http://www.qq.com/404/search_children.js"
          charset="utf-8" homePageUrl="/"
          homePageName="回到我的主页">
  </script>
  <script src="https://qzone.qq.com/gy/404/data.js" charset="utf-8"></script>
  <script src="https://qzone.qq.com/gy/404/page.js" charset="utf-8"></script>


</body>
</html>
```

还有一个问题是：
因为博客中使用了网易云，网易云也是http协议，控制台上会有这样的警告：
![image](https://cloud.githubusercontent.com/assets/23254569/23685896/885557f2-03e1-11e7-936f-8e3b39ad18db.png)

后来，我查了下，在 ```C:\Users\Administrator\Mine-MuYan\themes\next\layout\_partials\head.swig```文件里加上一段``` <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">```就可以了，确实也生效了，控制台上没有警告信息了，但是本地上，所有的css样式都没了。
![image](https://cloud.githubusercontent.com/assets/23254569/23685937/acf82486-03e1-11e7-900b-2dd18790b278.png)

其实这也没什么，不耽误博客的整体运行，就是想接着问难问下，怎么在```hexo d``` 时忽略某个文件的上传？
问题太多，麻烦你了。
@iissnan

**Comment by tnie** [comment]
可以参考一下这篇：[](https://github.com/hexojs/hexo/issues/2411)

**Comment by ivan-nginx** [comment]
@Mine-MuYan don't understand u, write in English if not solved. If solved, close it please. Thank's!
