### ISSUE TITLE
如何向next主题中添加js

### ISSUE THREAD

**Issue by hyhajnal** [iissnan/hexo-theme-next#1436]
我在source/js 中添了一个js文件 不执行 不知为何

**Comment by Neveryu** [comment]
添加到这个里面。
`/themes/next/layout/_layout.swig`


[有问题给我留言](https://neveryu.github.io/guestbook)

**Comment by hyhajnal** [comment]
但貌似作者的js都写在
``` js
/themes/next/source/js
```

还有如果在layout.swig下外部引入自己的js，src的路径（除了用相对路径）next中有没有声明类似如下（_scripts/）的路径变量

``` js
{% include '_scripts/third-party/comments.swig' %}
```

**Comment by snowluliang** [comment]
在_Layout.swig中进行引用,</body>标签前:
<script type="text/javascript" src="/js/src/XXXX.js"></script>

**Comment by hyhajnal** [comment]
谢啦 @snowluliang 回头试试

**Comment by snowluliang** [comment]
@hyhajnal  welcome.试试有没有效果

**Comment by MuYunyun** [comment]
@hyhajnal 这种方式能引进JS文件，但是bower.json里定义的"jquery": "http://code.jquery.com/jquery-2.1.3.min.js" 却不能在该JS文件中使用，我现在的解决方法是在<script type="text/javascript" src="/js/src/XXXX.js"></script>前在引用一次jquery，有没有什么优化方案？

**Comment by snowluliang** [comment]
xxxx.js 换成你要的js文件吧

**Comment by ivan-nginx** [comment]
@hyhajnal don't understand u, write in English if not solved. If solved, close it please. Thank's!
