### ISSUE TITLE
首页-文章标题下面的评论取消了？

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#144]
能否加回来！

**Comment by eurusd** [comment]
原因：
`hexo\themes\next\layout\_scripts\comments\duoshuo.swig`
把`{% if (theme.duoshuo and theme.duoshuo.shortname and page.comments) or (theme.duoshuo_shortname and page.comments)%}`
改为
`{% if (theme.duoshuo and theme.duoshuo.shortname) or theme.duoshuo_shortname %}`

**Comment by mingmings** [comment]
更新了的确看不到多说评论呢

**Comment by iissnan** [comment]
@eurusd :+1:
