### ISSUE TITLE
关于next主题配置文件canvas_nest:的问题？

### ISSUE THREAD

**Issue by MustardG** [iissnan/hexo-theme-next#1442]
canvas_nest:应该是线条动画效果，好像没有教程，设置为true后也没有用
我是这样设置的：
                # Internal version: 1.0.0
                # https://github.com/hustcc/canvas-nest.js
                 canvas_nest: true

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:最新版

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  Pisces

**Comment by Acris** [comment]
配置有误。你这里是配置CDN用的，没有特殊需求留空就好。
应该将此处改为true：https://github.com/iissnan/hexo-theme-next/blob/master/_config.yml#L442

**Comment by MustardG** [comment]
可是我加了cdn后却没有动画效果

**Comment by MustardG** [comment]
知道了，谢谢
