### ISSUE TITLE
next能否在文章中自定义“特定几个字”显示的颜色和大小

### ISSUE THREAD

**Issue by alexpdh** [iissnan/hexo-theme-next#1445]
### Expected behavior (预期行为)
“next” 显示为4号微软雅黑蓝色字体

### Actual behavior (实际行为)

通过html的font标签可以设置大小，但是颜色和字体不生效
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
试试使用`!important`覆盖。

**Comment by alexpdh** [comment]
请问是在font标签中加吗，方便给一个示例吗

**Comment by alexpdh** [comment]
@Acris 您说的是 <font color="#FF0000" !important>next</font> 这样吗，方便给个示例吗

**Comment by Acris** [comment]
markdown里面是可以直接用HTML标签的。
你可以试试这样：` <span style="color: red;">红色字体</span>`
还不行的话试试  `<span style="color: red !important;">红色字体</span>`

**Comment by alexpdh** [comment]
可以了，谢谢。之前是我语法有问题。我想写一个文字链接，之前是这样写的：<font color=red size=4 face=“黑体”>[next](http://theme-next.iissnan.com/) </font>，这样写只有字体大小生效，其他不生效。后来换成：[<font color=red size=4 face=“黑体”>next</font>](http://theme-next.iissnan.com/) 生效了
