### ISSUE TITLE
next主题如何设置透明度？

### ISSUE THREAD

**Issue by XmGao** [iissnan/hexo-theme-next#1448]
设置了canvas nest ，但线条只在边上显示，手机版几乎不显是，看到别人的博客设置了透明度，显示出canvas nest       http://jinfang.life
如何设置？
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:最新版

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
windows

**Comment by MustardG** [comment]
还有https://notes.wanghao.work

**Comment by Acris** [comment]
他们使用的Scheme和你不一样，你切换成Mist或者Muse就会是透明的了。
不建议更改Pieces的透明度。如果非要改，可以使用`opacity`属性。

**Comment by MustardG** [comment]
请问这个属性在哪个文件中？这个好像是css属性

**Comment by Acris** [comment]
@MustardG 你如果自己要改的话，可以用类似`background: rgba(255, 255, 255, 0.5)`的方式将`content-wrap`、`sidebar`、`nav`等几个地方的背景设置为半透明。

**Comment by MustardG** [comment]
请问在那个文件中？

**Comment by ivan-nginx** [comment]
@xuanmiaog don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by mxdhqm** [comment]
正好在弄这个，看到了。
修改该目录下的css
themes\next\source\css\_schemes\Pisces\_layout.styl
修改点如@Acris所说，透明度自己调吧

**Comment by PaPa-jun** [comment]
可以通过修改  source_data/styles.styl 来设置透明度，添加 
```syle
:root {
  --content-bg-color:rgba(128, 138, 135, 0.1);
}
```
来设置。效果类似：https://papa-jun.github.io/

**Comment by LauArmy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
