### ISSUE TITLE
新建的标签页、分类页、关于页不显示

### ISSUE THREAD

**Issue by LuckX** [iissnan/hexo-theme-next#1449]
### Expected behavior (预期行为)
点击文章里面的分类（示例）可以正常跳转到示例界面
![image](https://cloud.githubusercontent.com/assets/7693720/23100168/034a9894-f6b5-11e6-801f-791786c6d528.png)

![image](https://cloud.githubusercontent.com/assets/7693720/23100176/2c559d4c-f6b5-11e6-9ef6-25fd924f5e16.png)
但是点击页面上的菜单栏分类，页面无法找到
![image](https://cloud.githubusercontent.com/assets/7693720/23100183/43cd8cf0-f6b5-11e6-908a-126d51645701.png)

![image](https://cloud.githubusercontent.com/assets/7693720/23100185/50c91532-f6b5-11e6-94fd-42de8782e910.png)

### Steps to reproduce the behavior (重现步骤)
按照官网上的步骤来的 http://theme-next.iissnan.com/theme-settings.html#categories-page
![image](https://cloud.githubusercontent.com/assets/7693720/23100186/5b1f53e8-f6b5-11e6-8bb9-e6ce6557a250.png)

![image](https://cloud.githubusercontent.com/assets/7693720/23100202/c3a7599c-f6b5-11e6-962c-b75bed4e9953.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by LuckX** [comment]
我启动$ hexo server进http://localhost:4000/看是有的，但是上https://luckx.github.io/没有

**Comment by LuckX** [comment]
问题已解决：
menu:
  home: /
  categories: /categories/
  archives: https://LuckX.github.io/archives/
  tags: https://LuckX.github.io/tags/
  about: https://LuckX.github.io/about/
  #sitemap: /sitemap.xml
  #commonweal: /404.html

**Comment by njafei** [comment]
这样解决，真的好吗？感觉是next的bug，我这边也遇到了，看起来是链接的问题

**Comment by jasonjsk** [comment]
我用的icarus主题，也遇到这个问题了

**Comment by chKatie** [comment]
怎么解决？

**Comment by ethanzhoujie** [comment]
@njafei @jasonjsk @chKatie 

首先请检查你tags 页面的问题，确认 tags page 的 yaml 头是否是如下,如果不是改成这样
fileName: source/tags/index.md
```
---
title:
date: 2017-02-17 17:19:25
type: "tags"
---
```

**Comment by morehao** [comment]
我也是标签页面本地可以访问，一旦部署之后就是404，求解。。
