### ISSUE TITLE
social_icons 中 Github 的图标显示为 globe

### ISSUE THREAD

**Issue by varzy** [iissnan/hexo-theme-next#1450]
目前我在 _config.yml 中的更改应该是没有问题的。

![image](https://cloud.githubusercontent.com/assets/13913491/23100591/255fe29e-f6c0-11e6-85ad-7d70d8a18658.png)

![image](https://cloud.githubusercontent.com/assets/13913491/23100595/323b0ba6-f6c0-11e6-87fd-86901cf5774a.png)

使用版本：

从 https://github.com/iissnan/hexo-theme-next/releases 下载的 5.1.0 版本。

**Comment by varzy** [comment]
plus, 我下载了最新的 FontAwesome 并重新引入到 lib 中，仍然没有解决。

**Comment by Acris** [comment]
配置应该没问题，试下先`hexo clean`再`hexo g && hexo s`看看本地访问有没有问题。

**Comment by iissnan** [comment]
配置中的大小写没有匹配

**Comment by CX1ng** [comment]
@varzy  方便说一下你的解决步骤吗？

**Comment by varzy** [comment]
@CX1ng 确实是大小写写错了。一个是 `Github`，一个是 `GitHub`，改成一致的即可。

**Comment by CX1ng** [comment]
@varzy 非常感谢！ : )
