### ISSUE TITLE
Algolia搜索popup出来之后没有关闭按钮

### ISSUE THREAD

**Issue by herunyu** [iissnan/hexo-theme-next#1451]
### Expected behavior (预期行为)
Algolia搜索popup出来之后应该有关闭按钮

### Actual behavior (实际行为)
Algolia搜索popup出来之后没有关闭按钮
![image](https://cloud.githubusercontent.com/assets/5023850/23103084/2204125c-f6f0-11e6-9edf-dd8f4643c608.png)

### Steps to reproduce the behavior (重现步骤)
点击搜索

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes ✔
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
看起来好像是和local search样式冲突了，我明天改一下。
