### ISSUE TITLE
首页 Read More（阅读更多）如何居中（center）?

### ISSUE THREAD

**Issue by o1xhack** [iissnan/hexo-theme-next#1452]
首先搜出来 #205
按照回答把所需要的添加到 customize 中依旧没有任何效果

### Expected behavior (预期行为)
[展示效果](http://wellliu.com)
首页中每篇文章的最下面阅读原文居中

### Actual behavior (实际行为)
么有任何反应。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔ -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔ -  Mist
  -  Pisces

**Comment by Hipple** [comment]
你好，想请教一下怎么实现列表显示 图片？

**Comment by cwyaml** [comment]
列表显示？？ 你说的是图片模式吧！看看这里是不是你想要的
http://www.cwyaml.top/2017/01/25/hexo2/

**Comment by ivan-nginx** [comment]
@o1xhack don't understand u, write in English if not solved. If solved, close it please. Thank's!
