### ISSUE TITLE
混合内容导致https绿标失效

### ISSUE THREAD

**Issue by Fomovet** [iissnan/hexo-theme-next#1454]
博客地址：[www.Fomovet.com](http://Fomovet.com)
错误原因：

`Mixed Content: The page at 'https://fomovet.com/2017/02/16/hello-world/' was loaded over HTTPS, but requested an insecure image 'http://wx.qlogo.cn/mmopen/ibdbgXWjCJE9zZoAnlt4KqRac5SlCUicuT3WGtvRUOYUY3Vu40FS4MJOlVQ4ibxhhhDl6AYP8pdypgvWUnPFEI5Elc0WOnwTbqT/0'. This content should also be served over HTTPS.
`

原因分析：
               头像地址使用了http协议导致网站地址https绿标显示不正常，并在调试台出现错误

疑问：    
               头像是存放在/source/imgers/目录下的为何图片出现在了http://wx.qlogo.cn

**Comment by Acris** [comment]
似乎没问题
![avatar.png](https://ooo.0o0.ooo/2017/02/21/58ab95435abc7.png)

**Comment by Fomovet** [comment]
原因已找到：头像使用的是本地图片没错，我登陆多说使用的是微信登陆而多说目前头像和表情还不支持https所以会出现这个混合显示错误这个问题。

**Comment by Acris** [comment]
@Fomovet 多说的问题可以看下这个：https://blog.mrx.one/2015/10/05/Let-duoshuo-comment-box-fully-support-HTTPS/

**Comment by Fomovet** [comment]
需要买一个vps来申请证书对吗？

**Comment by Acris** [comment]
反向代理需要的。
