### ISSUE TITLE
你好，请问所有页面关于分页的链接是否可以显式指定URL为.index.html这样的后缀？

### ISSUE THREAD

**Issue by tianshuang** [iissnan/hexo-theme-next#1459]
站点的配置文件中可以设置每篇文章的URL格式，但是关于分页地址的URL尝试修改node_modules的相关js，只对生成的文件名起作用，没有对页面中链接的URL进行修改，请问哪里可以配置生成页地址的format？谢谢

**Comment by tianshuang** [comment]
我这样做的原因是因为博客的静态文件直接放到对象存储，然后通过CDN分发，而对象存储并不像传统web服务器当用户请求/结尾的地址时会server index.html的文件，对象存储只会相应404，所以我想将页面中的链接全部显式为真实文件的地址，即以index.html结尾，谢谢

**Comment by tianshuang** [comment]
你好，我通过搜索class样式找到/node_modules/hexo/lib/plugins/helper/open_graph.js中
将
`  function link(i) {
    return self.url_for(i === 1 ? base : base + format.replace('%d', i));
  }`
改为
`  function link(i) {
    return self.url_for(i === 1 ? base : base + format.replace('%d', i)) + "index.html";
  }`
即达到了目的，请问楼主能否提供更好的配置方式？改源码不是解决之道啊

**Comment by iissnan** [comment]
可以参考这个 issue：https://github.com/iissnan/hexo-theme-next/issues/604

**Comment by ivan-nginx** [comment]
@tianshuang don't understand u, write in English if not solved. If solved, close it please. Thank's!
