### ISSUE TITLE
next 主题下文章都无法显示

### ISSUE THREAD

**Issue by o1xhack** [iissnan/hexo-theme-next#1461]
### Expected behavior (预期行为)
正常打开

### Actual behavior (实际行为)
打开所有文章全部是空白页面  [这是一篇文章](http://o1xhack.com/2017/02/21/infoit/)
可以尝试从首页中点击：[首页](http://o1xhack.com)
包括「开发者」，「尝新者」我在 index.md 中选了 page 的 layout 也一样打不开，不知道这算是什么情况？
md 解析失败？还是什么？
换成 landscape 主题完全没有任何问题！

### Steps to reproduce the behavior (重现步骤)
自上次 deploy 后没有更改什么设置，就算有我也完全完了！现在不知道该从何下手？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
 ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
 ✔ Mist
  -  Pisces

**Comment by iissnan** [comment]
可能是某个脚本报错了，打开浏览器的控制台（通常是 F12），看看有没有错误信息

**Comment by agandong4** [comment]
打开后显示    velocity is not a function
然后Google

**Comment by stevenjoezhang** [comment]
@agandong4 请参考 https://github.com/iissnan/hexo-theme-next/issues/2198 和 https://github.com/iissnan/hexo-theme-next/issues/2197
需要等Disqus官方修复
此项目已经停止维护，请移步这里：https://github.com/theme-next/hexo-theme-next
