### ISSUE TITLE
多作者支持

### ISSUE THREAD

**Issue by geminiwen** [iissnan/hexo-theme-next#1463]
请问 Next 会提供多作者的支持么，我发现 npm 上已经有提供多作者生成的 module 了，
https://www.npmjs.com/package/hexo-multiauthor
虽然改一下模板比较简单，但是还是希望官方能兼容一个，或者自己做。
如果不计划支持，那我就自己改了。

非常感谢能提供这么好的 hexo 主题

**Comment by ivan-nginx** [comment]
@geminiwen don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by geminiwen** [comment]
It resolved, thx.
