### ISSUE TITLE
开启fancybox切换图片会出现空白图片或者错误提示

### ISSUE THREAD

**Issue by wangziling** [iissnan/hexo-theme-next#1464]
### Expected behavior (预期行为)

fancybox 出现空白图片 (修改utils.js 里面的内容 将fancybox.image删掉) 或者提示：The requested content cannot be loaded.Please try again later.(不改动utils.js文件)

### Actual behavior (实际行为)

如预期一样

我看了一下浏览器的控制台，在每个article标签中，都有一个'span itemprop="publisher"'的标签，下面都会有一个'img style="display none;" itemprop="logo"'的标签，就是这个标签的问题。 当页面上不止一个文章的时候，有几个文章就会在一次操作中出现几次这个问题。

如果不适用markdown语法或者hexo 的{%img url%}而是在Front-matter里面设置为photos: -url，这样好像photo里面的图片是识别成单独一个块，与其他图片 没关联，只会切换这里面的。
或者设置了custom_logo ，只是这个logo也会被fancybox拿到。

如果如上面那样做 就不会出现这个问题，但是那个'img style="display none;" itemprop="logo"'标签还是会生成。

### Steps to reproduce the behavior (重现步骤)

开启fancybox. 
插入图片(使用markdown自带语法或者hexo 的{% img url %})
hexo server
点击图片，左右切换
就会出现这个问题

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

✔    -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
 ✔   -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

![image](https://cloud.githubusercontent.com/assets/24818903/23216170/fefc1db0-f94f-11e6-9bca-62217f0a5550.png)

**Comment by iissnan** [comment]
已修复。

**Comment by iissnan** [comment]
Close it as already fixed.
