### ISSUE TITLE
部署git后“Tags", "Categories"404，本地可以

### ISSUE THREAD

**Issue by lele6** [iissnan/hexo-theme-next#1466]
### Actual behavior (实际行为)
部署git后“Tags", "Categories"，"About" 等打不开，显示404； post可以打开

### Steps to reproduce the behavior (重现步骤)
已new page, 已尝试在.deploy_git下面加上.nojeyll文件 并在_config.yml下添加include

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
注意大小写

**Comment by lele6** [comment]
感谢！！！我刚刚把所有Categories换成categories，这一页还是不能显示～

**Comment by iissnan** [comment]
`git mv -f Categories categories`
`hexo clean`
`hexo s --debug`

没问题后再 Generate 和 Deploy

**Comment by lele6** [comment]
解决～感谢！！！

**Comment by owen94** [comment]
请问你是怎么解决的啊？我也是本地可以但是deploy之后tags页面就是404了 谢谢

**Comment by formath** [comment]
@owen94  me too

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
