### ISSUE TITLE
可以添加网易云音乐吗

### ISSUE THREAD

**Issue by laufan** [iissnan/hexo-theme-next#1468]
加一个网易云音乐播放器 感觉很好

**Comment by Neveryu** [comment]
可以的.
[https://neveryu.github.io/guestbook/](https://neveryu.github.io/guestbook/)

**Comment by imjacewang** [comment]
@Neveryu 为什么我添加的网易云音乐宽度占满屏幕？和你的不一样。http://abai.me/2013/d9bc1991.html

**Comment by youngseaz** [comment]
我的也是横着满屏，怎么修改无效？
