### ISSUE TITLE
设置边栏头像avatar后面需要什么内容？

### ISSUE THREAD

**Issue by bigbigsnail** [iissnan/hexo-theme-next#147]
iissnan的wiki里说：
> 编辑站点的 _config.yml，新增字段 avatar， 将其设置头像的链接地址。

请问头像的链接地址该怎么写？是本地文件路径还是其他？需要装hexo其他插件么

**Comment by eurusd** [comment]
avatar连接不卡吗？ 放在七牛上还差不多！

**Comment by geekrainy** [comment]
图片链接地址可以填 `/images/avatar.jpg`, 把图片放在主题内 `source/images/` 目录下

**Comment by suoba** [comment]
直接找到原图然后ps成自己想要的就行。
