### ISSUE TITLE
welcome to my blog

### ISSUE THREAD

**Issue by cwyaml** [iissnan/hexo-theme-next#1470]
刚刚搭建好的blog ,欢迎访问。。。
http://www.cwyaml.top

**Comment by hocgit2016** [comment]
I can not do like you, i want the source code, you can send me?
my email: kiesfan@gmail.com

**Comment by Neveryu** [comment]
[https://github.com/Neveryu/Neveryu.github.io](https://github.com/Neveryu/Neveryu.github.io)

**Comment by lovejia** [comment]
https://www.lovejia.win/

**Comment by ivan-nginx** [comment]
@cwyaml don't understand u, write in English if not solved. If solved, close it please. Thank's!
