### ISSUE TITLE
如何修改Mist主题的标题颜色？

### ISSUE THREAD

**Issue by swordspoet** [iissnan/hexo-theme-next#1471]
### Expected behavior (预期行为)
我想把文章的标题颜色修改为蓝色，在/hexo/themes/next/source/css/_schemes/Mist/index.styl目录下找到了.post-title并添加font-color: blue，但是得不到想要的效果

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist✔
  -  Pisces

**Comment by Neveryu** [comment]
``` css
color: blue;
```

即可

**Comment by swordspoet** [comment]
@Neveryu 不过在首页颜色还是没有变额

**Comment by Neveryu** [comment]
> 我想把文章的标题颜色修改为蓝色

你没有说首页也要变哦，你改的那个文件，只能变打开后的文章title颜色

**Comment by ivan-nginx** [comment]
@swordspoet don't understand u, write in English if not solved. If solved, close it please. Thank's!
