### ISSUE TITLE
V5.1.0的百度自动推送好像没有效果？

### ISSUE THREAD

**Issue by Alexander-Chiang** [iissnan/hexo-theme-next#1472]
### Expected behavior (预期行为)

打开baidu_push: true，点击对应的文章即可实现自动向百度搜索推送链接。
### Actual behavior (实际行为)

在百度站长平台的链接提交中查看，没有对应的推送，请问是有哪里设置的不对了吗？
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
F12 打开 Network 面板，看下 Baidu Push 的请求是否正常发出。

**Comment by Neveryu** [comment]
gitpage 是 https 的，baidu push 是 http 的

**Comment by iissnan** [comment]
支持 https的。脚本会自动检测站点当前所使用的协议：https://github.com/iissnan/hexo-theme-next/blob/master/layout/_scripts/baidu-push.swig#L6

**Comment by Alexander-Chiang** [comment]
Push正常发出了，状态码也是200,但是有一条这样的请求：https://sp0.baidu.com/9_Q4simg2RQJ8t7jm9iCKT-xh_/s.gif?l=https://blog.jiangyayu.cn/，状态显示failed。

**Comment by Promix953** [comment]
@Alexander-Chiang 我也是这个情况

**Comment by heqiang421** [comment]
我也是这个问题，怎么解决？

**Comment by ivan-nginx** [comment]
@Alexander-Chiang don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Richard-Cao** [comment]
@Alexander-Chiang same issue.
@ivan-nginx Baidu push request failed, url like this: https://sp0.baidu.com/xxx。

**Comment by Richard-Cao** [comment]
Why closed? @Alexander-Chiang

**Comment by ivan-nginx** [comment]
@Richard-Cao can u please confirm this bug in latest release and/or master branch version? I not use baidu so i can't reproducte this bug.

**Comment by Richard-Cao** [comment]
I confirm this bug in master branch version. @ivan-nginx

**Comment by ivan-nginx** [comment]
@Richard-Cao can u give live demo with this bug?

**Comment by Alexander-Chiang** [comment]
@Richard-Cao Sometimes it works, and I don't think it is a bug. Maybe  something wrong with Baidu，haha...  So I closed it .

**Comment by Richard-Cao** [comment]
![image](https://user-images.githubusercontent.com/5953992/30043640-2fa000c0-922b-11e7-98f7-4ab06d6496ee.png)

@ivan-nginx Like this.

**Comment by ivan-nginx** [comment]
U use any `AdBlock` or `uBlock` extensions? `BLOCKED_BY_CLIENT` — it's mean on client side something blocks script loading. In you case, i turn off `uBlock` in my Chrome and all scripts after that loading fine:
![image](https://user-images.githubusercontent.com/16944225/30043810-6d2bafa8-9202-11e7-9893-c926e23782b3.png)

But when i turn uBlock on again, scripts will block again:
![image](https://user-images.githubusercontent.com/16944225/30043832-8d392d0c-9202-11e7-918d-61a1cfc550ee.png)

Can u confirm this. And please, report bugs only if u sure what it is not your browser and/or any 3rd party extensions, thank's.

**Comment by Richard-Cao** [comment]
You are right! I used this extensions:[广告终结者](https://chrome.google.com/webstore/detail/%E5%B9%BF%E5%91%8A%E7%BB%88%E7%BB%93%E8%80%85/fpdnjdlbdmifoocedhkighhlbchbiikl).
I tried when I disable this extensions, all scripts loading fine.
Thank you very much!
@ivan-nginx

**Comment by ivan-nginx** [comment]
NP. So, it not NexT theme bug and for now i close this issue.

**Comment by Richard-Cao** [comment]
Yep~
