### ISSUE TITLE
请问如何适当增加首页中多行标题与时间的行间距

### ISSUE THREAD

**Issue by smilingmouse** [iissnan/hexo-theme-next#1474]
如题，在主页中，想增加多行标题之间以及标题与时间之间的行间距，如下图中A、B位置，不知该如何实现，谢谢！

![2017-03-01_16-17-50](https://cloud.githubusercontent.com/assets/17469249/23451631/b0a7b010-fe9b-11e6-93cf-27062fbc0032.png)

NexT Version:
  -  Master
 ✔  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
 ✔  Pisces

**Comment by Neveryu** [comment]
目前标题是使用的 `<h1>` 标签，行高是 1.5 ，
媒体栏与标题之间是 3px 的间距，
你可以自行调整

**Comment by smilingmouse** [comment]
感谢您的回复！再弱弱问一下，是需要更改 public/css/main.css 的参数吗？
另外再补充一下，主页中的这两个间距和点开一篇文章后的这两个间距，也是不同的。
![0001](https://cloud.githubusercontent.com/assets/17469249/23491462/744ca1ae-ff39-11e6-86d1-03ae20d95814.png)![0002](https://cloud.githubusercontent.com/assets/17469249/23491471/7d1230b0-ff39-11e6-8407-fbf89f8e7b70.png)

**Comment by Neveryu** [comment]
NexT 提供了一个 `custom.styl` 用于我们自己自定义样式，所以最好的做法是写在这个 `custom.style` 文件里。
路径在这里： [https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/_custom/custom.styl](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/source/css/_custom/custom.styl)

**Comment by smilingmouse** [comment]
非常感谢您的耐心解答！
