### ISSUE TITLE
谷歌字体文件Failed to load response data。

### ISSUE THREAD

**Issue by ilofter** [iissnan/hexo-theme-next#1476]
https://fonts.gstatic.com/s/lato/v13/MDadn8DQ_3oT6kvnUq_2r_esZW2xOQ-xsNqO47m55DA.woff2
https://fonts.gstatic.com/s/lato/v13/1KWMyx7m-L0fkQGwYhWwuuvvDin1pK8aKteLpeZ5c0A.woff2
尝试升级到最新版本依然存在

**Comment by iissnan** [comment]
我这边可以正常的访问这两个链接，或许是网络的问题。

**Comment by RuiqiangJiao** [comment]
如何将文章的字体修改成google字体？

**Comment by iissnan** [comment]
See [设置字体 - NexT 使用文档](http://theme-next.iissnan.com/theme-settings.html#fonts-customization)
