### ISSUE TITLE
给博客的头部添加一行座右铭

### ISSUE THREAD

**Issue by swordspoet** [iissnan/hexo-theme-next#1478]
### Expected behavior (预期行为)

请问如何给头部添加一个类似座右铭？
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist✔
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

![default](https://cloud.githubusercontent.com/assets/14816130/23505967/d5409a6e-ff80-11e6-82a7-b696b72987af.png)

**Comment by Neveryu** [comment]
![tim 20170303114820](https://cloud.githubusercontent.com/assets/14313328/23537474/53848c10-0007-11e7-99e9-1d094223d071.png)

写在 `header.swing` 里面。

**Comment by ivan-nginx** [comment]
@swordspoet don't understand u, write in English if not solved. If solved, close it please. Thank's!
