### ISSUE TITLE
建议：在侧边栏显示当前文章分类下的文章列表，方便快速切换和查看同类文章

### ISSUE THREAD

**Issue by lovejia** [iissnan/hexo-theme-next#1479]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  ✔  Pisces

**Comment by Neveryu** [comment]
![tim 20170303115117](https://cloud.githubusercontent.com/assets/14313328/23537535/b94c0e42-0007-11e7-86c8-c9ac7aed79a5.png)

简约原则挺好的，文章 title 下面已经有了分类

**Comment by zhangnew** [comment]
我倒是希望侧边可以显示全部分类目录，在个人信息下面

**Comment by ivan-nginx** [comment]
@lovejia issue is solved?
