### ISSUE TITLE
图片画廊显示问题

### ISSUE THREAD

**Issue by nullsheng** [iissnan/hexo-theme-next#148]
在文章中设置photos: 内容后，在chrome中显示是正常的，在ie上显示不正常，就是图片回超出文章宽度，一直延伸出去，用ie10和ie11都试过了，都会出现这个问题。
这边好像不能添加图片示例，我的主页上可以看一下。
http://nullsheng.com

我把display:table去掉后就好一点，但是图片会被裁切。

**Comment by iissnan** [comment]
https://github.com/iissnan/hexo-theme-next/pull/150
