### ISSUE TITLE
站点配置文件line_number为true，但行号没有显示

### ISSUE THREAD

**Issue by XuanmiaoG** [iissnan/hexo-theme-next#1481]
站点配置文件line_number为true，但行号没有显示[xuanmmiao.info](url)

**Comment by XuanmiaoG** [comment]
知道了 代码块这样写
```
```

**Comment by zhangferry** [comment]
@xuanmiaog 你好，我也遇到了这个问题，你怎么解决的

**Comment by xuanmiaog** [comment]
我发现了hexo的markdown语法中用`    `来代表代码框是不会显示行号的，要用```             ```来表示。谢谢！

2017-06-30 12:35 GMT+08:00 zhangferry <notifications@github.com>:

**Comment by zhangferry** [comment]
@xuanmiaog 是这样的，多谢啦
