### ISSUE TITLE
BUG??主题 - NexT.Pisces 底部信息不会在中间！

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1482]
### Expected behavior (预期行为)
```
sidebar:
  # Sidebar Position, available value: left | right
  #position: left
  position: right
```
底信息会显示在左栏中间

### Actual behavior (实际行为)
显示在整个页面（左右两栏中间）
改为侧栏在左边显示后
```
sidebar:
  # Sidebar Position, available value: left | right
  position: left
  #position: right
```
底部信息，显示正常！~！

效果详见：http://blog.ynxiu.com/

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by jcf94** [comment]
感觉像是 #1446 引进来的 bug

**Comment by aixiu** [comment]
@jcf94 我也更新了最新的代码了，我如果换成侧栏左显示就是对的，显示为右显示，就不行！~！~

**Comment by Acris** [comment]
fixed in #1502

**Comment by aixiu** [comment]
@jcf94 @iissnan 问题解决了，谢谢！~
