### ISSUE TITLE
友情链接样式错误

### ISSUE THREAD

**Issue by Cat7373** [iissnan/hexo-theme-next#1483]
### Expected behavior (预期行为)
![qq 20170305142204](https://cloud.githubusercontent.com/assets/9296576/23585088/22cb50c8-01af-11e7-8423-c16fb10bbf0c.png)

### Actual behavior (实际行为)
![qq 20170305142129](https://cloud.githubusercontent.com/assets/9296576/23585091/262ce2f4-01af-11e7-86d5-e81f499609e4.png)

### Steps to reproduce the behavior (重现步骤)
使用[这个提交](https://github.com/iissnan/hexo-theme-next/commit/4739f8c1a4982ab07e4e98ed2ef107e80ba72077)：
![qq 20170305142117](https://cloud.githubusercontent.com/assets/9296576/23585092/28a03a36-01af-11e7-88af-d8d46cf9ab50.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 3.2.2

NexT Scheme: Pisces

**Comment by abrahum** [comment]
我在最新的版本也遇到了这个问题，使用自定义css，list-style:  none; 解决了
