### ISSUE TITLE
不显示 description

### ISSUE THREAD

**Issue by Cat7373** [iissnan/hexo-theme-next#1484]
### Expected behavior (预期行为)
![qq 20170305142733](https://cloud.githubusercontent.com/assets/9296576/23585114/0f226b0a-01b0-11e7-9a31-85e92efef4b9.png)

### Actual behavior (实际行为)
![qq 20170305142814](https://cloud.githubusercontent.com/assets/9296576/23585115/1264cc5e-01b0-11e7-834c-f806c83fa3e2.png)

### Steps to reproduce the behavior (重现步骤)
使用[这个提交](https://github.com/iissnan/hexo-theme-next/commit/4739f8c1a4982ab07e4e98ed2ef107e80ba72077)：
![qq 20170305142829](https://cloud.githubusercontent.com/assets/9296576/23585116/1534e914-01b0-11e7-8bb3-fb49867b8de9.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 3.2.2

NexT Scheme: Pisces

**Comment by errorlife** [comment]
第一张的效果是hexo s 本地效果吗？第二张的效果是github pages还是vps上的tomcat等服务器呢？

**Comment by Cat7373** [comment]
恩 第一张是 hexo s
第二张是以前的版本在 github pages 上的

**Comment by errorlife** [comment]
或许你可以删除public->hexo g->hexo s->hexo d，重新上传试试看看。

如果搞不定的话，升级版本？

**Comment by Cat7373** [comment]
`Hexo`是最新稳定版，`Next`是`Github`上的最新提交。
删除`public`后问题依旧存在

**Comment by errorlife** [comment]
这是我之前的issues：https://github.com/iissnan/hexo-theme-next/issues/820

结果我在`VPS`上重装了一下`Tomcat`就好了。

Github上的，我可能不能提供很大的帮助，或许你对比github上的html源文件和Public，我就经常推送失败。

**Comment by Cat7373** [comment]
我是本地`hexo s`测试的。。。
因为有问题所以就没上传。。。

**Comment by iissnan** [comment]
主题配置文件里的 `seo` 值是 `true` 还是 `false`？ 目前模板里的判断：

```twig
{% if theme.seo %}
  <p class="site-description motion-element" itemprop="description">{{ theme.signature }}</p>
{% else %}
  <p class="site-description motion-element" itemprop="description">{{ theme.description }}</p>
{% endif %}
```

当 `seo` 设定为 `true` 的时候，`description` 设定的值将写入 `head`；同时每篇文章都可以写 description，以便更好的支持 SEO。此时，Sidebar 的签名将由 `signature` 代替。

**Comment by Cat7373** [comment]
好像`git`更新的时候`_config.yml`有冲突，于是先还原了之后更新，然后自己又改了一次配置。。。
顺手就把这个`seo`给开了的样子。。。
顺便建议配置文件不要让用户直接改`_config.yml`，支持在其他文件如`_config.inc.yml`里写自己的配置。。。
免得版本更新麻烦。。。

**Comment by Cat7373** [comment]
为何`seo`开启的时候要用`signature `来代替`description`呢？
统一一下不好么。。。

**Comment by iissnan** [comment]
从语义上理解，`signature` 更适合那个位置，`description` 更适合于 SEO。

你可以在 `站点目录/source/_data/` 目录下新建一个 `next.yml`，NexT 会读取这份文档的配置（继承了 `_config.yml`的配置）。只是这份文档并未有 processor 去处理，所以每次有修改，需要重启 hexo server，配置才会生效。

**Comment by Cat7373** [comment]
好的，谢谢 0.0

**Comment by Cat7373** [comment]
在[文档](http://theme-next.iissnan.com/)中我并没看到有关`seo`配置的说明，是不是应该加上呢？
比如放到常见问题里 0.0

**Comment by michaelHL** [comment]
遇到相同的问题，还好有萌妹子提交issue 😄
只好在站点配置文件 `_config.yml` 下增加新项
```yaml
signature: blablabla
```
