### ISSUE TITLE
删除页尾的行为是否违反了使用协议

### ISSUE THREAD

**Issue by errorlife** [iissnan/hexo-theme-next#1485]

**Comment by iissnan** [comment]
不会，NexT 使用的是 [MIT-LICENSE](https://github.com/iissnan/hexo-theme-next/blob/master/LICENSE)。

**Comment by errorlife** [comment]
这样子吗。好吧，不过我还是想让别人通过我的blog直接看到我在用的主题。: P

**Comment by Acris** [comment]
https://github.com/iissnan/hexo-theme-next/blob/master/_config.yml#L23
目前有选项可以控制是否显示，当然个人建议选择显示最好。

**Comment by errorlife** [comment]
@Acris 我也觉得：P
