### ISSUE TITLE
How to add named anchor to the headers in the "table of contents " in a post

### ISSUE THREAD

**Issue by jdhao** [iissnan/hexo-theme-next#1486]
### NexT Informations
NexT Version:
  -  Latest Release

NexT Scheme:
  -  Pisces

I would like to know how to add [named anchor](https://www.w3schools.com/tags/att_a_name.asp) to the headers in the "table of contents". So that when I click a specific header in the "table of contents", the page jump directly to that part (this has been achieved by NexT), and the location of that part is appended to the url (beginning with a \#).

To make what I mean clear, take [this webpage](http://matplotlib.org/api/axes_api.html) for an example.
In the "table of contents" part, if I click the "Clearing" section, the page jump to the part where “Clearing” section begins. The url changes correspondingly. See image below.
![named_anchor](https://cloud.githubusercontent.com/assets/16662357/23599258/d472ad00-027a-11e7-93b7-9123cb77e5a7.png)

I want to know how to achieve this effect in the NexT theme, since the "table of contents" is generated automatically. I have tried to search the Internet but can not find relevant resources.  I am not familiar with html, but I will try if anyone gives me some hints.

**Comment by iissnan** [comment]
The "table of contents" is generated by collecting headlines in the page contents, named anchor corresponds to the headline's id. This is the essential point of the effect. Actually, browser could jump to the corresponding headline without any animations when clicking on the named anchor and update the URL hash with the name. That's what you see in the example.

In NexT, it's implemented using JavaScript. Scripts written with JavaScript run after the page document object model (DOM) is ready, the content of "table of contents" is static then. When clicking on a named anchor, NexT will try to find the corresponding headline, calculate the headline's page offset and then scroll the page to the offset with animation if the headline was found.

**Comment by jdhao** [comment]
@iissnan , is there an easy setting which can change the url when click the headers in the "table of contents" ?

**Comment by iissnan** [comment]
No. The urls are what you define in the page document's headlines.

**Comment by jdhao** [comment]
Thanks anyway... 😃
