### ISSUE TITLE
英文单词间距太小，感觉像连起来，可以更改吗？

### ISSUE THREAD

**Issue by o1xhack** [iissnan/hexo-theme-next#1487]
### Expected behavior (预期行为)
英文单词之间的间距十分小，主要是在标题中显示，感觉像是连起来了一样，是否可以自定义？
尝试搜索 letter-spacing 并且在觉得会影响的地方更改，但是没有效果。

### Actual behavior (实际行为)
希望能够很清晰的分出来每一个单词,如图，十分难分辨出每一个单词。
![](https://ww3.sinaimg.cn/large/006tKfTcgy1fddv7hxw7fj30km02edg0.jpg)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔-  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔-  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

**Comment by iissnan** [comment]
你可以在 `source/css/_custom/custom.styl` 中添加 CSS 规则。比如：

```styl
.post-title { letter-spacing: .2em; }
```

**Comment by PandaonMars** [comment]
在 source/css/_custom/custom.styl 添加了 

.post { word-spacing: .1em; } 

已经看起来舒服很多 感谢回复！
