### ISSUE TITLE
是不是谷歌统计只能支持https的网站？

### ISSUE THREAD

**Issue by swordspoet** [iissnan/hexo-theme-next#1488]
### Actual behavior (实际行为)
我在站点配置文件中添加了谷歌统计跟踪ID，也更新了主题配置文件中的js代码，数据仍然显示为0，何解？是不是我的站点是http的缘故？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist✔
  -  Pisces

**Comment by swordspoet** [comment]
![default](https://cloud.githubusercontent.com/assets/14816130/23639042/299c76c6-0320-11e7-9716-723d2b93674a.png)
这里有一个错误，应该是主题配置文件才有效

**Comment by iissnan** [comment]
Google Analytics 目前用的是[ `https` 协议](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_scripts/third-party/analytics/google-analytics.swig#L6)，应该是正确的。你可以 F12 打开浏览器的网络面板，看下请求 Google Analytics 的请求是否正常。

**Comment by ivan-nginx** [comment]
@swordspoet issue is solved?
