### ISSUE TITLE
怎么更换首页正中那个logo啊，那个跟齿轮一样的东西。。。

### ISSUE THREAD

**Issue by suoba** [iissnan/hexo-theme-next#149]
1.怎么更换首页正中那个logo啊，能换成大一点的么
2.搜索栏呢？怎么添加的

**Comment by iissnan** [comment]
[自定义LOGO以及主题图标](https://github.com/iissnan/hexo-theme-next/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89LOGO%E4%BB%A5%E5%8F%8A%E4%B8%BB%E9%A2%98%E5%9B%BE%E6%A0%87)

**Comment by suoba** [comment]
大哥啊，我要能看的明白那种说明，我就不会过来问了。。。
不就是换一张png/ico图片么，有必要这么复杂么，又是网站，又是代码。。。
像这种每个人都想换的logo，直接替换对应的图片不是更好么，比如你左侧栏的头像。

**Comment by suoba** [comment]
另外，像齿轮一样的东西一般都是表示“设置”，不是“home”吧。我以为起到误导作用。

**Comment by eclipseflower** [comment]
没那么简单的，你看下作者的说明

**Comment by allanzhang** [comment]
配置里加个avatar就行了啊

**Comment by diffroot** [comment]
实话说那个logo更换我也没有怎么看明白

**Comment by victoryxs** [comment]
在font目录下根据icon服务里的图标码修改
