### ISSUE TITLE
 Cannot find module 'hexo-util' in /next/script/tags/exturl.js

### ISSUE THREAD

**Issue by hitao123** [iissnan/hexo-theme-next#1490]
### Expected behavior (预期行为)
var util = require('hexo-util');

### Actual behavior (实际行为)
but you don not provide the module in the repository , than i need to install it again

**Comment by iissnan** [comment]
Could you please provide the following information?

- Node.js and NPM version
- Hexo version
- Your site package dependencies

**Comment by hitao123** [comment]
@iissnan 
hexo-cli: 1.0.1
os: Windows_NT 10.0.14393 win32 x64
node: 6.9.2
npm: 3.10.9
![ex df _ h4r52z uid1vwx](https://cloud.githubusercontent.com/assets/16607714/23886218/2348d4ba-08b4-11e7-96be-d6a76bbae6c9.png)
![owy9mgjer bxe17nj0tnj](https://cloud.githubusercontent.com/assets/16607714/23886220/26006718-08b4-11e7-8cb7-4e851083f65c.png)
![wkuko loza5v 50 9r5nt](https://cloud.githubusercontent.com/assets/16607714/23886222/281c0778-08b4-11e7-9fa6-abfe8ca97dad.png)
the main package dependencies `hexo-util` ,when i meet this problem then i install the dependency

**Comment by iissnan** [comment]
According to the [NPM package installation algorithm](https://docs.npmjs.com/cli/install#algorithm), `hexo-util` (with other hexo plugin like `hexo-fs`) should be installed just in your "Blog/node_modules" directory, you don't have to specify `hexo-util` explicitly. 

Could you please delete the `hexo-util` dependency in the `package.json` and `Blog/node_modules` directory, then reinstall all dependencies?

**Comment by hitao123** [comment]
@iissnan ,thanks for your help and patience, i build another folder, use `hexo init`, i found it in the node_modules, maybe  create the folder for a long time.

**Comment by iissnan** [comment]
You are welcome.

For those who also encounter this issue, please check your NPM version. 

- `> 3`: Still not work. Please remove `node_modules` directory and reinstall using `npm install`.
- `< 3`: Please add `hexo-util` explicitly via `npm install --save-dev hexo-util` to you site package deps.
