### ISSUE TITLE
侧边栏社交链接无法显示

### ISSUE THREAD

**Issue by wangxiaotaot** [iissnan/hexo-theme-next#1492]
### Expected behavior (预期行为)

# Social links
social:
  GitHub: https://github.com/your-user-name
  Twitter: https://twitter.com/your-user-name
  Weibo: http://weibo.com/your-user-name
  douban: http://douban.com/people/your-user-name
  zhihu: http://www.zhihu.com/people/your-user-name
  # 等等

social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocalItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Linkedin: linkedin
### Actual behavior (实际行为)

社交链接空白
。。。。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iTofu** [comment]
请问你是如何解决的，我也遇到了这个问题。
https://note.leodev.me/
