### ISSUE TITLE
新建基于next的Scheme主题求助

### ISSUE THREAD

**Issue by Gabirel** [iissnan/hexo-theme-next#1493]
### Expected behavior (预期行为)
如何自定义并添加主题呢？
现在有`Muse`，`Mist`，`Pisces`，可是这些主题我都不喜欢，现在想要自定义一个新的主题

请问新建的主题放在什么位置比较好呢？

**Comment by iissnan** [comment]
Scheme 最主要的部分在于 CSS 的再定义。NexT 里 CSS 由 5 个层次构成：

Layer |  Description | Composition |
-------| -------------|----------------|
Variables | Variables used throughout the style sheets. Scheme variables will override variables which defined in the base variables defenition |  base variables, scheme variables, custom variables |
Mixins | Mixins used throughout sytlesheets | base mixins, scheme mixins, custom mixins|
Common | Base styles for all schemes | scaffolding, outline, components |
Scheme | Scheme specific styles | outline, components |
Custom | Custom styles by end users | * |

当新建一个 Scheme 时（假设 Scheme 名为 Ocean），必须定义的文件包括有：
- Scheme 的 Variables 定义，存放于 `source/css/_variables/Ocean.styl`
- Scheme 的 Mixins 定义，存放于 `source/css/_mixins/Ocean.styl`
- Scheme 的特定样式定义，存放在 `source/css/_schemes/Ocean/`，这里通常定义的 Scheme 的结构以及不能通过 Variables 更改的样式
- Scheme 的特定脚本，存放于 `source/js/schemes/ocean.js`

**Comment by Gabirel** [comment]
这些只是针对于css而言，对于改动比较大的，涉及到layout之类的怎么办？

**Comment by iissnan** [comment]
All templates reside in the `layout` folder written with swig. It is not recommended to change the layout unless you have to.

**Comment by ivan-nginx** [comment]
@Gabirel issue is solved?

**Comment by Gabirel** [comment]
@ivan-nginx

I'm sorry. No, I just get part of what I want to know.

I have something else to ask when making a new scheme.
But I've been busy since that. So I'm sorry that I can't close this issue for now.

**Comment by ivan-nginx** [comment]
@Gabirel ok, let me know when u can to close and try to remember any answers.

**Comment by Gabirel** [comment]
Why some of the function name doesn't mathch its actual doing
https://github.com/iissnan/hexo-theme-next/blob/master/source/js/src/motion.js#L230-L239
```js
      function getMistLineSettings (element, translateX) {
        return {
          e: $(element),
          p: {translateX: translateX},
          o: {
            duration: 500,
            sequenceQueue: false
          }
        };
      }
```

**Comment by ivan-nginx** [comment]
@Gabirel need to do this question to @iissnan i think.
But this is not actially bug. Get? Set? No matter if it worked, no?

**Comment by Gabirel** [comment]
@ivan-nginx Yes, it worked very well. But not friendly to developers or users who want to customize their thems.

**Comment by Gabirel** [comment]
All of my work finished. Close it right now
