### ISSUE TITLE
请问怎样添加封面和关于页面

### ISSUE THREAD

**Issue by mengxianliang** [iissnan/hexo-theme-next#1496]
我看您的封面地址是http://iissnan.com
blog地址是：http://notes.iissnan.com

能简述一下实现过程么，我需要建一个新的GithubPage去存这个封面么 还是在netx里面就可以添加了？
然后这个域名怎样添加解析才能绑定封面和blog？
然后这个关于页面怎么添加呢？

**Comment by iissnan** [comment]
Yes. I use two GitHub Pages to serve them respectively:

- Personal home page (http://iissnan.com) is hosted in the User Page Site, the `username.github.io` repository's `master` branch. There is a CNAME file that specify the domain to `iissnan.com`.
- Blog (http://notes.iissnan.com) is hosted in a Project Page Site, `notes` repository's (in my case)  `gh-pages` branch. There is a CNAME file that specify the domain to `notes.iissnan.com`.
- Setup custom domain for your GitHub Pages. Please see [Using a custom domain with GitHub Pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/)

My personal home page is just a plain HTML file, you can find it at https://github.com/iissnan/iissnan.github.com

**Comment by mengxianliang** [comment]
请问您的博客(http://notes.iissnan.com)是托管在另一个GitHub账号里么？

**Comment by iissnan** [comment]
The same account, different repository (https://github.com/iissnan/notes).  Only the generated HTML files.

**Comment by mengxianliang** [comment]
好的，谢谢！
