### ISSUE TITLE
调试状态内容区域出现空白

### ISSUE THREAD

**Issue by bolee** [iissnan/hexo-theme-next#1498]
### Expected behavior (预期行为)
调试状态正常显示

### Actual behavior (实际行为)
只显示顶部一块颜色区域，右下角显示一个按钮

### Steps to reproduce the behavior (重现步骤)
1.hexo server
2.打开浏览器
备注：通过hexo generate发布之后运行是没有问题的,但百度快照里面也是这个bug

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  ✔ All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

![next_bug](https://cloud.githubusercontent.com/assets/2450909/23828653/a69c9b46-0713-11e7-8d8c-7f118d097a08.png)

**Comment by DemoJameson** [comment]
`//jquery/index.js?v=2.1.3`
遇到同样问题，看起来像是 internal 变量值为空

**Comment by ivan-nginx** [comment]
@bolee try any other Theme. If issue still exists, problem not in Next theme.

Issue resolved?
