### ISSUE TITLE
侧边栏查看站点概览不正常

### ISSUE THREAD

**Issue by jiangxy** [iissnan/hexo-theme-next#15]
点开侧边栏，“文章目录”是正常的
但点击“站点概览”后内容就消失了
再点击“文章目录”也不显示了

**Comment by iissnan** [comment]
你能提供一些你所使用的环境信息吗？ 比如浏览器（及版本）、Hexo 版本。

**Comment by jiangxy** [comment]
firefox 26.0
hexo 2.8.3
访问http://notes.iissnan.com/ 也有这个问题
但用chrome 40.0就正常了

**Comment by iissnan** [comment]
多谢。我去下载个Firefox 26

**Comment by jiangxy** [comment]
IE 10也有问题

**Comment by iissnan** [comment]
已经修复了。由原先使用 promise 改成 callback 的形式。

感谢反馈：）

**Comment by jiangxy** [comment]
赞！已验证
