### ISSUE TITLE
md文件里添加了<!--more-->后，正文里如果有列表，则列表会乱序

### ISSUE THREAD

**Issue by zhangjh** [iissnan/hexo-theme-next#1504]
如题，如果md文件里使用了列表，那么会被搞乱顺序，more前会有1,2,3,4,more之后又会重新计数1,2,3,4，预期应该接着计数。

![image](https://cloud.githubusercontent.com/assets/3371714/23884915/cadd717c-08aa-11e7-9abb-7ec9c98b86ac.png)

**Comment by iissnan** [comment]
Try indenting the `<!--more-->` placeholder with 4 spaces to make it to be a child of some list item.

**Comment by zhangjh** [comment]
@iissnan Thanks, it's solved.
