### ISSUE TITLE
网易云跟帖无法使用，key也使用了，排查了gentle.swig也是与云跟帖上代码一样，next是不是还不支持？

### ISSUE THREAD

**Issue by lyyiqo** [iissnan/hexo-theme-next#1506]
### Expected behavior (预期行为)
评论系统使用的是网易云跟帖

### Actual behavior (实际行为)
没有任何显示。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by lyyiqo** [comment]
谢谢各位大神帮忙解答

**Comment by iissnan** [comment]
There should be some requests pointed to Gentie 163. You can check the status of them and provide them in this issue.

**Comment by WujieRen** [comment]
楼主解决问题了么

**Comment by iissnan** [comment]
Please check the response of the request to `https://api.gentie.163.com/thread/check`.

I have just tested this comment service, it works well. Please note, this service requires that the domain you set in GenTie management console should be the same as your site's domain. 

If you need to validate this in your local machine, you need to do:

1. Map your domain request to `127.0.0.1` in your machine's hosts file.

        notes.example.com 127.0.0.1

2. Run Hexo to listen on port 80

        hexo server --port 80 --debug

Once you confirm that the service works, please remove the mapping info in your hosts.

**Comment by lyyiqo** [comment]
Vi   正解！！！！谢谢，问题解决，只是本地调试无法看到评论界面，上传github后，可以使用，还是喜欢网易云跟帖的风格。  网址：  www.lyyiqo.win

**Comment by gglinux** [comment]
注意next的版本！！！
