### ISSUE TITLE
hexo d 部署失败，提示如下，寻求解决办法

### ISSUE THREAD

**Issue by xdoupd** [iissnan/hexo-theme-next#1507]
![image](https://cloud.githubusercontent.com/assets/5766864/23888074/e42a2da8-08c0-11e7-85bb-eb17097a77c3.png)

**Comment by iissnan** [comment]
How did you deploy your site to GitHub Pages?

**Comment by xdoupd** [comment]
@iissnan 删除本地隐藏.depoly_git文件夹后，再hexo d 解决了这个问题，感谢博主
