### ISSUE TITLE
点开主页时，侧栏作者信息能否像打开具体一页面一样，固定右上或左上？？

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1509]
### Expected behavior (预期行为)
点开主页时，侧栏作者信息能否像打开具体页面一样，随滚动条向下移动时，固定位置？
也就是想，主页的侧栏作者信息，像内容页一样，随滚动条动而动！！
主要是使用了最新的向上滚动返回顶部百分比的按钮，内容页可以使用，但是主页使用时，侧栏不固定，也就失去意义了~！建议也做个开关！~

### Actual behavior (实际行为)
点开主页时，侧栏作者信息能否像打开具体页面一样，随滚动条向下移动时，看不到了！~

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@aixiu in English, if not solved for now.

**Comment by AlynxZhou** [comment]
@ivan-nginx I have the same question as him and am trying to translate it into English. We use the new percent style back-to-top button in pisces. But there is a problem that it is under the sidebar, when in posts, the sidebar's content part always stick on the top of the screen, even you move to the end, which is very right, but in other pages the sidebar's lower half never stick on top and the back-to-top button follows it to go outside of the screen, and become useless, we think it should be fixed. The lower half of sidebar should stick on the screen as it was designed. Thanks.

**Comment by ivan-nginx** [comment]
@AlynxZhou can u give live example for this? I can't reproducte this.

**Comment by aixiu** [comment]
![dome](https://user-images.githubusercontent.com/8064012/28243818-be3c1f74-6a0a-11e7-9da5-6895348463d8.jpg)
@ivan-nginx As shown in the figure, when the home page opens the% progress bar (the red box area), the scroll bar scrolls down, and the sidebar should lock the blue box area.

**Comment by AlynxZhou** [comment]
I believe this bug has been fixed, at least my blog behave correctly now.

**Comment by ivan-nginx** [comment]
Ah, yes. Affix sidebar now work on all pages from 5.1.2 version.

@aixiu if solved, close it please.
