### ISSUE TITLE
分享和搜索，能否放在侧边栏？

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#151]
分享工能，可否加到标签后面，也可以是侧边栏。

搜索现在摆放位置，太难看了。

**Comment by iissnan** [comment]
放在侧栏感觉太不明显了，使用起来也麻烦。

**Comment by tmacychen** [comment]
搜索的位置希望可以调整一下，确实不美观

**Comment by xirong** [comment]
@iissnan  搜索栏这块启用了后在手机端是有问题的，没启用，手机端显示的效果很棒，启用后就不好了。@eurusd  分享功能，我加入了百度分享，是在侧边的，你看我的文章是你想要的样式了 http://www.ixirong.com

**Comment by eurusd** [comment]
分享功能 能否加在评论的上方

**Comment by iissnan** [comment]
搜索样式已更新，默认主题 和 Mist 主题都有对应的修改（包括移动设备上的显示）
