### ISSUE TITLE
从阅读全文进入新界面, 起始位置不在页面最顶部

### ISSUE THREAD

**Issue by SYFH** [iissnan/hexo-theme-next#1511]
### Expected behavior (预期行为)
点击阅读全文, 新界面的起始位置在最顶部

### Actual behavior (实际行为)
新界面的起始位置在左侧栏的文章目录视图的顶部, 但点击标题进入没有问题

### Steps to reproduce the behavior (重现步骤)
刚开始以为是乱改的 CSS 有问题, 但之后全部重新安装依然存在

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔

**Comment by iissnan** [comment]
Set `scroll_to_more` filed in the `_config.yml` to `false` to disable the default behavior of the "Read More" button.

**Comment by SYFH** [comment]
完美解决, 谢谢!
