### ISSUE TITLE
手机打开网站似乎不可以显示友情链接和社交连接   Pisces  可以设置让他显示吗

### ISSUE THREAD

**Issue by labulaka521** [iissnan/hexo-theme-next#1512]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
感觉没有地方可以显示了

**Comment by iissnan** [comment]
No. Mobile edition is the simplified version of Desktop one. I didn't plan to update it recently.

**Comment by labulaka521** [comment]
oh ...thank you

**Comment by ivan-nginx** [comment]
@labulaka521 issue resolved?

**Comment by Jan9th** [comment]
期待增加这个功能
