### ISSUE TITLE
本地可以正常显示页面，但是github page404，并且github发邮件说不支持这个主题

### ISSUE THREAD

**Issue by WeiDongYang** [iissnan/hexo-theme-next#1513]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
Could you please provide more information for this case？ For example, the insensitive email content of GitHub

**Comment by WeiDongYang** [comment]
OK,thanks
The page build completed successfully, but returned the following warning:

You are attempting to use a Jekyll theme, "NexT", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this emai

**Comment by iissnan** [comment]
I am not sure how the deployment of Hexo would cause GitHub considering it as a Jekyll site. Did you follow the [Deployment in Hexo's documentation](https://hexo.io/docs/deployment.html)?

**Comment by WeiDongYang** [comment]
Thanks very much, I will try to install  Hexo again .

**Comment by Still-Maos** [comment]
i have this problem too, did you fixed it by reinstalling hexo ?

**Comment by WeiDongYang** [comment]
yes , reinstalling hexo and hexo-theme-next .

**Comment by Still-Maos** [comment]
Ok, thanks.
