### ISSUE TITLE
categories页面更新不正常

### ISSUE THREAD

**Issue by ilovin** [iissnan/hexo-theme-next#1517]
### Expected behavior (预期行为)
markdown里面新建一个文件，或者更改了一个文件的categories，那么categories页面也应该相应更改
### Actual behavior (实际行为)
 ![img](https://ooo.0o0.ooo/2017/03/17/58cb7a874ccbf.jpg)
可以看到，有三个分类，实际却只有两个categories。另外更改markdown的categories时，有个文件是可以有效更新的，有的文件更改后，categories还是没有更新。另外tags可以正常更新
### Steps to reproduce the behavior (重现步骤)
不太清楚你们是否可以复现
### NexT Informations
NexT Version: 5.1.0

  ✔ -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  ✔  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
chrome,win10 x64

**Comment by iissnan** [comment]
run `hexo clean` and try again.

**Comment by ilovin** [comment]
I have already tried that
`hexo clean && hexo s`
or `hexo clean  && hexo g`
the results are the same

**Comment by aixiu** [comment]
`hexo clean`
`hexo g`
`hexo s`

**Comment by ilovin** [comment]
```hexo clean
hexo g
hexo s
```
之后，变成2个分类了，且每个分类只有一篇文章
然实际上，我有3个分类，4篇文章

**Comment by iissnan** [comment]
I only saw two categories in two posts of your blog, they are "hexo" and "test".  Another two posts do not have a category. Please confirm the front-matter categories setting of those posts.

**Comment by ilovin** [comment]
my fault! In the other two posts,
I misspell categories to categorises
