### ISSUE TITLE
怎么可以支持两种评论了

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1518]
怎么可以支持两种评论了？其他评论不喜欢，多说不稳定，Disqus又得翻墙才可以

**Comment by iissnan** [comment]
Not sure what you are talking about.

**Comment by ehlxr** [comment]
@iissnan 我的意思是可以支持显示两种评论系统，默认显示Disqus，影藏第二种（比如多说），点击可以显示第二种，像这个，点击“想留言却没看到评论框？点这里。”就会显示多说评论框
![image](https://cloud.githubusercontent.com/assets/11313370/24087812/931b9efe-0d5e-11e7-9432-70445bccac0f.png)

**Comment by iissnan** [comment]
I see. The major problem for this is that it might be hard to detect if the primary comment system is available or not.

**Comment by ehlxr** [comment]
@iissnan I think it does not need to detect the primary comment system is available or not, Just show if it is available, not show if it is not available

**Comment by ehlxr** [comment]
自己琢磨了一下，实现了
https://ehlxr.me/about/

**Comment by ivan-nginx** [comment]
#1549
