### ISSUE TITLE
修改内容区的宽度，本地服务器预览没问题，但部署到github上就不生效

### ISSUE THREAD

**Issue by tfx919** [iissnan/hexo-theme-next#1519]
修改内容区的宽度，本地服务器预览没问题，但部署到github上就不生效，清除数据什么都没用，求解

**Comment by iissnan** [comment]
Do a "force" refresh or change the `version` in theme's `_config.yml` to update the anti-cache string.

**Comment by ivan-nginx** [comment]
@tfx919 may close issue, it is solved?
