### ISSUE TITLE
Pisces风格怎么设置友情链接居中？

### ISSUE THREAD

**Issue by VeiZhang** [iissnan/hexo-theme-next#1520]
### Expected behavior (预期行为)
RT

### Actual behavior (实际行为)
左开头，"links_title"不居中

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  Pisces

**Comment by ivan-nginx** [comment]
@VeiZhang don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by VeiZhang** [comment]
@ivan-nginx sorry.
