### ISSUE TITLE
不能实现热更新吗

### ISSUE THREAD

**Issue by JackZong** [iissnan/hexo-theme-next#1521]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by mcknote** [comment]
考慮到 Github 上存的是靜態頁面，最接近的解決方案應該是 Travis-CI 吧。不然樓主想要怎樣的熱更新？

**Comment by ivan-nginx** [comment]
@JackZong don't understand u, write in English if not solved. If solved, close it please. Thank's!
