### ISSUE TITLE
leancloud_visitors首页阅读次数没有显示，只有文字显示【阅读数量】

### ISSUE THREAD

**Issue by ifgyong** [iissnan/hexo-theme-next#1523]
每个文章详情页面有阅读次数，但是在首页文章列表确没有这个数字，但是有文字【阅读数量】，请问，怎么在首页 阅读数量后边加上数量啊

**Comment by cduyzh** [comment]
本地测试是看不到的哦，如果还有配置上的问题可以来我博客看看www.cduyzh.com

**Comment by lighkLife** [comment]
我也遇到了同样的问题，有解决吗？

**Comment by ifgyong** [comment]
@lighkLife 本地的没有数字，推到线上就好了，数据库的 名字是 Counter.

**Comment by HiZhaoxiaoyang** [comment]
theme.leancloud_visitors.enable是false，所以阅读数文字和数字都没显示，不知道是否是 @ifgyong 说的原因需要推到线上？

**Comment by HiZhaoxiaoyang** [comment]
目前用了generate成静态目录也不行

**Comment by ifgyong** [comment]
@HiZhaoxiaoyang  推到线上就显示了。数据库名字要对【Counter】，其他的不变。
