### ISSUE TITLE
多说要停服务器了，官方消息

### ISSUE THREAD

**Issue by cwyaml** [iissnan/hexo-theme-next#1525]
官方给的公告  http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241
随便推广一下博客 http://www.cwyaml.top

**Comment by aixiu** [comment]
能用到6月1号就停了

**Comment by Maples7** [comment]
提供一个新思路：https://commentit.io/

据说是直接用 git commit 提交到 GitHub 代码库的，不需要第三方数据存储。

可以考虑支持一下。

**Comment by fuchao2012** [comment]
建议用畅言替代多说，另外，@Maples7 提供的思路很赞啊！

**Comment by cheeseKun** [comment]
= =，可怕
还好不用多说了
> 顺便推：http://cheesekun.top

**Comment by AlynxZhou** [comment]
我以前问过commentit，那个跟jekyll和github的联系很紧密，要和hexo联系的话估计很麻烦。

**Comment by Master-Wang** [comment]
肿么办求解决方案。commentit 能和 hexo 结合吗

**Comment by yongming9011** [comment]
@fuchao2012 刚去注册了畅言，发现有点坑啊，必须要网站备案才能用，麻烦问下你是怎么解决这个问题的？

**Comment by cwyaml** [comment]
@yongming9011  目前还没计划

**Comment by Maples7** [comment]
也有人已经利用 GitHub Issues 实现了评论系统：https://github.com/imsun/gitment

**Comment by iissnan** [comment]
Gitment 看起来不错

**Comment by ehlxr** [comment]
@iissnan 有没有打算把 Gitment 集成过来啊😝

**Comment by ivan-nginx** [comment]
@cwyaml don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by JesseHuang-CHN** [comment]
使用来比力评论系统可以解决吧，我就用了这个，官网：https://livere.com/introduce
畅言要备案才行，我在阿里云买的域名要买空间才能给域名备案。。
大家有空可以来看看，，http://hjx98.com

**Comment by ivan-nginx** [comment]
Already removed Duoshuo in [NexT v6.0.1](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.1).
