### ISSUE TITLE
How to set inverse color style of header and footer?

### ISSUE THREAD

**Issue by elonliu** [iissnan/hexo-theme-next#1529]
I'd like to use a dark header and footer. Just like the way in GitHub website, or Boostrap "navbar-inverse" style. Is there an easy way to do this?

### Expected behavior (预期行为)
![snipaste20170322_231717_](https://cloud.githubusercontent.com/assets/5549178/24205833/7ae952c2-0f57-11e7-9953-94f80dcd0e65.png)

### Actual behavior (实际行为)
![snipaste20170322_231717](https://cloud.githubusercontent.com/assets/5549178/24205842/7eba7fac-0f57-11e7-96ec-c430f0f99730.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

**Comment by iissnan** [comment]
Need to customize the styles by yourself.

**Comment by elonliu** [comment]
Thanks for reply. Already solved.
