### ISSUE TITLE
网易云跟帖评论和热门文章一同加载时的错误显示

### ISSUE THREAD

**Issue by cduyzh** [iissnan/hexo-theme-next#1530]
### Expected behavior (预期行为)
热门新闻和评论一起加载出来

### Actual behavior (实际行为)

只加载了评论
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔

NexT Scheme:

  -  Mist ✔

**Comment by ivan-nginx** [comment]
@cduyzh don't understand u, write in English if not solved. If solved, close it please. Thank's!
