### ISSUE TITLE
如何关闭某个页面上的fancybox功能？

### ISSUE THREAD

**Issue by VeiZhang** [iissnan/hexo-theme-next#1533]
### Expected behavior (预期行为)
新建一个收藏的菜单，里面展示书籍，在点击书籍图片的时候，跳转到指定的url链接：书籍介绍界面。

### Actual behavior (实际行为)
点击书籍图片时，是加载fancybox显示书籍的大图。通过网页元素查找，在点击图片时，加载fancybox，去掉后，可以正常跳转链接，但是我只是想这个页面去掉fancybox效果。

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

**Comment by iissnan** [comment]
Not support at present.

**Comment by VeiZhang** [comment]
ok，Thx
