### ISSUE TITLE
Pisces下sidebar.position为right时，footer-inner在移动端不居中。

### ISSUE THREAD

**Issue by yogagee** [iissnan/hexo-theme-next#1536]
### Expected behavior (预期行为)
Pisces下sidebar.position为right时，footer-inner在移动端应居中。

### Actual behavior (实际行为)
Pisces下sidebar.position为right时，footer-inner在移动端不居中。

### Steps to reproduce the behavior (重现步骤)
scheme: Pisces
sidebar position：left时

window.width小于990时footer-inner显示错误，
原因应该是在pc端的margin-right或padding-right值在移动端没有消除导致的。

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.1.0

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔#sidebar.position:right

**Comment by aixiu** [comment]
的确有这个问题，我特意用手机看了下，sidebar.position为right时，显示在手机屏左下，并且格式乱了。我的主题也是右显示的。~！

**Comment by lavenus** [comment]
我的也是，这里也问题，但找不到生成ＣＳＳ文件前的样式，自定义样式加入会出现样式冲突之类
@media (max-width: 767px) {
  .footer-inner {
    width: auto;
    padding-left: 0;
  }
}

**Comment by Acris** [comment]
@aixiu 
@lavenus 
@yogagee 
麻烦拉取最新代码再试试是否还有问题。

**Comment by aixiu** [comment]
@Acris 更新最新代码后，解决问题，谢谢！~

**Comment by yogagee** [comment]
@Acris 问题已解决，谢谢。
