### ISSUE TITLE
建议支持友言或畅言

### ISSUE THREAD

**Issue by xuanmiaog** [iissnan/hexo-theme-next#1537]
多说关闭了，能支持友言吗？

**Comment by xuanmiaog** [comment]
不过说实话可以写个scripts插件在文末尾推荐评论脚本了

**Comment by aixiu** [comment]
畅言已经支持了。在主题设置·
```
+changyan:
+  enable: false
+  appid:
+  appkey:
```

**Comment by xuanmiaog** [comment]
支持网易跟贴吗？畅言好像要备案

**Comment by xuanmiaog** [comment]
哦哦支持了

**Comment by lavenus** [comment]
畅请要实名制上传身份证还要人拿着身份证拍照

**Comment by tyoungcn** [comment]
@lavenus 没有看到畅言哪里有要求实名制上传身份证啊，只是要求域名有备案。
关于备案，如果有朋友在阿里云买ECS的话，可以向朋友借一个备案服务号（貌似一个帐号可以申请10个），就可以在阿里云申请备案了，差不多半个月可以搞定。

**Comment by lican09** [comment]
我的博客配置了畅言，但没法弹出登陆页面，地址如下:
http://blog.lican.site/2017/11/05/mongodb_idex/#more
