### ISSUE TITLE
next主题怎么更新呢？

### ISSUE THREAD

**Issue by cwyaml** [iissnan/hexo-theme-next#1539]
比如说，我是用的是版本1.0   更改了自己的各种配置
然后出了2.0版本。怎样在保留自己的配置的前提下更新主题呢？？

**Comment by Acris** [comment]
You can use Hexo data files, See #328 for more information.

**Comment by Wangjunyu** [comment]
参考我的博客：[参考信息化管理的博客版本升级策略](http://blog.junyu.pro/posts/0014-theme-version-upgrade-guide.html)
我也是准备从过去的版本做升级，但是没有采用 #328 的方式，因为自己做了大量的改动，此次升级的基本思路如下：
- 原版本博客进行备份
- 搭建测试环境，部署新的模版，用其他的域名先跑起来
- 新旧版本对比，明确功能差异
- 基于新版本进行配置修改，并做好记录

---
为什么要这么麻烦：
- 原有的博客配置文件做了很多个性化配置，需要梳理
- 希望充分发挥新版本的新功能优势，所以尽量以新版本为主

**Comment by ivan-nginx** [comment]
@cwyaml solved?

**Comment by xiaobai050** [comment]
@cwyaml  @Wangjunyu 
我用临时构建git主题仓库的方式，感觉还好，写了篇分享。
http://zhangnai.xin/2018/11/11/hexo-theme-upgrade/

**Comment by zq-97** [comment]
用 `git branch` 和 `git merge` 命令可以自动解决这些问题，除了需要手动处理一下双方修改引起的冲突，参考[我的博客](https://i-m.dev/posts/20190331-103618.html)。
I solved this problem by `git branch` and `git merge` such that config&update&conflict could be handled easily, you can refer [my blog](https://i-m.dev/posts/20190331-103618.html) for detail.
