### ISSUE TITLE
单击菜单栏的search没反应

### ISSUE THREAD

**Issue by yanshengjia** [iissnan/hexo-theme-next#1542]
### Expected behavior (预期行为)
启用了Local Search功能。
单击菜单栏的search应出现搜索弹窗

### Actual behavior (实际行为)
单击菜单栏的search没反应

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
 ✔  Old version - 5.0.1

NexT Scheme:
  -  All schemes
  -  Muse
✔ Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
看了下 search.xml，出现了如下错误：
![2017-03-26 10 57 11](https://cloud.githubusercontent.com/assets/8682800/24328098/10685916-1213-11e7-8492-6a8ff3f97128.png)
XML解析失败了，错误是“Input is not proper UTF-8, indicate encoding !”
我用编辑器打开了search.xml，然而错误提示中的位置已经超出了文件的范围。。。
可能我在文章里输入了一些神秘字符？

不知道有没有和我遇到同样问题的人，希望能提供一些帮助，十分感谢！

**Comment by MekaYangyi** [comment]
插件装了吗

**Comment by yanshengjia** [comment]
装了，按照官方文档一步步做的

**Comment by Neveryu** [comment]
编码的问题

**Comment by lin493369** [comment]
@yanshengjia 你好，解决了吗？能告知解决方法吗？

**Comment by yanshengjia** [comment]
没有。。我感觉要一篇篇文章看来检查是哪里编码出了问题，但是现在文章有点多，就没搞。

**Comment by Neveryu** [comment]
所有的文章都应该保存为utf-8无BOM
你这里面有某个文件是utf-8 with BOM 的 原因

**Comment by yanshengjia** [comment]
并不是很明白 UTFB 编码里有 BOM 是如何出现的。

那应该如何检测以及删除 BOM 呢？

**Comment by lin493369** [comment]
检查了所有文章，并没有 utf-8 with BOM 的，依然是那个问题。

**Comment by lin493369** [comment]
已解决，并不是 BOM 的问题，我的问题是文章中有特殊字符，mac 上下载一个 TextWrangler ，可以检查文件中的特殊字符，显示红色的特殊字符删掉就好了。

**Comment by ivan-nginx** [comment]
@yanshengjia don't understand u, write in English if not solved. If solved, close it please. Thank's!
