### ISSUE TITLE
请大家推荐一个社会化评论系统

### ISSUE THREAD

**Issue by Neveryu** [iissnan/hexo-theme-next#1544]
多说马上要停了，在考虑换什么
[https://neveryu.github.io/guestbook](https://neveryu.github.io/guestbook)

我还是希望先听听大家的意见，你们自己用过的，用的感觉怎么样？

最好留个链接看看

👍 💯 🥇 😸 🌹

**Comment by wuxubj** [comment]
一天到晚的骗访问量，有意思？

**Comment by cduyzh** [comment]
## 针对题主
你提问就不要把自己的链接放出来，骗流量干嘛啊，而且你的域名也没解析过，百度也不会收录你的。
回归整体，不去评论你，我主要给其他人有这个问题的说说我的看法。
## 我的看法
### next支持的情况
next目前支持国内的有来**必力、多说、网易云跟帖**；还有一个**畅言**，其中畅言没有集成在配置文件里，但是可以自己来配置也不难，类比其他评论软件。
**多说**倒闭了没法聊。
**来必力**是韩国的，爱国的青年不要用，我没用过，因为我看到是棒子的，但是从心里话来讲，我看了下功能介绍还不错的说，但是有收费和免费的区别，想来不错的东西都是收费的。
**网易云跟帖**就是我现在用的，出于对网易云音乐的情怀，但是这个评论系统有不少的问题，后台管理不完善，技术人员感觉也很少，没人来维护，让人觉得心寒，目前还是在试用期间，如果半年内没太大改变，可能会另寻其他的了。
**畅言**这个比较烦人的是，必须要你的网站备案，我们的博客用next主题，很多都是把网站放在github pages上的，所以没法备案，我看了有些人在群里说，用了别人的备案号，成功备案通过了检查，我不敢去冒这个险，胆子大的人就去试试吧。
## End
最后贴出自己的博客链接，感兴趣的网友可以进来看看我对这几个评论插件的更详细的介绍，以及如何从多说迁移到网易云跟帖的。
博客地址：http://www.cduyzh.com

**Comment by Neveryu** [comment]
只是希望能够和大家相互交流学习而已

**Comment by cduyzh** [comment]
@Neveryu 可能我说的重了，不好意思，有任何问题欢迎来我博客提问。

**Comment by ehlxr** [comment]
最近发现了一个不错的评论系统 gitment 
大家可以参考一下 http://ehlxr.me

**Comment by effie999** [comment]
今天在别地看到[hashover](https://github.com/jacobwb/hashover-next)，好像也很不错的样子！

**Comment by zhaiqianfeng** [comment]
畅言已经集成到配置文件了

**Comment by vincentlauvlwj** [comment]
多说倒闭了，自己写代码撸了一个评论系统。。。

**Comment by ehlxr** [comment]
@vincentlauvlwj 你的评论数据托管在哪儿

**Comment by loveNight** [comment]
@cduyzh 百度已经开始收录Github博客了。比如你吐槽的楼主的博客，其收录结果如下：
https://www.baidu.com/s?ie=utf8&wd=site%3Aneveryu.github.io&tn=87048150_dg

**Comment by cduyzh** [comment]
@loveNight 我看到了，百度收录一般会在一个月后。

**Comment by ivan-nginx** [comment]
@Neveryu what's the point? Close it, please. If solved.

**Comment by booxood** [comment]
可以试试 Gitalk：一个基于 Github Issue 和 Preact 开发的评论插件

[在线示例](https://gitalk.github.io/)

**Comment by newdee** [comment]
@booxood 你加入gittalk评论没？我之前用的gitmeng
