### ISSUE TITLE
请问如何使用NexT主题获得如下链接的效果

### ISSUE THREAD

**Issue by dslztx** [iissnan/hexo-theme-next#1548]
NexT主题已经很简洁了，但是我想要获得如下链接所示的效果，请问该如何做？或者作者有没有可能在Muse，Mist，Pisces之外，新建一个独立的模式满足这个需求呢？
万分感谢大神！

http://mingxinglai.com/cn/

**Comment by Acris** [comment]
如果喜欢这种极简风格的话，可以试试这个主题：https://github.com/icylogic/carbon

**Comment by dslztx** [comment]
这个主题是不是还没有开发完成，感觉有点问题呢 @Acris

**Comment by Acris** [comment]
不太清楚，你可以咨询下作者。

**Comment by xaweather** [comment]
这个我之前用过，用jekyll做的博客

**Comment by ivan-nginx** [comment]
@dslztx don't understand u, write in English if not solved. If solved, close it please. Thank's!
