### ISSUE TITLE
disqus能不能设置为默认不加载，需要点击才加载呢？

### ISSUE THREAD

**Issue by skyue** [iissnan/hexo-theme-next#1549]
多说关闭，已经改用disqus了，但不翻墙的情况下，disqus影响整体页面的加载（浏览器一直转圈），所以是否可以将disqus设置为默认不加载，提供一个button，点击后才加载呢？

**Comment by tyoungcn** [comment]
这个建议挺好的，有在其他网站看到是这样实现的，期待Next也能实现 :smile:

**Comment by ehlxr** [comment]
也希望能支持显示多个评论系统，#1518

**Comment by neoFelhz** [comment]
https://github.com/viosey/hexo-theme-material/blob/master/layout/_widget/disqus_click.ejs

这是 Material 主题（hexo-theme-material）的实现方法。
@skyue 你可以根据这个思路自己 patch 以下 NexT 主题。其中 `ripple.js` 非必须。

**Comment by hitao123** [comment]
不知道 next 能不能实现静态图片延迟加载@iissnan

**Comment by effie999** [comment]
我觉得国外的评论系统都可以套上这个功能……

**Comment by ehlxr** [comment]
自己搞了一下，实现了效果
https://ehlxr.me/about/

**Comment by 1022-zhang** [comment]
减少主题文件修改，配合主题配置 https://1022-zhang.github.io/combined-comments.html

**Comment by ivan-nginx** [comment]
Already added lazyload option for disqus in [6.0.2 version](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.2).

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
