### ISSUE TITLE
换上了网易云跟帖！！

### ISSUE THREAD

**Issue by cwyaml** [iissnan/hexo-theme-next#1550]
今天把博客更新到了Next最新版本。放弃多说，换上了网易云跟帖。
效果到这里看：  http://www.cwyaml.top 
说一下体验：
优点：整体上看比多说更简洁一些，给人很爽的感觉。
缺点：没有最近访客功能，不能自定义样式（虽然默认的也很不错了）

**Comment by aixiu** [comment]
没发现你开启啊，是不是又给关了！

**Comment by Yaccc** [comment]
有教程吗。求

**Comment by NoahDragon** [comment]
404了

**Comment by ilovin** [comment]
试图绑定github.io的博客的时候说 站点或URL已存在，不是很懂

**Comment by chf2012** [comment]
相同的问题呀。绑定github.io时候 提示站点或URL已经存在。

**Comment by cduyzh** [comment]
@cwyaml 
### 样式还是可以自定义的，不过局限性很多
###　我把之前的多说头像旋转代码和自己的一些CSS效果代码加了进去。
详见博客：(http://www.cduyzh.com/)

**Comment by mushanshitiancai** [comment]
我也遇到了 绑定github.io时候 提示站点或URL已经存在，怎解决啊

**Comment by NoahDragon** [comment]
因为有人已经注册了github.io的子域名。目前看来应该是自定义域名才可以。

**Comment by icessun** [comment]
404

**Comment by You-Mo** [comment]
也提示站点URL已存在,有啥解决方案吗?

**Comment by unclechen** [comment]
貌似没有解决办法。。。只好买域名了吗？

**Comment by cduyzh** [comment]
@unclechen @youmofangke  只能换个域名

**Comment by unclechen** [comment]
虽然域名随便写了一个，但是评论框确实可以用了。。见：

http://unclechen.github.io/

**Comment by loveNight** [comment]
翻了楼上几位的博客评论，发布常有「有态度网友06I5VA」字样出现。这玩意去不掉吗？

**Comment by orangeshinee** [comment]
@loveNight  那个是网易云跟帖的昵称0 0 . 你点开之后就看得到了。。我都不知道怎么修改那个，所以退了用微博登陆的。。

**Comment by lengmo714** [comment]
使用网易云更贴必须是最新版本的next?我在更新的时候老是失败

**Comment by wangzzu** [comment]
网易云跟帖可以设置显示最新评论么

**Comment by huayuanp** [comment]
报错~~~~"Uncaught TypeError: Cannot read property 'contentWindow' of undefined"蜜汁尴尬

**Comment by jovey-zheng** [comment]
同样遇到 `Uncaught TypeError: Cannot read property 'contentWindow' of undefined`

**Comment by hustlibraco** [comment]
@huayuanp  我也遇到了这个错误……怎么解决的？

**Comment by lengmo714** [comment]
把之前的多说什么的关了试下

**Comment by ivan-nginx** [comment]
@cwyaml don't understand u, write in English if not solved. If solved, close it please. Thank's!
