### ISSUE TITLE
主题-NexT.Pisces在手机上底部信息格式错乱

### ISSUE THREAD

**Issue by Catcheryp** [iissnan/hexo-theme-next#1551]
### Expected behavior (预期行为)

  sidebar:
  #Sidebar Position, available value: left | right
  #position: left
  position: right

这里当position调为right的时候，博客首页的底部信息格式在手机上应该显示正常
### Actual behavior (实际行为)
当position调为right的时候，博客首页的底部信息格式在手机上显示错乱
还有一个很郁闷的问题，就是在手机上博客首页的时候，点阅读全文没反应
而当position调为left的时候，博客首页的底部信息在手机上显示正常，点击阅读全文也没有问题，完全正常
### Steps to reproduce the behavior (重现步骤)
直接在手机上打开https://catcheryp.github.io/
查看底部
或
在浏览器上->开发者工具->调成在移动端显示

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:最新版本

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
This bug has been fixed, see #1536.

**Comment by Catcheryp** [comment]
我和这个问题不一样呀！我的不是不居中的问题，是它在手机上分成好几行显示

**Comment by Catcheryp** [comment]
好了，太感谢了！真的很感谢，我问题没有描述好，导致我google半天没有找到正确答案！
很感谢很感谢！！！
