### ISSUE TITLE
如何提交next源码

### ISSUE THREAD

**Issue by haoshuaiya** [iissnan/hexo-theme-next#1552]
## 如何提交next的源码
我为了实现可以在不同的电脑上编写博客，所以把我自己的源码托管到了coding上的私人项目上了，但是在提交代码的时候发现，只提交了next空文件夹，无法提交里面的内容，请问如何解决呢？

**Comment by iissnan** [comment]
使用 [Git 子模块](http://iissnan.com/progit/html/zh/ch6_6.html)

**Comment by haoshuaiya** [comment]
@iissnan  我用子模块的时候没有办法提交next内自己配置的内容，只记录了submodule的信息，不知道是不是我自己操作有问题呢？另外，我后面的解决方法是直接down了一份，没有从github上拿。

**Comment by kakas** [comment]
@haoshuaiya 可以把 theme 的配置放到 ../hexo_rootdir/source/_data/next.yml

**Comment by haoshuaiya** [comment]
@kakas 哦哦，好的，那如果我需要加点别的东西，比如说加个logo或者加个404页面之类的，应该怎么办呢?

**Comment by kakas** [comment]
@haoshuaiya 

next.yml
```yml
avatar: /images/avatar.png
```

把 avatar.png 放到 `hexo_rootdir/source/images/` 下即可 （images 資料夾要自己創）
依此類推

**Comment by ivan-nginx** [comment]
@haoshuaiya problem is solved?

**Comment by youmofangke** [comment]
直接将主题下的 .git   删除了,这样应该可行吧?

**Comment by RiversMaJianCheng** [comment]
我也遇到了这个问题

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
