### ISSUE TITLE
ERROR Script load failed: themes/next/scripts/tags/exturl.js

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1554]
ERROR Script load failed: themes/next/scripts/tags/exturl.js
Error: Cannot find module 'hexo-util'

**Comment by Neveryu** [comment]
重新装一下 `hexo-util` 应该就好了，[参照这个](https://neveryu.github.io/2016/12/15/hexo-next-four/)

**Comment by ivan-nginx** [comment]
@charsdavy  #issuecomment-286672452
