### ISSUE TITLE
不蒜子site_pv数量矫正

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1555]
因为网站已经上线一段时间，想将google analysis里面的数据一并算进来，请问要怎么矫正数据？

**Comment by charsdavy** [comment]
@newnius 解决了，谢谢

**Comment by Mine-MuYan** [comment]
给个网站的链接看看。@Chars

**Comment by charsdavy** [comment]
http://charsdavy.github.io/ @Mine-MuYan

**Comment by seymourtang** [comment]
@charsdavy 不蒜子初始化计数是怎么解决的啊?给作者发了邮件也没有回应啊。

**Comment by ivan-nginx** [comment]
@charsdavy issue is solved? And in English please.
