### ISSUE TITLE
求教：调整顶部菜单栏格式，改哪里？

### ISSUE THREAD

**Issue by liguanghe** [iissnan/hexo-theme-next#1556]
### Expected behavior (预期行为)
将博客名字和四个页面并列

### Actual behavior (实际行为)
现在的顶部显示：博客名字下面并列四个页面。

### Steps to reproduce the behavior (重现步骤)

不敢动，希望告诉我在哪里改~ 谢谢。

**Comment by ivan-nginx** [comment]
@liguanghe don't understand u, write in English if not solved. If solved, close it please. Thank's!
