### ISSUE TITLE
如何让 Next 支持「汉字标准格式」？

### ISSUE THREAD

**Issue by Lonor** [iissnan/hexo-theme-next#1558]
### Expected behavior (预期行为)
让 Next 支持[「汉字标准格式」](https://css.hanzi.co/manual)。

### Actual behavior (实际行为)
引用文件二个文件来启用「汉字标准格式」——han.min.css（或使用 Sass 汇入）及 han.min.js （或使用 JavaScript 模组框架），后者（脚本文件）可依网站的需求选用。
```<link rel="stylesheet" href="path/src/css/han.min.css">``` 
``` <script src="path/src/js/han.min.js"></script>```

### Steps to reproduce the behavior (重现步骤)
同上

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  ✔Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)

作为一个刚刚入门 HTML 和 Hexo 的菜鸟，不知道如何实现 QAQ。

**Comment by jjandxa** [comment]
仔细阅读源代码，可以的话作为一个可配置选项，在 **_config.yml** 启用或关闭。
**_layout/_script/vendors.swig** 是作为第三方库导入的一个模板。请多多研究后贡献代码吧。

**Comment by jjandxa** [comment]
_layout/_script/vendors.swig 是作为第三方库导入的一个模板，请多多研究并贡献代码吧。
不过似乎已经有人提交过 PR 了

**Comment by geekrainy** [comment]
@jjandxa 0dbde47

**Comment by ivan-nginx** [comment]
Reference to #1598
@Lonor problem is solved?

**Comment by Lonor** [comment]
Probldem solved. Much appreciated!

**Comment by ivan-nginx** [comment]
@Lonor if solved, why reopen it? Please, do all bugs in #1598. Thanks.
