### ISSUE TITLE
能否增加显示访问次数功能？

### ISSUE THREAD

**Issue by chineselzh** [iissnan/hexo-theme-next#156]
能否增加显示访问次数功能？谢谢！

**Comment by eurusd** [comment]
好象得需要插件支持吧，主题本身没法实现！

**Comment by chineselzh** [comment]
[http://ibruce.info/2015/04/04/busuanzi/#more](http://ibruce.info/2015/04/04/busuanzi/#more)
能否考虑增加进主题里？因为每次更新主题后都要手动更改，呵呵。。。

**Comment by flashlab** [comment]
@chineselzh 这种服务的稳定性值得商榷，而且修改似乎也不麻烦吧。反对把主题越改越臃肿。

**Comment by geekrainy** [comment]
@chineselzh 更新主题的时候处理下冲突就好了。

**Comment by eurusd** [comment]
同上楼上的朋友，反对把主题越改越臃肿。

**Comment by xirong** [comment]
你自己加入就可呀，看我的 www.ixirong.com 页尾，只是我用了一个图标，只有自己能看到这些访问量，你完全可以使用 cnzz 的另外的风格如  
![image](https://cloud.githubusercontent.com/assets/3087094/7750382/5d298b4c-0006-11e5-8544-7547ff2a0e4c.png)

**Comment by iissnan** [comment]
https://github.com/iissnan/hexo-theme-next/issues/216

**Comment by ihappyhacking** [comment]
http://ihappyhacking.github.io/
看我的这个（页脚），我已经实现了，用的是不蒜子
传送门：http://ibruce.info/2015/04/04/busuanzi/
