### ISSUE TITLE
tags 出现问题

### ISSUE THREAD

**Issue by longzhixin** [iissnan/hexo-theme-next#1560]
### Expected behavior (预期行为)
本地部署正常，点击tags 应该出现'读书笔记' 'writecode'

### Actual behavior (实际行为)
部署到github page 后
点击tags按钮，页面不会发生变哈，但是会刷新。
### Steps to reproduce the behavior (重现步骤)

本地部署正常。这是我的
http://longzhixin.github.io/
折腾了一天了无法解决。

**Comment by longzhixin** [comment]
warning: LF will be replaced by CRLF in tags/读书笔记/index.html.
The file will have its original line endings in your working directory.
Branch master set up to track remote branch master from git@github.com:longzhixin/longzhixin.github.io.git.
远程部署的时候会出现以上的警告

**Comment by iissnan** [comment]
It seems everything works well on your site.
