### ISSUE TITLE
为什么代码行无法滚动，不显示滚动条

### ISSUE THREAD

**Issue by chengw1121** [iissnan/hexo-theme-next#1562]
看了一圈Issues里面关于代码行滚动的。都是在问怎么去掉。。
但我的为什么没有滚动条？
不只是移动端，PC端也不显示。
求教怎么添加。。。代码行太长挤在一起很不舒服。

Mac，Safari

**Comment by Acris** [comment]
尝试使用```符号

**Comment by ivan-nginx** [comment]
@chengw1121 don't understand u, write in English if not solved. If solved, close it please. Thank's!
