### ISSUE TITLE
设置文章页标题跳转和自动展开标题

### ISSUE THREAD

**Issue by HoiweCheng** [iissnan/hexo-theme-next#1564]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/8936345/24602408/3c3339a8-188f-11e7-9fcf-42f788752aae.png)

图中的标题，如何设置点击标题跳转到标题位置，以及如何设置自动展开子标题？
谢谢！

**Comment by Neveryu** [comment]
现在本来就是这样的了啊

**Comment by HoiweCheng** [comment]
我的意思是，现在我的点击标题并不会跳转？有什么办法做么？

**Comment by Acris** [comment]
@HoiweCheng 你在markdown中子标题是用什么方式写的？

**Comment by HoiweCheng** [comment]
# 这种方式

**Comment by ivan-nginx** [comment]
@HoiweCheng if i right understand, u want make permalink without refresh your page.
Internal link: [Text](#Header "Title")

Issue resolved?
