### ISSUE TITLE
Scheme无法切换成Muse

### ISSUE THREAD

**Issue by yanshengjia** [iissnan/hexo-theme-next#1567]
### Expected behavior (预期行为)
将 Scheme 切换成 Muse

### Actual behavior (实际行为)
Scheme 还是 Mist

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 5.1.0

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
_config.yml:
scheme: Muse

**Comment by Neveryu** [comment]
```
# Schemes
scheme: Muse
#scheme: Mist
#scheme: Pisces
```
是这样写的吗？
然后记得清除缓存，重新 `hexo g`

**Comment by yanshengjia** [comment]
是这样写的。

清楚缓存了，然而还是切换不到 Muse Scheme。

Pisces Scheme 倒是可以切换。。。

**Comment by Acris** [comment]
生成前尝试执行一下`hexo clean`

**Comment by ivan-nginx** [comment]
@yanshengjia issue resolved?

**Comment by yanshengjia** [comment]
sloved
