### ISSUE TITLE
<!--more-->的位置应该放在哪

### ISSUE THREAD

**Issue by GEeKkk** [iissnan/hexo-theme-next#1568]
请问这个手动截断应该怎么放，我在文章中设置这个，

title:
date: 
tags:  
categories: 
这是摘录
(这里放的是截断符号)

结果开头的"title: "、"date: "、"tags: "、"categories: "被识别成摘录的一部分了，请问如何解决

**Comment by iissnan** [comment]
There should be an divider which separates the content and front-matter.

```
title: Hello World
date: 2013/7/13 20:46:25
---

Content goes here.
<!-- more -->
```

**Comment by ivan-nginx** [comment]
@GEeKkk issue is resolved?
