### ISSUE TITLE
local search点击无反应

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1570]
### Expected behavior (预期行为)

点击导航栏搜索框，弹出搜索交互界面
### Actual behavior (实际行为)

点击搜索无反应，调试发现调用了search.xml
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by charsdavy** [comment]
http://charsdavy.github.io

**Comment by Acris** [comment]
刚查看你的站点，是可以弹出搜索界面的。

**Comment by charsdavy** [comment]
@Acris 我已经换了，使用algolia搜索，不是local search。

**Comment by Acris** [comment]
好的。issue先关闭了，以后有问题再重新打开。

**Comment by fastzhong** [comment]
问题依旧，点了"搜索"（local search）, 一直出不来。

**Comment by dreamsk** [comment]
@fastzhong 重新安装下 hexo-generator-searchdb，如果不行，建议删除node_modules重新npm i
