### ISSUE TITLE
阅读次数文字不对

### ISSUE THREAD

**Issue by sweetkk** [iissnan/hexo-theme-next#1572]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by sweetkk** [comment]
[](url)
<img width="597" alt="2017-04-07 4 31 31" src="https://cloud.githubusercontent.com/assets/8746235/24792273/dd900362-1baf-11e7-9764-54a1d0400547.png">

**Comment by ivan-nginx** [comment]
@sweetkk what are u talking about? (In English, please)

**Comment by AlynxZhou** [comment]
也许你需要检查一下自己leancloud配置啊，还有如果是hexo s的话显示的应该不对，因为网址不对啊。
@ivan-nginx I think this more probably his own setting problem, not next's.

**Comment by ivan-nginx** [comment]
@AlynxZhou ok, will wait for him answer. And thank's for translate, @AlynxZhou =)
