### ISSUE TITLE
emoji文章评价

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1573]
### Expected behavior (预期行为)
请问有什么方式可以添加emoji文章评价功能。
类似于  http://www.kuwoku.com/2016/05/30/Hexo%E9%9B%86%E6%88%90Algolia%E6%90%9C%E7%B4%A2%E6%8F%92%E4%BB%B6/ 这个地址的效果
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Trim21** [comment]
这个用的是多说

**Comment by Acris** [comment]
需要第三方评论系统支持。

**Comment by ivan-nginx** [comment]
@charsdavy u are talking about this emoji?
![image](https://cloud.githubusercontent.com/assets/16944225/25247877/db32c0a4-2614-11e7-9cc5-dfc54db13665.png)
If yes, Acris right — need to import external libs services. U may pull request or give some links/examples about what services with this "emoji" u use.
