### ISSUE TITLE
如何修改首页文章间的间距以及分割线的长度？

### ISSUE THREAD

**Issue by jcx70100** [iissnan/hexo-theme-next#1575]
### Expected behavior (预期行为)
首页文章之间间距可以小一点，文章顶端间距也可以小一点，文章之间的分割线太短，希望能和文章页面宽度差不多，不然文章与文章之间不好区分。

### Actual behavior (实际行为)
文章之间间距过大，文章间的分割线太短，不好区分

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by allanxia** [comment]
同问，感觉首页上文章之间分割不清晰，而且留白太多了

**Comment by jcx70100** [comment]
@allanxia  找到了一个方法，写了一个教程，您可以参考一下 http://cxjiang.top/2017/04/07/Hexo-NexT/

**Comment by ivan-nginx** [comment]
@jcx70100 can u make this question in English, if issue is not solved.

**Comment by jcx70100** [comment]
fixed #1575

**Comment by allanxia** [comment]
感谢。
