### ISSUE TITLE
mist主题header固定后，点侧栏toc时，文章对应的锚点被遮盖。

### ISSUE THREAD

**Issue by budaig** [iissnan/hexo-theme-next#1576]
@iissnan 你好，我使用mist主题，修改导航菜单栏为固定，
点侧栏 toc 时，文章对应的锚点位于顶部，被导航栏遮盖了。自己试了很久也没办法将它下移。

我的博客 [www.zhinuo.site](www.zhinuo.site)

所做修改如下
next\source\css\_schemes\Mist\_header.styl 

```
.header {
  background: $whitesmoke;
  z-index: 999;
  opacity: 0.9;
  position: fixed;
  right: 0;
  left: 0;
  top: 0;  

  +mobile() { height: 58px; position: fixed; }
}
```

有时间的话能否帮忙解决？谢谢！

**Comment by budaig** [comment]
![Uploading 2017-04-07_193516.jpg…]()

**Comment by ivan-nginx** [comment]
@budaig in English, i not understand.
And can u do work screen?
