### ISSUE TITLE
友言评论

### ISSUE THREAD

**Issue by charsdavy** [iissnan/hexo-theme-next#1577]
### Expected behavior (预期行为)

能够使用友言评论
### Actual behavior (实际行为)

添加友言uid之后不能显示友言评论
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by charsdavy** [comment]
已经解决

**Comment by xiaohao890809** [comment]
请问怎么解决的呢？我现在友言添加了id不能使用哦！

**Comment by penggy** [comment]
是啊, 怎么解决的呀, @charsdavy 能提供些信息吗?
