### ISSUE TITLE
开启Disqus后评论框文字乱码

### ISSUE THREAD

**Issue by loody** [iissnan/hexo-theme-next#1579]
出现类似أوصي شارك رتب طبقاً这样的文字
next版本是5.1.0,改了其他的语言还是一样，求解！

**Comment by Acris** [comment]
貌似你已经换成网易云跟帖？
查看你的站点无法复现该问题。

**Comment by loody** [comment]
对啊，这个问题没解决就换云跟帖了

**Comment by ehlxr** [comment]
用 gitment 吧，挺不错的

**Comment by ivan-nginx** [comment]
@ehlxr Gitment — is Gitment. And there is issue about Disqus.

@loody can u give some screens or links with this problem and write in English?
