### ISSUE TITLE
站点概览的头像无法加载

### ISSUE THREAD

**Issue by cexowengui** [iissnan/hexo-theme-next#158]
点击一篇博客后侧边的站点概览的头像没有图片

**Comment by xiangfly11** [comment]
你的图片是放在自己的创建的文件夹下的吗？是不是只有在home页面的时候你侧边的头像能够显示？如果是的话，我建议在avatar后面添加网络链接，不要使用本地路径，因为我发现本地路径不能再public/tags/index.html这样的文件夹中使用，因为你所存的照片会被创建在public/soruce/images这个路径下。本人也是菜鸟，但是我是这样做的，如果有高手也请指教。谢谢

**Comment by cexowengui** [comment]
按你说的真的能行。原来是在themes/next/source/images/下放的头像图片，home下侧边头像是显示的，站点概览就不显示头像。 谢谢xiangfly11 ，要好好学习下nodejs了。
