### ISSUE TITLE
Tags删除后在Page页数目不变

### ISSUE THREAD

**Issue by bentleyxia** [iissnan/hexo-theme-next#1580]
### Expected behavior (预期行为)
Tags显示数目和tags计数保持一致

### Actual behavior (实际行为)
删除tags之后，tags计数数目不变，增加tags直接在原有基础增加

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@bentleyxia do u have any posts in _drafts directory?
And in English, please.

**Comment by azrael1911** [comment]
删除blog根目录下的db.json文件 然后 hexo s -g 打开浏览器后就可以有正确的标签数了 我是这样做的
