### ISSUE TITLE
如何删除每个菜单下的标题字样

### ISSUE THREAD

**Issue by EnkiChen** [iissnan/hexo-theme-next#1581]
在 3.1.0 版本中，在 关于/分类/标签 分页中是没有 about / categories / tags 标题的，在当前的 3.3.1 版本中，如何将 about / categories / tags 标题去除，否则会在界面中显示两个标题

我的个人博客是 http://www.enkichen.com/

**Comment by Acris** [comment]
@EnkiChen 麻烦尝试使用下hexo 3.2.2版本，看是否正常。

**Comment by Acris** [comment]
参考一下文档：http://theme-next.iissnan.com/theme-settings.html#tags-page
检查下source目录，查看并修改about、tags和categories目录中，index.md的title字段。

**Comment by EnkiChen** [comment]
多谢，我把 title 字段删除就可以了！
