### ISSUE TITLE
表格内容溢出

### ISSUE THREAD

**Issue by zlukawa** [iissnan/hexo-theme-next#1582]
### Expected behavior (预期行为)

下图为sublime text中所预览的表格
![1](https://cloud.githubusercontent.com/assets/22488967/24835867/0d4e1062-1d40-11e7-9746-cd2f2e056731.png)

### Actual behavior (实际行为)
如果表格中内容太多，放不下，导致表格间内容重合，而不是下一行继续放，或者添加一个滑动条。
下图为next主题中，添加表格所出现的问题。
![2](https://cloud.githubusercontent.com/assets/22488967/24835871/18958554-1d40-11e7-8678-5ecb252e6351.png)

以下为我的表格

| 1 |  0 |  0 | 0 |
| -- | -- | -- | --  |
| $1-P_1$ | $P_1$ | $0$ | $0$ |
| $(1-P_1)\times(1-P_2)$ | $P_1\times(1-P_2)+(1-P_1)\times P_2$ | $P_1\times P_2$ | $0$ |
| $(1-P_1)\times(1-P_2)\times(1-P_3)$ | $(P_1\times(1-P_2)+(1-P_1)\times P_2)\times(1-P_3)+(1-P_1)\times(1-P_2)\times P_3$ | $P_1\times P_2\times(1-P_3)+(P_1\times(1-P_2)+(1-P_1)\times P_2)\times P_3$ | $P_1\times P_2\times P_3$ | 

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by stevenjoezhang** [comment]
用`<div style="overflow-x: scroll !important; white-space: nowrap;"></div>`把表格框起来，似乎可以解决这个问题。
你有更好的解决方案么？

**Comment by ivan-nginx** [comment]
Solved in [598 pull](https://github.com/theme-next/hexo-theme-next/pull/598) (v6 / v7)
