### ISSUE TITLE
本地预览及部署后页面均显示空白

### ISSUE THREAD

**Issue by MmmL** [iissnan/hexo-theme-next#1584]
### Actual behavior (实际行为)
最初本地预览是正常的，没有看发布之后是否正常。
中间换了一次主题，再换回NEXT的时候，本地预览就是空白。
发布后也是空白。
只显示如图部分。
![20170409183859](https://cloud.githubusercontent.com/assets/13990729/24836676/96e41ef2-1d54-11e7-9ef0-21d33e8516d2.jpg)
![20170409183921](https://cloud.githubusercontent.com/assets/13990729/24836677/971f350a-1d54-11e7-9764-799152c859f2.jpg)

hexo clean了好几次QAQ
最新版本，vendors已经改成了lib

F12显示这个问题
![qq 20170409184455](https://cloud.githubusercontent.com/assets/13990729/24836682/aa8c22a6-1d54-11e7-9cc1-4bed1e9cdb17.jpg)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by rookiefly** [comment]
我刚刚交了pull request，见https://github.com/iissnan/hexo-theme-next/pull/1585

**Comment by gaoshijun1993** [comment]
把themes\next\source\js\src\utils.js 文件74行的  }); 删掉就好了。。。

**Comment by Acris** [comment]
@MmmL 最新版本已修复该BUG，麻烦确认下。
issue先关闭，有其他问题再重开。
