### ISSUE TITLE
当使用canvas背景动画时，手机端会无法滑动页面，提示：Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.

### ISSUE THREAD

**Issue by qwertyyb** [iissnan/hexo-theme-next#1589]
### Expected behavior (预期行为)
滑动页面

### Actual behavior (实际行为)
无法滑动

### Steps to reproduce the behavior (重现步骤)
将任意一个canvas动画设置为true

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Promix953** [comment]
我也是，IOS10.3.1 Safari
关闭动画就可以了

**Comment by aixiu** [comment]
经测式的确有这个问题！~！~

**Comment by zeeqy** [comment]
刚想开新问题，发现了有人提出来了，我就说一下我的情况吧，经过测试canvas_nest不会，但是three_waves在手机端（IOS）会出现无法下拉页面的问题。

**Comment by cpm828** [comment]
我之前也发现问题了，canvas_nest没问题，three_waves有bug，还给作者发email了，但是没回，希望能改进

**Comment by Acris** [comment]
@zeeqy 能否提供下iOS版本以及使用的浏览器和版本？

**Comment by cpm828** [comment]
@Acris 我测试的是ios10.3的，还有ios9，安卓也测了几个都无效，用微信内置浏览器测试的。

**Comment by zeeqy** [comment]
@Acris 移动端测试了两个设备，iphone6s iOS 10.3.1 Safari 和 ipad mini2 10.2.1 Safari

**Comment by Acris** [comment]
了解。
@jjandxa

**Comment by Acris** [comment]
@zeeqy @cpm828 麻烦更新最新版再试试。

**Comment by jjandxa** [comment]
@zeeqy @qwertyyb @Promix953 @aixiu 请更新最新版本测试

**Comment by zeeqy** [comment]
串，iphone6s iOS 10.3.1 Safari 和 ipad mini2 10.2.1 Safari 均没有问题。

**Comment by zeeqy** [comment]
研究了一下three.js，下个版本可以加多些背景吗？我刚才自己拼凑一个js文件放到source/lib里面，再改了一下vendors.swig把example里面的canvas_geometry_birds做成了Next的背景，感觉不错呢

**Comment by aixiu** [comment]
@jjandxa 火狐浏览器手机版 52.0  和 MIUI自带浏览器V8.6.5 问题依旧存在！~

**Comment by jjandxa** [comment]
@aixiu 已测试，Android 6.0.1 火狐浏览器手机版 52.0、MIUI 8.6.9.8 自带浏览器 V8.6.5 均无问题，请更新最新版本 **Next** 进行测试

**Comment by jjandxa** [comment]
@zeeqy 欢迎贡献代码

**Comment by addappcn** [comment]
我的是最新的next  用的wave  不能滑动

**Comment by aixiu** [comment]
@jjandxa 这问题的确还是存在，不能华东！~！

**Comment by qwertyyb** [comment]
@addappcn @aixiu 我刚刚更新测试了一下，没再出现这个问题，你用的什么浏览器？

**Comment by aixiu** [comment]
@qwertyyb 小米浏览器  一个朋友的平板不知道是什么  火狐浏览器手机版 52.0 和 MIUI自带浏览器V8.6.5 只能显示手机屏的大小，上下左右均无法移动，菜单能正常滑动，然而我现在关掉了彩带，以上浏览器均显示正常滑动！~！

**Comment by cpm828** [comment]
@Acris 我对next主题的配置个人修改了一些，如何在保证我这边不做修改的前提下更新？

**Comment by Acris** [comment]
@cpm828 #328
