### ISSUE TITLE
设置了duoshuo_shortname但是会提示“还没有设置多说域名”

### ISSUE THREAD

**Issue by Witype** [iissnan/hexo-theme-next#159]
_config中的设置
# duoshuo accout
duoshuo_shortname: witype
----------------------------------------------------

# 这样设置多说账号也不行
duoshuo_shortname: witype.duoshuo.com
-----------------------------------------------------
![pasted_image](https://cloud.githubusercontent.com/assets/6899329/7664781/d4a8e716-fbca-11e4-883e-fc7ca391e683.jpg)

**Comment by eclipseflower** [comment]
你有注册多说么
