### ISSUE TITLE
订阅微信公众号失败

### ISSUE THREAD

**Issue by tingtingli911** [iissnan/hexo-theme-next#1590]
### Expected behavior (预期行为)

文章底部生成微信公众号的二维码

### Actual behavior (实际行为)

无法加载二维码图片，甚至编译无法通过

### Steps to reproduce the behavior (重现步骤)

按照介绍中的步骤完成，结果无法在文章末尾正常显示二维码

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 

  -  Master
  -  ✔   Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -   ✔  Mist
  -  Pisces

**Comment by Acris** [comment]
编译无法通过？贴一下错误信息看看。

**Comment by ivan-nginx** [comment]
@tingtingli911 in Eng, pls. Don't understand in what error.
