### ISSUE TITLE
footer中的年份在不重新hexo g的情况下不能自动更新

### ISSUE THREAD

**Issue by seymourtang** [iissnan/hexo-theme-next#1594]
希望不要在generate的时候就将footer中的年份写死了，建议写个js当用户访问的时候来输出当前的年份。

**Comment by ivan-nginx** [comment]
@seymourtang live demo?
And in English, please.

**Comment by iissnan** [comment]
@ivan-nginx He said the date time in the footer section should not be hard coded.

**Comment by ivan-nginx** [comment]
@iissnan what's mean "in footer"? In post meta may be? Where time create and time modified. Is it?
