### ISSUE TITLE
请问添加菜单后需要toc效果如何配置？

### ISSUE THREAD

**Issue by thqy39** [iissnan/hexo-theme-next#1601]
还有 请问菜单的图标在哪里改

**Comment by Neveryu** [comment]
toc 已经配在侧边栏中了，你如果想配在顶部，可能需要自己动手实现。
[菜单的图标配置](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/_config.yml#L45)

**Comment by ivan-nginx** [comment]
Don't understand, what u mean? In English, please.
