### ISSUE TITLE
当文章目录过长时，无法显示完全

### ISSUE THREAD

**Issue by brandon911** [iissnan/hexo-theme-next#1602]
**当文章目录过长时，无法显示完全**

NexT Version:version: 5.1.0

### Other Information (Like Browser, System, Screenshots)
Chrome 57.0.2  ；win10；
![default](https://cloud.githubusercontent.com/assets/8828859/25120733/d71eefac-2451-11e7-837d-f013fef53fc9.PNG)

**Comment by ivan-nginx** [comment]
@brandon911 need to insert at least 1 space to next line formatting.

**Comment by yizhushan** [comment]
请问怎么添加目录,需要在layout中添加格式代码吗?我直接用md的段落语法不会自动生成目录呀

**Comment by ivan-nginx** [comment]
@yizhushan in English, please.
