### ISSUE TITLE
实现支持双评论（Gitment 和 Disqus），可以选择默认加载一个或两个，点击按钮后在加载等功能

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1604]
实现支持双评论（Gitment 和 Disqus），可以选择默认加载一个或两个，点击按钮后在加载等功能。

由于更改个性化东西太多，提交 PR 冲突太多，所以有需要的可以留言给我，我单独发送！

参考效果 https://ehlxr.me/about/

#1549 #1518 #1527 #1528 #1544

**Comment by aixiu** [comment]
你这个做法还是很牛的，设计的也挺好！！希望做的更好。服务hexo!~

**Comment by ivan-nginx** [comment]
Reference to #1549

**Comment by chchuj** [comment]
我的解决方法：
[Hexo Next 主题点击加载 Disqus 和来必力双评论系统](https://chchuj.coding.me/20171123-load-Disqus-livere-comment-on-click-in-hexo-next-theme/)

**Comment by 1022-zhang** [comment]
研究了一下，配合主题配置，减少原主题文件修改的方法：https://1022-zhang.github.io/combined-comments.html

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by ivan-nginx** [comment]
Added in https://github.com/theme-next/hexo-theme-next/pull/1048
