### ISSUE TITLE
GFW内在线字体太不稳定，请问有没办法上传字体文件用本地字体

### ISSUE THREAD

**Issue by zhuoji** [iissnan/hexo-theme-next#1605]
虽然有360做的谷歌镜像，还是会时常抽风

**Comment by aixiu** [comment]
fonts.lug.ustc.edu.cn  用这个地址试试

**Comment by ivan-nginx** [comment]
@zhuoji don't understand u, write in English if not solved. If solved, close it please. Thank's!
