### ISSUE TITLE
个别页面 TOC 报错

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#1608]
### Expected behavior (预期行为)
无报错，且 leancloud 计数可用
### Actual behavior (实际行为)
报错，leancloud 计数不可用
### Steps to reproduce the behavior (重现步骤)
页面1：https://rainylog.com/post/what-methods-of-clearfix-can-i-use/  
页面2：https://rainylog.com/post/hexo-post-image-manage/

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces✔

### Other Information (Like Browser, System, Screenshots)
页面1，页面2 打开控制台都提示：
![2017042002](https://cloud.githubusercontent.com/assets/7333266/25232589/7a9f1ca2-260e-11e7-888b-2383b1558198.png)
且这两个页面的右侧浮动 TOC 在滚动到下方时并不会悬浮在右侧，而是固定在页面上方。并且无一例外这两个页面都无法使用 leancloud 的阅读统计。可能是这个报错导致一些 js 无法运行。

暂时不清楚这个问题的出现情景，只是个别出现，不知和标题结构存在什么样的联系。

**Comment by ivan-nginx** [comment]
@geekrainy

> jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: # 溢出属性
> Uncaught Error: Syntax error, unrecognized expression: # 同步目录
> # 溢出属性
> # 同步目录
![image](https://cloud.githubusercontent.com/assets/16944225/25233220/c547b692-25e6-11e7-8931-d06eb5082c53.png)
![image](https://cloud.githubusercontent.com/assets/16944225/25233195/b018702c-25e6-11e7-8ce9-8a779658b88f.png)

See? This is spaces.

**Comment by geekrainy** [comment]
@ivan-nginx My markdown not have any additional spaces.
`## 同步目录`  
`## 溢出属性`  
But hexo rendered to:
` 同步目录`  
` 溢出属性`  
I don't known why.

**Comment by ivan-nginx** [comment]
Yeah. i think about it. This is strange. MB, error in markdown rendering `hexo-renderer-marked` module? In this case need to do 2 things:
1. Test same posts on any another theme (not Next).
2. If error will, write same issue on Hexo thread. If will not error, then try to off any additional Next modules and check it again.

**Comment by geekrainy** [comment]
I switch to default theme. This bug still exists. I think it's an error from `hexo-renderer-marked` module. I will report this problem.

**Comment by geekrainy** [comment]
[hexo-filter-auto-spacing](https://github.com/hexojs/hexo-filter-auto-spacing). It's the cause of this problem.

**Comment by ivan-nginx** [comment]
@geekrainy it's standart plugin?
