### ISSUE TITLE
如何在某个分类下搜索?

### ISSUE THREAD

**Issue by MrMorning** [iissnan/hexo-theme-next#1610]
我有许多文章, 我希望做了分类之后能够在这个分类下搜索, 或者选中一个标签, 使得仅仅显示这个分类下带有这个标签的文章, 请问我该怎么做?
I have lots of articles and I want to find articles with more than one property, what i want to do is to search some ariticle in a particular category rather than search in the whole blog. Or I want to select a tag and a category to display articles that both have the tag and the category. What should I do to realize this feature? Thx.
@ivan-nginx

**Comment by ivan-nginx** [comment]
@MrMorning can u explain your problem in English language? Tnx.

**Comment by flashlab** [comment]
可以在分类页面生成单独的索引文件。

**Comment by MrMorning** [comment]
@flashlab 
可以详细说一下怎么做吗? 谢谢您的帮助.

**Comment by ivan-nginx** [comment]
@MrMorning this can make with [hexo-generator-index2](https://github.com/Jamling/hexo-generator-index2).
```
index_generator:
	per_page: 10
	order_by: date
	include:
#		- category CATEGORY
		- path PERMALINK
#	exclude:
#		- tag TAG
```
Isse is resolved?
