### ISSUE TITLE
scrollpercent 进度显示有问题

### ISSUE THREAD

**Issue by VeiZhang** [iissnan/hexo-theme-next#1615]
### Expected behavior (预期行为)
scrollpercent为百分之正数，且网页最底下为100%

### Actual behavior (实际行为)
scrollpercent是负数，且网页最底下不为100%

### Steps to reproduce the behavior (重现步骤)
开启scrollpercent，在分类，标签页面，长度较短的页面时，向下滚动，会出现

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release  ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces  ✔

### Other Information (Like Browser, System, Screenshots)
![qq 20170422190154](https://cloud.githubusercontent.com/assets/19425616/25303903/c9e260ae-278e-11e7-8a41-c53016ace6f6.png)

**Comment by ivan-nginx** [comment]
@VeiZhang u install latest patch on this? #1574
https://github.com/iissnan/hexo-theme-next/commit/4bd315d0d40ba42a7c6efbb244fa75bef8eb5497

**Comment by VeiZhang** [comment]
@ivan-nginx 我合并了最新的NexT代码后，这种现象

**Comment by ivan-nginx** [comment]
@VeiZhang write in English, please.
I see your site and not see -22%. How u can get -22%? What u do?

**Comment by VeiZhang** [comment]
@ivan-nginx in the site tags：http://tiimor.cn/tags/ ，if you scroll down， it will be

**Comment by ivan-nginx** [comment]
@VeiZhang ok, i see it now, but can't reproducte on test site. Can u off all plugins/extensions/comments for a moment to see what that conflict is not give any plugin.

**Comment by ivan-nginx** [comment]
@VeiZhang ok, no need to do, i find it.

**Comment by VeiZhang** [comment]
@ivan-nginx ok， Thx

**Comment by ivan-nginx** [comment]
@VeiZhang ok, i fix it.
Issue is resolved?

**Comment by VeiZhang** [comment]
@ivan-nginx  Yes, It's OK, Thx
