### ISSUE TITLE
Disqus 评论数统计不显示

### ISSUE THREAD

**Issue by ehlxr** [iissnan/hexo-theme-next#1617]
已经正常配置 Disqus ，也能保证正常访问 disqus.com 

不显示评论个数
![image](https://cloud.githubusercontent.com/assets/11313370/25319570/146e35b4-28d2-11e7-9dba-6592d55582f9.png)

已经有评论数
![image](https://cloud.githubusercontent.com/assets/11313370/25319507/7c4fdf3a-28d1-11e7-8d20-486ec71db45f.png)

**Comment by Acris** [comment]
![DQ.png](https://ooo.0o0.ooo/2017/04/24/58fd9baf10d05.png)

看样子是Disqus没有返回评论数，请检查Disqus相关配置，以及Hexo配置文件中站点地址与Disqus是否一致。

**Comment by ivan-nginx** [comment]
No. This is Next theme bug. Disqus must return count of comments.

**Comment by Acris** [comment]
@ivan-nginx Really? but I tested on my blog just now and the count function is worked fine.

**Comment by ivan-nginx** [comment]
@Acris i don't remember, but with Disqus there is was somethere bug, with count. Maybe fixed?

**Comment by SPRING-Z** [comment]
我的也是这样，评论数不对，就算有评论还是显示的 0

**Comment by ehlxr** [comment]
@Acris 配置都检查了，没啥问题

**Comment by SPRING-Z** [comment]
发现问题了，等几个小时就好了，貌似评论数刷新需要时间

**Comment by ehlxr** [comment]
@ivan-nginx it's not work yet，I'm checking the reason now

**Comment by ehlxr** [comment]
@SPRING-Z 可我的已经评论完好久了，还是不显示

**Comment by ehlxr** [comment]
i find the reason. i change my website from http to https, but i forget update disqus setting

**Comment by JohnnyLuv** [comment]
是过了几分钟才刷新出来，但是首页的计数君还是阵亡状态=-=

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
