### ISSUE TITLE
如何修改首页文章顶部与标题之间的距离

### ISSUE THREAD

**Issue by jcx70100** [iissnan/hexo-theme-next#1619]
### Expected behavior (预期行为)

减小首页显示的文章正文顶部与"发表于"一栏之间的距离，现在距离比较大，想缩小一点，更美观

![](http://okr3rrs4n.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-04-24%20%E4%B8%8B%E5%8D%888.45.48.png)

### Actual behavior (实际行为)
没找到修改方法

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@jcx70100 in English, please. What style u need? All custom styles may rewrite in `source/css/_custom/custom.styl`.

**Comment by jcx70100** [comment]
@ivan-nginx  Thank you for your attention, my question is: the distance between the title and the top of article is too loog , i want to make it  smaller ,  the picture below may make my problem more clearly:

![](http://okr3rrs4n.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-04-25%20%E4%B8%8A%E5%8D%889.07.46.png)

**Comment by ivan-nginx** [comment]
@jcx70100 ok, i see. That's easy, u may change any custom style u want without edit original Next templates. To do this, in file `next/source/css/_custom/custom.styl` simply add your any custom css:
```
.posts-expand .post-meta {
	margin: 3px 0 5px 0;
}
```
If issue is solved, close it please.

**Comment by jcx70100** [comment]
@ivan-nginx  I solved the problem under your tips, you are so kind, thanks very much.

close #1619

**Comment by jcx70100** [comment]
close #1619
