### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by fewtime** [iissnan/hexo-theme-next#162]
目前代码显示会挤成一块，看不到代码
文件是hexo自带的Hello World文件
如图
![代码显示](http://i1.tietuku.com/28c41ee85c88522c.png)
请问怎样才能让它正常显示？

**Comment by xiangfly11** [comment]
@fewtime 我使用https://stackedit.io/这个网站写markdown,可以直接看效果，你可以试一下，它上面有定义好的代码块，只要在工具栏点击之后输入代码就可以正常显示了。

**Comment by fewtime** [comment]
@xiangfly11 还是不行，我把[stackedit.io](http://stackedit.io)的范例放进去，还是显示错误，我不知道是不是自己在哪里设置错了。
![code](http://i1.tietuku.com/78d8e59d7ea8c203.png)

**Comment by xiangfly11** [comment]
@fewtime 那我还真的不知道怎么办了，我也是新手。

**Comment by fewtime** [comment]
用稳定版能正常显示，估计是新版的一个bug

**Comment by mingmings** [comment]
![image](https://cloud.githubusercontent.com/assets/3365500/7768549/d3ef7928-00ae-11e5-81d3-c7bb1fcc130d.png)
更新了 hexo 3 之后，next 主题下的代码块就成了上面那样，这个是这个原因引起的么？

**Comment by alfredtofu** [comment]
@fewtime 代码块显示问题解决了么？
此外，@iissnan 我发现很多merge都没注释....

**Comment by alfredtofu** [comment]
修改文件`source/css/_vendor/highlight/highlight.styl`，修改`line-height`的属性：`line-height:  $line-height-base`

不过我现在遇到的问题是，不管怎样都是只显示只有一行，而且不高亮
![selection_010](https://cloud.githubusercontent.com/assets/1112801/7878184/cb63cd5a-0616-11e5-8492-fad8387c31b7.png)

**Comment by alfredtofu** [comment]
fix了，在站点配置加上`auto_detect: true`，详见 [#186](https://github.com/iissnan/hexo-theme-next/issues/186)

**Comment by iissnan** [comment]
@alfredtofu 我猜测这个 bug 可能跟之前修改 line-height 有所关系，但是没去验证，你修改之后可以解决这个问题吗？

只有一行看起来是 `highlight.js` 无法解析你使用的语言，你可以试试给代码快加上语言指示，例如：

```js
function repeat (target, n ) {
  return new Array(n + 1).join(target);
}
```

**Comment by alfredtofu** [comment]
@iissnan 只显示一行跟不高亮的问题应该正如你说的，3.1默认不检测代码，至于代码块宽度不够的问题，我刚才重新去验证了，`line-height: $line-height-base`改回`line-height: $line-height-code-block`，还会会出现缩成一团的问题，我用chrome的控制台看过，是line-weight是1.2，改成1.6就没问题，web我一窍不懂，也没办法做深入探究，但是改成`line-height: $line-height-base`能解决我的问题。
![selection_011](https://cloud.githubusercontent.com/assets/1112801/7878762/6fee5bce-061c-11e5-9ed5-380684b195fd.png)

**Comment by iissnan** [comment]
@alfredtofu 多谢。 `line-height` 是特意从 1.6 改成 1.2 的，我再花点时间看下。

**Comment by fewtime** [comment]
@alfredtofu @iissnan 代码能正场显示了，行数显示也正常

**Comment by MingyuWu** [comment]
我现在用现在还是一坨
