### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by daoqing99** [iissnan/hexo-theme-next#1620]
next 的Markdown 语法是什么样的，怎么跟标准的不一样的

比如这个a链接变成这样了  难看啊

**Comment by ivan-nginx** [comment]
@daoqing99 can u give some example?
Also, if error in mardown, why u wrote in Next theme issues? Mb need to do issue in [`hexo-renderer-marked`](https://github.com/hexojs/hexo-renderer-marked)?
