### ISSUE TITLE
安装完主题，不显示文章，刷新后页面最下面有错误信息

### ISSUE THREAD

**Issue by yimuyang** [iissnan/hexo-theme-next#1623]
### Expected behavior (预期行为)
安装主题完，显示默认文章

### Actual behavior (实际行为)
安装完之后，页面大面积空白，只显示了footer部分，源代码里请求到了文章的内容但是没有显示，刷新一下，footer下面出现js代码

### Steps to reproduce the behavior (重现步骤)
错误如下：
这是footer
>© 2017  yim
>Erstellt mit Hexo  Theme - NexT.Muse

这是footer下面的错误信息，js代码
```javascript
nter.get('time'));\n },\n error: function(newcounter, error) {\n console.log('Failed to create');\n }\n });\n }\n },\n error: function(error) {\n console.log('Error:' + error.code + \" \" + error.message);\n }\n });\n }\n\n $(function() {\n var Counter = AV.Object.extend(\"Counter\");\n if ($('.leancloud_visitors').length == 1) {\n addCount(Counter);\n } else if ($('.post-title-link').length > 1) {\n
```
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes ✔
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
背景绿色是因为我用了护眼插件
![error](https://cloud.githubusercontent.com/assets/13547399/25379064/55c24944-29de-11e7-9f80-851f46719208.png)

**Comment by iissnan** [comment]
It seems some template was interrupted. Can you try to reinstall the theme?

**Comment by yimuyang** [comment]
@iissnan yes, I tried. It works well when I change to the v5.0.0 version.
