### ISSUE TITLE
5.1.1版本添加网易云跟贴有BUG

### ISSUE THREAD

**Issue by a506488043** [iissnan/hexo-theme-next#1624]
### Expected behavior (预期行为)
disqus下面的enable 填false，评论显示。
填true，网易云跟贴就不显示了。这个是什么情况？
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
使用网易云跟帖需要禁用disqus，暂时无法同时开启。

**Comment by a506488043** [comment]
这样啊，为什么教程没提示。

**Comment by iissnan** [comment]
Only one comment system would be adopted if enabled at the same time. And comment systems are prioritized.
