### ISSUE TITLE
5.1.0添加网易云跟帖后,首页加载时cloud-tie-wrapper元素未加载导致js报错

### ISSUE THREAD

**Issue by TimLuo465** [iissnan/hexo-theme-next#1625]
### Expected behavior (预期行为)
首页加载时，评论系统不应该加载，只有page加载时才加载评论系统

### Actual behavior (实际行为)
首页加载时, 引用了云跟帖的SDK, 但是对应的wrap没有加载

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by TimLuo465** [comment]
我在_third-party/comments/index.swig中添加了判断
{% if page.comments %} ... {% endif %}
问题暂时解决

**Comment by iissnan** [comment]
That should be a bug

**Comment by ivan-nginx** [comment]
@TimLuo465 don't understand u, write in English if not solved. If solved, close it please. Thank's!
