### ISSUE TITLE
IE9 报错，matchMedia，建议考虑使用 垫片

### ISSUE THREAD

**Issue by biaomingzhong** [iissnan/hexo-theme-next#1626]
### Expected behavior (预期行为)
Win7使用IE9访问正常

### Actual behavior (实际行为)
IE9访问的时候报错

### Steps to reproduce the behavior (重现步骤)
访问 [我的博客](https://biaomingzhong.github.io/)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Latest Release

NexT Scheme: 
  - Pisces

### Other Information (Like Browser, System, Screenshots)
IE9 报错信息
```
SCRIPT438: 对象不支持“matchMedia”属性或方法 
pisces.js，底下这一行
r=window.matchMedia("(min-width: 991px)")
```

**Comment by iissnan** [comment]
https://github.com/paulirish/matchMedia.js

**Comment by ivan-nginx** [comment]
@biaomingzhong don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by biaomingzhong** [comment]
@ivan-nginx Just open your blog in IE9. I found an error.
```
SCRIPT438: 对象不支持“matchMedia”属性或方法 
pisces.js，底下这一行
r=window.matchMedia("(min-width: 991px)")
```
It means that IE9 `Window` didn't have method  `matchMedia`. So I suggest you adding a polyfill for `matchMedia`. And `iissnan` provide a link that host this kind of polyfill

**Comment by ivan-nginx** [comment]
IE not supported by NexT anymore. See [here](https://github.com/theme-next/hexo-theme-next/issues/30) for details.

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
