### ISSUE TITLE
创建了一个新的菜单，如何让文章放到新创建的菜单下面？

### ISSUE THREAD

**Issue by sunny123123** [iissnan/hexo-theme-next#1629]
如果新创建了一个菜单，既不是category也不是tags。比如新创建live菜单，那么在写文章的时候这么把文章放到这个我新创建的live菜单下面呢

**Comment by iissnan** [comment]
You can link the "live" menu item to a custom page in which collects specific posts. Need to create a template to support this.

**Comment by sunny123123** [comment]
Yes, I thought there is a better or more convenient way just like "Home" menu. Thanks very much. I will try this just like what you say.

**Comment by zhuzhuyule** [comment]
@iissnan but a problem exist！the posts of new page collects will not add to tags and categories ！

@sunny123123 
I find the plugin hexo-generator-index2 that have filtered function, you can copy this plugin then new a page! you can try it !
