### ISSUE TITLE
友链问题

### ISSUE THREAD

**Issue by allanzhang** [iissnan/hexo-theme-next#163]
自己想修改，不知道修改那些文件和样式，求教~

作者能不能加上这个功能，很频繁的使用吧，在国内。

**Comment by mingmings** [comment]
cool，下个版本中友链都带上了

**Comment by iamwent** [comment]
[给 NexT 主题增加友情链接功能](http://iamwent.github.io/2015/06/11/adding-friendly-links-to-next-theme/)，在侧边栏添加友链

**Comment by xirong** [comment]
@iamwent  赞，已经添加！

**Comment by iamwent** [comment]
@xirong 哈, 从你的 github 也学到不少东西, 感谢

**Comment by mingmings** [comment]
撇除 next 的友链不说，有没有比较好的友链模板，想单独做一个友链

**Comment by iissnan** [comment]
@iamwent 你能把你的关于友链的修改发一个 PR 给我吗

**Comment by mingmings** [comment]
@iissnan 原以为 github的 wiki 也能发 PR 的，结果看了半天没有，悲催了~

**Comment by iissnan** [comment]
可以直接改

**Comment by iissnan** [comment]
#250 Thanks to @iamwent
