### ISSUE TITLE
Hexo g 无法生成，load过后就显示killed了

### ISSUE THREAD

**Issue by Gahon1995** [iissnan/hexo-theme-next#1631]
### Expected behavior (预期行为)
生成一下主题

### Actual behavior (实际行为)
更改了一下主题，但是生成是却发现无法继续生成了，一生成就提示被killed，但是用其他主题就能够生成。

### Steps to reproduce the behavior (重现步骤)

一直不能生成
删掉重装了也不能够生成。
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master  ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
debug信息：
---------
14:48:27.010 DEBUG Processed: source/lib/font-awesome/fonts/fontawesome-webfont.svg
14:49:18.479 DEBUG Generator: page
14:49:18.558 DEBUG Generator: post
14:49:18.714 DEBUG Generator: json-content
14:49:19.036 DEBUG Generator: index
14:49:19.397 DEBUG Generator: category
14:49:19.620 DEBUG Generator: archive
14:49:19.821 DEBUG Generator: tag
14:49:22.469 DEBUG Generator: asset
14:49:24.065 INFO  Files loaded in 60 s
14:49:24.477 DEBUG Rendering page: tags/index.html
14:49:25.349 DEBUG Rendering index: index.html
14:49:25.966 DEBUG Rendering archive: archives/index.html
14:49:26.589 DEBUG Rendering archive: archives/2017/index.html
14:49:27.213 DEBUG Rendering post: 2017/04/01/Hello-Gahon/index.html
14:49:27.779 DEBUG Rendering archive: archives/2017/04/index.html
14:49:31.637 DEBUG Rendering post: 2017/04/01/hello-world/index.html
14:49:37.401 DEBUG Rendering tag: tags/MarkDown/index.html
14:49:54.641 DEBUG Rendering tag: tags/随笔/index.html
14:49:55.355 DEBUG Rendering tag: tags/测试/index.html
14:49:55.882 DEBUG Rendering post: 2017/04/01/markdownTest/index.html
14:50:00.511 DEBUG Rendering tag: tags/Testing/index.html
Killed

**Comment by iissnan** [comment]
Not sure the about this issue. Is the process killed when rendering 'tags/Testing/index.html' all the time?

**Comment by Gahon1995** [comment]
解决了，主要原因是因为内存不足，我创建了一个swap就能够生成了
