### ISSUE TITLE
如何在侧边栏添加分隔符

### ISSUE THREAD

**Issue by Zeecoders** [iissnan/hexo-theme-next#1636]
### Expected behavior (预期行为)

（上传图一直失败，很抱歉）
麻烦到我的博客[zeecoder](http://zcheng.ren)中看预期行为，在云标签和友情链接中间能否添加虚线分隔符。

### Actual behavior (实际行为)
实际中间没有分隔符

### Steps to reproduce the behavior (重现步骤)

无
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@Zeecoders don't understand u, write in English if not solved. If solved, close it please. Thank's!
