### ISSUE TITLE
Mathjax公式无法显示

### ISSUE THREAD

**Issue by juneshi0315** [iissnan/hexo-theme-next#1637]
### Expected behavior (预期行为)
显示Mathjax公式

### Actual behavior (实际行为)
在主题配置文件中自定义了Mathjax CDN，但生成页面中公式部分指定的Mathjax源仍是默认源。事实上原来的源已经无法使用，已经迁移到了cdnjs.cloudflare.com，参见[http://docs.mathjax.org/en/latest/start.html](url)

### Steps to reproduce the behavior (重现步骤)
在文件中写一些公式

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by duohappy** [comment]
try to replace default with
//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

**Comment by angrySquirrel** [comment]
Referring to http://docs.mathjax.org/en/latest/start.html
use this should works fine : 
https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML

**Comment by huyingjie** [comment]
@duohappy It works. Thank you.

**Comment by JYCFM** [comment]
那个，请问我在本地的_config.yml设置好了样式，比如   sidebar:  position: left  这样设置好了，然后推送到git上就没有变，是怎么办呢 ？

**Comment by ivan-nginx** [comment]
Solved and resumed all possible future MathJax issues [here](https://github.com/theme-next/hexo-theme-next/issues/19).
