### ISSUE TITLE
主题配置文件中han设置为true后，一级标题与正文之间的空行显示不正常

### ISSUE THREAD

**Issue by fulanto** [iissnan/hexo-theme-next#1645]
### Expected behavior (预期行为)
一级标题与正文之间空行正确显示

### Actual behavior (实际行为)
一级标题与正文之间紧挨在一起

### Steps to reproduce the behavior (重现步骤)
将主题配置文件中的[han]配置项设为[true]

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

**Comment by Richard-Cao** [comment]
Pisces也有这个问题

**Comment by geekrainy** [comment]
默认样式是这样，会考虑进行一些调整。

**Comment by sli1989** [comment]
还有一级标题下面正文的行距不对。

![Uploading 2.png…]()
![Uploading 1.png…]()

**Comment by ivan-nginx** [comment]
@fulanto don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by fulanto** [comment]
@ivan-nginx there is a configuration item in the theme config file named _han_. If set it to true,  h1 header and article are too closed.

**Comment by ivan-nginx** [comment]
@fulanto screens? Live demo? Anything.

**Comment by geekrainy** [comment]
@ivan-nginx I will fix it.

**Comment by ivan-nginx** [comment]
@geekrainy ok, thank's a lot!

**Comment by ivan-nginx** [comment]
@fulanto fix in #1780. Solved?

**Comment by fulanto** [comment]
@ivan-nginx Yes, it solved. Thank you very much. Thanks @geekrainy .
