### ISSUE TITLE
W3 validator Baidu errors.

### ISSUE THREAD

**Issue by ivan-nginx** [iissnan/hexo-theme-next#1646]
In file `layout/_partials/head.swig` there are strings:
```
{# #238, Disable Baidu tranformation #}
<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
```
And W3 validator give 2 errors on this:
![image](https://cloud.githubusercontent.com/assets/16944225/25645763/35c1b4ae-2fba-11e7-83b9-48324e690219.png)

My questions is:
1. For what this was doing?
2. Why this give errors?
3. If it only for Baidu and if it really need, may be we can add switch option to disable it errors when Baidu not used?

```
{% if theme.baidu_push or theme.baidu_analytics %}
  {# #238, Disable Baidu tranformation #}
  <meta http-equiv="Cache-Control" content="no-transform" />
  <meta http-equiv="Cache-Control" content="no-siteapp" />
{% endif %}
```

What u think about it?

**Comment by iissnan** [comment]
Baidu is a search engine that likes Google, it is widely used in China. Baidu transforms sites using their own presentation fot mobile devices, those two meta are used to tell Baidu not to do the transformation.
 
I think we should add an option such as `baidub_transformation_disabled` so that users can enable it by themselves.

**Comment by ivan-nginx** [comment]
@iissnan ok, but why errors in W3 validator?

**Comment by iissnan** [comment]
According to the W3C specification, the value for http-eqiuv is not valid. Please see https://www.w3.org/TR/2016/REC-html51-20161101/document-metadata.html#pragma-directives

**Comment by ivan-nginx** [comment]
Yeah, i just see it. And talking about it. I think may try to resolve it.

**Comment by ivan-nginx** [comment]
@iissnan @Acris @ can we resolve this issue?
