### ISSUE TITLE
侧栏的分类不显示

### ISSUE THREAD

**Issue by a506488043** [iissnan/hexo-theme-next#1648]
### Expected behavior (预期行为)

设置了分类不显示
### Actual behavior (实际行为)

www.saiita.cn

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
What are u talking about? In English.

**Comment by a506488043** [comment]
The sidebar adds categories of pages, points in the non-reality category,

**Comment by jjandxa** [comment]
1. `hexo new page "tags"`
2. edit **source/tags/index.md**, modify **type** to **tags**

**source/tags/index.md**
```
---
title: 标签
date: 2017-03-23 09:59:07
type: "tags"
comments: false
---
```
