### ISSUE TITLE
首页显示的文章的全部，而不是部分，怎么回事？

### ISSUE THREAD

**Issue by suoba** [iissnan/hexo-theme-next#165]
我的显示了文章全部内容呢。。。老长老长的看着闹心，怎么限定是显示文章摘要，片段或者内容目录啊？
具体请看：
http://dksrz.com
我是不会编码的小白，麻烦尽量说简单点。谢谢

**Comment by wbprime** [comment]
在你post.md文件的front matter区域添加description字段，也就是在三个连字符那一行的上面添加一行。

比如，有一篇post：

    title: first
    date: 2015-05-17
    description: 简要介绍 加在这里
    ---

    正文部分 blablabla

祝好运！

Best wishes from Elvis Wang <mail AT wbprime DOT me>

**Comment by fewtime** [comment]
也可以用，会显示它上面的内容

**Comment by xirong** [comment]
我理解你的这个问题和 #166  是同一个问题，都是想要在标题下面显示文章简介，请看我的回复是否能够满足你需求 ，在 #166  问题的下面
