### ISSUE TITLE
配置的站点地图，url不是自己的域名

### ISSUE THREAD

**Issue by a506488043** [iissnan/hexo-theme-next#1651]
### Expected behavior (预期行为)

在文件里也添加了自己的域名，就是不现实。
http://www.saiita.cn/sitemap.xml

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Vincentqyw** [comment]
在站点配置文件的URL协商自己的域名就行，例如下面是我的：
**url: http://www.vincentqin.tech**
然后再重新生成部署就行了

**Comment by ivan-nginx** [comment]
@a506488043 if solved, close it please.

**Comment by a506488043** [comment]
已经解决了，百度教程不完善，在站点配置文件里有个url,设置自己的域名。
