### ISSUE TITLE
如何对post文档中的图像进行排版？

### ISSUE THREAD

**Issue by Vincentqyw** [iissnan/hexo-theme-next#1652]
### Expected behavior (预期行为)
用markdown写文档插入图片，可以实现一行有三幅图像这种效果？

### Actual behavior (实际行为)
图片一行只能有一张，无法实现上述layout

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔ 
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse ✔ 
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
[图片排版模式](https://neveryu.github.io/2016/11/11/hexo-next-three/#六、图片模式)

**Comment by ivan-nginx** [comment]
@Vincentqyw don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by cutelittleturtle** [comment]
I believe you can use this [fix](https://ehlxr.me/2016/08/30/%E4%BD%BF%E7%94%A8Hexo%E5%9F%BA%E4%BA%8EGitHub-Pages%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%EF%BC%88%E4%B8%89%EF%BC%89/#%E5%85%AB%E3%80%81%E5%9B%BE%E7%89%87%E6%A8%A1%E5%BC%8F) to arrange your pictures in post.
