### ISSUE TITLE
Tags are offcenter

### ISSUE THREAD

**Issue by KaitoKid** [iissnan/hexo-theme-next#1654]
### Expected behavior (预期行为)
Tags should be centered with a left margin against the bullet point

### Actual behavior (实际行为)
[Tags are off center](http://i.imgur.com/LTDpNON.png)

### Steps to reproduce the behavior (重现步骤)
Click on any tag.
i.e. https://kairuizeng.com/blog/tags/nodejs/

**Comment by ivan-nginx** [comment]
@KaitoKid what version u is used? On my [test site](http://test.almostover.ru/tags/TOC/) everything is fine with tags.

**Comment by KaitoKid** [comment]
@ivan-nginx Also using the latest version. Just saw your suggestion, looks like it fixed it. for now.

**Comment by ivan-nginx** [comment]
@KaitoKid it is fixed in 7c02491
If issue is resolved, close it, please.

**Comment by KaitoKid** [comment]
@ivan-nginx Fixed.
