### ISSUE TITLE
Highlight isn't working

### ISSUE THREAD

**Issue by KaitoKid** [iissnan/hexo-theme-next#1655]
### Expected behavior (预期行为)
Code should be highlighted

### Actual behavior (实际行为)
Everything is still grey

### Steps to reproduce the behavior (重现步骤)
Example [post](https://kairuizeng.com/blog/hexo-guide-to-make-static-websites/)

I can see that the figure for "highlight bash" exists in the HTML, but nothing's happening.

Highlight is enabled in the _config.yml for the blog, and I have selected 'night' in _config.yml for the theme.

**Comment by ivan-nginx** [comment]
@KaitoKid in [Install Hexo](https://kairuizeng.com/blog/hexo-guide-to-make-static-websites/#Install-Hexo) header it is highlighted. If you want appear highlight code language, u need to set it code, for example:
```
``` yml
```
Will be `yml` language highlight. [Highlight codes](https://almostover.ru/2016-07/hexo-highlight-code-styles/) u may find on my blog post.

**Comment by KaitoKid** [comment]
@ivan-nginx I set everything to 
````bash`
but I guess I will try some other stuff (inc custom ones). Thanks.

**Comment by ivan-nginx** [comment]
@KaitoKid bash/sh highlight template u may find in `node_modules/highlight.js/lib/languages/bash.js`.
My custom sh commands are:
```
    // Custom CentOS commands
    'sh cat ls ln cp mv chmod chown wget yum nano chkconfig service reboot sestatus date hwclock updatedb locate mkdir crontab tar zip unzip gunzip make logrotate arch ps ntpdate ntpq rpm tail mc hexo ' +

    // Custom MySQL commands
    'show connect alter ' +
```
And, of course, u may add there `git`, `hexo` and any things what u want.
