### ISSUE TITLE
百度分享打开用不了呢

### ISSUE THREAD

**Issue by ws1227** [iissnan/hexo-theme-next#1659]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by heqiang421** [comment]
应该是百度分享不支持https,我选择用jiathis

**Comment by ehlxr** [comment]
jiathis 也不支持 https 吧，[百度分享不支持Https的解决方案](https://github.com/hrwhisper/baiduSharehttps://github.com/hrwhisper/baiduShare)

**Comment by ivan-nginx** [comment]
@ws1227 don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Haocen** [comment]
The problem is about Baidu, a search engine similar with Google, this issue is inappropriate to open in this repository.

**Comment by ivan-nginx** [comment]
#1592.
