### ISSUE TITLE
home首页能不能做多一个可以隐身的标题目录，就像具体文章中的目录那样

### ISSUE THREAD

**Issue by suoba** [iissnan/hexo-theme-next#166]
首页加隐身的标题目录
好处：在很多篇文章的博客中能更加快速筛选出陌生人想看到的文章。其实就是效率提高了。

假设文章很多，比如100篇。
一.传统方案
1.1某个陌生人打开你网站博客首页
A方法：点击归档或者搜索，表面上来看是最快的，实际上呢，他们都永远都只能看到文章标题，无法预览内容，任何一篇文章都要点击进去才知道是不是自己想要看的，不是的话就退出/返回，然后重复循环以上动作，效率低的可怕，只有很熟悉的人才这么用，比如作者自己。
B方法：
从头到尾的看预览缩略简要，1页1页的翻看，一般每页10篇，最糟糕的时候要翻看看10页，翻看动作很浪费时间。这期间呢，还可能会点击某页某篇文章，之后返回继续。最糟糕的是，有人在第5页时候点了某篇文章，看了觉得不合适，有人会点返回后退，但也有人点首页，点了首页的人，必须将继续翻页，悲催的是必须一页一页的翻看，我就在其它地方遇到过。翻页是最大缺陷，当页面很多的时候，我在任何一页都只能看到当前页的内容，无法看到其它页面的，所预览到的内容比较少
二.无限瀑布流+缩略简要
C.如果所有人都是一直从头看到尾，那无疑是最省事的。但是。。。。
经常的是：某天看到某篇就中断了，过了两又有时间了，然后又从头看之前看到的，直到续上，这期间要重复看的数量取决于中断前看到的数量。
我的经验告诉我，当足够多的时候（取决于耐心程度），放弃是必然的。
无限流是表面是蛮好的，实际非常霸道和野蛮。
而且有些做得不好就更恶心了：比如在中间点击进去某篇文章，不看，点返回，好吧，大侠请从新来过，从头加载，而不是回到刚才点进去那里！！

三：目录+瀑布流+缩略简要
我以为这个才是更加效率的方案。
目录是一级筛选，简要是二级筛选，两者同在一页面。
但是根据iissnan说的“如果文章达到一定数量，这个标题目录还是需要分页。”
我不知道是不是技术上的问题，如果是 ，那么可以保留翻页，每个页面的最大长度应该就是，标题目录长度的极限。然后翻页，翻页后的标题目录当然也是要跟着变的了。

**Comment by wbprime** [comment]
可以加概要吧，首页显示目录有点违和吧

Best wishes from Elvis Wang <mail AT wbprime DOT me>

**Comment by suoba** [comment]
不违和啊，sublime text 还有缩略图呢。
我本意是不想要翻页，或者尽量少翻页，但是无限瀑布流也有问题，所以觉得要很长，但是却要容易定位，目录是选择。在交互上来说，翻页是最大缺陷，当页面很多的时候，我在任何一页都只能看到当前页的内容，无法看到其它页面的，所预览到的内容比较少（一般是10篇文章，多了就很长，更不方便）。大概就这样

**Comment by flashlab** [comment]
你需要做的是点击archive（归档）

**Comment by iissnan** [comment]
如果文章达到一定数量，这个标题目录还是需要分页。
@flashlab 好机智的小伙

**Comment by suoba** [comment]
我觉得我说的不是很清晰明白，所以重新写个
假设文章很多，比如100篇。
一.传统方案
1.1某个陌生人打开你网站博客首页
  A方法：点击归档或者搜索，表面上来看是最快的，实际上呢，他们都永远都只能看到文章标题，无法预览内容，任何一篇文章都要点击进去才知道是不是自己想要看的，不是的话就退出/返回，然后重复循环以上动作，效率低的可怕，只有很熟悉的人才这么用，比如作者自己。
  B方法：
  从头到尾的看预览缩略简要，1页1页的翻看，一般每页10篇，最糟糕的时候要翻看看10页，翻看动作很浪费时间。这期间呢，还可能会点击某页某篇文章，之后返回继续。最糟糕的是，有人在第5页时候点了某篇文章，看了觉得不合适，有人会点返回后退，但也有人点首页，点了首页的人，必须将继续翻页，悲催的是必须一页一页的翻看，我就在其它地方遇到过。
二.无限瀑布流+缩略简要
   C.如果所有人都是一直从头看到尾，那无疑是最省事的。但是。。。。
   经常的是：某天看到某篇就中断了，过了两又有时间了，然后又从头看之前看到的，直到续上，这期间要重复看的数量取决于中断前看到的数量。
   我的经验告诉我，当足够多的时候（取决于耐心程度），放弃是必然的。
   无限流是表面是蛮好的，实际非常霸道和野蛮。
   而且有些做得不好就更恶心了：比如在中间点击进去某篇文章，不看，点返回，好吧，大侠请从新来过，从头加载，而不是回到刚才点进去那里！！
   
三：目录+瀑布流+缩略简要
   我以为这个才是更加效率的方案。
   目录是一级筛选，简要是二级筛选，两者同在一页面。
   但是根据iissnan说的“如果文章达到一定数量，这个标题目录还是需要分页。”
   我不知道是不是技术上的问题，如果是 ，那么可以保留翻页，每个页面的最大长度应该就是，标题目录长度的极限。然后翻页，翻页后的标题目录当然也是要跟着变的了。
   
希望我能说清楚了。

**Comment by mingmings** [comment]
这是阅读体验了呢

**Comment by xirong** [comment]
你认为的“三” 目前是可以做到的，有两种方式。
1、 md文件的头部都有几个标记，其中一个是`description`，这个地方是可以来描述你整篇文章的简介，和你文章的内容不同，当然也是seo优化的地方，详情参考我的文章 http://ixirong.com/page/2/  《mac新手入门指南及常用工具及java编程环境搭建》和《科学上网神器shadowsocks使用方法及资料汇总
》这两篇都是这样子的。

你直接看我的原文吧，应就能理解了 ……
``` markdown
title: mac新手入门指南及常用工具及java编程环境搭建
date: 2015-03-19 20:45:17
tags: [mac,Java]
categories: 设备
description: 还记得刚买 mac book pro 的时候，啥都不会用，网上到处找资料，去查看怎么使用，mac常用快捷键、mac常用软件、mac java 环境搭建等等，中间走了不少弯路，也积累了不少资料，特此分享给大家，方便新手最好的mac入门指南！
keywords: mac 新手 , mac 环境搭建，mac 常用软件 ，mac java环境搭建
---

# OSX 系统介绍
OSX 是苹果公司为Mac系列产品开发的专属操作系统，基于 UNIX 系统，处处体现着简洁的宗旨。从 PC 过渡到 Mac，建议先了解 OS X 系统，你就会知道OS X 比 Windows …………
```

2、  标签的使用，标签之前的会展示在`标题`的下方，之后的会用`阅读全文`来区分开来 ，详情看我的首页 http://www.ixirong.com 《分布式实时日志系统环境搭建（二） flume 集群搭建/flume ng资料》就是这样子的 ，原markdown如下 ：
``` markdown 
……
学习flume ng的过程中还是遇到一些障碍的，可是在搜索引擎搜到的所有的flume的资料都是以前的`flume og`（flume orign generation），而这个不是我们要用的，我们要使用 `flume ng`（flume next generation），所以你要搜资料最好搜索 `flume ng` 来查找，详细看一下这两个版本的区别：<!-- more -->
 [Flume NG：Flume 发展史上的第一次革命](http://www.ibm.com/developerworks/cn/data/library/bd-1404flumerevolution/index.html) 
 讲的非常详细，包括 两代的变化，安装配置等，可以仔细阅读下。
```
