### ISSUE TITLE
怎么让部分标签变大呢

### ISSUE THREAD

**Issue by liwangmin** [iissnan/hexo-theme-next#1661]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
What do you mean? can you give more information about your question?

**Comment by liwangmin** [comment]
I see some labels on the tag menu larger than the others. Why is that?

**Comment by Acris** [comment]
Can you give a screenshot for this problem?

**Comment by liwangmin** [comment]
![tags](https://cloud.githubusercontent.com/assets/26134079/26250123/a5950f28-3cdb-11e7-99db-2bae226fc036.jpg)

like this，Why are some labels bigger than the others

**Comment by Acris** [comment]
https://github.com/iissnan/hexo-theme-next/blob/master/layout/page.swig#L27
The font size is generated randomly, you can re-run `hexo -g` if you want get a different result.

**Comment by liwangmin** [comment]
Thank you

**Comment by ivan-nginx** [comment]
> Tag's font size is generated randomly
@Acris not randomly. They generated by count of tags. When bigger one tag count — then font size will bigger too.
@liwangmin and, yes, this is not Next function.
