### ISSUE TITLE
添加leancloud统计阅读数，前端数量展示不对

### ISSUE THREAD

**Issue by njafei** [iissnan/hexo-theme-next#1662]
### Expected behavior (预期行为)

首页展示对应的次数，如：‘阅读次数10’
详情页展示对应的次数，如：‘阅读次数10’

### Actual behavior (实际行为)

查询leancloud的后台，发现数量是10

首页展示：‘阅读次数0’  次数全部为0
详情页展示：‘阅读次数’  次数不展示

### Steps to reproduce the behavior (重现步骤)
[首页](https://njafei.github.io/)

[详情页](https://njafei.github.io/2017/05/11/ES6%E4%B9%8B%E5%8F%98%E9%87%8F%E7%9A%84%E8%A7%A3%E6%9E%84%E8%B5%8B%E5%80%BC/)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

### Other Information (Like Browser, System, Screenshots)

MacOS Sierra
Chrome 浏览器

**Comment by calabash519** [comment]
可以看下这篇文章：[为NexT主题添加文章阅读量统计功能](https://notes.wanghao.work/2015-10-21-%E4%B8%BANexT%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD.html#%E9%85%8D%E7%BD%AELeanCloud)

**Comment by njafei** [comment]
@calabash519  就是根据这篇文章来的，但是有问题

**Comment by ivan-nginx** [comment]
@njafei don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by hezhipengzipp** [comment]
我也是集成了，但是阅读数量不显示
