### ISSUE TITLE
Bootstrap Callout  不支持 ```  希望修改一下

### ISSUE THREAD

**Issue by Stitch-Taotao** [iissnan/hexo-theme-next#1663]
### Expected behavior (预期行为)

![2017-05-12 6 24 33](https://cloud.githubusercontent.com/assets/26296915/25994390/4926743e-3740-11e7-8f6c-c6e6c6bfae49.png)

### Actual behavior (实际行为)

![2017-05-12 6 17 43](https://cloud.githubusercontent.com/assets/26296915/25994159/5b3db840-373f-11e7-9176-f3060eeadc4c.png)

### Steps to reproduce the behavior (重现步骤)

如果我的code 是以下形式的话，我的代码就可以拥有Bootstrap Callout的效果
 {% note primary %}
 {% codeblock %} 
 我的code 
{% endcodeblock %} 
{% endnote %}

但是如果是 下面的形式的话，就是未定义的行为了
{% note primary %}
\```
我的code
\```
{% endnote %}

现在我想要的是 希望代码块放在 **\```** 中也是可以执行的，因为这样更简单而且各个平台markdown的兼容性也很好，希望作者可以回复我。

**Comment by geekrainy** [comment]
这是 Hexo 的问题，在所有的标签插件中都会引起此问题。可以在 https://github.com/hexojs/hexo/issues/2400 找到问题的讨论及解决方案。

**Comment by ivan-nginx** [comment]
@Stitch-Taotao don't understand u, write in English if not solved. If solved, close it please. Thank's!
