### ISSUE TITLE
你好，我想问一下侧边栏怎么改成半透明

### ISSUE THREAD

**Issue by lijxug** [iissnan/hexo-theme-next#1665]
我想把Pisces各个区块改成半透明的，对文章、主菜单的背景颜色改动都成功了，只剩下sidebar有一些小问题。
### Expected behavior (预期行为)
我希望侧边栏无论是拖动与否都是半透明背景

### Actual behavior (实际行为)
实际上只有在拖动以后才转成半透明的

之前我都是自己瞎蒙。。其实我还是不知道侧边栏的背景颜色具体是在哪里定义的，望告知~

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  -  Master

NexT Scheme:
  -  Pisces

网络有些问题。。图传不上去

**Comment by Acris** [comment]
aside#sidebar
![next.png](https://ooo.0o0.ooo/2017/05/18/591cf5831ddbe.png)

**Comment by lijxug** [comment]
找到了，已解决，感谢！

**Comment by Holmeyoung** [comment]
老哥，怎么弄得呀，我和你用的主题一样，也在改呢
