### ISSUE TITLE
windows chrome显示不完全

### ISSUE THREAD

**Issue by iczbl** [iissnan/hexo-theme-next#167]
windows chrome部分内容显示不出来，如图

![png1] (https://i.imgur.com/sQfHHVa.png)

**Comment by xiangfly11** [comment]
是不是你的chrome版本问题，我的可以显示。

**Comment by geekrainy** [comment]
lato字体问题，去除即可。

**Comment by iczbl** [comment]
@xiangfly11 win7 32位 chrome `42.0.2311.152 m`
@geekrainy 是的，注释掉lato字体就可以了，按默认设置的话无法显示
