### ISSUE TITLE
搜索卡顿

### ISSUE THREAD

**Issue by VeiZhang** [iissnan/hexo-theme-next#1670]
### Expected behavior (预期行为)
点击侧栏搜索，弹出搜索框；搜索文章，流畅输入，快速查询结果

### Actual behavior (实际行为)
有时打不开搜索框；搜索文章，输入很卡顿

### Steps to reproduce the behavior (重现步骤)
点击主页侧栏的搜索，有时打不开搜索框；在搜索弹出框输入，非常卡顿

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release   ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces   ✔

### Other Information (Like Browser, System, Screenshots)
* 打不开搜索框
![qq 20170517092239](https://cloud.githubusercontent.com/assets/19425616/26134646/96af75de-3ae2-11e7-9dbd-39198be5e394.png "打不开搜索框")

* 输入卡顿
![qq 20170517092250](https://cloud.githubusercontent.com/assets/19425616/26134647/96b623f2-3ae2-11e7-8f5c-dcfb2d65889a.png "输入卡顿")

**Comment by Acris** [comment]
Try to use master branch, this bug should be fixed.
