### ISSUE TITLE
重定向问题

### ISSUE THREAD

**Issue by lugavin** [iissnan/hexo-theme-next#1671]
当我打开 [https://lugavin.github.io/](https://lugavin.github.io/) 点击左侧**归档**菜单时浏览器跳到 [http://lugavin.github.io/archives/](http://lugavin.github.io/archives/) 显示无法打开网页，而直接输入 [https://lugavin.github.io/archives/](https://lugavin.github.io/archives/)却可正常访问。

### Expected behavior (预期行为)
[https://lugavin.github.io/archives/](https://lugavin.github.io/archives/)

### Actual behavior (实际行为)
[http://lugavin.github.io/archives/](http://lugavin.github.io/archives/)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
I can't reproduce it, you can check your hexo configuration file, make sure the `url` is correct.

**Comment by lugavin** [comment]
今天居然又好了，真的很奇怪。

**Comment by Acris** [comment]
Closed, reopen it when needed.
