### ISSUE TITLE
手机浏览器点击搜索没有反应

### ISSUE THREAD

**Issue by romypan** [iissnan/hexo-theme-next#1673]
### Expected behavior (预期行为)
手机浏览器上浏览搜索流畅正常

### Actual behavior (实际行为)
手机浏览器点击搜索没有反应，无弹框

### Steps to reproduce the behavior (重现步骤)
手机浏览器点击搜索没有反应，无弹框

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔ 
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔ 

### Other Information (Like Browser, System, Screenshots)
手机浏览器点击搜索没有反应，无弹框

![96af75de-3ae2-11e7-9dbd-39198be5e394](https://cloud.githubusercontent.com/assets/23111440/26275201/16a8a6d6-3d8e-11e7-965f-8c24c9a320fd.png)

**Comment by Keldos-Li** [comment]
有时可以有时不行，，我是大概要在“搜索"上按0.5秒左右再松手，看运气搜索框会不会弹出来

**Comment by flashlab** [comment]
用的什么搜索？有没有例子？

**Comment by Keldos-Li** [comment]
升到nexT 5.1.1似乎能解决？

**Comment by ivan-nginx** [comment]
Solved?
