### ISSUE TITLE
Bootstrap callout 任意两个完整的{% note classname %}{% endnote %}之间内容渲染出错。

### ISSUE THREAD

**Issue by liuzhenrain** [iissnan/hexo-theme-next#1674]
### Expected behavior (预期行为)
![预期](http://oq8caemg8.bkt.clouddn.com/12.png)
预想能够正常渲染
### Actual behavior (实际行为)
![预期](http://oq8caemg8.bkt.clouddn.com/13.png)
结果，在danger和info之间所有的 Markdown 语法均不能正常渲染
### Steps to reproduce the behavior (重现步骤)

使用两个完整输入的{% note info %} {% endnote %} （任意tag都一样，不一定为info） 之间添加的任何 Markdown 语法均无法正常的渲染。

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by liuzhenrain** [comment]
如果在两个{% note info %}{% endnote %}之间插入 {% note label %}{% endnote %}，或者 {% codeblock %}{% endcodeblock %} 则两个{% note info %}{% endnote %}之间的Markdown语法能够正常渲染。
但很明显这不是我们想要的结果。
![image](https://cloud.githubusercontent.com/assets/6817052/26276025/db67dfd4-3da0-11e7-87f7-4abdd5a4b819.png)
结果:
![image](https://cloud.githubusercontent.com/assets/6817052/26276029/e80a140a-3da0-11e7-9033-154dfd75412b.png)

**Comment by zhuzhuyule** [comment]
这个是 定义`{% node%}`...`{% endnode%}` 标签导致的，我查看了 [这里](https://github.com/iissnan/hexo-theme-next/blob/master/scripts/tags/note.js#L7), 
本行内 `content` 内容到下一个标签才会结束，感觉是bug，

-----

我的解决方案：**重写** *node* **标签** 越过这个bug
代码：https://github.com/zhuzhuyule/useful-code/tree/master/src/hexo-tags
其中：
[label.js](https://github.com/zhuzhuyule/useful-code/blob/master/src/hexo-tags/label.js)  path:(hexoRoot)\themes\next\scripts\tags\label.js

[lable.swig](https://github.com/zhuzhuyule/useful-code/blob/master/src/hexo-tags/label.styl) path:(hexoRoot)\themes\next\source\css\_custom\label.styl

**Comment by ivan-nginx** [comment]
@liuzhenrain what's the question? I don't understand.

**Comment by ivan-nginx** [comment]
@liuzhenrain if issue resolved, close it please.

**Comment by liuzhenrain** [comment]
@zhuzhuyule 如果使用超过一个note 标签，那么必须要使用如下的方式才能正常使用
```
{% note danger %}
note danger, note danger, note danger
note danger, note danger, note danger
note danger, note danger, note danger
{% endnote %}
```

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/pull/4161
