### ISSUE TITLE
怎么在前面加一个小图标呢？如图

### ISSUE THREAD

**Issue by shenzekun** [iissnan/hexo-theme-next#1677]
### Expected behavior (预期行为)
![](https://cloud.githubusercontent.com/assets/21151080/26332623/6cd98fae-3f8a-11e7-94c3-c34febe4127d.png)

### Actual behavior (实际行为)

![](https://cloud.githubusercontent.com/assets/21151080/26332632/80f18a14-3f8a-11e7-9d9c-c55b2ad94781.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by zhuzhuyule** [comment]
you can go to [**This**](http://www.fontawesome.com.cn/faicons/), Find your want !
```markdown
 <i class="fa fa-external-link"></i>
```

**Comment by shenzekun** [comment]
@zhuzhuyule  Where can I add it？

**Comment by zhuzhuyule** [comment]
For Example：
```
Copy This Content
<i class="fa fa-calendar-o" aria-hidden="true"></i>发表于2017-5-25| <i class="fa fa-folder-o" aria-hidden="true"></i>分类于 工作
View effect
```
just copy ico code that you want to your post !
(click [Here ico](http://www.fontawesome.com.cn/faicons/#search) to [Here](http://www.fontawesome.com.cn/icons/folder-o/)) copy !

----

if you want to modify Title info, please see [here](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/post.swig#L25-L247) !

**Comment by shenzekun** [comment]
very good ，thank you @zhuzhuyule
