### ISSUE TITLE
Bootstrap callout 之间的内容无法渲染..

### ISSUE THREAD

**Issue by MeeSong** [iissnan/hexo-theme-next#1678]
### Expected behavior (预期行为)
没有出现预期行为...

### Actual behavior (实际行为)

整个文本是这样

```
{% note success %}
同步是一个对于 Windows 应用程序可见的属性, 它指的是, 一个线程通过等待某个对象从一种状态改成成另一种状态, 从而达到同步其执行过程的能力.
一个线程可以通过执行体的作业, 进程, 线程, 文件, 事件, 信号量, 互斥体和定时器对象来进行同步.其他的执行体对象不支持同步.

一个对象支持同步的能力基于以下三种可能性:

* 该执行体对象是一个分发器对象的包装对象, 它包含一个分发器头; 分发器头是一个内核结构.  
* 对象类型的创建者请求一个默认对象, 而对象管理器提供默认对象.  
* 执行体对象有一个内嵌的分发器对象, 比如在对象体内部某处的一个事件; 该对象呢的所有者在注册此对象类型时向对象管理器提供了此内嵌对象的偏移量.
{% endnote %}
```

生成之后是这样...

![boostrap](https://cloud.githubusercontent.com/assets/6848759/26349274/d6f7f4c8-3fe1-11e7-9cc9-723dd5628969.jpg)

对..没有了任何格式(包括换行和空格)...没有任何渲染...

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
 ✔  Mist
  -  Pisces

**Comment by MeeSong** [comment]
我发现... 把这段内容放到最下面就能正常渲染...我需要提供原始md文件么?

**Comment by ivan-nginx** [comment]
@MeeSong #1674. If solved. close it.

**Comment by MeeSong** [comment]
并没有解决.. 可以到我的文章来查看现象..
[Object Management](https://meesong.github.io/StaticBlog/2017/Windows-kernel-learning/4-Object-Management/#对象头中的域)

**Comment by ivan-nginx** [comment]
No need to write this in 1 line, like that:
```
{% note danger %}note danger, note danger, note danger{% endnote %}
```
Need to write it like u may see in note documentation link (#1160), like this:
```
{% note danger %}
note danger, note danger, note danger
{% endnote %}
```

**Comment by MeeSong** [comment]
在 md 文件里面, 我就是按照正确的方式来写的.

就像这样
![boostrip-md](https://cloud.githubusercontent.com/assets/6848759/26496299/7be5ea02-4259-11e7-9316-16f70dd8f545.jpg)


然而, 实际生成了这样...
![boostrip](https://cloud.githubusercontent.com/assets/6848759/26496263/5eb48f60-4259-11e7-8472-f2a9174218a0.jpg)

**Comment by ivan-nginx** [comment]
@MeeSong i don't understand in what error is. Write in English, please if u want to resolve this issue.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/hexojs/hexo/pull/4161
