### ISSUE TITLE
本地查看发布后不一样

### ISSUE THREAD

**Issue by alfredtofu** [iissnan/hexo-theme-next#168]
本地看是这样的：
![qq 20150519004339](https://cloud.githubusercontent.com/assets/1112801/7685386/7b60c00a-fdc0-11e4-8ec7-a4ea76971fcd.jpg)

发布到github上是这样的：
![qq 20150519004350](https://cloud.githubusercontent.com/assets/1112801/7685435/e28c38d6-fdc0-11e4-8799-7af5379ca1e0.jpg)

然后我对比过他们的html文件，除了域名不一样，其他完全一样。。
文件在这里：http://pan.baidu.com/s/1o6zHRYy

我搞不懂为什么会这样，求解救。。我的博客地址是：http://cvmarcher.com/

**Comment by fewtime** [comment]
你强制刷新(Ctrl+F5)一下，我这边显示的是Mise主题的

**Comment by xiangfly11** [comment]
我觉得可能是github服务器的问题，你刚上传部署在github服务器上并没有进行相应的改变。我这里显示的也是mist主题。

**Comment by alfredtofu** [comment]
谢大家，后来我把node_modules, .deploy_git都删掉了，然后重新install一次就没事了，好奇怪..

**Comment by Brutustao** [comment]
我也遇到这个问题了

**Comment by benjamin603** [comment]
同样遇到这个问题了

**Comment by Brutustao** [comment]
> 同样遇到这个问题
   @benjamin603 
   1自定义域名的话 ,本地推送到githup中不能将CNAME上传博客是显示不了的，要将 CNAME 文件放在source文件中。
   2 把浏览器最近的历史纪录删了，再刷新。

**Comment by benjamin603** [comment]
我这边解决了，原因是我本地文件夹branch的问题。学习了3个小时git基础知识后搞定了😂

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 边涛 <notifications@github.com>
发送时间: Monday, November 23, 2020 7:45:10 PM
收件人: iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>
抄送: Benjamin Jowe <benjamin.jowe@gmail.com>; Mention <mention@noreply.github.com>
主题: Re: [iissnan/hexo-theme-next] 本地查看发布后不一样 (#168)


同样遇到这个问题
@benjamin603<https://github.com/benjamin603>
1自定义域名的话 ,本地推送到githup中不能将CNAME上传博客是显示不了的，要将 CNAME 文件放在source文件中。
2 把浏览器最近的历史纪录删了，再刷新。
