### ISSUE TITLE
请教如何跳转到指定行

### ISSUE THREAD

**Issue by Jan9th** [iissnan/hexo-theme-next#1681]
不知道是否可以跳转到指定行，我看其他地方可以实现。[比如说这个](http://stackoverflow.com/a/30334668/7161403)

**Comment by NoahDragon** [comment]
添加锚点即可http://blog.csdn.net/yangkai_hudong/article/details/14163483

**Comment by Jan9th** [comment]
感谢，已经完成了相同页面跳转，但是像这种跳转到别人的页面是如何解决的（或者如何知道别人的锚点是什么）？

**Comment by NoahDragon** [comment]
这样的锚点一般是在share的时候才会用到，或者如Hexo主页在有锚点处会特殊显示。
![image](https://cloud.githubusercontent.com/assets/5704064/26501585/0d4e3456-4208-11e7-8a1b-4362cb4b9e06.png)

最后可以通过developer tool来看是否有锚点：
![image](https://cloud.githubusercontent.com/assets/5704064/26501706/560457a2-4208-11e7-853d-467ead7423d0.png)

**Comment by Jan9th** [comment]
多谢，请问 developer tool 是 chrome 插件，还是浏览器调试工具

**Comment by ivan-nginx** [comment]
@Jan9th don't understand u, write in English if not solved. If solved, close it please. Thank's!
