### ISSUE TITLE
Need to remove unnecessary line breaks

### ISSUE THREAD

**Issue by online** [iissnan/hexo-theme-next#1683]
### Expected behavior (预期行为)
There should be no unnecessary line breaks.

### Actual behavior (实际行为)
In fact, there are extra line breaks.

### Steps to reproduce the behavior (重现步骤)
See the **screenshot** attached to this issue.

NexT Version:

  - ✔ Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  - ✔ Pisces

### Other Information (Like Browser, System, Screenshots)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

![25 05 2017_10h57m28s](https://cloud.githubusercontent.com/assets/722881/26441548/8bcbe744-4139-11e7-995e-960f21c0181f.png)

**Comment by zhuzhuyule** [comment]
you can use  gulp-htmlclean and gulp-htmlmin to solve your problem ！
```
npm install gulp-htmlmin --save-dev
npm install gulp-htmlclean --save-dev
```
+ `gulp-htmlmin`--压缩html，可以压缩页面javascript、css，去除页面空格、注释，删除多余属性等操作[文档](https://github.com/jonschlinkert/gulp-htmlmin)
+ `gulp-htmlclean`-- null

config
```
var gulp = require('gulp');
var htmlmin = require('gulp-htmlmin');
var htmlclean = require('gulp-htmlclean');
// 
gulp.task('minify-html', function() {
  return gulp.src('./public/**/*.html')
  .pipe(htmlclean())
  .pipe(htmlmin({
    removeComments: true,
    minifyJS: true,
    minifyCSS: true,
    minifyURLs: true,
  }))
  .pipe(gulp.dest('./public'))
});
// 默认任务
gulp.task('default', [
  'minify-html'
]);
```

**Comment by Neveryu** [comment]
good idea

**Comment by ivan-nginx** [comment]
HTML minification plugins may help in this. Also, this is not big problem with this line breaks and search engines do not see this. So, no need to do this for now, need to do other great and usable things instead this.
