### ISSUE TITLE
The 	statistics of tags and categories  include drafts post !

### ISSUE THREAD

**Issue by zhuzhuyule** [iissnan/hexo-theme-next#1685]
### Expected behavior (预期行为)
I just want the tags and categories include my post article !

### Actual behavior (实际行为)
the tags and categories include all article that include drafts post !

### Steps to reproduce the behavior (重现步骤)

new some drafts and include much tags and categories, then see the "tags" and "categories"!

**Comment by ivan-nginx** [comment]
Affermative, need to fix it.

**Comment by ivan-nginx** [comment]
Fixed in NexT v6 [here](https://github.com/theme-next/hexo-theme-next/pull/42).
