### ISSUE TITLE
Muse 主题文章详情页目录导航点击无效，文章不居中

### ISSUE THREAD

**Issue by suerb** [iissnan/hexo-theme-next#1686]
### Actual behavior (实际行为)
Muse 文章详情页，有以下问题：

1. 默认打开侧栏，文章会被顶到左边，点击一张图片后，文章重新居中，页面强烈跳动；
2. 侧栏的目录导航，点击无反应，是否应该跳转至相应的 heading？

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔  
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse ✔  
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)

Chrome
macOS

**Comment by ivan-nginx** [comment]
@suerb in English please.
