### ISSUE TITLE
How to translate Disqus counter word (Comments)?

### ISSUE THREAD

**Issue by online** [iissnan/hexo-theme-next#1687]
### Expected behavior (预期行为)
The word "Comments" should be translated into Russian.

### Actual behavior (实际行为)
There is no translation for the word "Comments".

### Steps to reproduce the behavior (重现步骤)
See the **screenshot** attached to this issue.

NexT Version:

  - ✔ Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  - ✔ Pisces

### Other Information (Like Browser, System, Screenshots)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

![28 05 2017_12h13m21s](https://cloud.githubusercontent.com/assets/722881/26527580/4a610bf0-439f-11e7-963d-e02e9570b2b2.png)

**Comment by ivan-nginx** [comment]
@online в самом дискусе вроде как настраивается, глянь там.
***
Если нет, то пробуй вместо дискуса — Hypercomments. Они намного лучше, но у HC только лишь 1 недостаток: ограничение 1 сайт и оп. кол-во запросов в месяц. Но для обычного блога — с головой хватает бесплатной версии. На моём блоге стоит HC, к слову.

**Comment by online** [comment]
@ivan-nginx, спасибо, теперь разобрался ;-) / Thanks, now I understand.
