### ISSUE TITLE
标签页和分类页的标题和圆点挤在一起了

### ISSUE THREAD

**Issue by YorksonChang** [iissnan/hexo-theme-next#1688]
在next主题中标签页和分类页的标题和圆点挤在一起了

![image](https://cloud.githubusercontent.com/assets/13660547/26528045/2069cfd2-43d4-11e7-9707-24eb6c48cd24.png)

![image](https://cloud.githubusercontent.com/assets/13660547/26528057/4db84f18-43d4-11e7-8701-7a6c05b75989.png)

有人知道是什么原因吗

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  ✔All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
Chrome、Safari
Mac OSX 10.12

**Comment by fangdc** [comment]
我也是出现了这个问题，你的问题解决了没

**Comment by angrySquirrel** [comment]
https://github.com/iissnan/hexo-theme-next/commit/7c02491dec76399bf21ea103e75d1a033950a1b3

**Comment by YorksonChang** [comment]
@angrySquirrel  that works，thx
