### ISSUE TITLE
404.html  is missing when deployed.md

### ISSUE THREAD

**Issue by starkey-zh** [iissnan/hexo-theme-next#169]
create a 404.html as [you said](https://github.com/xirong/hexo-theme-next/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%A2%9E%E5%8A%A0%E8%85%BE%E8%AE%AF%E5%85%AC%E7%9B%8A404%E9%A1%B5%E9%9D%A2), and work good in local, but after `hexo clean ,hexo d -g`, the 404.html was missing

**Comment by iissnan** [comment]
`hexo clean` will delete the `public` directory and generate a new one, so the `404.html` will be deleted.

Please put the `404.html` into theme's `source` directory.

**Comment by xirong** [comment]
just as iissnan said , `hexo generate` will also delete the `public` directory . I have created a `cp404.sh` , which is `cp 404.html  public/ ` , before you do `hexo deploy` , just do `sh cp404.sh` first .

**Comment by iissnan** [comment]
Close this issue cause there is no any updates follow up, please reopen it if you still have any questions.
