### ISSUE TITLE
某一categories或tags的页面，时间轴显示有问题

### ISSUE THREAD

**Issue by reuixiy** [iissnan/hexo-theme-next#1690]
### Expected behavior (预期行为)
某一<i>categories</i>或<i>tags</i>的页面，时间轴显示如果和<i>archives</i>页面一致就好了:laughing:
A page of one of the <i>categories</i> or <i>tags</i>, and it could be better if the timeline display is consistent with the <i>archives</i> page. :laughing:
### Example (例子)
  1.https://reuixiy.github.io/categories/beautiful/
  2.https://reuixiy.github.io/tags/share/
  3.https://reuixiy.github.io/archives/
如果1和2的时间轴显示如3，那么是多好:stuck_out_tongue_closed_eyes:
How good it is if the timeline of 1 and 2 is shown like 3! :stuck_out_tongue_closed_eyes:
### One more issue (另)
![issue](https://yixiuer.oss-cn-shanghai.aliyuncs.com/Picture/issue.jpg)
Unsightly:joy:

**Comment by aixiu** [comment]
https://github.com/iissnan/hexo-theme-next/commit/7c02491dec76399bf21ea103e75d1a033950a1b3
这里有解决办法！

**Comment by reuixiy** [comment]
@aixiu :grin:谢谢，小白刚接触GitHub，第一次提issue，想不到效率这么高！

小白还有个问题，就是怎么更改，能让某一个categories或tags的页面的时间轴（<b>无年份</b>），显示和archives页面的时间轴（<b>有年份</b>）一样，这是这个issue的重点:joy:
