### ISSUE TITLE
https://almostover.ru/   主页（index）文章列表块级化？

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1692]
### Expected behavior (预期行为)

主页（index）文章列表块级化？
### Actual behavior (实际行为)
默认所有文章在一个块！

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
![009](http://7u2ss1.com1.z0.glb.clouddn.com/009.png)
![008](http://7u2ss1.com1.z0.glb.clouddn.com/008.png)

**Comment by ivan-nginx** [comment]
@aixiu i will make separate scheme for this template. Need some time.

**Comment by aixiu** [comment]
Thank you for your attention!

**Comment by ivan-nginx** [comment]
@aixiu added new scheme Gemini in #1697 **PART 9**.
