### ISSUE TITLE
Next 5.1.1 版本 配置了gentie_productKey，网易云跟帖仍无法显示

### ISSUE THREAD

**Issue by GFigure** [iissnan/hexo-theme-next#1693]
主题文件配置了`gentie_productKey`跟贴产品密钥 ，然后`hexo clean && hexo g &&  hexo d ` 网页仍然不加载评论框。

试着查看` /themes/next/layout/_partials/comments.swig ` 中的代码，找到下面代码：
```
 {% elseif theme.gentie_productKey %}
      <div id="cloud-tie-wrapper" class="cloud-tie-wrapper"></div>
##添加web代码
{% elseif theme.youyan_uid %}
      <div id="uyan_frame"></div>

```

进入网易云跟贴，复制web代码添加，再试着`hexo clean && hexo g &&  hexo d ` ,就可以了。

`hexo s`不显示，是需要配置本地host文件：参照 [#1506](https://github.com/iissnan/hexo-theme-next/issues/1506)

**Comment by Cslove** [comment]
为什么还是不行啊 老是报这种错误：
yunsdk.kjZisxGp5HBN.28.js:3 Uncaught TypeError: Cannot read property 'contentWindow' of undefined

**Comment by Cslove** [comment]
而且没加web代码之前也都是报上面的错误，

**Comment by geekrainy** [comment]
请换用其它评论插件，云跟帖停止服务，已提交移除支持请求。https://github.com/iissnan/hexo-theme-next/pull/1745

**Comment by ivan-nginx** [comment]
@geekrainy issue may be closed? Gentie will not work from 2017 AUG, right?

**Comment by geekrainy** [comment]
@ivan-nginx Yep.
