### ISSUE TITLE
NexT.Mist主题栏高度设置

### ISSUE THREAD

**Issue by VIPyinzhiwei** [iissnan/hexo-theme-next#1696]
大家在切换主题风格 NexT.Mist 时，头部栏那一块背景色的高度怎么设置的？

**Comment by ivan-nginx** [comment]
@VIPyinzhiwei in English please.

**Comment by Kaiyh** [comment]
（导航栏吗？）找到 themes\next\source\css\_schemes\Mist\_header.styl 文件，在 .header 样式中添加 "height=xxx" 

you should add "height=..." in the style '.header', file : themes\next\source\css\_schemes\Mist\_header.styl

**Comment by Kaiyh** [comment]
（导航栏的高度吗？）找到 themes\next\source\css\_schemes\Mist_header.styl 文件，在 .header 样式中添加 "height=xxx"

you should add "height=..." in the style '.header', file : themes\next\source\css\_schemes\Mist_header.styl
