### ISSUE TITLE
hexo-algolia>=1.0.0 不能使用adminApiKey

### ISSUE THREAD

**Issue by qiyuey** [iissnan/hexo-theme-next#1698]
hexo-algolia 升级到 1.0.0 之后, 不能够使用 adminApiKey, 必须使用环境变量 HEXO_ALGOLIA_INDEXING_KEY 并设置 restricted key.

[具体操作](https://www.algolia.com/doc/guides/security/api-keys/)

[hexo-algolia说明](https://github.com/oncletom/hexo-algolia)

**Comment by FlyHan** [comment]
是的，需要参考hexo-algolia说明，主题手册需要更新一下
http://theme-next.iissnan.com/third-party-services.html#algolia-search

**Comment by Nameless13** [comment]
你们这些人 说也不说清楚 设置HEXO_ALGOLIA_INDEXING_KEY 和 restricted key A Search-Only API key

**Comment by ivan-nginx** [comment]
@qiyuey in English please.
