### ISSUE TITLE
添加友言uid没有用

### ISSUE THREAD

**Issue by Stevenclc** [iissnan/hexo-theme-next#1699]
在主题的config.yml里设置了友言的uid，但是无论在网页还是本地都没有用

**Comment by ivan-nginx** [comment]
@Stevenclc i think u need plugin with this function. See hexo.io/plugins.

**Comment by blastbao** [comment]
我也遇到这种情况了，用chrome浏览器F12抓一下包可以发现有标红的网络请求，发现是友言后台服务500错误。

**Comment by huayuanp** [comment]
+1也遇到了相同的情况~~~~~~

**Comment by franktly** [comment]
同样遇到这样的情况+1

**Comment by RickyWong33** [comment]
+1

**Comment by Acris** [comment]
检查下除了有言是否还设置了其他的评论系统？

**Comment by Stevenclc** [comment]
现在换成hypercomments了，效果挺好的，推荐大家使用，缺点是要用google账号登录

**Comment by zhkuo24** [comment]
@Stevenclc  hypercomments只是需要设置 id 吗，怎么设置了 id 还是不能用

**Comment by PaulLuv** [comment]
@Stevenclc hypercomments 配置 hypercomments_id还是不能用呢？ 还需要配置什么吗
@zhkuo24  你弄好了吗？

**Comment by hxlzpnyist** [comment]
是 因为 友言的请求是 http 的 ，github.io 都是 https的不允许 http的

**Comment by toodm** [comment]
同楼主问题   楼主你解决了吗

**Comment by thors-wang** [comment]
我也是遇到了这个问题啊，什么情况？解决了咩？

**Comment by SunOfHomeBoy** [comment]
就在今年，Uyan 关闭了自己的服务。详见[官网](www.uyan.cc)
