### ISSUE TITLE
next 是不是应建一个QQ群了？

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#170]
大家意下 如何？

**Comment by eurusd** [comment]
`群号：315452354`

**Comment by xirong** [comment]
qq群 理解还不如 issues，一来 qq群大家平日上班是没有多少时间关注的，工作比较忙，二来，一般群里面的问题都描述不清楚，别人很难理解，再者实在解决不了直接@相应的人，帮忙就是了

**Comment by allanzhang** [comment]
这家伙明显是做广告的么~

**Comment by iissnan** [comment]
我觉得 GitHub 的 issues 已经够用了哈 :smile:

**Comment by zhiyue** [comment]
没必要，详细的记录还是issues
