### ISSUE TITLE
置顶文章不置顶

### ISSUE THREAD

**Issue by willin** [iissnan/hexo-theme-next#1700]
### Expected behavior (预期行为)

<http://blog.airdwing.com>

### Actual behavior (实际行为)

置顶文章根据发布日期排在了非置顶文章的前面

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master

NexT Scheme:

  -  Pisces

### Other Information (Like Browser, System, Screenshots)

Github Pages

**Comment by ivan-nginx** [comment]
May u write in English, lpease. Don't understand what's the problem.

**Comment by willin** [comment]
Sticky  Post is not sticky.

**Comment by Acris** [comment]
https://github.com/iissnan/hexo-theme-next/issues/415#issuecomment-190665237

**Comment by willin** [comment]
@Acris bad practise.

**Comment by Acris** [comment]
@willin I just want to tell you Next didn't provide this function for now.

**Comment by ivan-nginx** [comment]
@willin can u show some example on it? I just don't use sticky posts and i'll try to fix it later, if i see what's the trouble.

**Comment by willin** [comment]
@ivan-nginx  http://blog.airdwing.com
source: https://github.com/AirDwing/AirDwing.github.io

**Comment by ivan-nginx** [comment]
@willin ok, and what post must be sticky?

**Comment by willin** [comment]
@ivan-nginx yes

**Comment by ivan-nginx** [comment]
@willin as @Acris talk above, for now Sticky posts is not provided by Next. @Iissnan do that function about 2 years ago and then remove js filter (https://github.com/iissnan/hexo-theme-next/blob/f4a08bffed0d7dbc0ab8ef643295f5f0c8b75453/scripts/filters/sticky.js) for sticky function. I don't know why he do it, but i think was bugs with standart Hexo rendering plugins or something else. 
If you want your post to stick, u may try to add this: https://github.com/iissnan/hexo-theme-next/issues/415#issuecomment-152378542.

If resolved, close it please. And thanks for wordcount plugin. :+1:

**Comment by stevenjoezhang** [comment]
Fixed in hexojs/hexo-generator-index#51
