### ISSUE TITLE
关于使用 tab 缩进产生的代码块样式

### ISSUE THREAD

**Issue by suerb** [iissnan/hexo-theme-next#1702]
我在 markdown 写作里使用的代码块是按 `tab` 键缩进来标记的，然后出来的效果是这样的？貌似没有任何 padding？

![image](https://cloud.githubusercontent.com/assets/3916752/26819633/5a3b959c-4ad2-11e7-9fa5-62328ad36bf2.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by zhuzhuyule** [comment]
页面不会展示 \t 的，手动加入`全角空格`或者`　`来当做tab效果！

**Comment by Acris** [comment]
建议使用 三个连续的`符号生成代码块。

**Comment by ivan-nginx** [comment]
@suerb if solved, close this please.
