### ISSUE TITLE
首页阅读次数

### ISSUE THREAD

**Issue by cpm828** [iissnan/hexo-theme-next#1703]
### Expected behavior (预期行为)
首页每条博客上显示阅读次数

### Actual behavior (实际行为)
无阅读次数

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)

如何和作者的博客一样在首页的每条博客后面带上阅读次数

**Comment by zhangnew** [comment]
https://notes.wanghao.work/2015-10-21-%E4%B8%BANexT%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E9%98%85%E8%AF%BB%E9%87%8F%E7%BB%9F%E8%AE%A1%E5%8A%9F%E8%83%BD.html#%E9%85%8D%E7%BD%AELeanCloud

http://theme-next.iissnan.com/third-party-services.html#analytics-busuanzi

**Comment by Acris** [comment]
是否已解决？

**Comment by cpm828** [comment]
没有
发自Pimi的iPhone7 Plus
在2017年07月03日 18:32，Acris Liu 写道： 是否已解决？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iissnan/hexo-theme-next","title":"iissnan/hexo-theme-next","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iissnan/hexo-theme-next"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Acris in #1703: 是否已解决？"}],"action":{"name":"View Issue","url":"https://github.com/iissnan/hexo-theme-next/issues/1703#issuecomment-312610765"}}}

**Comment by Acris** [comment]
检查一下主题配置文件中leancloud的配置是否正确：
https://github.com/iissnan/hexo-theme-next/blob/master/_config.yml#L416

**Comment by ivan-nginx** [comment]
@cpm828 issue is solved?

**Comment by chaixuhong** [comment]
阅读次数这个按next文档安装应该是没问题的，你的问题可能是 在leancloud设置了访问权限，就会出现阅读数不显示数字
