### ISSUE TITLE
canvas-nest效果怎么添加css媒体查询？

### ISSUE THREAD

**Issue by tanzby** [iissnan/hexo-theme-next#1706]
### Expected behavior (预期行为)
可以在某个文件里定义meta查询，实现手机上可以屏蔽效果而电脑上显示

### Actual behavior (实际行为)
*****

### Steps to reproduce the behavior (重现步骤)
*****

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes ✔
  -  Muse 
  -  Mist
  -  Pisces

**Comment by AlynxZhou** [comment]
这个效果是我加进去的好像…应该是在布局文件里加一个if判断？swig我是不怎么会的…哪个文件我也忘了…而且我不会判断手机和电脑…

**Comment by Neveryu** [comment]
https://neveryu.github.io/

**Comment by Acris** [comment]
可以移步canvas-nest的repo进行讨论。
https://github.com/hustcc/canvas-nest.js
