### ISSUE TITLE
将hexoblog链接在io仓库的index页面，结果不显示主题

### ISSUE THREAD

**Issue by sylviaxgj** [iissnan/hexo-theme-next#1708]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
看了你的博客，似乎问题已解决？

**Comment by ivan-nginx** [comment]
@sylviaxgj solved?
