### ISSUE TITLE
删除分类或标签后，分类以及标签的总个数没有相应减少啊！

### ISSUE THREAD

**Issue by Jason-Yuan** [iissnan/hexo-theme-next#171]

**Comment by iissnan** [comment]
尝试 `hexo clean` 以及删除 `.deploy_git` 目录后重新 generate 试试。

**Comment by zqdongxw** [comment]
@Jason-Yuan  请教一下，如何删除分类和标签？

**Comment by iissnan** [comment]
貌似没有快速批量删除的方法，或许可以写一个 Plugin 来支持（起码可以列出使用了某个特定的 分类/标签 的文章）

**Comment by iissnan** [comment]
@Jason-Yuan 参考 https://github.com/iissnan/hexo-theme-next/issues/188
