### ISSUE TITLE
package.json version 还是5.1.0

### ISSUE THREAD

**Issue by Lanseria** [iissnan/hexo-theme-next#1713]
Nothing

**Comment by Neveryu** [comment]
对呀，文档里面对于 disqus 的配置有5.1.1的

**Comment by Lanseria** [comment]
你们看懂他的写的，我只是建议作者将`package.json`中的数据改正确，他的版本的确已经到了5.1.1版本了，这个不用担心的，顺便说一句，`disqus`最近抽了，还是用那个韩国的，也就是 最下面那个评论配置（来必力）吧。
