### ISSUE TITLE
自定义主页问题

### ISSUE THREAD

**Issue by leiu** [iissnan/hexo-theme-next#1716]
自定义主页之后，跳转至默认主页；
问：新建的页面怎么渲染成默认主页的样式？

**Comment by Neveryu** [comment]
新建的页面怎么渲染成默认主页的样式？
:question:

**Comment by Acris** [comment]
意义不明，需要更加详细的描述。

**Comment by chong-w** [comment]
@Acris @leiu 的问题应该是如果按照 https://github.com/hexojs/hexo/issues/1077 自定义主页后，不再自动渲染生成主页。但是又想要原来渲染生成的主页作为网站的另外一个页面。 
比如   （ 首页    博客    归档    ）     这种结构

**Comment by ivan-nginx** [comment]
https://github.com/hexojs/hexo/issues/1077

***

Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.

***

Also,

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
