### ISSUE TITLE
Make hyper comment visible

### ISSUE THREAD

**Issue by Gabirel** [iissnan/hexo-theme-next#1718]
### Expected behavior (预期行为)
I want my comment area to be visible. Is there any way to do that?

@ivan-nginx I guess I need your help

### Actual behavior (实际行为)
Yes, my blog's background color is black
![image](https://user-images.githubusercontent.com/12933851/27217187-5beabebe-52ab-11e7-8df2-9ffd17d090ca.png)

![image](https://user-images.githubusercontent.com/12933851/27217244-a9ae02b4-52ab-11e7-8d42-f3e67074d4b9.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release  ✔
  -  Old version - 

NexT Scheme:
   My customized black scheme ✔

**Comment by Gabirel** [comment]
I'm sorry. I am so stupid that I forget importing customized stylus into `index.styl`.

I'm working on it.

**Comment by Gabirel** [comment]
![image](https://user-images.githubusercontent.com/12933851/27217436-67644f5c-52ac-11e7-8628-a2f62d0d9dbf.png)
Adding these should do the job.

Close it

**Comment by ivan-nginx** [comment]
@Gabirel can u make pull with this if this is bug?

**Comment by Gabirel** [comment]
@ivan-nginx 
I'm sorry that I can't do that.

Why?
> NexT Scheme:
> My customized black scheme ✔

So, this change doesn't work for your blog since your blog's bg color is `white`.
But, I just made another scheme called `Mala`, which this bg color is `black`. So, that's not a fatal bug for all users.

**Comment by Gabirel** [comment]
Oh, BTW, I can submit a Pull Request to this repo only if official black scheme comes out

**Comment by ivan-nginx** [comment]
Oh, i see. But there is global var for background color, right?
In /var/www/vhosts/_hexo-test/themes/next/source/css/_variables/custom.styl
```
$body-bg-color			= #ededed;
```

**Comment by ivan-nginx** [comment]
@Gabirel what scheme is this?

**Comment by Gabirel** [comment]
Yes, it's true.

However, I've make a lot of changes in my schemes. Not just changed the `$body-bg-color`.

I've re-designed based on @idhyt 's [hexo-theme-next](https://github.com/idhyt/hexo-theme-next). 
This repo has black themes which he calls it `Mala`(just like `Mist`, `Muse`, and `Pisces`). 

Since his blog's theme seems to never keep updated with upstream(hexo-next-theme), his theme of blog is too old. And also, too much I don't like  and not good for developers. So I based on latest version of hexo-next-theme and his Mala scheme to finish my `Mala` scheme.

Totally compatible with official `hexo-next-theme`. So, that's Mala scheme. You can see it in [here](https://github.com/Gabirel/next-geek).

**Comment by ivan-nginx** [comment]
@Gabirel ok, this is good. Many peoples want to use black scheme and i think need to pull request from you.

**Comment by Gabirel** [comment]
Umm...It's OK for me though. But, how do you do that? I've forked from [idhyt/hexo-theme-next](https://github.com/idhyt/hexo-theme-next). But his repo doesn't have any relationships with this repo(upstream). So do I.

Also, making a theme(including front-end stuff) isn't my  speciality. I don't have any warranty

**Comment by ivan-nginx** [comment]
@Gabirel yeah, this is called «work». Need to clone original repo and then need to compare all changes from your repo and find changes to «Mala» scheme. Afterthat — make pull.
For compare files need some programs/utilittes. If u use Windows, u can use program called «Beyond Compare». If u use Mac or Linux, u can find program like that. Something like «program to compare file changes». It's like compare on GitHub, but local program.

**Comment by Gabirel** [comment]
OK, if you want to merge Mala into it, please add a hyperlink to the original repo

**Comment by ivan-nginx** [comment]
@Gabirel ok, for now a have not enough time and try to do it later.
***
Thanks for discussion.
