### ISSUE TITLE
主题使用太多第三方框架了，并且，如果是用php语言那还用不了你的主题，耦合太深了

### ISSUE THREAD

**Issue by 5nn** [iissnan/hexo-theme-next#1719]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
使用太多框架的问题，后期会通过按需加载解决。
另外，这个本来就是Hexo的主题，无法适用于PHP。
