### ISSUE TITLE
scheme设置无效

### ISSUE THREAD

**Issue by rainbowbedrock** [iissnan/hexo-theme-next#1720]
### Expected behavior (预期行为)
scheme设置为mist本地测试有效，生成的网页是默认muse的scheme

### Actual behavior (实际行为)
生成的网页使用muse scheme而不是mist

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.1.1

  -  Master
  - ✔ Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  - ✔ Muse
  -  Mist
  -  Pisces

**Comment by msjbear** [comment]
我也遇到了同样的问题，@rainbowbedrock 请问你解决了吗

**Comment by xiligey** [comment]
我也遇到了同样的问题，@rainbowbedrock @msjbear

**Comment by Acris** [comment]
需要更详细的信息。
本地测试是指使用hexo server运行么？ 部署到服务器以后有没有尝试浏览器清空缓存？

**Comment by AlynxZhou** [comment]
按理说你hexo s用的就是hexo g的页面吧……是不是没有考虑CDN更新需要时间的……

**Comment by ivan-nginx** [comment]
@rainbowbedrock issue solved? If yes, close it. If no, write in English, please.

**Comment by yuzhenlei** [comment]
清除浏览器缓存或者多次hexo g

**Comment by WangLeto** [comment]
遇到了同样的问题，清缓存或是重新生成都没有其效果

**Comment by WangLeto** [comment]
我出现的问题是这样的：我的项目没有使用 git 部署，而是直接使用 `hexo g`，nginx 直接读取项目中的 public 文件夹，这种情况下修改 scheme 无效；但是使用 `nexo s`，预览出的效果是对的。切换回去后变成了默认的 scheme。

**Comment by yuzhenlei** [comment]
多次 **hexo g** 试试

**Comment by silloy** [comment]
遇到同样的情况求解

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
