### ISSUE TITLE
Next 5.1.1 can not see the sharing button after set jiathis: true(5.1.1版本Next设置jiathis为true无法显示分享按钮)

### ISSUE THREAD

**Issue by rangerzhou** [iissnan/hexo-theme-next#1727]
### Expected behavior (预期行为)
The bottom of the article can see the sharing button.(文章底部可以看到分享按钮)

### Actual behavior (实际行为)
The bottom of the article can not see the sharing button(文章底部看不到分享按钮)

### Steps to reproduce the behavior (重现步骤)
# Share
jiathis: true
# Warning: JiaThis does not support https.
#add_this_id:

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.1.1

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme: Mist
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
Chrome 57.0.2987.133, Win7, https://rangerzhou.github.io/

**Comment by Neveryu** [comment]
我的好像也是这样，本地可以，线上的不行

**Comment by rangerzhou** [comment]
可能是因为https://xxx.github.io是https开头的

**Comment by urzone** [comment]
jiathis 不支持 https
