### ISSUE TITLE
菜单没有选中状态

### ISSUE THREAD

**Issue by iiwf** [iissnan/hexo-theme-next#1728]
### Expected behavior (预期行为)
最新版本，使用 Pisces，点击侧边栏的菜单时，每个菜单都有选中状态
### Actual behavior (实际行为)
点击侧边栏的菜单时，只有首页有选中状态，其他菜单是没有选中状态的
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔ 

### Other Information (Like Browser, System, Screenshots)

![image](https://user-images.githubusercontent.com/28853200/27476841-caea6206-583c-11e7-9394-1930515c2bab.png)
![image](https://user-images.githubusercontent.com/28853200/27476857-e18afed0-583c-11e7-97d9-69db89677df6.png)

使用 v5.1.1 的稳定版本也无效；

**Comment by i-wangfan** [comment]
使用的是 Google Chrome 59.0.3071.104

**Comment by aixiu** [comment]
我也有同样的问题，没有当前页面，菜单的选中状态！

**Comment by iiwf** [comment]
目前暂时得到解决：

方法：使用 `Latest Release 5.11` 版本的Next主题就可以避免这个问题；

但是如果你要将博客挂载到二级目录下，例如`https://iiwf.github.io/blog/`,那么首页这个菜单将会没有选中效果，已经找到问题并解决；

在 `hexo/theme/next/source/js/src/utils.js` 中，找到 `addActiveClassToMenuItem` 方法，并修改即可；
