### ISSUE TITLE
/tags/index.html is missing 

### ISSUE THREAD

**Issue by iqiancheng** [iissnan/hexo-theme-next#173]
标签tags 无法自动生成 /tags/index.html

访问http://domain.com/tags/   404

**Comment by ArtinHuang** [comment]
自己新建一个试试？

**Comment by iissnan** [comment]
[创建标签云页面](https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E6%A0%87%E7%AD%BE%E4%BA%91%E9%A1%B5%E9%9D%A2)

**Comment by iqiancheng** [comment]
OK，
```
hexo new page "tags"
```
如何可以做出你的iissnan博客上的那种标签index页面效果呢？

**Comment by iissnan** [comment]
@iqiancheng NexT 只是调用了 Hexo 的 [tagcloud](http://hexo.io/docs/helpers.html#tagcloud) helper，并指定了一些配置。

```
tagcloud({min_font: 12, max_font: 30, amount: 200, color: true, start_color: '#ccc', end_color: '#111'})
```

指定字体，颜色值即可，这个部分是 hard-coded。
