### ISSUE TITLE
How to set empty key of social links and only show label icons on sidebar (如何设置侧边栏不显示社交链接名, 只显示图标)

### ISSUE THREAD

**Issue by wendingp** [iissnan/hexo-theme-next#1730]
How to show only social icons without the name of the social link on the sidebar, e.g., only show Facebook icon, without the name "Facebook" on the sidebar? (How to set empty key value for social links name?)

如何设置侧边栏上不显示社交链接网站的名字, 只要图标, 比如只要 Facebook 的图标, 而不要显示 "Facebook" +  Facebook 图标?

**Comment by zhuzhuyule** [comment]
you can change  [`sidebar.swig`](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/sidebar.swig#L116)
```
 <a href="{{ link }}" title="{{ name }}" target="_blank">{{ name }}</a>
```
to
```
 <a href="{{ link }}" title="{{ name }}" target="_blank"></a>
```

**Comment by ivan-nginx** [comment]
Need to add switch option here.

**Comment by wendingp** [comment]
@zhuzhuyule Then how to set the `_config.yml`?

**Comment by ivan-nginx** [comment]
@wendingp for now with standart metods it is not possible. You may use decision by @zhuzhuyule and it must work fine.

**Comment by ivan-nginx** [comment]
@wendingp alright, check PART 3 in #1697 pull, there is needed by you option.

**Comment by zhuzhuyule** [comment]
@wendingp if you modify  the [`sidebar.swig`](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/sidebar.swig#L116) file, don't about `_config.yml`.

Suggest: 
----
1. revert `sidebar.swig`
2. then  update theme 'NexT'
3. Modify `_config.yml`
```
social_icons:
  enable: true
  icons_only: true
  transition: false
```

like **PART 3** in [ #1697](https://github.com/iissnan/hexo-theme-next/pull/1697) pull
----
