### ISSUE TITLE
NexT的背景动画如何实现根据不同设备实现开启和关闭？

### ISSUE THREAD

**Issue by zipeijun** [iissnan/hexo-theme-next#1731]
NexT自带的一种背景动画很好玩，但是只能设置开启或关闭，这就导致一个问题，在桌面端的体验很好，但是在移动端就显得十分的渣乱。

想知道可不可以实现根据访问者使用设备情况，只在桌面端开启，移动端自动关闭？

如果可以，如何实现？

动画具体效果可以在桌面端和移动端分别打开我的[博客](https://zipeijun.github.io)体验

**Comment by Acris** [comment]
https://github.com/hustcc/canvas-nest.js

**Comment by zipeijun** [comment]
@Acris 原来是这样，之前没有了解清楚。十分感谢。

**Comment by ivan-nginx** [comment]
@zipeijun if solved, close it please.
