### ISSUE TITLE
侧边栏样式问题

### ISSUE THREAD

**Issue by seaheart** [iissnan/hexo-theme-next#1733]
### Expected behavior (预期行为)
看了示例的样式，比如说点了归档或者标签菜单，菜单按钮的右边都会有个点

### Actual behavior (实际行为)
我是昨天下的版本，没有出现这个情况，也就是没有点出来，只有刚进去的时候首页这个菜单有个点，切换到其他的菜单的时候就没有点了。

### Steps to reproduce the behavior (重现步骤)
我用控制台看了一下，好像是少了个叫menu-item-active的class，我没对js以及css做任何的修改，示例上有而我用npm clone下来的版本没有，求帮忙谢谢

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Acris** [comment]
https://github.com/iissnan/hexo-theme-next/blob/7ee84aaaf32c56acb69902d0a20d808b7321c189/_config.yml#L50

**Comment by Acris** [comment]
@seaheart master分支已经修复该问题。
