### ISSUE TITLE
网易云跟帖问题？？！

### ISSUE THREAD

**Issue by Cslove** [iissnan/hexo-theme-next#1734]
为什么设置了gentie_productKey，就是不显示，disqus下的shortname字段是填在disqus官网上注册的shortname吧，我填了这个shortname后是显示了disqus官网的那个评论风格，但不是网易云跟帖的风格啊，而且也必须的翻墙才能访问到disqus的评论显示，所以为什么设置了gentie_productKey的key，就是不显示网易云跟帖呢？另外我是直接hexo g -d部署到线上进行域名访问的，没在本地修改hosts访问，它就是不显示。。。版本 是5.1.1的

**Comment by Cslove** [comment]
可以了 犯了个低级错误  ，把disqus与网易云跟帖弄混了，把disqus的enable设为false就行了

**Comment by aesion** [comment]
网易云已经停止维护了，多说也挂了
