### ISSUE TITLE
custom.styl样式修改无法生效

### ISSUE THREAD

**Issue by dj940212** [iissnan/hexo-theme-next#1737]
我在/source/css/_custom/custom.styl中添加了样式 ，hexo server可以看到样式已经修改，但是hexo g -d 之后样式还是没有改变

**Comment by zhuzhuyule** [comment]
step1.hexo clean
step2.hexo s (检查是自己的更改是否成功)
step3.hexo g
step4.gulp (这是拓展项，需要安装gulp插件，如果没有，可以忽略)
step5.hexo d

**Comment by dj940212** [comment]
@zhuzhuyule 感谢， 问题已经解决，貌似执行复合命令hexo g -d不成功,分开执行hexo g  hexo d就没问题了

**Comment by Acris** [comment]
Closed.
