### ISSUE TITLE
canvas_nest 的 JS 源文件在哪里？我想给它的加载加个判断条件。

### ISSUE THREAD

**Issue by zipeijun** [iissnan/hexo-theme-next#1738]
NexT 的背景动画使用的是 canvas_nest，效果在桌面端很棒，但是移动端就不尽如人意留，我想知道 NexT 是在哪里加载 canvas_nest 的 JS 文本的，翻了一下主题没有找到。

我想给他加个 JS 的判断，只有检测到桌面端时才加载 canvas_nest，移动端不加载。

**Comment by Neveryu** [comment]
NexT主题有背景动画吗？没有明白你说的背景动画指的是哪个动画。
[我的博客](https://neveryu.github.io/) 中有自己加一个背景动画，而且实现了桌面端才有，移动端没有。
详见[我的博客更新日志](https://neveryu.github.io/weblog/)。

**Comment by Acris** [comment]
https://github.com/hustcc/canvas-nest.js

**Comment by ivan-nginx** [comment]
@zipeijun solved?

**Comment by zipeijun** [comment]
@ivan-nginx Sorry,not yet.

**Comment by zipeijun** [comment]
@Acris 我去看了，其实很简单，加个 JS 去判断用户是什么设备访问的即可。之所以回来这里是因为增加这个 JS 需要的是修改这个主题，而不是背景动画。

**Comment by Acris** [comment]
@zipeijun 欢迎提交PR

**Comment by zipeijun** [comment]
@Neveryu NexT 确实有背景动画，使用方法参见 [这里](http://theme-next.iissnan.com/theme-settings.html#use-bg-animation)。使用的是 [canvas-nest](https://github.com/hustcc/canvas-nest.js)。但只是简单添加了开关，并没有检测用户访问设备的能力。

我想做的是在加载 `canvas-nest` 的地方增加一段 JS 用于判断用户访问设备，根据设备选择性加载 `canvas-nest。`

另外，你的博客我看了，确实做到了选择性加载，我看见你是在 `\themes\next\layout\_layout.swing` 的 `</body>` 前添加的 `particle.js` 的引用就完成了。所以我想，这个 `particle.js` 可能自己就包含了判断条件吧。

但是，放在我这里好像就不太适用了，毕竟我用的 NexT 主题自带的，而你这边是自己引用的。我也去那个文件里面看了，没有看到自带的引用代码。

**Comment by AlynxZhou** [comment]
@zipeijun 如果我没猜错你的意图，你是想检测一下设备再处理canvas-nest对吧，在移动设备上就不加载了，具体检测设备的方法我也不是很清楚，但是这个canvas是我添加到NexT里面的，在模板里面判断加载的位置在`next/layout/_scripts/vendors.swig`，滚动到文件尾部能看见这样一条:
```
{% if theme.canvas_nest %}
  {% set js_vendors.canvas_nest  = 'canvas-nest/canvas-nest.min.js' %}
{% endif %}
```
所以如果你明白swig的语法又知道判断移动端的办法的话应该就好说了，那个js不建议修改因为我是从github直接拉下来的min版本，我就只能建议你在这里添加条件判断就应该能达到效果了，这里就是具体的加载判断的地方，没有必要修改其它位置。因为我既不熟悉swig也不知道怎么判断设备（猹喵）所以只能帮这些了……

**Comment by zipeijun** [comment]
@AlynxZhou 哈哈，可能是我的表达有问题，我就是你这个意思，想找到引入的位置。十分感谢，后面的我自己在研究研究。

**Comment by AlynxZhou** [comment]
@zipeijun 我觉得在js里修改是改不了的嘛，那样你得去canva_nest的repo去提issue了，这个功能应该是改模板的，应该帮忙的，我之前添加的时候也是找这个找了一段时间。

**Comment by Neveryu** [comment]
关于 移动端 还是 PC 的判断，我是这样实现的
[https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/layout/_layout.swig#L75-L107](https://github.com/Neveryu/Neveryu.github.io/blob/resource/themes/next/layout/_layout.swig#L75-L107)

**Comment by zipeijun** [comment]
@Neveryu 我看了一下。你应该是没用系统自带的效果，然后自己引用了背景动画，我研究看看能不能整合进 NexT。谢谢你的帮助。

**Comment by Neveryu** [comment]
@zipeijun 
当然可以呀，人家都告诉你了 canvas-nest 的引用位置：
```
{% if theme.canvas_nest %}
  {% set js_vendors.canvas_nest  = 'canvas-nest/canvas-nest.min.js' %}
{% endif %}
```
你再加上我的那个判断不就 O 了。

**Comment by zipeijun** [comment]
@Neveryu 说来惭愧，才开始学习代码，JS 还不是很熟悉，自己试着用几种方式添加，均无果。😭

**Comment by zipeijun** [comment]
@Neveryu 哈哈，是的，其实加上就可以了。说来惭愧，由于刚刚开始学习代码，对于 JS 也不是很熟悉，之前想着直接添加，无奈没有成功，所以刚才研究了一下，我把判断用 JS 做成独立一个文件，用链接才成功添加进去了，不知道是不是多此一举了。

`vendors.swig` 修改如下：
```
{% if theme.canvas_nest %}
  {% set js_vendors.canvas_nest  = 'canvas-nest/adaptive.js' %}
{% endif %}
```
`adaptive.js`内容如下：
```
  (function(){  
    var res = GetRequest();  
    var par = res['index'];  
    if(par!='gfan'){  
      var ua=navigator.userAgent.toLowerCase();  
      var contains=function (a, b){  
          if(a.indexOf(b)!=-1){return true;}  
      };   
      if((contains(ua,"android") && contains(ua,"mobile"))||(contains(ua,"android") && contains(ua,"mozilla"))||(contains(ua,"android") && contains(ua,"opera"))||contains(ua,"ucweb7")||contains(ua,"iphone")){
        return false;
      } else {
        $.getScript("lib/canvas-nest/canvas-nest.min.js");
      }
    }  
  })();  
  function GetRequest() {  
    var url = location.search;
    var theRequest = new Object();  
    if (url.indexOf("?") != -1) {  
      var str = url.substr(1);  
      strs = str.split("&");  
      for(var i = 0; i < strs.length; i ++) {  
        theRequest[strs[i].split("=")[0]]=unescape(strs[i].split("=")[1]);  
      }  
    }  
    return theRequest;  
  }
```
命名方面不知道这种组件有没有规范的名字，我就随便取了一个，哈哈哈（尴尬）
你要是觉得可以的话，我就提交 PR 了？

**Comment by AlynxZhou** [comment]
@zipeijun 我觉得这个判断放在swig里比较直观，放在js里的话一个是不直观另一个是有点麻烦，用cdn的话不知道还得怎么改。
