### ISSUE TITLE
也许需要精简一下结构？

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#1740]
### Expected behavior (预期行为)
感觉现在有点太大了…而且好多功能以前有的现在都不流行了，以及一些功能太小众的也在里面，三个scheme也许可以拆成三个theme这样代码阅读起来更好理解结构？不过是我个人的想法，不知道大家怎么想…

还有很不明白swig的主页面不是显示not maintained了吗…有没有必要迁移成其他模板语言呢…

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@AlynxZhou in English, please.

**Comment by AlynxZhou** [comment]
@ivan-nginx Sorry...I just mean that I think now NexT has too many functions and some of them are not used by the majority, maybe we need to remove some functions, and split three schemes into three themes? Because I used to hack some part of my blog, I find it's hard to remind which part I have changed and how I found it, because there are three schemes and a lot of files...It maybe easier to understand if split.
Plus I find the github repo of swig template language shows that swig is not maintained? Is that means we need to move to another kind of template language? Any future plan here?
However those are just my thoughts and I think final decision needs to be made by @iissnan , I just give some advice. And seems he hasn't showed up for a long time...
I am wondering that once I saw your reply under a Chinese pullrequest/issue, so I guess you use google translate to read Chinese sometimes? :-) Sorry for my forgeting using English for you to read, I'll remember though my English is not so good.

**Comment by ivan-nginx** [comment]
@AlynxZhou ok, it's alright. I use google translate sometimes, but sometimes it's translate that i don't understand what there meaning. Don't forget, my basic language is Russian and my English is not good to.

1. About migrate form `swig` to `ejs` or `jade` or else language - about this must think @iissnan. Of course, we all must to do decision about how it will be better, but for now, as i thing, `swig` is already fast and anyone may do what he's want: all variables is worked anywhere - in `.swig` files, in `.styl` files and in other basic and custom style variables too. But, if, for example, `ejs` something will gooder then `swig`, need to think about migrate. But don't remember, at the begining of this theme Next Vi ported this theme from `jade` (or `ejs`, i don't remember, but you may see this in first commits of repository) to `swig`, so, i think this was do not simply and was true causes for migrate to `swig`.
2. About split themes - don't understand what are u real meaning. U want to remove other themes and stay just 1 theme or what? In fact, themes - it's just misc CSS styles what used by `scheme` option in config. If 1 scheme is used, another scheme styles don't include in main compilation, but not always. We thing about it in our chat and if your interesting of maintenance Next theme, a can ask for Vi to invite you in working team. And about unused/unworked functions - need to talk too. But, my main idea for all of this: make all parts of styles and/or templates to load at compilation by conditional import by Next `_config.yml`.

**Comment by AlynxZhou** [comment]
@ivan-nginx I understand what you say, I am not meaning that stay just 1 theme, I mean make 3 schemes into 3 different themes may be better to maintain. I understand that final page will only contain 1 scheme codes and won't waste space. Why I think about that is sometimes I want to try to change some code and find it's hard to find the proper file. And in China sometimes it's hard to connect to github and clone a repo, smaller project is easier to clone. ;-p But I think maybe I need to read more and understand the structure clearly. So maybe there is no need to change.
And about maintainance, in fact I love this theme very much, and I'm happy to contribute to this theme, but I am lack of experience of front-end like this, and may not work well. I would like to learn more.
Plus I think this issue can be closed because I got answer to my problem, thanks to your work that make NexT better.

**Comment by ivan-nginx** [comment]
> Why I think about that is sometimes I want to try to change some code and find it's hard to find the proper file.
At the beginning of maintenance, i use local search in files content by needed strings. For example, u can see source code in browser and find `.any-class-name`, and afterthat u may find needed files by `.any-class-name` key from local search. Anyway, whole structure is basically build on variables and she's really difficult to understand it at beginning.
