### ISSUE TITLE
返回顶部按钮跟那个百分比怎么实现的？

### ISSUE THREAD

**Issue by Su9Tail** [iissnan/hexo-theme-next#1742]
因为看到作者博客有这个功能，但是在next的文档中并没有找到哪里有设置，可以告之吗？

**Comment by ivan-nginx** [comment]
```
  # Scroll percent label in b2t button
  scrollpercent: true
```
@Su9Tail if solved, close it please.

**Comment by Su9Tail** [comment]
@ivan-nginx It's perfect.thx.

**Comment by GIS90** [comment]
有没有插件，自带的好难用

**Comment by stevenjoezhang** [comment]
@GIS90 请使用新版：https://github.com/theme-next/hexo-theme-next
加上插件：https://github.com/jiangtj-lab/hexo-cake-moon-menu
