### ISSUE TITLE
打赏二维码图片问题

### ISSUE THREAD

**Issue by ctzld** [iissnan/hexo-theme-next#1743]
### Expected behavior (预期行为)
1 移动端二维码长按，出现保存图片，识别图片中二维码；
2 选择图片进入大图模式后，长按二维码任何地方出现识别图中二维码 ；
### Actual behavior (实际行为)
1 出现打开图片的js
2 选择图片进入大图模式后，只有长按中间才出现识别图中二维码，其他地方会显示JS 打开。

**Comment by ivan-nginx** [comment]
@ctzld in English please.

**Comment by liszd** [comment]
@ctzld 出现打开图片的js 是什么意思？
