### ISSUE TITLE
移动端归档页面：menu打开后被遮挡

### ISSUE THREAD

**Issue by linfengluo** [iissnan/hexo-theme-next#1744]
### Expected behavior (预期行为)
移动端——归档：
菜单栏打开后应该遮挡住归档页面

> .site-nav(z-index: 1)的层级没有.posts-collapse(z-index: 1010)的高，被遮挡
> 

### Actual behavior (实际行为)
归档页面遮挡住菜单

### Steps to reproduce the behavior (重现步骤)
移动端->进入归档页面->打开菜单

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@linfengluo in English please.

**Comment by Amethyst-564** [comment]
@linfengluo 
我个人的解决方法：
在`\next\source\css\_custom\custom.styl`文件中加入
```css
.site-nav-toggle {
  top: 0;
  transform:  translateY(78%);
}
```
78%这个数字自行修改，在我这边测试ipadmini2和oneplus 3t上显示位置和修改前差不多，不会遮挡

顺便艾特一下ivan如果他有更好的办法，就按他的来吧~

----------------
@ivan-nginx 
The meaning of this issue just as these pictures.
![](http://oklij0lk2.bkt.clouddn.com/17-8-27/76323451.jpg)
![](http://oklij0lk2.bkt.clouddn.com/17-8-27/69900410.jpg)
After click, the button is covered by the menu. 

My English is very poor,  sorrry..

**Comment by ivan-nginx** [comment]
@Amethyst-564 i see. I can't reproducte this, because i use standart browsers like Chrome and Firefox and all menu fine. What browser i can use to see this problem?

**Comment by Amethyst-564** [comment]
@ivan-nginx
Chrome of windowsx64, press f12 and select the Galaxy S5 could meet this problem. And in my Android phone(oneplus 3T), VIA browser( http://via.1year.cc/ ) can also see this problem.

**Comment by ivan-nginx** [comment]
@Amethyst-564 latest Chrome (CentOS 7x64), latest NexT master branch:
![image](https://user-images.githubusercontent.com/16944225/29752160-88f79fd2-8b61-11e7-8f68-670353c436a4.png)
Can't catch it anyway. What NexT version u use? What scheme? Need more info if u want fix on this.

**Comment by Amethyst-564** [comment]
@ivan-nginx 
I found the way to fix this.
edit `\next\source\css\_custom\custom.styl` and add these:
```css
.site-nav-toggle {
  top: 0;
  transform:  translateY(78%);
}
```
#### before:
- chrome
![](http://oklij0lk2.bkt.clouddn.com/17-8-28/82150378.jpg)
- firefox
![](http://oklij0lk2.bkt.clouddn.com/17-8-28/16614428.jpg)

#### after
- chrome
![](http://oklij0lk2.bkt.clouddn.com/17-8-28/2924080.jpg)
- firefox
![](http://oklij0lk2.bkt.clouddn.com/17-8-28/1765502.jpg)



--------------
chrome version: 60.0.3112.113 (stable x64)
firefox version: 55.0.3 (x64)
Next version: 5.1.0, scheme is Pisces.
hexo version: 3.2.2

maybe beacuse my next version is not latest

**Comment by ivan-nginx** [comment]
Maybe.
