### ISSUE TITLE
本地和部署的不太一样怎么回事

### ISSUE THREAD

**Issue by seadaughter** [iissnan/hexo-theme-next#1750]
### Expected behavior (预期行为)

![qq 20170709170534](https://user-images.githubusercontent.com/29600997/27992527-1ab9383c-64c9-11e7-924a-8ac7408bc753.png)

### Actual behavior (实际行为)
![qq 20170709170702](https://user-images.githubusercontent.com/29600997/27992531-263627c4-64c9-11e7-95b3-11f37dc21bde.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Bitzo** [comment]
我之前也是这样
hexo clean

**Comment by ivan-nginx** [comment]
@seadaughter solved?

**Comment by AlynxZhou** [comment]
hexo有时候缓存弄得不准，一般clean一下就可以强制刷新了。再有就是pages服务会有延迟。
