### ISSUE TITLE
想在移动端菜单栏右侧下显示类似sidebar，应该怎样实现

### ISSUE THREAD

**Issue by aboutimes** [iissnan/hexo-theme-next#1751]
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by flashlab** [comment]
可以参考#1717修改下

**Comment by reuixiy** [comment]
可以参考一下[这篇文章](https://leaferx.online/2017/02/05/EnableTOConMobile/)，也可以看一下[我的博客](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html)更改后的效果，反正我自己感觉不错😂😂😂

**Comment by aboutimes** [comment]
谢谢，移动端保留sidebar知道怎么设置了，不过体验并不好，所以还是自己写了个简单的about页面。

**Comment by reuixiy** [comment]
嗯，看个人喜好
