### ISSUE TITLE
如何设置在移动端不加背景壁纸？

### ISSUE THREAD

**Issue by swordspoet** [iissnan/hexo-theme-next#1753]
### Expected behavior (预期行为)
移动端不加载背景壁纸以加快访问速度

### Actual behavior (实际行为)
在手机浏览器中打开完全加载十分缓慢

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

**Comment by ivan-nginx** [comment]
@swordspoet in English please.
