### ISSUE TITLE
Algolia 搜索出来的文章，链接错误。点击无法进入

### ISSUE THREAD

**Issue by maxmeng93** [iissnan/hexo-theme-next#1754]
### Expected behavior (预期行为)
Algolia 搜索出来的链接缺少 `www`

### Actual behavior (实际行为)
我的域名是 `www.xxxxx.com`
Algolia 搜索出来的链接是 `xxxxx.com/2017/06/07/xxxxx`，因为缺少 `www`，所以点击搜索结果无法正确进入文章页面。
这种问题该怎么解决？

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@maxmeng93 in English please.

**Comment by bobo2334** [comment]
检查hexo的配置文件下你的域名设置是否正确
