### ISSUE TITLE
什么时候集成 Gitment 。。感觉这个挺好用的咧。

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1758]
### Expected behavior (预期行为)

希望集成 Gitment 
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by shenshanlaoyuan** [comment]
NexT主题集成Gitment 参考这篇文章[https://meesong.github.io/StaticBlog/2017/NexT+Gitment/](https://meesong.github.io/StaticBlog/2017/NexT+Gitment/)

**Comment by aixiu** [comment]
@shenshanlaoyuan 谢谢

**Comment by ivan-nginx** [comment]
@aixiu we do discussion about it in #1634. And if issue solved, don't remember to close it.

**Comment by aixiu** [comment]
@ivan-nginx thx
