### ISSUE TITLE
网易云跟帖8月1号也要关了。

### ISSUE THREAD

**Issue by a506488043** [iissnan/hexo-theme-next#1759]
### Expected behavior (预期行为)
网易云跟帖8月1号也要关了。
我的博客：www.saiita.cn

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
#1745.
