### ISSUE TITLE
不能跳转到404.html

### ISSUE THREAD

**Issue by yicheng-dolphin** [iissnan/hexo-theme-next#176]
在source目录下新建404.html页面，hexo generate后public目录下生成了404.html。
访问http://localhost:4000/404.html正常显示，访问类似http://localhost:4000/404/错误的网站，则html显示Cannot GET /404/。
请问是什么原因呢？

**Comment by iissnan** [comment]
服务器接收到一个目录的请求时（例如/domain/404/），通常会返回配置的默认页面（例如 index.html, default.html等），所以 http://localhost:4000/404/ 实际上访问的是 http://localhost:4000/404/index.html。

你可以将 404.html 改成 index.html，并放在 source/404/ 目录下，然后就可以通过 domain/404/ 来访问。

**Comment by yicheng-dolphin** [comment]
嗯，404只是一个例子，表示不存在的页面。我的意思是服务器没有将错误路径指向404.html。
ps：我是在站点的source目录下放置404页面的
thanks

**Comment by iissnan** [comment]
噢，不好意思，我理解错了。在 GitHub 上这样配置是可以的，示例看 @xirong 的站：http://www.ixirong.com/404/

**Comment by xirong** [comment]
@yicheng-dolphin  你的需求是什么，看了上面的，最终还是没有搞明白，你是想解决请求你的站点资源找不到后，跳转到自定义的404页面这个问题么？详情查看 https://help.github.com/articles/custom-404-pages/ ，只是我的404页面加入了腾讯公益的内容，如果说是这类问题，上面 @iissnan  的答案，我理解应该是说清楚了。

**Comment by mrsup** [comment]
看见有一篇教程里说：自定义404页面仅对绑定顶级域名的项目才起作用，GitHub默认分配的二级域名是不起作用的。引用地址：http://ibruce.info/2013/11/22/hexo-your-blog/

**Comment by iissnan** [comment]
@mrsup 自定义页面对于 用户或组织 仓库（user.github.io）是有效的，只有 [Project Pages](https://help.github.com/articles/user-organization-and-project-pages/#project-pages) 需要使用自定义域名。

@yicheng-dolphin Hexo本地服务器并没有对 404 做任何处理（不会跳转），GitHub 是在服务器端上做了配置。

**Comment by all-smile** [comment]
主要是404页面的格式
hexo new 404, 创建404页面，并在404/index.md文件中生成的内容清空并写入如下代码：
```md
---
permalink: /404.html
---
<!-- 下面可以随便写点什么（注意：上面的不要改动） -->
```
我放置了腾讯公益，并且在本地环境也是可以查看公益广告的

**Comment by LauArmy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
