### ISSUE TITLE
leancloud计数器不显示了。

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1760]
### Expected behavior (预期行为)
http://blog.ynxiu.com/
主题设置选项
```
leancloud_visitors:
  enable: true
```
这些都打开。leancloud网页设置没变，之前都能显示，这两天更新后发现不显示了。也更新到了#1724
### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Richard-Cao** [comment]
我也遇到了同样的问题。

报错信息：
us-api.leancloud.cn/1.1/classes/Counter Failed to load resource: the server responded  with a status of 401 ()

是不是哪里出了问题，访问401了

@iissnan

**Comment by myroid** [comment]
我的也是一样的，发现最新版本内置了阅读统计，我开始以为是和我原来配置的冲突了，移除原来自己添加的阅读统计后还是不显示

**Comment by ivan-nginx** [comment]
Join to discuss about this bug here: #1724.

P.S. Please, don't need to create new issues if u know about bug after pull update. Say it directly in pull comments.

**Comment by Richard-Cao** [comment]
我还是有这个问题，我用的最新的master分支。。
我看到作者revert了一个修正leancloud的分支，还没merge？ @ivan-nginx

**Comment by ehlxr** [comment]
修正leancloud的分支应该是有问题

**Comment by aixiu** [comment]
#1724 我最后根据上边提示更新后，正常了。@ehlxr 去看看。

**Comment by ivan-nginx** [comment]
Revert & update version: https://github.com/iissnan/hexo-theme-next/commit/23ee43ada2202a7c1c0362d86a6f8c32eac9fa1c
