### ISSUE TITLE
怎么实现图片点击后不进行放大或缩小的效果且不会出现放大或缩小的小图标？

### ISSUE THREAD

**Issue by Marze1994** [iissnan/hexo-theme-next#1761]
**下面这个截图是next主题作者博客第一页最下面的那篇纯图片文档，效果就是点击图片不进行放大或缩小，我想实现这种效果，我网上找了好久都没找到，不知道怎么设置，还望有懂的大牛能帮忙解答，感激不尽~**
![image](https://user-images.githubusercontent.com/25895849/28105735-4d563852-6713-11e7-96ce-74a095be3476.png)

**Comment by aixiu** [comment]
主题_config.yml
```
# Fancybox
fancybox: false
```
设置为fase就好

**Comment by ivan-nginx** [comment]
@Marze1994 issue is solved?

**Comment by Marze1994** [comment]
@ivan-nginx It has been solved，The answer is the one he @aixiu  answered.
