### ISSUE TITLE
头像设置不起！！

### ISSUE THREAD

**Issue by CHENQIKUAI** [iissnan/hexo-theme-next#1762]
### Expected behavior (预期行为)
头像随着config里面avatar的改变而改变

### Actual behavior (实际行为)
改变avatar 

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@CHENQIKUAI in English please.

**Comment by geekrainy** [comment]
头像应该放置于主题目录下 sources/images 目录

**Comment by JoeAsir** [comment]
1.Check your file path
2.Refresh your browser or clean up memory,especially for Chrome.
