### ISSUE TITLE
为何 hexo g 生成出的 HTML 文件开头的 !DOCTYPE html 是小写的？

### ISSUE THREAD

**Issue by Cat7373** [iissnan/hexo-theme-next#1763]
感觉其他网站都是大写的呀 0.0
NexT 小写是有什么原因喵。。。

似乎是这里小写了的原因：https://github.com/iissnan/hexo-theme-next/blob/23e18e511bb105913ce29abdd590eb7bb37573c2/layout/_layout.swig#L1

**Comment by ivan-nginx** [comment]
Hmm.. U are right, most of other sites have uppercase `!DOCTYPE`, but i don't think what that's will difference in html validator, for example. Ok, if on most sites it's uppercase, need to do the same. And thanks!
