### ISSUE TITLE
Muse主题下 移动端Alogila搜索有问题

### ISSUE THREAD

**Issue by revotu** [iissnan/hexo-theme-next#1764]
Muse主题下 集成的Alogila搜索，在移动端搜索时 出现的弹框遮挡住了结果，无法点击结果列表的文章链接

**Comment by ivan-nginx** [comment]
@revotu in English please.

**Comment by revotu** [comment]
Mobile Plaform  Alogila search under the Muse scheme, the search box at the end of the search appears to block the results, and can not click on the results list of article links

**Comment by ivan-nginx** [comment]
@revotu may u give some examples on it? Live demo? Screens? Anything.

**Comment by revotu** [comment]
![image](https://user-images.githubusercontent.com/11746753/28399799-d5b2cec0-6d41-11e7-937c-56f13a914b03.png)

can't click the search results because of the mask

**Comment by ivan-nginx** [comment]
@revotu can u show live demo?

**Comment by revotu** [comment]
![_20170720120030](https://user-images.githubusercontent.com/11746753/28399987-149ecc96-6d43-11e7-8442-7d85e41af80f.jpg)

live demo is the same bug...    my site is http://www.revotu.com   when mobile search that mask will appear so i cant click anything

**Comment by ivan-nginx** [comment]
@revotu ok, i'm on your site and there is all work fine. Tested on Chrome under Linux.
![image](https://user-images.githubusercontent.com/16944225/28400158-fc7b95a0-6d19-11e7-8979-7d64345e9f03.png)

**Comment by ivan-nginx** [comment]
@revotu ok, i get it: on mobile this is bug, links are not clickable.

**Comment by liszd** [comment]
I thought I found the bug.

![](https://ws1.sinaimg.cn/large/006tKfTcgy1fj80244tewj31ao0c2wj4.jpg)

`site-nav`'s `z-index` is 1 (on max-width: 767px)
but the ` algolia-pop-overlay`'s `z-index` 2080

**Comment by ivan-nginx** [comment]
@liszd can u fix it?

**Comment by liszd** [comment]
@ivan-nginx I have not read the code, I afraid I will make some trouble. Hah~

**Comment by lanpangzhi** [comment]
http://blog.langpz.com/2017/12/22/Hexo-Next%E9%9B%86%E6%88%90Algolia%E6%90%9C%E7%B4%A2/  文章最后有解决这个bug

**Comment by ivan-nginx** [comment]
Fixed in NexT v6 [here](https://github.com/theme-next/hexo-theme-next/pull/89).
