### ISSUE TITLE
怎么在每篇文章下面都增加作者功能？

### ISSUE THREAD

**Issue by weixingdeng** [iissnan/hexo-theme-next#1767]
请问我想在每个文章下面都增加作者，就和“分类”功能一样，请问我该怎么修改源码来实现？

**Comment by Neveryu** [comment]
可以考虑自己来实现这个功能吧，应该挺简单的。

**Comment by ivan-nginx** [comment]
@weixingdeng if solved, close it.

**Comment by mixool** [comment]
好像开启那个版权声明就带有作者了吧?

**Comment by geekrainy** [comment]
请开启主题配置下的 `post_copyright` 字段开启。

**Comment by aboutimes** [comment]
1.you can add author in ' layout／post.swig'
before
'{% if post.comments %}'
add
`<span> ｜ </span><span class="fa fa-user-o"> </span><span  style="color:#222;"> {{ post.author }}</span>
          
          {% if post.comments %}
`
2.and than  'in _post/xx.md' add 'author: xx'

**Comment by ivan-nginx** [comment]
Added in #1898 (**PART 5**).
