### ISSUE TITLE
一些 Tags 和 Categories 目录下 的链接  会出现 "404 not found"

### ISSUE THREAD

**Issue by cocofe** [iissnan/hexo-theme-next#1768]
As shown below, there are 9 articles in this directory of `Hexo`
![image](https://user-images.githubusercontent.com/27345052/28254545-4fd8b714-6ae0-11e7-94c5-cf4cffbb58b2.png)

But access the `Hexo` directory,There will be an error : `404 not found`
![image](https://user-images.githubusercontent.com/27345052/28254515-14079a20-6ae0-11e7-8a88-7677b3368e78.png)

But change the `Hexo` to` hexo`, the URL can be displayed properly
![image](https://user-images.githubusercontent.com/27345052/28254601-b915ee36-6ae0-11e7-86d4-aa9bc8bb4f75.png)

----
as the directory `laTex`
![image](https://user-images.githubusercontent.com/27345052/28254633-fe126b0e-6ae0-11e7-9bbd-2e8a73f97a5c.png)
also will be an error `404`
![image](https://user-images.githubusercontent.com/27345052/28254645-19e86e1e-6ae1-11e7-96cc-48d89cefb3fc.png)

---
is it the `Case problem`

**Comment by ivan-nginx** [comment]
@cocofe live demo?

**Comment by cocofe** [comment]
i have something to do .wait a moment




发自网易邮箱大师
在2017年07月17日 11:19，Ivan.Nginx 写道：

@cocofe live demo?

**Comment by cocofe** [comment]
you can visite [my website](cocofe.cn), @ivan-nginx

**Comment by ivan-nginx** [comment]
@cocofe in main Hexo config:
```
# Writing
filename_case: 1
```

**Comment by cocofe** [comment]
Thanks ,it`s solved

**Comment by ivan-nginx** [comment]
#1904.
