### ISSUE TITLE
ERROR Asset render failed: css/main.css

### ISSUE THREAD

**Issue by TopVitamin** [iissnan/hexo-theme-next#1769]
报错信息：
```
ERROR Asset render failed: css/main.css
ParseError: expected "indent", got "import"
    at Parser.error (G:\åå®¢\hexo\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (G:\åå®¢\hexo\node_modules\stylus\lib\parser.js:287:12)
```
在本地进行hexo -g 后，生成的public里面有main.css，然后localhost://4000下面也加载了这个css
*也就是路径没有错*，但是生成的文件为空了！
但是实际生成的main.css文件是是空的，不知道是什么原因！

本地其他的没有问题，就是这个生成静态文件的时候这个css文件有问题！求解救！

**Comment by ivan-nginx** [comment]
1. Try to rename local path from `G:\åå®¢\hexo` to something like `G:\ENGLISH_ANSI\hexo`.
2. `hexo clean` && `hexo g`. If any of CSS was changed, need always do `hexo clean` before generate.
3. As i see, this path target to `node_modules`, not to the `hexo\theme\next\...`, so, need to write issue in Hexo issues, not in issues for theme Next.

**Comment by TopVitamin** [comment]
@ivan-nginx  ok,  I'will try it again

**Comment by coyawa** [comment]
@TopVitamin 怎么样，请问有解决吗，我跟你一样的问题， 提示是
ParseError: expected "indent", got "=="
    at Parser.error (...\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (...\node_modules\stylus\lib\parser.js:287:12)
