### ISSUE TITLE
配置畅言评论后在归档页面中js抛出抛错，虽然不影响就是看着别扭

### ISSUE THREAD

**Issue by oceanbaby715** [iissnan/hexo-theme-next#1770]
start.min.js:71 Uncaught No SOHUCS div!

**Comment by ivan-nginx** [comment]
I don't understand, write in English, please. And try to give maximum info about errors, local files and other usefull things.

**Comment by chaixuhong** [comment]
@oceanbaby715  今天我会在我的博客中写下关于  畅言在next里使用的两个问题，1是分类标签归档页报错，2首页计数永远为0

**Comment by chaixuhong** [comment]
http://www.chaixuhong.com      
resolved  it !

**Comment by ivan-nginx** [comment]
Issue will be closed due not enought information.
