### ISSUE TITLE
这是原作者不维护了吗，哈哈😆

### ISSUE THREAD

**Issue by gnaixx** [iissnan/hexo-theme-next#1772]
Is this the original author not up to it? 😆😆😆
@iissnan

**Comment by ivan-nginx** [comment]
What are u talking about? Author can't do anything and he's already made a lot for this theme and it's all free for all of us and for u too.
So, if u have real issue, u are welcome; if not - no need to make flood here because we have a lot of opened issues without u. Can u see my mind? Thank's!

**Comment by gnaixx** [comment]
sorry about this

**Comment by gnaixx** [comment]
sorry about this @ivan-nginx

**Comment by ivan-nginx** [comment]
@gnaixx don't worry about is, it's fine. But u must understand what there is not funny room like social chats, etc. This is working place for free-soft maintaners and a lot of useless info do hard to resume it.

**Comment by gnaixx** [comment]
@ivan-nginx  i will remember and thank's for what u did
