### ISSUE TITLE
请教一个博客文章路径的问题?

### ISSUE THREAD

**Issue by flystarhe** [iissnan/hexo-theme-next#1773]
当文章比较多的时候,分目录(文件夹)管理是很常见的方法.比如我的目录结构:

```
.
├── categories
│   └── index.md
├── _posts
│   ├── algorithm
│   ├── data-analysis
│   ├── keras
│   ├── linux
│   ├── nlp
│   ├── note
│   ├── ocr
│   ├── python
│   ├── r
│   ├── scala
│   ├── tensorflow
│   └── zzz
└── tags
    └── index.md
```

比如`r`下有一篇文章`r-data-prepare.md`

### Expected behavior (预期行为)
期望的文章地址是:`base_dir/r/r-data-prepare/`,其他的主题也是这样干的.

### Actual behavior (实际行为)
结果是:`base_dir/r-r-data-prepare/`

自动把连接扁平化了,这并不是希望的.

还有一个问题,我习惯把资源和`.md`文件放在同一个目录下:
```
.
├── r
│   ├── index.md
│   ├── image-01.jpg
│   ├── image-02.jpg
```

这样做有很多好处,但是hexo好像对于这种相对引用就找不到资源了.

**Comment by ivan-nginx** [comment]
It seems u are talking about Hexo directories, not about theme Next. Anyway, can u explain on English?

**Comment by AlynxZhou** [comment]
这个是hexo的问题啦，另外对于那个资源文件夹的问题，hexo是建立的md文件不在资源文件夹里，这两个在同一个父目录里，最后生成的页面却在一个子路径里，如果觉得不合适，建议你去hexo的repo提issue~
@ivan-nginx He is truly talking about hexo, not theme.
