### ISSUE TITLE
MathJax have no effect

### ISSUE THREAD

**Issue by BarryLiu1995** [iissnan/hexo-theme-next#1774]
### Expected behavior (预期行为)
I am using the Typora Markdown local editor, his grammar is to comply with the GFM standard, I wrote the latex formula in the editor, the local editor shows the correct result！

![typoa](https://user-images.githubusercontent.com/20590350/28457503-ef5a5cce-6e38-11e7-8d3b-c0bcc989c52a.jpg)

![latex](https://user-images.githubusercontent.com/20590350/28457472-cff368b2-6e38-11e7-9463-18ab57968b2e.jpg)

### Actual behavior (实际行为)
**But the formula can not be displayed on the web page**
![default](https://user-images.githubusercontent.com/20590350/28457529-0a2eba18-6e39-11e7-956b-038eef2cdcf0.jpg)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
   ✔-  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
 ✔  -  Muse
  -  Mist
  -  Pisces

### Other Information (Like Browser, System, Screenshots)
When the beginning of the problem, I first looked at other people's issues, found that the problem is quite common, and the reasons for a variety of. I started to see #1154, I used their method, but found no effect. I uninstalled the kramed plugin and reused the hexo's rendering engine. Later, some people say that the default mathjax cdn has been invalid, I changed a cdn. Anyway, try a lot of ways, but do not know where the problem lies

here is my theme's config.yml
![mathjax](https://user-images.githubusercontent.com/20590350/28457685-abeb8188-6e39-11e7-8973-3ba57c587f71.jpg)

**Comment by BarryLiu1995** [comment]
Please I need a help!

**Comment by ivan-nginx** [comment]
@BarryLiu1995 can u check #1672? Mb, it can help.

**Comment by BarryLiu1995** [comment]
@ivan-nginx This is not the problem

**Comment by ivan-nginx** [comment]
@BarryLiu1995 may be u right, but anyway i think what problem is not in Next theme.
Theme Next - it's just templates and styles with some javascripts engines.
Mathjax - it's third party javascript and not Next maintenance it. And as markdown engine too.
It seems, problem in markdown engine in compilation with mathjax or any third-party plugins, what directly support markdown and/or Hexo. And i really don't know about mathjax and how it work, but u may also try to research in our issues by [this link](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue%20mathjax) or ask in MathJax | Markdown | NodeJS issues. Next it's just template, u must know and understand it.

**Comment by BarryLiu1995** [comment]
@ivan-nginx Ok, I got it. I will try to fix my problem by myself.

**Comment by ivan-nginx** [comment]
@BarryLiu1995 i don't know what this is, but see - [it's](https://github.com/iissnan/hexo-theme-next/issues/1429#issuecomment-279590051) working:
In `_config.yml`:
```
# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```
In `*.md` file:
```
$$lim_{1\to+\infty}P(|\frac{1}{n}\sum_i^nX_i-\mu|<\epsilon)=1, i=1,...,n$$
```
![image](https://user-images.githubusercontent.com/16944225/28497584-8d2dc570-6f93-11e7-8d57-46de8f686510.png)

**Comment by BarryLiu1995** [comment]
@ivan-nginx I change Front-matter like this and it work
![g](https://user-images.githubusercontent.com/20590350/28508868-6b22ef72-7070-11e7-9489-08214f678721.jpg)

**Comment by huyingjie** [comment]
[这个帖子里有提到解决方法](https://github.com/iissnan/hexo-theme-next/issues/1637)
>try to replace default with
//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

最后的代码是 (final code)

```
mathjax:
  enable: true
  per_page: true
  #cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  cdn: ////cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```
