### ISSUE TITLE
Google Webmaster tools can't be verified

### ISSUE THREAD

**Issue by LemonSprite** [iissnan/hexo-theme-next#1775]
### Expected behavior (预期行为)

set up a verification string for Google Webmaster tools

### Actual behavior (实际行为)

I followed the [Google Webmaster Tools Document](http://theme-next.iissnan.com/third-party-services.html#google-webmaster-tools
) for configuration, but I got the following result at [Google Webmaster Tools](https://www.google.com/webmasters/tools/).

```
Verification failed for http://xxx.com/ using the Meta tag method (less than a minute ago). We couldn't find the verification meta tag.
```

### Steps to reproduce the behavior (重现步骤)

[Google Webmaster Tools Document](http://theme-next.iissnan.com/third-party-services.html#google-webmaster-tools
) 

### NexT Information

NexT Version:

  -  ✔ Master
  -  Latest Release
  -  Old version -

**Comment by ivan-nginx** [comment]
Site adress? Site scheme?

**Comment by LemonSprite** [comment]
Site adress: [lujianan.com](http://lujianan.com)
Site scheme: Mist
Next verson: 5.1.1

**Comment by ivan-nginx** [comment]
@LemonSprite ok, can u tell what u do step by step? Because, my 2 sites on Next already verified by meta tag in google webmasters. And i think, on other peoples there is no errors about this.

**Comment by LemonSprite** [comment]
I solved the problem, probably because of my deployment problems
