### ISSUE TITLE
How to delete string "categories" and "tags" shown in the page,

### ISSUE THREAD

**Issue by HZzzzB** [iissnan/hexo-theme-next#1777]
### Expected behavior 
![image](https://user-images.githubusercontent.com/17507543/28496765-1e19c522-6fa6-11e7-9a2e-166286b9611e.png)
![image](https://user-images.githubusercontent.com/17507543/28496772-2d4ddd26-6fa6-11e7-9c8a-be2c584d44fd.png)

### Actual behavior 
![image](https://user-images.githubusercontent.com/17507543/28496761-0f28231a-6fa6-11e7-8e99-cd6b93f79a30.png)
![image](https://user-images.githubusercontent.com/17507543/28496776-34ad8de6-6fa6-11e7-99f5-3f59003cda1e.png)

### NexT Information 

**NexT Version:**
- [ ] Master
- [x] Latest Release
- [ ] Old version - 

**NexT Scheme:**
- [ ] All schemes
- [ ] Muse
- [x] Mist
- [ ] Pisces

### Other Information 
I want to delete the string “categories” and "tags" to make the page look better, how to achieve it.. Thank you for your help!

**Comment by ivan-nginx** [comment]
@HZzzzB edit files in `languages` dir and what u want.

**Comment by HZzzzB** [comment]
@ivan-nginx  Problem solved, Thank you!
I'm a beginner...So...I can' t recognize where problem should be.
