### ISSUE TITLE
如何自定义添加菜单及其对应的页面

### ISSUE THREAD

**Issue by KaimingWan** [iissnan/hexo-theme-next#1778]
### Expected behavior 
MENU菜单增加一个reading菜单，点击后跳转到一个html，能够罗列出指定category下的所有文章

### Actual behavior 
不知道该如何实现

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link to source code to generate this site: N/A

### NexT Information 

**NexT Version:**
```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**
```
[ ] All schemes
[x] Muse
[ ] Mist
[ ] Pisces
```

**Comment by ivan-nginx** [comment]
Menu may add via `config.yml` in Next theme.
How to add page - write in readme.

**Comment by KaimingWan** [comment]
@ivan-nginx I want to use my custom template(like categorie.swig) in a newly added page and get posts in a specified categories. The way you mentioned can only suppoort add a markdown page (hexo new page xxx)and I can only use the markdown syntax which will not support any logical code.

**Comment by ivan-nginx** [comment]
@KaimingWan Hm? U say pages not support any logical code, but posts support? Can u give some examples? Logical code like what?

**Comment by KaimingWan** [comment]
@ivan-nginx Like the code in file categories.swig which using the swig template engine.


`  <section id="posts" class="posts-collapse">
    <div class="collection-title">
      <{% if theme.seo %}h2{% else %}h1{% endif %}>{#
      #}{{ page.category }}{#
      #}<small>{{  __('title.category')  }}</small>
      </{% if theme.seo %}h2{% else %}h1{% endif %}>
    </div>

    {% for post in page.posts %}
      {{ post_template.render(post) }}
    {% endfor %}
  </section>`

**Comment by ivan-nginx** [comment]
@KaimingWan and? U may add this code to `page.swig`, not? U don't understand, what u want? What is your target, what u want do?

**Comment by KaimingWan** [comment]
what i want to do:
1. add a reading menu in the index（finished）
2. when touch the reading menu,i will go to a page which is created by command 'hexo new page reading'（finished）
3. the page named reading.md will show me all posts in category 'mycategory' for example.（not finished）

i want to use swig syntax in markdown file reading.md to solve the problem.

**Comment by ivan-nginx** [comment]
@KaimingWan so? Edit `page.swig` file as u want.
```
    {#################}
    {### PAGE BODY ###}
    {#################}
    <div class="post-body{% if theme.han %} han-init-context{% endif %}{% if page.direction && page.direction.toLowerCase() === 'rtl' %} rtl{% endif %}">
      {# tagcloud page support #}
      {% if page.type === "tags" %}
        <div class="tag-cloud">
          <div class="tag-cloud-title">
              {{ _p('counter.tag_cloud', site.tags.length) }}
          </div>
          <div class="tag-cloud-tags">
            {{ tagcloud({min_font: 12, max_font: 30, amount: 200, color: true, start_color: '#ccc', end_color: '#111'}) }}
          </div>
        </div>
      {% elif page.type === 'categories' %}
        <div class="category-all-page">
          <div class="category-all-title">
              {{ _p('counter.categories', site.categories.length) }}
          </div>
          <div class="category-all">
            {{ list_categories() }}
          </div>
        </div>
      {% else %}
        {{ page.content }}
      {% endif %}
    </div>
    {#####################}
    {### END PAGE BODY ###}
    {#####################}
```
This is page body. What u want? Show selected category? File `category.swig` extract post from category:
```
  <section id="posts" class="posts-collapse">
    <div class="collection-title">
      <h2 >
        {{ page.category }}
        <small>{{  __('title.category')  }}</small>
      </h2>
    </div>

    {% for post in page.posts %}
      {{ post_template.render(post) }}
    {% endfor %}
  </section>
```
U can take code from `category.swig`, insert him into `page.swig` and do custom additions.
About `page.category` and other variables u can read on [Hexo Docs](https://hexo.io/docs/variables.html).

**Comment by KaimingWan** [comment]
@ivan-nginx thanks. I will try  to change the page.swig later and verify what you said.

**Comment by KaimingWan** [comment]
@ivan-nginx  hello, I can use list_categories() in page.swig to get all categories in my custom page. But how can I get a specified categories such as a category called 'book' ? does any API support this or I have to change the source code of hexo to support this feature?

**Comment by ivan-nginx** [comment]
> does any API support this

No, as i know.

> or I have to change the source code of hexo to support this feature

Yes.

**Comment by mrcotter** [comment]
@KaimingWan I think my recent post can solve your problem about adding category pages as menu and change the layout to the same as the home page.

You can visit: [http://kris2d.info/posts/b706980b/](http://kris2d.info/posts/b706980b/)

**Comment by Yalhu** [comment]
Doesn't `liat_categories()` support filter specified categories?
 Is there any solution of this situation? What have you done @KaimingWan ?
I also want a category page that only including what I want.

**Comment by moyokoo** [comment]
@KaimingWan 老哥，问题解决了吗
