### ISSUE TITLE
RTL Language Support for Specific Article

### ISSUE THREAD

**Issue by shohret** [iissnan/hexo-theme-next#1779]
### Expected behavior 
First of all, thank you so much for your theme, I really like it.

I want to write some posts, articles by the right to left languages, such as Arabic, Uyghur, etc. And I have found some solutions, like this [Hexo Theme Icarus Arabic Test](http://blog.zhangruipeng.me/hexo-theme-icarus/2016/01/30/Arabic-Test/) (you could find the source code below), [Hebrew Post](http://orenm.biz/2017/02/19/right-to-left-align-in-hexo/). 

I tried to use this solution in Next theme by myself, but the theme files are .swig, not .ejs, I couldn't find a way to change it. So I really hope that you could help me this out.
I even put CSS code in single post, but this affects all the articles. T_T

It would be great if I can specify the language setting in front-matter, for example
`
title: اختبار اللغة العربية
date: 2016-01-30 10:15:01
...
language-direction: rtl
`

Also, I want to set a different font size and font family for RTL languages. I think this part would be easy, just specify it in CSS file for RTL LANGUAGE {direction:rtl; font-size: 16px; font-family: ...;}

### Steps to reproduce the behavior 
Link to demo site with this issue:
http://blog.zhangruipeng.me/hexo-theme-icarus/2016/01/30/Arabic-Test/

Link to source code to generate this site: 
https://github.com/ppoffice/hexo-theme-icarus/issues/234
https://github.com/ppoffice/hexo-theme-icarus/commit/d961446f3fa2990a4924e6df0e767a65159f6ab8

### NexT Information 

**NexT Version:**
```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**
```
[x] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
```

**Comment by ivan-nginx** [comment]
> I think this part would be easy, just specify it in CSS file for RTL LANGUAGE {direction:rtl; font-size: 16px; font-family: ...;}

U think right! So, u need just to add in `next/source/css/_custom/custom.styl` any u want. In this state, this  must be:
```
p { direction:rtl; font-size: 16px; }
```
But u right, need to think about add option for this. Thank's.

**Comment by ivan-nginx** [comment]
@shohret ok, i add this option. See PART 4 in #1697.
And if solved, close it.

**Comment by shohret** [comment]
Hey, great, thank you!
And I saw your test demo and CSS modification.
`
.post-body {
  font-family: $font-family-posts;
  +mobile() {
    word-break: break-word;
  }
  &.rtl p { direction: rtl; }
}
`
Just additionaly, it is better to add h1, h2, h3, h4, and li tags rtl as well, since in RTL language these all should start from right to left.

If I want to change rtl articles/pages font-size and font-family I can just add CSS code in `post.styl` like this right?
`
.post-body {
  font-family: $font-family-posts;
  +mobile() {
    word-break: break-word;
  }
  &.rtl p { direction: rtl;
               font-size: 16px;
               font-family: blablabla;
}
}
`

**Comment by ivan-nginx** [comment]
@shohret 
1. If u want to add h1-h6, li or any additional tags, u can change `&.rtl p` to `&.rtl p, h1, h2, li, etc.`.
    If u want to add all tags, not only selected, u may just change `&.rtl p` to `&.rtl` - this will like wildcard (*).
2. U no need to modify original repositories files. If u do it, in future your update from master branch will by hard. If u want to add your own custom styles, as i say before, u can add any custom styles in `_custom.styl` and this styles will rewrite basic styles? e.g.:
    Add to `next/source/css/_custom/custom.styl`
```
.post-body {
  &.rtl p {
    direction: rtl;
    font-size: 16px;
    font-family: blablabla;
   ...
  }
```
And this styles will rewrite all basic styles. No need to add mobile style if u don't wan't rewrite they. If want, u can add something like:
```
.post-body {
  +mobile() {
    word-break: initial;
    bla bla bla;
  }
  &.rtl p {
    direction: rtl;
    font-size: 16px;
    font-family: blablabla;
```
Next use scss and style can directly support variables, wich u can find in next/source/css/_variables`. Also, there is `custom.styl` too, so, u may rewrite basic variables too. That's why Next is so good theme, but no all know it.

**Comment by shohret** [comment]
I modified the code as you said, but it is not working well.

First, the [categories](https://shohret.github.io/categories/) page is aligned to right side, I want to make it normal, not RTL. I only want the lists to be RTL only in RTL language posts, not other pages.

Second, the [English article's header tag](https://shohret.github.io/2017/03/13/hello-world/) is aligned to the right side as well, I want to make it normal, not RTL.

These are the CSS code I added in `post.styl`

```
.post-body {

  +mobile() {
    word-break: initial;
  }
  &.rtl p, h1, h2, h3, h4, h5, h6, li, ol, ul {
  direction: rtl;
  font-family: UKIJ Ekran;
}
  &.rtl p {
  font-size: 16px;
}
}
```
and in `custom.styl`

```
@font-face {
  font-family: UKIJ Ekran;
  src: url("fonts/ukij-ekran.ttf");
}
```

Thank you

**Comment by shohret** [comment]
I realized my code in `post.styl` generated this CSS code below
```
.post-body.rtl p,
.post-body h1,
.post-body h2,
.post-body h3,
.post-body h4,
.post-body h5,
.post-body h6,
.post-body li,
.post-body ul,
.post-body ol {
  direction: rtl;
  font-family: UKIJ Ekran;
}
.post-body.rtl p {
  font-size: 16px;
}
```
Apparently, except p tag, all other tags are just `.post-body`, not `.post-body.rtl`. How should I write in post.styl to make it correct? Should I write each tag one by one? I am sure there is a convenient way tho.

**Comment by ivan-nginx** [comment]
> &.rtl p, h1, h2, h3, h4, h5, h6, li, ol, ul

Sorry, i mistake. Need to do like that:
>  &.rtl p, .rtl a, .rtl h1...

Or like that:
```
 &.rtl
  & p, a, h1...
```
***
Try to write 'UKIJ Ekran' or "UKIJ Ekran". Also, font option was buggy, as i remember.

**Comment by shohret** [comment]
The font `UKIJ Ekran` is working perfectly for post body, for the title, `post-title.rtl` selector is not working.

**Comment by ivan-nginx** [comment]
Live demo?

**Comment by shohret** [comment]
Sorry, forgot in the last comment.
Here is the webpage: https://shohret.github.io/

**Comment by ivan-nginx** [comment]
> post-title.rtl

Don't understand, where is this selector? This:
```
.post-title.rtl a, h1 {
    direction: rtl;
    font-family: UKIJ Ekran;
}
```
As i see, font working. What u want can u explain?

**Comment by shohret** [comment]
The font in the title is not UKIJ Ekran, I want to make that RTL language post's title to be UKIJ Ekran, just like body text.

![image](https://user-images.githubusercontent.com/17599211/28602956-cb22b882-7186-11e7-94d9-755e366ae87f.png)

**Comment by ivan-nginx** [comment]
See above.

**Comment by shohret** [comment]
I tried that code, it will affect that **Hello World** post's title. I want to keep left to right language posts normal. Only RTL post title to be in UKIJ Ekran

**Comment by ivan-nginx** [comment]
@shohret ok, then u need to modify like above `post-title.styl`. There are 2 sections - for expanded post and for homepage.

**Comment by ivan-nginx** [comment]
@shohret a can make separated `post-rtl.styl` for this. How u think, this is needed?

**Comment by ivan-nginx** [comment]
@shohret hand's up! I find why this not work. Take a moment, need to fix this.

**Comment by ivan-nginx** [comment]
@shohret check for this: 9673657.

**Comment by shohret** [comment]
Yeah, I think if we have `post-rtl`, it is easier to control. Then we don't have to change post-title-rtl, `post-body-rtl` separately.

For RTL language post, text should be `direction: rtl`, but programming code in any post should be always normal.

**Comment by shohret** [comment]
> check for this: 9673657.

Thank you, this is gonna work. Haha, that is why I was saying `post-title.rtl` isn't working.

**Comment by ivan-nginx** [comment]
@shohret yep, `.rtl` class was added in `post-body` only. So, i add it in `post-title` and if need, you also can add it to anyway (for sidebar, for example).
Ok, i will make `post-rtl.styl`. Need a test this from you. Wait for response.

**Comment by shohret** [comment]
Sure, thank you!

**Comment by ivan-nginx** [comment]
@shohret ok, check last 3 commits in #1697 PART 4.

**Comment by shohret** [comment]
It is working great, [demo](https://shohret.github.io/), thank you a lot!

**Comment by ivan-nginx** [comment]
U are welcome! But there is some problem: readmore button caption have rtl direction too. Or this is fine? how u think?

**Comment by shohret** [comment]
I don't think this is a big problem, it is fine~~~ ^_^

**Comment by ivan-nginx** [comment]
Good.
