### ISSUE TITLE
自动形成摘要

### ISSUE THREAD

**Issue by zqdongxw** [iissnan/hexo-theme-next#178]
可以通过description和more标签指定摘要，如果未指定的话，希望可以实现通过自动截取前几百字或者前几段自动生成摘要。

**Comment by suoba** [comment]
对啊，我最想要这个了，谁知道怎么做。

**Comment by iissnan** [comment]
提供一个思路，使用 [swig-extra](https://github.com/hexojs/hexo/pull/1151) 的 `truncate` 截取指定长度的字符，例如 WordPress 是截取 55 个字符。

或许，得再加一个控制的选项，是否自动进行文章的截取。

**Comment by iissnan** [comment]
增加了一个 `auto_excerpt`，自动截取文章内容。
此选项默认关闭，开启后默认的截取字符个数是 150 个，具体设定如下：

```
auto_excerpt:
  enable: false
  length: 150
```

@zqdongxw @suoba
