### ISSUE TITLE
怎么取消目录自带的序号？

### ISSUE THREAD

**Issue by dev-fancyluo** [iissnan/hexo-theme-next#1781]
我写文章会在文章的标题里写上序号，但是主题又自带序号，重复了，怎么取消？

**Comment by ivan-nginx** [comment]
Don't understand u. Can u talk in English?

**Comment by Neveryu** [comment]
那你就别加序号，主题会帮你加的

**Comment by Druadach** [comment]
Just modifly the ._config.yml
ctrl + f type toc
`
toc:
  enable: true

  # Automatically add list number to toc.
  number: true`

**number: false**
