### ISSUE TITLE
Hello,Iissnan.I created my blog with the NextT recently.Here is my question:I want to add the award function into my blog ,but after I do what you interduce in the instructions,there is no reward fuction in my blog.

### ISSUE THREAD

**Issue by Arno-cn** [iissnan/hexo-theme-next#1783]
***

### Expected behavior 
![](http://i.imgur.com/t9Lz9ia.png)

### Actual behavior 
 ![](http://i.imgur.com/VvesF6q.png)
### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[x] Pisces
```

### Other Information

**Comment by ivan-nginx** [comment]
Read Docs please.

**Comment by Arno-cn** [comment]
this my theme-config imformation
![](http://i.imgur.com/GFNMoTO.png)
