### ISSUE TITLE
Hi,Iissan.I've already read the docs,and after I complete the step there is no excepted reward fuction in my blog ,what is the problem?

### ISSUE THREAD

**Issue by Arno-cn** [iissnan/hexo-theme-next#1784]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![](http://i.imgur.com/0v4FI7X.png)

### Actual behavior 
![](http://i.imgur.com/MZ6AXse.png)

### Steps to reproduce the behavior 
Link to demo site with this issue: Arno-cn.github.io
this is my theme-config imformation
![](http://i.imgur.com/FmtmMKq.png)
### NexT Information

**NexT Version:**

```
[x ] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ x] Pisces
```

**Comment by ivan-nginx** [comment]
1. Path on images, what u write, must be absolute or relative path and open in browser directly.
For example, u put your `alipay.jpg` image into `themes/next/source/images` directory and in NexT `config.yml` write:
```
alipay: /images/alipay.jpg
```
Then, try to open this image directly in browser by `http://arno-cn.github.io/images/alipay.jpg` link. If image will open - alipay must work and will open this image too.
2. No need to create issues with this long labes. If anyone can help u - he's do it.

**Comment by Arno-cn** [comment]
Thank you very much!
