### ISSUE TITLE
阅读全文的样式修改

### ISSUE THREAD

**Issue by lixianshen** [iissnan/hexo-theme-next#1785]
现在设置阅读全分样式是左下方.一个横线.如何改成实例中.居中带边框的呢

**Comment by Neveryu** [comment]
NexT 的 Pisces 阅读全文是居中带边框的，你可能使用的不是 Pisces 吧，
如果你想使用这种样式，试试自己写css改样式吧。

**Comment by ivan-nginx** [comment]
@lixianshen solved?

**Comment by Haocen** [comment]
This issue is about customizing the style in order to change the way displaying a post, but the language is very vague and potentially fall out of the scope of this project.

**Comment by ivan-nginx** [comment]
@Haocen thank you for translate and close unnecessary issues! U help to make theme cleaner.
