### ISSUE TITLE
文章有代码时，首页显示效果错乱

### ISSUE THREAD

**Issue by whyteH** [iissnan/hexo-theme-next#1787]
有代码时，首页显示效果行号成这样了。
<img width="600" alt="2017-07-26 23 15 01" src="https://user-images.githubusercontent.com/12572016/28629000-bb204828-7258-11e7-99c3-56b2ea5655a2.png">
阅读全文有代码是这样的
<img width="600" alt="2017-07-26 23 16 03" src="https://user-images.githubusercontent.com/12572016/28629090-f97b86dc-7258-11e7-8ec9-d830b8df3ae6.png">
网址：http://laosiji.tech

**Comment by ivan-nginx** [comment]
Please, use search in issues before create new one.
#62, #178, #244 and full explain in #1591.
