### ISSUE TITLE
怎么去掉地址栏的 #more

### ISSUE THREAD

**Issue by GaoChaosh** [iissnan/hexo-theme-next#1791]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [ ] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ ] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
```

**Comment by Druadach** [comment]
So easy , just modify 

> /themes/next/layout/_macro/post.swig

Here is my blog , welcome ~
http://qianling.pw/

**Comment by ivan-nginx** [comment]
@GaoChaosh solved?

**Comment by shenzekun** [comment]
打开themes/next/layout/_macro/post.swig，在里面搜索 more 
https://ws4.sinaimg.cn/large/006tNc79ly1fhq0bqapdpj31hw08waaw.jpg
把下面的#more 去掉即可

**Comment by ivan-nginx** [comment]
```
# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: false
```
No need to modify anything.
