### ISSUE TITLE
Pic's shadow and border

### ISSUE THREAD

**Issue by alanxgorlan** [iissnan/hexo-theme-next#1792]
I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [ ] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

### Expected behavior 
Originally Remove the border by `..\source\css\_common\components\post\post-expand.styl`
```
img {
    box-sizing: border-box;
    margin: auto;
    padding: 3px;
    border: 1px solid $gray-lighter;
  }
```
Achieve the effect as shown in the 3th picture below
This time want to add the shadow，just like the 2nd pic.
Add the code as follows
```
 img {
    box-sizing: border-box;
    margin: auto;
    padding: 3px;
    border: 0px solid $gray-lighter;
    box-shadow:0px 0px 50px #aaaaaa;
  }
```
### Actual behavior 
And border appears again.Like 1st pic.
### NexT Information

**NexT Version:**

```
[ ] Master
[ ] Latest Release
[ √] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[√ ] Mist
[ ] Pisces
```

### Other Information
![20170729201403](https://user-images.githubusercontent.com/22426153/28744948-5f15c1f4-749f-11e7-9a06-3429733f6302.png)
![20170729204621](https://user-images.githubusercontent.com/22426153/28744951-72b40cca-749f-11e7-8b47-0c6de91f9c6b.png)
![20170729204539](https://user-images.githubusercontent.com/22426153/28744956-8202619a-749f-11e7-960c-54b516c4cb7c.png)

**Comment by ivan-nginx** [comment]
U can remove and add any things u want in `_custom.style`.
Also, i don't see any bugs here, just custom additionals and removes.
