### ISSUE TITLE
能否添加一个夜间的主题提供使用？

### ISSUE THREAD

**Issue by YanHuiLi** [iissnan/hexo-theme-next#1795]

**Comment by ivan-nginx** [comment]
@YanHuiLi in English, please.

**Comment by YanHuiLi** [comment]
@ivan-nginx  can u  add  the night theme for use ?

**Comment by ivan-nginx** [comment]
@YanHuiLi it's already backlogged.

**Comment by YanHuiLi** [comment]
@ivan-nginx  thx

**Comment by stevenjoezhang** [comment]
Added in https://github.com/next-theme/hexo-theme-next
