### ISSUE TITLE
分类和标签页里面的内容要自己写还是会自动生成呢？我的那两个页面是空白的

### ISSUE THREAD

**Issue by wuxianqiang** [iissnan/hexo-theme-next#1797]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ ] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
```

**Comment by wuxianqiang** [comment]
问题已经解决l

**Comment by tidyjiang8** [comment]
@wuxianqiang 
请问怎么解决的，我刚刚也碰到这个问题了？

**Comment by tidyjiang8** [comment]
Thanks，我也解决了
之前偷懒了，一直没clean
需要hexo clean,然后再hexo g

**Comment by OHLIA** [comment]
@tidyjiang8 
我clean还是没有内容，怎么回事？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
