### ISSUE TITLE
The navigation list and the article section have the right distance.

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1798]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![01](https://user-images.githubusercontent.com/8064012/28853018-171d9d36-7760-11e7-9029-13fc626f0d66.png)
The navigation list and the article section have the right distance

### Actual behavior 
![02](https://user-images.githubusercontent.com/8064012/28853046-491d9598-7760-11e7-8d97-869bd9a030b2.png)
In fact, the left navigation list is below the article section

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A
```
hexo clean
hexo g
hexo s
```
### NexT Information

**NexT Version:**

```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[x] Gemini 
```

### Other Information 
@ivan-nginx

**Comment by ivan-nginx** [comment]
@aixiu see there, there is [latest master branch](http://test.almostover.ru/) downloaded yesterday after global merge. All alignments working fine. Try to force refresh browser cache by CTRL+SHIFT+R.

**Comment by aixiu** [comment]
@ivan-nginx I pulled the latest branch code, also used CTRL + SHIFT + R failed, updated the same as other browsers

**Comment by ivan-nginx** [comment]
It's strange. Can u show `hexo -v`, `npm -v`?

**Comment by aixiu** [comment]
![npm](https://user-images.githubusercontent.com/8064012/28865363-35542c9c-77a2-11e7-867a-45fd83d99964.png)
![hexo](https://user-images.githubusercontent.com/8064012/28865370-3afac138-77a2-11e7-9be5-06376354acfb.png)

**Comment by ivan-nginx** [comment]
@aixiu and can u please give site live demo with this bug?

**Comment by aixiu** [comment]
@ivan-nginx I do not know what the reason, but I re-clone a new branch code, the deployment is successful, the show is normal.

**Comment by ivan-nginx** [comment]
@aixiu omg, don't need to be fast. Check all slowly and all will be fine.
If solved, close it.

**Comment by aixiu** [comment]
I used `git fetch origin master` as before
`git merge origin / master`
After replacing the `Gemini` theme, `hexo clean`, `hexo g`, `hexo s`.

**Comment by aixiu** [comment]
@ivan-nginx Thank you, the problem is temporarily resolved, just need to re-set some things.

**Comment by ivan-nginx** [comment]
@aixiu no need to replace anything. If something not work as expected, need to do separated test directory and load latest master branch to test it.

**Comment by aixiu** [comment]
@ivan-nginx Thanks for your advice。
