### ISSUE TITLE
Math 

### ISSUE THREAD

**Issue by ailurus1991** [iissnan/hexo-theme-next#18]
可否考虑加上数学公式的支持？

**Comment by iissnan** [comment]
可以。我会加上。

**Comment by iissnan** [comment]
@ailurus1991 
采用了 [MathJax](http://www.mathjax.org/) 提供的数学公式渲染支持。你试试是否可以满足你的需求。

**Comment by ailurus1991** [comment]
你的可以吗？我试了一下没能识别出公式。MathJax 语法是$$(行内)和$$$$没错吧。。

**Comment by iissnan** [comment]
噢，忘记说了，mathjax 默认是关闭的。需要在主题设置中将其设置为 `true` 开启。:sweat:

**Comment by iissnan** [comment]
```
# MathJax Support
mathjax: true
```

**Comment by ailurus1991** [comment]
Worked. 🍭

**Comment by pengzhendong** [comment]
矩阵渲染不出来。。。
