### ISSUE TITLE
二级目录的情况下，多说后台文章链接显示错误

### ISSUE THREAD

**Issue by ghw** [iissnan/hexo-theme-next#180]
#前置
#二级目录/notes/
正常情况下，应该的文章链接是
*.com/notes/2015/05/NGINX/
但是现在多说后台显示是
*.com/2015/05/NGINX/ 
##多说网站后台 文章标签 下可以看出
希望能帮忙解决，谢谢。

**Comment by iissnan** [comment]
按照多说的[评论框调用代码参数说明](http://dev.duoshuo.com/docs/5003ecd94cab3e7250000008)，当没有使用 `data-url` 时，默认是取页面的 url，这样看来应该不会有这个问题。

你可以尝试在[模板里](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_macro/post.swig#L52)加一个 `data-url` 看看是否能解决这个问题：

```html
<span class="post-comments-count ds-thread-count" 
    data-thread-key="{{ post.path }}" 
    data-url="{{ url_for(post.path) }}">
</span>
```

**Comment by mingmings** [comment]
@iissnan 想请问下，配了/note/之后，分类重新生成 category 以及 tag，貌似访问依旧是 404 ，还需要配置主题里的 menu 么

**Comment by iissnan** [comment]
category 和 tag 的链接指向对吗？ 

```
/note/categories/
/note/tags/
```

**Comment by mingmings** [comment]
@iissnan 已经试出来了，谢了
