### ISSUE TITLE
救命呀，我的页面怎么了？

### ISSUE THREAD

**Issue by Summyj** [iissnan/hexo-theme-next#1801]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

刚搭建好博客没多长时间，页面变成了这样，这是截图：

![image](https://user-images.githubusercontent.com/26139198/28995601-a1968e16-7a1f-11e7-8738-3d47391ea8e3.png)

我好绝望，大神快救命

### NexT Information

**NexT Version:**

```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[x] Pisces
```

### Other Information 

这是我的博客链接：http://jmyblog.top/

**Comment by ivan-nginx** [comment]
```
hexo clean && hexo g?
```

**Comment by Summyj** [comment]
There is no error:

![image](https://user-images.githubusercontent.com/26139198/28999760-95f13036-7a86-11e7-97af-9f3710f4518a.png)


but after comparing it to the previous file, I modified highlight.styl and _sidebar. Styl file, which can now be displayed normally. But there's a problem with color and page size, and now I'm working on it.

Thank you for your comment .^_^.
