### ISSUE TITLE
分享到微信没有缩略图

### ISSUE THREAD

**Issue by myjeshurun** [iissnan/hexo-theme-next#1802]
### I agree and want to create new issue 

- [x ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [ x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
1. 我的博客中含有图片，我预期把他分享到朋友圈（使用QQ浏览器）之后，能够像人们常见的公众号文章出现缩略图，这样看起来要美观好多。

### Actual behavior 
没有缩略图，只有一个链接标志。

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ x] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ x] Mist
[ ] Pisces
```

**Comment by ivan-nginx** [comment]
@myjeshurun can u explain in English?

**Comment by myjeshurun** [comment]
Yes. When I share to wechat, I want to present my page with a thumbnail
image, like the first item in the picture; but what I get is the second one
without a thumbnail picture.

Thank you.



Blessings in Christ,

*Jeshurun*
*我的仆人雅各，我所拣选的耶书崙哪，不要害怕！*
*Don’t be afraid, Jacob my servant; and you, Jeshurun, whom I have chosen.*

**Comment by ivan-nginx** [comment]
@myjeshurun about what pictures u speak?

**Comment by myjeshurun** [comment]
@starry-s exactly. Thx.

**Comment by liszd** [comment]
@myjeshurun 缩略图是微信自己生成的，要求图片大于300px x 300px

**Comment by myjeshurun** [comment]
是的，但即使我blog中有图片也不会出现缩略图，但简书jianshu.com 上的文章就会。

**Comment by Haocen** [comment]
@myjeshurun 简书，亚马逊这些八成是对 bot 抓取做了特殊优化了，要求一个静态页面做到相同效果似乎是很难的。

The website that is capable of generating thumbnails when linked by chatting app probably handle crawlers specifically by dynamically generating response based on `user-agent`, it doesn't seemed possible for Hexo to do the same.

**Comment by myjeshurun** [comment]
OK. Now I understand. Thank you for your explanation.

**Comment by Haocen** [comment]
微信要求网站已经注册公众号且在页面上引入他们的 JSSDK 才能自定义缩略图。

It has been confirmed WeChat JSSDK has to be used in order to allow the crawler parse the content.
At the meantime your website has to be registered on WeChat public channels.

**Comment by myjeshurun** [comment]
is there a way to use JSSDK on the hexo website?



Blessings in Christ,

*Jeshurun*
*我的仆人雅各，我所拣选的耶书崙哪，不要害怕！*
*Don’t be afraid, Jacob my servant; and you, Jeshurun, whom I have chosen.*

**Comment by Haocen** [comment]
Obviously the answer is yes, but you have to research it yourself, if you have access to WeChat JSSDK and registered as public channel.

You're welcomed to make a PR once you figure out a solution.

**Comment by ivan-nginx** [comment]
@Haocen this issue may be closed?

**Comment by zbl19962** [comment]
微信要求网站已经注册公众号且在页面上引入他们的 JSSDK 才能自定义缩略图。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
