### ISSUE TITLE
怎么设置文档或页面加密功能？（How to set up a document or page encryption function?）

### ISSUE THREAD

**Issue by Summyj** [iissnan/hexo-theme-next#1803]
**NexT Scheme:** Pisces

**问题描述（Problem description）：**

想在博客中加入自己的简历，但是不想让所有人都能看到。可以不可以设置密码，这样只有有密码的人才可以访问我的简历。文章也可以设为私密的。（I want to join my resume in the blog, but I don't want to let all to see.  Is there a way can set the password so that only a person with a password can access my resume. And  article can also be set to private.）

**Plus：**

另外，博客中加了网易云音乐的外链，但是每次换页面的时候，都会重新开始播放，能不能设成全局有效？（In addition, the blog has a Music links, but every time I change the page, it will start to play again, can I set it to be globally valid?）

这是我的博客链接（Here is my blog link）：http://jmyblog.top/

**Comment by ivan-nginx** [comment]
@Summyj NexT not have this function. But u can see in [hexo.io/plugins](https://hexo.io/plugins/) way about this.

**Comment by yangfanv** [comment]
你好，hexo博客框架有文章加密插件，希望能解决你的问题

**Comment by dataiyangu** [comment]
> **NexT Scheme:** Pisces
> 
> **问题描述（Problem description）：**
> 
> 想在博客中加入自己的简历，但是不想让所有人都能看到。可以不可以设置密码，这样只有有密码的人才可以访问我的简历。文章也可以设为私密的。（I want to join my resume in the blog, but I don't want to let all to see. Is there a way can set the password so that only a person with a password can access my resume. And article can also be set to private.）
> 
> **Plus：**
> 
> 另外，博客中加了网易云音乐的外链，但是每次换页面的时候，都会重新开始播放，能不能设成全局有效？（In addition, the blog has a Music links, but every time I change the page, it will start to play again, can I set it to be globally valid?）
> 
> 这是我的博客链接（Here is my blog link）：http://jmyblog.top/

你可以参看我的博客mmmmmm.me 加入pjax即可，不仅可以音乐播放不断，而且可以加快访问速度，相关文章在分类hexo中
