### ISSUE TITLE
边栏优化问题 almostover.ru 的边栏很不错！求教程。

### ISSUE THREAD

**Issue by David-Wey** [iissnan/hexo-theme-next#1809]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [ ] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
https://almostover.ru 边栏下的Back to top 的效果在哪里能看到如何修改？

### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ ] Master
[x ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
```

**Comment by Raincal** [comment]
![_ _20170810172414](https://user-images.githubusercontent.com/6279478/29164019-bfec699c-7df0-11e7-9e6f-8b3b7e4c8839.png)
