### ISSUE TITLE
使用畅言后，在标签、分类页报错问题

### ISSUE THREAD

**Issue by chaixuhong** [iissnan/hexo-theme-next#1810]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

+ 在添加畅言评论后，根据next使用文档，创建标签页、分类页，并且添加`comments:false`属性，正常应该在首页使用畅言计数功能，在文章页使用计数与评论功能，在分类页、标签页什么都不使用。

### Actual behavior 
+ 加了`conments=false`属性确实没有了计数与评论功能，但是却在分类与标签页加了一段畅言的代码，导致点进去后，控制台会一直报错，错误信息如下：
```
Uncaught No SOHUCS div!  
```
```
plugins.count.js:3 Uncaught TypeError: Cannot read property 'parentNode' of null  ....
```
一直报下去
### Steps to reproduce the behavior 
Link to demo site with this issue: N/A
Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ ] Master
[x] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[x] Mist
[ ] Pisces
```

**Comment by AlynxZhou** [comment]
NexT没有内置畅言吧，你是自己添加之后出现问题嘛？添加到哪里能说明一下吗？

**Comment by chaixuhong** [comment]
@AlynxZhou 最新的next已经内置了畅言，但是使用时有两个问题。第一个问题：在分类页、标签页、归档等不需要引用畅言的页面，却引进了一段计算评论数的js代码，导致控制台无限报错下去，倒是不影响使用。第二个问题，在首页中，计算评论数的代码，url::http://yoursite.com/xxx/xxx  中，如果写的文章标题有中文，那么首页评论数永远显示0。 因为畅言查找的url需要对上面url中的中文做encodeURI。     这两个问题我已经自己改了。

**Comment by chaixuhong** [comment]
@yidao620c http://www.chaixuhong.com/article/NEXT%E4%BD%BF%E7%94%A8%E7%95%85%E8%A8%80%E7%9A%84%E9%97%AE%E9%A2%98.html

**Comment by SilenceZhou** [comment]
@chaixuhong 请问下具体怎么操作？？？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
