### ISSUE TITLE
建议补充下文档

### ISSUE THREAD

**Issue by drtrang** [iissnan/hexo-theme-next#1815]
`hexo-theme-next` 项目迭代很快，最近加入了很多功能，但是文档没有跟进。
比如与第三方插件的集成，其实不需要按照插件的官方文档来配置，`hexo-theme-next` 已经做好了这部分工作，但是文档里没有写。如果按照官方文档配置的话会造成生成的文件中代码重复。

**Comment by ivan-nginx** [comment]
@drtrang don't understand u, can u write in English?

**Comment by AlynxZhou** [comment]
@ivan-nginx He means that theme grows fast and many new functions don't have documents in the theme document, and needs to update some new parts for the docs.

**Comment by ivan-nginx** [comment]
@AlynxZhou yeah, i think about it. I don't have access to iissnan docs site and it seems need to create documents here, in Github.
