### ISSUE TITLE
Sidebar position incorrect.

### ISSUE THREAD

**Issue by STARRY-S** [iissnan/hexo-theme-next#1817]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Changed the scheme to  Gemini
and the  sidebar position: right
### Actual behavior 
The sidebar position is incorrect

### Steps to reproduce the behavior 

i think i needn't to reduce it.
[Link here](http://cp-test.starry-s.com)
### NexT Information

**NexT Version:**

```
[ ] Master
[x] Latest Release
[ ] Old version - 

```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
no it happened in the Gemini in the latest version(v5.1.2)

```

### Other Information 

![screenshot from 2017-08-15 21-13-25](https://user-images.githubusercontent.com/21214244/29319060-2cb88d36-8205-11e7-808e-432c0b3ba1cd.png)

**Comment by ivan-nginx** [comment]
[Fixed](http://test.almostover.ru/).
