### ISSUE TITLE
如何保持footer始终在页面底部？

### ISSUE THREAD

**Issue by emptyxl** [iissnan/hexo-theme-next#1818]
标签云页、关于页等内容过少或使footer在页面中间，如何保持footer始终位于页面底部？
使用的是Mist

---

How to keep the footer always at the bottom of the page? If the content of tag cloud page or other pages are too little, footer will be displayed in the middle of the page.
Using the Mist theme.

**Comment by chaixuhong** [comment]
最新的5.1.2 NEXT 应该已经解决了这问题，因为我的footer是一直在底部的

**Comment by emptyxl** [comment]
@chaixuhong My current version is also 5.1.2.

code in theme _config.xml:
```
# Theme version
version: 5.1.2
```

**Comment by ivan-nginx** [comment]
@emptyxl can u show live example on this? Footer — is footer, he always must be in bottom of the page. What u mean?

**Comment by emptyxl** [comment]
@ivan-nginx You can see here: https://hellohxk.com/categories/
It is not in bottom of the page.

**Comment by ivan-nginx** [comment]
@emptyxl 5.1.1 version have this bug too?

**Comment by emptyxl** [comment]
@ivan-nginx I'm not sure. I only used 5.1.2. I just got into next theme.

**Comment by ivan-nginx** [comment]
@emptyxl ok, u use latest master branch update or [latest release](https://github.com/iissnan/hexo-theme-next/releases) version?

**Comment by emptyxl** [comment]
@ivan-nginx I  refer to http://theme-next.iissnan.com/getting-started.html and used this command:

```
$ git clone https://github.com/iissnan/hexo-theme-next themes/next
```

**Comment by ivan-nginx** [comment]
Ok, just try to do this steps:
1. Make backup of your `themes/next` directory.
2. Read[ English docs](https://github.com/iissnan/hexo-theme-next/blob/master/README.en.md) and try to update your theme. Update must include pull requests (#1807) with some footer changes.

**Comment by emptyxl** [comment]
@ivan-nginx I have done that following your steps. But it doesn't work.

**Comment by ivan-nginx** [comment]
3. `hexo g && hexo d`?

**Comment by chaixuhong** [comment]
> 文件坐标：next/source/css/_common/outline/outline.style

将里面的.footer样式改为:

```css
.footer {
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  min-height: $footer-height;
}
```
即可

**Comment by ivan-nginx** [comment]
@emptyxl it seems u use latest master branch version and with [latest footer changes](https://github.com/iissnan/hexo-theme-next/blob/7caab488a5fbf687e055c87fdd2b7e7cd10588ef/source/css/_common/outline/outline.styl#L43-L50). Usually, need to use releases if u want to close too stable version. U need to install clean [5.1.2 release]([url](https://github.com/iissnan/hexo-theme-next/releases/latest)) to normal footer position, like in @chaixuhong code above.

**Comment by emptyxl** [comment]
@chaixuhong thx! It works.

**Comment by emptyxl** [comment]
@ivan-nginx Yeah, It works. Thx.

**Comment by newdee** [comment]
@chaixuhong is right, I don't know what version I have downloaded, release or master version, but it's .1.2. 
And I find the follow sentences had been commented.
```
  position: absolute;
  left: 0;
  bottom: 0;
```

**Comment by newdee** [comment]
@chaixuhong 但是我改了后，虽然解决了底部状态栏的位置问题，可是首页的跳转到其他页面的一栏不见了。就是第123456页那一栏。

**Comment by cnrting** [comment]
v6.0.2 Gemini 没有用

**Comment by stevenjoezhang** [comment]
@cnrting 请使用最新版本（v7.1），已修复此问题

**Comment by vioao** [comment]
@stevenjoezhang 最新版 7.8 还是有这个问题
