### ISSUE TITLE
希望评论那里的判断条件加上enable

### ISSUE THREAD

**Issue by hbhaida** [iissnan/hexo-theme-next#1819]
将某个评论功能的 `enable` 改为 `false` 之后，还是不能用另外的评论插件。

检查发现，comments.swig 文件里的判断只判断的 `id` 和 `key`，因为上面的评论功能我只将 `enable` 改为了 `false`，但 `id` 和 `key` 我没有删除，所以导致了判断为 `true`。

贴一段小代码

```php
    {% elseif theme.youyan_uid %}
      <div id="uyan_frame"></div>
    {% elseif theme.livere_uid %}
      <div id="lv-container" data-id="city" data-uid="{{ theme.livere_uid }}"></div>
    {% elseif theme.changyan.appid and theme.changyan.appkey %}
      <div id="SOHUCS"></div>
    {% elseif theme.valine.appid and theme.valine.appkey %}
      <div id="vcomments"></div>
    {% endif %}
```

**Comment by ivan-nginx** [comment]
What's the point? In English, please.

**Comment by AlynxZhou** [comment]
@ivan-nginx He finds a bug of youyan comment in swig, when it have id and key in _config.yml, even enable is set to false, youyan is still opened, we need to add another if in the code he shows.

**Comment by ivan-nginx** [comment]
Fixed in [here](https://github.com/theme-next/hexo-theme-next/pull/39) in NexT v.6.0.x.
