### ISSUE TITLE
表格的显示问题

### ISSUE THREAD

**Issue by xirong** [iissnan/hexo-theme-next#182]
markdown中表格的用法如下：

 |   vpn   |   shadowsocks   |
 | --------:| :------: |
 |   简单，一键翻墙 |  简单，一键翻墙  |
 | 全局，代理浏览器、各种app、所有走网络的都经过vpn服务器|只有浏览器（可以手动设置代理其他app）|
 | 免费、收费服务商很多| 免费、收费服务商很多|
 | 速度可以| 速度很快，香港、新加坡几十毫秒|
 | 平台性稍差，有些做的也不错了，总体跨平台性差| 支持各平台客户端，跨平台性强|

理论上讲展示后应该是这样子的：
![image](https://cloud.githubusercontent.com/assets/3087094/7796332/2066dc06-0311-11e5-94f2-10fb7d5851f7.png)

可在 next 主题上面却是这样的，没有边框：
![img](http://static.ixirong.com/pic/error/next-md-table.png)

**Comment by flashlab** [comment]
我觉得这样很好～

**Comment by iissnan** [comment]
@xirong It is by design.
