### ISSUE TITLE
В теме NexT.Gemini отсутствуют отступы между шапкой и по бокам (моб. устройства)

### ISSUE THREAD

**Issue by online** [iissnan/hexo-theme-next#1820]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Ожидаю, что воспользовавшись последними правками из репозитория я получу максимально похожую тему, которую вижу на тестовом поддомене — https://test.almostover.ru/

### Actual behavior 
В последней версии темы NexT.Gemini отсутствуют отступы сверху и по бокам (дальше будут скриншоты для наглядности).

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: https://inotes.pp.ua/ (мой сайт, где можно увидеть проблему)
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Master
[ ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[x] Gemini
[ ] Muse
[ ] Mist
[ ] Pisces
```

## Вот как это выглядит в моём блоге:

![inotes pp ua](https://user-images.githubusercontent.com/722881/29498343-9748884e-8602-11e7-939d-bac0d2a760e5.png)

---

![inotes pp ua_2](https://user-images.githubusercontent.com/722881/29498347-a8187544-8602-11e7-8052-84c1fba8d32b.png)

## А вот как это выглядит на тестовом поддомене test.almostover.ru

![test almostover ru](https://user-images.githubusercontent.com/722881/29498356-f29f998a-8602-11e7-95ff-e3e381bd1138.png)

---

![test almostover ru_2](https://user-images.githubusercontent.com/722881/29498357-f985a9b0-8602-11e7-867a-1839e6a5f855.png)

**Comment by ivan-nginx** [comment]
@online приветствую!
Ну, во-первых, для удобства осмотра вёрстки на различных устройствах можно воспользоваться [респонзинатором](http://www.responsinator.com/?url=https%3A%2F%2Finotes.pp.ua%2F).
Во-вторых, всё верно, по-умолчанию экономичный режим отключен из-за проблемы совместимости с остальными темами (в частности — Mist и Muse). Опцию можно включить:
`themes/next/_config.yml`
```yml
# Reduce padding / margin indents on devices with narrow width.
mobile_layout_economy: true
```
Но по вёрстке Gemini до сих пор ещё не доработана, постараюсь доделать к следующему релизу. Но если будут замечены ещё недочёты — буду рад любым иссуям. Такие дела. :smiley:

**Comment by online** [comment]
@ivan-nginx, спасибо за responsinator, раньше не знал о таком удобстве. Также благодарю за подсказку про экономичный режим.

А вот про "ВС", к сожалению, не понял. Видимо нужно зайти куда вы порекомендовали, там будет понятнее, надеюсь.

**Comment by ivan-nginx** [comment]
@online if solved, close it please.
