### ISSUE TITLE
有人在闲鱼上以99元贩卖此主题，等难以置信的操作，他违规了吗？

### ISSUE THREAD

**Issue by gledos** [iissnan/hexo-theme-next#1822]
闲鱼[地址](https://2.taobao.com/item.htm?spm=2007.1000337.18.2.80194d2OU15jL&id=524519469932)
- 在他的博客中也没有提到 next 主题和 hexo 生成器，反而在footer的部分出现了 Powered by NorthPark.cn 的字样
- 并且仓库里没有 MIT License

图片:
[![2.taobao.com-item.htm-spm_2007.1000337.18.2.8019.png](https://s26.postimg.org/p9w1sqq21/2.taobao.com-item.htm-spm_2007.1000337.18.2.8019.png)](https://postimg.org/image/7wlrdvuqt/)
![2](http://okaibm8my.bkt.clouddn.com/17-8-21/15201282.jpg)

他的博客[仓库](https://github.com/liuhouer/liuhouer.github.io)

他违规了吗？

**Comment by mafeifan** [comment]
可以举报

**Comment by xiehaib** [comment]
大大的人才！

**Comment by novnan** [comment]
已举报！

**Comment by harveywhite** [comment]
已举报

**Comment by liuhouer** [comment]
网络上总是有很多杀币喷子，喷起来还念念有词。
我写的很明白，出售的是搭建博客，讲解写markdown博文并发布的服务。
主题可以选hexo自带的，也可以选你们自己喜欢的主题！本人不是出售主题，也不是出售hexo。next主题我是没有指明，hexo也没有指明，这是我的自由。但是咸鱼这个服务却是说的明明白白的！

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
