### ISSUE TITLE
Page navigate issue

### ISSUE THREAD

**Issue by GraysonLiu** [iissnan/hexo-theme-next#1823]
The _archives_ item in _config.yml was annotated in recent commit. Thus when click _posts_ on the sidebar, the page won't jump to archives.  How to solve this without archives menu shown?

**Comment by ivan-nginx** [comment]
@GraysonLiu u not believe in this, but just tomorrow u made this fix. Wait a moment, i will add commit to this.

**Comment by ivan-nginx** [comment]
@GraysonLiu fixed in 074bd04. Close, if solved.

**Comment by GraysonLiu** [comment]
@ivan-nginx Problem solved, THX.
