### ISSUE TITLE
When using Gemini scheme, how to adjust the width of the browser screen?

### ISSUE THREAD

**Issue by Flowsnow** [iissnan/hexo-theme-next#1827]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

There are too much blank on both sides of the screen. So I hope to get a method to adjust the width of how the blog show on the browser. For details, please refer to the final picture.

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[x] Gemini
```

### Other Information 
![](http://7xpzxw.com1.z0.glb.clouddn.com//test/github/2017-08-27_012203.png)

**Comment by Flowsnow** [comment]
The demo website is http://flowsnow.net/
Thanks

**Comment by ivan-nginx** [comment]
![image](https://user-images.githubusercontent.com/16944225/29744104-7d8c596e-8aa6-11e7-923a-370374c61229.png)
There is no middle blank. Try to clean cache of your browser.

Adjust left and right sides may to change variable in `source/css/_variables/Gemini.styl`:
```
$main-desktop                     = 75%;
```

@Flowsnow don't forget to close it, if solved.

**Comment by Flowsnow** [comment]
@ivan-nginx Your method is really effective. I change the variable in source/css/_variables/Gemini.styl as follow:
```
$main-desktop                     = 90%;
```
Thank you!
