### ISSUE TITLE
5.1.2没有修改,无法运行

### ISSUE THREAD

**Issue by Penguin-G** [iissnan/hexo-theme-next#1828]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x ] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
正常运行

### Actual behavior 
找答案
重新编译
无法运行

### Steps to reproduce the behavior 
1. 重新编译
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[ ] Master
[x ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[ ] Gemini
```

### Other Information 
![tim 20170827021902](https://user-images.githubusercontent.com/18643565/29744024-c0f746dc-8ace-11e7-862d-cb007a1570a7.png)

**Comment by ivan-nginx** [comment]
Too small info. Try to install clean copy of latest release version or give more information about this issue.
