### ISSUE TITLE
请问怎么自定义页面（禁用主题）

### ISSUE THREAD

**Issue by mrsup** [iissnan/hexo-theme-next#183]
需要自己做一个页面挂在博客下，不使用主题，整个页面完全自定义
尝试过在source下新建test.html，不过打开localhost:4000/test.html后自动加载了主题

**Comment by mrsup** [comment]
折腾了一下午，终于弄好，汗一个！！！
为了不使用主题的布局文件，可以直接在文章的Front-matter设置layout: false
就这么简单一个问题唉！！！

**Comment by flashlab** [comment]
[这里](https://github.com/hexojs/hexo/issues/1146#issuecomment-88380140)

**Comment by mrsup** [comment]
@flashlab 问题已解决，十分感谢！
