### ISSUE TITLE
只有两篇文章直接跳转到404

### ISSUE THREAD

**Issue by Penguin-G** [iissnan/hexo-theme-next#1831]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [ ] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [ x ] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
正常访问文章

### Actual behavior 
坐标: www.0924.tk
enter --> www.0924.tk --> Hello World --> 404
enter --> www.0924.tk --> 比特币币值已经超过四千美金，购买云挖矿算力抢收红利！ --> 404

本地测试正常!
网站上直接跳转404!
其中,主题的代码,并没有修改.

### Steps to reproduce the behavior 
1. 重新编译部署,依然跳转404
2. N/
3. N/A

* Link to demo site with this issue: www.0924.tk
* Link(s) to source code or any usefull link(s): https://github.com/Penguin-G/hexo-theme-next

### NexT Information

**NexT Version:**

```
[ ] Master
[ x ] Latest Release
[ ] Old version - 
```

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[x ] Mist
[ ] Pisces
[ ] Gemini
```

**Comment by ivan-nginx** [comment]
1. Something wrong in *.md files. See permalinks and Hexo settings.
2. There is no theme NexT bug. Try to install clean Hexo & NexT.

**Comment by Penguin-G** [comment]
still...🙁

**Comment by ivan-nginx** [comment]
@Penguin-G u install clean NexT release? What version?

**Comment by Penguin-G** [comment]
@ivan-nginx Finally,I delete my article.Be resolved!
Yes, clean NexT , 5.1.2.
