### ISSUE TITLE
post_wordcount bug

### ISSUE THREAD

**Issue by Caij** [iissnan/hexo-theme-next#1832]
post_wordcount separated_meta set true,  it is not in new line.

![2aac8e2e-e3ee-40ef-a602-f01f18c08c18](https://user-images.githubusercontent.com/8597839/29775595-3cbb4db2-8c38-11e7-99b8-96cc18ae4a4b.png)

If true wordcount block will placed in new line. Default.
If false wordcount block will added in main meta-block at the right of the time, category, comments blocks, etc.

**NexT Scheme:**

```
[ ] All schemes
[ ] Muse
[x] Mist
[ ] Pisces
[ ] Gemini
```
Theme version:5.1.2

**Comment by ivan-nginx** [comment]
Fixed in #1812 (latest master branch).

**Comment by Caij** [comment]
@ivan-nginx 
When is the release version?

**Comment by ivan-nginx** [comment]
@Caij [soon](../milestones).
