### ISSUE TITLE
怎么往主题里添加 mermaid 插件？

### ISSUE THREAD

**Issue by haoxueren** [iissnan/hexo-theme-next#1835]
现在的主题不支持 mermaid 绘图，也没有找到相关的插件。但又很需要这个功能。谢谢！

https://github.com/knsv/mermaid

**Comment by liszd** [comment]
@ivan-nginx Haoxueren need [mermaid](https://github.com/knsv/mermaid) ...

**Comment by MrHunterZhao** [comment]
Haoxueren need mermaid   +1024

**Comment by DateBro** [comment]
Hexo user need mermaid +1, plz!

**Comment by stevenjoezhang** [comment]
请升级到新版：https://github.com/theme-next/hexo-theme-next
已加入对于mermaid的支持
使用方法`{% mermaid %} ... {% endmermaid %}`

**Comment by ivan-nginx** [comment]
Feature added in [NexT v7](https://github.com/theme-next/hexo-theme-next).
