### ISSUE TITLE
网站存放在子目录 问题

### ISSUE THREAD

**Issue by Lt-grint** [iissnan/hexo-theme-next#1838]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
使用[litao.work/blog](http://www.litao.work/blog)打开显示成下面的效果，这是使用[localhost:4000/blog](localhost:4000/blog)打开的效果
![image](https://user-images.githubusercontent.com/14197717/29877539-7a50b194-8dd2-11e7-9dc1-f0fd0c9698fb.png)

### Actual behavior 
使用[http://litao.work/blog](http://www.litao.work/blog)打开显示成下面的效果
![image](https://user-images.githubusercontent.com/14197717/29877595-a417a2d0-8dd2-11e7-81fe-3df55c00577c.png)
使用[http://litao.work/](http://www.litao.work)打开显示成下面的效果

![image](https://user-images.githubusercontent.com/14197717/29877672-dcc174c6-8dd2-11e7-8bc8-f5b09ceafbb6.png)

### NexT Information

**NexT Version:**

```
[] Master
[x] Latest Release
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 

站点配置文件
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://litao.work/blog
root: /blog/
##永久链接
permalink: :year/:month/:day/:title/
permalink_defaults:
```
主题配置文件
```
menu:
  home: / || home
  categories: /categories ||th
  archives: /archives || archive
  tags: /tags || tags
  about: /about || user


menu_icons:
  enable: true
```
next主题版本
```
5.1.2
```

**Comment by ivan-nginx** [comment]
@Lt-grint [latest release](../releases/latest) for now is 5.1.2 and have no menu links with icons option.
So, u have latest master branch?

**Comment by himao** [comment]
应该和主题没有关系，似乎是站点部署问题。
推测你仍部署到了网站根目录下而不是/blog目录下，所以访问/blog目录返回404。访问根目录可以返回内容，但不加载样式的原因是你更改了配置文件中站点路径为/blog，在加载根目录内容时会请求/blog目录下的样式，但/blog目录下是空的，所以是无法加载的。
打开浏览器调试信息，可以更进一步确认该问题。
如果如上所述，那你应该更改部署路径。配置文件中的url和root参数与部署路径没有关系，更改这两个参数不代表你的部署路径就会更改。

**Comment by Lt-grint** [comment]
@himao 你好，之前排查了一些问题，应该时CNAME没有配置好，现在我在域名注册商那里将域名解析设置成下面这样：
![image](http://static.zybuluo.com/danerlt/zd82z5qlrrgpo02apo28iqf2/DeepinScreenshot_select-area_20170902210244.png)

然后将git仓库中CNAME文件设置成：`blog.litao.work`
![image](http://static.zybuluo.com/danerlt/2p5yy3renzm8ku6k8gfathz7/DeepinScreenshot_select-area_20170902210301.png)
现在的效果是我用localhost:4000预览时正常的：
![image]( http://static.zybuluo.com/danerlt/cx8b26em3vmye721y1ptr4ty/DeepinScreenshot_20170902210755.png)

但是我使用[http://blog.litao.work](http://blog.litao.work)访问时好像样式变了:
![image](http://static.zybuluo.com/danerlt/88w173ytgmktwmeqmagxaibd/DeepinScreenshot_select-area_20170902210748.png)

**Comment by himao** [comment]
@Lt-grint 看到你补充的内容，似乎和之前的描述的并不是一个问题。之前描述的是把a.com的内容转移到a.com/blog目录下，并能通过a.com/blog正确访问显示的问题；而补充内容似乎描述的是一个变更域名的问题，把之前a.com的域名变更为blog.a.com。我想这可能不需要混在一起讨论。
或许，你是想把站点内容放到a.com/blog目录下，并希望通过blog.a.com访问到该子目录的内容。那么我觉得你应该先解决之前的问题，然后再考虑把某一个域名绑定到站点子目录的问题。
如果，你仅仅是想更改一下域名，而不涉及子目录和子目录域名绑定问题，那么这应该和你第一次部署博客一样的，仅仅变更一下要使用的域名即可。

**Comment by Lt-grint** [comment]
@himao,你好，谢谢你的解答，我想要的效果是域名/blog能够正常访问，但是好像我没有配置起，所以就退一步用blog.域名去访问，现在用blog.域名我已经配置好了。开始定位问题应该是样式表的问题，后面仔细查看了发现是main.css出现304的重定向，里面内容是空的，我用浏览器清除缓存之后效果就正常了。使用域名/blog我明天再配一下，如果成功了我就把这个issue关闭。谢谢你的解答。

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!
