### ISSUE TITLE
关于页面右侧出现侧边栏外部链接（sidebar-Social Links）的问题

### ISSUE THREAD

**Issue by Zhang21** [iissnan/hexo-theme-next#1840]
进入个人主页的时候，侧边栏里面的外部链接出现在主页右边边上，只能看见一点点。
当你点开展开侧边栏的按钮，在关闭侧边栏，上面出现的那个情况就没有了！在其他页面也同样有这个问题。
我没有修改HTML、CSS代码。

**Comment by Zhang21** [comment]
应该是这串代码，每个页面都有。是Hexo渲染的问题吗？
`<div class="links-of-author motion-element">
          
            
              <span class="links-of-author-item">
                <a href="https://github.com/Zhang21" target="_blank" title="GitHub">
                  
                    <i class="fa fa-fw fa-github"></i>
                  
                    
                      GitHub
                    
                </a>
              </span>
            
              <span class="links-of-author-item">
                <a href="mailto:elite_zhang21@163.com" target="_blank" title="E-Mail">
                  
                    <i class="fa fa-fw fa-envelope"></i>
                  
                    
                      E-Mail
                    
                </a>
              </span>
            
              <span class="links-of-author-item">
                <a href="https://instagram.com/Zhang21_" target="_blank" title="Instagram">
                  
                    <i class="fa fa-fw fa-instagram"></i>
                  
                    
                      Instagram
                    
                </a>
              </span>
            
          
        </div>`

**Comment by ivan-nginx** [comment]
Can u explain in English?

**Comment by liszd** [comment]
![](https://ws3.sinaimg.cn/large/006tKfTcgy1fj7bwzxyupj30n40z8ab4.jpg)

@ivan-nginx Zhang21 means this,

When I open my homepage, I can see some links on the right side. And when open the right side bar, this bug will disappear.

**Comment by ivan-nginx** [comment]
@liszd live demo?

**Comment by liszd** [comment]
@ivan-nginx 
[http://www.zhang21.cn/](http://www.zhang21.cn/) is zhang21 website. 
[https://blog.naaln.com/](https://blog.naaln.com/) is my webiste. It also has same problem.

**Comment by ivan-nginx** [comment]
@Zhang21 @liszd what version of NexT u use? Latest master branch or release version?

**Comment by liszd** [comment]
@ivan-nginx I forked the theme in [liszd/hexo-theme-next](https://github.com/liszd/hexo-theme-next/tree/blog) and rebase with master branch [5858a19e57765d611e526f9fc4a7edfc3a307fe2](https://github.com/iissnan/hexo-theme-next/tree/5858a19e57765d611e526f9fc4a7edfc3a307fe2)

**Comment by ivan-nginx** [comment]
@liszd ok, this error appear only after this update? I see your commit 7 days ago, error was or not in that time?
And can u please temporarily disable all your custom styles and try to catch out this error again?

**Comment by liszd** [comment]
@ivan-nginx sorry, there is a little chaos on my commit.

Now I use the last [master branch](https://github.com/liszd/hexo-theme-next) (just change the _config)  . This problem also appeared. 

This error has appear several weeks.  I just solved with `links-of-author` in `custom.sty` at that time.
```
.links-of-author {
    display: block
}
```

I thought this bug only happen on me, until find Zhang21 has some problem.

**Comment by ivan-nginx** [comment]
@liszd `.links-of-author` was changed on `flex` style display when was added `icons_only` option.
But this bug is strange and i can't to catch him on my [test](http://test.almostover.ru/) site without any custom styles.

**Comment by ivan-nginx** [comment]
Fixed in #1846.
@liszd u can remove `display: block` from `custom.styl` after this update.

**Comment by ivan-nginx** [comment]
@Zhang21 if issue solved, close it please.

**Comment by liszd** [comment]
@ivan-nginx Thx, It works for me.

**Comment by Zhang21** [comment]
@liszd Sorry，I can't understand how to solve this problem according to your suggestions.

**Comment by liszd** [comment]
@Zhang21 他昨天晚上更新了，你使用他最新的代码就行了。

**Comment by Zhang21** [comment]
@liszd What mean about  use _data dir with next.yml？

**Comment by Zhang21** [comment]
@liszd Clone the new version of NexT？

**Comment by ivan-nginx** [comment]
@Zhang21 that say i, not him) I mean u can check [this](https://github.com/iissnan/hexo-theme-next#theme-configurations-using-hexo-data-files-328).

**Comment by Zhang21** [comment]
@ivan-nginx I see,think u

**Comment by Zhang21** [comment]
@ivan-nginx  @liszd  
I update it，it works true on some browser（like edge and IE），but on chrome，it also has the problem. I try to disable cache, and still exist.

**Comment by ivan-nginx** [comment]
@Zhang21 just refresh with Ctrl+Shift+T. I tested it on Chrome always.

**Comment by Zhang21** [comment]
I use your method, it's also exist.

** the problem **
![problem11](https://user-images.githubusercontent.com/18358275/30042746-ce4557bc-9225-11e7-8b3a-ebcb209c0d19.png)

** then **
![then](https://user-images.githubusercontent.com/18358275/30042776-03b8c226-9226-11e7-9119-b3f515aaf3a3.png)

**Comment by ivan-nginx** [comment]
@Zhang21 try to install latest master branch version. It must be fixed, @liszd confirmed it.

**Comment by Zhang21** [comment]
The NexT  release is v5.1.2，the newest version.

@ivan-nginx The problem is also on chrome。
@liszd 哥子，你是怎么解决的？

**Comment by ivan-nginx** [comment]
@Zhang21 https://github.com/iissnan/hexo-theme-next#download-latest-master-branch

**Comment by Zhang21** [comment]
@liszd  我已经 git pull 过了，这个 download 下来有什么区别吗？除了配置文件那些。

**Comment by liszd** [comment]
@Zhang21 我不确定你是不是真的有更新代码

他具体的修复代码在这，你没有实质性的更新
https://github.com/iissnan/hexo-theme-next/commit/edad5e331f0f145690015d30cead635f337bac4f
https://github.com/iissnan/hexo-theme-next/commit/fa2d484edf3ba91b0c64c3dc353bbfb4380ef1f1

**Comment by Zhang21** [comment]
@liszd 我改了相对应的代码，Bingo，多谢了哥子！
@ivan-nginx Bingo！think u!
