### ISSUE TITLE
Number of comments not correct (using Facebook SDK)

### ISSUE THREAD

**Issue by allenfrostline** [iissnan/hexo-theme-next#1841]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

After I comment using the Facebook SDK, the number of comments of this post on the home page should increase.

### Actual behavior 

After I commented below the post, the comment did show up in the post page, but the number of comments is still 0.

Check my [blog](http://allenfrostline.com).

### Steps to reproduce the behavior 
1. Set up Facebook SDK in the theme config file.
2. Comment in a post.
3. Check the number of comments in the home page.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

- [ ] Latest Master branch.
- [ ] Latest Release version.
- [x] Old version - **version?**

**NexT Scheme:**

- [ ] All schemes
- [x] Muse
- [ ] Mist
- [ ] Pisces
- [ ] Gemini

### Other Information 
<img width="405" alt="screen shot 2017-09-03 at 8 40 18 am" src="https://user-images.githubusercontent.com/24261329/30001118-1f12482e-9084-11e7-8ef0-0f650e2a8ad4.png">
<img width="679" alt="screen shot 2017-09-03 at 8 40 08 am" src="https://user-images.githubusercontent.com/24261329/30001117-1f05257c-9084-11e7-88b4-4e8cfe0b2583.png">

**Comment by ivan-nginx** [comment]
1. What version u use?
2. Try to update to latest release version.

**Comment by allenfrostline** [comment]
@ivan-nginx Thanks for the fast reply! I am using version 5.1.1 and I'm not sure how to safely upload without changing the configurations. I've done several deep changes to the theme, not only the `config` file. If you have time, please check my blog whether I can update directly.

**Comment by ivan-nginx** [comment]
U can save your configuration in `_data` directory. Please, check main readme and update section about this.
About changes to source files — u can also save all changes in `custom.styl` files. Just add any style there u want, a talking about it many times, u can search it in issues.
But, if u already changed `swig` or any other files, u can create puul request and make some additions in configuration files.

**Comment by allenfrostline** [comment]
@ivan-nginx I see. Thanks!

**Comment by ivan-nginx** [comment]
@allenfrostline issue resolved?

**Comment by allenfrostline** [comment]
Sorry but the number is still 0. It didn't help.

**Comment by ivan-nginx** [comment]
@allenfrostline try to install clean Hexo and clean HexT theme latest version on separated test domain.

**Comment by ivan-nginx** [comment]
If issue solved, close it please.

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?
