### ISSUE TITLE
添加默认显示文章所有目录包括所有子目录的配置选项

### ISSUE THREAD

**Issue by no5ix** [iissnan/hexo-theme-next#1842]
一次性显示文章里所有的目录, 比如: 目前是到某个一级目录下才能显示这个一级目录的子目录.

希望可以添加是否显示所有目录的配置选项.

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by nosix1992** [comment]
the subdirectory of the first level directory that can be displayed at the moment.
Pease add configuration options that show all directories.

**Comment by Loveslife** [comment]
我有同样的想法。
I hope that the post will always show all the title in the direcory ,not when i move to the title.

**Comment by ivan-nginx** [comment]
Can anyone give some examples on it?

**Comment by nosix1992** [comment]
```
# 1

## 2

## 3

# 4

## 5

## 6
```
Only when i move to #1 will the ##2 and ##3 display on the Sidebar, but ##5 and ##6 disappear,
now we can see:
# 1

## 2

## 3

# 4

then i move to #4 , the ##5 and ##6 display on the Sidebar, but ##2 and ##3 disappear, 
now we can see:
# 1

# 4

## 5

## 6

WE WANT:
All the titles(#1, ##2, ##3, #4, ##5, ##6) are always displayed on the Sidebar.

Just like this :

# 1

## 2

## 3

# 4

## 5

## 6

**Comment by ivan-nginx** [comment]
Like [this](http://test.almostover.ru/toc-test-page/)? All work fine, don't see any bugs.

***

Try to check [latest master branch](../#download-latest-master-branch). Issue still exists?

***

Also, mb it help to u: #1771.
