### ISSUE TITLE
如何自定义每篇博文下面的copyright的信息 How to customize the information of each blog post copyright

### ISSUE THREAD

**Issue by BarryLiu1995** [iissnan/hexo-theme-next#1843]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
中文描述：如果我设置了post_copyright为true，那么每篇博文下面就会有copyright的相关信息，比如作者，地址。但是如果有些博文我是转载过来的，需要修改copyright的信息，不知如何做到

English description：If I set the post_copyright to true, then each blog below there will be copyright related information, such as the author, address. But if I get some other's blog posts to show on my blog, I am not the original author, so I need to modify the copyright information, I do not know how to do

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - v5.?.?
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
Brower: Chrome latest version
System: Win10

**Comment by ivan-nginx** [comment]
> But if some blog posts I reproduced over, I am not the original author
Don't understand what u mean? Can u tell a lot about it or give some demo or anything?

**Comment by BarryLiu1995** [comment]
@ivan-nginx I had modified my description about my problem, so check again please!

**Comment by ivan-nginx** [comment]
> give some demo or anything?

**Comment by BarryLiu1995** [comment]
if my post like this
```
title: XXXXX
date: XXXXX
tags:
- XXXXX
categories: [XXXXX]
comment: true
author: A
URL: B
```
then I can get the result like this

![2017-09-04_18-10-49](https://user-images.githubusercontent.com/20590350/30022437-e28a6bbe-919d-11e7-8247-3b8660e675d1.png)

**Comment by liszd** [comment]
@ivan-nginx 
BarryLiu means that, he reprinted some articles from other's blog. So he need to add original blog's author and url into copyright on his blog.

**Comment by Summyj** [comment]
我觉得如果是转载过来的话，就关掉下边的copyright信息。然后直接在文末加上原文链接就好了啊

**Comment by BarryLiu1995** [comment]
@Summyj 我现在的解决办法就是这样的，但觉得能用代码解决的问题就用代码解决更好，就不用手动添加

**Comment by Haocen** [comment]
The copyright info at the bottom doesn't really mean having the copyright of everything on the page, take GitHub for example, you can see:

```
© 2017 GitHub, Inc.
```

on every single page, will you assume GitHub has the copyright of the words I'm typing?

I suggest you simply add additional copyright blog in your post.

**Comment by dragonstylecc** [comment]
@Summyj  如何关闭部分文章的copyright信息？

**Comment by ivan-nginx** [comment]
Added in #1898 (PART 5).
