### ISSUE TITLE
Sidebar offset from top menubar show wider in Safari

### ISSUE THREAD

**Issue by Voleking** [iissnan/hexo-theme-next#1844]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

Sidebar offset from top menubar show normal in Safari `Version 10.1.2 (12603.3.8)`.

### Actual behavior 

<img width="348" alt="screen shot 2017-09-04 at 5 43 47 pm" src="https://user-images.githubusercontent.com/13161779/30021072-b0074504-9198-11e7-8a95-4ab7ec95a689.png">

### Steps to reproduce the behavior 
1. open http://notes.iissnan.com in safari
2. sometime need refresh

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - v5.?.?
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Please, give live test on latest releases or master branches. On Iissnan site is not latest release.

**Comment by Voleking** [comment]
Sorry, After I deployed it, everything is fine now.
It seems like that this issue only occurs in `hexo s`.

**Comment by ivan-nginx** [comment]
If issue solved, close it please.

**Comment by Voleking** [comment]
@ivan-nginx Sorry, everything only work fine on first visit. After I refresh, this issue occurs again.
[my blog](https://blog.voleking.me)
[source code](https://github.com/Voleking/blog)

**Comment by ivan-nginx** [comment]
@Voleking are u sure what your settings is fine?

> https://blog.voleking.me

```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.voleking.me
root: /
```

**Comment by Voleking** [comment]
Sorry for my fault. 😢 I updated my setting now.
BTW, I refresh my site and this issue occurs randomly.

**Comment by ivan-nginx** [comment]
Please, try to follow next steps:

1. Backup your source of `themes/next` directory.
2. Switch to latest release version (5.1.2) (see `Download latest master branch.` section in main readme).
3. Try to catch same error by refreshing browser with `CTRL` + `SHIFT` + `R`.

And give me the anser please.

**Comment by Voleking** [comment]
I try the steps above but still can catch this error.

**Comment by ivan-nginx** [comment]
@Voleking all worked fine? Please, if u catch any bugs, first of all try to install clean Hexo and NexT versions.

**Comment by Voleking** [comment]
@ivan-nginx I found this bug only occur when site title was too long and has space, like:
```yaml
# Site
title: aaaaa aaaaa
```

**Comment by ivan-nginx** [comment]
Then it must be bug. Try to reproducte this error on separated test site and we will catch this bug. For now i don't see this bug at this year in many blogs and in mu blog too. And on my blog i always use titles with spaces, but sidebar from header marign not can use any titles.

**Comment by Voleking** [comment]
Yes, I reproducte this error on separated test site.
Here are two conditions for triggering a bug:
1. The site title contains spaces.
2. The site title contains more than 11 letters.

**Comment by ivan-nginx** [comment]
Can i see live demo?

**Comment by Voleking** [comment]
Here is the [live demo](https://voleking.github.io/test/) and [code](https://github.com/Voleking/test)

**Comment by ivan-nginx** [comment]
@Voleking so, Safari Version 10.1.2 (12603.3.8)?

**Comment by Voleking** [comment]
@ivan-nginx Yeah, Safari Version 10.1.2 (12603.3.8) have this bug.

**Comment by ivan-nginx** [comment]
@Voleking this bug avoid with two variants:

* Disable custom fonts in NexT config (will changed to default in next release version).
   ```yml
   font:
     enable: false
   ```
* Set «Web Safe» fonts for `global` (and if u want to change logo font, on `logo` too):
   ```yml
     global:
       external: false
       family: Times New Roman
   ```
I don't know why Safari brake margins within custom font settings and it's very weird. All other browsers work with custom fonts fine.

***

If issue solved, close it please.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/b9968b6be0a8b20be80adad185ee94d713672e52
