### ISSUE TITLE
Disqus出不来

### ISSUE THREAD

**Issue by fastzhong** [iissnan/hexo-theme-next#1851]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Disqus讨论会出现在文章末

### Actual behavior 
没有出现

### Steps to reproduce the behavior 
1. _config.yml：
# Disqus
disqus:
  enable: true
  shortname:
  count: true
2. 重新启动 hexo

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by l900416** [comment]
我觉得应该是Disqus在国内被屏蔽了，一些文件加载不出来。
例如：https://shortname.disqus.com/embed.js

**Comment by ivan-nginx** [comment]
@fastzhong solved?

**Comment by Acris** [comment]
@fastzhong Disqus was blocked in China by the Great Firewall.

**Comment by fastzhong** [comment]
不是，我不在国内，改用gitcomment。

**Comment by ivan-nginx** [comment]
Added Gitm**i**nt support in#1919.
