### ISSUE TITLE
Cannot render correctly (not `vendor` dir problem)

### ISSUE THREAD

**Issue by Joilence** [iissnan/hexo-theme-next#1854]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
正常渲染

### Actual behavior 

The website cannot render correctly.

大面积空白，渲染文件如 jq 等无法加载。

### Steps to reproduce the behavior 

visit the site: https://joilence.github.io/algorithms-course/

访问：https://joilence.github.io/algorithms-course/

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 

I have tried add `.nojekyll` file into root directory both of blog and next theme directory and this didn't; work. Since I create the blog today, `lib` dir has replaced `vendor` dir.

尝试过在根目录和 next 根目录添加 `.nojekyll` 文件，也不行。另外由于是今天新建的 Blog，next 的 vendor 目录已经默认叫做 lib 了。

**Comment by ivan-nginx** [comment]
@Joilence > Since I create the blog today

`hexo clean && hexo g`?

**Comment by Joilence** [comment]
@ivan-nginx tried, the problem remains.

**Comment by ivan-nginx** [comment]
`F12`, see console log: 404 not found for many files. It seems, there is `url` or `path` option in Hexo config problem.

**Comment by Joilence** [comment]
@ivan-nginx Since the address is `https://joilence.github.io/algorithms-course/`, I thought the site is put in a subduer of `joilence.github.io` and modify `url` value to `/algorithms-course/`, and the `option` remains as default.

**Comment by ivan-nginx** [comment]
@Joilence so? NexT theme is not working and it's buggy and ugly theme **or** u just wrong configure your Hexo settings and write excess issue in NexT and also still not close it?

**Comment by Joilence** [comment]
I got it. Sorry for my being reckless and thank you for your help.

**Comment by Joilence** [comment]
@ivan-nginx I got it. Sorry for my being reckless and thank you for your help.
