### ISSUE TITLE
Option to disable wechat/alipay/bitcoin reward animation.

### ISSUE THREAD

**Issue by ivan-nginx** [iissnan/hexo-theme-next#1856]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Option to enable/disable animation.

### Actual behavior 
Animation on reward is hardcoded.

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[ ] Latest Release version.
[ ] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[ ] Gemini
```

**Comment by xy2401** [comment]
thank you for this issue.
i like static page,and image with animation(event) cannot be directly identified at wechat browser.XD

**Comment by ivan-nginx** [comment]
@stevenjoezhang this link: https://github.com/iissnan/hexo-theme-next/pull/687#issuecomment-327529147

If I right understand, he want to disable shaking animation after user moving in cursor to any donate picture.

**Comment by stevenjoezhang** [comment]
Added in https://github.com/theme-next/hexo-theme-next/pull/695
