### ISSUE TITLE
每次hexo d部署后，index页面消失

### ISSUE THREAD

**Issue by realchoi** [iissnan/hexo-theme-next#1857]
# I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 
####index页面消失了！！！

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
[](https://ws1.sinaimg.cn/large/005Ib0ZLgy1fjb46np2o9j30rd05rmxi.jpg)

**Comment by ivan-nginx** [comment]
Live demo?

**Comment by realchoi** [comment]
###部署后由于index消失，变成404

**Comment by realchoi** [comment]
**由于index消失，页面变成404，clean也没用。**

**Comment by realchoi** [comment]
一些错误：

`Error: F:/Hexo/themes/next/source/css/_common/components/highlight/highlight.styl:78:30
   74|
   75|   .gutter pre {
   76|     padding-left: 10px
   77|     padding-right: 10px
   78|     color: $highlight-gutter.color
------------------------------------^
   79|     text-align: right
   80|     background-color: $highlight-gutter.bg-color
   81|   }

$highlight-gutter has no property .color
`

**Comment by l900416** [comment]
hexo g 可以正常生成静态页面吗？

**Comment by realchoi** [comment]
@l900416 hexo g时没有生成html

**Comment by realchoi** [comment]
@l900416 只能生成tags目录下的index.html页面

**Comment by l900416** [comment]
@realchoi  使用hexo生成静态网址的时候报了什么错误吗？
我觉得你应该先检查下你的环境，比如：npm、nodejs、hexo等。或者干脆把你的源码放出来。。

**Comment by realchoi** [comment]
@l900416 错误我在上面贴出来了啊，而且我用5.1.0版本没有发生错误。

**Comment by Haocen** [comment]
@realchoi 请删除你的主题文件夹用最新版本再试。

**Comment by JERE-MIAH** [comment]
我错误应和你一样，是不是上传了以后2017文件夹和最下面的index以及一堆文件夹都没有了

**Comment by realchoi** [comment]
@JERE-MIAH 是的

**Comment by petteran** [comment]
我的也是这样,你解决了吗?

**Comment by JERE-MIAH** [comment]
我好像是删除deploy文件夹解决的，记不清了，很久了，删除deploy文件夹后再clean然后再试试

2018年1月16日 上午11:20，"petteran" <notifications@github.com>写道：

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
