### ISSUE TITLE
本地localhost:4000显示和hexo部署后显示的页面不一样

### ISSUE THREAD

**Issue by mrzhaisp** [iissnan/hexo-theme-next#1859]
本地localhost:4000显示和hexo部署后显示的页面不一样。

**Comment by ethanzhoujie** [comment]
推荐这个帖子，写的非常详细 https://liguanghe.github.io/2017/05/22/blogRebuilt/

**Comment by mrzhaisp** [comment]
已解决，谢谢大神！！！------------------ 原始邮件 ------------------发件人: Ethan Zhou  <notifications@github.com>发送时间: 2017年9月9日 06:17已搞定，收件人: iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>抄送: mrzhaisp <mr_zhai_sp@126.com>, Author <author@noreply.github.com>主题: 回复：[iissnan/hexo-theme-next] 本地localhost:4000显示和hexo部署后显示的页面不一样 (#1859)推荐这个帖子，写的非常详细 https://liguanghe.github.io/2017/05/22/blogRebuilt/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iissnan/hexo-theme-next","title":"iissnan/hexo-theme-next","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iissnan/hexo-theme-next"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ethanzhoujie in #1859: 推荐这个帖子，写的非常详细 https://liguanghe.github.io/2017/05/22/blogRebuilt/"}],"action":{"name":"View Issue","url":"https://github.com/iissnan/hexo-theme-next/issues/1859#issuecomment-328226677"}}}

**Comment by summir** [comment]
404了

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
