### ISSUE TITLE
hexo升级到3.1.1的问题

### ISSUE THREAD

**Issue by flashlab** [iissnan/hexo-theme-next#186]
升级之后代码高亮失效，more标签也不起作用了，有人出现这些问题吗？
***
确认已经fix~ 先不关闭吧，应该能解决一些共性问题

**Comment by iissnan** [comment]
3.1.1 似乎取消了代码块语言自动检测，也就是说，如果没有指定代码所使用的语言就没有高亮。
more 标签没有看到有相关的改动。

明天我升级上去看看。

**Comment by eurusd** [comment]
增加了什么功能？

**Comment by iissnan** [comment]
@eurusd 貌似一两句话描述不完这两个版本的更新，看具体的 Release log 吧：

- [3.1.0](https://github.com/hexojs/hexo/releases/tag/3.1.0)
- [3.1.1](https://github.com/hexojs/hexo/releases/tag/3.1.1)

**Comment by iissnan** [comment]
@flashlab 升级到了 3.1.1，发现要手动做两个事情：

1. 升级 hexo-generator-index 至 0.1.2 
2. 增加 `auto_detect: true` 到站点 `_config.yml` 的 `hilight` 部分，否则默认自动检测语言高亮是关闭的

        highlight: 
          enable: true
          auto_detect: true
          line_number: true
          tab_replace: ''

另外，More 标签确实出现问题了，标题链接似乎也消失了，貌似 Bug 一堆 :sob:

**Comment by iissnan** [comment]
`is_home()` helper 有问题。。。

**Comment by flashlab** [comment]
辛苦了╯▂╰我先想办法回到老版本-_-||

**Comment by iissnan** [comment]
Fixed 了。使用 Hexo 的 is_xx helper 挺尴尬的。
