### ISSUE TITLE
Configuration override is not possible. Please provide a flag

### ISSUE THREAD

**Issue by julianxhokaxhiu** [iissnan/hexo-theme-next#1860]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

Hi,

I am contacting you because I really like this theme but I found something that could improve the usage of this theme, especially is you use it as a submodule.

What I basically need is a way to override totally the menu structure with my custom links. Although at the current status the default `_config.yml` defines a Home link which I can't remove/override. Also, since Hexo has the issue that languages cannot be overridden outside of the theme, I am basically stuck with the "Home" labelling even If I don't need it like that.

What I purpose is [providing a flag in `_data/next.yml`](https://github.com/iissnan/hexo-theme-next/blob/master/scripts/merge-configs.js#L10) that allows the user to decide if to merge the configs or to override them.

Thank you and best regards,
Julian

### Expected behavior 
When using `_data/next.yml` the configuration is fully overridden.

### Actual behavior 
When using `_data/next.yml` the configuration is merged.

### Steps to reproduce the behavior 
1. Try to comment the `menu` section.
2. Run `hexo clean && hexo generate`
3. Run `hexo server`

* Link to demo site with this issue: N/A ( I don't want to publish it yet with this bug )
* Link(s) to source code or any usefull link(s): https://github.com/julianxhokaxhiu/blog.julianxhokaxhiu.com/blob/master/src/_data/next.yml

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 
```shell
$ hexo --version
hexo: 3.3.9
hexo-cli: 1.0.3
...
```

**Comment by nielinjie** [comment]
Hexo has a way to override theme config, why NEXT design another way? Have I miss anything here?
https://github.com/hexojs/hexo/pull/757

**Comment by julianxhokaxhiu** [comment]
Fair enough, I was not aware of that. Willing to create a dedicated MR?

**Comment by ivan-nginx** [comment]
@nielinjie yes, please create new issue. Maybe need to do global refactoring in override option.

**Comment by nielinjie** [comment]
#2006
