### ISSUE TITLE
Something wrong with "social---E-Mail"

### ISSUE THREAD

**Issue by Dedsecr** [iissnan/hexo-theme-next#1866]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
use E-mail link properly

### Actual behavior 

![image](https://user-images.githubusercontent.com/25794491/30273972-f11a646e-972d-11e7-9bad-82bbb500501d.png)
![image](https://user-images.githubusercontent.com/25794491/30274178-d871fe94-972e-11e7-997d-fefa2a81055c.png)

How to solve it?

### Steps to reproduce the behavior 
there is my source.
![image](https://user-images.githubusercontent.com/25794491/30274015-30d16422-972e-11e7-9218-c0888c80ca40.png)

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
In latest master branch for now u should specify your e-mail by `mailto:xxx@qq.com`.
```yml
social:
  GitHub: https://github.com/ivan-nginx || github
  E-Mail: mailto:ivan.nginx@gmail.com || envelope
```

**Comment by Dedsecr** [comment]
thx
