### ISSUE TITLE
社交链接的图标无法正常显示

### ISSUE THREAD

**Issue by Loveslife** [iissnan/hexo-theme-next#1867]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
显示社交链接图标

### Actual behavior 
配置后依然无法显示社交链接的图标
微博那个链接的信息我没有改，但是图标应该会变。实在不知道哪里有问题了。。。
![4f1220d4-971b-46a4-89de-f1bdd441d969](https://user-images.githubusercontent.com/23011675/30311364-759caa50-97c7-11e7-9e4c-90bb97d7b91a.png)
![9f295c1e-9e3c-4aad-95f1-9fb88835f413](https://user-images.githubusercontent.com/23011675/30311443-cd70f876-97c7-11e7-8b7e-0fc659c2cc2b.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A
* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
See #1866 issue.

**Comment by Spongecaptain** [comment]
#Google: https://plus.google.com/yourname || google
以上面的格式进行网址和图标的关联配置
