### ISSUE TITLE
页面设置关闭评论后报错

### ISSUE THREAD

**Issue by ChangingFond** [iissnan/hexo-theme-next#1868]
博客使用的是畅言评论，在“关于“页面的index.md中设置comments: false，hexo g -d发布后的页面，用F12控制台查看有如下错误：
`plugins.count.js: Uncaught TypeError: Cannot read property 'parentNode' of null`

**Comment by ivan-nginx** [comment]
Can u give more info about versions of Hexo & NexT, OS, NPM, Node?

**Comment by ChangingFond** [comment]
Hexo 3.3.7
Next 5.1.1
OS Centos7.2
Node 8.3.0

**Comment by ivan-nginx** [comment]
Can u try to install [latest release NexT version](https://github.com/iissnan/hexo-theme-next#download-latest-release-version)? And clean Hexo, without any plugins, etc.

**Comment by chaixuhong** [comment]
@ChangingFond http://www.chaixuhong.com/article/NEXT%E4%BD%BF%E7%94%A8%E7%95%85%E8%A8%80%E7%9A%84%E9%97%AE%E9%A2%98.html

**Comment by ChangingFond** [comment]
@chaixuhong Thank you very much!

**Comment by ChangingFond** [comment]
fixed #xxx

**Comment by ChangingFond** [comment]
fixed #xxx

**Comment by ChangingFond** [comment]
fixed #1868

**Comment by ChangingFond** [comment]
Fixes #1868
