### ISSUE TITLE
更新到最近一版的release图标前变成问号了

### ISSUE THREAD

**Issue by leeyuanhe** [iissnan/hexo-theme-next#1869]
![image](https://user-images.githubusercontent.com/17116084/30386255-f66125f2-98db-11e7-87cd-20f96e7d43ab.png)

前台页面在如下位置有一个tab属性报错 
![image](https://user-images.githubusercontent.com/17116084/30386549-a8003668-98dc-11e7-85e7-458166ffefb4.png)

tab：“,”   (Uncaught SyntaxError: Unexpected token ,)

**Comment by ivan-nginx** [comment]
See #1867 / #1866 issues.

If solved, close it please.

**Comment by leeyuanhe** [comment]
Finally, i revert to v5.1.1  and  did't  change any  configration , it became normal.
So  maybe  there was something wrong with the latest release

**Comment by ivan-nginx** [comment]
Maybe.
Anyway, too small info. To resolve it need more. For now both latest release and latest master branch worked fine.
