### ISSUE TITLE
Next 在chrome version 43.0.2357.81 m 下显示存在问题？

### ISSUE THREAD

**Issue by NeilJee** [iissnan/hexo-theme-next#187]
升级了CHROME后，Next即显示出现问题。

截图如下：

![hi] (http://7xj90c.com1.z0.glb.clouddn.com/QQ截图20150528184651.png)
![hi] (http://7xj90c.com1.z0.glb.clouddn.com/QQ截图20150528184658.png)

有人也遇到过吗

**Comment by alfredtofu** [comment]
等，等，等！只是字体还没加载出来。

或者把换成大家都有的字体，修改文件
```
source/css/_variables/base.styl
```
把`$font-family-base`里的`lato`去掉。

**Comment by NeilJee** [comment]
这和我升级chrome有关系吗？ 确定是这个原因？

**Comment by NeilJee** [comment]
果然有效果，不过为啥字体加载要这么久，都等了几个小时还是这样

**Comment by iissnan** [comment]
可能是字体请求失败了，自定义字体可以参考 [issue 111](https://github.com/iissnan/hexo-theme-next/issues/111)
