### ISSUE TITLE
怎么改变动态背景的颜色？

### ISSUE THREAD

**Issue by sjxt** [iissnan/hexo-theme-next#1870]
在next配置文件中设置了动态背景为true，之后怎么设置颜色呀

**Comment by ivan-nginx** [comment]
About what dynamic background u talk?

**Comment by sjxt** [comment]
Yes,  I just set up in the next configuration file ----`canvas_nest: true`   Now，I want to change the color

**Comment by ivan-nginx** [comment]
In `source/css/_variables/custom.styl`:
```
$body-bg-color                = #f5f7f9
```
Close it if solved.

**Comment by sjxt** [comment]
OK, thanks
