### ISSUE TITLE
Next.Mist主题底栏高度问题

### ISSUE THREAD

**Issue by newdee** [iissnan/hexo-theme-next#1872]
不知道从哪天起，发现Mist的主题的底栏，就是有powered by的那一栏，在个人介绍、标签、分类等页面中，该栏会跑到屏幕中间，而不是在底部。大概是因为内容比较少。请问是要修改footer么？

**Comment by ivan-nginx** [comment]
See #1824 pull to fix this.

**Comment by newdee** [comment]
Thanks， but the 2 issues both have not solve the problem. They are in Gemini and Pisces, and I use Mist. And if I refer to the #1818 , it can set the footer always keep in bottom,  BUT the pagination is missing, and I cannot go to other page after then. 
So, the issues you gave cannot fix this problem.

**Comment by ivan-nginx** [comment]
@newdee fotter used by all themes. See #1807 and #1824 pulls.
