### ISSUE TITLE
留白尽量少点（最好能自定义宽度），目录样式不太好、文章调色稍微不协调

### ISSUE THREAD

**Issue by Seifon** [iissnan/hexo-theme-next#1875]
你们的博客主题很棒，不过有几点小毛病，希望能够改进一下

1、文章尽量铺满比较好

2、文章目录背景色不协调。建议采用码云那种风格的目录列表

![](http://ww1.sinaimg.cn/large/8e24145egy1fjk2eokdiaj20g20bbdgg.jpg)

3、背景色和字体色不太协调，看着比较费眼。建议调整一下。

对了，我用的 Mist scheme

**Comment by Haocen** [comment]
您所提供的建议很好，但是缺乏建设性。

1、文章尽量铺满比较好（请给出相应的页边距，行距等参数，并提供示例图，最好能直接提供预编译的 css 样式表和源码）

2、文章目录背景色不协调。建议采用码云那种风格的目录列表（哪种风格？请给出详细设计细节，并提供示例图，最好能直接提供预编译的 css 样式表和源码）

3、背景色和字体色不太协调，看着比较费眼。建议调整一下。（哪种配色？请给出详细设计细节，并提供示例图，最好能直接提供预编译的 css 样式表和源码）

This issue is too vague to provide any value.

**Comment by Neveryu** [comment]
围观

**Comment by stormxing** [comment]
666

**Comment by ivan-nginx** [comment]
Issue will be closed due not enought information.
