### ISSUE TITLE
How to modify the margin between each post in the home page(Mist theme)?

### ISSUE THREAD

**Issue by newdee** [iissnan/hexo-theme-next#1878]
I use the Mist theme, and I think the margin between two posts looks too bigger. So how to decrease the distance between each post?

**Comment by newdee** [comment]
Sorry, I have solved it.
```
.post.post-type-normal{margin: 0px 0px 0px 0px;} 
```

**Comment by ivan-nginx** [comment]
Also, do not touch source files. U can simply add any modifications in custom styles file:
`next/source/css/_custom/custom.styl`:
```css
.post.post-type-normal {
  margin: 0
}
```
All styles will be rewrited by your own custom styles.

Custom styles files list:
* next/source/css/_custom/custom.styl
* next/source/css/_variables/custom.styl

Custom layouts files list:
* next/layout/_custom/header.swig
* next/layout/_custom/sidebar.swig
* next/layout/_partials/head/custom-head.swig

***

If solved, close it please.
