### ISSUE TITLE
原来删除的tags和categories 还是会在统计数量中。

### ISSUE THREAD

**Issue by dougen** [iissnan/hexo-theme-next#188]
原来删掉的tags和categories 在页面中还是会统计数量。

**Comment by iissnan** [comment]
看起来是 Hexo 的一个 bug。

**Comment by iissnan** [comment]
找到了一个解决方法：

1. 删除站点目录下的 `db.json` 文件
1. 执行 `hexo clean`
1. 重新生成 `hexo g`
