### ISSUE TITLE
Font size gets smaller than before, is it a feature or a bug?

### ISSUE THREAD

**Issue by panqiincs** [iissnan/hexo-theme-next#1889]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The font size of Home, Archives, Catetories, Tags and About pages should be the same.
主页、分类、归档、标签和关于页面的字体大小应该一致

### Actual behavior 
The font size of Home, Categories, Tags and About pages is much smaller than before, only Archives and Tags pages font size is as big as before.
主页、分类和关于页面的字体变小，只有归档和标签页面字体和以前保持一致

The pictures blow shows the difference:
下面是差异对比：

Home Page，主页：

Tag v5.1.2:
![image](https://user-images.githubusercontent.com/3938330/30600738-de0cedfe-9d92-11e7-9a89-35b44d22e101.png)

Latest version:
![image](https://user-images.githubusercontent.com/3938330/30600779-f1dc5e32-9d92-11e7-8735-e03b14a19fb9.png)

About Page，关于页面：

Tag v5.1.2:
![image](https://user-images.githubusercontent.com/3938330/30600873-20ddb4ce-9d93-11e7-8d10-c4a9a4a683d6.png)

Latest version:
![image](https://user-images.githubusercontent.com/3938330/30600892-2dc42ccc-9d93-11e7-8912-68559585f834.png)

### Steps to reproduce the behavior 
1. Upgrade my theme version from git Tag v5.1.2 to newest  从Tag v5.1.2升级到最新版
2. Generate my blog 重新生成博客
3. See the result 查看结果

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
It is #1880 fix. U can ask @julianxhokaxhiu about this.

**Comment by julianxhokaxhiu** [comment]
You're right. The rule for post-body must be moved to mobile only.

I'll create a PR for this to fix it.

**Comment by ivan-nginx** [comment]
@julianxhokaxhiu no no no, no need to create NEW PR, please. So it in same PR please.

**Comment by ivan-nginx** [comment]
@julianxhokaxhiu oh shed. I forgot it. There is what i'm talking about before: no need to do fast and smalls PR, see it?
Ok, try to fix this issue, ok?

**Comment by julianxhokaxhiu** [comment]
👌🏻
