### ISSUE TITLE
页面显示不正常 GET /css/main.css?v=5.1.2 404

### ISSUE THREAD

**Issue by dinghmcn** [iissnan/hexo-theme-next#1890]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
能正常使用 

### Actual behavior 
![screenshot_20170919_235538](https://user-images.githubusercontent.com/15715884/30602712-fff7fc1a-9d97-11e7-9a8b-34fae409ba08.png)

### Steps to reproduce the behavior 
1. git clone https://github.com/iissnan/hexo-theme-next themes/next
2. theme: next
3. hexo clean && hexo g && hexo s --debug

* Link to demo site with this issue: https://dinghmcn.github.io/
* Link(s) to source code or any usefull link(s): https://github.com/dinghmcn/dinghmcn.github.io

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
错误日志：
16:18:14.511 DEBUG Generator: asset
16:18:14.520 INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
16:18:14.527 DEBUG Database saved
16:18:18.589 DEBUG Rendering index: index.html
GET / 200 84.027 ms - -
GET /css/main.css?v=5.1.2 404 4.637 ms - -
GET /lib/fancybox/source/jquery.fancybox.css?v=2.1.5 200 7.384 ms - -
GET /lib/font-awesome/css/font-awesome.min.css?v=4.6.2 200 6.697 ms - -

public/css/ 下只有 main.styl
~:cat public/css/main.styl
// CSS Style Guide: http://codeguide.co/#css

$scheme    = hexo-config('scheme') ? hexo-config('scheme') : 'Muse';
$variables = base $scheme custom;
$mixins    = base $scheme custom;

// Variables Layer
// --------------------------------------------------
for $variable in $variables
  @import "_variables/" + $variable

// Mixins Layer
// --------------------------------------------------
for $mixin in $mixins
  @import "_mixins/" + $mixin;

// Common Layer
// --------------------------------------------------

// Scaffolding
@import "_common/scaffolding";

// Layout
@import "_common/outline";

// Components
@import "_common/components";

// Schemes Layer
// --------------------------------------------------
@import "_schemes/" + $scheme;

// Custom Layer
// --------------------------------------------------
@import "_custom/custom";

**Comment by ivan-nginx** [comment]
Try to use standart Hexo theme, is there errors too?

**Comment by unclejimbo** [comment]
我刚也有这个问题，样式显示不出，然后把 font enable 关了就恢复正常了

**Comment by dinghmcn** [comment]
重新创建hexo init blog就可以了，应该是我的hexo目录有问题，感谢大家回复。
