### ISSUE TITLE
configuration file override failed

### ISSUE THREAD

**Issue by cutelittleturtle** [iissnan/hexo-theme-next#1893]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Set in `website/_config.yml `:

```
menu:

        home: /

        categories: /
```

Set in `website/themes/next/_config.yml`:
````
override: false/true (tried both)

menu:

        home: /

        #categories: /
```

Except categories displays in menu

### Actual behavior <!-- (实际行为) -->

categories does not display in menu

### Steps to reproduce the behavior <!-- (重现步骤) -->
1. hexo new page categories and add `type: categories`
2. set `override: true` or `override: false` in `theme/next/_config.yml`, tried both
3. delete db.json, hexo clean, re-generate multiple types

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**
<!-- Check one with "x" (使用 "x" 选择) -->
```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**
<!-- Check one with "x" (使用 "x" 选择) -->
```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information <!-- (Like Browser, System, Screenshots) -->
I think the main problem is something went wrong for the default _config.yml overriding the theme's configuration file. I tried to set excerpt option in the default _config.yml, which does not work either.

**Comment by ivan-nginx** [comment]
Wrong way to use it. Please, see [update](https://github.com/iissnan/hexo-theme-next#theme-configurations-using-hexo-data-files-328) section in main readme.

**Comment by nielinjie** [comment]
Hexo has a way to override theme config, why NEXT design another way? Have I miss anything here?
hexojs/hexo#757

**Comment by ivan-nginx** [comment]
@nielinjie please create new issue. Maybe need to do global refactoring in override option.

**Comment by nielinjie** [comment]
#2006
