### ISSUE TITLE
main.css 生成后内容为空，导致blog页面排版丢失

### ISSUE THREAD

**Issue by coyawa** [iissnan/hexo-theme-next#1894]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
hexo g -d 后，生成的public文件夹里 css/main.css 应该有内容

### Actual behavior 
1. 出现ParseError错误
2. main.css 无内容，为空

### Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/4596255/30626700-8aee2b9a-9d99-11e7-9184-98165fc34560.png)

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by AlynxZhou** [comment]
@coyawa 建议提供一下详细的报错信息，现在的信息不足以判断问题所在，谢谢！
@ivan-nginx He means while generating got a ParseError, and generated main.css is empty, I asked him for more info of error.
