### ISSUE TITLE
如何将首页和归档页的博文按照更新时间排序？

### ISSUE THREAD

**Issue by liqiang311** [iissnan/hexo-theme-next#1895]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

按照更新时间排序显示博文。

### Actual behavior 

现在是按照发布时间显示。

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by ivan-nginx** [comment]
This is not NexT theme issue, this is Hexo.

**Comment by geekrainy** [comment]
@ivan-nginx I think this is the NexT's  job.The Hexo is responsible for data generation and the theme is responsible for rendering.

**Comment by ivan-nginx** [comment]
Maybe, but i don't understand what he's want. Google translate it to me like archives sort ordering and archives generate by Hexo. Mb i just not und what he's meaning because i don't understand Chinese.

**Comment by liqiang311** [comment]
@ivan-nginx Sorry, What I want is sorting the blog post in homepage and archive page by updated time, and now it is sorted by created time.

**Comment by ivan-nginx** [comment]
I understand it but it's will be better to implement in Hexo main generated functions and on all themes, not only for NexT.

**Comment by liqiang311** [comment]
OK, I understand it and thank you. Maybe it should be configured in hexo's configuration file.

**Comment by ivan-nginx** [comment]
@liqiang311 i think they implement it.

**Comment by geekrainy** [comment]
@liqiang311 This plugin has an optional configuration item. See https://github.com/hexojs/hexo-generator-index.

```
index_generator:
  path: ''
  per_page: 10
  order_by: -updated
```

Configured it in site _config.yml.
:smiley::smiley:

**Comment by liqiang311** [comment]
@ivan-nginx @geekrainy Thank you very much!
