### ISSUE TITLE
页面最后一篇文章部分信息无法显示

### ISSUE THREAD

**Issue by Loveslife** [iissnan/hexo-theme-next#1897]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![2017-09-22 6 02 32](https://user-images.githubusercontent.com/23011675/30739519-423e79d0-9fc0-11e7-8b17-9e75301515ed.png)
文章和底部中间会有空白

### Actual behavior 

![2017-09-22 5 54 33](https://user-images.githubusercontent.com/23011675/30739401-c92679a8-9fbf-11e7-873d-9525c75a9de1.png)
页面的最后一篇文章的部分信息会被footer挡住。

当我把每页文章设置为3时，页面底部应该会有分页显示。但是这里应该也是被挡住了。
![2017-09-22 6 11 56](https://user-images.githubusercontent.com/23011675/30739959-c03322f4-9fc1-11e7-9b7c-27c90efd5f10.png)

可以访问 changle.red查看效果。

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by Loveslife** [comment]
这个问题好像只会在Mist主题下出现，我设置成Pisces主题后没有这种情况，求大佬告诉一下该怎么设置

**Comment by ivan-nginx** [comment]
Don't und u and don't see any bugs on changle.red.

**Comment by Haocen** [comment]
请提供配置文件并将生成的 public 文件夹压缩上传以协助解决问题。

Please provide `_config.yml` and the generated public folder.

**Comment by Loveslife** [comment]
我重装了。。。
