### ISSUE TITLE
服务器端文章目录只能显示一级标题，并且无法点击跳转

### ISSUE THREAD

**Issue by ZKC96** [iissnan/hexo-theme-next#1899]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![local](https://user-images.githubusercontent.com/18170166/30771224-acae4eda-a074-11e7-9789-fb426516c962.jpg)
*screenshot on localhost:4000

*如图，浏览文章时，网页端应该和本地一样可以显示完整目录，并且点击能跳转至相应位置；本地环境下文章目录可以实现完整功能。
*The menu should show full sub menu when reading, and it should point to the right place about the page when clicked. But it only work well in my computer, rather than my website.

### Actual behavior 

![website](https://user-images.githubusercontent.com/18170166/30771244-1b2e9e96-a075-11e7-921e-be4fa57ad2d6.jpg)
*screenshot on web page

*如图，网页端文章目录并不能展开，并且点击也不会跳转至相应位置。
*As you can see, the menu can't unfold on the web page, and the page can't jump to the right position when the menu is clicked.

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 
1. 一级标题用了 ## , 二级标题用了 ### 。
2. 搭建博客时参考了[Hexo快速搭建静态博客并实现远程VPS自动部署](https://segmentfault.com/a/1190000006745478)
3. 服务器端用 centos 7 , 安装 hexo 时出现并参考过  [hexo-cli/issues/23](https://github.com/hexojs/hexo-cli/issues/23) 问题

**Comment by ivan-nginx** [comment]
Try to check [latest master branch](../#download-latest-master-branch). Issue still exists?

**Comment by ZKC96** [comment]
Well, I don't understand the reason but I solved the bug. I searched " Myblog / node_modules " in my VPS, and I found hexo-toc folder which didn't exist in my computer. Then " npm uninstall hexo-toc" , and bug fixed. Thanks!

**Comment by ivan-nginx** [comment]
Your TOC is forget your VPS. :smile:

**Comment by onlyfly34** [comment]
Does anyone know the reasons for this problem? I have the same issue here and done all configurations above. But that doesn't solve my problems.

Here's my blog:
https://hexo.zam.tw/

**Comment by ivan-nginx** [comment]
@onlyfly34 what Hexo your version(hexo -v)? Next version 5.1.2 as i see?
Try to check [latest master branch](../#download-latest-master-branch). Issue still exists?

**Comment by onlyfly34** [comment]
Hexo version is 3.3.9 and that's right, NexT version is 5.1.2.
I just built my blog yesterday and installed with latest master branch of theme NexT.

I just `cd themes/next` and try `git pull` again.
But that doesn't work.

**Comment by ivan-nginx** [comment]
There is some update about TOC in latest Hexo version, but i don't remember where. Maybe this is reason? I have still Hexo 3.2.2 and TOC works fine with **latest master branch** & dev version. But, yes, In 5.1.2 **release version** somewhere was bug with TOC in Next.

Please, try to follow next steps:

1. Backup your source of `themes/next` directory.
2. Switch to latest release (or 5.1.2 / 5.1.1) version (see `Download latest master branch.` section in main readme).
3. Try to catch same error by refreshing browser with `CTRL` + `SHIFT` + `R`.

P.S. Today will be 5.1.3 release with some TOC features & fixes & updates, u just can wait a little time.

**Comment by onlyfly34** [comment]
I just upgraded to NexT v5.1.3. Also, well, reinstall Hexo and that solves my problem.
I guess I lost some dependencies after `npm uninstall hexo-renderer-marked --save` and `npm install hexo-renderer-markdown-it --save`

Thanks for @ivan-nginx 's help.
