### ISSUE TITLE
右侧文章目录, 文章层级过多, 无垂直滚动条

### ISSUE THREAD

**Issue by arccode** [iissnan/hexo-theme-next#19]
由于文章过长, 分级较多,  希望加入垂直滚动条, 以便看更多的目录

**Comment by arccode** [comment]
层级关系出错导致该问题的发生, 但出现双滚动条(新问题), 正在考虑更好的解决方案, 效果见http://arccode.net/2015/02/26/RESTful%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5/

**Comment by iissnan** [comment]
嗯，之前有考虑到会出现这种情况。偷懒没有去处理：）。我看看怎么处理会比较合适。

**Comment by iissnan** [comment]
TOC 做了调整，默认仅展示一级标题。当滚动页面到特定标题位置或者点击标题，都会自动展开子目录。
使用了 Bootstrap 的 ScrollSpy.

**Comment by arccode** [comment]
目前还存在一个问题, 相同级别的目录过多, 将溢出页面

**Comment by iissnan** [comment]
这个问题会比较麻烦点，不过应该可以解决。

**Comment by iissnan** [comment]
Still working on this issue.

**Comment by iissnan** [comment]
对于这个问题，我的想法是：

TOC区域不使用滚动条。

滚动条带来的问题，一是在黑色背景下太碍眼，而是双滚动条体验实在糟糕。

不使用滚动条，需要做的事情有：

1. 隐藏超出部分，并给出内容隐藏提示。
1. 自定义鼠标滚动事件，并阻止滚动时的事件冒泡 。

这两点都没有问题，目前碰到的问题是跟 Bootstrap scrollspy 集成时会出现一个怪异的 bug。

另外，这些操作应该只会针对 Desktop。
