### ISSUE TITLE
BUG：关闭动画后侧边栏不能正确自动开关，附解决方法

### ISSUE THREAD

**Issue by ChasenTsai** [iissnan/hexo-theme-next#1900]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### 问题描述：
> 在主题配置文件(_config.yml)里面把 “motion.enable” 设置为 false 去掉动画之后，
无论将 “sidebar.display” 设置为 “post” 或者 “always” ，在任何页面都不会自动弹出侧边栏。

### Expected behavior 
文章中有多级标题的页面会自动弹出侧边栏。

### Actual behavior 
文章中有多级标题的页面没有自动弹出侧边栏。

### Steps to reproduce the behavior 
1. 打开主题配置文件 _config.yml
2. 把 “motion.enable” 设置为 false，因为我想把加载动画关闭了。
3. 无论将 “sidebar.display” 设置为 “post” 或者 “always”，重新编译后在任何页面都不会自动弹出侧边栏。

### BUG 根源所在
> \themes\next\source\js\src\post-details.js 的第 143 行：

```
CONFIG.motion ?
```

> 应该改为：

```
CONFIG.motion.enable ?
```

> 原因：设置项中 “motion” 的一个数组，显然它的布尔值为 true
所以总会执行三目表达式中 “:” 之前的语句。
改为 “motion.enable” 之后，侧边栏就能正确开关了。

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Fixed in #1898 **PART 2**.
