### ISSUE TITLE
文章页的标签在文章的结尾显示了，而不是和时间、分类一起显示

### ISSUE THREAD

**Issue by mrzhenggang** [iissnan/hexo-theme-next#1901]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
文章页的开始：
时间、分类和标签一起显示

### Actual behavior 
文章页的开始：
时间、分类正常显示

而标签在文章的末尾显示了

### Steps to reproduce the behavior 
1. 正常安装发布文章就这样子了。

* Link to demo site with this issue:  http://mrzhenggang.github.io
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 

请问是不是就是这样子设计的呢？我如果想修改，该怎么做呢？感谢！
使用版本：

NexT.Gemini v5.1.2

**Comment by ivan-nginx** [comment]
Try to check [latest master branch](../#download-latest-master-branch). Issue still exists?

**Comment by Haocen** [comment]
是的，目前设计就是这样。

This behavior is correct by current design. To modify it, please raise the issue with the reason why you think it is a bug(or a feature, if you raise a feature request).

**Comment by ivan-nginx** [comment]
@Haocen thank u for translate and give answers on issues.
Also, somewhere u want to give to u assign to issues? Can u explain how to do it? I'm not owner of this repo, mb i not have some privileges for do it for u? Any help will be great.

**Comment by reuixiy** [comment]
<hr>

*设计就是这样，NexT 把分类（categories）作为一种主要分类方式，而标签（tags）则是辅助分类方式，我个人很喜欢这种设计，categories 为主，tags 为辅。*

## categories 应为博客主分类

我们日常生活中的分类都是树状分类（也可以说是有阶级性的，有“父”与“子”的关系），比如知识的分类、技术的分类、甚至国家公务员和公司的职员的分类。而我们博客写的文章，肯定不能脱离日常生活，故写的文章的分类也逃不了这种树状的分类，也就是 categories，**因此 categories 应为博客的主分类**。另外各种文件浏览器主要分类方式也是 categories 式的树状分类，而不是 tags 。

## 用 tags 修复 categories 的 ”bug“

但是树状分类有个缺陷，比如你的 Windows 电脑按文件类型有视频、音乐、文档三个文件夹，但是如果这三个文件夹中各有些你很喜欢的，而你想把它们放到一起咋办，再创建个「我喜欢」文件夹，然后把它们复制到「我喜欢」文件夹？但是这样「我喜欢」文件夹就有视频、音乐、文档三种文件类型了，又乱了……那再在「我喜欢」文件夹创建视频、音乐、文档文件夹？可以，但是如果某天你突然不喜欢了，咋办，你要把这个文件从两个目录都删除。那开始时移动到「我喜欢」文件夹不就行了，而不是复制，但是这样你视频、音乐、文档的所有文件就不在一个目录了。

为啥会这么麻烦？因为文件类型是一种分类维度，而「我喜欢」是另一种分类维度，在树状分类的
 Windows 文件浏览器中，无法实现不同分类维度的共存，树状分类只能有一种分类维度。

而 tags 就可以弥补 categories 式的树状分类的缺陷，毕竟 tags 是一种平行分类，一个 tag 就是一种分类维度，因此可以解决这个问题。在上面的例子中，如果 Windows 文件浏览器可以在你喜欢的文件上加上「我喜欢」的 tag ，然后有个” tags 浏览器“，就 OK 了。什么？Windows 上的文件浏览器没有这个功能？哈哈哈，NexT 就有啊！

## 博客文章分类的正确姿势

Linux 安装软件，Linux 系统安装好，一些目录就已经存在，然后你安装一个软件，文件就会存放在这些已有的相应目录下。而写博客和 Linux 中安装软件也是类似的，最好搭建好博客后写文章前就想好博客的分类，然后写一篇文章就“移动”到相应”目录“。写完文章后，再通过加 tags 补 categories 的 ”bug“ 。

## 最后说不放顶部的原因

首先由上文，因为 categories 才是博客主分类，当然要放顶部了233333……

其次，博客分类（categories）一般不超过 3 级（但不意味着分类少，比如3个一级目录，每个一级目录又有5个二级目录，每个二级目录又有3个三级目录，则有 3*5*3 = 45 种分类，categories 的优越性？233333……），所以最多也就三个词，字数比较少，所以放在顶部，叫`site-meta`。而标签（tags），与文章有关的词语就可以加个标签，脑洞大的话可以加一大堆，太多就不适合放在顶部，和文章标题抢风头，也不美观。

## 要是你觉得我上面都是废话

当然，如果你还是更喜欢标签（tags）这种分类方式，可以换个主题，比如 [hexo-theme-yilia](https://github.com/litten/hexo-theme-yilia) 和 [hexo-theme-material-indigo](https://github.com/yscoder/hexo-theme-indigo/tree/card) 。

**Comment by reuixiy** [comment]
@mrzhenggang  对了，要是解决了，麻烦关掉这个 issue，这个老外也是辛苦了

**Comment by ivan-nginx** [comment]
If issue solved, close it please.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
