### ISSUE TITLE
The menu icon is not displayed

### ISSUE THREAD

**Issue by lucasleelz** [iissnan/hexo-theme-next#1902]
### Expected behavior 
Display the menu icon

### Actual behavior 

The menu icon is not displayed

### Steps to reproduce the behavior 
1. download hexo-theme-next master

I do not know if the configuration is missing. 
Before the third-party library in the `vendors`, is now in `lib`, whether there is an impact?

**Comment by ivan-nginx** [comment]
#1830.

**Comment by lucasleelz** [comment]
@ivan-nginx thanks!
```
home: / || home
```
This can be solved.
