### ISSUE TITLE
目录排除一些标题项

### ISSUE THREAD

**Issue by cutelittleturtle** [iissnan/hexo-theme-next#1905]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
toc可以选择排除一些标题项

```
# Title1
## sub-title1
## sub-title2
#Title2
#Thisisnotatitle  // exclude with some code

### Actual behavior <!-- (实际行为) -->
不能排除

### Steps to reproduce the behavior <!-- (重现步骤) -->
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**
<!-- Check one with "x" (使用 "x" 选择) -->
```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**
<!-- Check one with "x" (使用 "x" 选择) -->
```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information <!-- (Like Browser, System, Screenshots) -->

**Comment by ivan-nginx** [comment]
**TOC rendering is [provide by Hexo](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/toc.js)**, not by NexT or any other theme.
Please, create issue about this into [Hexo issues](https://github.com/hexojs/hexo/issues).
