### ISSUE TITLE
b2t button display in a wrong position，回到顶部按钮显示位置不对

### ISSUE THREAD

**Issue by songbochn** [iissnan/hexo-theme-next#1906]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
http://www.songbohome.com/%E9%A2%84%E6%9C%9F.png

### Actual behavior 
http://www.songbohome.com/%E5%AE%9E%E9%99%85.png

### Steps to reproduce the behavior 
1. modify next theme's _config.yml
2. modify b2t to true

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
[x] 5.1.2
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
```yml
  # Back to top in sidebar (only for Pisces | Gemini).
  b2t: false
```
Mist and Muse doesn't support `b2t` for now. May be in next releases...
