### ISSUE TITLE
Custom Menu order error.

### ISSUE THREAD

**Issue by chilly** [iissnan/hexo-theme-next#1907]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

If Custom Menu contains number , only display the number.

### Actual behavior 
See Picture
![error](https://user-images.githubusercontent.com/229258/30863083-a9ad15d2-a302-11e7-883c-dec48f7580b2.png)

### Steps to reproduce the behavior 
1. write h1  # 5 ABC
2. write h2 ## 5.1 AAA
3. see the left menu bar

* Link to demo site with this issue: http://chillyc.info/2017/Architect-week3-whatsapp/Class-Diagram/
* Link(s) to source code or any usefull link(s): https://github.com/chilly/chilly.github.io/blob/source/source/_posts/Architect-week3-whatsapp/Class-Diagram.md

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
```yml
toc:
  # Automatically add list number to toc.
  number: true
```

**Comment by chilly** [comment]
this config is global, I want to config my one article.
