### ISSUE TITLE
How to change the font of highlight code?

### ISSUE THREAD

**Issue by yunzhitan** [iissnan/hexo-theme-next#1915]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I want to use Monaco font in highlight code but culminated in failure.

    _config.yml
    codes:
      external: true
      family: Monaco
      size: 16

I modify _config.yml but  just changed non-highlight code

highlight code:
<img src="https://raw.githubusercontent.com/yunzhitan/blog_photo/master/QQ%E5%9B%BE%E7%89%8720171001002237.png" weight="400px" height="400px"/>
non-highlight code
<img src="https://github.com/yunzhitan/blog_photo/blob/master/QQ%E5%9B%BE%E7%89%8720171001002319.png?raw=true" weight="400px" height="400px" />

I also modified custom.styl but nothing happened.

    custom.styl
    $code-font-family =  "Monaco"

**Comment by ivan-nginx** [comment]
1. Try to enable global custom font:
    ```yml
    font:
      enable: false
    ```
2. Try to change on **Web Safe** fonts. Not all fonts may support by `highlight` plugin.
    ```
    # ---------------------------------------------------------------
    # CAUTION! Safari Version 10.1.2 bug: https://github.com/iissnan/hexo-theme-next/issues/1844
    # To avoid space between header and sidebar in Pisces / Gemini themes recommended to use Web Safe fonts for `global` (and `logo`):
    # Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
    # ---------------------------------------------------------------
    ```
3. Try to create issue in [hexo-util](https://github.com/hexojs/hexo-util/blob/master/lib/highlight.js) plugin. NexT use `highlight.js` from there.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
