### ISSUE TITLE
当你不停地点 sidebar 按钮，sidebar 就会被玩坏

### ISSUE THREAD

**Issue by ceoimon** [iissnan/hexo-theme-next#192]
#### 废话：
最近打算开个人博客，于是找到 hexo 和这个主题。
这个主题的特色之一就是滑动侧栏，然后我偶然发现（就是喜欢不停地点:)）这个不知道算不算 bug 的 bug——如果你不停地点 sidebar 按钮，就会重复触发某些事件。
<del>我这是前端新手求交流</del>
#### 重点：
按照我个人想法，在 sidebar 未完全滑出前再点击一次按钮相当于中止了这次事件，应该中断滑出动画并恢复隐藏状态。
在 post 页面下的 sidebar 的文章目录添加 motion 效果。
我在这里给出我的[解决方案](http://ceoimon.com)。

**Comment by ceoimon** [comment]
#193

**Comment by iissnan** [comment]
已合并 PR，多谢
