### ISSUE TITLE
[Bug]Favicon config

### ISSUE THREAD

**Issue by Richard-Cao** [iissnan/hexo-theme-next#1920]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I set favicon path in [my config file](https://github.com/Richard-Cao/Richard-Cao.github.io/blob/hexo/source/_data/next.yml#L17), I will see my custom favicon.

### Actual behavior 
But not. I only see the default favicon. I tried if i changed the favicon name, it could take effect.
If i used default name but only change the image, `hexo g` could not generate favicons with new images, like this: https://richardcao.me/images/favicon-32x32.png?v=5.1.3
Another case: https://richardcao.me/images/safari-pinned-tab.svg?v=5.1.3

### Steps to reproduce the behavior 
1. set favicon path in config file
2. hexo clean
3. hexo g

* Link to demo site with this issue: https://richardcao.me
* Link(s) to source code or any usefull link(s): https://github.com/Richard-Cao/Richard-Cao.github.io/blob/hexo/source/_data/next.yml#L17

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
By the way, i think `#android_manifest: /images/manifest.json` is for PWA?

**Comment by ivan-nginx** [comment]
> But not. I only see the default favicon.

Just try to clean cache & change browser.

**Comment by Richard-Cao** [comment]
Clean invalid.
If you run `hexo clean & hexo g`, you will find these favicons are old.But if changed the favicon name, hexo will generate both new favicon and old default favicon.

**Comment by Richard-Cao** [comment]
You can see my config file, and verify my two cases.

**Comment by ivan-nginx** [comment]
https://github.com/iissnan/hexo-theme-next/blob/b82dc5209571c26bbc6d9b22803114595ba32dcb/layout/_partials/head.swig#L76-L93

And u can see source of NexT. If standart icons worked, any other icons must worked too.

**Comment by Richard-Cao** [comment]
![image](https://user-images.githubusercontent.com/5953992/31145065-395974f2-a8b5-11e7-9830-7415d742df20.png)
You can see this.

**Comment by ivan-nginx** [comment]
> But if changed the favicon name, hexo will generate both new favicon and old default favicon.

Don't understand u, what generate? Favicons? 

> You can see this.

I can see this, and?)

**Comment by ivan-nginx** [comment]
@Richard-Cao give me your favicon 16x16 url online path, link on your any favicon.

**Comment by Richard-Cao** [comment]
https://richardcao.me/images/favicon-32x32.png?v=5.1.3 is old.
https://richardcao.me/images/safari-pinned-tab.svg?v=5.1.3 is new.
If i used default favicon name but changed the image, hexo will generate default favicon.

**Comment by ivan-nginx** [comment]
Favicon 32x32 not the same as safari pinned tab. It's a different icons.

**Comment by Richard-Cao** [comment]
![image](https://user-images.githubusercontent.com/5953992/31145234-c5f5cece-a8b5-11e7-9e67-2cc60c146e59.png)

**Comment by Richard-Cao** [comment]
My config file: https://github.com/Richard-Cao/Richard-Cao.github.io/blob/hexo/source/_data/next.yml#L17

**Comment by Richard-Cao** [comment]
Safari pinned tab image is my true custom favicon.
![image](https://user-images.githubusercontent.com/5953992/31145324-01951f48-a8b6-11e7-99ae-186f7fdafe82.png)

**Comment by ivan-nginx** [comment]
> Safari pinned tab image is my true custom favicon.

Well, u must read documentation how to generate favicons:

https://github.com/iissnan/hexo-theme-next/blob/b82dc5209571c26bbc6d9b22803114595ba32dcb/_config.yml#L13-L16

**Comment by Richard-Cao** [comment]
But i placed my icon in `hexo-site/source/images`, i should now remove `/images` prefix.
It is wrong?

**Comment by ivan-nginx** [comment]
There is English words in comments, above the `favicon` option. What may be unclear?

**Comment by Richard-Cao** [comment]
I know. I placed my icon into `hexo-site/source/images`, not into `hexo-site/themes/next/source/images/`. Same name.

**Comment by ivan-nginx** [comment]
Why same name? Try to rename and define names in config.

**Comment by Richard-Cao** [comment]
……
I understand what you mean.

**Comment by ivan-nginx** [comment]
God..

**Comment by Richard-Cao** [comment]
I thought that files can be same name.
Sorry.

**Comment by ivan-nginx** [comment]
If u place icons in Hexo root directory, icons from Next / images directory always will rewrite they.

>  # Default NexT favicons placed in `hexo-site/themes/next/source/images/` directory. 
> # And if you want to place your icons in `hexo-site/source/`, you must remove `/images` prefix from pathes.
