### ISSUE TITLE
icon problem

### ISSUE THREAD

**Issue by butan2333** [iissnan/hexo-theme-next#1921]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
set icon for new pages in meau

### Actual behavior 
it does not work, i just did it as told in the Chinese document. And it shows no error.

### Steps to reproduce the behavior 
1. hexo new page "tags"
2. add "tags: tags" to the theme _config.yml file
3. restart hexo

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

### Other Information 
system: Debian.
I just start to use hexo, thanks a lot

**Comment by ivan-nginx** [comment]
Hi! Can u show src of Hexo/HexT configs? Or links to this confogs in Github? Need more info.
> add "tags: tags" to the theme _config.yml file

Default is:
```yml
tag_dir: tags
```
