### ISSUE TITLE
How to insert image into text instead of center

### ISSUE THREAD

**Issue by Wanguy** [iissnan/hexo-theme-next#1922]
### Expected behavior 
例如一些公式的图片，想紧接着文字插入

### Actual behavior 
图片换行并且居中显示

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any useful link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Wanguy** [comment]
How to insert image into text instead of center

**Comment by reuixiy** [comment]
你可以看一下我的![博文](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html)中`6.2. 如何使用emoji`，自己定义`img`图片标签的一个`id`（定义`class`没用……![class和id](http://www.divcss5.com/rumen/r3.shtml)的知识），然后每次你想这样插入图片，不要用 Markdown 语法，而是用 HTML，比如我定义了一个`id`为`github-emoji`，则只用写：

```
<img id="github-emoji" src="https://图片.jpg" alt="图片描述">
```

如果你觉得上面这种操作太麻烦了，自己折腾不来，你也可以写文章时直接套用下面这行代码，亲测可以达到效果（且无论主题配置文件中的`fancybox`是否开启）：

```
<img src="https://图片.jpg" alt="图片描述" style="margin:0; padding:0; display:inline !important; vertical-align:bottom; border:none; cursor:text; height:50px; width:50px">
```

要自定义`style`，要达到你要的效果，则`style`为上面这行代码这样就应该就行了。图片高宽的话，改`height`和`width`的值就 OK 。

然后`margin`是外边距，`padding`是内边距，`display:inline`是让图片与文字一行显示，加`!important`是提高指定样式规则的应用优先权（就是让`display:inline`有效果），`vertical-align:bottom`是让图片底部与文字底部在一条线上，`border:none`是去掉图片边框，`cursor:text`是鼠标在图片上面时的形状……

最后，如果你想要[这篇文章](https://reuixiy.github.io/beautiful/notnow/2017/11/04/fairy-tale.html)的图片显示效果，则

```
<p><img src="https://图片.jpg" alt="图片描述" style="float:right; height:510px; width:365px; margin-left:10px"></p>
```

加个`float:right`就行，如字面意思，浮动到右边……

**Comment by Wanguy** [comment]
@reuixiy 非常感谢谢谢，就是还有一个问题顺道问问你，关于你那个博文中的更改页面样式，请问如果改完后不满意，有没有什么办法恢复初始化的~~

**Comment by ivan-nginx** [comment]
If issue solved, close it please.

**Comment by reuixiy** [comment]
`custom.styl`那？删了就行 :smile: @Wanguy

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
