### ISSUE TITLE
Article directories also exist around the center

### ISSUE THREAD

**Issue by aixiu** [iissnan/hexo-theme-next#1923]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Actual behavior 

![default](https://user-images.githubusercontent.com/8064012/31314424-07681eea-ac33-11e7-920f-7be22270d6e5.png)
![default](https://user-images.githubusercontent.com/8064012/31314434-49f12efa-ac33-11e7-8a0b-ccb2e4779b4c.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
![default](https://user-images.githubusercontent.com/8064012/31314434-49f12efa-ac33-11e7-8a0b-ccb2e4779b4c.png)

**Comment by geekrainy** [comment]
Fixed https://github.com/iissnan/hexo-theme-next/pull/1988

**Comment by ivan-nginx** [comment]
I suggest to do it like in #1916.
Problem with this `width` because if TOC height taller then viewport, we will see ugly scrollbar:
![image](https://user-images.githubusercontent.com/16944225/32809356-95c45492-c9a7-11e7-80d3-d3219dd092ab.png)

**Comment by geekrainy** [comment]
@ivan-nginx You are right, it should detect the size of the window to change the style.

**Comment by geekrainy** [comment]
@ivan-nginx I create a new commit for this pull request #1988. It works fine for me. :-)

**Comment by aixiu** [comment]
@geekrainy @ivan-nginx thx.

**Comment by ivan-nginx** [comment]
If issue solved, close it please.
