### ISSUE TITLE
Is there a solution to use secondary menu?

### ISSUE THREAD

**Issue by helianthuswhite** [iissnan/hexo-theme-next#1924]
I wanna use a secondary menu to link some static pages. It seems Next can't do this.

**Comment by ivan-nginx** [comment]
Can u tell some more about what u exactly want? Because it seems NexT can do this, if i right understand.

**Comment by Neveryu** [comment]
i think NexT can do it also.
U must used absolute path in `_config.yml`.
link this:
```
menu:
  google: https://www.google.com
```
then.
U will link google in your menu ,and other static pages also use this methods.
:taco:

**Comment by helianthuswhite** [comment]
Thanks for comments.  @Neveryu @ivan-nginx 

Maybe i didn't describe my question clearly.

I wish i can edit like this in the `_config.yml`.

```
menu:
    ARCHIVE:
        Sub Item 1: /url
        Sub Item 2: /url
        Sub Item 3: /url
        Sub Item 4: /url
    OTHER: /url
```

Then i get like this.

![image](https://user-images.githubusercontent.com/12878076/31441387-aa2db596-ae58-11e7-9e99-29e4e899fae6.png)

**Comment by ivan-nginx** [comment]
This called submenu, not secondary menu. And no, NexT did not support this function for now.

**Comment by helianthuswhite** [comment]
Ok, thanks a lot.

**Comment by ivan-nginx** [comment]
@helianthuswhite already implemented in [this pull](https://github.com/theme-next/hexo-theme-next/pull/156) as sub-menu feature.
