### ISSUE TITLE
About upgrading

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#1928]
First thank you for your contribution. @ivan-nginx 
I recently upgraded the latest version, but it seems that everything is not working.I spent a lot of time to troubleshoot the problem,finally found to be due to a new configuration caused.

```
# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

# Set to true, if you want to fully override the default configuration.
# Useful if you don't want to inherit the theme _config.yml configurations.
override: false
```
Since the previous version did not have this configuration option, it caused my blog to fail to work.

After each update, there will be a large number of options that need to be merged into _config.yml. This is cumbersome, for the average user they will not carefully read every commit, if the update caused by the problem they can not solve.

So I think the update should be kept as backward as possible, otherwise the next becomes more and more complex. This will cause a lot of problems.

I hope that NexT can be kept simple, but it is now becoming more and more complex.

Thank you very much for your work. @ivan-nginx

**Comment by ivan-nginx** [comment]
Hi, nice to meet u again, dude!

1. `Override` option was added not by me, so, it is possible that this option have some bugs, yes. What trouble u have with this option? Can u give reproduce steps, etc.? I almost always use `_data/next.yml` and everything was fine to me.
2. With the next new version i always support readme's with all possible breaking changes in [releases](https://github.com/iissnan/hexo-theme-next/releases). Only trouble can be if u just update your master without read all news. And this is at most cases bug with documentation: @iissnan is dissapear and i no have privilegies to modify site with [NexT Docs](https://github.com/iissnan/theme-next-docs). He's just go out somewhere, that's all. I not seen him / not recived any messages from him from April this year. No commits from him also. I don't know what i may or must do with this repo, but i love NexT and i'm trying to best.
3. About complex... I also think about it, yeah. At last weeks i decide to create separate NexT repository with full access (according section 2 above), rights to modify own docs to NexT, etc. And i also think to create and support any new features there. And for this repo i only can make any small fixes, that's all. 
   Also, we can make this repo without any new features, can to rollback all my (and mb others) latest modifitations (Gemini, Menu, Icons, Logo) in master branch and stay this repo just a simple with possible fixes only, what u think about this? This repo don't be complex, don't will have any new features and don't have any new bugs at least. New repo will with features, but will complex and have many bugs.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
