### ISSUE TITLE
Wrong archives page url

### ISSUE THREAD

**Issue by JoeAsir** [iissnan/hexo-theme-next#1930]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Click archives bottom should be linked to  https://joeasir.github.io/archives/

### Actual behavior 
However ,the archives bottom linked to https://joeasir.github.io/archives/%20%7C%7C%20archive.
which is caused by the Menu Settings (archives: /archives/ || archive) in config.yml, but I don't know why it happend and how to fix it

### Steps to reproduce the behavior 
1. click the archives bottom above avator
2. url would be https://joeasir.github.io/archives/%20%7C%7C%20archive

* Link to demo site with this issue: https://joeasir.github.io
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.3.8
hexo-cli: 1.0.3
os: Linux 4.10.0-35-generic linux x64
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
ba842f52bf783bdce37ede0dc5f7c8c29c52e48f
