### ISSUE TITLE
the wechat share maybe has conflict with livere comment service

### ISSUE THREAD

**Issue by windsmoon** [iissnan/hexo-theme-next#1931]
### Expected behavior 
I have opend the livere comment service and when I scan the QR code of wechat share using wechat app, the blog article page should be showed.

### Actual behavior 
The wechat app gives a tip that it will access a dangerous site and the url is livere's url.

### Steps to reproduce the behavior 
1. come into a article
2. scan the QR code of wechat share using wechat app
3. watch the phone

### Hexo Information

```
hexo: 3.3.9
hexo-cli: 1.0.3
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 6.11.4
v8: 5.1.281.108
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by ivan-nginx** [comment]
U talking about this #1856?

**Comment by stevenjoezhang** [comment]
It has nothing to do with NexT. You can try to contact Wechat Customer service
