### ISSUE TITLE
About Valine comment system

### ISSUE THREAD

**Issue by Aqua-Dream** [iissnan/hexo-theme-next#1933]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

In file valine.swig, the line `el: '#vcomments'` should be modified by `el: '#comments'`, or the comment system would not work.

**Comment by ivan-nginx** [comment]
@Aqua-Dream u can create small pull with fix this bug. Thanks!
