### ISSUE TITLE
next有landscape那样的便签云吗？

### ISSUE THREAD

**Issue by youngjuning** [iissnan/hexo-theme-next#1937]

**Comment by youngjuning** [comment]
请关闭这个issue吧

**Comment by HarlanZhou** [comment]
如何设置标签页面？
```bash
cd myBlog
hexo new page tags
```	
在 `myBlog/source`会生成一个新的文件夹`tags`,在该文件夹下会有一个`index.md`文件设置 
设置页面类型
然后在你的每篇文章的head部分添加你的字段如 tags: [Github]
具体可以参考[我的博客](harlanzhou.co)

**Comment by HarlanZhou** [comment]
如何设置标签页面？
```bash
cd myBlog
hexo new page tags
```
在 myBlog/source会生成一个新的文件夹tags,在该文件夹下会有一个index.md文件设置
设置页面类型
然后在你的每篇文章的head部分添加你的字段如 tags: [Github]
具体可以参考 [我的博客](www.harlanzhou.co) www.harlanzhou.co

**Comment by youngjuning** [comment]
大哥，你会错意了，而且默认是有tags模版的。我说的是侧边栏的标签云，你说的是标签页模版

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by youngjuning** [comment]
It‘s solved
