### ISSUE TITLE
站内搜索的位置感觉怪怪的

### ISSUE THREAD

**Issue by zhiyue** [iissnan/hexo-theme-next#194]
![](http://ww4.sinaimg.cn/large/8d6e2d38gw1esqboyydw7j20nw047aa6.jpg)

我看到作者的搜索框也是放置在右边的

**Comment by iissnan** [comment]
@zhiyue Search 相关的修改还在 dev 分支上，目前 Mist scheme 已经完成了（Desktop 和 Mobile），等待默认 scheme 完成后就会到 master 分支上，所以请稍后再更新下主题。完成后，我会在这个 issue 上通知你。

**Comment by minoscc** [comment]
搜索其实就建议用它的弹窗~~  只显示一个按钮[:mag:]~   :smile:

**Comment by imcoddy** [comment]
其实我觉得是只显示一个放大镜按钮，点击后纵向放大方便输入的效果比较好。
不过手机版本上，排版位置也是个问题。

**Comment by iissnan** [comment]
@minoscc @imcoddy  只显示一个按钮，并使用弹窗或者纵向放大的方式我一开始都考虑过，但是觉得多了一次无谓的操作（我懒哈哈）

**Comment by eurusd** [comment]
iissnan 完成了吗？没见github更新呢？

**Comment by iissnan** [comment]
@eurusd 在 dev 分支上有

**Comment by eurusd** [comment]
iissnan 已更新，谢谢。
