### ISSUE TITLE
hexo algolia 索引没有更新

### ISSUE THREAD

**Issue by kbrx93** [iissnan/hexo-theme-next#1941]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
after delete the page and "hexo algolia" 
show 
![image](https://user-images.githubusercontent.com/26616985/31483291-4ac8b4e6-af5e-11e7-961d-c97dd05902ff.png)

### Actual behavior 
in the algolia console show it has been update
but the index didn't delete 

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by kbrx93** [comment]
增加的key有删除index的权限

**Comment by ivan-nginx** [comment]
If issue solved, close it please.
