### ISSUE TITLE
canvas_ribbon 打开后，在手机端无法正常滑动屏幕

### ISSUE THREAD

**Issue by leviding** [iissnan/hexo-theme-next#1942]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

canvas_ribbon 打开后，不影响手机端屏幕滑动

### Actual behavior 

实际上影响了

### Steps to reproduce the behavior 

canvas_ribbon: true
push 以后，在手机端打开网站即可重现这个 bug

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

- Node.js v8.1.4
- NPM -v5.3.0
- Hexo -v3.3.7

```
hexo: 3.3.7
hexo-cli: 1.0.3
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 8.1.4
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

- package.json

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.7"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.1",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-searchdb": "^1.0.3",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^2.0.1"
  }
}
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

### Other Information 

**手机端 chrome 可以正常，其他的不可以，应该算作兼容问题？**

**Comment by leviding** [comment]
@geekrainy

**Comment by geekrainy** [comment]
晚上修复 :pensive:

**Comment by leviding** [comment]
辛苦了 ❤️

**Comment by ivan-nginx** [comment]
See @geekrainy, that's not easy to state NexT simple (not complex) without any bugs. If there is more features — then more bugs with this features and more and more strings of code...

I think need to separate 3rd-party modules for easiest maintenance they in future.

**Comment by geekrainy** [comment]
@leviding Fixed.
@ivan-nginx Yes, it is inevitable. It's a good idea to split the module. :tada:

**Comment by leviding** [comment]
@geekrainy thanks

**Comment by leviding** [comment]
Can close this issue？

**Comment by ivan-nginx** [comment]
Yeah.
