### ISSUE TITLE
用muse主题在手机上查看归档，点击菜单，如果菜单栏过长，下方的菜单点不到

### ISSUE THREAD

**Issue by wangziling** [iissnan/hexo-theme-next#1946]
![default](https://user-images.githubusercontent.com/24818903/31573787-1708d828-b0f5-11e7-99b3-18d880b5b1a9.png)
红圈范围，好像z-index过低的感觉。这个问题在很早之前就有了

**Comment by wangziling** [comment]
页面正在渲染的时候，红圈内的Pixiv，关于，搜索都能点击到。
渲染完毕，都没法点击到了。
我按住鼠标，拖动，可以看到选中了下方的文字。说明这儿的菜单已经不在这个层级了。
这是一个bug吧。希望能修复。菜单栏应该都能点到，菜单应该浮在下方的文字上面。
![default](https://user-images.githubusercontent.com/24818903/31581621-95d64f20-b1a2-11e7-957b-df93ea05bcd2.png)

**Comment by wangziling** [comment]
应该是这种样式的都会把。
![default](https://user-images.githubusercontent.com/24818903/31581953-ad902d3c-b1a9-11e7-855c-8f2b2514d1bc.png)

**Comment by geekrainy** [comment]
@wangziling Fixed.https://github.com/iissnan/hexo-theme-next/pull/1967

**Comment by ivan-nginx** [comment]
@geekrainy thanks!

**Comment by wangziling** [comment]
Nice work~  ^_^
