### ISSUE TITLE
how to solve seo for baidu

### ISSUE THREAD

**Issue by HarlanZhou** [iissnan/hexo-theme-next#1949]
i choose auto push to baidu site , i has edited _config.yml file about 
```baidu_push: true``` ,but lasted for 7 days ,my website can't  seo for baidu , i wanna know how to solve this problem
我选择百度的自动推送，并且已经将配置文件中的```baidu_push```设置为```true```但是持续了一周还没有被收录，该如何解决呢？

**Comment by ivan-nginx** [comment]
Issue still exists?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
