### ISSUE TITLE
首页文章图片无法正确显示

### ISSUE THREAD

**Issue by vinurs** [iissnan/hexo-theme-next#1951]
一般用hexo发文章的时候，例如发一篇名字test的文章，会在_posts目录下面建一个文件名为test.md的文件，同样在该_posts目录下面会有一个同名的test目录，然后我将该文章用到的图片放在这个目录下面，在test.md里面引用图片的时候会用这种方式引用“./show.png”
这就导致如果`<!--more-->`标签之前有图片的话，那么这个图片在首页是无法正确显示的，请问除了用另外的图床传地址，还有没有别的方式解决这种问题。

**Comment by Mr-LiuDC** [comment]
你可以看看hexo g -d 后public文件夹下图片路径是否正确。

**Comment by vinurs** [comment]
@Mr-LiuDC 我在public目录下面的index.html里面查看了，有图片的那篇文章的图片引用还是这样引用：
`<img src="./show.jpeg">`，但是其实真正的目录路径应该是
`2017/10/08/test/show.jpeg`

**Comment by vinurs** [comment]
我找到解决方案了，https://github.com/iissnan/hexo-theme-next/issues/780
