### ISSUE TITLE
取消tag标签的下划线

### ISSUE THREAD

**Issue by anson2416** [iissnan/hexo-theme-next#1952]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
在博客标签显示的时候，去除下划线。

### Actual behavior 
显示下划线，不美观。

### Steps to reproduce the behavior 
1. 直接打开博客，采用默认设置

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
.posts-expand .post-tags {
  margin-top: 40px;
  text-align: center;
  
  a {
    display: inline-block;
    margin-right: 10px;
    font-size: 13px;
  }
}
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?
* Screens? Live demo?

**Comment by geekrainy** [comment]
根据个人需求更改。

**Comment by reuixiy** [comment]
很简单的，只用在`~/blog/themes/next/source/css/_custom/custom.styl`里面加入：

```
.posts-expand .post-tags a {
    border-bottom: none;
}
```

就解决了。

更多个性化定制，你可以看看我写的博文：
![打造个性超赞博客Hexo+NexT+GithubPages的超深度优化](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html)……

打个小广告[逃……]

**Comment by reuixiy** [comment]
刚刚把超链接的`[]()`写成图片的`![]()`了，所以打不开链接，sorry……:joy:

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
