### ISSUE TITLE
jiathis and baidushare don't show in Gemini mode

### ISSUE THREAD

**Issue by youngjuning** [iissnan/hexo-theme-next#1955]

**Comment by ivan-nginx** [comment]
Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?
* NexT version?
* Screens? Live demo?

**Comment by geekrainy** [comment]
Please check the network.

**Comment by zhichengMLE** [comment]
Whether he is using https or not. I believe baidushare and jiathis don't support https as the comments say so.

**Comment by ivan-nginx** [comment]
Issue will be closed due not enought information.
