### ISSUE TITLE
local search is not show on mobile

### ISSUE THREAD

**Issue by youngjuning** [iissnan/hexo-theme-next#1956]

**Comment by WiseHou** [comment]
这问题我也遇到了，顺便作者是中国的 hhh

**Comment by youngjuning** [comment]
维护的是外国的

**Comment by WiseHou** [comment]
我明白意思了，不过我现在是正常的，用的手机上的chrome，你可以访问hentai.re看下效果

**Comment by youngjuning** [comment]
我的也可以了，就是QQ浏览器效率比较差

**Comment by JiangTJ** [comment]
QQ浏览器的内核版本较低（一些网站的检查结果是chrome 37），我的手机上也不能搜索
QQ mobile browser may be based on chrome 37

**Comment by flashlab** [comment]
看下是不是search文件过大

**Comment by youngjuning** [comment]
@flashlab 不是，网速、QQ浏览器内核版本低都是原因

**Comment by fishandbread** [comment]
也遇到过这类问题，手机上很多浏览器的搜索图标显不出来，也不知咋搞
