### ISSUE TITLE
装了ABP过滤广告百度分享不显示。

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#196]
我想问下多说分享怎开启。

**Comment by iissnan** [comment]
多说分享是什么？

**Comment by vinyo** [comment]
额就是文章分享到社区啊。

**Comment by xirong** [comment]
参考：[多说自带分享使用效果](http://ixirong.com/2015/05/17/how-to-build-ixirong-blog/#comments)

**Comment by iissnan** [comment]
Refer to: https://github.com/iissnan/hexo-theme-next/issues/223
