### ISSUE TITLE
已经修复了next搜索框弹不出手机键盘bug和自定义更简洁的搜索框

### ISSUE THREAD

**Issue by no5ix** [iissnan/hexo-theme-next#1963]
# 动机

- next自带的搜索框有手机键盘不能自动弹出来的bug, 需要点击两次才可以弹出来
- 渴望拥有更简洁的搜索框

# 展示图

如[我博客](https://no5ix.coding.me/2017/10/22/%E4%BF%AE%E5%A4%8Dnext%E6%90%9C%E7%B4%A2%E6%A1%86%E5%BC%B9%E4%B8%8D%E5%87%BA%E6%89%8B%E6%9C%BA%E9%94%AE%E7%9B%98bug%E5%92%8C%E6%9B%B4%E7%AE%80%E6%B4%81%E7%9A%84%E6%90%9C%E7%B4%A2%E6%A1%86/)右上角所示

# GitHub

我的[博客源码](https://github.com/no5ix/no5ix.github.io/tree/source), 欢迎Fork+Star.

如果你也喜欢这样的搜索框, 参考这个[commit](https://github.com/no5ix/no5ix.github.io/commit/3dea59d520457ddc0a1aeaea7e229e6c29ea5bd0)便可改成跟我一样.

**Comment by no5ix** [comment]
it's not a bug, it's a bugfix.

**Comment by ivan-nginx** [comment]
It's issue with bug labeled.
Bugfix it's when u create pill request with direct fix on bug.
