### ISSUE TITLE
不蒜子标识错位

### ISSUE THREAD

**Issue by shijiebei2009** [iissnan/hexo-theme-next#1966]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
期望一切正常

### Actual behavior 
截图如下，在标题下方和博客底部均错位

![11111](https://user-images.githubusercontent.com/4994697/31923096-7bd428e4-b8ab-11e7-8ace-320141d4c281.png)

![222222](https://user-images.githubusercontent.com/4994697/31923106-82c2b5e4-b8ab-11e7-9e56-f015f2ddd57c.png)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue:  
http://codepub.cn
http://codepub.cn/2017/10/13/lucene-implements-any-word-search-and-returns-location-information/

* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo v 3.3.5
nodejs v 7.10.0
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 
Chrome 版本 62.0.3202.62（正式版本） （64 位）

**Comment by ivan-nginx** [comment]
Live demo?

**Comment by shijiebei2009** [comment]
@ivan-nginx add it.

**Comment by ivan-nginx** [comment]
So? All looks fine. Chrome, latest.

**Comment by shijiebei2009** [comment]
@ivan-nginx it is fine in you chrome brower? my is 版本 62.0.3202.62（正式版本） （64 位）

**Comment by ivan-nginx** [comment]
Yeah, i checked it twice (on homepage and on post page). Chrome Версия 62.0.3202.62 (Официальная сборка), (64 бит). Firefox 52.4.0 (64-бит) looks fine too.

**Comment by shijiebei2009** [comment]
@ivan-nginx 
amazing, I don't know why?
chrome + liebao V6.0.114 not correct.
IE V11.0.9600 correct.

**Comment by ivan-nginx** [comment]
> Try to clean cache, change browser, etc. Problem in your client browser side.

Trouble in your Chrome. Any additional extensions maybe?

**Comment by shijiebei2009** [comment]
@ivan-nginx restart my computer, and try again, still not correct.

**Comment by geekrainy** [comment]
All looks fine.
![20171024001](https://user-images.githubusercontent.com/7333266/31943253-bbc01752-b8fa-11e7-98a8-8d095d51cc30.png)

**Comment by shijiebei2009** [comment]
![image](https://user-images.githubusercontent.com/4994697/48311292-76956900-e5d8-11e8-9235-0ef75d10bc67.png)
the problem still exist，is it because busuanzi.js not found?

**Comment by FengZhiheng** [comment]
Its work for me. When I set 2d-live false. And set busuanzi true.

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-theme-next/pull/1233#issuecomment-585576298
