### ISSUE TITLE
some of the LaTeX equations are not rendered correctly

### ISSUE THREAD

**Issue by jdhao** [iissnan/hexo-theme-next#1968]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The LaTeX equation `$(c)$, $(p)$ and $(r)$` should be rendered literally.  Yes, I know that some special character such as `_` , `\`, `*`   are known to cause trouble if you use them in your LaTeX equations and should be properly escaped. But these 3 command do not contain those special characters and I expect them to be rendered correctly.

### Actual behavior 
These 3 characters (i.e., `c`, `p` and `r`) inside parentheses will be rendered differently. The actual outcome is confusing(see below)
![image](https://user-images.githubusercontent.com/16662357/31933853-e04214fe-b8dc-11e7-841f-b1849594775f.png)
When you check their under-lining LaTeX equation, you see `©`, `§`  and `®`, which is really weird. 

### Steps to reproduce the behavior 
1. create a post using `hexo new post "test_latex"`
2. open the post source, and add `$(c)$, $(p)$, $(r)$` to it. 
3. using `hexo s -g` and see the rendered result in the browser

### Hexo Information

version 3.2.2

### NexT Information

**NexT Version:**

- [x] Old version

**NexT Scheme:**

[x] Pisces

### Other Information 
I have also tested these three LaTeX command using plain mathjax and they are rendered correctly. The source is 
```
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<!-- Copyright (c) 2010-2017 The MathJax Consortium -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
  });
</script>
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

</head>
<body>

<p>
	$(c)$, $(p)$, $(r)$
</p>

</body>
</html>
```
So I am assuming that these  3 commands are somehow changed before they are processed by the mathjax engine. But I do not know why...

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.

**Comment by jdhao** [comment]
yes, I think it is not the problem of this theme. I will raise an issue on Hexo project.
