### ISSUE TITLE
there are square brackets around pic when insert picture in blogs

### ISSUE THREAD

**Issue by thuxx** [iissnan/hexo-theme-next#1969]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

When I insert pictures in my blog using hexo generator, I use 

`![](http://oya81c68k.bkt.clouddn.com/OSPPOSPP_13.png)` 

with markdown grammar.

And the html webpage that hexo generated shows：

`<p><img src="http://oya81c68k.bkt.clouddn.com/OSPPOSPP_13.png" alt=""></p>`

I thought it right.

However, when I deploy my hexo blog, there are two square brackets around the picture I inserted. I was wondering how this could happen.
[the picture around two brackets][1]

And I check the codes of the webpage in the Chrome browser:
[codes of the picture][2]
I find nothing about two brackets.

How can I delete two brackets around the picture?

  [1]: https://i.stack.imgur.com/fiJBZ.png
  [2]: https://i.stack.imgur.com/c35UR.png

### Actual behavior 

* Link to demo site with this issue:   [my blog](https://thuxx.github.io/OSPP-3/)
* Link(s) to source code or any usefull link(s): N/A

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by thuxx** [comment]
使用本地上传图片 时
`{%asset_image xxx.jpg. xxx%}`
图片显示正常
用图床就出现这个问题

**Comment by ivan-nginx** [comment]
1. As u can see at original markdown syntax, there [must be Alt text](https://daringfireball.net/projects/markdown/syntax#img) in standart image usage. But if u want to force use image without any text, u can also try to disable `fancybox` in NexT.
2. There is `[{% img %}](https://github.com/hexojs/hexo/blob/master/lib/plugins/tag/img.js)` tag in Hexo. Or u can use `{% asset_image %}` tag as alternative.
3. Also, try to check [latest master branch](../#download-latest-master-branch). Maybe this error dissapear.

If issue solved, close it please.

**Comment by thuxx** [comment]
@ivan-nginx I disable `fancybox`  and the brackets disappear. Thx.

**Comment by thuxx** [comment]
Em...I turn on the `fancybox`  and try to use the  `{% img %}` tag. They work as well so I think there might be something wrong with the `![ ]( )`.
Thx.
