### ISSUE TITLE
发现一个侧边栏的bug

### ISSUE THREAD

**Issue by astraylinux** [iissnan/hexo-theme-next#197]
在menu里有archives和tags的时候，点边栏的post和tags能正常进入archives和tags页面，要是menu里没有这两个的时候，在首页点post还是在首页，tags不能点击（在文章页面是正常的）。categories不知道是不是一样的情况，我还没有用到categories。

**Comment by astraylinux** [comment]
看样子，是少了那两个配置，取不到路径了

**Comment by astraylinux** [comment]
<a href="{{ url_for(theme.menu.archives) }}">
不懂有没有像我这些，把首页那些也去掉的，我自己分开配置吧

**Comment by astraylinux** [comment]
```bash
<a href="{{ url_for(theme.menu.archives) }}">
```

**Comment by mingmings** [comment]
我这边侧边栏不知道是哪里的问题，我取消了主题默认 toc 的功能，转换成自己手写，但是在 push 完成之后，得到的侧边栏显示会出现很诡异的问题
![image](https://cloud.githubusercontent.com/assets/3365500/7961139/1353f944-0a38-11e5-8525-b522c3168ecb.png)
我习惯 一级标题

```
## 一级分类
#### 1.1 子分类

#### 1.2 子分类
```
请问这样有问题么 @iissnan

**Comment by iissnan** [comment]
@astraylinux 侧边栏的 分类/标签 链接是根据 `menu` 是否有对应的配置来定，也就是说，如果没有开启对应的配置，主题默认不会为侧栏 分类/标签 添加链接，仅将这两者作为纯粹的数据来展示。当然你可以自定义下。

**Comment by iissnan** [comment]
@mingmings 你说的取消以及自己手写具体是怎么样的方式？ 从截图上看，是菜单的嵌套出现了问题。

**Comment by mingmings** [comment]
@iissnan 就是改动了 `toc_list_number: false` 这里，进而我在 markdown 里 手动填上 一、1.1、1.2 这样的，然后push 之后最后就展示成那样了，chrome 和 Firefox 均如此

**Comment by iissnan** [comment]
@mingmings  `toc_list_number: true` 是没有问题的吗？

看下 标题的层次是否有出现跳级的情况，例如：

```
# 一级标题 

### 三级标题 

## 二级标题
```

**Comment by mingmings** [comment]
@iissnan 这个之前也仔细检查过，并没有跳级的影响，我一般都是用

```
## 父分类
#### 子分类

这个应该不影响才对的把
```

**Comment by minoscc** [comment]
应该是递归有问题    解析出来是 
```
# -> ol  第一层没事
##
# -> li   第二就变li了
```

**Comment by mingmings** [comment]
![image](https://cloud.githubusercontent.com/assets/3365500/7982507/494374be-0aea-11e5-8fff-d5a624dba7ba.png)
测试，开启了 `toc_list_number: true` 结果还是不行，还是会有样式的问题，这个也是醉了

@minoscc  我检查看看文章会不会有你说的这个问题，那么如果我在每篇文章的最后加上一个
```
### 参考阅读
- []
- []
```
这样是不是会对嵌套产生问题呢

**Comment by iissnan** [comment]
@mingmings 我看了下你的 [redis 持久化](http://mingmings.org/note/2015/redis-%E6%8C%81%E4%B9%85%E5%8C%96/) 这篇文章，发现出现嵌套问题的都是在 h1 标签上（# something ）。

看起来 `toc` 这个 `helper` 无法正确处理这种情况：

```
# Headline 1
## Headline 2
# Headline 1 A
# Headline 1 B
```

**Comment by mingmings** [comment]
@iissnan 也就是说 排除掉 h1 标签不写，只用 h2 - h5 但是仍旧有问题，貌似不能出现下面的标签比上面更高的情况，我有的文章就可以，有的文章就不行了

**Comment by iissnan** [comment]
Hmm.. 奇怪，我看 `toc` 的测试脚本里面是支持这种写法的

https://github.com/hexojs/hexo/blob/master/test/scripts/helpers/toc.js

**Comment by minoscc** [comment]
不能连续跳级~  第一层会没事  后面的会出问题~ 
像你那篇 redis 的 是   1+3+3 1+3 1+3  最前面没事 后面2个就出问题  
如果你是  1+2+3+3 那就是最后面个才出错了~

检查没事的那些怎么写的~ 就行了

**Comment by OCNYang** [comment]
![](https://cloud.githubusercontent.com/assets/3365500/7982507/494374be-0aea-11e5-8fff-d5a624dba7ba.png)
