### ISSUE TITLE
侧边栏社交icon无法修改？？？

### ISSUE THREAD

**Issue by sundongxu** [iissnan/hexo-theme-next#1971]
@iissnan  #求解答一下问题~

在主题配置文件中相关字段配置如下：
social:
  GitHub: https://github.com/sundongxu
  ZhiHu: https://www.zhihu.com/people/sun-dong-xu-6/activities
  Weibo: ...
  Twitter: ...   

social_icons:
  enable: true
  GitHub: github
  Zhihu: graduation-cap
  Twitter: github
  Weibo: weibo

效果如下：
  
<img width="280" alt="2017-10-27 4 29 11" src="https://user-images.githubusercontent.com/13673539/32095161-e5c0765e-bac7-11e7-8dce-77096bee1870.png">

想要指定知乎和微博的icon失败，似乎就是显示的是默认icon。
Github、Twitter这种在social字段下本已经有定义的似乎就是会显示指定icon，在social_icons中修改icon也失败。

**Comment by ivan-nginx** [comment]
See [release notes](https://github.com/iissnan/hexo-theme-next/releases) please.

**Comment by NaraLuwan** [comment]
Upstairs, the same problem has been solved.
