### ISSUE TITLE
求助：各位大佬，如何才能修改博主的模板？不想要默认的这个，想要博主展示的那个theme。

### ISSUE THREAD

**Issue by rickyyangrui** [iissnan/hexo-theme-next#1973]
## 小弟有两个问题，还请给位给点指点，不胜感激。跪谢！
* 比如说这个博客[http://sh.alynx.xyz/](http://sh.alynx.xyz/)主题。
* 博主提供了三套theme,我是有点蠢了，搞了半天就只弄成功了默认的这个主题，我想要的是这个主题：[博主主题](http://notes.iissnan.com/2015/something-about-next/)

* 第二个问题，就是，我看到几个好看的next主题，我如何直接套用别人的模板？
比如刚刚提到的这个博主的：[http://sh.alynx.xyz/](http://sh.alynx.xyz/)

**Comment by ivan-nginx** [comment]
Gemini scheme.

**Comment by FraserYu** [comment]
修改主题配置文件， 查找scheme, 选择 Gemini 即可.
