### ISSUE TITLE
安装后运行时出现错误

### ISSUE THREAD

**Issue by Er-S** [iissnan/hexo-theme-next#1974]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
产生localhost：4000站点

### Actual behavior 
使用bundle exec jekyll server后报错
Administrator@SKY-20140710IIO MINGW64 /d/Er WorkSpace/Eyre Technology CO., LTC/g                                                                                                                it/eyretec.github.io/jekyll-theme-next (master)
$ bundle exec jekyll server
Configuration file: D:/Er WorkSpace/Eyre Technology CO., LTC/git/eyretec.github.io/jekyll-theme-next/_config.yml
            Source: D:/Er WorkSpace/Eyre Technology CO., LTC/git/eyretec.github.io/jekyll-theme-next
       Destination: D:/Er WorkSpace/Eyre Technology CO., LTC/git/eyretec.github.io/jekyll-theme-next/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'description':
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/post.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
It's not Jekyll theme, it's theme for Hexo.
