### ISSUE TITLE
Even though I delete the file ,as follows ,next/source/css/_custom/custom.styl, the background image set before will still be loaded. be 

### ISSUE THREAD

**Issue by shirley5li** [iissnan/hexo-theme-next#1977]
I set background image in the custom.styl file before, the code added as follows,
```
body {
    background:url(https://source.unsplash.com/random/1600x900);
    background-repeat: no-repeat;
    background-attachment:fixed;
    background-position:50% 50%;
}
.main-inner { 
    margin-top: 60px;
    padding: 60px 60px 60px 60px;
    background: #fff;
    min-height: 500px;
}
```
However when I deleted these codes to resume the blank background yesterday, and ```$ hexo g -d ```to push the update, there's nothing changed, the background image still be loaded. But when ```$ hexo s```in localhost, the the background images dispaired, and however when  ```$ hexo g -d ```the git told nothing to commit, working tree clean. Thanks for your help!

**Comment by geekrainy** [comment]
Run `hexo clean`

**Comment by shirley5li** [comment]
Thanks too much for your help.
