### ISSUE TITLE
Overlength toc cannot show full content in wrap: false mode.

### ISSUE THREAD

**Issue by zhichengMLE** [iissnan/hexo-theme-next#1980]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The exceeding content of the toc is not displaced.

### Actual behavior 
A floating window should be showed up and displays full contents of that toc.

### Steps to reproduce the behavior 
1. Having a overlength toc 
2. Please make sure you have toc wrap function disabled.
3. Move you cursor to the toc

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version. - 5.1.3
[] Old version
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by ivan-nginx** [comment]
Screens? Live demo?

**Comment by zhichengMLE** [comment]
A snapshot is showed below. Compare the toc on the left and header on the right. E.g., "1) Machine Learning V.S. Data Mining" (The highlighted header)

I am expecting a float window show full content while the cursor is pointing.

![toc](https://user-images.githubusercontent.com/13708160/32322642-2fff7106-c000-11e7-849c-153cf029fa63.png)

**Comment by ivan-nginx** [comment]
> I am expecting a float window show full content while the cursor is pointing.
This feature didn't implement yet, but nice idea, need ti think about it. That's why TOC wrap function was added by me as alternative variant to show full headers length.

**Comment by zhichengMLE** [comment]
Thanks in advanced, I am currently using warped TOC. But wraping, as far as I am concerned, is not good-looking.

**Comment by ivan-nginx** [comment]
Feature added in [NexT v6 / v7](https://github.com/theme-next/hexo-theme-next).
