### ISSUE TITLE
Category 404, name with spaces

### ISSUE THREAD

**Issue by PhoenixPan** [iissnan/hexo-theme-next#1982]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Display categories correctly. 

### Actual behavior 
SOME categories gave 404 for no reason

### Steps to reproduce the behavior 
1. I have two posts, with heading: 
```
---
title: News Feed System
categories: System Design
date: 2017-10-09 22:15:03
---
```
```
---
title: 15619 Project1.1 Guide
categories: 15619 Cloud Computing
date: 2017-07-09 17:45:21
---
```
2. I put the md files under two directories:  `_posts\system-design\xxx.md` and `_posts\15619-cloud-computing\xxx.md`, respectively;
3. I run my service this by steps: (1) delete `db.json`, (2) run `hexo clean,` (3) run `hexo g` and then (4) run `hexo s`;
4. It will run correctly on localhost:4000. For example, the category URL is `http://localhost:4000/blog/categories/System-Design/`(category name) and the post URL is `http://localhost:4000/blog/2017/10/11/system-design/user-system/` (directory). The same thing applys to "15619 Cloud Computing"
5. However, when I run `hexo d` to deploy it on my GitHub Pages, the 15619 Cloud Computing still works, but the System Design is DEAD

After this, I found solutions in issue 1768, 1903, 1904, I have also done: 
1. Add category_map, I also tried to add "-" in between, but it doesn't work.
```
category_map:
  General: general
  15619 Cloud Computing: 15619 cloud computing
  LeetCode: leetcode
  Linux: linux
  System Design: system design
```

2. `filename_case: 1`

But it's still a no go. The problem comes out even with a signle word category, General. The default URL is still `/General` instead of `general`, despite I set `filename_case: 1`. The "System Design" category will not display no matter I changed it to lower or upper cases. In my live demo, "15619 Cloud Computing" and "Linux" works, but "System Design" and "General" do not work. I have no idea how's that happening, as the behavior is not consistant for similar-name categories. 

Several concerns: 
1. Does the directory name relevant to this issue? It seems not as some categories can display correctly, but some are not. 
2. Do I need to worry about spaces between words in category names? 
3. It feels to me that the categories are not changing at all. Is there a cache or something keeps it from me to change it?

* Link to demo site with this issue: https://www.phoenixpan.com/blog/categories/
* Link(s) to source code or any usefull link(s): https://github.com/PhoenixPan/phoenixpan.github.io

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Where u set this settings? In Hexo or in NexT? If in Hexo (and there is) why u create issue in NexT theme? 

Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.

**Comment by PhoenixPan** [comment]
Humm...I posted here because I found: 

https://github.com/iissnan/hexo-theme-next/issues/1768  
https://github.com/iissnan/hexo-theme-next/issues/1903  
https://github.com/iissnan/hexo-theme-next/issues/1904  

Please let me identify the issue again according to your suggestion.

**Comment by PhoenixPan** [comment]
Yeah...It remains that way even I use the landscape theme. Let's close this issue for now, sorry for the inconvenience.
