### ISSUE TITLE
menu下选项的路径叠加问题

### ISSUE THREAD

**Issue by caocan** [iissnan/hexo-theme-next#1985]
我这里出现一个问题，就是当点击首页（home）的时候，博客只停留在当前路径。而点击其他时候，比方“标签”，就会在现在的url上叠加一个tags这样就会出现如图所示的问题：
<img width="453" alt="default" src="https://user-images.githubusercontent.com/12294613/32415937-65b15dc2-c27c-11e7-8504-2a6c37c0a366.PNG">
而且我的menu下的home已经设置了/ ，怎么解决这个问题？

**Comment by caocan** [comment]
重新clone了一份，已经ok了。

**Comment by chenfanlinux** [comment]
我的menu旁边一直是问号

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
