### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by CaesarChan** [iissnan/hexo-theme-next#1998]
env
```
hexo: 3.4.0
next: v5.1.3
OS: macOS Sierra 10.12.6
```

I create a new markdown file and run 

```bash
hexo d -g  && hexo generate --deploy
```

the file content is 
```
飞天敏捷版充分体现了云 + 容器的独特价值。不仅大大了降低容器服务的操作难度，移植性也很强，能在不同环境中进行应用部署。有了它，客户可以在一组主机上通过 Docker 容器来进行分布式应用的部署、更新和弹性伸缩，轻松实现混合云方案。当业务出现峰值流量时，快速将本地数据中心应用扩展到云端，利用云资源更好的进行灾备、应对峰值流量。 
```
and then  
![image](https://user-images.githubusercontent.com/4354095/32885982-dc7805a4-ca84-11e7-9553-e8a14a4ee3b8.png)

In my local markdown editor ,the content can be parse .

**Comment by zhuzhuyule** [comment]
### step.1
delete this post file, then  try again !
### step.2
if it still occurre error,  the error isn't this post influence, you can try other post again !
### step.3
else if it's running success , you can delete a part of the post content, then try again !

tip:
> 飞天敏捷版充分体现了云 + 容器的独特价值。不仅大大了降低容器服务的操作难度，移植性也很强，能在不同环境中进行应用部署。有了它，客户可以在一组主机上通过 Docker 容器来进行分布式应用的部署、更新和弹性伸缩，轻松实现混合云方案。当业务出现峰值流量时，快速将本地数据中心应用扩展到云端，利用云资源更好的进行灾备、应对峰值流量。

i don't find this content exist special sign, you can show all content that include title.

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
