### ISSUE TITLE
代码块高亮前后可能会出现多余空白块

### ISSUE THREAD

**Issue by niklaus520** [iissnan/hexo-theme-next#2]
![qq 20150129221003](https://cloud.githubusercontent.com/assets/3125626/5958818/af9b9498-a803-11e4-8024-df8f4143beee.png)

如图，代码块可能会出现多余空白块。
theme版本为`commit 7109c872bc3def66cf1546db66d67fbc75624e04`；
hexo版本如下：
```
marvin@ubuntu:~/MyLove/tmp/blog$ hexo --version
hexo: 2.8.3
os: Linux 3.13.0-32-generic linux x64
http_parser: 1.0
node: 0.10.36
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.30
zlib: 1.2.8
modules: 11
openssl: 1.0.1l
```

建议按照https://github.com/wuchong/jacman/commit/e182a058690ca5433e7a6eadb81639ada2ead0a6 改善一下这个问题~

Thx for ur great work!

**Comment by iissnan** [comment]
@niklaus520  Hi Marvin. 我昨晚加上了.line的高度。我测试了下，在有使用行号的情况下，没有指定line的高度，会发生行与代码无法对上的问题。

我不太确定你是否是指的这个问题。因为加上这个高度并不能解决代码前出现多余的空白的问题。

谢谢你的反馈。
