### ISSUE TITLE
个人觉得, sidebar应该在开始的时候就展开

### ISSUE THREAD

**Issue by arccode** [iissnan/hexo-theme-next#20]
通过对该hexo-theme-next的多次浏览, 我觉得sidebar默认应该展开,原因如下:
1. 展开按钮不是那么显眼
2. 陌生用户不知道还有个sidebar隐藏着, 比如用户浏览文章的时候, 他是不知道还有目录的

**Comment by iissnan** [comment]
确实，目前不是很明显。在制作的过程我也感觉到了，本来还想加动画效果上去。

我的想法是：

- 全局默认展开
- 在文章页面默认展开

另外，在主题设置中可以定制是否默认展开。

是否有更好的想法？

**Comment by arccode** [comment]
@iissnan 我觉得目前可以按你说做.以后如果sidebar中增加了更多的菜单,可以考虑制作一条菜单图标栏(垂直排列), 点击可展开相关菜单下的内容.

**Comment by jiangxy** [comment]
赞成在文章页面默认展开，但不喜欢全局展开
喜欢简洁的首页

其实我觉得侧边栏的“站点概览”很大程度跟about页面是一个作用。。。倒是可以考虑在about页面默认展开

**Comment by iissnan** [comment]
我看下是否能判断是否是空的目录结构，如果是则不展示。另外一种考虑是当目录结构是空的时候给一个提示，说明当前目录为空，保持文章页面展示的一致性。

暂定在文章页面默认展开。

**Comment by arccode** [comment]
文章详情页sidebar默认展开, 感觉有点突兀, 我觉得应该让sidebar延时点展开效果更好.

layout/post.swig(line: 67)
if ($('.post-toc').html().trim().length > 0 && isDesktop()) {
          setTimeout(function(){$('.sidebar-toggle').trigger('click')},800);
        }

setTimeout虽然不是什么好的计时方法, 但能达到效果

**Comment by iissnan** [comment]
Agreed. Will fix later.

**Comment by arccode** [comment]
文章目录的anchor, 点击后anchor定位直接顶住浏览器上端, 我觉得应该对h*(1~6)增加padding-top: 10px, 这样更美观些

css/_core/base.styl(line: 63)
h2, h3, h4, h5, h6 {
  margin: 60px 0 15px;
  padding : 10px 0 0 0;
}

**Comment by iissnan** [comment]
延迟 Sidebar 的显示 以及 Headline 留白已经处理了。见https://github.com/iissnan/hexo-theme-next/commit/1e3ff9681c644237617c7d72673a8a58a6e5f55c

**Comment by arccode** [comment]
手机适配有问题, sidebar出现

**Comment by iissnan** [comment]
你使用的手机是？

**Comment by arccode** [comment]
分辨率是1080x1920的

**Comment by iissnan** [comment]
这种分辨率情况下，我觉得展示 sidebar 是可以接受的。

**Comment by ianwith** [comment]
加个配置项吧？让用户定制是否默认展开

**Comment by zhiyue** [comment]
我也认为加一个配置项会好一点，有些散文，有个目录在会很突兀。

**Comment by chenupt** [comment]
同意，多次展开有点审美疲劳了，能提醒一次便好。btw，主题很棒！

**Comment by ohlife** [comment]
既然简洁就简洁到底,全局和文章页面都不默认打开最好:）
如果打开文章就显示侧边栏个人觉得会让人分心,影响整体的阅读流畅性.
也同意增加个配置项,让用户自己选择侧边栏是否默认打开.

**Comment by Andrew-liu** [comment]
感觉刚进入博客时候打开sidebar, 然后在文章中可以选择性的打开

**Comment by iissnan** [comment]
添加了一个侧栏设置的选项：

```yml
# Sidebar 侧栏行为，可选值有
#  - post   默认值，在文章页面自动展开侧栏
#  - always 在所有页面自动展开侧栏
#  - hide   在手动点击侧栏的开关按钮时展开
sidebar: post
#sidebar: always
#sidebar: hide
```
