### ISSUE TITLE
Generate website without CSS 

### ISSUE THREAD

**Issue by liuslevis** [iissnan/hexo-theme-next#200]
Right after git Pull this theme and setup.

Is the version of hexo out-of-date?

hexo -v
hexo-cli: 0.1.6
os: Darwin 14.3.0 darwin x64
http_parser: 1.0
node: 0.10.22
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.19
zlib: 1.2.3
modules: 11
openssl: 1.0.1e

**Comment by iissnan** [comment]
The version of `hexo-cli` looks fine. Could you please provide more info about this error, such as:

- The status of request to `main.css`.
- Run `hexo g` then take a look at `main.css`.

or something else.

**Comment by liuslevis** [comment]
Chrome Console:
``` Javascript
http://main.css/?v= Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://default_avatar.jpg/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://motion_fallback.js/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://helpers.js/ Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://jquery/index.js?v=2.1.3 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
(index):303 Uncaught ReferenceError: $ is not defined(anonymous function) @ (index):303
favicon.ico:1 GET http://0.0.0.0:4000/favicon.ico?v= 404 (Not Found)
```
Chrome DOM Inspector:

``` HTML
<link rel="stylesheet" type="text/css" href="//main.css?v=">
```

Meanwhile I found my main.css is located at ``` ./blog/css/main.css```

It seems that HTML got the wrong main.css location?
Is it possible to fix?

Thank you for your design. I do appreciate and really want to use this splendid theme.

**Comment by iissnan** [comment]
Yeah, it seems links to assets are all incorrect.

Could you try to clean and re-generate your site with:

```
hexo clean
hexo generate
```

Another possible solution is to set `relative_link` to `false` in your site's `_config.yml`. Please also try it.

Let me know if it works or not.

**Comment by liuslevis** [comment]
```relative_link``` is ```false``` already.

Tried ``` hexo clean && hexo generate ``` and still showed the same error.

Is it possible to set any breakpiont within ```hexo generate``` code and figure out what is going wrong?

**Comment by liuslevis** [comment]
Changing to another theme solved this problem, thanks for your help!
