### ISSUE TITLE
求这个网站的修改效果，哪位大神来教一下

### ISSUE THREAD

**Issue by Moober** [iissnan/hexo-theme-next#2000]
想知道这个网站的效果是如何修改的  

 http://qinsman.com/

### 1，他是如何去掉 左侧栏目中的 日志的

![image](https://user-images.githubusercontent.com/26390644/32977103-cc22a626-cc61-11e7-9b4a-360200fcf915.png)

###  2，如何把内容区域修改成他那样的格式，求教程，

![image](https://user-images.githubusercontent.com/26390644/32977158-727acf08-cc62-11e7-84f7-263767f555a5.png)

**Comment by FloatingShuYin** [comment]
你直接去问他啊

**Comment by Moober** [comment]
问了他不搭理我......

**Comment by Moober** [comment]
@FloatingShuYin 问了他根本不搭理我.....哎，

**Comment by huyingjie** [comment]
1.  `layout/_macro`文件夹下的`sidebar.swig`里有sidebar的内容, 删除不要的内容就好
2.  自己创建新的首页的swig, 然后`layout`里的`index.swig`引用新的`swig`

**Comment by Moober** [comment]
@huyingjie 感谢你的回复，我去研究怎么写去了

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
