### ISSUE TITLE
wechat share dose not work

### ISSUE THREAD

**Issue by windsmoon** [iissnan/hexo-theme-next#2002]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
click wechat share button and there will has a  QRCode image

### Actual behavior 
click wechat share button but the QRCode image dose not appear. The borwser's console show the error :
 ```
api.qinco.me/api/qr?size=400&content=http%3A%2F%2Fwindsmoon.com%2F2017%2F10%2F09%2F%25E5%2588%25A4%25E6%2596%25AD%25E5%258D%2595%25E5%2590%2591%25E9%2593%25BE%25E8%25A1%25A8%25E6%2598%25AF%25E5%2590%25A6%25E6%259C%2589%25E7%258E%25AF%25E5%258F%258A%25E6%25B1%2582%25E7%258E%25AF%25E5%2585%25A5%25E5%258F%25A3%25E7%259A%2584%25E7%25AE%2597%25E6%25B3%2595%25E6%2595%25B0%25E5%25AD%25A6%25E8%25AF%2581%25E6%2598%258E%2F%23more:1 GET https://api.qinco.me/api/qr?size=400&content=http%3A%2F%2Fwindsmoon.com%2F2017%2F10%2F09%2F%25E5%2588%25A4%25E6%2596%25AD%25E5%258D%2595%25E5%2590%2591%25E9%2593%25BE%25E8%25A1%25A8%25E6%2598%25AF%25E5%2590%25A6%25E6%259C%2589%25E7%258E%25AF%25E5%258F%258A%25E6%25B1%2582%25E7%258E%25AF%25E5%2585%25A5%25E5%258F%25A3%25E7%259A%2584%25E7%25AE%2597%25E6%25B3%2595%25E6%2595%25B0%25E5%25AD%25A6%25E8%25AF%2581%25E6%2598%258E%2F%23more 

net::ERR_CONNECTION_CLOSED

Image (async)
wechat @ needsharebutton.js:122
(anonymous) @ needsharebutton.js:494
```
so I think is the server which provide QRCode api crashed ?

### Steps to reproduce the behavior 
1. click the wechat share button

* Link to demo site with this issue: http://windsmoon.com
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.3.9
hexo-cli: 1.0.3
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 6.11.4
v8: 5.1.281.108
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
chrome, osx

**Comment by ivan-nginx** [comment]
Please, try to apply patch in #1976 pull.
Issue solved?

**Comment by windsmoon** [comment]
@ivan-nginx  My mistake, thank you very much
