### ISSUE TITLE
how to combine the theme with native html well

### ISSUE THREAD

**Issue by huyingjie** [iissnan/hexo-theme-next#2004]
If we put html files in `_posts` folder, hexo will automatically combine html files and theme. The content of the html files is now the content of the new posts. 

On the homepage, the titles of the posts generated are "Untitled". This is not I wanted. I hope that the titles of the posts are those of original html files. In addition, how to set excerpt, tags, and categories for this type of post? How can I achieve this?

### Expected behavior 
Post title is the title of the native html.
### Actual behavior 
Post title is "Untitled" in the home page.

### Steps to reproduce the behavior 
1. I have a html file
2. move the html file to `source/_posts` folder
3. run `hexo s`

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.1
hexo-cli: 1.0.4
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 8.5.0
v8: 6.0.287.53
uv: 1.14.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.
