### ISSUE TITLE
gitment 设置不生效，请给个例子可以吗

### ISSUE THREAD

**Issue by iiskei** [iissnan/hexo-theme-next#2007]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by Neveryu** [comment]
好吧，给你一个例子 [https://neveryu.github.io/guestbook/](https://neveryu.github.io/guestbook/)

**Comment by iiskei** [comment]
@Neveryu 哈哈 这个广告打的很牛逼了  我想知道你的配置文件是怎么写的gitment这块，然后昨晚我查了，最新的5.1.3系统中并没有gtiment相关代码插进去，只是多了一个gitment的配置参数

**Comment by Neveryu** [comment]
本来就不用添加什么代码，他这个引入js和css就行了，然后配置一下参数不就够了吗，你还想搞什么，搞事情吗？？？ 吃我一拳 :fist_oncoming:

**Comment by iiskei** [comment]
@Neveryu 他最新的那个参数 你没看到吗  你能发下你的？

**Comment by Neveryu** [comment]
我用的是老版本，没有集成gitment，我是自己弄的

**Comment by iiskei** [comment]
@Neveryu 老版本你说那么多呢，老版本我的也能搞出来。你会持续集成么，这个我一直是没搞成功

**Comment by JiangTJ** [comment]
@iiskei GitLab-CI的例子https://gitlab.com/pages/hexo

**Comment by iiskei** [comment]
@JiangTJ 很实用 多谢了

**Comment by iiskei** [comment]
@JiangTJ  有没有Travis CI 持续集成的例子啊

**Comment by JiangTJ** [comment]
我用GitLab托管的，所以没研究过Travis CI，但ci的原理是一样的
1. 提交代码触发ci
2. ci编译成静态页面
3. 托管ci编译后的静态页面

**Comment by Raincal** [comment]
@iiskei 我用了Travis CI 部署在coding和firebase上 你可以参考下
https://github.com/Raincal/blog

**Comment by hydewww** [comment]
@iiskei 请问解决了吗？

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by iiskei** [comment]
Gitment does not take effect

**Comment by ivan-nginx** [comment]
@iiskei 

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create issue in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)**.
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by iiskei** [comment]
Ok, you can close this issue

**Comment by mll120110** [comment]
出现一个问题，若新建中文标题的文章(中文+英文)，操作初始化评论，就会报错Error: Validation Failed，初始化评论请求，返回Status Code:422 Unprocessable Entity
。如果文章名字是纯英文，初始化评论正常。已经修改站点配置文件language: zh-Hans，现在使用Next主题，5.1.4（已经集成gitment），希望得到回复
