### ISSUE TITLE
Muse主题下，打开菜单的同时，点击展开个人信息。

### ISSUE THREAD

**Issue by wangziling** [iissnan/hexo-theme-next#2008]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

右侧个人信息应该置于顶层。The personal info at right side should be at the top level.

### Actual behavior 

右侧个人信息的Z-index过低，左侧菜单的Z-index过高

### Steps to reproduce the behavior 
1. 点击菜单 click to expand menu
2. 点击右侧个人信息 click to expand personal info at right side

* Link to demo site with this issue: wangziling.github.io
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
Latest.
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
![image](https://user-images.githubusercontent.com/24818903/33209673-f5d6a144-d151-11e7-980d-130573c41c6c.png)

**Comment by ivan-nginx** [comment]
Try to aplly #1993 pull. Issue still exists?

**Comment by wangziling** [comment]
I'm not going to use 'git' very much，but I update those files changed by him ,  this problem fixed. Every page is good.
![image](https://user-images.githubusercontent.com/24818903/33217595-80832990-d173-11e7-9e7e-362f57c2af45.png)

**Comment by wangziling** [comment]
@ivan-nginx thank you

**Comment by ivan-nginx** [comment]
Welcome.

**Comment by chenfanlinux** [comment]
为啥我的菜单图标显示不出来
