### ISSUE TITLE
5.1.3动画效果怎么关闭，试了motion，use_motion，都不行

### ISSUE THREAD

**Issue by mrgiser** [iissnan/hexo-theme-next#2009]
如题，5.1.3动画效果怎么关闭，试了motion，use_motion，都不行

**Comment by Raincal** [comment]
```yml
motion:
  enable: false
```
这样就可以啊

**Comment by mrgiser** [comment]
@Raincal 我在主题配置文件中加上那句，hexo g会报错。。
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: duplicated mapping key at line 654, column -1051:

**Comment by Raincal** [comment]
@mrgiser 配置里本身有这项 默认是true 改成false就行了

**Comment by mrgiser** [comment]
@Raincal 谢谢啦，重复配置了，解决了。
