### ISSUE TITLE
额！怎在导航加个多说留言板

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#201]
如题。

**Comment by iissnan** [comment]
可以新建一个页面，然后在那个页面内调用多说的留言即可，最后再导航上添加页面的链接即可。

**Comment by vinyo** [comment]
怎调用多说。

**Comment by vinyo** [comment]
还有图标怎设置

**Comment by iissnan** [comment]
页面调用多说参考这个： https://github.com/iissnan/hexo-theme-next/issues/34#issuecomment-77865225
图标设置参考： [自定义LOGO以及主题图标](https://github.com/iissnan/hexo-theme-next/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89LOGO%E4%BB%A5%E5%8F%8A%E4%B8%BB%E9%A2%98%E5%9B%BE%E6%A0%87)

**Comment by iissnan** [comment]
另外添加导航时，需要在语言 `languages` 目录下设定导航的名字
