### ISSUE TITLE
左侧目录显示（缩进）有问题/The left directory shows anomalies

### ISSUE THREAD

**Issue by realchoi** [iissnan/hexo-theme-next#2013]
### I agree and want to create new issue 

- [ ] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
The left directory is displayed normally, this is the markdown code below （预期，左边目录应该正常显示，markdown代码如下）
![prtsc2.png](https://i.loli.net/2017/11/30/5a1fcb5183eb1.png)

![prtsc3.png](https://i.loli.net/2017/11/30/5a1fcb8063f71.png)

### Actual behavior 
The left directory shows anomalies, but the article's content is normal.（实际上，同级目录的缩进不一样，而且显示成列表类型，但是文章内容显示正常）
![prtsc1.png](https://i.loli.net/2017/11/30/5a1fca94c3fd8.png)

### Steps to reproduce the behavior 
1. My blog's address（我的博客地址）: https://realchoi.com/2017/11/30/determine-whether-the-user-ip-is-from-the-intranet/
2. The detail of my markdown code is likes below（markdown详细代码如下）:
````
## 前言

最近做项目时遇到一个需求：判断当前访问的用户，和服务器是否在同一个内网中，然后进行不同的跳转。说白了，就是先获取用户的 IP ，然后判断其是否属于内网 IP 。由于项目的语言是 C# ，所以这里我也是用 C# 进行记录。

## 方法

#### 获取用户的 IP 地址

简单的来说，有两种方法可以获取到用户的IP，分别是 `remote_addr` 和 `x_forwarded_for` ，这两者区别如下`[1]`：

* `remote_addr` ：代表客户端的IP，但是它的值不是由客户端提供的，而是服务端根据客户端的 IP 指定的，当你的浏览器访问某个网站时，假设中间没有任何代理，那么网站的 Web 服务器（Nginx，Apache 等）就会把 `remote_addr` 设为你的机器 IP ；如果你使用了代理，那么你的浏览器会新访问这个代理，然后再由这个代理转发到网站，这样 Web 服务器就会把 `remote_addr` 设为这台代理机器的 IP 。

  通过 `remote_addr` 获取 IP 的代码如下：

  ```c#
  string ip = HttpContext.Current.Request.ServerVariables["remote_addr"];
  ```

* `x_forwarded_for` ：正如上面所述，当你使用了代理时，Web 服务器就不知道你的真实 IP 了，为了避免这个情况，代理服务器通常会增加一个叫做 `x_forwarded_for` 的头信息，把连接它的客户端 IP（即你的上网机器 IP ）加到这个头信息里，这样就能保证网站的 Web 服务器能获取到真实 IP 。

  通过 `x_forwarded_for` 获取 IP 的代码如下：

  ```c#
  string ip = HttpContext.Current.Request.ServerVariables["x_forwarded_for"];
  ```

<!--more-->

由于我们的用户提出这个功能，目的是供自己内部人员使用，并不存在伪造等各种复杂的情况，因此这里使用上述两种方法即可完成预期功能：

* 先直接通过 `x_forwarded_for` 方式获取IP，以防止偶尔有人员挂上了代理。
* 判断通过上述方法获取的 IP 是否为空，如果不为空（用户刚好使用了代理），则获取的 IP 即为用户的 IP ；如果为空（用户没有使用代理），则再使用 `remote_addr` 获取的 IP 作为用户的 IP 。

至此，用户的 IP 我们已经拿到了。

#### 判断用户的 IP 是否来自内网

内网（私有 IP ）有三类：

* A 类：10.0.0.0 - 10.255.255.255
* B 类：172.16.0.0 - 172.31.255.255
* C 类：192.168.0.0 - 192.168.255.255
* 最后还有一个回环 IP 地址：127.0.0.1

搞明白这个，也就容易了，即判断用户 IP 是否属于上述四类 IP 的范围即可。

## 代码

详细代码贴在下面：

```c#
//C# code block（C#代码片段）
```

## 参考资料

```[1]``` [怎样正确设置 remote_addr 和 x_forwarded_for](http://blog.csdn.net/smilefyx/article/details/52120461)
````

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
$ hexo -v
hexo: 3.3.9
hexo-cli: 1.0.3
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 8.4.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.22.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
Browsers（浏览器）: Chrome & Firefox

**Comment by Raincal** [comment]
有个解决方法
\## 后的标题用 ### 不要用 ####
![2017-11-30 18-36-54](https://user-images.githubusercontent.com/6279478/33426628-832f28ae-d5fd-11e7-98bd-26d4ea5fcc28.png)

**Comment by ivan-nginx** [comment]
```
## 方法

#### 获取用户的 IP 地址
```

Looks like u don't use **right** hierarchy rules. Please, check #1771 issue.

**Comment by realchoi** [comment]
@Raincal 多谢！
@ivan-nginx Thanks!
