### ISSUE TITLE
local search, loading forever, no searching view appear

### ISSUE THREAD

**Issue by zjh1943** [iissnan/hexo-theme-next#2014]
***

### Expected behavior 
click "search" in sidebar. It should show searching view

### Actual behavior 

Searching view never show. Just loading loading loading... 

### Steps to reproduce the behavior 

**site config.yml** ：
```
# hexo-generator-searchdb
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
```
**theme config.yml** ：
```
# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  # trigger: manual
  # show top n results per article, show all results by setting to -1
  # top_n_per_article: -1
```

* Link to demo site with this issue: <http://blog.bookbook.in>
* Link(s) to source code or any usefull link(s): <https://github.com/zjh1943/zjh1943.github.io>

### Hexo Information

```
hexo: 3.4.2
hexo-cli: 1.0.4
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 9.0.0
v8: 6.2.414.32-node.8
uv: 1.15.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```
version: 5.1.1

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
5.1.3 latest release version for now. Please, check [here](https://github.com/iissnan/hexo-theme-next/releases).

**Comment by zjh1943** [comment]
I have updated to version 5.1.3. But the problem exists.

**Comment by ivan-nginx** [comment]
1. Can u try to install clean version? And test it again.
2. Did u install [hexo-generator-searchdb](https://github.com/flashlab/hexo-generator-search)? Only this plugun is suppoerted by NexT, as i know.
3. How many posts do u have? In my book blog i have [posts with ~50k symbols](http://xn----8sbgbitbekygtz.xn--p1ai/%D0%B8%D1%81%D0%BA%D1%83%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%8B%D0%BD-%D0%BB%D1%8E%D1%86%D0%B8%D1%84%D0%B5%D1%80%D0%B0/144-%D0%BF%D0%B8%D1%80%D0%B0%D0%BC%D0%B8%D0%B4%D0%B0-%D1%84%D0%B5%D0%BD%D0%B8%D0%BA%D1%81/) and this search was work fine.

**Comment by zjh1943** [comment]
Sorry. I updated to 5.1.3 and deployed, then the css breaks. I have re-deployed and  fixed the css just now.
1. I have tried clone the clean version from <https://github.com/iissnan/hexo-theme-next>. Not work.
2. "hexo-generator-searchdb" is in my `package.json` and `./node_module` dir.
3. I have 86 posts. I guess more than 100k words( 1k+ words per post ).

Thanks for you help.

**Comment by zjh1943** [comment]
@ivan-nginx I have go to you blog. It loads quite a long time (10+ seconds), but finally success. I think it is relevant to the total number of words.

**Comment by ivan-nginx** [comment]
@zjh1943 yeah, i set settings to manual trigger in search because when first time user press search button, it will search whole site in `search.xml` file. This file around ~8 MB size. And any other requests by search button next time load instantly from cache. So, for that's big size data ~10 seconds is fine on simple vps server. Your site must take 1-3 seconds by fist time press search button.

So, u can also check browser's console log for errors. Maybe some scripts block js requests or something. Anyway, u can try to disable any 3-rd party additions like baidu / loading bar / etc. to test it cleanly. Just try to make clean blog with posts and search only, it must work; then make additions and see on changes.

**Comment by kangsunlei** [comment]
I met the similar problem. 
I tried to open the `search.xml` in the browser, and I saw some error.
> Input is not proper UTF-8, indicate encoding !

After I delete some words, the local search works.

**Comment by ivan-nginx** [comment]
@kangsunlei wich words u delete?

**Comment by kangsunlei** [comment]
@ivan-nginx If you have the same error message, you can locate the wrong line through the error information. There may be some characters or words that are not utf-8, delete them and try again.

**Comment by ivan-nginx** [comment]
@kangsunlei i don't have same problem with my native language. But i try to resolve this bug, if i catch him.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
