### ISSUE TITLE
菜单图标显示？，我配置没有问题啊

### ISSUE THREAD

**Issue by chenfanlinux** [iissnan/hexo-theme-next#2017]

**Comment by chenfanlinux** [comment]
我的菜单图标为啥一直都是？啊？

**Comment by Neveryu** [comment]
没有问题的

**Comment by ivan-nginx** [comment]
閱讀發行說明: https://github.com/iissnan/hexo-theme-next/releases

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
