### ISSUE TITLE
JS代码高亮问题(JS code highlight issue)

### ISSUE THREAD

**Issue by KokoTa** [iissnan/hexo-theme-next#2020]
当代码行数大于40行时会出现后续代码无高亮的问题，找了一下看到别人也有这种情况。
When code lines > 40, the highlight feature will have a problem.
![bug](https://user-images.githubusercontent.com/14892053/33776142-7248b620-dc7b-11e7-8b21-3f49465e928a.png)

**Comment by zhuzhuyule** [comment]
估计是你代码不够规范导致的。

我的 高亮就没有问题呀，譬如：[This Bolog](https://zhuzhuyule.com/blog/HEXO/Gulp-Plgues.html#配置)，我也试了下，其他都可以。

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).
