### ISSUE TITLE
LiveRe 插件

### ISSUE THREAD

**Issue by chenfanlinux** [iissnan/hexo-theme-next#2021]
怎么下载

**Comment by reuixiy** [comment]
可以参考 [为hexo添加LiveRe来必力评论系统](https://linan.blog/2017/LiveReCommentsSystem/)

更多基础配置可以查看我的这篇文章—— [打造个性超赞博客 Hexo+NexT+GithubPages的超深度优化](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html)

:smile:

**Comment by chenfanlinux** [comment]
安装这个配置有问题，评论不生效

**Comment by reuixiy** [comment]
……

**Comment by Neveryu** [comment]
插件怎么下？这个问题，我觉得你应该要学会自己解决

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
