### ISSUE TITLE
label tag bug

### ISSUE THREAD

**Issue by reuixiy** [iissnan/hexo-theme-next#2022]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

![selection_004](https://user-images.githubusercontent.com/28993043/33802350-08885e12-ddb0-11e7-8a51-36fcc8e7a72e.jpg)

The rendered `label` tag should be included in `<p>` tag in the current situation.

### Actual behavior 

![selection_001](https://user-images.githubusercontent.com/28993043/33802368-cbece300-ddb0-11e7-8c2b-fa180e45a3dd.jpg)

`<br>` shouldn't be rendered.

![selection_003](https://user-images.githubusercontent.com/28993043/33802397-792707a8-ddb1-11e7-961f-2a363c733af4.jpg)

`<p>` appeared and  `<br>` disappeared after I deleted the `label` tag.

### Steps to reproduce the behavior 

1. Write the `label` tag at the beginning of the paragraph.

### Hexo Information

```
hexo-cli: 1.0.4
os: Linux 4.14.0-kali1-amd64 linux x64
http_parser: 2.7.0
node: 8.3.0
v8: 6.0.286.52
uv: 1.13.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 

The only solution I've found right now:

1. Do not write the `label` tag at the beginning of the paragraph.
2. Write `label` tag with HTML syntax, and include the paragraph in `<p>` by myself.

![selection_005](https://user-images.githubusercontent.com/28993043/33802658-c184058c-ddb6-11e7-941a-ef8ec6b9cb55.jpg)

**Comment by ivan-nginx** [comment]
Sup!
Can u check [this](https://almostover.ru/2016-01/hexo-theme-next-test/#Label-tag-test)? It seems all work fine. But if u can give source code, i will try to fix it in the future.
But u're right, i remebmer when i make it was some bugs like this. Of course, labels need to use only with simple words, not with any other components. Anyway, this bug can fixed with markdown or markdown it ,but this is Hexo, not NexT.

**Comment by reuixiy** [comment]
:smile: Hi~
Yes, I've checked that before. Source code? I think there is no need to provide that, you can reproduce the behavior by writing the `label` tag at the beginning of the paragraph, perhaps… :sweat_smile:

**Comment by ivan-nginx** [comment]
So, what's the problem? U know this bug, u can around it. Perhaps, the question is: can u fix this bug?

**Comment by reuixiy** [comment]
I'd love to, but I don't know how to fix it because I had no programming experience before… believe it or not. :joy:

**Comment by ivan-nginx** [comment]
Well, anabody care and nobody don't know, but anybody want and want all for free. Just like free beer. :smile: U want free girls? Free food. And, of course, it must working fine. If this will not work fine, anyone must to fix it, but not me. Think about it: it's a logic:: u just take it, open it (like a girl) and start to stydy it, from top to the bottom. U when like it, sometimes it agry you (like a girl, yeah?), sometimes u do for it something what it will wonder you a lot of times in future. And u will know it. Think about it.

**Comment by reuixiy** [comment]
Thank you! Get it!

**Comment by geekrainy** [comment]
Try to use https://github.com/hexojs/hexo-renderer-markdown-it.
That's work fine for me.
The bug from https://github.com/hexojs/hexo-renderer-marked.

**Comment by reuixiy** [comment]
Thank you so much, I'll try it~

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
