### ISSUE TITLE
已自行解决

### ISSUE THREAD

**Issue by geyan666** [iissnan/hexo-theme-next#2023]

**Comment by geyan666** [comment]
我的博客www.dmgroup.site

**Comment by geyan666** [comment]
去掉canvas_nest特效还是有边框

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by celestialphineas** [comment]
You can close it already... He reopened the issue only to change the title to "I've solved this myself".
已自行解决 → Already solved by myself.

**Comment by ivan-nginx** [comment]
@celestialphineas ok, i see. And thank you.
