### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by siaimes** [iissnan/hexo-theme-next#2024]
hexo-theme-next-5.1.3

无法解析前缀和公式：$sum_i=\sum_{j=1}^{i}{\alpha{_j}}$

解析结果为：$sumi=\sum{j=1}^{i}{\alpha{_j}}$

**Comment by siaimes** [comment]
所以没人理我么？

**Comment by ivan-nginx** [comment]
[MathJax](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue+MathJax)?

**Comment by siaimes** [comment]
@ivan-nginx 是mathJax

**Comment by siaimes** [comment]
咦，标记为Resolved Maybe是什么意思呢？

**Comment by zhuzhuyule** [comment]
@siaimes hexo 本來就不支持....

**Comment by siaimes** [comment]
@zhuzhuyule 没有啊，只是这个解析失败了！其它都正常！

**Comment by siaimes** [comment]
又发现一个解析失败的：$p_l,p_{l+1},\cdots, p_r$

**Comment by siaimes** [comment]
@ivan-nginx [http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/](http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/)这个！！！

**Comment by siaimes** [comment]
最终解决方案：https://github.com/wzpan/hexo-renderer-pandoc

**Comment by amjiuzi** [comment]
```bash
npm install hexo-renderer-pandoc --save
hexo g -d
```
主页看到的文章
![math1.png](https://i.loli.net/2017/12/28/5a44678071144.png)
点击标题进入文章内容时
![math2.png](https://i.loli.net/2017/12/28/5a4467806f85c.png)
@siaimes  请问这是怎么回事 ??

**Comment by siaimes** [comment]
@amjiuzi 不知道，我不是客服啊，我只是分享了我自己遇到问题的解决方案。你得去其它issue看看，或者自己去开一个issue

**Comment by siaimes** [comment]
@amjiuzi 不过可能是*号的问题，markdown*号别有他用

**Comment by siaimes** [comment]
@amjiuzi pandoc好像是可以解决_的问题，所以我的公式里面有下划线就解决了！

**Comment by ivan-nginx** [comment]
Resolved [here](https://github.com/theme-next/hexo-theme-next/issues/10) and [here](https://github.com/theme-next/hexo-theme-next/issues/19).
