### ISSUE TITLE
bug提交toc

### ISSUE THREAD

**Issue by youshutong2080** [iissnan/hexo-theme-next#2025]
![image](https://user-images.githubusercontent.com/8230915/33919015-6866b1ba-dff1-11e7-88eb-83159592d3d6.png)

这个链接行为如何将其改为整行链接，以前的版本都是正常的，但回滚几个版本都不生效

**Comment by Neveryu** [comment]
现在不是整行了吗？

**Comment by xuchengpeng** [comment]
我也遇到了同意的问题，突然变成这样的

**Comment by chanshiyucx** [comment]
hexo更新的问题 [Nested `a` elements should not be used in TOC](https://github.com/hexojs/hexo/issues/2896) 

改改就好了 https://github.com/hexojs/hexo/pull/2898/commits/ef38893b774599b06f9c1f17f95957bb40c6d3bc

**Comment by chanshiyucx** [comment]
@Neveryu @xuchengpeng @youshutong2080 

hexo更新的问题 [Nested `a` elements should not be used in TOC](https://github.com/hexojs/hexo/issues/2896) 

改改就好了 https://github.com/hexojs/hexo/pull/2898/commits/ef38893b774599b06f9c1f17f95957bb40c6d3bc

**Comment by youshutong2080** [comment]
谢谢大神指点
