### ISSUE TITLE
social icons显示异常

### ISSUE THREAD

**Issue by steve-yuan-8276** [iissnan/hexo-theme-next#2026]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
按照[说明文档](http://theme-next.iissnan.com/theme-settings.html)和[isuues](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E4%BE%A7%E8%BE%B9%E6%A0%8F%E7%A4%BE%E4%BA%A4%E9%93%BE%E6%8E%A5)提示的操作方法，在[fontawesome](http://fontawesome.io/icons/)找到相应的图片名称，但是显示结果很预期的不一样。

### Actual behavior 
实际显示效果是这样的（如图），只有facebook正常，其他三个图标都不对，不知道为什么。
![](http://oslz30y7b.bkt.clouddn.com/17-12-14/74306491.jpg)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: http://www.steve-yuan.com/
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.3
hexo-cli: 1.0.4
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
mac OS 10.13.2     Browser: chrome62

**Comment by steve-yuan-8276** [comment]
已经解决了，是我自己没有注意文档说明，闹笑话了。

**Comment by Neveryu** [comment]
你是真的僵~

**Comment by ivan-nginx** [comment]
Please, read [releases notes of 5.1.3 version](../releases/tag/v5.1.3).

**Comment by StevenShiChina** [comment]
我的图标也是这情况，您是怎么解决的？

**Comment by steve-yuan-8276** [comment]
后来认真看了说明文档，没有按规定动作来。

主题配置文件里有说明，按照这个格式，直接在social这里改， || 后面就是图标名称
social: GitHub: https://github.com/steve-yuan-8276 || github


下面那个social icons没有卵用，保持默认就好了。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
