### ISSUE TITLE
图片不能正确显示

### ISSUE THREAD

**Issue by lpplbiubiubiub** [iissnan/hexo-theme-next#2027]
我在_posts文件夹下新建文章，然后将想要引用的图片放在了/assets/post_image文件夹下，现在的问题是我可以在github里面正常浏览图片，图片的地址为/xxx/zones/raw/master/assets/post_img/xxx/4.png，而在对应的博客文章中，其地址变为/assets/post_img/xxx/4.png，导致无法正常显示。请问这个问题该怎样解决？

**Comment by Neveryu** [comment]
你要这样写的话，那你就使用绝对路径吧~

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).
