### ISSUE TITLE
A question about the configuration of appending new page[自定义页面的配置]

### ISSUE THREAD

**Issue by WhaleIsland** [iissnan/hexo-theme-next#2028]
I agree and want to create new issue.

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Additional a new page which not is a article page. 
添加一个首页代替原来的首页，把原来的首页改成一个 Menu 页面

### Actual behavior 
Rename the original homepage file to 'showmenu.swig'
- 把原来的首页文件重命名为 showmenu.swig

New addition 'index.swig'
- 新追加 index.swig

Adding in existing _config.yml menu menu> showmenu: / showmenu /
- 在 _config.yml 文件中追加 menu > showmenu : /showmenu/

### Hexo Information

hexo: 3.4.3
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.0
v8: 6.1.534.46
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2l
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

**NexT Version:**

```
Latest Master branch.
```

**NexT Scheme:**

```
Gemini
```

### Question
How to configure hexo render the page of layout folder which outside of the page in the original page？
如何配置可以让 hexo 渲染 layout 文件夹中原有页面以外的页面？

**Comment by zhuzhuyule** [comment]
先看看 [hexo-generator-index2](https://github.com/zhuzhuyule/hexo-blog-modify/tree/master/node_modules_modify/hexo-generator-index2) 是如何运行的，你的想法就可以实现了。
通过设置文章 ：分类，标签 就可以控制页面展示与否。
控制展示与否的[代码](https://github.com/zhuzhuyule/hexo-blog-modify/blob/master/node_modules_modify/hexo-generator-index2/lib/generator.js#L42-#L43)


你可以模仿 `hexo-generator-index2` 开发自己的插件，比如 我的：[hexo-generator-Me](https://github.com/zhuzhuyule/hexo-blog-modify/tree/master/node_modules_modify/hexo-generator-indexMe),没啥大改动了，只要 改动[此处](https://github.com/zhuzhuyule/hexo-blog-modify/blob/master/node_modules_modify/hexo-generator-indexMe/lib/generator.js#L98):
`return pagination(config.indexMe_generator.pagename, posts, {` -->
 `return pagination(config.showmenu.pagename, posts, {`；

你需要更换渲染模板，所以还要更改[此处](https://github.com/zhuzhuyule/hexo-blog-modify/blob/master/node_modules_modify/hexo-generator-indexMe/lib/generator.js#L100):
`layout: ['index', 'archive'],`   --->  
`layout: ['showmenu', 'index', 'archive'],`

**Comment by ivan-nginx** [comment]
Please, try to reproduce this behavior with any default Hexo theme ([light](https://github.com/hexojs/hexo-theme-light) / [landscape](https://github.com/hexojs/hexo-theme-landscape)).
If behavior will same, it's not NexT theme bug; close this issue and create same issue in [Hexo](https://github.com/hexojs) repositories: [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) or [hexo root engine](https://github.com/hexojs/hexo) will at most best choises.
