### ISSUE TITLE
如何更新next？

### ISSUE THREAD

**Issue by ailaiwuyou** [iissnan/hexo-theme-next#2029]
如何更新next？在官网没有看到有更新的教程

**Comment by WhaleIsland** [comment]
npm update hexo -g // 全局

**Comment by reuixiy** [comment]
在主题文件夹根目录`git pull`即可，如果报错，可以查看我的 [这篇文章](https://reuixiy.github.io/technology/computer/computer-aided-art/2017/06/09/hexo-next-optimization.html) 的第 2.3.2 节～

**Comment by ivan-nginx** [comment]
Read documentation on main NexT page. [Update](../#update) section.

**Comment by GH1995** [comment]
agree with @reuixiy . You can `git fetch` from [here](https://github.com/iissnan/hexo-theme-next.git), then try to `git merge`, sloving the confliction. Continue the loop.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
