### ISSUE TITLE
主页加个图片巡回展示

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#203]
方便企业展示产品。哈哈。

**Comment by iissnan** [comment]
这个。。你可以自己在模板里加

**Comment by vinyo** [comment]
怎加呀！来个示例。

**Comment by flashlab** [comment]
@iissnan 你可以考虑收费了;)

**Comment by vinyo** [comment]
额！收费就没人用了。会被泛生版。

**Comment by iissnan** [comment]
@flashlab :smile: 

@vinyo 这种问题其实很尴尬，增加这个功能应该没有问题，但是有其他的问题，例如：

1. 图片如何编辑替换等，目测只能手动去改动，也就是说可能带来其他新的需求，而这些需求在主题的层次几乎没有便捷的处理方式
1. 属于特定的个例

**Comment by iissnan** [comment]
没有考虑过收费的事情，@vinyo 说的也是一个事实，当一个作者想要将用其精力与时间来换取物质成果时总是困难重重。站在一个开发者的角度来说，我觉得更多的时候激励他们花费时间去创造一些东西是内在的原因（例如好奇心与热情）以及这个东西可能带来的正向的精神反馈。

有感而发，罗嗦了一些无关主题的事情，权且当成个人碎碎念吧 :smile:

**Comment by vinyo** [comment]
设定特定的图片巡回展示 点击图片进入文章。。。直接在配置文件加，跟加友情连接一样。

**Comment by astraylinux** [comment]
这种各别需求，还是自己改吧，@iissnan不可能为大家做所有事的

**Comment by minoscc** [comment]
其实作者只要按照自己的想法做就行了~  喜欢的自然会用~  
想要自己定义自己去学css~   不然就出钱让别人做~
现在看到issue好多都是提说怎么加功能的~  wiki也不先看~     :neutral_face:
