### ISSUE TITLE
调查-跨博客的相关文章推荐

### ISSUE THREAD

**Issue by huiwang** [iissnan/hexo-theme-next#2030]
友情链接是大家常用的增加博客间交流的方法，但这种方法是静止的，非常死板。

我有一个新想法，就是在相关文章推荐的那一栏，不仅推荐自己博客的文章，也推荐其他博客相关的文章。当然，这种做法是相对的，在别人的博客里，别人也会推荐你的文章。这样能更灵活，更有效的增进博客间的联系，也可以帮用户发现更多的优质内容，当然也可以增加博客的流量。

比如说在我[这篇文章](http://hui-wang.info/2017/12/10/%E8%8E%B7%E4%BA%86%E4%B8%80%E7%AD%89%E5%A5%96%E5%8D%B4%E4%BB%8D%E7%84%B6%E5%A4%B1%E8%B4%A5%E7%9A%84%E5%88%9B%E4%B8%9A%E7%BB%8F%E5%8E%86/)的结尾，除了推荐博客内的文章，我还推荐了其他资源。

我不知道这个想法，有没有什么现实意义，大家觉得呢？

**Comment by reuixiy** [comment]
大佬的想法很好，现实意义肯定有，我之前有想过[「知识和图书馆」与「知识和互联网」的对比](https://reuixiy.github.io/philosophy/how/2017/11/25/a-catalogue-of-the-internet-s-knowledge.html)，在这个知识大爆炸的互联网时代，大众如何获取知识，大家如何交流知识，这是一个待解决的问题。知乎为什么能够火起来，就是因为它提供了一个解决方案——知识平台。当然，还不够完美……

emmmmm……好像又跑题了……回正题……我觉得你的意思是：做一个第三方平台，让各位博主把自己的文章提交给这个平台（或者平台自己抓取），这个平台再将这些文章进行分类处理（或者在文章提交时提供一个分类索引，让博主自己选择），然后博客通过调用这个平台的 API，获取这个平台处理后的资源（相关文章），并显示在相关文章的末尾。

为什么不直接自己加，就像你这篇文章的末尾一样？因为平台的力量比一个人的力量大，自己一个人可了解不了这么多内容，也就不能自己推荐很多资源。

另外，这个平台还可以利用这些资源做一个知识平台（像知乎那样的），按照用户注册时选择的分类推送资源，让平台上的注册用户可以对推送的文章点赞，并且还可以提供一些社交功能，让博主能够交流……

而且，这样（文章点赞）还可以解决上面「博客应用」中的一个问题——如何判断提交上来的（或者抓取到的）资源是优质资源，毕竟只是推荐博客中一篇文章的相关资源可不够，必须要是相关优质资源。

目前想到的问题：
1. 平台的用户，有博客的人可不多（相比于大众），这就限制了平台的发展

**Comment by huiwang** [comment]
@reuixiy 你知识平台的想法，很新颖，我之前没有想到过。如果我理解的正确的话，你说的只是平台解决的是知识的索引，分类，统一的入口。wikipedia作的应该就是这个工作，对吗？

我所说的这个想法，还没有上升到知识平台的高度。初衷是让写博客的人共享他们的资源，既帮助博主们拓展他们的流量来源，又帮助用户找到更多的他们喜欢读的文章。其实是解决友情链接死板的问题。

接下来，如果有了这个小圈子，我们确实可以提供其他更多的服务，但首先要把这个圈子建起来。

关于博主不多的问题，特别是独立博主，我确实没有考虑到，这真的可能成为一个问题。但我觉得，一个很小的圈子，是不是也可以创造出一些价值。

非常感谢你的反馈！你愿意尝试这个服务吗，哪怕只有我们两个人现在？

**Comment by reuixiy** [comment]
哈哈哈，感谢，这个想法也是一个偶然，且还不完美……

当然愿意尝试……不过只可惜我只是个有想法没技术的乞丐:new_moon_with_face:……估计帮不上大佬你:joy:……

**Comment by huiwang** [comment]
@reuixiy 我可不是什么大佬，实现这个也得埋头苦学。你如果愿意体验已经上帮上大忙了，这几天我先出一个简单的版本，现在我博客上试一下，接下来就联系你！你可以加我微信 mhuiwang 或发邮件 hedonplay@gmail.com。谢谢！

**Comment by geekrainy** [comment]
这个需求完全可以在第三方的写作平台碰到，这样的话丧失了独立博客的意义。

**Comment by huiwang** [comment]
@geekrainy 非常感谢你参与啊！你的意思是说在第三方平台就可以满足跨博客推荐的需求吗？能更详细的解释一下为什么独立博客，会因此失去意义，我对你的想法非常感兴趣。

**Comment by reuixiy** [comment]
@huiwang :smile: 好的

**Comment by geekrainy** [comment]
@huiwang 在我看来，第三方的博客平台诸如博客园、CSDN、简书、掘金等都可以满足文章的交流需要，而独立博客大都不想于他人的文章像混杂关联，因而才有“独立性"。但独立博客除了名博大都在交流方面不如第三方托管的博客平台OR写作平台，但是这不意味着要把独立博客的构建系统/工具发展成为一个个关联的平台。

**Comment by reuixiy** [comment]
独立非孤立，若孤立直接本地运行不是更妥，个人理解啊

**Comment by huiwang** [comment]
@geekrainy 多谢你的解释 :+1: 我明白了你说的独立性的意思。

我不知道我的理解对不对，但不妨一说，独立性，对我来讲，意味着我对博客有控制权，选域名，排版，加不加广告，都是自己控制的。

当然你所说的不想与其它博客混杂关联，也属于独立性的范畴。我们尊重每个人的喜好。

我只是从个人经历中学到，和别人多沟通给我带来了很多帮助，比如帮我结识更多的朋友，发现自己的不足，向优秀的人学习等等。但每个人的经历不一样，认识也不一样。

@geekrainy 谢谢你的反馈，如果你对这个做法现在不感兴趣，那等真正实现了之后，你愿意再给点反馈吗？

**Comment by huiwang** [comment]
@reuixiy 让你久等了，经过几天的开发，实现了第一个版本 😄 

- 插件地址 https://github.com/huiwang/hexo-recommended-posts
- 服务器地址 https://github.com/huiwang/encore
- 开发笔记及示例[文章](https://hui-wang.info/2017/12/22/%E5%AE%89%E5%8F%AF%E6%8E%A8%E8%8D%90%E7%B3%BB%E7%BB%9F%E5%BC%80%E5%8F%91%E7%AC%94%E8%AE%B0%EF%BC%881%EF%BC%89/)

期待你的反馈 😃

**Comment by reuixiy** [comment]
果然是大佬啊！

试了一下，很赞！运行正常，目前没遇到错误。

是用文章的 tag 来分析相关文章的吧，因为我发现我有一篇没加 tag 的文章提示`To have better recommendation, specify tags for Hello World`。

然后，我想起了一个 [类似的插件](https://github.com/tea3/hexo-related-popular-posts) ，也是利用 tag，不过它没有不同博客之间的推荐。

很棒，下一步应该要推广推广，才能将更多的博客通过大佬的作品连接起来～

**Comment by huiwang** [comment]
赞！嗯，现在只基于标签推荐，接下来看效果再优化。 你说的很对，推广很重要，用的人越多，效果才会越好，劳烦大家帮着测试宣传啊 :-)

**Comment by huiwang** [comment]
@reuixiy [这篇文章](http://hui-wang.info/2016/10/23/Hexo%E6%8F%92%E4%BB%B6%E4%B9%8B%E7%99%BE%E5%BA%A6%E4%B8%BB%E5%8A%A8%E6%8F%90%E4%BA%A4%E9%93%BE%E6%8E%A5/)推荐了你的一篇！

**Comment by reuixiy** [comment]
哈哈哈，看到了，我测试的时候也有你的文章出现

**Comment by huiwang** [comment]
第一个版本开发出来了，[这里](https://hui-wang.info/2017/12/02/%E5%AD%A6%E4%B9%A0%E5%A6%82%E4%BD%95%E5%AD%A6%E4%B9%A0/)和[这里](https://reuixiy.github.io/philosophy/how/2017/11/25/a-catalogue-of-the-internet-s-knowledge.html)已经实现了互推， 大伙能不能给点建议？

https://github.com/huiwang/hexo-recommended-posts

**Comment by huiwang** [comment]
谢谢大家的帮助，特别是 @reuixiy 和 @geekrainy ，第一阶段的调查先到此结束。
