### ISSUE TITLE
如何禁止解析html

### ISSUE THREAD

**Issue by siaimes** [iissnan/hexo-theme-next#2031]
如何让next不是解析markdown页面中的HTML代码，而是直接原样嵌入到生成的HTML页面中！

**Comment by siaimes** [comment]
要是可以的话，这样就可以在页面中自己做一部分效果了。

**Comment by siaimes** [comment]
或者提供一个环境，使得被环境包围的东西不是解析而是直接拷贝！

**Comment by zhuzhuyule** [comment]
三种方法：
### NO.3 
粗暴简单：直接写HTML内容即可。（注意：**Html** 内容不要添加 **换行/回车**，否则Markdown会自动j转义为`</br>`）

### NO.2 （解决你的问题，这个应该是个算个最优解）
使用Hexo中的忽略Markdown编译的标签：`<escape></escape>`，解析在[这里](https://github.com/hexojs/hexo/blob/2d0af8137206b37b4555bf1a10bb6d0979719963/lib/hexo/post.js#L15)
使用方法:
```html
<escape>
内容爱写啥写啥，反正原文返回
</escape>
```

### NO.1（推荐，有助于了解Hexo标签机制； 此方法依然会解析为 NO.2）
使用Hexo 自定义标签：（这里需要自定义）
保存路径：`.\themes\next\scripts\tags\ignore.js`， [去看答主Tags](https://github.com/zhuzhuyule/hexo-blog-modify/blob/master/themes/next/scripts/tags/ignore.js)
```js ddd.js
/* global hexo */
// Usage: {% ignore %} Something {% endignore %}

function ignore (args, content) {
  return content;
}

hexo.extend.tag.register('ignore', ignore, {ends: true});
hexo.extend.tag.register('ig', ignore, {ends: true});
```
使用方法：
```
{% ig %}内容{% endig %}

{% ignore %}
内容爱写啥写啥，反正不编译
{% endignore %}
```

**Comment by siaimes** [comment]
@zhuzhuyule 这样确实可以使得hexo不解析html，不过没有得到我想要的结果。

我想要的效果是页面中某一张图片是点击跳转到一个连接（使用 **[![图片说明]](图片连接)](跳转连接)** 实现 ），而其他图片是点击放大这样。

我将 **[![图片说明]](图片连接)](跳转连接)**生成的html直接拷贝到escape环境，去掉fancybox和fancybox.image这两个类，仍然不能达到点击跳转的目的，看了一下浏览器获取到的代码仍然有这两个类，于是跟踪了一下发现图片的点击放大这两个类是由utils.js（目录：hexo-theme-next\source\js\src\utils.js）强制加上去的。

我的代码：
```html
<a href="baidu.com" target="_blank" rel="group"><img src="test.jpg" alt="test"></a>
```
以下是浏览器中的html代码：
```html
<a href="baidu.com" target="_blank" rel="group" class="fancybox fancybox.image"><img src="test.jpg" alt="test"></a>
```
然后我在浏览器里面手动删除掉这两个类之后确实是可以点击跳转的！

这就不好弄了！大概想法是：
1. 自己写一个js，在utils.js运行完成之后运行，将有某一个标记的图片的fancybox和fancybox.image这两个类再次去掉；
2. 修改utils.js让其识别某一个标记，遇到这个标记就不要加入fancybox和fancybox.image这两个类。

可是我不会做前端。。。

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
