### ISSUE TITLE
更新的最新的hexo后目录无法正常显示

### ISSUE THREAD

**Issue by 602689817** [iissnan/hexo-theme-next#2032]
![image](https://user-images.githubusercontent.com/11787200/34049577-eacf76d8-e185-11e7-8425-366c6a8cdc12.png)
如图，原来是有链接点击可以跳转，现在无法点击。

**Comment by 602689817** [comment]
![image](https://user-images.githubusercontent.com/11787200/34071624-a056fc7c-e246-11e7-8a81-c0b8faabf1c9.png)
如果有编号就出现这种情况，只有编号是可以点击的链接，文字不可以点击。
![image](https://user-images.githubusercontent.com/11787200/34071630-c97bc786-e246-11e7-8aad-4d064e7e5ddd.png)
<a/>标签只包着编号，文字没有

**Comment by zhuzhuyule** [comment]
the same [issues#2035](https://github.com/iissnan/hexo-theme-next/issues/2035)!

this bug is from hexo/issues#2896, you can update Hexo .

**Comment by ivan-nginx** [comment]
Solved [here](https://github.com/theme-next/hexo-theme-next/issues/16).

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
