### ISSUE TITLE
RSS开启后会自动打开社交链接DIV

### ISSUE THREAD

**Issue by SylarMa** [iissnan/hexo-theme-next#2033]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
只打开RSS功能

### Actual behavior 
打开RSS后会自动打开社交链接DIV，即使社交链接没开也会留白DIV框。

### Steps to reproduce the behavior 
1. rss:
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.3
hexo-cli: 1.0.4
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 9.2.1
v8: 6.2.414.44-node.11
uv: 1.16.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

### NexT Information

**NexT Version:5.1.3

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by SylarMa** [comment]
实际效果可以看malonghua.com的侧边栏RSS下

**Comment by reuixiy** [comment]
![selection_001](https://user-images.githubusercontent.com/28993043/34067471-d67a2db8-e261-11e7-9f02-8ad9e64c19b5.jpg)

这是你想要的效果吗？

**Comment by SylarMa** [comment]
@reuixiy 你这是什么浏览器，我用火狐、edge都不行会有
`          <div class="links-of-author motion-element">
            
          </div>`
形成的空白，在rss和links之间
IE干脆不显示这个图片的所有内容

**Comment by reuixiy** [comment]
Chrome……我这样看也有空白，我是 F12 调成这样的……你自己也可以调一调，然后 Copy 更改后的 CSS 代码到 `~/blog/themes/next/source/css/_custom/custom.styl` 即可……

**Comment by geekrainy** [comment]
Fixed https://github.com/iissnan/hexo-theme-next/pull/2040

**Comment by ivan-nginx** [comment]
@geekrainy thank's!

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
