### ISSUE TITLE
hexo-next为啥文章预览那里我的文章跳转只能点击前面的数字

### ISSUE THREAD

**Issue by eibitme** [iissnan/hexo-theme-next#2035]
![heheh](https://user-images.githubusercontent.com/31364191/34072188-bd2e8ea6-e2bd-11e7-91b4-5ec478983aa2.png)

**Comment by zhuzhuyule** [comment]
Bug 来源于： [hexo/issues#2896](https://github.com/hexojs/hexo/issues/2896)

**Comment by chuxubank** [comment]
https://github.com/hexojs/hexo/issues/2896

**Comment by alanhg** [comment]
downgrade hexo to v3.3.9

**Comment by xuchengpeng** [comment]
hexo 3.4.4 released, have fixed this bug

**Comment by Arthurwu24** [comment]
@xuchengpeng  why can't i upgrade to 3.4.4? 

- first of all, i tried type `npm ungrade -g`,then i got this.
![image](https://user-images.githubusercontent.com/9261202/34320045-acb5a9ba-e82b-11e7-8ef9-2b7dd6ae6542.png)

then i type command `hexo version`,it is still on 3.4.3

- then i tried `npm install hexo-cli -g`,i got this
![image](https://user-images.githubusercontent.com/9261202/34320072-0c0522b0-e82c-11e7-8535-2162dbe24c30.png)

still failed,what's wrong with the command ?  Am i doing upgrade wrong ?

**Comment by xuchengpeng** [comment]
get into your blog folder,    npm update hexo
  

  
  

  
  
>

**Comment by Arthurwu24** [comment]
@xuchengpeng  
Thx,bro. It worked. 

The official website and github didn't say so.

**Comment by boomclub** [comment]
@eibitme 你好，我也遇到了同样问题，请问你是如何解决的？

**Comment by ivan-nginx** [comment]
If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).
