### ISSUE TITLE
disqus的语言不是英文

### ISSUE THREAD

**Issue by Aria461863631** [iissnan/hexo-theme-next#2036]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
disqus出现英文

### Actual behavior 
出现的是匈牙利文，一开始装上主题的时候默认也是匈牙利文需要手动改成英文
Még nincs hozzászólás

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by Aria461863631** [comment]
Apologize for my misbehavior.
What I want to ask say is that my disqus is hungarian rather than English, and I can't solve it.
I've already set the language to English both in Disqus and Next theme, but still doesn't work.
I remember when I first installed Next it was also hungarian until I change the language manually, is that relative？
Thanks a lot！

**Comment by ivan-nginx** [comment]
@Aria461863631 in Disqus u must set language in Disqus system (in [their web-configuration](https://almostover.disqus.com/admin/)), not in NexT theme.

If solved, close it please.
