### ISSUE TITLE
突破容器宽度限制的图片无法正常居中是什么问题

### ISSUE THREAD

**Issue by eibitme** [iissnan/hexo-theme-next#2039]
设置突破容器宽度限制的图片存在无法居中，总是靠右显示。左边栏没有超出，右边栏超出很多，如何居中显示？
[live demo](http://ray-eldath.tech/)

**Comment by geekrainy** [comment]
给出一个 live demo?

**Comment by eibitme** [comment]
@geekrainy  类似这样子 [live demo](http://ray-eldath.tech/)  不管哪个scheme都一样

**Comment by geekrainy** [comment]
已修复。#2043

**Comment by ivan-nginx** [comment]
Merged.
If solved, close it please.
