### ISSUE TITLE
安装algolia搜索插件失败

### ISSUE THREAD

**Issue by amjiuzi** [iissnan/hexo-theme-next#2041]
next version: 5.1.3
```bash
npm install hexo-algolia --no-optinal
hexo algolia
```
![err1](https://i.loli.net/2017/12/19/5a38a21f76dc5.png)

**Comment by lanpangzhi** [comment]
http://blog.langpz.com/2017/12/22/Hexo-Next%E9%9B%86%E6%88%90Algolia%E6%90%9C%E7%B4%A2/  你可以看下我安装的过程，我猜你可能是环境变量没配置     export(windows 为 set) HEXO_ALGOLIA_INDEXING_KEY=你的Search-Only API key     如果是 Powershell 用 $env:

**Comment by amjiuzi** [comment]
@lanpangzhi 
谢谢你的解答，按照你的笔记修改之后
![algolia0.png](https://i.loli.net/2017/12/27/5a4393a9439ae.png)

**Comment by lanpangzhi** [comment]
怀疑你的node版本太低，建议升级 7.6 以上版本

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
