### ISSUE TITLE
sidebar 下的description文字显示不全

### ISSUE THREAD

**Issue by yangcongtougg** [iissnan/hexo-theme-next#2042]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
### 具体问题
在hexo的.yml下配置Site下的description，不知道这里的div为什么会+17px，导致文字显示不全；
![222](https://user-images.githubusercontent.com/16517304/34142377-c943ce6c-e4c1-11e7-9f19-2390a5f322f7.png)

![66](https://user-images.githubusercontent.com/16517304/34142087-379eb68a-e4c0-11e7-88ab-c66e62651d92.png)
手动去掉的话会显示出来；
![1](https://user-images.githubusercontent.com/16517304/34142248-fa9208d6-e4c0-11e7-9298-c9b8bf78f782.png)

### Hexo Information

```
hexo -v3.4.3
```
### NexT Information
**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```
**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini

**Comment by geekrainy** [comment]
判断是否超出视图大小，超出出现滚动条，预留出滚动条的宽度像素，这里应该是有个判断错误。

**Comment by yangcongtougg** [comment]
也不知道V神会不会看到 - -

**Comment by geekrainy** [comment]
已修复。Fixed #2044

**Comment by yangcongtougg** [comment]
是否可以直接pull？

**Comment by geekrainy** [comment]
等待 @ivan-nginx 合并，如果等不及的话你也可以直接合并我的分支 https://github.com/geekrainy/hexo-theme-next/tree/fix/2042

**Comment by yangcongtougg** [comment]
thanks

**Comment by yangcongtougg** [comment]
Hi,geekrainy,还是sidebar文字遮挡的问题；当进入阅读全文之后，文字依旧遮挡；应该是少改了一个文件；可以告诉我具体的代码修改的位置吗，我fork一下。谢谢
![1](https://user-images.githubusercontent.com/16517304/34150264-d8998f5c-e4e2-11e7-8ae7-bf6cc50a1b96.png)
![2](https://user-images.githubusercontent.com/16517304/34150270-dc7a652e-e4e2-11e7-9683-4bd285f7023d.png)

**Comment by geekrainy** [comment]
我这边显示正常，清理下缓存试试。
![20171219003](https://user-images.githubusercontent.com/7333266/34150590-c0bc28bc-e4e3-11e7-9e31-8c846991cf85.png)

**Comment by nq117** [comment]
![image](https://user-images.githubusercontent.com/24732032/34187726-c485377e-e56d-11e7-8130-c9b5e39e28b3.png)
请问这个是怎么设置的

**Comment by nq117** [comment]
![image](https://user-images.githubusercontent.com/24732032/34187738-d7a06c3e-e56d-11e7-829a-94035f5d9821.png)
我的是这样的

**Comment by yangcongtougg** [comment]
@nq117 theme-next主题下的_config.yml配置中找到Schemes,可以切换样式；
@geekrainy 我这里清除缓存也是不可以的，公司和家中的电脑都试了；进入阅读全文后，点击站点概览，我左侧是有文章目录的；应该还是这个问题
![1](https://user-images.githubusercontent.com/16517304/34187970-f13c6c1e-e56e-11e7-94d3-3249f9e347eb.png)

**Comment by nq117** [comment]
@yangcongtougg   好  谢谢

**Comment by ivan-nginx** [comment]
@yangcongtougg `CTRL`+`SHIFT`+`R` — must clean cache with full refresh on Chrome.

**Comment by yangcongtougg** [comment]
@ivan-nginx Thank you I'll give it a try

**Comment by ivan-nginx** [comment]
So, issue is solved?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
