### ISSUE TITLE
主页不显示侧边栏

### ISSUE THREAD

**Issue by xiaozha87** [iissnan/hexo-theme-next#2045]
v5.1.3主页不显示侧边栏，设置配置文件如下：
scheme: Pisces
display: always

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).
