### ISSUE TITLE
Markdown Table（表格） the last column of the last line（最后一行最后一列）can not be empty（不能为空）

### ISSUE THREAD

**Issue by tingstory** [iissnan/hexo-theme-next#2047]
## Environment Info
hexo: 3.4.2
theme: next mist
hexo-cli: 1.0.4
os: Linux 3.10.0-693.5.2.el7.x86_64 linux x64
http_parser: 2.7.1
node: 6.11.3
v8: 5.1.281.107
uv: 1.10.2
zlib: 1.2.7
ares: 1.10.1-DEV
icu: 50.1.2
modules: 48
openssl: 1.0.2k-fips

## For BUG

Markdown Table（表格） the last column of the last line（最后一行最后一列）can not be empty（不能为空）

| 1  | 2  | 3  |
| -- | -- | -- |
| 1  | 2  |     |

如果为空，将会缺失最后一行最后一列。
If empty, the last column of the last line will be missing.

**Comment by Neveryu** [comment]
i dont think so.

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
