### ISSUE TITLE
有没有统计文章字数的第三方服务（Have anyone optional software plugin which have word count function ）？

### ISSUE THREAD

**Issue by Zhang21** [iissnan/hexo-theme-next#2048]
好像现在NexT官方文档上的第三方服务，只包含有全站字数统计。

请问有没有统计文字字数的插件？

谢谢！

**Comment by FannyChung** [comment]
@Zhang21 请问是在哪个issue呀？没找到~

**Comment by Zhang21** [comment]
@FannyChung 
Next第三方服务：<http://theme-next.iissnan.com/third-party-services.html>
