### ISSUE TITLE
在next-mist主题下怎样将原右侧边栏，改成左侧打开

### ISSUE THREAD

**Issue by RobertDawn** [iissnan/hexo-theme-next#2049]
在next-mist主题下怎样将原右侧边栏，改成左侧打开，就像这样的[demo](https://zhuzhuyule.com/)

**Comment by CJCSDN** [comment]
文档说目前仅 Pisces Scheme 支持 position 配置。影响版本5.0.0及更低版本。 同求解答

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
