### ISSUE TITLE
I can't change since time and the icon for my next

### ISSUE THREAD

**Issue by SuAdrenine** [iissnan/hexo-theme-next#2050]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
1.I want change since time in the "themes/next/_config.yml" file
2.I set social icons for such as Github: github
### Actual behavior 
1.The since time is doesn't change.
2.The social icons doesn't work.
### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
Screens? Live demo? Anything.

Also, mb [this](https://github.com/iissnan/hexo-theme-next/releases/tag/v5.1.3) will solve problem:

```yml
GitHub: https://github.com/yourname || github
```

**Comment by SuAdrenine** [comment]
<img width="111" alt="one" src="https://user-images.githubusercontent.com/13587388/34473468-12719a78-efae-11e7-91b2-b3d8f926c466.png">
<img width="97" alt="two" src="https://user-images.githubusercontent.com/13587388/34473469-12b0833c-efae-11e7-9106-16ea80801dc4.png">
like this two photo, the first one's social icons doesn't change to github's, the second one's since time I set 2016 but it shows 2017. I have set those in 'themes/next/_config.yml' file ,but it doesn't work.

**Comment by ivan-nginx** [comment]
`themes/next/_config.yml`
```yml
footer:
  # Specify the date when the site was setup.
  # If not defined, current year will be used.
  since: 2016

social:
  GitHub: https://github.com/SuAdrenine || github
```

***

Please, read #2061 issue.

**Comment by SuAdrenine** [comment]
Thanks! Both did work. But there are something wrong in the [document](http://theme-next.iissnan.com/theme-settings.html), I'm following this document config my themes.
Thank you!

**Comment by ivan-nginx** [comment]
@SuAdrenine need to close issue if it was solved.

**Comment by SuAdrenine** [comment]
Thank you!
