### ISSUE TITLE
关于gitment 的问题

### ISSUE THREAD

**Issue by smallage** [iissnan/hexo-theme-next#2052]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
我想我的gitment 可以正常使用评论功能

### Actual behavior 
gitment 评论框渲染成功并且也可以登录成功，但是在评论的时候鼠标是灰色的，我使用F12查看，在
<textarea placeholder="(发表评论)" title="" disabled=""></textarea>  评论框和发送的按钮上 都加了disabled,  我手动吧disbaled去掉之后，点击发送，弹出的提示：Error: Comments Not Initialized ,
[带有评论的页面地址](https://blog.smallage.net/2017/12/23/Centos7-4-%E6%9B%B4%E6%96%B0yum%E6%BA%90/#more)

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.4
hexo-cli: 1.0.3
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by mll120110** [comment]
出现一个问题，若新建中文标题的文章(中文+英文)，操作初始化评论，就会报错Error: Validation Failed，初始化评论请求，返回Status Code:422 Unprocessable Entity
。如果文章名字是纯英文，初始化评论正常。已经修改站点配置文件language: zh-Hans，现在使用Next主题，5.1.4（已经集成gitment），希望得到回复

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
