### ISSUE TITLE
hexo generate use too many time

### ISSUE THREAD

**Issue by wkq278276130** [iissnan/hexo-theme-next#2053]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
generated in 65 seconds

### Actual behavior 
15:33:57.952 INFO  682 files generated in 4.7 min
15:33:58.196 DEBUG Database saved

### Steps to reproduce the behavior 
1. 15:22:53.198 INFO  690 files generated in 5.6 min
    15:22:53.437 DEBUG Database saved

2.  15:33:57.952 INFO  682 files generated in 4.7 min
     15:33:58.196 DEBUG Database saved

3.  15:55:35.060 INFO  680 files generated in 4.9 min
     15:55:35.323 DEBUG Database saved

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.3.8
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```
next 5.1.3

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 
before i update my hexo-theme-next, it cost 65 seconds when i use hexo generate
but after i merge to latest master,  it cost 4.7 min when i use hexo generate

15:33:57.952 INFO  682 files generated in 4.7 min
15:33:58.196 DEBUG Database saved

when i remove all just leave one article on _post, it debug message :
16:01:43.090 INFO  338 files generated in 3.43 s
16:01:43.135 DEBUG Database saved

**Comment by Neveryu** [comment]
随着你的内容越来越多，正常现象~

**Comment by wkq278276130** [comment]
@Neveryu 但是在升级主题前hexo generate 只需要60s左右，升级后需要5min

**Comment by ivan-nginx** [comment]
@wkq278276130 what version u use before? Need more info.

Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?

Also, can u tell how many posts/tags u have? Some links maybe...

**Comment by wkq278276130** [comment]
@ivan-nginx  

node -v
v6.10.0


 hexo -v
hexo: 3.3.8
hexo-cli: 1.0.3
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.7.0
node: 6.10.0
v8: 5.1.281.93
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k


{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.8"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.1.0",
    "hexo-algoliasearch": "^0.2.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
  }
}

**Comment by wkq278276130** [comment]
@ivan-nginx

i hava 97 post    105 draft     165 tags

**Comment by wkq278276130** [comment]
my website is http://weikeqin.cn/

**Comment by wkq278276130** [comment]
@ivan-nginx

my website is http://weikeqin.cn/

**Comment by ivan-nginx** [comment]
@wkq278276130 please, try to temporaily remove `hexo-wordcount` plugin and test again. Same speed?

**Comment by wkq278276130** [comment]
@ivan-nginx 

yeah, when i remove hexo-wordcount,  it just take 45s 

671 files generated in 45 s

thank you

**Comment by ivan-nginx** [comment]
@wkq278276130 u can try to replace `hexo-wordcount` by [this](https://github.com/theme-next/hexo-symbols-count-time) plugin.

Close it if solved.

**Comment by wkq278276130** [comment]
the reason is there are some line have million words in my page
when i remove hexo-wordcount,  671 files generated in 45 s

**Comment by ivan-nginx** [comment]
Yeah, `worcount` have internal filtering by unicode, that's why he's so slowly.
