### ISSUE TITLE
master 分支 Mist 主题正文字体在手机上显示过小

### ISSUE THREAD

**Issue by xerlang** [iissnan/hexo-theme-next#2055]
# 问题

使用默认字体大小（14px）的情况下，master 分支 Mist 主题正文字体在手机上显示过小，而其他主题和Release 5.1.3 版本中的Mist主题却正常，所以是 master 分支 Mist 主题的问题。

对比图如下。可以明显看出字体大小不一致，在手机上更为明显。

## master Mist 截图

![master Mist](https://user-images.githubusercontent.com/34172455/34368801-ab8b57e2-eaf1-11e7-813a-b24aaef43d79.PNG)

## Release 5.1.3 Mist 与 master 其他主题截图

![Release 5.1.3 Mist与master其他主题](https://user-images.githubusercontent.com/34172455/34368789-95bf9e00-eaf1-11e7-8748-4d991a2c584c.PNG)

# 环境

- Hexo：3.4.4
- Next：Latest Master branch

**Comment by shaoyy147** [comment]
我的Mist主题也遇到同样的问题，求解。

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
