### ISSUE TITLE
next升级后的公式渲染问题

### ISSUE THREAD

**Issue by amjiuzi** [iissnan/hexo-theme-next#2058]
next升级之前mathjax公式显示一直正常
升级之后未做任何改动,公式无法正常显示
于是
```bash
npm uninstall hexo-renderer-marked --save
npm install hexo-renderer-pandoc --save
hexo g -d
```
1. markdown 公式：
```
### 原理
1. A/B系数计算
$$Score.....= A - B * log(odds)$$
$$Score + pdo = A - B * log(odds/2)$$

$$
\begin{aligned}
B &= \frac{pdo}{log(2)} \\\
A &= Score + B * log(odds)
\end{aligned}
$$

- $odds$ - 坏好比 , 目标变量值 $1$ 的占比 除以 $0$ 的占比
- $pdo$ - $odds$ 变化时 $Score$得分的上下浮动差
<!--more-->
初始计算A/B值时, $odds$ 为整体数据的坏好比,即 
$$odds = \frac {P_{B_{T}}}{1-P_{B_{T}}}$$
```
1. 网站主页看到的文章
![math1.png](https://i.loli.net/2017/12/28/5a44678071144.png)
2. 点击标题进入文章内容时
![math2.png](https://i.loli.net/2017/12/28/5a4467806f85c.png)

**Comment by sli1989** [comment]
there is a problem: `TypeError: Cannot read property 'template' of undefined` when `hexo g`. uninstalling the hexo-renderer-pandoc it works

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by sli1989** [comment]
try to modify [mathjax](https://sli1989.github.io/2016/10/17/markdown-user-guide/#hexo-mathjax) and Romove `the if(config.template) args.push("--template=" + config.template);` in `index.js` using `hexo-renderer-pandoc` ([the issue](https://github.com/theme-next/hexo-theme-next/issues/10)), at the same time,  close the mathjax support in the theme's  `_config.yml`.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
