### ISSUE TITLE
如何使用Travis持续集成hexo代码，同时保存在coding和github上

### ISSUE THREAD

**Issue by iiskei** [iissnan/hexo-theme-next#2059]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by wkq278276130** [comment]
添加两个仓库，每次提交到两个仓库
git remote add origin  github.git
git remote add coding coding.git

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

Also, if your issue refers to 6.x version, please, [create issue in corresponding repository](https://github.com/theme-next/hexo-theme-next/issues).

**Comment by iiskei** [comment]
How to use Travis to continuously integrate hexo code while saving on coding and github？

**Comment by ivan-nginx** [comment]
This is not NexT theme question. U can create this issue in Hexo issues, not in NexT.

**Comment by iiskei** [comment]
OK，thank u !
