### ISSUE TITLE
Page blank: Uncaught ReferenceError: jQuery is not defined&$ is not defined

### ISSUE THREAD

**Issue by Pkuflint** [iissnan/hexo-theme-next#2060]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I visited my blog using Chrome 62.0.3202.94. The blog page should load normally.

### Actual behavior 
The blog page does not load. Only some background is displayed. 
![](http://7sbpes.com1.z0.glb.clouddn.com/pageBlank.png)

And i got the error in developer panel saying:
![](http://7sbpes.com1.z0.glb.clouddn.com/developerPanelError.png)

### Steps to reproduce the behavior 
1. Just type in pkuflnt.me, the blog name and visit it.
2. This happens often, but does not 100% reoccur. If you refresh the page like 2-3 times, the error will go away and the page will load.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 6.9.1
v8: 5.1.281.84
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 5.1.0
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

### Other Information 
Screenshots are above. This happens both in mac and windows.

**Comment by ivan-nginx** [comment]
> Just type in pkuflnt.me

ERR_NAME_NOT_RESOLVED

***

Could you please provide the following information?

* Node.js and NPM version ($`node -v && npm -v`)?
* Hexo version ($`hexo -v`)?
* Your site package dependencies ($`cat package.json`)?

***

Please, try to follow next steps:

1. Backup your source of `themes/next` directory.
2. Switch to latest release version (see `Download latest master branch.` section in main readme).
3. Try to catch same error by refreshing browser with `CTRL` + `SHIFT` + `R`.

OR

Try to check [latest master branch](../#download-latest-master-branch). Issue still exists?

**Comment by jcf94** [comment]
Try to add: 
```
lazyload: true
```
in `_config.yml` or your `next.yml`, see if it's fixed.

I got same error when updating my old version to the 6.0 version.

**Comment by ivan-nginx** [comment]
@jcf94 but `lazyload` in 6.0 moved to external lib, right?

**Comment by Pkuflint** [comment]
I used another directory to upgrade to v6.0 and the errors are gone now.

**Comment by ivan-nginx** [comment]
For anyone, who want to upgrade from 5.x to 6.x, — #2067.

**Comment by ivan-nginx** [comment]
@Pkuflint so, issue is solved? Close it if solved.

**Comment by iiskei** [comment]
我的也是页面一片空白
