### ISSUE TITLE
I want to redirect to other website when I click the menu item

### ISSUE THREAD

**Issue by chenfengkg** [iissnan/hexo-theme-next#2063]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.2
hexo-cli: 1.0.4
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information 
I want to redirect to other website when I click a menu item.for example,when I click photography,I want to redirect to www.tuchong.com. how should I do?

**Comment by ivan-nginx** [comment]
Please, read #2061 issue.

**Comment by chenfengkg** [comment]
I sloved this quesiton. when redirecting to other website ,we need to add http:// or https:// .
detail as followed,configure your theme's _config.yml like this:
```
menu:
  photography: http://tuchong.com || camera
```
Then you will be redirected to http://tuchong.com when you click photography item!

**Comment by ivan-nginx** [comment]
Cool)
