### ISSUE TITLE
谁能告诉我发生了什么？为什么突然到了6.0版本？

### ISSUE THREAD

**Issue by yoursaf** [iissnan/hexo-theme-next#2065]
@iissnan 你是要放弃NexT了吗？

**Comment by ivan-nginx** [comment]
NexT is rebased in [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
Please, read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
