### ISSUE TITLE
'/public/lib/' folder content was missed after `push` to remote

### ISSUE THREAD

**Issue by MARGI3** [iissnan/hexo-theme-next#2066]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

index page render successfully

页面正常渲染

### Actual behavior 

js css file was droped 

js css 文件丢失

### Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.4
hexo-cli: 1.0.1
os: Darwin 16.6.0 darwin x64
http_parser: 2.5.2
node: 4.4.4
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version -
git clone --branch v5.1.2 https://github.com/iissnan/hexo-theme-next themes/next
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 

local public folder content is correct 
本地的 public 文件夹的内容是正确的

![screen shot 2018-01-03 at 2 58 49 pm](https://user-images.githubusercontent.com/8514173/34511746-ac8204be-f098-11e7-9a28-92cf8341bbdc.png)

when use `git push` to origin master branch, the lib folder miss a few js css files 
将本地修改 push 到github时，lib 文件夹的内容 部分文件丢失了

![screen shot 2018-01-03 at 2 59 01 pm](https://user-images.githubusercontent.com/8514173/34511775-e7b2a55c-f098-11e7-94e8-3ccd543f9a59.png)

**Comment by MARGI3** [comment]
use 'locahost:4000' to preview the result was correct , so the local files was correct. 

but i was confused that a few files was dropped when i push the commit to the remote

**Comment by MARGI3** [comment]
replace theme eg: hueman,  it is correct. 

after use next release 5.1.3 version (zip resource) still the same problem, 'lib' folder content was dropped

**Comment by ivan-nginx** [comment]
U must check `.gitignore` file. Also, please, do not mix v6.x and v5.x repos. There is difference because all possible external libs (in `lib` directory) was moved out to external repos. See [here](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) for details.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by MARGI3** [comment]
delete github page content , and then "hexo init",  fetch next theme 6.0.1 , "hexo g", "hexo d" 

still not work.

**Comment by ivan-nginx** [comment]
Solved solution [here](https://github.com/theme-next/hexo-theme-next/issues/21).
