### ISSUE TITLE
how to set next's _config.yml when using hexo-renderer-pandoc

### ISSUE THREAD

**Issue by sli1989** [iissnan/hexo-theme-next#2068]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

completely display equation

### Actual behavior 

in `hexo-renderer-pandoc` version 0.2.1, adding `if(config.template) args.push("--template=" + config.template);` leads to `TypeError: Cannot read property 'template' of undefined` when hexo generate...
Romove the `if(config.template) args.push("--template=" + config.template);`, it works.
On the other hand,  how to set pandoc in `_config.yml` to avoid the undefined of  `template`   , thank you for your help.

```
pandoc:
  filters:
  extra:
  template:
  meta:
  mathEngine:
```

### Steps to reproduce the behavior 
1. npm uninstall hexo-renderer-marked --save
2. npm install hexo-renderer-pandoc --save
3. `TypeError: Cannot read property 'template' of undefined` when `hexo generate`
1. npm uninstall hexo-renderer-pandoc --save
2. npm install hexo-renderer-marked --save
3. successfully when `hexo generate`

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.4"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-generator-topindex": "^0.3.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-pandoc": "^0.2.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
NexT is rebased in [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, please, [create issue in v6.x repo](https://github.com/theme-next/hexo-theme-next/issues).

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by sli1989** [comment]
@ivan-nginx sorry for the mistake, it's version: 5.1.4...

**Comment by ivan-nginx** [comment]
Try to check it on version 6. Same error?

**Comment by sli1989** [comment]
@ivan-nginx the same erroe on version 6, besides, the menu bar & it's icon/Site'description/pages toc are all gone may due to personalized setting... i have given up trying...

**Comment by ivan-nginx** [comment]
So, u can create this issue in 6 version. Ok?

**Comment by sli1989** [comment]
@ivan-nginx yeah, thank u
