### ISSUE TITLE
关于对next主题浏览器兼容的问题

### ISSUE THREAD

**Issue by luengzeegin** [iissnan/hexo-theme-next#207]
我用火狐和IE打开作者网站，会出现英文缺失，但是我用chrome打开的话，则显示正常。
然后用猎豹浏览器（用的是chrome的内核），显示也是没有问题的，所以我觉得next对浏览器内核兼容有问题。

**Comment by iissnan** [comment]
我猜测是字体的问题

**Comment by luengzeegin** [comment]
我也有问过一些也用主题的朋友，他们也说是字体的问题，不过如果是字体的问题的话，应该每个浏览器显示效果都是一样的吧，所以应该是字体的兼容性有问题吗？

**Comment by iissnan** [comment]
不同的浏览器可能使用不同的字体渲染引擎。

**Comment by iissnan** [comment]
使用了 Google Font API 上 Lato 替换掉了内置的 Lato 字体，不过对于语言设置成 `zh-Hans`的用户来说，是不使用 Lato。详见 https://github.com/iissnan/hexo-theme-next/issues/249
