### ISSUE TITLE
Disqus is not working

### ISSUE THREAD

**Issue by qifengzhou** [iissnan/hexo-theme-next#2070]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates] (https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Disqus works after loading.

### Actual behavior 
Disqus does not show up at the end of blogs.

### Steps to reproduce the behavior 
1. next-thema -config.yml
disqus:
          enable: true
          shortname: qifengzhou
          count: true
2. 
hexo clean
hexo g # generate with the new settings
hexo s # start it local
3. hexo d # deploy also not working
* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo-cli: 1.0.4
os: Darwin 14.5.0 darwin x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[x] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
chrome
OS X 10.10.5

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)**.
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by qifengzhou** [comment]
Thank you ivan-nginx.
Should I open a new issue on the new site?

**Comment by ivan-nginx** [comment]
Yes, close it and open there.
