### ISSUE TITLE
怎么去除页面上方的黑线

### ISSUE THREAD

**Issue by zq-97** [iissnan/hexo-theme-next#2071]
## 电脑还好，但对于Android Chrome，如图，在浏览器地址栏和页面中间的黑线特别违和，请问如何取消之 
![screenshot_2018-01-09-00-04-40-905_com android ch](https://user-images.githubusercontent.com/17429111/34696992-3bea3f9a-f4d1-11e7-9620-78f5c155d5cb.png)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)**.
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
