### ISSUE TITLE
hexo 自定义背景图片后本地可以显示 ，上传后却无法显示

### ISSUE THREAD

**Issue by ALL3NYUAN** [iissnan/hexo-theme-next#2072]
hexo自定义背景图片后本地调试可以显示，部署到github后图片和样式文件都存在的，但在网页里就是不显示，不知道是什么原因，图片大小为700kb左右
上传后样式被添加到css目录下main.css中，代码如下
` ` `body {
  background: url("/images/city.JPG") no-repeat;
  width: 100%;
  height: 100%;
  background-size: 100% 100%;
  background-attachment: fixed;
}
` ` `

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
