### ISSUE TITLE
next-Pisces主题添加网易云音乐，在站点概览上显示不全

### ISSUE THREAD

**Issue by Yuhaha** [iissnan/hexo-theme-next#2075]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
![expected](https://user-images.githubusercontent.com/26532084/34815047-e39ceaba-f6ea-11e7-9bcc-14368dc6d7c4.png)

### Actual behavior 
![actual](https://user-images.githubusercontent.com/26532084/34815057-ef033ff8-f6ea-11e7-9b6c-2f21e45bcd21.png)

### Steps to reproduce the behavior 
1.在themes\next\layout\_macro\sidebar.swig中添加如下代码：
```
 <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=2083073&auto=0&height=66"></iframe>
```
![code](https://user-images.githubusercontent.com/26532084/34815070-fc4355d6-f6ea-11e7-90f1-9a149f0fe4d1.png)

* Link to demo site with this issue: https://yuhaha.github.io/
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 8.9.4
v8: 6.1.534.50
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[x] Pisces
[] Gemini
```

### Other Information 
站点概览的padding-top:
![1233](https://user-images.githubusercontent.com/26532084/34815860-f917b93a-f6ed-11e7-978a-a78f1504ddc0.png)

首页上的padding-top:

![123](https://user-images.githubusercontent.com/26532084/34815865-ff5d81da-f6ed-11e7-84e3-2eda14db0681.png)

改padding-top可以实现，不知道在哪里更改，themes\next\source\css\_custom\custom.styl中自己设定吗，还是有其他修改方法，如果在文章目录下也显示该怎么设置？求指导~

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
