### ISSUE TITLE
next主题内置标签centerquote出现问题，引号消失

### ISSUE THREAD

**Issue by geyan666** [iissnan/hexo-theme-next#2078]
对比图如下引号消失。
示例图
![1](https://user-images.githubusercontent.com/33111559/34915612-6ebe86e6-f964-11e7-8552-6cf1cecc7050.png)
异常图
![2](https://user-images.githubusercontent.com/33111559/34915617-7f890e92-f964-11e7-9df6-a36f3b184e28.png)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
