### ISSUE TITLE
6.0.1执行 hexo g 之后没有生成 index.html

### ISSUE THREAD

**Issue by panoshu** [iissnan/hexo-theme-next#2079]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [X] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
public 路径下有 index.html

### Actual behavior 
v6.0.1 执行 hexo g 之后 public 路径下没有生成 index.html

### Steps to reproduce the behavior 
1. hexo clean --config source/_data/next.yml && hexo g --config source/_data/next.yml
2. hexo s
3. 以上两步均没有报错，但是打开 localhost:4000 显示 cannot get，查看 pubic 路径发现没有生成 index.html

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

无

### NexT Information
无
**NexT Version:**

```
[] Latest Master branch.
[X] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[X] Gemini
```

### Other Information

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
