### ISSUE TITLE
移动端代码太长时不能横向滚动

### ISSUE THREAD

**Issue by atomicink** [iissnan/hexo-theme-next#208]
代码太长时无法横向滚动，看不到后面的

**Comment by iissnan** [comment]
我记得我在 iOS 设备上测试过是可以横向滚动的

**Comment by atomicink** [comment]
刚试了一下你的http://notes.iissnan.com/，不能啊

**Comment by iissnan** [comment]
@atomicink 确认了，是不行。。

**Comment by alim0x** [comment]
首页第一篇的代码块，PC端Chrome响应式模式测试会有滚动条，并且可以左右滑动，安卓自带浏览器测试，不显示滚动条，但可以左右滑动

**Comment by iissnan** [comment]
可能在 #266 这个 PR 中修复了

**Comment by iissnan** [comment]
目前已知无法代码无法滚动可能的原因有：

1. 页面其他元素撑开页面导致 ，见 #266 
2. 代码块代码行高过小，致使行本身具有滚动条，最终导致整体的滚动失效

如果确实无效，请尝试使用

```css
.highlight {
  -webkit-overflow-scrolling: touch;
}
```

见 #353
