### ISSUE TITLE
mist主题markdown的无序列表显示问题

### ISSUE THREAD

**Issue by liutf** [iissnan/hexo-theme-next#2081]
* 问题：按照markdown的正常渲染逻辑应该是实心圆，现在是个空心圆。  

![image](https://user-images.githubusercontent.com/14069370/35141140-eda316f6-fd34-11e7-8f8c-0ddc1b9171df.png)

* 期望：
![image](https://user-images.githubusercontent.com/14069370/35141212-3b20766c-fd35-11e7-8223-55710fe723a5.png)

 求教下。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
