### ISSUE TITLE
`Hexo g` generates CSS without version number but index.html require CSS with version number

### ISSUE THREAD

**Issue by 6061960** [iissnan/hexo-theme-next#2085]
The index.html requires CSS as below path,
```
/css/main.css?v=5.1.4
```

But `Hexo g` only generates CSS without the version number in my path.
```
/public/css/main.css
```
This causes style file request error when I deploy the generated website to the cloud.

No issue if I run the website with `hexo s`

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
