### ISSUE TITLE
hexo next主题 js,css文件访问404

### ISSUE THREAD

**Issue by oneion** [iissnan/hexo-theme-next#2089]
hexo next主题 js,css文件访问404

## 1.

正常访问应该是： 
https://oneion.github.io/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7
但是deploy上去发现是目标文件要多加个 **/hexoblog** 才能访问：
https://oneion.github.io/hexoblog/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7
多了一个目录 hexoblog

##  2

更新了_config.yml 
url: http://oneion.github.io/
root: /hexoblog/
发现github上的html文件里访问路径是正常了，
但是页面访问还是少了个**/hexoblog**

## 求解决办法
tips. 
1: CNAME 。nojekyll也都加上去了访问还是不到， 博客路径是
 https://oneion.github.io/hexoblog/

2.github地址是： https://github.com/oneion/hexoblog

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
