### ISSUE TITLE
如何在新的页面下用主页的样式渲染？

### ISSUE THREAD

**Issue by linyuxuanlin** [iissnan/hexo-theme-next#2090]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### 预期行为 
在一个新建的页面渲染出类似主页的卡片式文章展示，并且这个页面的文章不出现在主页（与主页文章不重叠）

### 实际行为 

none

### 重现步骤 

none

* Link to demo site with this issue: http://radiastu.com
* Link(s) to source code or any usefull link(s): http://lupeng.me/2015/06/06/Hexo_Docs3.html#3%E3%80%81%E6%A8%A1%E7%89%88

### Hexo Information

```
hexo: 3.5.0
hexo-cli: 1.0.3
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch.
- [ ] Latest Release version.
- [ ] Old version - 

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini

### Other Information 
 是否能通过修改页面布局的模板实现？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
