### ISSUE TITLE
I wonder if next theme support configuration visual width of article?

### ISSUE THREAD

**Issue by XiaochenCui** [iissnan/hexo-theme-next#2093]
I wonder if next theme support configuration visual width of article. If not, I suppose add this future to next.

For example, on the big screen, the article area looks too wide, and I want to make it narrower:

![](https://www.dropbox.com/s/d335tqja25xyb35/WX20180201-154055.png?raw=0)
![](https://dl.dropboxusercontent.com/content_link/Il3zxilaEJYRV6s7SKEbeAtqpVJTVgujHxqsscuDkR5kT9abJn4pTAljXoArwFI3/file)

### I agree and want to create new issue

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior
1. N/A
2. N/A
3. N/A

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information
```
hexo: 3.4.3
hexo-cli: 1.0.4
os: Linux 3.10.0-693.5.2.el7.x86_64 linux x64
http_parser: 2.7.0
node: 8.9.2
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
```

### NexT Information

**NexT Version:**
```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 5.1.3
```

**NexT Scheme:**
```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

### Other Information

None

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
