### ISSUE TITLE
如何才能切换语言显示？

### ISSUE THREAD

**Issue by jingle0927** [iissnan/hexo-theme-next#2097]
https://github.com/iissnan/hexo-theme-next/tree/master/languages 虽然提供了很多语言支持，但是如何才能切换语言或者说 国外的人访问是否可以根据ip切换英文或其他语言显示？

**Comment by darrenliuwei** [comment]
站点配置`_config.yml`文件里有`language: zh-Hans`选项来切换你喜欢的语言。
如果你想根据IP来切换语言的话，你可以弄两个站点，比如一个中文一个英文，国外IP访问英文站点，国内IP访问中文站点。
刘伟的博客：[darrenliuwei.com](https://darrenliuwei.com)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
