### ISSUE TITLE
next.motion.integrator undefined

### ISSUE THREAD

**Issue by smilepasta** [iissnan/hexo-theme-next#2098]
每次清除缓存后，第一次打开Blog主页就会出现这个问题，请问有什么解决方法吗？
博客地址： [http://www.smilepasta.com/](url) <br/>
<img src="http://cdn.smilepasta.com/images/error/hexo-next-error1.png" style="max-width:100%;"><br/>
<img src="http://cdn.smilepasta.com/images/error/hexo-next-error2.png" style="max-width:100%;">

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
