### ISSUE TITLE
添加多说评论一直有弹框出现怎么破？

### ISSUE THREAD

**Issue by Deeer** [iissnan/hexo-theme-next#210]

**Comment by atomicink** [comment]
我也碰到过。
要在站点的 _config.yml 里添加 duoshuo_shortname 字段，而不是在主题的  _config.yml 添加。

**Comment by Deeer** [comment]
@atomicink 已经设置了，但还是有这个提示

**Comment by rampagepeter** [comment]
多说shortname是指什么呀 我用了用户名，百度用户名，数字都不对啊

**Comment by Deeer** [comment]
好像是域名去掉.duoshuo.com的那一部分，但是我到现在还没弄好

**Comment by iissnan** [comment]
我更新了下使用 [多说的 Wiki 页面](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%B4-DISQUS)，请参考说明设置。

**Comment by iamwent** [comment]
@rampagepeter 要先注册多说——不仅仅是微博之类的登陆就ok，用户名就是shortname

**Comment by cosven** [comment]
我设置了shortname，结果还是弹窗。

我的站点名称填写为：ysw-blog
站点域名填写为：ysw-blog.duoshuo.com

然后再_config.yml中写入ysw-blog，结果页面还是弹窗提醒

**Comment by iissnan** [comment]
@cosven 多谢反馈。多说的 shortname 引用确实有问题，这可能的导致多说配置失败的主要原因之一。
