### ISSUE TITLE
hexo博客目录下使用next主题5.1.3开启LiveRe会全部页面底部都加上评论框问题

### ISSUE THREAD

**Issue by CJCSDN** [iissnan/hexo-theme-next#2108]
hexo博客目录下使用next主题5.1.3开启LiveRe会全部页面底部都加上评论框，如何才能只在_posts下的文章显示留言LiveRe？目录如下，现在是连我不需要显示的about、categories、tags等页面都加上LiveRe，如何让LiveRe只显示在_posts下的文章里？
```
source
 ├─ _posts
  |         ├── demo1文章.md
  |         └── demo2文章.md
 ├─ about
  |          └── index.md
 ├─ categories
  |          └── index.md
 └── tags
            └──index.md
```

**Comment by sli1989** [comment]
add `comments: false` in front-matter.

**Comment by CJCSDN** [comment]
你的意思是让我换6.0？

**Comment by sli1989** [comment]
just add `comments: false` in front-matter. It seems missing in your blog.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
