### ISSUE TITLE
some posts don't show on the home page

### ISSUE THREAD

**Issue by chenfengkg** [iissnan/hexo-theme-next#2109]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Steps to reproduce the behavior 
1.  I use hexo-generator-index to divide pages.
2. for some reasons ,I need to hide some post,I do the procedure as follow:
change he them/next/laytout/index.swig to like this:
 `<section id="posts" class="posts-expand">
    {% for post in page.posts %}
    	{% if post.visible !== 'hide'%}
      	{{ post_template.render(post, true) }}
    	{% endif %}
    {% endfor %}
  </section>`
as it  shows , I add a judgement to make  it don't render the post when I set the post's attribute visible to  hide.

then it show error!

it divide posts before redering  which make  the number of post in some page fewer than other pages.

you can visite my blog http://chenfengkg.cn.

my slution is to make redering post be first ,then  divide page.so this can slove this problem.but  I don't know how to change the code ,can any one help me .or do you have any other solution? Thanks in advance.

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[x] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
