### ISSUE TITLE
```代码不让它显示行数序号数字怎搞

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#211]
如题

**Comment by iissnan** [comment]
在站点配置文件中找到 `highlight` 节点，设置 `line_number` 为 `false`

**Comment by imzyf** [comment]
line_number: false
没有作用 依然显示行号

**Comment by aogooc** [comment]
@imzyf  please delete db.json, then execute hexo clean

**Comment by forliuyifei** [comment]
> @imzyf please delete db.json, then execute hexo clean

Thank U👍
