### ISSUE TITLE
博客菜单添加自定义页面后，发布文章后页面内容为空白

### ISSUE THREAD

**Issue by Andywang089** [iissnan/hexo-theme-next#2111]
### I agree and want to create new issue 

- [] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [X] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
问题简要描述如下：
1、博客基于hexo+Git+next构建
2、菜单添加自定义菜单：随笔、电子书分享、读书笔记、变成、学习、工具资源、影音
>设置如下：
menu:
  home: / || home
  essay: /essay/ || pencil-square 
  book: /book/ || book
  booknotes: /booknotes/ || pencil-square-o
  learncode: /learncode/ || code
  learning: /learning/ || leanpub
  tools: /tools/ || briefcase 
  media: /media/ || film 
  archives: /archives/ || history
  tags: /tags/ || tags
  about: /关于/ || user 
  categories: /categories/ || list

3、给自定义菜单添加页面，出现问题如图所示，页面内容为空白，以随笔为例：
添加随笔页面：hexo new page essay
在 essay 文件夹下的 index.md 文档中添加 “type: essay
发布文章时也在“front matter”中标明：essay，如下：
![](http://p4seftkqz.bkt.clouddn.com/2.jpg)

### Actual behavior 
但是发布后随笔页面依然为空白，这是什么原因呢？
![](http://p4seftkqz.bkt.clouddn.com/1.jpg)

### Steps to reproduce the behavior 

* Link to demo site with this issue: 
* Link(s) to source code or any usefull link(s): 

### Hexo Information

```
$ hexo v
hexo: 3.5.0
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64

```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[X] Old version - v5.1.4
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[X] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
