### ISSUE TITLE
关于%号前面的-

### ISSUE THREAD

**Issue by hainuo** [iissnan/hexo-theme-next#2114]
https://github.com/iissnan/hexo-theme-next/blob/ef1f33b372f48286c1c60343f39801dec3971a67/layout/index.swig#L8

请问这个-是不是多余的

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
