### ISSUE TITLE
图床图片无法显示-Can't display picture from url

### ISSUE THREAD

**Issue by OHLIA** [iissnan/hexo-theme-next#2116]
I agree and want to create new issue 

- [x] Yes, I was on Hexo Docs page, especially on Templates, Variables, Helpers and Troubleshooting.
- [x] Yes, I was on NexT Documentation Site.
- [x] And yes, I already searched for current issues and this is not help to me.

---

Expected behavior 

文章里面引用的图床的图片显示正常

Actual behavior 

无法显示，

提示“the requested content cannot be loaded. please try again later”

Steps to reproduce the behavior 

1. 按照markdown语法插入图床图片链接
2. hexo clean &&  hexo g 生成html文件
3. hexo s 或者hexo d
4. 浏览页面，图片无法显示

- Link to demo site with this issue: [PIC-Test](http://localhost:4000/2018/03/05/PIC-Test/)
- Link(s) to source code or any usefull link(s): 
---
    ![yHcS3.png](https://s1.ax2x.com/2018/02/10/yHcS3.png)
    
    ![yHaPp.png](https://s1.ax2x.com/2018/02/10/yHaPp.png)
    
    [![v8vZr.md.jpg](https://s1.ax2x.com/2018/02/08/v8vZr.md.jpg)](https://simimg.com/i/v8vZr)
    
    ![](http://ww1.sinaimg.cn/large/71ca360dgy1fp2bcza1ccj20qm0ig3z1.jpg)
---
Hexo Information

    (node:8336) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
    hexo: 3.6.0
    hexo-cli: 1.1.0
    os: Windows_NT 10.0.16299 win32 x64
    http_parser: 2.7.0
    node: 9.7.1
    v8: 6.2.414.46-node.20
    uv: 1.19.2
    zlib: 1.2.11
    ares: 1.13.0
    modules: 59
    nghttp2: 1.29.0
    napi: 2
    openssl: 1.0.2n
    icu: 60.2
    unicode: 10.0
    cldr: 32.0.1
    tz: 2017c
    

NexT Information

NexT Version:

    [] Latest Master branch.
    [x] Latest Release version.
    [] Old version - 

NexT Scheme:

    [] All schemes
    [] Muse
    [] Mist
    [x] Pisces
    [] Gemini

Other Information 

    I am sure the PIC URL can use normal.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
