### ISSUE TITLE
how dose list_categories() works for filter specific categories

### ISSUE THREAD

**Issue by Yalhu** [iissnan/hexo-theme-next#2117]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I want to show some specific categories on a category list page.
And get its length.

### Actual behavior 
```
 {{ list_categories(site.categories.find(function(v){return v.name!='categoryNotShow'})) }}
```
There is an error: Reserved keyword "return" attempted to be used as a variable on line 52 in file 
 ....\themes\next\layout\page.swig.
`{{ list_categories(site.categories.find({name:'categoryShow'})) }}` is work ok.
 I had two level of categories for now.  
And I don't want to filter it on a script after it had rendered all of the categories .
Is there any good solutions?

### Hexo Information

```
hexo-cli: 1.0.4
os: Windows_NT 10.0.10240 win32 x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[x] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```

### Other Information 
None.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
