### ISSUE TITLE
部署到github之后，页面空白， lib下文件404

### ISSUE THREAD

**Issue by gegenhasi** [iissnan/hexo-theme-next#2120]
## Expected behavior (预期行为) ##
本地预览和部署到gitpage上显示一样才对

## Actual behavior (实际行为) ##
本地预览没有问题，但是使用hexo d部署到git上去的时候，就是一片白屏，lib下文件404如图：

![image](https://user-images.githubusercontent.com/37357243/37551390-aa035e52-29d9-11e8-8b0d-fbd919755ab6.png)

### NexT Informations ###
next版本 5.1.4
 @iissnan

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
