### ISSUE TITLE
本地搜索无法成功弹出搜索框，显示一直加载的图案

### ISSUE THREAD

**Issue by sundongxu** [iissnan/hexo-theme-next#2122]
按照 https://theme-next.iissnan.com/third-party-services.html#search-system 此处正确配置后，点击搜索按钮，无法成功弹出搜索框，而是显示不断加载的图案，请问如何解决？bug如图所示：
![1](https://user-images.githubusercontent.com/13673539/37564425-bd05194e-2ad0-11e8-9be4-05fd2cbf538c.png)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
