### ISSUE TITLE
The page that used Travis to deploy the NEXT topic failed.

### ISSUE THREAD

**Issue by zhujinyao822** [iissnan/hexo-theme-next#2124]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
Due to lack of experience, the deployment page can not be successful, please consult your heroes here.

### Expected behavior 
I'm going to use Travis-CI to automatically deploy my page.

### Actual behavior 
During the Travis-CI deployment, I was reminded that my documentation does not exist.There is no problem when I use landscape themes.But when I switched to NEXT, I failed.Here is the tip for Travis-CI.
$ hexo g
INFO  Start processing
INFO  Files loaded in 250 ms
WARN  No layout: categories/index.html
WARN  No layout: tags/index.html
WARN  No layout: 2018/03/24/hello-world/index.html
WARN  No layout: 2018/03/23/001/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2018/index.html
WARN  No layout: archives/2018/03/index.html
WARN  No layout: categories/categories/index.html
WARN  No layout: index.html
WARN  No layout: tags/tags/index.html

### Steps to reproduce the behavior 
1. In the new folder,I use the following instructions.
   $ npm i -g hexo-cli
   $ hexo init
   $ cnpm i
2. Then, clone the NEXT topic file and configure it.
   $ git clone https://github.com/iissnan/hexo-theme-next themes/next 
3. I modified the content in the topic configuration file.(\myBlog\themes\next\_config.yml)
   Line 157:avatar: /images/me.jpg  //this is portrait
   Line 117:scheme: Gemini  //Replace the built-in theme.
   Line 94:  //Adjust the column
   And this file(\myBlog\_config.yml)
   Line 11:language: zh-Hans
   Line 76:theme: next
   In the Travis-CI configuration file,I provided the correct username, mailbox, and warehouse path.
4. Travis-CI settings
   I opened the following two options.
   Build only if .travis.yml is present        AND        Build pushed branches
5.The following is the upload log of Travis-CI.
In Attached file
[Travis-CI.txt](https://github.com/iissnan/hexo-theme-next/files/1843914/Travis-CI.txt)

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): github.com/zhujinyao822/zhujinyao822.github.io
### Hexo Information

```
$ npm -v
5.5.1
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[x] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
