### ISSUE TITLE
为什么我的next主题没有头像

### ISSUE THREAD

**Issue by zhaofengcheng** [iissnan/hexo-theme-next#2127]
![img_9697 20180328-003429](https://user-images.githubusercontent.com/37662656/37981364-1c4b8040-3220-11e8-9c1c-8697156efff7.jpg)
也不能添加背景音乐。。。。。。
而且这个是出了什么问题啊？？？
![img_9695](https://user-images.githubusercontent.com/37662656/37981410-39c8ec7a-3220-11e8-9300-5284ba076d99.JPG)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
