### ISSUE TITLE
Please register your site here/ 在这里注册你的站点

### ISSUE THREAD

**Issue by crazy-canux** [iissnan/hexo-theme-next#2130]
https://github.com/iissnan/hexo-theme-next/wiki/Powered-by-hexo-theme-next

开了一个page注册站点，不要在issue注册。

**Comment by sli1989** [comment]
[Your Blogs Here!](#119) the same thing?

**Comment by ivan-nginx** [comment]
1. This list will be in main **theme-next.org** site, so, no need to add issue or wiki page in NexT v6.
2. Why u add **hexo-theme-canux** in **hexo-theme-next**? This is at least irrelevant, no need to do this.
3. NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

    There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

    You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
