### ISSUE TITLE
Google時出現 Hexo, NexT 字樣

### ISSUE THREAD

**Issue by chiehpower** [iissnan/hexo-theme-next#2132]
各位好:
自己在google搜尋引擎搜尋自己的blog
但出現自己的網站標題是  Hexo, NexT - Blog title - Blog description
請教一下如果要刪掉前面的 Hexo, NexT要如何操作!? 
非常感謝!

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
