### ISSUE TITLE
最新版本(NexT-Mist v5.1.4) 集成Algolia功能时报TypeError: data.tags.map is not a function异常

### ISSUE THREAD

**Issue by AlanKeene** [iissnan/hexo-theme-next#2133]
$ hexo algolia
INFO  [Algolia] Testing HEXO_ALGOLIA_INDEXING_KEY permissions.
INFO  Start processing
WARN  ===============================================================
WARN  ========================= ATTENTION! ==========================
WARN  ===============================================================
WARN   NexT repository is moving here: https://github.com/theme-next
WARN  ===============================================================
WARN   It's rebase to v6.0.0 and future maintenance will resume there
WARN  ===============================================================
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: data.tags.map is not a function
    at F:\MyBlog\Hexo\node_modules\hexo-algolia\lib\command.js:113:39
    at Array.map (<anonymous>)
    at F:\MyBlog\Hexo\node_modules\hexo-algolia\lib\command.js:99:37
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
