### ISSUE TITLE
怎么使标签字体变大

### ISSUE THREAD

**Issue by lionliuchen** [iissnan/hexo-theme-next#2135]
![images](http://wx3.sinaimg.cn/mw690/006ykx3cly1fq0wy7mvt1j30k405wjtn.jpg)
我的标签的字体太小了，从哪儿可以使标签页的标签字体变大，还有颜色

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
