### ISSUE TITLE
How to align the math formula?（怎么对齐公式）

### ISSUE THREAD

**Issue by imhuay** [iissnan/hexo-theme-next#2138]
Generally, I use `\begin{aligned} .. \end{aligned}`, but it seems not support in the NexT.
```
$$
\begin{aligned} 
    P(X=1) & = p \\
    P(X=0) & = 1-p
\end{aligned}
$$
```

**Comment by ivan-nginx** [comment]
[Math docs](https://github.com/theme-next/hexo-theme-next/blob/master/docs/MATH.md) in new NexT repo.

***

NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
