### ISSUE TITLE
How to get images to show in "archives" page (or other timelines, e.g. tags, categories)? & How to get featured image?

### ISSUE THREAD

**Issue by nouyang** [iissnan/hexo-theme-next#2139]
I am trying to replicate some behavior in the demo site,
http://notes.iissnan.com/archives/

However, I do not know how to do so. I have tried searching other issues on this repository, however I'm having some difficulty understanding the posts in Chinese.

### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

1) I would like to make a photo gallery show up on the archives page timeline
2) I would like to make a "featured image" for my blog posts
![gallery](https://user-images.githubusercontent.com/764681/38764978-70248d8c-3f87-11e8-846e-dab896ff52be.jpg)
![featured_image](https://user-images.githubusercontent.com/764681/38764979-71a9e85a-3f87-11e8-8d92-668a55807e02.JPG)

### Actual behavior 

No photos appear in timeline

Additionally, I have no idea how to make a "featured image". I tried adding to the frontmatter
```
---
layout: post
featured_image: test.png
---
```
However, this did not do anything.

### Steps to reproduce the behavior 
1. hexo new post testgallery.md
```
---
type: "gallery"
layout: post 
title: testgall
photos:
 - images/pasted-0.png
 - images/pasted-1.png
date: 2018-04-14 01:27:32
tags:
---
test page
```

Go to `http://localhost:4000/my-site/archives/` -- no images appear

**NexT Scheme:**

```
[] All schemes
[] Muse
[] Mist
[] Pisces
[x] Gemini
```

###

What I really want to do, is to have a single "featured image" show up both on the index page and on the archives (timeline) pages. That is, a combination of being able to set a featured image in a post (maybe in the frontmatter), and have it show up in the archive with a picture thumbnail.

Is this possible?

Thank you very much for the beautiful theme.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
