### ISSUE TITLE
手机上浏览好像无法左右移动页面

### ISSUE THREAD

**Issue by JSSU** [iissnan/hexo-theme-next#214]
非常喜欢这个主题，很感谢分享！
最近想在手机上看自己写的code然后发现屏幕不能缩放，因为code超出的边界部左右移动没办法读所以想问下有没有办法可以调整页面缩放功能，或者这个是什么问题，应该怎么解决？

**Comment by xirong** [comment]
`code`部分超出边界的是可以左右移动的，这样子不也ok？ [参考-我的代码](http://ixirong.com/2015/03/16/something-about-fastdfs/)

**Comment by JSSU** [comment]
可能我哪边弄错了，code我用 ```cpp  (内容) ``` 来写的，超出部分移动不了， 我看了你的网站是可以移的。 还有一点是手机版本没有了显示个人信息的小按钮，就是原来右下角的那个。
很感谢帮助

**Comment by xirong** [comment]
@JSSU 嗯，code 部分就是这么来写，手机端屏幕太小，如果现实个人信息的话，排版上很不好看。你可以试试。

**Comment by JSSU** [comment]
@xirong 好的，我再研究研究。谢啦

**Comment by alviezhang** [comment]
我的代码区域也无法移动...

**Comment by iissnan** [comment]
与 #208 重复
