### ISSUE TITLE
点击菜单不跳转，反而只是刷新

### ISSUE THREAD

**Issue by AlexC-developer** [iissnan/hexo-theme-next#2140]
我的配置：
![image](https://user-images.githubusercontent.com/14200813/38765915-ca116f20-3ffc-11e8-92bb-8583363928f0.png)
网站页面：
![image](https://user-images.githubusercontent.com/14200813/38766146-71c45798-4000-11e8-8efd-b12a1925a243.png)

不知道为什么，前段时间还是好好的，今天试了一下居然不行了，点击菜单的任意图标都不能跳转，只会刷新页面，求大佬告知怎么解决

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
