### ISSUE TITLE
依照开始文档，Bundle exec jekyll server 操作时  出错

### ISSUE THREAD

**Issue by noodles1995** [iissnan/hexo-theme-next#2141]
# 我在依照官方文档操作时，Bundle etec jekyll server 报错 求告知
错误提示内容 Liquid syntax error (line 43): Unknown tag 'gist'

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
