### ISSUE TITLE
要是wordpress下也有这种主题就好了

### ISSUE THREAD

**Issue by 22881916** [iissnan/hexo-theme-next#2148]

**Comment by ivan-nginx** [comment]
For now this theme (NexT) officially only supported under the Hexo engine. There are same old clones under Jekyll or Hugo, but there are not officiall (many features was cutted-out in this clones / new features wasn't added). Under WP and similar engines NexT not planned to adapt for now.

BTW, 
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
