### ISSUE TITLE
可以增加延迟加载功能么？

### ISSUE THREAD

**Issue by chineselzh** [iissnan/hexo-theme-next#215]
可以增加图片和页面文章延迟加载功能么？
比如打开首页，显示几篇文章，当鼠标继续下滑的时候再加载其它文章。。。
又比如打开一篇文章后，当滑动到图片位置的时候再显示图片。。。
这些功能可以实现么？如果实现了访问主页和页面的速度又提升了，呵呵。。。
就像[yilia主题](https://github.com/litten/hexo-theme-yilia)一样

**Comment by araolin** [comment]
我倒是弄了个图片延迟加载，页面文章没弄http://www.arao.me/2015/hexo-optimize-pic-lazyload/

**Comment by chineselzh** [comment]
@araolin 看到了，谢谢！
