### ISSUE TITLE
MathJax公式显示错误(Math formula shows wrong)

### ISSUE THREAD

**Issue by Doraemonzzz** [iissnan/hexo-theme-next#2153]
使用数学公式之后出现以下错误，但有的时候又显示正常。
Sometimes the math formula looks like this and sometimes it is normal.
![](https://github.com/Doraemonzzz/md-photo/blob/master/Hexo/2018051510.png?raw=true)

**Comment by Doraemonzzz** [comment]
你好，谢谢你的回复。我查阅了这些配置，我的已经是这样了。其实我这个问题比较奇怪，有时候deploy之后公式可以显示，有时候又会出现上述情况。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
