### ISSUE TITLE
设置了canvas_nest: true  怎么没有效果？

### ISSUE THREAD

**Issue by jerryc127** [iissnan/hexo-theme-next#2154]
设置了canvas_nest: true  怎么没有效果？

**Comment by SurpassRabbit** [comment]
请问解决了吗？

**Comment by sli1989** [comment]
[ADD CDN vender](https://github.com/theme-next/theme-next-canvas-nest).

V6+ is recommended to [update](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md).
