### ISSUE TITLE
配置侧边栏社交连接后报错，不配置则没有错误

### ISSUE THREAD

**Issue by Sandry666** [iissnan/hexo-theme-next#2156]
![image](https://user-images.githubusercontent.com/30287824/41339263-f6ed4dd0-6f26-11e8-8ca0-63076890cf6c.png)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
