### ISSUE TITLE
How to change font-size on mobile webpage?

### ISSUE THREAD

**Issue by huyinjie** [iissnan/hexo-theme-next#2157]
The font-size on my mobile webpage looks so small , Can I change them?

![image](https://user-images.githubusercontent.com/8533957/41392255-3c39bd46-6fd2-11e8-996e-59d30871aa00.png)

I found the code below override the font-size I set in `source/css/_variables/custom.styl`
```
@media (max-width: 767px)
.posts-expand .post-body {
    font-size: 12px;
}
```
Can I change the font-size of `.posts-expand .post-body` to 14px in `custom.styl` ?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
