### ISSUE TITLE
文章可以增加已浏览多少次吗

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#216]
如题

**Comment by zqdongxw** [comment]
同求

**Comment by eurusd** [comment]
很难实现

**Comment by geekrainy** [comment]
有需求的可以自己修改主题，试试这个http://service.ibruce.info/

**Comment by wdnb** [comment]
静态的博客我感觉实现可能性为0.00001

**Comment by iissnan** [comment]
主题无法实现这个功能，试试 @geekrainy 提供的第三方服务吧

**Comment by ihappyhacking** [comment]
可以的，我用不蒜子实现了，就是现实的位置不太好选择，放在标题下面的话，在首页也会显示，但是只能显示某一篇文章的浏览次数，其他文章就显示不了，所以我还是去掉了，只显示网站访问次数和人数
