### ISSUE TITLE
文章发表时间会随着文章更新而更新为最新时间怎么解决

### ISSUE THREAD

**Issue by Jacknolfskin** [iissnan/hexo-theme-next#2160]
如题

**Comment by flyingzl** [comment]
将大特固定就好

**Comment by Jacknolfskin** [comment]
换了一台电脑，现在正常了

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
