### ISSUE TITLE
遇见一个bug在scheme: Gemini模式下百度分享不显示

### ISSUE THREAD

**Issue by CPUdream** [iissnan/hexo-theme-next#2161]
在scheme: Gemini主题下，百度分享type: button不显示，其它主题下是正确的，版本号是5.1.4，求解决 @Vinnl @iissnan @winterTTr

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
