### ISSUE TITLE
请问怎么出来多个标签，多个连接？

### ISSUE THREAD

**Issue by shuimaizi** [iissnan/hexo-theme-next#2165]
请问每篇文章里面，# 笔记 # 编程 # 学习 # 计算机程序的构造和解释 # SICP， 这个是怎么写出来啊。
我用MacDown, tags: 花园； 园艺

请问要怎么写啊，为什么不能出来多个连接啊， 怎么搞都是一个标签，一个连接

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
