### ISSUE TITLE
next_misc_sidebar position problem

### ISSUE THREAD

**Issue by Hackerfire** [iissnan/hexo-theme-next#2167]
next主题misc侧边栏的位置突然在底部显示，如何恢复正常，在右侧显示
![sidebar_problem](https://user-images.githubusercontent.com/39851540/44449497-e66f0580-a620-11e8-9ae2-ef2fdeea717d.png)

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
