### ISSUE TITLE
网站文章分享到QQ群QQ好友能实现没。

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#217]
如题

**Comment by geekrainy** [comment]
这种个别需求还是自己修改吧。

**Comment by vinyo** [comment]
额，百度分享可以

**Comment by iissnan** [comment]
使用了 JiaThis 的分享服务，具体效果见[这里](http://notes.iissnan.com/2015/angularjs-application-unit-testing-getting-stated/)，位置在评论的上方。
