### ISSUE TITLE
请问如何让侧边栏的文章目录全部展示

### ISSUE THREAD

**Issue by 1996szw** [iissnan/hexo-theme-next#2170]
现在都是每次滑到哪儿文章目录展开到哪。这样查看文章结构就很不方便，请问怎么设置才能让文章目录默认全部都展开？

**Comment by ztz12** [comment]
请问设置toc:
enable: true
(# 标题)虽然可以显示目录，但是无法点击跳转到指定位置，怎么解决

**Comment by HelloZCB** [comment]
add the code to themes/next/source/css/_custom/custom.styl
`.post-toc .nav .nav-child { display: block; }`

the menu will expand all levels by default.

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
