### ISSUE TITLE
网站顶部空白过大如何处理

### ISSUE THREAD

**Issue by yiny0liuyin** [iissnan/hexo-theme-next#2172]
![image](https://user-images.githubusercontent.com/41265413/45250143-e4ff4600-b35f-11e8-9239-fb003633e0aa.png)
如图空白过大,导致视觉效果不佳

**Comment by Mtax** [comment]
- [ ]  cdcd

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
