### ISSUE TITLE
不蒜子统计失效

### ISSUE THREAD

**Issue by jiang95** [iissnan/hexo-theme-next#2174]
http://ibruce.info/2015/04/04/busuanzi/
好像因为域名失效，原来的不蒜子统计失效，需要修改域名。
![image](https://user-images.githubusercontent.com/19852739/46711261-24ca8d80-cc7e-11e8-85a5-234d2535e977.png)

**Comment by L1H0n9Jun** [comment]
新版本 `6.4.2` 已经修改好了。
自己修改的话文件位置在 `/next/layout/_third-party/analytics/busuanzi-counter.swig`
```diff
{% if theme.busuanzi_count.enable %}
<div class="busuanzi-count">
{% if theme.busuanzi_count.enable %}
<div class="busuanzi-count">
- <script async src="原来的url/busuanzi/2.3/busuanzi.pure.mini.js"></script>
+ <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
```

然后就是部署三连。。。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
