### ISSUE TITLE
where are you?iissnan

### ISSUE THREAD

**Issue by TrumanDu** [iissnan/hexo-theme-next#2176]
## 为什么问这个问题？
[NexT v6.0.0 [Reloaded]](https://github.com/iissnan/hexo-theme-next/issues/2061)

看到这块就比较好奇了？未见iissnan回复，ivan-nginx是个好同志，扛起next大旗，但是还是很好奇iissnan干了什么？为什么抛弃自己一手创建的Next.

如题，知道的人回复一下，满足一个关注Next用户的亲切关怀。

**Comment by ChungZH** [comment]
问Vi他自己吧

**Comment by TrumanDu** [comment]
@iissnan

**Comment by TrumanDu** [comment]
@ChungZH 你知道什么消息么？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
