### ISSUE TITLE
头像怎么设置啊？

### ISSUE THREAD

**Issue by lingfohn** [iissnan/hexo-theme-next#218]
首先感谢作者无私奉献了这么好的主题，
问一下，头像怎么设置啊？
多谢！

**Comment by iissnan** [comment]
见 Wiki： [设置侧边栏头像](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E4%BE%A7%E8%BE%B9%E6%A0%8F%E5%A4%B4%E5%83%8F)

**Comment by magicyb** [comment]
按照上述方法设置，貌似没有效果。

**Comment by magicyb** [comment]
貌似我自己avatar拼错啦。感谢作者！！赞！

**Comment by ithuangqing** [comment]
# Site
title: ithuangqing
subtitle:
description:
author: ithuangqing
language: zh-Hans
timezone:
avatar：/images/avatar.png
在站点配置文件中新增avatar字段如上  执行hexo g的时候出现问题 请教为何

**Comment by PanGongsen** [comment]
@ithuangqing avatar：和/images/avatar.png之间必须有一个空格
