### ISSUE TITLE
刚搭建的blog: https://supremeyh.github.io/  欢迎来交流讨论啊

### ISSUE THREAD

**Issue by Supremeyh** [iissnan/hexo-theme-next#2188]
刚搭建的blog: https://supremeyh.github.io/  欢迎来交流讨论啊

**Comment by generalthink** [comment]
https://generalthink.github.io   来呀，交流呀

**Comment by a2396837** [comment]
@Supremeyh 你的标题有黑色背景，来看看我的：https://dmxis.me/

**Comment by Brainbg** [comment]
https://www.brainbg.com/

**Comment by ivan-nginx** [comment]
Post your blogs here: #119.
