### ISSUE TITLE
博客内容和头像间距过小怎么解决

### ISSUE THREAD

**Issue by Owenscu** [iissnan/hexo-theme-next#2193]
![image](https://user-images.githubusercontent.com/23129979/53003115-36604500-3469-11e9-8914-5af478ccdb28.png)

**Comment by stevenjoezhang** [comment]
请升级到新版：https://github.com/theme-next/hexo-theme-next
如果此问题仍然存在，欢迎提交issue

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
