### ISSUE TITLE
Markdown区块引用中插入一级标题被当做目录生成了

### ISSUE THREAD

**Issue by yandiwei** [iissnan/hexo-theme-next#2194]
![2019-02-25 19-48-18](https://user-images.githubusercontent.com/37269162/53335634-f43a7600-3936-11e9-9b84-532422471306.png)
如图，请问应该怎么处理？

**Comment by Brainbg** [comment]
# 侧边栏的目录
# Table Of Contents in the Sidebar
toc:
  enable: true
  # Automatically add list number to toc. 是否自动追加节点号
  number: false
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # Maximum heading depth of generated toc. You can set it in one post through `toc_max_depth` in Front Matter.
  max_depth: 6

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
