### ISSUE TITLE
next 不支持评论系统Disqus了？

### ISSUE THREAD

**Issue by jasonhzy** [iissnan/hexo-theme-next#2197]
next主题现在不支持评论系统了？_config.yml配置文件中：
# Disqus
disqus:
  enable: true
  shortname: xxxx
  count: true
配置后出错，不能加载文章

**Comment by stevenjoezhang** [comment]
暂时的解决方案是`count: false`。
此项目已经停止维护，请移步这里：https://github.com/theme-next/hexo-theme-next

**Comment by jasonhzy** [comment]
非常感谢

**Comment by stevenjoezhang** [comment]
可以关注一下这个：https://disqus.com/home/discussion/channel-discussdisqus/installation_disqus_suddenly_includes_its_own_jquery_version/
需要等Disqus官方修复

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x / v7.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
