### ISSUE TITLE
除了标题和footer外一片空白，控制台提示$(...).velocity is not a function？

### ISSUE THREAD

**Issue by Pudgedd** [iissnan/hexo-theme-next#2198]
NexT v6.0.0.
正常使用了一个月，在没有进行任何修改的情况下，突然今天打开页面一片空白，只显示标题和footer统计。控制台报错$(...).velocity is not a function。
<img width="1435" alt="屏幕快照 2019-03-11 23 06 00" src="https://user-images.githubusercontent.com/22662844/54134732-76588d80-4453-11e9-9d72-3ccd8e81e8bc.png">

**Comment by stevenjoezhang** [comment]
和https://github.com/iissnan/hexo-theme-next/issues/2197一样
暂时的解决方案是count: false。
此项目已经停止维护，请移步这里：https://github.com/theme-next/hexo-theme-next

**Comment by Pudgedd** [comment]
谢谢回复

**Comment by stevenjoezhang** [comment]
不客气，可以关注一下这个：https://disqus.com/home/discussion/channel-discussdisqus/installation_disqus_suddenly_includes_its_own_jquery_version/
需要等Disqus官方修复
