### ISSUE TITLE
v0.4.3 generate failed

### ISSUE THREAD

**Issue by alim0x** [iissnan/hexo-theme-next#220]
`hexo generate`:

ERROR Asset render failed: css/main.css
Error: hexo/themes/next/source/css/main.styl:14:27
   10| 
   11| // Variables Layer
   12| // --------------------------------------------------
   13| for $variable in $variables
   14|   @import "_variables/" + $variable
---------------------------------^
   15| 
   16| 
   17| // Mixins Layer

failed to locate @import file _variables/Mist.styl

I renamed `themes/next/source/css/_variables/mist.styl` to `themes/next/source/css/_variables/Mist.styl`, it works. Hope this could be help.

**Comment by iissnan** [comment]
@alim0x Thanks. This is a fetal issue. 

Your solution is right.  I have fixed this issue on the master branch and update the release 0.4.3 too.

**Comment by alim0x** [comment]
Thanks for fix it.:)
