### ISSUE TITLE
Disqus is not working

### ISSUE THREAD

**Issue by Sherlock2435** [iissnan/hexo-theme-next#2207]
Browser： Google
os:windows 10

I've determined that shorname is correct, and when Disqus is enabled, it will not display properly at the end of the article.

Here is the effect shown in the comments section of my local web page.:
![image](https://user-images.githubusercontent.com/35016940/59967874-69bff700-9563-11e9-9b32-672b1a163db7.png)

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net). Have you ever thought of migrating from Disqus, which has a plethora of shortcomings that deter many bloggers, say

1. privacy issues
2. slow load speed
3. no markdown support
4. poor SEO
5. high cost of migration

You may refer to these articles to know more.

1. https://victorzhou.com/blog/replacing-disqus/
1. https://old.reddit.com/r/programming/comments/b9022a/switching_off_of_disqus_reduced_my_page_weight_by/
1. https://medium.com/remys-blog/ejecting-disqus-4120e9985823
