### ISSUE TITLE
tags下面没法生成index.html,所以点击tags都是404

### ISSUE THREAD

**Issue by wdnb** [iissnan/hexo-theme-next#222]
这该如何解决?

**Comment by iissnan** [comment]
[创建标签云页面](https://github.com/iissnan/hexo-theme-next/wiki/%E5%88%9B%E5%BB%BA%E6%A0%87%E7%AD%BE%E4%BA%91%E9%A1%B5%E9%9D%A2)

**Comment by wdnb** [comment]
问题解决了 谢谢

**Comment by MeiMeng** [comment]
怎么解决的？

**Comment by wdnb** [comment]
根据上面给的链接,安装步骤来就搞定了

**Comment by dpyinjie** [comment]
就这个了，可以...
