### ISSUE TITLE
github pages 不支持 next theme?

### ISSUE THREAD

**Issue by yuwangi** [iissnan/hexo-theme-next#2226]
![image](https://user-images.githubusercontent.com/13346477/65567793-0ee6d300-df8a-11e9-848f-7016da4b47df.png)
本地运行时可以的    编译上传之后 
![image](https://user-images.githubusercontent.com/13346477/65567818-2920b100-df8a-11e9-9cd4-72fb3fb23947.png)
github 给发的邮件

**Comment by SkySkin** [comment]
支持呀，我的就说next模板 skyskin.github.io,这两天搭建的

**Comment by yuwangi** [comment]
你是怎么部署的？  用的什么工具？  能分享一下吗？



343046650@qq.com
 
发件人： SkySkin
发送时间： 2019-09-28 12:08
收件人： iissnan/hexo-theme-next
抄送： yuwangi; Author
主题： Re: [iissnan/hexo-theme-next] github pages 不支持 next theme? (#2226)
支持呀，我的就说next模板 skyskin.github.io,这两天搭建的

**Comment by SkySkin** [comment]
![image](https://user-images.githubusercontent.com/47810174/65829268-184ba480-e2d6-11e9-9a13-880b834e9537.png)

你好像上传错了啊，要上传public
![image](https://user-images.githubusercontent.com/47810174/65829275-2d283800-e2d6-11e9-9128-0d10c3f28865.png)

**Comment by SkySkin** [comment]
这个是我的
![image](https://user-images.githubusercontent.com/47810174/65829280-4c26ca00-e2d6-11e9-8bcf-70e7282ce4ac.png)
![image](https://user-images.githubusercontent.com/47810174/65829284-682a6b80-e2d6-11e9-8fb0-00446d0f6a89.png)

**Comment by yuwangi** [comment]
哦哦 我试试


343046650@qq.com
 
发件人： SkySkin
发送时间： 2019-09-29 16:29
收件人： iissnan/hexo-theme-next
抄送： yuwangi; Author
主题： Re: [iissnan/hexo-theme-next] github pages 不支持 next theme? (#2226)
你好像上传错了啊，要上传public

**Comment by yuwangi** [comment]
可以了   非常感谢！！    


343046650@qq.com
 
发件人： SkySkin
发送时间： 2019-09-29 16:30
收件人： iissnan/hexo-theme-next
抄送： yuwangi; Author
主题： Re: [iissnan/hexo-theme-next] github pages 不支持 next theme? (#2226)
这个是我的

**Comment by SkySkin** [comment]
很nice，解决就好 :+1:
