### ISSUE TITLE
侧边栏post链接跳转异常 #1836

### ISSUE THREAD

**Issue by jas502n** [iissnan/hexo-theme-next#2228]
http://localhost:4000/archives/%7C%7Carchive

![image](https://user-images.githubusercontent.com/16593068/67963657-ec577200-fc39-11e9-9caf-d94bab867aec.png)

![image](https://user-images.githubusercontent.com/16593068/67963592-d34ec100-fc39-11e9-93d1-b5a4c10749a1.png)

**Comment by stevenjoezhang** [comment]
THIS REPO IS NOT SUPPORTED ANYMORE!
DON'T NEED CREATE ISSUE HERE!
NEXT MOVED HERE: https://github.com/theme-next/hexo-theme-next

NexT is rebased into organization repo https://github.com/theme-next
If you want new feature, fix, or support, create new issue in NexT v6.x repo (desirable in English).

There is instructions
on English: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md
or Chinese: https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md
how to update from v5.1.x to v 6.x

You also may read this for details: #2061

该工程已不再提供任何支持与维护！
请大家不要再在这里创建issue了！
NexT主题仓库已移动到此处: https://github.com/theme-next/hexo-theme-next

NexT已经rebase到theme-next组织(https://github.com/theme-next) 的repo中.
如果你想要求新的特性，bug修复或其他支持，请在新的v6.x的仓库下创建新issue（最好用英文，谢谢）

英文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)
或中文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md)
如何从 v5.1.x 更新到 v 6.x

相关细节参考这里: #2061

**Comment by jamekuma** [comment]
我也遇到了同样的问题，请问你解决了吗
