### ISSUE TITLE
JiaThis还是会被ABP过滤啊

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#223]
能换成多说分享按钮吗？

**Comment by iissnan** [comment]
我使用 Google Chrome 的 [Adblock Plus](https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb) 没有被顾虑掉。你使用的是？

**Comment by vinyo** [comment]
@iissnan 我使用 Google Chrome 的 Adblock Plus你更新下规则是过滤的。

**Comment by alim0x** [comment]
@vinyo 使用 Google Chrome 的 Adblock Plus，没有被过滤

**Comment by vinyo** [comment]
你们是全过滤的么。
×   启用 Adblock Warning Removal List 最近更新于 今天上午9:18:45
×   启用 EasyList China+EasyList 最近更新于 今天上午9:18:50
×   启用 Malware Domains 最近更新于 今天上午9:18:47
×   启用 Fanboy's Social Blocking List 最近更新于 今天上午9:18:48
×   启用 EasyPrivacy 最近更新于 今天上午9:18:48

**Comment by alim0x** [comment]
×   Enabled EasyList Last updated at 10:14:32 PM on 6/13/2015
×   Enabled EasyList China+EasyList Last updated at 11:08:23 PM on 6/12/2015

**Comment by iissnan** [comment]
只是使用默认的 List。 能提供一个 多说分享按钮 的示例吗？ 
我看 [多说官网](http://duoshuo.com/)使用的是 bShare 的分享服务。

**Comment by xirong** [comment]
可以使用多说自带的分享插件，效果 http://ixirong.com/2015/05/17/how-to-build-ixirong-blog/#comments

**Comment by iissnan** [comment]
@vinyo @xirong 使用的多说分享插件会被过滤掉吗？ 如果没有，我将多说分享的插件添加上去。

**Comment by vinyo** [comment]
@iissnan 多说分享插件不会过滤

**Comment by xirong** [comment]
@iissnan  我使用的 `mac osx chrome  43.0.2357.124 adblock pro ` 没有问题的，你可以试试在你的环境下面访问  http://ixirong.com/2015/05/17/how-to-build-ixirong-blog/#comments 看是否ok

**Comment by vinyo** [comment]
@xirong OK的

**Comment by iissnan** [comment]
@vinyo 已添加 多说分享服务。需要注意的是：

1. 多说分享必须跟多说评论共同使用
1. 使用多说分享时，将 `JiaThis` 设置为 `false`
