### ISSUE TITLE
hexo-next-v6.7.0 首页 和 归档 按钮 显示乱码

### ISSUE THREAD

**Issue by Azjhong** [iissnan/hexo-theme-next#2231]
![Snipaste_2019-12-08_17-15-35](https://user-images.githubusercontent.com/46050133/70387290-75eb2400-19de-11ea-9e6c-d9eb4622501f.png)

**Comment by stevenjoezhang** [comment]
THIS REPO IS NOT SUPPORTED ANYMORE!
DON'T NEED CREATE ISSUE HERE!
NEXT MOVED HERE: https://github.com/theme-next/hexo-theme-next

NexT is rebased into organization repo https://github.com/theme-next
If you want new feature, fix, or support, create new issue in NexT v6.x repo (desirable in English).

There is instructions
on English: https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md
or Chinese: https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md
how to update from v5.1.x to v 6.x

You also may read this for details: #2061

该工程已不再提供任何支持与维护！
请大家不要再在这里创建issue了！
NexT主题仓库已移动到此处: https://github.com/theme-next/hexo-theme-next

NexT已经rebase到theme-next组织(https://github.com/theme-next) 的repo中.
如果你想要求新的特性，bug修复或其他支持，请在新的v6.x的仓库下创建新issue（最好用英文，谢谢）

英文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md)
或中文文档: (https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md)
如何从 v5.1.x 更新到 v 6.x

相关细节参考这里: #2061
