### ISSUE TITLE
请问如何关闭侧边栏？

### ISSUE THREAD

**Issue by wdnb** [iissnan/hexo-theme-next#224]
不想配置侧边栏，想直接关了

**Comment by iissnan** [comment]
主题 `_config.yml` 中有一个配置：

```yml
# Sidebar, available value:
#  - post    expand on posts automatically. Default.
#  - always  expand for all pages automatically
#  - hide    expand only when click on the sidebar toggle icon.
sidebar: post
#sidebar: always
#sidebar: hide
```

设置为 `sidebar: hide` 即可

**Comment by iissnan** [comment]
如果要完全去掉，改下模板，将 sidebar 块和对应的 sidebar-toggle 移掉就行了。

**Comment by xirong** [comment]
@iissnan  我试了下，设置为 `sidebar: hide` 不管用呢？ 从源码中也没有找到相关判断的地方，还有什么改动？

**Comment by iissnan** [comment]
@xirong 我在 https://github.com/iissnan/hexo-theme-next/commit/e2cb7d8853dcbb438ee1d695f4be5c290347bb4e 这个提交中添加了 sidebar 的控制，应用的地方在 `layout.swig` 和 `post-details.swig`（搜索下 `HEXO_SIDEBAR_CONFIGURATION`）

**Comment by xirong** [comment]
@iissnan :+1:  ok ,搞定了 ~

**Comment by xirong** [comment]
@iissnan :+1:  ok ,搞定了 ~
