### ISSUE TITLE
一级目录无法跳转问题，求帮助啊

### ISSUE THREAD

**Issue by ChenAi007** [iissnan/hexo-theme-next#2240]
博客地址：bxhong.top

NexT版本：5.1.4

我F12看见说是

Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.<anonymous> (post-details.js?v=5.1.4:76)
    at HTMLAnchorElement.dispatch (index.js?v=2.1.3:3)
    at HTMLAnchorElement.r.handle (index.js?v=2.1.3:3)
(anonymous) @ post-details.js?v=5.1.4:76
dispatch @ index.js?v=2.1.3:3
r.handle @ index.js?v=2.1.3:3

在post-details.js上报错行为76行，源码：   var offset = $(targetSelector).offset().top;

**Comment by ChenAi007** [comment]
已解决，并已提出解决方案https://bxhong.top，可以直接在我博客看我的解决方案

**Comment by stevenjoezhang** [comment]
https://github.com/theme-next/hexo-theme-next/issues/1168#issuecomment-546791065

**Comment by f0rest9999** [comment]
@Ash1104 兄弟你的网站我进不去，能给个联系方式吗，遇到了和你一样的问题，已经困扰很久了，谢谢！

**Comment by Liquanhong123** [comment]
兄弟 我的一级目录用#也有问题，请问怎么解决的呢？？？我的邮箱1271826574@qq.com

**Comment by Liquanhong123** [comment]
> @Ash1104 兄弟你的网站我进不去，能给个联系方式吗，遇到了和你一样的问题，已经困扰很久了，谢谢！

兄弟 我的一级目录用#也有问题，请问怎么解决的呢？？？我的邮箱1271826574@qq.com
