### ISSUE TITLE
怎么控制布局？

### ISSUE THREAD

**Issue by MeiMeng** [iissnan/hexo-theme-next#225]
请问怎么控制布局？
比如说：写个html页面不让它自动加头尾，原样输出。
看不懂.swig文件的代码，木有学过呀😢
望大神指教！

**Comment by iissnan** [comment]
据我所知（可能过时），在 Hexo 里需要将这个 html 页面放置在 `主题的 source 目录` 下。

**Comment by MeiMeng** [comment]
Thank you,very much. 完美解决～
