### ISSUE TITLE
如何创建文章时候增加固定内容

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#227]
主题的内建样式 `<blockquote class="blockquote-center">blah blah blah</blockquote>` 我创建一篇文章时候已经可以自动弹出编辑器编辑，但是这部分样式内容却是每次都要手动输入，有什么方式可以自动创建的时候自动加上，有如 template 的概念一般

**Comment by iissnan** [comment]
有一种是通过 Hexo 的 [Tag-Plugin](http://hexo.io/docs/tag-plugins.html)，可以简便地添加这种 blockquote.

**Comment by mingmings** [comment]
@iissnan 看来即使借助了 tag-plugin ，貌似还是得手动输入一堆东西呢，OK，不过也简单多了，多谢多谢

**Comment by iissnan** [comment]
工具流可以考虑 TextExpander 或者 Alfred， 不知道 Alfred 能否定义这种快捷输入的宏

**Comment by mingmings** [comment]
@iissnan 我找到方式了，还是和之前一样，在 `scaffolds/post.md` 中加入字段即可，新建文章的时候就会被当做模板继承下来，如图
![image](https://cloud.githubusercontent.com/assets/3365500/8157243/b80a44c4-1385-11e5-93c0-f9e48cad19d0.png)
详情在我的博文中以前记录了，竟然给我自己忘了，╮(╯▽╰)╭
[hexo功能设置](http://mingmings.org/note/2014/hexo%E5%8A%9F%E8%83%BD%E8%AE%BE%E7%BD%AE/)

现在改成这样
![image](https://cloud.githubusercontent.com/assets/3365500/8157267/e103d0ca-1385-11e5-9309-ac254dfcfbb0.png)

这样每次 new 的时候就可以直接写文章了

**Comment by iissnan** [comment]
:+1: 不错的方法
