### ISSUE TITLE
_custom.styl打赏按钮开始不显示。

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#228]
source\css下新建了个_custom.styl打赏按钮开始不显示。但是二维码图片显示的。
是什么问题呢
post.swig
_layout.swig
_config.yml
都改好了。

**Comment by xirong** [comment]
这个 iissnan 的版本应该不支持的，没有 `merge` 进来，你可以手动添加 https://github.com/xirong/hexo-theme-next/commit/ff2f5330087e2af1d1bd280ead884b0e2a9b30fb ，也可以 fork我的版本就行merge就ok。还是那句，喜欢的用，不喜欢的就不用，个人兴趣。

**Comment by imcoddy** [comment]
其实个人觉得这个功能还是挺有必要的，希望能 merge 进来。
不过刚才看了一下 PR，似乎有文件冲突了，@xirong 先修正一下吧。

**Comment by vinyo** [comment]
@xirong xirong测试是有问题的。

**Comment by xirong** [comment]
@vinyo   xirong测试是有问题的。 这是什么意思？有什么问题？
