### ISSUE TITLE
博主导航页面不能加多说

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#229]
<div class="ds-thread" data-thread-key="/about"
     data-title="about" data-url="http://syscca.com/about/">
</div>
这样不能实现啊。

**Comment by xirong** [comment]
`博主导航页面不能加多说 `  什么意思？

**Comment by vinyo** [comment]
@xirong 页面

**Comment by araolin** [comment]
是这个吗？[让你的page页面也支持_多说_/_DISQUS_评论系统](http://www.arao.me/2015/hexo-next-theme-optimize-base/#让你的page页面也支持_多说_/_DISQUS_评论系统)
