### ISSUE TITLE
sidebar 第二次打开，内容消失

### ISSUE THREAD

**Issue by swwwan** [iissnan/hexo-theme-next#235]
第二次触发silebar,原有侧边栏的内容消失。debug html，发现sliebar关闭时将内容区display设置为none,第二次触发显示时没有重新设置dispaly的值。

![qq 20150620212705](https://cloud.githubusercontent.com/assets/3192152/8267419/9120b016-1793-11e5-9193-28e5b8d00bca.png)

![qq 20150620212637](https://cloud.githubusercontent.com/assets/3192152/8267425/ad4ab53e-1793-11e5-8cba-70d6927c879c.png)

**Comment by iissnan** [comment]
已修复，关闭此 issue。如果有问题请 repopen 或者贴一个新的 issue。
