### ISSUE TITLE
請問一下Markdown，中的table語法

### ISSUE THREAD

**Issue by LIYINGZHEN** [iissnan/hexo-theme-next#236]
我打了markdown的table

顯示

| Tables | Are | Cool | |:-------------:|:-------------:|:-----:| | col 3 is | right-aligned | 1600||col2is|centered|12 | | zebra stripes | are neat | $1 |

而不是

| Tables        | Are           |  Cool |
|:-------------:|:-------------:|:-----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      | $12   |
| zebra stripes | are neat      | $1    |
請問是目前沒有支援嗎?

**Comment by alim0x** [comment]
Markdown官方并没有提供表格语法，你的写法应该是额外的Markdown实现，建议直接插入html表格

**Comment by iissnan** [comment]
[GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#tables) 应该是支持的。

**Comment by xirong** [comment]
@LIYINGZHEN 这块实现的不大好，先手动插入 html 表格吧

**Comment by iissnan** [comment]
我发现格式稍微改下是可以的：

```md
| Tables | Are | Cool |
|:-------------:|:-------------:|:-----:|
| col 3 is | right-aligned | 1600|
|col2is|centered|12 |
| zebra stripes | are neat | $1 |
```

本地测试了下是可以正确的渲染成你期望的表示。

**Comment by chitanda** [comment]
发现默认的table没左右边框线， 某些极端情况下，**当表格内容长且都水平居中的时候**不太容易分清楚两列表格内容（不过我试着加了下边框线又发现好丑。），所以还是现在这样先吧= =。
例子：
```
| 链接 | 结果 | 原因 |
|:-------|:-----:|:-------|
|http:// **`www.example.com`** /dir/page2.html | **`是`** | 同协议同域名同端口 |
|http:// **`www.example.com`** /dir2/other.html | **`是`** | 同协议同域名同端口 |
|http://user:pwd@ **`www.example.com`**/dir2/other.html | **`是`** | 同协议同域名同端口 |
|http://www.example.com: **`81`**/dir/other.html|否|端口不同
| **`https`**://www.example.com/dir/other.html|否|协议不同端口不同|
|http:// **`en.example.com`**/dir/other.html|否|域名不同|
|http:// **`example.com`**/dir/other.html|否|域名不同（要求精确匹配）|
|http:// **`v2.www.example.com`**/dir/other.html|否|域名不同（要求精确匹配）|
|http://www.example.com: **`80`**/dir/other.html|视浏览器而定|取决于浏览器的实现方式|
```
主题下输出是这样的：（最后一行的显示略有问题）
![image](http://ww1.sinaimg.cn/large/8b59c960gw1etra6n0mi5j20lt0dwwi2.jpg)

github下输出：
> | 链接 | 结果 | 原因 |
|:-------|:-----:|:-------|
|http:// **`www.example.com`** /dir/page2.html | **`是`** | 同协议同域名同端口 |
|http:// **`www.example.com`** /dir2/other.html | **`是`** | 同协议同域名同端口 |
|http://user:pwd@ **`www.example.com`**/dir2/other.html | **`是`** | 同协议同域名同端口 |
|http://www.example.com: **`81`**/dir/other.html|否|端口不同
| **`https`**://www.example.com/dir/other.html|否|协议不同端口不同|
|http:// **`en.example.com`**/dir/other.html|否|域名不同|
|http:// **`example.com`**/dir/other.html|否|域名不同（要求精确匹配）|
|http:// **`v2.www.example.com`**/dir/other.html|否|域名不同（要求精确匹配）|
|http://www.example.com: **`80`**/dir/other.html|视浏览器而定|取决于浏览器的实现方式|

由于github的padding给的足，所以加了边框也不难看，不过代价是文本换行了。。个人来说还是喜欢不换行的多一点。不过希望**可以将隔行背景色不同这个css样式加进去**

另外想请教下，
```
http://www. **`badu`**com
```
这样写法的话,会输出：
> http://www. **`badu`**com

域名会被从中间截断掉，有办法取消这里的超链接自动转码么？（我本义只是想将链接里的`百度`加粗而已）

**Comment by iissnan** [comment]
@chitanda 表格的样式我更新下，添加少许的 padding 以及 striped row。

另外一个问题，Makrdown 貌似无解（可能我不知道），换 HTML 吧

**Comment by quxiaofeng** [comment]
@chitanda 你那个似乎可以试试直接 markdown 写链接

```
> [http://www.**baidu**.com](http://www.badu.com)
```

效果如下
> [http://www.**baidu**.com](http://www.badu.com)

**Comment by iissnan** [comment]
@quxiaofeng :+1:

**Comment by chitanda** [comment]
@quxiaofeng  非常感谢。虽然不是很想把这个不存在的链接做上超链接，不过为了美观，好像也没别的更好的办法了。

**Comment by mylittlestar** [comment]
有一个问题，假如表格中的内容比较多的话，就是一个格子写不下的时候，大家一般怎么解决这个问题的呢
