### ISSUE TITLE
Mist 主题部署到github后出现问题

### ISSUE THREAD

**Issue by UDvoid** [iissnan/hexo-theme-next#237]
在本地测试mist效果可用，但是部署到github后失效；
检查页面元素之后发现main.css不一样；
我把本地的css文件和github上的css替换，发现显示正常；

**Comment by iissnan** [comment]
本地 hexo clean 下，删除 .deploy_git 目录后再部署试试

**Comment by UDvoid** [comment]
THX，实测可行；
