### ISSUE TITLE
博主加上多说动感头像。

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#238]
http://wsgzao.github.io/post/duoshuo/

**Comment by eurusd** [comment]
简洁为好。

**Comment by xirong** [comment]
@vinyo  最好有开关，不喜欢就关闭，喜欢才打开。

**Comment by iissnan** [comment]
参照[这个](http://www.vsay.cn/one-more-custom-css-lets-you-say-comments-city.html)加到多说后台自定义css应该就可以了吧
