### ISSUE TITLE
有个疑问就是 右边侧边栏中 分类（在日志和标签中签的那个）不能点击

### ISSUE THREAD

**Issue by HelloKing** [iissnan/hexo-theme-next#240]
有个疑问就是 右边侧边栏中 分类（在日志和标签中签的那个）不能点击
原来设计就是这样的么，我看到你的博客也是这样的？

**Comment by iissnan** [comment]
没有使用分类，就没有链接。同样的，没有使用标签，也没有标签链接

**Comment by HelloKing** [comment]
恩 原来是我没启用 谢谢了 真得相当nice的主题...

**Comment by jerryling315** [comment]
@iissnan 在顶部没有启用 categories 和 tags 的情况下能否使得 sidebar 的链接可点. 比如我 menu 里有两个 categories 的链接我希望sidebar能点击进入所有 categories 的页面

**Comment by jerryling315** [comment]
## work around (而且还有一定的实用性 + 挺好看的)
![image](https://cloud.githubusercontent.com/assets/5306213/9401137/323b7686-47fd-11e5-8e81-8fd78217c698.png)`/next/_config.yml`![image](https://cloud.githubusercontent.com/assets/5306213/9401145/4b394d2a-47fd-11e5-8586-93b1f48136c1.png)`/next/languages/en.yml`
## 效果:
![image](https://cloud.githubusercontent.com/assets/5306213/9401151/6a096eb0-47fd-11e5-9bee-e4cce1ae5d06.png)
