### ISSUE TITLE
文章内容英文字母无法显示,代码能显示!

### ISSUE THREAD

**Issue by Dev-Wiki** [iissnan/hexo-theme-next#241]
![qq 20150624091826](https://cloud.githubusercontent.com/assets/12946956/8320883/8f7e84c4-1a52-11e5-99f9-a371362e259c.png)

如图所示,该如何解决?

**Comment by iissnan** [comment]
Lato 字体有问题，请自己替换下 https://github.com/iissnan/hexo-theme-next/issues/111

**Comment by Dev-Wiki** [comment]
已经修复,谢谢
