### ISSUE TITLE
next主题在ubuntu chrome 下渲染有问题

### ISSUE THREAD

**Issue by emacsist** [iissnan/hexo-theme-next#245]
就是 

```bash
xxxxxxx
```
类似这些代码块, 在ubuntu下的 chrome 浏览器渲染不正常, 无论多长,都会出现左右拉框, 而且比较短, 极难操作.

**Comment by alim0x** [comment]
查看作者首页文章的代码块没有问题，看了下你的博客，也没有问题
![screenshot from 2015-06-25 16 43 12](https://cloud.githubusercontent.com/assets/4954007/8350611/a1a926e2-1b59-11e5-9249-f8f4e4525098.png)
![screenshot from 2015-06-25 16 43 31](https://cloud.githubusercontent.com/assets/4954007/8350614/a7d92dd2-1b59-11e5-8e78-4a19a0b67ac1.png)

Ubuntu  Chrome 43

**Comment by emacsist** [comment]
![image](https://cloud.githubusercontent.com/assets/11989769/8350731/9f4c97d4-1b5a-11e5-8656-3c37784dad9f.png)

ubuntu chrome 43, 64 bit 
下显示这样子...

**Comment by alim0x** [comment]
![screenshot from 2015-06-25 18 07 43](https://cloud.githubusercontent.com/assets/4954007/8352088/23211792-1b65-11e5-8fc1-c716089e9029.png)

Ubuntu 15.04  Chrome 43 64bit 我这里表示正常...换个浏览器或者清除缓存试试？具体就不清楚了

**Comment by lulucici** [comment]
我碰到了一样的问题
Ubuntu15.04 Chrome 43.0.2357.130 (64-bit)43.0.2357.130 (64-bit)

**Comment by wmspectre** [comment]
我也有同样的问题

Ubuntu 14.04 Chrome 44.0.2403.89 (64-bit)

**Comment by tenlee2012** [comment]
**赞!!***

**Comment by geekrainy** [comment]
@emacsist @wmspectre @iissnan 一开始也有这样的问题，今天使用了这个脚本http://www.lulinux.com/archives/278。发现问题没有了。初步推测是ubuntu下字体渲染的问题。之前适当调整行高才能适应ubuntu默认渲染？:)

**Comment by iissnan** [comment]
按照 @wmspectre 的方案，`padding: 0` 更改成 `padding: 1px`。如果还存在问题，试试将 [codeblock](https://github.com/iissnan/hexo-theme-next/blob/master/source/css/_common/_vendor/highlight/highlight.styl#L12) 的 `line-height` 改大点。
