### ISSUE TITLE
微信内置浏览器网页被重排

### ISSUE THREAD

**Issue by iparanoid** [iissnan/hexo-theme-next#246]
经过测试
朋友圈分享
http://notes.iissnan.com/
可以正常打开
朋友圈分享
http://notes.iissnan.com/2015/angularjs-application-unit-testing-getting-stated/
则会提示 网页被重排

**Comment by iparanoid** [comment]
详细描述一下
设备 New Moto X
系统 Android 5.1
环境 微信 6.2

第一步 
扫描链接
http://notes.iissnan.com/2015/angularjs-application-unit-testing-getting-stated/
的二维码
如下图正常显示
![image](https://cloud.githubusercontent.com/assets/6026988/8357131/cfb3ffd0-1b8b-11e5-9a9d-2df57f4266bc.png)

第二步
将网页分享到朋友圈
![image](https://cloud.githubusercontent.com/assets/6026988/8357151/e9ec57b2-1b8b-11e5-85bf-2ac72590163a.png)

第三步
在朋友圈动态中 打开分享的链接
如下图
![image](https://cloud.githubusercontent.com/assets/6026988/8357167/01a3ff54-1b8c-11e5-92b9-5fd3d2dc8a33.png)

PS：同样的流程 在分享 http://notes.iissnan.com/时 没有任何问题
        只是在分享“文章页”时会出现被重排的现象
求解决方案 谢谢

**Comment by iissnan** [comment]
看样子是重排之后，动画没有被执行导致

**Comment by chitanda** [comment]
朋友圈的页面记得分享出去的域名如果没有用微信jssdk验证过的话，都会被强制转码的。。

**Comment by chitanda** [comment]
@iissnan  话说这个是微信的问题，不能算主题的bug。微信对于没有认证过的域名，分享到朋友圈全部会重新排版，js全部被屏蔽掉。另外我这边的测试来看， http://notes.iissnan.com /  这个域名也是被转码的，不知道@iparanoid 是怎么测试的
[转码后的链接](http://qbview.url.cn/getResourceInfo?appid=62&url=http%3A%2F%2Fnotes.iissnan.com%2F%3Ffrom%3Dtimeline%26isappinstalled%3D0%26nsukey%3Djgmdi1kEyGTdOAzI%252FpUmCtasProlDyvXeSSeDazG4gV8DgDywiRlDCpOpbziw70RFEV%252BQny%252Fy%252F11oF%252Frq%252ByR5g%253D%253D&openid=ooa-VuE9uiCQJ5R7Y81uYIEgmUsA&version=10000&doview=1&platformtype=700)（可以看到里面没一个js了）
要解决这个转码问题必须先要有个公共号╮(╯▽╰)╭
![怎样不被微信转码](http://ww4.sinaimg.cn/large/8b59c960gw1etktsazv92j20k00zk78n.jpg)

**Comment by iissnan** [comment]
@chitanda :+1:  多谢。或许我得考虑在没有 js 的情况下保证内容的可见性。

**Comment by iparanoid** [comment]
@chitanda 多谢测试 @iissnan 感谢回复
我这边亲自测试的是 http://notes.iissnan.com 在朋友圈没有任何问题
分享 “内容页”时 我自己手机是提示被转码
但身边朋友的手机 有的是正常显示 有的也是提示被转码
情况比较诡异
所以我一开始以为不完全是微信认证的问题

**Comment by chitanda** [comment]
@iissnan 哈哈，膜拜。noscript情况下反正我是写不来页面了。。
@iparanoid  啊，这个确实比较奇怪，但是可以肯定的是如果微信认证过的话，肯定不会被转码。所以如果真的有分享到朋友圈的需求，个人建议你还是弄个公共号比较好。（另外你可以看下正常显示的朋友有没有可能是微信版本的问题？低版本微信可能还没有分享的限制）

**Comment by iparanoid** [comment]
@chitanda  都是泪... 这个功能还必须是公司认证的那种公众号 才有 个人申请的还没域名业务功能 万恶的企鹅

**Comment by araolin** [comment]
我分享到朋友圈正常显示- -

**Comment by zhchbin** [comment]
目前我尝试的解决方式，关掉主题配置里的`use_motion`。

```yaml
# Motion
use_motion: false
```

配置说明
```
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
```

**Comment by Haocen** [comment]
微信这么设计应该是害怕 webkit 存在漏洞吧。
想来 Hexo 也不是专为微信公众号设计的，这个应该不算是一个 Bug 。

**Comment by ivan-nginx** [comment]
@iparanoid don't understand u, write in English if not solved. If solved, close it please. Thank's!
