### ISSUE TITLE
精简fancybox组件

### ISSUE THREAD

**Issue by flashlab** [iissnan/hexo-theme-next#247]
fancybox下似乎只有source文件夹是有用的，如果没有版权问题，其他诸如demo之类的文件是否可以删去呢？

**Comment by iissnan** [comment]
应该可以，我将这些文件排除在 版本控制之外就可以了。这样 Bower 还可以继续使用

**Comment by iissnan** [comment]
@flashlab 已经挪掉 没有在使用的 Fancybox 文件。请更新试试，有问题开 issue :smile:

**Comment by flashlab** [comment]
:+1:之前测试过，我这里没问题:ok_hand:
