### ISSUE TITLE
导航栏某些情况会消失[bug]

### ISSUE THREAD

**Issue by flashlab** [iissnan/hexo-theme-next#248]
在电脑上缩小浏览器宽度，直到出现折叠菜单，然后点开并关闭菜单，最后拉伸浏览器直到恢复PC样式的排版，这时导航按钮和搜索框都不能恢复了。目前只发现这一种情况下才会这样，也找不到原因 ;(
![-fs8](https://cloud.githubusercontent.com/assets/4102853/8369467/c037cf6c-1bec-11e5-844b-65b7a4b9ae07.png)

**Comment by iissnan** [comment]
已修复
