### ISSUE TITLE
Remove built-in Lato font

### ISSUE THREAD

**Issue by iissnan** [iissnan/hexo-theme-next#249]
There are many issues with built-in Lato font ( #135, #137, #164, #167, #187), so I decide to remove the built-in Lato font and replace it by using Google font API.

But Google font API has the connection issue in China, so I have to do some additional things for this case. If `language` is set to `zh-Hans`, NexT will not use Google font API. And there will be a new setting `use_lato_font`, to manually turn it on/off.

That is to say, Lato font will be:

1. off = `language: zh-Hans`  || `use_font_lato: false`
1. on = !off

**Comment by iissnan** [comment]
The default value of `use_font_lato` is `true`. So if you set `language` to something other than `zh-Hans` and you have problem with connection to Google Fonts API. You need to manually change `use_font_lato` to `false`.

**Comment by eurusd** [comment]
use_font_lato: false 
是解决手机浏览卡顿吗？

**Comment by eurusd** [comment]
好勤快的作者，超赞。

**Comment by iissnan** [comment]
@eurusd 去掉了 Lato 字体，加载速度应该会快一些。另外一个就是，在有些场景下，英文字体显示不了的问题。

**Comment by mingmings** [comment]
@iissnan 👍

**Comment by flashlab** [comment]
@iissnan 国内可以用http://libs.useso.com/提供的镜像
