### ISSUE TITLE
手机浏览文章，侧边栏太宽

### ISSUE THREAD

**Issue by sshuair** [iissnan/hexo-theme-next#25]
手机浏览文章时，侧边栏占据大量位置，手机：魅族MX3（手机自带浏览器），并且手机上侧边栏貌似无法关闭
![s50304-141122](https://cloud.githubusercontent.com/assets/5787131/6478996/a5b543ea-c278-11e4-817d-3aebefc8eb5b.jpg)

**Comment by Comee** [comment]
我也遇到这种情况，貌似当前版本（2015/3/6）还没解决

**Comment by iissnan** [comment]
还木有处理：）

**Comment by Comee** [comment]
恩恩  晓得了   感觉这个主题很棒， 
有以下几点建议：
1、访问主页面的时候，侧栏可以自动显示出来（注意：关闭、打开侧栏的按钮也要显示，发现手机屏就存在不显示 关闭、打开侧栏  的按钮这个问题）；
2、查看具体文章时，屏幕比较窄的时候（手机屏）不显示侧栏，（若想显示侧栏的话，关闭、打开侧栏的按钮也应该显示出来）。

**Comment by iissnan** [comment]
谢谢你的建议。

侧边栏应该会做成可配置是否自动展开。
手机设备上貌似存在挺多问题，我还没有花时间去测 :sweat_smile:

**Comment by Comee** [comment]
还是有问题，在宽屏的情况下打开侧栏，然后拖拽浏览器变窄，这时候关闭侧栏的图标就会消息，个人觉得不应该让关闭的图标消失；或者关闭侧栏的图标消失的时候，应该把侧栏自动关闭。

宽屏的时候打开侧栏：（有关闭侧栏的图标）
![qq 20150309093345](https://cloud.githubusercontent.com/assets/5416227/6548780/77d96ca6-c63f-11e4-9b90-f8401e57dd25.png)


拖拽变窄之后，关闭侧栏的图标消失
![default](https://cloud.githubusercontent.com/assets/5416227/6548784/88e2a13e-c63f-11e4-8f1e-c888c40ee7ca.PNG)

**Comment by iissnan** [comment]
:+1:

**Comment by iissnan** [comment]
Hi @Comee。 做了下调整，现在 Sidebar 的行为应该如以下表格：

      | Mobile (< 767px)  | Tablet (< 992px) | Desktop (<992px) | Desktop (> 992px)
------------ | ------------- | ------------- | ------------- | ------------- 
Sidebar    | x | x | x | √
Sidebar toggle | x | x | x | √
Back to top | x | x | x | √

**Comment by Comee** [comment]
基本修复了，如果消失的时候是渐变消失就更完美了

**Comment by iissnan** [comment]
谢谢反馈与测试。目前是使用 `media query` 硬性隐藏，应该可以改进成渐变的形式。
