### ISSUE TITLE
添加站点访问数量

### ISSUE THREAD

**Issue by smilexiamo** [iissnan/hexo-theme-next#251]
感谢作者开发这么精美的主题，请问能否考虑加入站点访问数量的功能呢？[配合这个脚本](http://service.ibruce.info/)

**Comment by alfredtofu** [comment]
@smilexiamo 本身百度统计已经支持查看站点访问数量，而且有很详细的分析。

**Comment by smilexiamo** [comment]
@alfredtofu 好吧，请问下您的博客主页和博客内容分别托管在github上是怎么做的呢？我也想尝试弄一下 。DNS解析这边应该怎么设置呢

**Comment by alfredtofu** [comment]
@smilexiamo 不是xxx.github.io的repository要用`gh-pages`这个分支来进行展示。详细可以看[官方文档](https://help.github.com/articles/user-organization-and-project-pages/#project-pages)，或者直接fork我的。

**Comment by smilexiamo** [comment]
谢谢您，我已经解决了
