### ISSUE TITLE
多说用户默认头像总是不显示！！

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#252]
大家有没有发现多说用户默认头像总是不显示？？

有人这样解决的，希望iissnan直接在主题上修改一下。

这是解决办法 http://cuiqingcai.com/1835.html

**Comment by eurusd** [comment]
我菜 不会弄。谁弄好教我一下。

**Comment by chitanda** [comment]
我正常啊。。多说默认头像在多说后台设置下就可以了吧。。

**Comment by chitanda** [comment]
特地又跑过去看了下，感觉可能是你那边CDN的问题，我这边是正常的。而且这个其实不好在主题里修改，因为每个人要的自定义头像都不一样，加上大部分人可能都是可以直接连看到多说那个默认头像文件的，单独把这个当参数拿出来改感觉意义不大

而且这个自己改不难：
先到`blog\themes\next\layout\_scripts\comments\`目录下按找到`duoshuo.swig`文件，然后从倒数第二行开始，就是在
```javascript
{% endif %}
```
的前面，把下面代码复制进去。
```javascript`
  <script>
   $(window).load(function(){
    $('.ds-avatar img[src*="cdncache"]').each(function(){
      $(this).attr("src",'http://ww1.sinaimg.cn/large/8b59c960gw1etkcowi9v2j201e01e3y9.jpg');
      console.log(1);
    })
  }); 
  </script>
```
这里图片链接我用了你现在设置的默认图片，直接用了新浪的图床。你可以自己换这个链接来替换图片（不过其实对于很多人来说你的头像应该都是正常的。）

**Comment by eurusd** [comment]
真心感谢。

**Comment by eurusd** [comment]
按你的方法 更改后  多说全不显示了

**Comment by chitanda** [comment]
你现在的页面是按照我和你说的那样子设置的么。我整个页面都没看到多说的代码啊

**Comment by iissnan** [comment]
@eurusd 我看 `ds.cdncache.org` 的解析很正常啊 （厦门联通，厦门电信）

**Comment by chitanda** [comment]
@iissnan  同样是南京电信，我昨天在家正常，今天在单位就斯巴达了。。多说这个头像的cdn确定相当不稳定。。

**Comment by chitanda** [comment]
@eurusd 你要不就直接全文替换，我怀疑你可能插错地方了。
把整个`duoshuo.swig`的内容换成下面的代码：
```
{% if (theme.duoshuo and theme.duoshuo.shortname) or theme.duoshuo_shortname %}

  {% if theme.duoshuo %}
    {% set duoshuo_shortname = theme.duoshuo.shortname %}
  {% else %}
    {% set duoshuo_shortname = theme.duoshuo_shortname %}
  {% endif %}

  <script type="text/javascript">
    var duoshuoQuery = {short_name:"{{duoshuo_shortname}}"};
    (function() {
      var ds = document.createElement('script');
      ds.type = 'text/javascript';ds.async = true;
      ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
      ds.charset = 'UTF-8';
      (document.getElementsByTagName('head')[0]
      || document.getElementsByTagName('body')[0]).appendChild(ds);
    })();
  </script>
  <script>
   $(window).load(function(){
    $('.ds-avatar img[src*="cdncache"]').each(function(){
      $(this).attr("src",'http://ww1.sinaimg.cn/large/8b59c960gw1etkcowi9v2j201e01e3y9.jpg');
      console.log(1);
    })
  }); 
  </script>
{% endif %}
```

**Comment by iissnan** [comment]
@chitanda 好像确实不太稳定。

我看了下，这个替换脚本可能会有问题，因为不单单是默认头像使用  `cdncache` ，自定义的头像也是走那个域名。也就是说，这个脚本会替换掉所有走这个域名的头像。所以可能会看到同一个页面多个拥有同样的头像但是名称不同的评论，感觉更乱。

**Comment by chitanda** [comment]
@iissnan 如果这样的话就无解了。。两种头像之前的地址并没有严格的区分出来吧。。看了下都是一个格式。。要么就都换掉了要么就不换（虽然我一直感觉多说大部分都是社交媒体登录的帐号的样子。）

**Comment by eurusd** [comment]
有办法吗？我现在整个多说多都挂了，别的城市的朋友可以看到多说了，我这里不显示多说。

**Comment by flashlab** [comment]
@eurusd 这类问题最好去多说官方反映，博客微博邮件都行。或者直接换disqus

**Comment by chitanda** [comment]
@eurusd  看上面，你直接把整个配置文件都换成我给你的代码，然后看下。你确定你没动过别的地方么。我怎么感觉你把多说关掉了。

**Comment by eurusd** [comment]
解决了 感谢你的热心帮助。
