### ISSUE TITLE
菜单是中文问题

### ISSUE THREAD

**Issue by dzhai** [iissnan/hexo-theme-next#254]
如果菜单设置成中文
menu:
  首页: /
  分类: /categories
  归档: /archives
  标签: /tags
  关于: /about
 
1. 导航菜单变成   menu.首页，menu.分类。。。
2. 右侧菜单上对应的分类、归档 链接失效

是不是我设置有问题？还是需要手动的修改模板？

**Comment by iissnan** [comment]
你的问题跟这个类似： https://github.com/iissnan/hexo-theme-next/issues/243

右侧菜单链接失败是指什么？

**Comment by dzhai** [comment]
解决了 原来是这样设置啊
Thanks
