### ISSUE TITLE
查看网站必须强制刷新

### ISSUE THREAD

**Issue by dorachenxx** [iissnan/hexo-theme-next#256]
如题，我发现每次我新建了一个post，然后第一次点进去这个post的时候什么都看不到，必须得强制刷新一次才能看。

**Comment by iissnan** [comment]
能否看下 JavaScript Console 有什么错误提示没有

**Comment by alfredtofu** [comment]
http://pan.baidu.com/s/1eQD8r42

@iissnan 你看看这个，看源代码是由内容的。

**Comment by iissnan** [comment]
@alfredtofu 这个页面有什么问题吗？ 内容我打开之后是可以看得见的

**Comment by alfredtofu** [comment]
@iissnan 我依旧遇到问题，我把刷新前跟刷新后的网页保存下来，http://pan.baidu.com/s/1qWPz2Ny 这里可以下载，前后网页的代码不太一样，不过我不知道区别是什么。

**Comment by iissnan** [comment]
@alfredtofu  去掉 Tinysou 以及 MathJax 的服务试试看有没有问题

**Comment by ivan-nginx** [comment]
@dorachenxx solved?
