### ISSUE TITLE
next修改展示：在next基础上添加了留言板，最近访客，图片延迟加载，文章阅读量等

### ISSUE THREAD

**Issue by araolin** [iissnan/hexo-theme-next#257]
如题，感谢这么精美的主题。
刚折腾[hexo](http://www.arao.me/)没多久，网站开了十多天，新站求罩。http://www.arao.me/

**Comment by iissnan** [comment]
:+1:  赞

**Comment by hanjilai** [comment]
靓啊

**Comment by mapan2020** [comment]
是不是我的网络问题，你的网站加载速度感觉很慢

**Comment by xiao-fang** [comment]
难道是我网络问题么, 你的网站加载速度超慢...

**Comment by AverageJoeWang** [comment]
加载真的好慢

**Comment by fenghanorg** [comment]
刚看了下，你网站第一次加载慢的原因应该是还在用 360 useso字体库吧。
<link href="//fonts.useso.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">

**Comment by zlmica** [comment]
等了好久

**Comment by weiyitai** [comment]
真的等了好久

**Comment by missyun** [comment]
网速太慢是硬伤啊，赶紧优化吧

**Comment by Xiankai-Wan** [comment]
实在是太慢了

**Comment by leafjame** [comment]
七夕接触hexo next主题后，一发不可收，捣鼓了好几天了，还在继续~
美化的自我感觉良好😁，就是还没绑定域名，同求罩：**_https://leafjame.github.io_**
