### ISSUE TITLE
#强烈建议#给head头部加防止百度转码代码

### ISSUE THREAD

**Issue by araolin** [iissnan/hexo-theme-next#258]
百度转码出发点是好的，帮网民快速打开网页。但是这样一来我们的主题什么的显示一团糟。
移动网络，手机百度结果，访问你的网站会被百度转码，例如手机百度[arao](http://www.arao.me/)进入我的网站，杯具就出现了。
![screenshot_2015-06-29-23-12-00](https://cloud.githubusercontent.com/assets/8462544/8411250/971094cc-1eb5-11e5-8b87-c62d78d6125b.png)
毁了一个好主题不说，居然还挂上了百度联盟广告。
解决方法：
找到head.swig，路径在`your-hexo-site\themes\next\layout\_partials`目录下，在`<meta charset="UTF-8"/>`下面添加两行代码
```
<meta http-equiv=”Cache-Control” content=”no-transform” />
<meta http-equiv=”Cache-Control” content=”no-siteapp” />
```
添加完后没那么快被取消转码，大约3~5个小时左右百度会取消转码(百度官方声明为5天)，请耐心等待生效。

**Comment by chitanda** [comment]
为啥我百度blog进去就没有。。

**Comment by araolin** [comment]
好神奇的说，我手机百度了“主题 - NexT.Mist”，有一些会有一些没有，不过加上那两行代码稳妥点吧

**Comment by araolin** [comment]
@iissnan 前面给的代码有误，导致我禁止百度转码没成功，引号应该全部是英文半角引号。准确代码如下：
```
<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
```

**Comment by iissnan** [comment]
@araolin 多谢提醒，我使用的是英文半角引号。
