### ISSUE TITLE
无法在详情页使用多说评论

### ISSUE THREAD

**Issue by zhenn** [iissnan/hexo-theme-next#259]
在站点的config中，配置duoshuo_shortname: 6961706a24417bd4d2c348fbd18a996b，无法启动评论组件，看了你的文档，不太明白shortname是神马？请指教

**Comment by araolin** [comment]
@zhenn 例如我的araolin.duoshuo.com，shortname就是araolin

**Comment by zhenn** [comment]
@araolin , 已经ok，谢谢。不过建议对shortname做一些说明，应该很多人不太明白这个字段的含义。

**Comment by iissnan** [comment]
@zhenn  多说 shortname 貌似也是常见的问题。文档正在完善中，在 [Wiki - 设置多说 和 DISQUS](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%B4-DISQUS#%E4%BD%BF%E7%94%A8%E5%A4%9A%E8%AF%B4) 有提到。

或许后续加上配图会更容易理解。
