### ISSUE TITLE
是否支持显示categories

### ISSUE THREAD

**Issue by ianwith** [iissnan/hexo-theme-next#26]
没有找到categories在哪里配置

**Comment by iissnan** [comment]
目前还不支持，在下个版本将会支持。

**Comment by ianwith** [comment]
好啊，期待～

**Comment by sabrinaluo** [comment]
+10086
我也想要categories功能

**Comment by iissnan** [comment]
Will be implemented in 0.4.0
Please see: https://github.com/iissnan/hexo-theme-next/wiki/Changelog#release-040

**Comment by mingmings** [comment]
hi，用了你的主题，本想从你这里直接开始学习nodejs，但是看了下你的源文件都是swig结尾的格式，搜了搜，貌似没太看明白呢

**Comment by iissnan** [comment]
这是一个前端的项目，不适合于学习 nodejs。

**Comment by baininghan** [comment]
@iissnan 我也想了解swig结尾的格式，有没有学习的链接。

**Comment by ianwith** [comment]
@baininghan [Swig](http://paularmstrong.github.io/swig/) 这个是否是你要的～

**Comment by baininghan** [comment]
@ianwith 贊~

**Comment by iissnan** [comment]
已支持 categories。

**Comment by mingmings** [comment]
@iissnan 我今天无意 `pull` 发觉更新 4.0 tag 了

**Comment by iissnan** [comment]
嗯...本来打算把其他的几个功能一起做掉再 release，估计时间会比较久，干脆就先 release 其中的大头，其他再迭代 :smile: 。就是更新会比较频繁。

`0.4.0` 主要是一个新的紧凑版本 :smile:

**Comment by mingmings** [comment]
@iissnan 给力给力，我中间好几天都 `pull` 玩玩，结果都更新了好几次，辛苦。的确现在分类虽然不一定那么完美，但是至少支持了，后面就更加期待了，啊哈哈哈
