### ISSUE TITLE
貌似多说的分享样式坏了。

### ISSUE THREAD

**Issue by keeleys** [iissnan/hexo-theme-next#260]
貌似多说的分享样式坏了。

**Comment by eurusd** [comment]
是的 多说总这样。
多说分享更不稳定，还不如百度分享呢。

**Comment by iissnan** [comment]
似乎多说的服务有许多问题。可以试试 JiaThis 或者 百度分享，NexT 都支持。

**Comment by iissnan** [comment]
对了，使用多说分享目前来说必须同时使用多说评论，因为分享的样式是在多说评论里面
