### ISSUE TITLE
bug：侧栏目录在第二次打开时会自动消失

### ISSUE THREAD

**Issue by smilexiamo** [iissnan/hexo-theme-next#261]
更新到最新版本的next主题之后，文章自动生成的侧栏目录在点击一次之后再次展开目录将会消失。

**Comment by iissnan** [comment]
多谢反馈。可能跟 https://github.com/iissnan/hexo-theme-next/issues/235 是同一个问题

**Comment by iissnan** [comment]
奇怪，我在最新的 NexT 版本上没法重现这个 bug。能提供下你的重现步骤吗？ @smilexiamo

**Comment by smilexiamo** [comment]
@iissnan 刚升级NexT，测试了下还是会有这个bug。具体操作步骤为：`找到一篇带有目录的文章`--->`展开侧栏`----->`任意点击一个目录索引`------->`关闭侧栏`------>`再展开侧栏`-------->`目录不再显示`

**Comment by iissnan** [comment]
@smilexiamo OK，可以重现，我现在修复。多谢

**Comment by smilexiamo** [comment]
@iissnan 感谢作者提供这么精美的主题！

**Comment by iissnan** [comment]
@smilexiamo 已修复。请更新，`themes\next\_config.yml` 可能会冲突，请先备份。

**Comment by smilexiamo** [comment]
@iissnan 十分感谢！
