### ISSUE TITLE
[BUG]Toc的行为很奇怪

### ISSUE THREAD

**Issue by Xuanwo** [iissnan/hexo-theme-next#262]
文章地址为：http://xuanwo.org/2014/06/05/sublime-text-3-IDE/
源代码地址为：https://github.com/Xuanwo/xuanwo.github.io/blob/blog/source/_posts/sublime-text-3-IDE.md

见图：
![image](https://cloud.githubusercontent.com/assets/5351546/8434060/d0c9820c-1f7b-11e5-8010-5c3d1f0408e8.png)

**Comment by Xuanwo** [comment]
我猜测问题出在那个`2.0.x`上面，我修改为二级标题试试看

**Comment by iissnan** [comment]
嗯，我发现这个问题挺频繁出现的。NexT 内部是调用了 Hexo 的 [toc helper](https://hexo.io/docs/helpers.html#toc)，我在想这个问题是 Markdown 解析过程的有问题，还是 toc helper 有问题。

从 [toc 的测试脚本](https://github.com/hexojs/hexo/blob/master/test/scripts/helpers/toc.js)来看 toc helper 应该是没有问题。

**Comment by iissnan** [comment]
这个问题我记得 @mingmings 碰到过。

**Comment by Xuanwo** [comment]
从控制变量的角度来考虑，唯一的不同就在于我的`2.安装`下直接跳过了二级标题，直接开始了三级标题。
通过查看源代码可以看出，从`3.changelog`开始就是`<li>`了.

**Comment by iissnan** [comment]
是的，HTML 结构出现了问题，跟随着样式匹配上也出问题。

**Comment by Xuanwo** [comment]
@iissnan 将三级标题修改为二级标题后，已经修复了。

不过我还是不确定这到底是算BUG，还是算用户的非常规行为= =

**Comment by mingmings** [comment]
@iissnan  @Xuanwo 这个问题我没法从代码角度解决，所以采用了更改 markdown toc 方式解决，我的文章现在的结构是这样的

```
## 一、
### 1.1 
### 1.2

## 二、
### 2.1
```

中间不要插入任何其他的 标题结构了，如果中间插入一个 `####` 四级标题，可能都会引起结构解析混乱，我这个算是不是解决办法的办法

**Comment by Xuanwo** [comment]
是的，我目前的结论是标题结构不能跳跃。
```
## 一、
### 1.1 
### 1.2

## 二、
### 2.1
```
这样是没有问题的，但是
```
# 一、
### 1.1 
### 1.2

# 二、
### 2.1
```
这样就会导致解析错误。

其实也还好，毕竟标题等级跨越本来就是一种很奇怪的行为

**Comment by mingmings** [comment]
@Xuanwo 我个人认为，从 `#` 一级标题跨越到 `###` 三级标题就会出现问题，如果是从二级标题啧不会，所以为了避免出现这种情况，尽量避免跨级标题吧，或许可以尝试

```
## 一、
### 1.1 
#### 1.1.1 
```
这种方式，我觉得这样可能可行

**Comment by flashlab** [comment]
可以看看别的主题是不是也有这个问题。比如[jacman](https://github.com/wuchong/jacman)

**Comment by returnyuteng** [comment]
遇到了同样的问题，没想到一年了这个问题还没有修复

**Comment by Wangjunyu** [comment]
@returnyuteng 这个并不复杂，只要不越级就没有问题。

**Comment by Xuanwo** [comment]
Closed for wontfix

**Comment by viryyew** [comment]
四年过去了，问题依旧存在……搜了一圈搜到这个 issue 才知道是啥原因……

**Comment by stevenjoezhang** [comment]
@viryyew 这个与NexT无关。ToC是Hexo生成的，并且这个bug仅在Markdown本身存在目录问题时出现。
