### ISSUE TITLE
首页显示untitled

### ISSUE THREAD

**Issue by liyuguo** [iissnan/hexo-theme-next#264]
只修改了配置中的 theme: hexo-theme-next 。
其他未动，通过路径可以看到发布的文章，但主页显示如下：
https://imgur.com/fvrdTH9
看了wiki，没找到怎么修改。

**Comment by iissnan** [comment]
@liyuguo 方便贴你的文章的内容？ 只要前面部分即可

**Comment by xirong** [comment]
@liyuguo  看看你文章是怎么写的，理论上应该如下：
``` html
title: "test-write"
date: 2015-07-08 22:59:09
tags:
- test
- 标签内容
categories:
- 目录名字
description: 
---

这是测试文章
```

另外，config.xml 中的配置主题的地方应该是：
``` xml
theme: next
```

**Comment by liyuguo** [comment]
文章应该没什么问题，我把主题切换到 light 或者 landscape 都是显示正常的
原因可能是：$ hexo generate 没有编译成功
我更新 next 主题后继续编译，报错。https://imgur.com/HGUMSsU
之前不了解切换主题时最好使用一下hexo clean 否则容易出错

**Comment by iissnan** [comment]
升级下 Hexo 试试。Hexo 2.7.1 我没有测试过 :smile:
