### ISSUE TITLE
more标签和水平分割线相遇

### ISSUE THREAD

**Issue by adushui** [iissnan/hexo-theme-next#272]
more标签和水平分割线相遇时，如果偷懒，\------前不空一行，例如：
\
\------
会导致“阅读全文”样式走形：
![](http://ww4.sinaimg.cn/large/71194c49gw1etxxobg7wpj204c01a0sj.jpg)

如果\------空一行，
\

\------
![](http://ww4.sinaimg.cn/small/71194c49gw1etxxqi9cq2j203k01ka9v.jpg)

**Comment by iissnan** [comment]
已修正。另外，最好还是保留空行。不保留空行，在 Markdown 里意味这是标题，而非水平分割线。
