### ISSUE TITLE
主题里面没有 Tabs 标签页的样式？

### ISSUE THREAD

**Issue by imcoddy** [iissnan/hexo-theme-next#274]
想在这主题上用 tab 标签页实现一些效果，不过看了一下主题里面的 css 似乎是没有这个功能。
现在这个主题的 css 里面能否像 bootstrap 那样实现标签的效果呢？

http://getbootstrap.com/javascript/#tabs

**Comment by zou-mono** [comment]
建议增加bootstrap，现有的label颜色有些单调

**Comment by ivan-nginx** [comment]
Added in #1697 (PART 7. Add tabs tag.).
