### ISSUE TITLE
在文章里添加图片，怎么控制图片的大小？

### ISSUE THREAD

**Issue by midiao** [iissnan/hexo-theme-next#277]
还有一个问题就是，怎么指定一页里的文章数，我现在所有文章都在一个页面里，没有分页。

**Comment by araolin** [comment]
@midiao 文章分页在站点配置文件_config.yml那里，我设置4篇文章一页
```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 4
pagination_dir: page
```

**Comment by iissnan** [comment]
图片可以使用 Hexo 的 [Image Tag](https://hexo.io/docs/tag-plugins.html#Image)

**Comment by linarz** [comment]
@iissnan关于您博客里面最前面的图片“group-picture-test”是如何发布的？

**Comment by iissnan** [comment]
@linarz 这个功能还在开发中，使用方式会再次调整，所以暂时还没发布。
