### ISSUE TITLE
多说评论加载速度慢，不稳定的解决方法

### ISSUE THREAD

**Issue by araolin** [iissnan/hexo-theme-next#278]
1.多说css文件头部加载，js文件底部加载
2.利用七牛镜像存储镜像多说static.duoshuo.com网站，实现多说静态文件`embed.js`和`embed.xxx.css`CDN加速，然后我们网站请求的是我们自己七牛空间的CDN加速后的多说静态文件，实现多说核心js和css加速载入，减少多说服务器负担。
具体实现可以参考[多说评论不稳定，加载速度慢优化方法](http://www.arao.me/2015/make-duoshuo-faster-qiniu-cdn/)
优化结果，经百度站长平台网站速度诊断工具测试，多说核心脚本`embed.js`加载至少减少1秒多，具体效果可以测试我的网站[ARAO'S BLOG](http://www.arao.me/)

**Comment by RuiqiangJiao** [comment]
你好,参照你的博客,在hexo\themes\next\layout\_scripts\third-party\comments中修改了(document.getElementById('footer'),之前评论区数学公式无法显示,有解决办法吗?附地址:http://ruiqiangjiao.github.io/2016/02/26/MathJax-With-Hexo/#more
