### ISSUE TITLE
如何在 Markdown 文件里面调用主题内置样式？

### ISSUE THREAD

**Issue by imcoddy** [iissnan/hexo-theme-next#280]
虽然在说明的页面里面有这样的介绍，不过不知道在写博客的时候，如何在 Markdown 文件里面加入如下的样式呢？
比如说，如果我想要首页图片自动缩放到页面宽度大小，需要怎么在文件里面加下面的 full-image 类呢？

## 主题内建样式

`.blockquote-center`

> 带上下分割线的引用，引用内文本将自动居中。适用于单行引用文本的场景。

### 示例

![Blockquote Center](http://iissnan.com/nexus/next/blockquote-center.png)

### 使用方式：

```html
<blockquote class="blockquote-center">blah blah blah</blockquote>
```

`.full-image`

> 图片将自动扩展 26%，突破文章宽度。

### 示例

![Full Image](http://iissnan.com/nexus/next/full-image.png)

### 使用方式：

```html
<img src="/image-url" class="full-image" />
```

**Comment by iissnan** [comment]
可以在 Markdown 里直接写 HTML 代码。

**Comment by imcoddy** [comment]
果然还是要直接写 HTML 代码呀……好的明白了，Markdown 不支持调用 css class 不知是好是坏 :P

**Comment by iissnan** [comment]
考虑将其做成 Hexo 的 [Tag Plugins](https://hexo.io/docs/tag-plugins.html)  以方便调用。

**Comment by imcoddy** [comment]
嗯，这个想法很不错。这样在使用方面也会感觉统一一些，而且兼容性也会好一点：）

**Comment by anson2416** [comment]
请问怎样修改blockquote-center里面的 超链接 默认样式？
