### ISSUE TITLE
文章页面显示两个多说评论？

### ISSUE THREAD

**Issue by realzsy** [iissnan/hexo-theme-next#281]
首先，非常喜欢这款主题，谢谢作者的无私分享。

安装完成后，打开页面居然出现两个多说，我打开作者的博客发现居然也是两个，是bug吗？或者如何解决？

![2015-07-13_215606](https://cloud.githubusercontent.com/assets/2454959/8651204/23b2793c-29aa-11e5-8166-3c05fbfa8625.png)
![2015-07-13_215627](https://cloud.githubusercontent.com/assets/2454959/8651205/23de476a-29aa-11e5-9023-177f65c81e01.png)

**Comment by iissnan** [comment]
多谢反馈，已修复，请更新一下

**Comment by realzsy** [comment]
我做了更新以后，还是两个？

**Comment by iissnan** [comment]
看下 `themes/next/layout/post.swig` 这个文件是否更新了，`{% if page.comments %}...{% endif %}` 应该被删掉了。

然后执行下 `hexo clean`，再 `hexo s --debug` 一下看看有没有问题

**Comment by realzsy** [comment]
{% if page.comments %}
      <div class="comments" id="comments" itemscope itemtype="http://schema.org/UserComments">
        {% if (config.duoshuo and config.duoshuo.shortname) or config.duoshuo_shortname %}
          <div class="ds-thread" data-thread-key="{{ page.path }}"
               data-title="{{ page.title }}" data-url="{{ page.permalink }}">
          </div>
        {% elseif config.disqus_shortname %}
          <div id="disqus_thread">
            <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
          </div>
        {% endif %}
      </div>
    {% endif %}
  </div>

这段代码还在，文件还是昨天的时间，应该是没有更新成功。
更新不是在next文件夹git pull吗？我执行命令以后，也提示了post.swig,怎么会没有更新成功呢？

**Comment by iissnan** [comment]
是在 next 文件夹内执行 `git pull`，可能是冲突导致没有更新成功。方便的话，粘贴下 git pull 命令后的输出。

另外一种方式是备份 next 文件夹下的 `_config.yml` 文件，然后将 next 文件夹删除掉，重新 `git clone` 一份。（如果有更改过 next 文件夹下的其他文件也记得备份）

**Comment by realzsy** [comment]
@iissnan 好的，我已经手动更新了这个文件，谢谢了。

**Comment by Hunter-Zack** [comment]
底部出现一个宽的有言评论框是怎么回事？
