### ISSUE TITLE
当 `photos` 中只有一张图片时，是不是应该把图片当作 `banner` 显示？

### ISSUE THREAD

**Issue by quxiaofeng** [iissnan/hexo-theme-next#282]
```
如果 post.photos.length == 1
    把 post.photos[1]  当作 banner 显示
结束//如果
```

现在的方式是不论 `photos.length == anything`, CSS 中的设置都是 `25% width`。如果要求根据数量自适应比较难办，至少可以做到一张图片的时候显示为 `100% width` 的 `banner` 吧？

远景看应该是:

```
switch(post.photos.length) {
    case 1:
        显示 post.photos[1] 为 banner ( 100% width)
        break;
    case 2:
        并排显示 post.photos (50% width)
        break;
    case 3:
        三列显示 post.photos (33% width)
        break;
    default: // >=4
        现有显示方式
}
```

**Comment by iissnan** [comment]
这个 idea 不错

**Comment by iissnan** [comment]
Master 分支上的版本（`0.4.5.1`）已包含此需求。

当 `photos` 

1. 仅包含 1张 图片时，将按照图片的原始大小显示
2. 包含 2张 图片时，将以图片的 50% 大小并排显示
3. 包含 3张 图片时，将以图片的 33% 大小并排显示
4. 包含 4张 以上的图片时，一列满 3张 时换行，以图片的 33% 大小显示

**Comment by quxiaofeng** [comment]
Well done, thanks.
