### ISSUE TITLE
Update styles of tables

### ISSUE THREAD

**Issue by iissnan** [iissnan/hexo-theme-next#287]
Update styles of tables. [reference](https://github.com/iissnan/hexo-theme-next/issues/236#issuecomment-118538781)

- Striped rows
- Highlight row when hovering
- Padding for table cells
- Border of tables and cells 
- Decrease font size of tables
- Add variables for re-scheme

---

表格样式将更新，[参考](https://github.com/iissnan/hexo-theme-next/issues/236#issuecomment-118538781)

- 增加条纹式表格行
- 增加鼠标滑过高亮所在行
- 增加单元格内边距
- 增加表格与单元格边框
- 减少表格字体大小
- 抽取表格相关变量以便 re-scheme

**Comment by chitanda** [comment]
感谢更新。这几天没多少时间折腾blog，待我过两天更新了给个反馈o(∩_∩)o

**Comment by chitanda** [comment]
看了下目前还是0.4.4版本，这个是TODO？

**Comment by iissnan** [comment]
在 dev 分支上 https://github.com/iissnan/hexo-theme-next/commit/c9fff9cbf35abee5ac73730d7e7ca3de93879103。

**Comment by iissnan** [comment]
Master 分支已包含 table 样式的修改。
