### ISSUE TITLE
Fancy box bug

### ISSUE THREAD

**Issue by CookieJaySJ** [iissnan/hexo-theme-next#29]
使用fancy box图片会被压缩成条状，两边黑框严重=_=

**Comment by iissnan** [comment]
可以提供你的文章地址吗？

**Comment by CookieJaySJ** [comment]
http://iicookie.com/2015/03/06/test/

黑边明显

**Comment by iissnan** [comment]
去掉了黑色底色。Gallery 需要一个新的设计，现在有点草。
