### ISSUE TITLE
localhost:4000 显示 Mist 主题但远端不显示

### ISSUE THREAD

**Issue by Dynamicer** [iissnan/hexo-theme-next#290]
`localhost:4000` 中可以显示 Mist 主题，远端 `_config.yml` 中确定取消了注释，重装 hexo 数次仍然不显示 `Mist` 主题......

应该不是本地缓存问题， http://dynamicer.com 。

**Comment by chitanda** [comment]
看你部署在哪。有可能是云空间服务提供商的问题，页面缓存时间比较长或者部署页面进入排队导致没有即时部署你的页面。

另外也可以先`hexo clean`下再部署试试看

**Comment by Dynamicer** [comment]
`hexo clean && hexo g` 确实有效~

**Comment by Dynamicer** [comment]
@chitanda 那么换言之是不是说下次遇到此类情况，实则可能明天或许就自己恢复了？

**Comment by chitanda** [comment]
clean掉再部署正常的话那就说明不是服务商的问题，而是hexo的问题。。hexo 3.1.1的话好像可以用`hexo d -fg`来强制重新编译生成的内容。

**Comment by GerrieWell** [comment]
有用. mark.
