### ISSUE TITLE
Mist主题中 搜索的位置变动了

### ISSUE THREAD

**Issue by ranhere** [iissnan/hexo-theme-next#291]
本来的布局都还好好的，但是后来可能调了一下什么，就错位了。
直接上图 哎呀图上不去
http://img-storage.qiniudn.com/15-7-17/61349650.jpg)

求能改回去的方法

**Comment by haskio** [comment]
有同样的问题 。
不过我的是搜索框跑到左边去了。挨着title。。

看log 是字体么有。。
fonts/lato/Lato-Bold.woff Failed to load resource: the server responded with a status of 404 (Not Found)

http://izen.tk/fonts/lato/Lato-Bold.ttf Failed to load resource: the server responded with a status of 404 (Not Found)


我的地址：
http://izen.tk/

**Comment by iissnan** [comment]
@haskio 你的 Swiftype 最后一步激活没有做。

> {"error":"Install is not activated. Activate install at https://swiftype.com/engines/haskio-dot-github-dot-io/install_flow/start"}

**Comment by iissnan** [comment]
@ranhere 检查下 模板里 `<div class="site-search">` 后面是否有多余的空白字符。

**Comment by ranhere** [comment]
@iissnan 好像没有.....
`
    <div class="site-search">
      
  ﻿
<form class="site-search-form">
  <input type="text" id="st-search-input" class="st-search-input st-default-search-input" />
</form>
<script type="text/javascript">
  (function(w,d,t,u,n,s,e){w['SwiftypeObject']=n;w[n]=w[n]||function(){
    (w[n].q=w[n].q||[]).push(arguments);};s=d.createElement(t);
    e=d.getElementsByTagName(t)[0];s.async=1;s.src=u;e.parentNode.insertBefore(s,e);
  })(window,document,'script','//s.swiftypecdn.com/install/v2/st.js','_st');
  _st('install', 'JQUbQVCiyitVcNWJvb88','2.0.0');
</script>


<div class="site-search-toggle"></div>
    </div>
`

**Comment by ranhere** [comment]
@iissnan 诶我把Swiftype.swig ·</script>` 后面删去一行空行后，就变正常了 XD

**Comment by haskio** [comment]
@iissnan  把搜索id 去了， 问题依旧。。

ps：本地没这个问题。 奇怪了。
