### ISSUE TITLE
页面的href不正确

### ISSUE THREAD

**Issue by zhourongyu** [iissnan/hexo-theme-next#292]
root: /
    permalink: :year/:month/:day/:title/
但页面上得 href 却是 2015/07/16/index.html 这样的url。是哪里的配置不对么？

**Comment by iissnan** [comment]
有修改过站点/主题的配置吗？

**Comment by zhourongyu** [comment]
找到问题了，relative_link: false  改成true就不对了~

**Comment by iissnan** [comment]
That's cool.
