### ISSUE TITLE
文章中部分代码没有行号

### ISSUE THREAD

**Issue by Dynamicer** [iissnan/hexo-theme-next#293]
[http://dynamicer.com/how-to-deploy-hexo-blogs-with-git-hooks-on-vps/](http://dynamicer.com/how-to-deploy-hexo-blogs-with-git-hooks-on-vps/)

很奇怪的，前一半有，后一半没有，全文中的多行代码的标注都一样，都是：

\`\`\` bash
\`\`\`

**Comment by ihappyhacking** [comment]
我这么写都是有行号的：
```
code
```

**Comment by iissnan** [comment]
我所知道的没有行号的写法是用 缩进的形式，但用 GFM 的codeblock 应该都有行号

**Comment by ihappyhacking** [comment]
写在上下两行每行三个`里面的代码都是有行号的
