### ISSUE TITLE
为什么对很多md格式都不支持？

### ISSUE THREAD

**Issue by wongkoo** [iissnan/hexo-theme-next#297]
比如引用注释 、序列图

**Comment by zhangpj** [comment]
hexo默认使用的renderer是这个[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)，支持[GFM](https://help.github.com/articles/github-flavored-markdown/)。
要用引用注释的话试下这个[hexo-renderer-pandoc](https://github.com/wzpan/hexo-renderer-pandoc)。
