### ISSUE TITLE
关于404页面

### ISSUE THREAD

**Issue by phenfun** [iissnan/hexo-theme-next#298]
按照配置说明，新建 404.html 文件，放在主题 next 的 source 文件夹根目录下，配置文件 _config.yml 中
信息如下：
![image](https://cloud.githubusercontent.com/assets/12717698/8870950/73e658f6-3224-11e5-9c4c-4e45b8dd8765.png)
点击博客中的 公益 404 跳转源码，如图：
![image](https://cloud.githubusercontent.com/assets/12717698/8870983/a029c4fc-3224-11e5-8147-0968a2537227.png)
求助，谢谢！

**Comment by chitanda** [comment]
生成的这个404.html有问题，这个就是他渲染后的结果，并不是所谓的源代码方式。比较好奇你的编辑器。
把你source目录下的404文件的源代码贴上来看看。

**Comment by phenfun** [comment]
@chitanda 我就是按照 https://github.com/xirong/hexo-theme-next/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%A2%9E%E5%8A%A0%E8%85%BE%E8%AE%AF%E5%85%AC%E7%9B%8A404%E9%A1%B5%E9%9D%A2 这个教程弄的，源代码也是这页面上提供的代码，然后我在osx里面直接用默认的文本编辑保存的

**Comment by chitanda** [comment]
其实我是担心你复制代码的拷贝多了东西，用的不是你把source下的404页面截图或者贴代码上来都可以，没用过osx不清楚，但是window下很多富文本编辑器会自作多情把网页上的样式也复制到编辑器中去，所以我不能确定你复制下来的一定就是正确的404页面代码。。

**Comment by phenfun** [comment]
嗯，其实吧，不加这个404功能也可以，既然出现问题，我就想知道原因。我尝试手动一行一行复制吧。还想请教下，配置文件中的 subtitle 有什么作用，我查看生成博客后，网页的源码，可是没有找到与 subtitle 有关联的地方。
![image](https://cloud.githubusercontent.com/assets/12717698/8875226/2a6706d2-324a-11e5-87bd-e1168fd05212.png)

**Comment by chitanda** [comment]
这个是子标题。不过我也不知道有啥用。反正没体现在next主题下。。
我建议你直接把
https://gist.githubusercontent.com/chitanda/cb71043ce14d2558a628/raw/a70083052027cb1e4546f585c69fc43bd522e0f6/404.html
这里的文件另存为下来，然后覆盖你主题source文件夹下的404（其实直接扔在blog下的source文件夹也一样

**Comment by phenfun** [comment]
@chitanda 谢谢你能跟进这个问题。按照你的方法，已经成功，我终于发现了问题所在：从教程页面复制代码到 404.html 的时候，内容已经带有源代码的样式，这样保存后的文件，打开是没有任何效果的，只能显示为代码的样式。现在我又发现了一个新的问题：回到我的主页，这个功能不好使，因为无论参数 homePageUrl 的值是什么，链接的地址都会追加字符串 /"homePageUrl的值" 在博客地址的后面。比如 homePageUrl="www.rt4j.com"，鼠标移到回到我的主页链接上，浏览器左下角状态栏会显示 www.rt4j.com/"www.rt4j.com"；如果 homePageUrl=""，链接则为 www.rt4j.com/""；如果参数  homePageUrl 的等号后面什么都不写，在 Mou 编辑器的预览显示效果 返回腾迅网，但其实链接地址变为了 homePageName="回到我的主页"，如下图：
![image](https://cloud.githubusercontent.com/assets/12717698/8878890/4d851a26-3260-11e5-8831-80d96ec30b56.png)
如果直接点，把 homePageUrl 参数去掉，虽然显示为 回到我的主页，但实际点击链接跳转到 www.qq.com 。真心弄不好了-_-#

**Comment by chitanda** [comment]
所以前面就说了很有可能是你编辑器的问题。之所以让你发源代码就是为了确认而已。
看样子你也不是专门的开发人员吧。。这个主题好像还挺受大众欢迎的貌似。。

至于回到主页那个问题，
把`“http://www.rt4j.com”`改成`"http://www.rt4j.com"`即可。
我前面的404页面直接复制的你的代码，没注意检查。你这里的连接的双引号是中文符号

**Comment by phenfun** [comment]
@chitanda 现已解决问题：修改 homePageUrl="index.html" ，然后就进入首页了。大神说的 referer 好像一般用于防盗链吧。感谢一直跟进与支持，谢谢！

**Comment by chitanda** [comment]
你去查下绝对路径和相对的区别就知道问题出在哪了。。。或者把你自己最开始的url和我后来给你那个404页面的url比对下就知道了。

**Comment by phenfun** [comment]
@chitanda 我确定 从 https://github.com/xirong/hexo-theme-next/wiki/%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87%E5%A2%9E%E5%8A%A0%E8%85%BE%E8%AE%AF%E5%85%AC%E7%9B%8A404%E9%A1%B5%E9%9D%A2 拷贝过来后，只修改过 homePageUrl 的参数。第一次出错，是因为拷贝的内容为富文本类型包含样式，保存后不是有效的可解析html文件，所以我发了这个 issue。之后你发了链接给我，保存后还是出问题，是因为中文双引号的问题，关键是我改过来了，但点击链接跳转的地址还是不对。最后我没办法，只好自己写个最简单的内容为 404: Not found 的 404页面。但就在刚才我又重试，发现又好了，我真心无语了，难道是以前改好了，刷新页面时，有缓存的问题？这与绝对路径和相对路径无关。尽管我是个java小菜鸟，但这基本概念我还是知道的。不管怎样，还是谢谢你，这个 issue 就彻底解决了！

**Comment by chitanda** [comment]
是我疏忽了。如果是这样的话还有个可能是hexo的缓存问题。可以先`hexo clean`然后`hexo g`。

**Comment by phenfun** [comment]
@chitanda 好吧。我不想说我一直都这样运行的：hexo clean && hexo d -g

**Comment by chitanda** [comment]
那就比较灵异了。。现在没有之前的404文件，也不好对比问题出在哪里了╮(╯▽╰)╭

**Comment by phenfun** [comment]
@chitanda 是很诡异。我也无法解释。但至少现在确实是可以的。为了解决这个喜欢在后面加 homePageUrl 参数值的问题，我确实捣腾了一段时间。有个不情之请，每次提交的时候，都要输入github的帐号和密码，怎么破啊？我按照别人搭建时的教程已经添加过 ssh key，难道这与我的问题不搭噶？

**Comment by chitanda** [comment]
git传输方式的问题。用ssh的git连接，不要用https那个。参考：
http://chitanda.me/2015/06/11/tips-for-setup-hexo/
