### ISSUE TITLE
打赏

### ISSUE THREAD

**Issue by zqdongxw** [iissnan/hexo-theme-next#301]
内容付费的时代已经带来，so 不少hexoer 也需要这个功能吧。

**Comment by xirong** [comment]
@zqdongxw  我之前整个这个东西，详情参考：https://github.com/xirong/hexo-theme-next/wiki/%E5%A2%9E%E5%8A%A0%E5%8D%9A%E5%AE%A2%E6%89%93%E8%B5%8F%E5%8A%9F%E8%83%BD，不过后来发现自己的文章质量上还不够，于是没有采用。

**Comment by imcoddy** [comment]
@xirong 不是不被采用，而是你的 Pull Request #179 不能被采用。
你去看一下，现在是无法合并的状态，@iissnan 想合并也合并不了。
你需要先 rebase 一下你的代码，修改好里面的冲突别人才能接受的。

**Comment by xirong** [comment]
@imcoddy  我说的不采用是指的我个人博客上自己关掉了，开了一段时间也没有打赏的。#179的冲突问题，回头会找时间解决下的。
