### ISSUE TITLE
为什么我的标签云的标签大小是一样大的

### ISSUE THREAD

**Issue by JOKERCHAN** [iissnan/hexo-theme-next#302]
标签云的大小为何一致啊。很喜欢那个大小不一样的样子。弄了好久不知道怎么回事。麻烦解答下 。谢谢

**Comment by flashlab** [comment]
大小代表文章数多少，如果都是一样多就是一样大小了

**Comment by iissnan** [comment]
看了下你博客的所有标签下都只有一篇文章（我好无聊），每一个标签都只有一篇文章，你可以试试多加几篇文章，在文章内多加几个标签。

**Comment by JOKERCHAN** [comment]
谢谢 知道怎么回事了。 = = 大神为何也这样闲。
