### ISSUE TITLE
当相片文件名为 _MG 开头时无法读取的问题

### ISSUE THREAD

**Issue by Renlong-Yin** [iissnan/hexo-theme-next#303]
若 post.md 如下：

```
title: ☭
type: quote
comments: false
date: 2014-08-20
---
![_MG 0096](/img/_MG_0096.jpg)
```

则相片 can't load，若更改 `_MG_0096.jpg` 为 `IMG_0096.jpg`，则一切正常。

暂未考证此问题为 hexo 所为还是本主题的 bug。

> _MG 为相机使用 Adobe RGB 色彩空间时默认文件名

**Comment by iissnan** [comment]
猜测是下划线开头的文件被 Hexo 忽略掉了
