### ISSUE TITLE
多说评论，如果有非游客账户评论，会导致评论显示不了

### ISSUE THREAD

**Issue by x8087** [iissnan/hexo-theme-next#304]
由于layout/_scripts/comments/duoshuo.swig文件第20和21行的判断限制
如果theme.duoshuo_info.admin_enable配置为false会导致duoshuo_user_ID没有设置，而引起source/js/hook-duoshuo.js的18行报错找不到变量duoshuo_user_ID而显示不了评论

**Comment by smilexiamo** [comment]
@x8087 如果不想显示`博主`字段的话，`duoshuo_user_ID`的值设置为`0`即可。不要留空。

**Comment by smilexiamo** [comment]
@x8087 `duoshuo_user_ID`表示为多说的用户id号，可以在http://dev.duoshuo.com中选择`登录`--->`你的用户名`--->`我的主页`,然后在浏览器的地址栏截取`dev.duoshuo.com/user/xxxxxxxx`,其中`11339369`就是你的多说用户id号，填入`duoshuo_user_ID`字段中即可。

**Comment by x8087** [comment]
抱歉，可能我描述不是很清楚，关键点不在于id，而在于admin_enable的设置不能为false，否则会显示不了

**Comment by smilexiamo** [comment]
@x8087 还真是，找个时间我修复一下吧，最近有点小忙。。

**Comment by chitanda** [comment]
@smilexiamo 
顺路提一点小意见：
建议在浏览器名称和浏览器版本号中间加两个空格键。。现在中间靠`|`分割然后紧紧贴一起，看着略难受。
![image](https://cloud.githubusercontent.com/assets/8258592/8949119/caf5f24e-35e1-11e5-92e3-68e062ab17fb.png)

**Comment by smilexiamo** [comment]
@chitanda 请问是加上两个空格中间再用`|`分割吗？我在考虑要不要加入系统或者浏览器的Icon增加辨识度。

**Comment by smilexiamo** [comment]
@x8087 已修复。更新下主题吧。

**Comment by chitanda** [comment]
@smilexiamo  icon的话我个人倒是没啥特别需求。不过加上去也可以，因为默认有iconfont字体，不需要另外再引进去，属于锦上添花了。

**Comment by smilexiamo** [comment]
@chitanda 仔细想了想，还是留给使用者自己DIY吧，加上去会让主题略显臃肿，毕竟只是一个小功能呢。我的懒癌晚期又犯了：）
