### ISSUE TITLE
请问是否在自定义 logo 时，以 logo（png格式） 替换主页最上面的 title？

### ISSUE THREAD

**Issue by Renlong-Yin** [iissnan/hexo-theme-next#305]
换句话说，是否可以 disable IcoMoon？

若可，是否可用 png 格式 logo 时自动不显示 title（只显示logo）？

**Comment by iissnan** [comment]
目前没有这个配置。

若是整个替换成自定义的图片应该比较容易；仅替换左侧的icon，对图片的格式要求比较高。两个方案都不需要 disable IcoMoon。可以预期的实现可能是：

增加配置选项

```
custom_logo:
  replace: true/false
  image: url-of-image
```

**Comment by Renlong-Yin** [comment]
* 若实现custom logo，则此 logo 与侧边栏 avatar 会重复（且 avatar 对背景色为透明的 png 文件支持不够友好）。是否可考虑提供关闭侧边栏的选项？

* 若关闭侧边栏，是否可把 description 下放到 custom logo 下？

* 是否能方便自定义字体和字号？

**Comment by Renlong-Yin** [comment]
此站是比较不错的图片站点优化参考方案:

http://minimumtheme.tumblr.com/
