### ISSUE TITLE
关于添加背景音乐为博客润色

### ISSUE THREAD

**Issue by phenfun** [iissnan/hexo-theme-next#307]
尝试在模板 footer.swig 里面添加一段 吓米播播的代码
但是不晓得如何隐藏播放器 占着面积太大 有点不雅啊
另外不能实现如 qq空间那样的全局播放
切换页面 好像就刷新一次 音乐就得从头播放 这不美好
所以在这里弱弱问下大神们 可有哪位有这方面的经验
提供一些思路和解决的方案呢 不甚感激！
Looking forward to your good news !

**Comment by chitanda** [comment]
个人一点看法，不一定正确：

1. 隐藏播放器那是作死。不是所有人都喜欢你的背景音乐和音乐品味。
2. 一定要放音乐播放栏的大概只能像微博那样放页面左下角。
2. 没用过QQ空间的音乐全局播放，不过目前大部分有全局播放的无非以下几种思路：
    1. iframe
    2. quickling
    3.  全站ajax实现页面不刷新，也就是所谓的SPA

上面3种办法里，2，3都是需要后台配合的，对于纯静态页面的hexo站点来说并不现实。第一种全站iframe的话，对于那些对播放器没需求的人来说，对blog改造的又太彻底，没有美感。

---
因此个人现在是比较反对添加播放器的，因为HEXO上没有比较优雅的实现方案。期待其他大神的意见

**Comment by phenfun** [comment]
@chitanda 很感激大神你的回复。只有你鸟我，其他大神都很忙，没空理我这个小白。我曾想过用 iframe ,但没有尝试。在 footer.swig 里面添加个 iframe 标签，然后放入播放器代码，比如 embed 之类？针对上次 404 的问题，发现引用公益页面的话，homePageUrl 的值真不好设置，最后我直接丢个 404.html 文件放在 source 根目录下，内容如下：<html><title>404: Not Found</title><body>404: Not Found</body></html>。

**Comment by iissnan** [comment]
@chitanda :+1: 。如 chitanda 所说，全局播放的问题对于静态博客来说确实比较麻烦，对于 NexT 来说，改动会非常大。

SPA的方案其实还是比较容易的，如果你感兴趣的话可以尝试：

1. 写一个 Plugin 来获取所有 post 的数据，存储成特定的 JSON 文件（组）
2. 使用脚本拦截站内请求，将请求转换成对 JSON 文件的请求

**Comment by iissnan** [comment]
在 NexT 的基础上使用 [jquery-pjax](https://github.com/defunkt/jquery-pjax) 的可行性不知道如何。可以预见的问题是 jquery-pjax 对于浏览器的要求比较高，一旦发生 fallback，全局播放的效果也就失效了。

**Comment by phenfun** [comment]
@iissnan i大降临，荣幸之至。其实我就是个小白，不知道什么是 spa。暂时我就放弃这名为“润色”，实为装逼的行为吧，😂……

**Comment by chitanda** [comment]
@phenfun  404那个问题我一直你弄好了，因为issues都关掉了。。homePageUrl你开始标点符号用错了。把我的那个404替换过去应该就好了。。

---
播放器里这个问题里来说，用iframe的话，是把整个blog都扔iframe里去，播放器模块单独出来，这么一来就可以保证页面不管怎么变都不会影响播放器的进度。但是这样改造工程比较大，而且我个人很不喜欢这种方式，为了播放器妥协太多，因小失大。

**Comment by chitanda** [comment]
@iissnan  其实我之前倒是有考虑过要不要尝试着给next改成spa的形式，感觉页面不刷新的体验好不少。不过因为之前没有实践过SPA，所以也不是很了解具体原理。想请教下除了浏览器兼容性外，其他还有可能出问题的地方会是？

**Comment by iissnan** [comment]
SEO、必须 JavaScript enabled。

**Comment by phenfun** [comment]
@chitanda 用英文模式的双引号替换掉中文的双引号以后，还是不行。点击“回到我的首页”，浏览器默认在当前的地址下添加 homePageUrl 参数的值。比如说，正常访问 404 公益的页面，地址为 www.rt4j.com/404，如果访问 www.rt4j.com/abc，如果不存在，浏览器会跳到 404 页面，点击“回到我的首页”，地址会变为 www.rt4j.com/homePageUrl的值。如果访问 www.rt4j.com/abc/abc，不存在的话，浏览器还是会跳到 404 页面，但值得注意的是，浏览器地址栏地址为 www.rt4j.com/abc/abc，此时，点击“回到我的首页”，地址会变为 www.rt4j.com/abc/homePageUrl的值。啰嗦了这么多，总结一下就是：配置 404 以后，不管访问地址是什么，只要不存在，都会自动跳转到 404 页面，但点击“回到我的首页”，得到的跳转地址是什么呢？允许我用 java 的伪代码来描述一下：String str1 = 浏览器地址栏地址；String str2 = homePageUrl 参数的值；（str1.substring(0,str1.lastIndexOf("/")+1) + "/" + str2）就是最后点击 404 页面中“回到我的首页”超链接跳转的地址。发现敲完这么多，我整个人都不好了……😓

**Comment by chitanda** [comment]
@iissnan 明白了。不过SEO对跟人blog站来说应该不算啥大问题吧。。

**Comment by chitanda** [comment]
@phenfun  你需要先去了解下`相对路径`和`绝对路径`。我就好奇你到底有没有试过我给你的那个[`404`](https://gist.githubusercontent.com/chitanda/cb71043ce14d2558a628/raw/81954bca1a9d0f7f87a0bbbbfac5044719b8d3e6/404.html)页面。。
<script src="https://gist.github.com/chitanda/cb71043ce14d2558a628.js"></script>

给你看下正常的404页面。
http://chitanda.me/404/404

**Comment by phenfun** [comment]
@chitanda 谢谢你！我都想哭，记得以前按照你说的，另存过 404 页面，修改过中文的双引号，但我发布以后发现还是像我刚才描述的问题一样。最后我实在没办法，才放弃了公益的404页面，自己丢个最简单的404页面在source根目录下……但刚才我又重下载、另存、改双引号、发布，然后就真的好了，我不知道这是为什么，这是为什么啊！！！
