### ISSUE TITLE
加载页面时的渐变动画卡顿感明显

### ISSUE THREAD

**Issue by paicha** [iissnan/hexo-theme-next#308]
OS X 下，Safari 打开还是挺流畅的，Chrome 打开基本都会卡顿。
是否提供一个关闭这些动画的选项？

**Comment by iissnan** [comment]
主题配置文件中，将 `use_motion` 设置为 `false` 就可以禁用掉全站的动态效果。

说回来，动画卡顿确实是一个问题

**Comment by zhoujiealex** [comment]
@iissnan 能否关闭 use_motion的同时， 保证在文章页面 自动展开侧边栏，  
主要是默认的侧边栏 隐藏的太深了。
想达到不要动画，但是要侧边栏导航的效果。

现在我看了以前[issue 441](https://github.com/iissnan/hexo-theme-next/issues/441) 还是没解决啊

**Comment by cutelittleturtle** [comment]
在我的安装里，需要改变的是

`motion:
       
enable:true
`

加`use_motion`不能override以上设定

**Comment by ivan-nginx** [comment]
@cutelittleturtle because was refatoring on motion in #1829.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/pull/41

**Comment by LauArmy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
