### ISSUE TITLE
问一个小问题

### ISSUE THREAD

**Issue by twocucao** [iissnan/hexo-theme-next#31]
你的侧边栏很漂亮,我想仿照一个.

但是我遇到了问题,	

我找不到你的主题中的变量在哪设置的?

换而言之,就是诸如

{{ __('sidebar.overview') }}
{{ site.posts.length }}
{{ site.pages.length }}
{{theme.description}}

这些在哪儿定义?

我查看了官网的文档,在主题里查找相关变量,没有发现相关内容.

**Comment by iissnan** [comment]
变量在 [Variables | Hexo](http://hexo.io/docs/variables.html).

你所提到的那段代码里：

1. __('sidebar.overview') 这是 i18n 的辅助方法，其中 sidebar.overview 是定义在语言文件中的。
1. {{ site.posts.length }} 与 {{ site.pages.length }} 就是上面的链接中 `Site Variables`。
1. 最后一个 `theme.description` 这实际上是 `config.description`。在站点的 `_config.yml` 中设置。

**Comment by twocucao** [comment]
谢谢你! 我解决了.

还有一个小问题.

我对这个v3版本不是很熟悉,以前在v2的时候,我可以直接在source文件夹里面放置一个index.html,在执行hexo g -d 的时候直接就可以跳过渲染文件夹内部的文件,部署成功以后就可以直接访问地址来查看.

那么,如果我想自己写一个小网页单独放在source/temp 中,有什么好方法可以像v2版本一样正常运行吗?
(我想直接吧gitbook的静态网站和hexo Blog 同时挂在githubpage上)

**Comment by iissnan** [comment]
试试 `skip_render`。[Configuration](http://hexo.io/docs/configuration.html) - Directory.

**Comment by twocucao** [comment]
谢谢,我尝试了一下,好像不能用(或者Glob语法错误???)暂时没有办法把html夹在Source文件夹里面.

不过,我尝试了另一个方法,在shell脚本中先执行
hexo g
然后
gitbook直接生成html到public里面
最后

hexo d



终于解决这个问题啦,非常感谢!

**Comment by iissnan** [comment]
:+1:

**Comment by tonydeng** [comment]
不过，这个毕竟不是一个最优的办法，如果我们使用hexo clean的话，gitbook生成的内容就没有了。

有没有什么根本的解决办法？
