### ISSUE TITLE
“阅读全文”功能

### ISSUE THREAD

**Issue by jxiaoyu** [iissnan/hexo-theme-next#311]
非常感谢您提供的主题。我在使用过程中发现首页文章很长也是全部显示的。请问怎样能对过长的文章只显示一部分，然后通过”阅读全文“的按钮去看全文呢？

**Comment by iissnan** [comment]
[NexT 常见问题 - 首页显示文章摘录](http://theme-next.iissnan.com/faqs.html)

**Comment by jxiaoyu** [comment]
感谢
