### ISSUE TITLE
favicon.ico无效怎么回事

### ISSUE THREAD

**Issue by lycaste** [iissnan/hexo-theme-next#312]
谢谢UP的框架...我这种菜鸡也能搭出漂亮的blog了..现在遇到一个问题。favicon.ico设置了无效，我看了你的文档，丢在hexo/source文件下，我的根目录是Blog。我放在Blog/source/favicon.ico。编译上传到git上，这个图标也直接在git项目的根目录。但是任然显示的绿色的H

**Comment by jerryling315** [comment]
把你的目录树贴一下, 你这样明显是git根目录就在source下

**Comment by iissnan** [comment]
应该是缓存问题，我现在看到的是 swift logo

**Comment by HeminWon** [comment]
这个设置好之后好像是不会立即显示，缓存时间是比较长的
