### ISSUE TITLE
代码显示出错。

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#313]
![default](https://cloud.githubusercontent.com/assets/7333266/9006349/ff8f0b20-37b8-11e5-8473-79b8dbaaf2f8.PNG)

生成css中：
```
.post .highlight table {
    margin: 0;
    width: 100%;   // 注释这行显示正常，.highlight table, .gist table { width: auto;}规则生效。
    border: none;
}
```
显示正常：
![2](https://cloud.githubusercontent.com/assets/7333266/9006345/f1d9ad00-37b8-11e5-9913-5fbcad9a5eb8.PNG)
请修复。

**Comment by iissnan** [comment]
多谢反馈，已修复。
