### ISSUE TITLE
使用disqus评论，标签和分类下也会出现评论框。

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#315]

**Comment by smilexiamo** [comment]
在对应的`index.md`文件中加入`comments: false`应该可以解决。

**Comment by iissnan** [comment]
现在 pages 和 posts 都会带上评论， pages 如果不需要可以按照 @smilexiamo 说的方式关闭

**Comment by geekrainy** [comment]
@iissnan  @smilexiamo Thank!
