### ISSUE TITLE
Mist - 紧凑版无法启用

### ISSUE THREAD

**Issue by JolsonZhu** [iissnan/hexo-theme-next#318]
将#scheme: Mist 前的 # 去掉并且发布后，打开依旧是原版
![01](https://cloud.githubusercontent.com/assets/12669627/9024274/af12ba48-38f8-11e5-86a2-c82d416c22c0.png)
但在本地localhost查看时，已修改为Mist版
![02](https://cloud.githubusercontent.com/assets/12669627/9024275/ca0213b2-38f8-11e5-854f-89053ca461fe.png)
确认已上传至github，请问这个如何解决？

**Comment by wjk20120522** [comment]
我之前也遇到了这样的问题,后来 我 hexo clean 下后 hexo g就好了
