### ISSUE TITLE
主题自带分享功能

### ISSUE THREAD

**Issue by wuchong** [iissnan/hexo-theme-next#319]
第三方的分享插件（jiathis，duoshuo），其图标在mac上的分辨率不是很清楚，样式也与主题不是很搭。

有没有考虑添加一个主题自带的分享功能？？

**Comment by iissnan** [comment]
我想图标模糊以及主题匹配的问题可以通过样式覆盖来自定义，也就是提供一套自定义的 icon 以及样式

**Comment by wuchong** [comment]
嗯， 这样也是极好的。 我看 next 中的 icon 都是用的svg。 不知道这些icon的svg data 是从哪里找来的 ？

**Comment by iissnan** [comment]
图标都是从 [IconFinder](https://www.iconfinder.com/) 上面找的

**Comment by wuchong** [comment]
我还是建议能够集成自带分享，不依赖第三方，主要是多说的服务很不稳定...

**Comment by iissnan** [comment]
0.4.6 看有没有时间集成自带的版本

**Comment by ivan-nginx** [comment]
@wuchong solved?

**Comment by ivan-nginx** [comment]
Issue will be closed due not enought information.
