### ISSUE TITLE
火狐浏览器下不支持java代码段的markdown写法

### ISSUE THREAD

**Issue by baininghan** [iissnan/hexo-theme-next#32]
java代码段，在火狐浏览器下显示不正常。会显示出x轴和y轴的滚动条。````java`的这种。

**Comment by baininghan** [comment]
[效果图在这里](http://baininghan.com/2015/03/03/Redstone%20XML-RPC%20Library/#more)

**Comment by jiangxy** [comment]
我也是

**Comment by iissnan** [comment]
Will take a look at this issue when I get time. Thanks for your information.

**Comment by baininghan** [comment]
@iissnan 同样的效果图，刚进去此篇文章时，邮编的文章列表只显示1.没有文字。

**Comment by baininghan** [comment]
@jiangxy 我自己已经解决了，修改highlight样式，将overflow:auto;改为overflow-x:hidden;overflow-y:auto;

**Comment by iissnan** [comment]
很奇怪的问题。我刚试着用你的文章里的 `Java` 代码测试了一下，结果跟你显示的不一样。

![20150310123617](https://cloud.githubusercontent.com/assets/32269/6569276/3e7b1d68-c722-11e4-9547-de8fb20def8e.png)

我测试的代码是：

```java
public void doSomething( List array )
{
    boolean aBoolean = ( ( Boolean ) ( ( Map ) array.get( 0 ) ).get( "someBoolean" ) ).booleanValue();
}
```

```java
import java.io.Writer;
import java.io.OutputStreamWriter;
import redstone.xmlrpc.XmlRpcSerializer;
public static void main( String[] args ) throws Exception
{
    Writer writer = new OutputStreamWriter( System.out );
    XmlRpcSerializer.serialize( "Hello!", writer );
    XmlRpcSerializer.serialize( new Integer( 42 ), writer );
    writer.flush();
}
控制台输出：<value><string>Hello!</string></value><value><i4>42</i4></value>
```

**Comment by baininghan** [comment]
@iissnan 你是在火狐浏览器下测试的吗？难道只是我自己电脑里面的火狐浏览器有问题，我晚上回去还原回去，让别人访问试一下。

**Comment by jiangxy** [comment]
请问这个问题是否有解决？0.3.0里还是有这个bug

**Comment by iissnan** [comment]
Hi @jiangxy。奇怪的是，我尝试用同样的代码去生成文章，没有出现多个滚动条的问题。是否还有其他的因素导致这个问题？

**Comment by baininghan** [comment]
@jiangxy @iissnan  最近忙没有测试，我自己修改了滚动条样式之后正常。

**Comment by jiangxy** [comment]
@iissnan 我不是很懂前端。我用Firefox 29、Chrome 40、IE 10测试，Firefox和IE都有问题。Chrome正常。

@baininghan 的方法确实可行。在_custom.styl中加个配置即可：
```
.post pre, .post .highlight {
    overflow-y:hidden;
    overflow-x:auto;
}
```
另外我还发现在about页面中代码显示也不正常：
![test](https://cloud.githubusercontent.com/assets/1011123/6764557/4bd94404-cff0-11e4-9a93-c27bb0745259.jpg)
不过这个关系不大，一般不会在about页面写代码

**Comment by baininghan** [comment]
about页面以及我新建的自定义页面，代码区块是乱的。很痛苦

**Comment by iissnan** [comment]
我看看把你的修改以及代码高亮提到全局上。

**Comment by baininghan** [comment]
赞，等有空会试一试的，最近超忙的。
