### ISSUE TITLE
关于右侧隐藏区的界面进一步个性化问题

### ISSUE THREAD

**Issue by HeminWon** [iissnan/hexo-theme-next#322]
看啦别人的头像是圆形的，而且停留在上面还会自己转动http://blog.kingname.info/2015/07/19/mycodestyle/ 这个可以考虑下

**Comment by chitanda** [comment]
我记得作者之前说过这个效果很山寨感。。
其实这个要写很简单，一句css而已，不过个人也不怎么喜欢这个效果╮(╯▽╰)╭

**Comment by iissnan** [comment]
这个效果自定义不难，建议自己定制下

**Comment by idhyt** [comment]
你是在说我的头像吗哈哈，我自己改了下。
http://blog.idhyt.xyz/
感觉也不是很山寨 - -！
