### ISSUE TITLE
安卓微信内置浏览器字体颜色显示问题

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#323]
安卓4.4，微信6.2.2。
![webwxgetmsgimg 1](https://cloud.githubusercontent.com/assets/7333266/9056635/10bbc7a6-3ac7-11e5-88fa-0f31f879db4d.jpg)
![webwxgetmsgimg 2](https://cloud.githubusercontent.com/assets/7333266/9056636/10c2d3f2-3ac7-11e5-89ff-525d98392ad9.jpg)
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/7333266/9056638/1161b364-3ac7-11e5-9513-f7edf7b65a9e.jpg)

**Comment by iissnan** [comment]
确认可以重现

**Comment by ivan-nginx** [comment]
@geekrainy, solved?
