### ISSUE TITLE
博客按照最后修改时间排序而不是创建时间排序？

### ISSUE THREAD

**Issue by jungor** [iissnan/hexo-theme-next#325]
我发现，如果稍微修改一下发布时间早的文章，系统会把它当成新的一篇，从而在首页前面显示出来。
建议或者博客按照创建时间排序而不是最后修改时间排序？或者增加一个配置项来自定义=。=

**Comment by chitanda** [comment]
我这边不会这样。感觉是你配置问题。。。

**Comment by iissnan** [comment]
是按照创建时间排序的。我也没有出现这个问题，另外我没有发现有配置与这个有明显的关联。

**Comment by whzecomjm** [comment]
@jungor 我估计你写的文章没有写 `date: `，所以每次是以文件修改的时间算创建时间。

**Comment by iluhcm** [comment]
需要在最前面加上date时间,不然每次都是按照你修改的时间来生成和现实的

An kind of example.

```
title: Mac OS X 10.10.3下android-5.1.1_r9 源码下载与编译
date: 2015-08-18 10:36:21
categories: Android
tags: [Tech,Android]
---
```

**Comment by jungor** [comment]
get, 3q @whzecomjm @iluhcm
