### ISSUE TITLE
如何添加 微搜索

### ISSUE THREAD

**Issue by tenlee2012** [iissnan/hexo-theme-next#329]
RT

**Comment by iissnan** [comment]
@lzlun129

**Comment by lzlun129** [comment]
这有个以前写的： http://lizhuolun.com/posts/%E4%B8%BAhexo-next%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0tinysou-Swiftype-%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2/ 
建议你直接看下http://doc.tinysou.com/ ，然后自定义样式

**Comment by mousycoder** [comment]
微搜索不好用~~老挂~~虽然支持中文更好点 但是其他地方太差 差评 Swiftype  可以通过后台调整搜索权重等达到满意效果

**Comment by ivan-nginx** [comment]
@tenlee2012 solved?
