### ISSUE TITLE
代码的行号只有一个1，多行代码的行号是什么机制？

### ISSUE THREAD

**Issue by shnode** [iissnan/hexo-theme-next#33]
从原有的source拷贝过来的_posts， 发现所有的多行代码中都出现了一个1

![image](https://cloud.githubusercontent.com/assets/7784713/6542339/7d81cdd4-c530-11e4-957d-f9a803ced015.png)

markdown 语法如下：

    ```[python]
    class Animal(models.Model):
        name = models.CharField(max_length=50)
        age = models.PositiveIntegerField()

        # 下面这句决定了Animal是一个抽象类/Model
        class Meta:
            abstract = True


    class Human(models.Model):
        kind_hearted = models.BooleanField()
        sex = models.CharField('sex', choices=(('m','male'), ('f', 'female')), max_length=1)
        #...
    ```

**Comment by iissnan** [comment]
将 语言标识从 `[python]` 改成 `python` 就可以了。

代码高亮实际上是集成在 Hexo 里面， Hexo 3 应该使用的是 [highlights](https://github.com/atom/highlights)，我猜测是 highlights 在未能识别 `[python]` 所导致的。

**Comment by shnode** [comment]
帅。谢谢。
