### ISSUE TITLE
关于多说

### ISSUE THREAD

**Issue by HeminWon** [iissnan/hexo-theme-next#330]
我在配置文件中创建了：
# 多说帐号

duoshuo_shortname: your-duoshuo-shortname
文章中还是不能评论，这个主题说已经配有多说了 直接添加账号就行，我的没有效果，问题出在哪里

**Comment by iissnan** [comment]
多说 shortname 是否正确？

**Comment by baininghan** [comment]
@iissnan 我原先在/about/index.md中手动添加了如下代码(后来发现data-title和data-url都没有改动)：
```
<div class="ds-thread" data-thread-key="/about-me"
     data-title="about-iissnan" data-url="http://notes.iissnan.com/about/">
</div>
```
现在主题的comfig.yml增加了
```
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
```

我是应该在主题这里添加user_id，还是在blog/config.yml中添加short_name?
另外user_id是不是就是多说基本设置里面的密钥？short_name就是基本设置里面的名称？

我现在的问题是在/about/index.md里面增加了自己的多说div
```
<!--
<div class="ds-thread" data-thread-key="/tools"
     data-title="tools-iissnan" data-url="http://notes.iissnan.com/tools/">
</div>-->
```
导致页面出现两个多说框，一个有留言记录，一个没有留言记录。


请麻烦看一下效果图：http://www.baininghan.com/about/

**Comment by baininghan** [comment]
@iissnan 现在我去掉/about/index.md 里面的div，访问页面只存在一个多说框，也可以登陆，正常留言。但是以前的留言展现不出来了？但是多说的评论里面还是有历史评论记录存在的，这个该如何处理？

**Comment by xushaobo** [comment]
为什么我的duoshuo里没有徽信

**Comment by cross4fire** [comment]
一样的问题 哭死了。。虽然麻烦别人很不好意思  不过还是请大神指教  　Ｔ　Ｔ

**Comment by cross4fire** [comment]
文章中还是不能评论，这个主题说已经配有多说了 直接添加账号就行，我的没有效果，问题出在哪里

**Comment by bobbyliujb** [comment]
多说ID：进入dev.duoshuo.com的首页，上方黑色栏右侧你的账号下拉选框--我的主页，进入后显示的网址最后的数字就是自己的ID。http://dev.duoshuo.com/threads/53a1c51e16aac12b0df7ba9a

**Comment by ivan-nginx** [comment]
@HeminWon solved?
