### ISSUE TITLE
看完文档中的解释之后，字体修改还是存在的问题？

### ISSUE THREAD

**Issue by xiang578** [iissnan/hexo-theme-next#331]
我下载的source/css/_custom中没有variables.styl这个文件，是需要我自己创建吗？
还有字体库需要添加到哪里去？
有没有好的教程推荐？百度了好久都没有满意答案

**Comment by xiang578** [comment]
version: 0.4.4版本中找不到variables.styl文件

**Comment by iissnan** [comment]
文档 outdated 了... 在 `source/css/_variables/` 里 `custom.styl`。

字体库是指？

**Comment by xiang578** [comment]
是我天真了，后来才想起来，网页是直接调用本地字体的……谢谢

**Comment by haixinn** [comment]
怎么阻止侧边栏弹出啊，只想让他点的时候出来啊
