### ISSUE TITLE
hexo debug模式下高亮正常，但是提交后高亮不正确

### ISSUE THREAD

**Issue by lan2720** [iissnan/hexo-theme-next#332]
将主题配置中的code theme从normal改成了night，然后hexo d -g了。但是博客中的代码块还是normal样式，用hexo s --debug在本地看又是night样式的。问题应该是没提交到远程，但是hexo d -g又显示everything up-to-date了。求解。

**Comment by iissnan** [comment]
试试 `hexo clean` 后再 deploy

**Comment by lan2720** [comment]
@iissnan it works 多谢~
