### ISSUE TITLE
目前版本所有标点是悬空的，而此项目的演示图片却是正常的，可否修复？

### ISSUE THREAD

**Issue by Pararice** [iissnan/hexo-theme-next#334]
美观问题还是小事，标点也是中文的一部分，这多少有些不妥，希望尽快修复，除这个小问题以外，非常欣赏这个主题。

**Comment by Pararice** [comment]
添加描述：系统win10 x64 ie11、edge、chrome上均有此问题 但Android的chrome访问是正常的

**Comment by geekrainy** [comment]
字体就是这样的设定，你可以参考修改自定义字体，标点就会正常。:)

**Comment by Pararice** [comment]
受教，是那样的。
