### ISSUE TITLE
伸手党提个建议

### ISSUE THREAD

**Issue by lycaste** [iissnan/hexo-theme-next#335]
@~@就是文章与文章之间的区分度不明显。看着还是有这么一点点蛋疼，咋一看一个页面都是一篇文章...这个可以设置嘛...还是您老没加入这个功能

**Comment by chitanda** [comment]
![image](https://cloud.githubusercontent.com/assets/8258592/9268871/e7c3effa-4295-11e5-8567-791d4ea340b3.png)

这样不是挺好的么。。不知道怎么才算区分度明显。。

**Comment by imcoddy** [comment]
我觉得其实还好啊，不过打开首页就显示全文的，的确容易让人觉得压力大。
还是在文章里面加个 more 标签吧，你可以看看我的：https://imcoddy.github.io/
