### ISSUE TITLE
mathjax公式与markdown解析出现冲突，该怎么解决

### ISSUE THREAD

**Issue by BLKStone** [iissnan/hexo-theme-next#336]
我在md文件中输入的是
${\bf J}^{dark}(x) = \min_{c \in \{ r,g,b \} }(\min_{y \in \Omega(x)}({\bf J}^c (y))),(1) $

调试latex的网站 http://www.codecogs.com/latex/eqneditor.php
希望得到这样的结果
![form](https://cloud.githubusercontent.com/assets/8243595/9287651/ada3bfa4-4352-11e5-9a20-a908e0c56600.png)

但是似乎公式解析与markdown解析发生冲突
![darkchannel](https://cloud.githubusercontent.com/assets/8243595/9287654/be4f8ce8-4352-11e5-8330-574909e92412.png)

搜索引擎找了很久无果，想咨询一下解决办法

**Comment by BLKStone** [comment]
好吧，我解决掉它了。
公式中代表下标的`_`会被markdown当成斜体解析，所以要将它转义。
所以最终要改成

$${\bf J}^{dark}(x) = \min\_{c \in \{ r,g,b \} }(\min\_{y \in \Omega(x)}({\bf J}^c (y))),(1) $$

参考资料
http://mathjax-chinese-doc.readthedocs.org/en/latest/start.html [搜索关键词“混淆”]

**Comment by LiamHuang0205** [comment]
给了一个利用 JS 解决问题的办法：
<http://liam0205.me/2015/09/09/fix-conflict-between-mathjax-and-markdown/>

**Comment by BLKStone** [comment]
@LiamHuang0205  感谢分享

**Comment by Tveek** [comment]
可是更换**markdow解释器**，使用**pandoc**,可以几乎完美解决问题，[https://tveek.github.io/2016/08/27/octopress-hexo-learning-experience/#more](url)

**Comment by Tveek** [comment]
https://tveek.github.io/2016/08/27/octopress-hexo-learning-experience/

**Comment by Tveek** [comment]
好像网站必须复制才能打开

**Comment by ngunauj** [comment]
@BLKStone 所以是 多两个$就行了？
