### ISSUE TITLE
具体页面如何关闭多说热评文章的显示

### ISSUE THREAD

**Issue by tasselx** [iissnan/hexo-theme-next#337]
在一些页面不想显示热评文章，md文件里面需要加入什么配置

**Comment by Joe-Hill** [comment]
YAML
comments: false

**Comment by tasselx** [comment]
@Joe-Hill 我tags那个页面的有加入comments: false 如下,多说评论是关闭状态的，但是多说的热评文章还在
![image](http://ww2.sinaimg.cn/large/7c00f1e1gw1ev61fhlpulj20i008674h.jpg)

**Comment by Joe-Hill** [comment]
@tasselx 
呃，那我就不清楚了，我用的是 Disquz

**Comment by dannywu19910524** [comment]
@tasselx 热评是另一个参数
'uoshuo_hotartical: true' 改成'false'就可以了

**Comment by tasselx** [comment]
@dannywu19910524 感谢！ 我这边解决了，改了下 _layout.swig那个文件,根据comments参数的设置达到具体页面关闭多说热评文章的目的

```
 {% if (theme.duoshuo_hotartical and page.title and page.comments) %}
                <!-- 多说热评文章-->
                <p>热评文章</p>
                <div class="ds-top-threads" data-range="weekly" data-num-items="4"></div>
            {% endif %}
```

**Comment by yeziahehe** [comment]
thx.

**Comment by VeiZhang** [comment]
@tasselx 麻烦请教下，我按照你的方法修改 _layout.swig，没有成功，仍然会有热评文章？？
