### ISSUE TITLE
categories 与 tags文件夹下无内容

### ISSUE THREAD

**Issue by fyales** [iissnan/hexo-theme-next#339]
自己新建了tags和categories文件夹，但是编译过后没有生成index.html.点击菜单栏上的标签页报Cannot GET /categories/。
hexo自身的_config.yml配置如下：

``` xml
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
```

Next下_config配置如下：

``` xml
menu:
  home: /
  categories: /categories
  #about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html
```

希望大神们能够给出解答

**Comment by bao3** [comment]
我与你类似，我是在分类可以正常显示，但是 tags页面不显示任何标签，但是标签目录 public/tags/ 下面有标签，也有 index.html。
很是奇怪，也一直无解，希望可以有人帮忙解答一下。

**Comment by bao3** [comment]
@fyales 我已经解决了。问题的原因在于要在 *index.md* 指定类型，例如 `tags/index.md ` 就要加入 __`type: “tags”` __

**Comment by fyales** [comment]
index.md?我不知道这个文件夹在哪，请说详细一点可以么。。。
我现在的解决方案时自己重写head文件。

**Comment by iissnan** [comment]
按照 [这里的步骤](http://theme-next.iissnan.com/theme-settings.html#标签云页面) 创建即可

**Comment by RainKolwa** [comment]
### STEP1
```
hexo new page tags
```
### STEP2
打开 `/source/tags/index.md`，增加type
```
---
title: tags
date: 2016-06-08 16:19:38
type: "tags"
---
```
### STEP3
打开 `/themes/next/_config.yml`，找到menu，打开tags的注释，可能是这样
```
menu:
  home: /
  categories: /categories
  #about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html
```

**Comment by scotthou94** [comment]
@RainKolwa我按照步骤配置了站点的_config和主题的_config还有tag和category的index.md，但是点击我文章的标签转到的tag页面只显示了index.md中的type: tags或者categories/index.md中的type: categories，并没有拥有相应标签的文章

**Comment by TracerLee** [comment]
按照@RainKolwa 加了STEP2的`type: "tags"`就好了

**Comment by Zhang21** [comment]
type: "tags"
