### ISSUE TITLE
不知道何时可以支持分页功能？

### ISSUE THREAD

**Issue by baininghan** [iissnan/hexo-theme-next#34]
如题，可以在当前文章的底部，有类似上一页和下一页的按钮。

**Comment by baininghan** [comment]
我发现的确有分页的模块。我想知道如何将翻页的模块放在多说模块的上面，多说模块始终置于底部。
还有如何在关于页面底部添加多说模块？

**Comment by iissnan** [comment]
已添加页面导航。

在页面比如 `about.md` 中引用多说，只要添加：

```
<div class="ds-thread" data-thread-key="your-page-path"
     data-title="your-page-title" data-url="your-page-permalink">
</div>
```

配置下 `data-thread-key` 、`data-title` 以及 `data-url` 即可。

**Comment by iissnan** [comment]
@baininghan 你说的是文章的分页，还是文章上下篇的导航？

**Comment by baininghan** [comment]
@iissnan 文章上下篇的导航。我希望多说评论是置于底部的，翻篇的导航在文章下面，多说上面。我比较习惯这种，好像大部分网站都是这样的吧。

**Comment by iissnan** [comment]
OK。那已经实现了，效果看这篇文章：[ReactJS 快速入门](http://notes.iissnan.com/2015/getting-started-reactjs/)

**Comment by baininghan** [comment]
赞，我去看看需要改哪些文件。

**Comment by baininghan** [comment]
@iissnan 我还是不知道如何在“about”页面添加多说评论框。
是不是要修改`_layout.swig`这个文件：
```
<div id="posts" class="{{ postsClass }}">
    {% block content %}{% endblock %}
</div>
```
我对`{% block content %}{% endblock %}`表达不是不懂，不知道如何修改。

**Comment by iissnan** [comment]
不用修改任何 `template`。 新建 `about` 页面之后，不是有一个 `about/index.md` 文件么，在那个文件里加入我上面提到的那段脚本就可以：

```
<div class="ds-thread" data-thread-key="your-page-path"
     data-title="your-page-title" data-url="your-page-permalink">
</div>
```

也就是说，`about/index.md`的内容可能是这样：

```
title: 关于我
date: 2015-03-09 22:36:12
---

Blah blah blah


<div class="ds-thread" data-thread-key="/about-me"
     data-title="about-iissnan" data-url="http://notes.iissnan.com/about/">
</div>
```

再试试看 :smile:

**Comment by baininghan** [comment]
好的，我晚上回去试一试

**Comment by baininghan** [comment]
Great~我已经解决问题了，可以关闭issue~

**Comment by vinyo** [comment]
title: message
date: 2015-06-05 13:46:47
---
<div class="ds-thread" data-thread-key="/message"
     data-title="message" data-url="http://syscca.com/message/">
</div>
我这样加没显示多说呀!

**Comment by HeiLiu** [comment]
怎么在首页文章那里底部添加分页的导航呢 各位老哥
