### ISSUE TITLE
[BUG?]使用markdown-it的问题

### ISSUE THREAD

**Issue by hhuimie** [iissnan/hexo-theme-next#340]
今晚由于默认的[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)不完善.

所以使用了[hexo-renderer-markdown-it](https://github.com/celsomiranda/hexo-renderer-markdown-it). 

但是用了一下, 发现文章的侧边栏目录只显示一层目录, 无法展开, 并且点击无法跳转, 审查元素发现,`.nav-child` 一直是 `display: none;`

求助,默认的md简直不能忍啊..

**Comment by ivan-nginx** [comment]
@hhuimie solved?

**Comment by hhuimie** [comment]
@iissnan Never Know. It has been a long long time. Sorry.
