### ISSUE TITLE
如何不在归档页分页，让所有文章显示在一个页面上

### ISSUE THREAD

**Issue by uruir** [iissnan/hexo-theme-next#341]
默认是每页10条，我想去掉分页，把所有文章倒序显示在一个页上，怎么修改呢？

**Comment by chitanda** [comment]
blog的配置文件里，照下面的改
```
# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page
```

不过你的倒序是啥意思我没理解

**Comment by uruir** [comment]
@chitanda 恩，我知道这样可以，但我主要是想把归档页去掉分页，主页还是保留分页。

**Comment by chitanda** [comment]
抱歉，是我没看仔细。但我感觉这个应该是hexo底层功能，主题作者可能并没有对这个做过处理。估计不是改个配置就能实现的。。

**Comment by uruir** [comment]
@iissnan 博主，要怎么改代码呀。或者博主你是怎么学习制作主题的，我也想写一个主题体验个强度，可是找不到入门教程。

**Comment by uruir** [comment]
用简单粗爆的方式解决了，我是直接在“hexo-generator-archive"模块里，把"per_page"置为0了。这样主页就分页，归档不分页。好怂。

**Comment by chitanda** [comment]
重新补了下文档，发现配置里有。
http://theme-next.iissnan.com/faqs.html#设定归档页面文章的篇数
