### ISSUE TITLE
想问下这个主题有没有可能单独弄个js文件来加载用户自定义的js特效

### ISSUE THREAD

**Issue by chitanda** [iissnan/hexo-theme-next#342]
RT。
因为感觉有些小功能比较私人化，可能大众需求不会那么高，（比如那个不蒜子统计的PR，我个人blog根据标签页显示隐藏与否来动态改变页面title等效果）并不怎么适合整合到主题里去，因为即使是在主题配置文件里决定开不开启，那也是多了一次判断，各种diy小功能多了之后必然让主题变得庞大且影响页面渲染速度。
所以想问下有没有可能就是弄一个单独js之类的，让有需求的用户把自己的那部分js扔到这里面去，这样的话一来不需要每次更新主题都一个个文件找着改，二来也以后有别的diy小功能也好加

不过这种方式`目前已知的实现难点是

```
1. 有些效果并不是单独一段js就可以实现的，可能需要同时更改html模版部分
2. 有些js代码需要添加到特定模块里去
```

个人对hexo的底层实现不是很熟悉，所以也就是单纯提一个意见，开发者可以看下有没有可能实现。

**Comment by ivan-nginx** [comment]
@chitanda don't understand at most of your answer, but we working on speed optimization.
