### ISSUE TITLE
如何将以前在windows上建好的github博客移植到Mac上

### ISSUE THREAD

**Issue by xiangfly11** [iissnan/hexo-theme-next#344]
以前在windows上建立了一个hexo博客，使用了github的免费pages功能。现在使用Mac电脑，想知道怎么把它移植到Mac电脑上继续使用。谢谢

**Comment by chitanda** [comment]
首先你需要先在mac上装好hexo。然后把windows上的blog文件夹拷贝过去就好了。。插件记得重新装。

**Comment by xiangfly11** [comment]
@chitanda  我重新安装了hexo, 但是现在windows电脑不在自己这里。我只能通过以前上传到github的文件去安装到Mac上，问题是这里需要怎么安装，然后以后如何通过Mac更新github上的博客呢？ 谢谢了

**Comment by chitanda** [comment]
之前上传到github的文件。。这个要看你上传的是啥了。如果是完整的blog备份了，那直接拖下来就可以用了。如果只是`public`文件夹内的内容的话，那没啥实际用处。hexo的blog最重要的是文章的md源文件。至于更新，mac和Windows都一样的，hexo的指令不分平台

**Comment by xiangfly11** [comment]
@chitanda 谢谢你了，我只有public内容上传了，看来只能重现建立博客了。
