### ISSUE TITLE
请问侧边栏的社交链接下划线如何去掉？

### ISSUE THREAD

**Issue by jellybins** [iissnan/hexo-theme-next#345]

**Comment by chitanda** [comment]
到`blog\themes\next\source\css\_common\_section`目录下，编辑`sidebar.styl`文件，添加下面的代码
```
.links-of-author-item a {
    border-bottom: none;
}
```

**Comment by jellybins** [comment]
@chitanda  thanks 。刚搜到了。css一直比较弱。刚知道原来可以这么添下划线。之前只知道text-decoration。
