### ISSUE TITLE
右侧文章目录消失

### ISSUE THREAD

**Issue by rdmclin2** [iissnan/hexo-theme-next#347]
问题是这样的：
- 进文章，出现右侧文章目录，显示目录文章，没问题。
- 下面拖动页面，展开目录，没问题。
- 然后重点来了，点x关闭右侧文章目录，再点开，目录消失了。
- 再按x关闭，把页面拖到顶部，再点开，又会出现目录

<img width="320" alt="img" src="https://cloud.githubusercontent.com/assets/4705237/9411682/fe8b6d7a-4859-11e5-9a92-a2b8bd4bd9ca.png">

**Comment by wedojava** [comment]
不明觉厉,我这一切妥当,浏览器:Safari

**Comment by rdmclin2** [comment]
@wedojava 我这用Safari也没卵用，版本信息如下：

hexo: 3.0.1
os: Darwin 14.4.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by wedojava** [comment]
真是个奇怪的现象啊,看作者有没办法吧,估计难~~

**Comment by iissnan** [comment]
我记得修复过一个类似的 bug

**Comment by iissnan** [comment]
已经修复，请更新的到最新的修订版本

**Comment by rdmclin2** [comment]
@iissnan Great!
