### ISSUE TITLE
代码展示出现滚动条

### ISSUE THREAD

**Issue by zweite** [iissnan/hexo-theme-next#348]
代码样式好丑啊，请问怎么样去取消掉滚动条呢?

**Comment by wedojava** [comment]
你是火狐吧,谷歌浏览器和Safari都没有的.不知道这问题怎么解决

**Comment by wedojava** [comment]
另外,麻烦把标题修改下,实在是缺乏针对性.....

**Comment by zweite** [comment]
抱歉，忘了贴图了。另外，浏览器是chromium,版本 43.0.2357.130 Ubuntu 14.04 (64-bit)

![截图](http://g.hiphotos.baidu.com/image/pic/item/3b87e950352ac65c8e56ef15fdf2b21193138a01.jpg)

**Comment by wedojava** [comment]
我也是Ubuntu,不是开发版,是chrome,没问题不如换浏览器吧

**Comment by zweite** [comment]
恩，在mac下用chrome和safari都是可以的，应该是浏览器不兼容．但是换浏览器的话．．．还是算了
