### ISSUE TITLE
点击继续阅读能否不从文中开始阅读

### ISSUE THREAD

**Issue by callmewhy** [iissnan/hexo-theme-next#35]
现在的效果是，点击继续阅读之后自动用 `#` 对齐到了 `more` 部分一下的内容=。=、能不能在config 里加个设置，比如 `auto_scroll_to_more` ，因为这个不太符合阅读习惯，还是挺想一进来直接看到标题的。。。还有 `<!-- more -->` 以上的内容能隐藏吗？因为可能只是的概述，并不想在文中出现。

赞一下楼主，很赞的主题！

**Comment by iissnan** [comment]
很不错的想法，我加一个配置项。

隐藏 `<!-- more -->` 的以上的内容感觉有点怪，因为那些内容也是文章的一部分。 我觉得使用 Hexo 的 [Front-matter] (http://hexo.io/docs/front-matter.html) 特性，约定一个属性（例如 `description`），然后在主题里可以优先选择 `post.description`，`fallback` 到 `post.excerpt`，最后到 `post.content`。

**Comment by callmewhy** [comment]
十分感谢，希望有机会可以 fork 一下：)
PS：Homepage 也很赞！哈哈

**Comment by iissnan** [comment]
已完成。

1. 可以自定义 `阅读全文` 的按钮是否跳转到 `more` 以下的内容，默认是 `true`。
1. 增加了 `description` Front-matter，在首页将优先显示 `description`，其次是 `excerpt`。

比如文章 `test-more-link.md`，内容如下：
```
title: "Test more link action"
date: 2015-03-09 12:12:12
tags:
description: "foobar"
---

Blah blah blah...

```

**Comment by iissnan** [comment]
:smile:

**Comment by callmewhy** [comment]
大兄弟我太喜欢你了！

**Comment by mlick** [comment]
666 不错不错，解决我的问题~~~
