### ISSUE TITLE
No search bar in the default and mist theme

### ISSUE THREAD

**Issue by maajidz** [iissnan/hexo-theme-next#350]
Installed the theme and turned the scheme to Mist but I am able to get the search bar. is that a bug?
or Am I missing something?
![screenshot from 2015-08-24 17 19 56](https://cloud.githubusercontent.com/assets/13271535/9439428/7ff41386-4a84-11e5-9877-56f90497899f.png)

**Comment by chitanda** [comment]
The search bar isn't display by the default settings.You should add it by yourself.

manual:
http://theme-next.iissnan.com/third-party-services.html#Swiftype

**Comment by maajidz** [comment]
Got it. thanks. Try using an english version too.
