### ISSUE TITLE
升级hexo-3.1.1之后生成post无法解析markdown中标题#，post中依旧是"#"，请问这是怎么回事？

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#351]

**Comment by lazydao** [comment]
建议贴原文

**Comment by wongxingjun** [comment]
http://wongxingjun.github.io/2015/05/18/Paxo%E7%AE%97%E6%B3%95%E7%9A%84%E4%B8%80%E7%A7%8D%E7%AE%80%E5%8D%95%E7%90%86%E8%A7%A3/

**Comment by wongxingjun** [comment]
markdown标题不能解析了，之前是可以的，不知道是为什么

**Comment by wongxingjun** [comment]
不好意思找到原因了，hexo3.1.1对markdown语法检查更严格了，要求#和标题内容之间必须有空格，之前没有也可以正确解析，现在不行了，惭愧惭愧。

**Comment by zzpan** [comment]
fuck

**Comment by zzpan** [comment]
what a fuck

**Comment by JiantaoFu** [comment]
这个，其他的编辑器都可以啊。。。

**Comment by yangcvo** [comment]
请问下，为什么之前4个空格有框 ，现在都不行。
