### ISSUE TITLE
[BUG?]生成的404.html不对

### ISSUE THREAD

**Issue by haohao007** [iissnan/hexo-theme-next#354]
按照文档http://theme-next.iissnan.com/theme-settings.html的方法：新建 404.html 页面，放到主题的 source 目录下，但是使用hexo generate生成的public文件夹下的404.html明显不对，居然是站点的第一篇文章。反复尝试clean了还是一样的结果，上网也没查到什么资料，在文档的常见问题里也没见到。哪位大神能帮忙解答下。站点：http://haoc.info

**Comment by haohao007** [comment]
额 现在点站点的任何文章都会跳到404.html。hexo g每次生成的public文件夹里都会有404.html这个文件，明明我已经把source文件夹下的404.html已经删除了，为什么还会生成。额，好郁闷。求救。
站点：http://haoc.info  git仓库：https://github.com/haohao007/GitBlog/tree/gh-pages

**Comment by solarhell** [comment]
自己看看根目录的 404.html 吧... 你默认访问的 404 页面 就是根目录的

**Comment by haohao007** [comment]
额 我确认所有的404.html都被我删了。但是hexo g总会生成404.html，现在文章都不生成了。折腾了很久还是没找到原因，于是我直接重置了hexo。

**Comment by geekrainy** [comment]
是否在执行hexo clean后没有这个问题了呢。

**Comment by ivan-nginx** [comment]
@haohao007 solved?
