### ISSUE TITLE
怎样添加虾米音乐这种音乐控件？

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#356]
前端小白伸手党，如题，能不能把这种http://www.xiami.com/widget/isingle?spm=a1z1s.3521865.23309997.12.NN6HMG&sid=1773859142  控件弄到博客里去，不用每次去粘贴html代码，这样很麻烦。能给整合到主题里去吗？

**Comment by iissnan** [comment]
可以直接修改模板文件

**Comment by wongxingjun** [comment]
改post模板吗？

**Comment by iissnan** [comment]
取决于你所要放置的位置

**Comment by wongxingjun** [comment]
好吧，我本来是想可以在markdown里直接用一个标签就可以实现的，不太懂前端的东西，谢赐教。

**Comment by jiklin** [comment]
`markdown` 也支持 `html` 标签
