### ISSUE TITLE
如何设置自定义文件夹不被主体编译？

### ISSUE THREAD

**Issue by agileago** [iissnan/hexo-theme-next#359]
![qq 20150901105223](https://cloud.githubusercontent.com/assets/11799110/9595167/e2d64cb2-5097-11e5-9802-4ee41a009799.jpg)

现在我在`source`文件夹内建了一个`demo`文件，此demo文件就是放些自己写的html文件，但是生成的时候，主题还是给我添加了不少东西，如何才能不让他被编译？

**Comment by stiekel** [comment]
好像是用 `skip_render` 来配置，但我这配置一直有问题。

**Comment by stiekel** [comment]
刚刚用 https://github.com/hexojs/hexo/issues/1333#issuecomment-111217533 里的方法解决了。
