### ISSUE TITLE
发完贴后，默认不展示全部，有一个阅读全文怎么设置的？

### ISSUE THREAD

**Issue by caigaopei** [iissnan/hexo-theme-next#362]

**Comment by heatech** [comment]
more 以上的会显示

more 以上的会在首页隐藏

**Comment by caigaopei** [comment]
@heatech 可以描述的更准确一些吗?不是太明白!

**Comment by heatech** [comment]
在hexo根目录的source\_posts目录的“帖子文件名.md”文件中，在正文中，需要首页显示的部分内容和不需要在首页显示的内容之间，插入\<\!\-\- more \-\-\>。\<\!\-\- more \-\-\>标签后面的文字，都会显示为“阅读原文”连接。

**Comment by caigaopei** [comment]
@heatech 非常感谢您的耐心回答.可以了.
