### ISSUE TITLE
The next and previous paginator is not in expected sequence

### ISSUE THREAD

**Issue by winterTTr** [iissnan/hexo-theme-next#366]
Maybe this is by design, but it seems a little weird i think. If it is indeed like this, please close this.

Here is my page using hexo, let's say [this page](http://winterttr.me/2015/09/04/hexo-next-done/).
Please scroll down to the paginator.

In fact, the *start again* is a early page ( based on date ) and *common hero workflow* is later one based on this page. But right now *start again* is on right and *common hero workflow* is on left.

Usually, I think people may consider the left is the early page, and right is the later page.

So, is this by design?

**Comment by iissnan** [comment]
You are right. This is not by design, I will fix it.

**Comment by iissnan** [comment]
Fixed.

**Comment by winterTTr** [comment]
Thanks so much, I will update the latest version
