### ISSUE TITLE
在模板中如何获取 多说“喜欢”次数？

### ISSUE THREAD

**Issue by HuberyLee** [iissnan/hexo-theme-next#368]
我需要在文中信息部分显示 多说评论的“喜欢”次数，类似于“评论次数”，我找到了“评论次数”的代码：
<a href="{{ url_for(post.path) }}#comments" itemprop="discussionUrl">
  <span class="post-comments-count disqus-comment-count" data-disqus-identifier="{{ post.path }}" itemprop="commentsCount"></span>
</a>
我在网络请求中看到返回的数据中包含 “likes”，但不知道如何使用，还请指点一二，谢谢！

**Comment by ivan-nginx** [comment]
@HuberyLee dont understand u, write in English if not solved. If solved, close it please.
