### ISSUE TITLE
article 分类问题

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#37]
这是 archives 第一页显示，这是正常的
![image](https://cloud.githubusercontent.com/assets/3365500/6568650/3d11b10a-c716-11e4-9c46-fc9e1f7204f0.png)

但是到了第二页，就开始显示全文，而不是 title，另外，两行文章之间连接在一起了
![image](https://cloud.githubusercontent.com/assets/3365500/6568654/56c84082-c716-11e4-9ed0-84dc7908a2f9.png)

这是我个人的问题么，http://mingmings.org/archives/

**Comment by iissnan** [comment]
可能跟你所设置的 `permalink` 有关系，试试 

```
permalink: :year/:title/ 
```

**Comment by mingmings** [comment]
多谢了。的确，按照 timeline 的方式的话貌似 permalink 只能是你给出的这种，不过也不影响，我挺想改点东西的，可惜不太会
