### ISSUE TITLE
请问，侧边栏的社交链接，可以设置为图片吗？

### ISSUE THREAD

**Issue by CaliosD** [iissnan/hexo-theme-next#371]
请问侧边栏的社交链接，可以设置为图片吗？感觉图片会更好看一点。。。

**Comment by ivan-nginx** [comment]
@CaliosD dont understand u, write in English if not solved. If solved, close it please.

**Comment by CaliosD** [comment]
Sorry for my Chinese. :( That's an issue long time ago. I've closed it.
