### ISSUE TITLE
头像设置有点小bug

### ISSUE THREAD

**Issue by lingfohn** [iissnan/hexo-theme-next#372]
作者您好！
首先感谢你编写的如此好的主题。
但是我在使用你的主题过程中发现一点小bug，当然也可能是我的使用设置不当。
我按照你的说明设置了头像，主页是可以正常显示，但是在我的文章中，头像就无法正常显示了。
我的[blog](http://gitblog.me)
期待您的回应。

**Comment by iissnan** [comment]
`images/avatar.jpg` -> `/images/avatar.jpg`

**Comment by lingfohn** [comment]
感谢作者，的确是我设置的问题。
