### ISSUE TITLE
如何正确删除一篇文章？

### ISSUE THREAD

**Issue by CaliosD** [iissnan/hexo-theme-next#373]
我想删除一篇文章，于是在/source/_posts/中直接删除了相应的.md文件，然后`hexo g`了一下，但是在`hexo server`中发现文章还在。

请问该如何彻底清除一篇文章呢？谢谢~

**Comment by CaliosD** [comment]
删除不完全造成的一个问题就是，评论框报错：
```
评论框出错啦(990015): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-2015/09/12/早自习' for key 'channel_thread_key'
```
链接如下：[http://www.calios.gq/2015/09/12/%E6%97%A9%E8%87%AA%E4%B9%A0%F0%9F%93%92-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD/](http://www.calios.gq/2015/09/12/%E6%97%A9%E8%87%AA%E4%B9%A0%F0%9F%93%92-%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E4%B8%AD/)

**Comment by eurusd** [comment]
hexo clean
hexo g -d

**Comment by CaliosD** [comment]
clean之后还是会有评论框报错的问题。删除之后，重新新建一篇就好了~谢谢~~
