### ISSUE TITLE
请问如何去掉侧边栏中的分类数显示？

### ISSUE THREAD

**Issue by BigPa** [iissnan/hexo-theme-next#375]
个人不喜欢分类（categories）管理，侧栏的分类计数中一直为0。
![2015-09-16 14 11 00](https://cloud.githubusercontent.com/assets/9963287/9897581/cb2d1438-5c7c-11e5-9d06-3f56313cba05.png)

**Comment by BigPa** [comment]
在 `themes/next/layout/_macro/sidebar.swig` 中，删除如下代码：
```
<div class="site-state-item site-state-categories">
            {% if theme.menu.categories %}<a href="{{ url_for(theme.menu.categories) }}">{% endif %}
              <span class="site-state-item-count">{{ site.categories.length }}</span>
              <span class="site-state-item-name">{{ __('state.categories') }}</span>
              {% if theme.menu.categories %}</a>{% endif %}
          </div>
```

**Comment by 70kg** [comment]
请问你知道怎么在侧边栏增加微博秀那个挂件吗，谢谢@BigPa

**Comment by Overvenus** [comment]
@BigPa 谢谢，我也想去掉分类。

@70kg 可以试了一下在 `themes/next/layout/_macro/sidebar.swig` 97 行左右的 `</section>` 之前粘贴上新浪的那个 iframe，不过会很难看 :joy:

**Comment by 70kg** [comment]
@Overvenus 这个我试过 太丑放弃了😂

**Comment by Haocen** [comment]
@iissnan 我提交了一个针对此问题的修改。 #639
