### ISSUE TITLE
能否提供文章字数统计功能？

### ISSUE THREAD

**Issue by iluhcm** [iissnan/hexo-theme-next#378]
RT，

前端小白，不知道怎么修改配置文件。

能否在文章标题下面的‘时间/分类/评论’这一栏中添加文章字数统计功能？类似简书那样。

谢谢。

**Comment by iissnan** [comment]
可以使用 [Hexo WordCount](https://github.com/willin/hexo-wordcount)

**Comment by iluhcm** [comment]
多谢，我试试。
