### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by jovey-zheng** [iissnan/hexo-theme-next#382]
似乎发布上来的都会存在这个问题。
在一级站点添加`<meta http-equiv="Access-Control-Allow-Origin" content="*">`也没有解决，求大神指导！

**Comment by iissnan** [comment]
不太清楚你的问题场景。从错误提示信息来看，是请求的资源所在的服务器未提供 `Access-Control-Allow-Origin` 这个信息，也就是服务器不允许来自外站的跨站资源请求。

**Comment by jovey-zheng** [comment]
@iissnan 例如打开预览的[http://notes.iissnan.com/](http://notes.iissnan.com/)，在开发者工具中查看就会看到这个报错。这个报错会影响多说在首页文章标题下显示`暂无评论/有1条评论……`这个功能。报错如下：
![qq 20150918164803](https://cloud.githubusercontent.com/assets/9565245/9955935/391798dc-5e27-11e5-8a7d-a8359fd1c05b.png)

**Comment by Acris** [comment]
好奇怪，我这边查看http://notes.iissnan.com/没有报错。

**Comment by jovey-zheng** [comment]
@Acris @iissnan 知道了。因为Chrome装了一些插件，例如ABP，就会把一些东西给屏蔽了。
