### ISSUE TITLE
有没有办法设置制表符宽度？

### ISSUE THREAD

**Issue by dengbo22** [iissnan/hexo-theme-next#383]
抱歉可能我问的问题比较简单，我是刚开始学着用的^_^
我看了一下生成的页面，代码高亮很好看，但是好像制表符的宽度有点大。
有没有办法设置代码的制表符宽度为2/4/8？

**Comment by Acris** [comment]
你是指用Tab缩进宽度有点大？
我记得Tab缩进是4个字符吧，如果你觉得4个字符有点大，可以试试使用空格来缩进。

**Comment by geekrainy** [comment]
这个取决于你的编辑器的配置，在编辑器中配置tab缩进的空白字符数，相应的hexo也会解析成相对应的数目。

**Comment by dengbo22** [comment]
谢谢回答~
