### ISSUE TITLE
hexo generate报错

### ISSUE THREAD

**Issue by fenjuly** [iissnan/hexo-theme-next#388]
![](http://i.imgur.com/7KapuUe.png)

**Comment by zyvas** [comment]
`/themes/hexo-theme-next/scripts/merge-configs.js:8:26)`
就你涂改的地方，看到没？
这个文件的第八航，方法get没法用。
可能是版本问题，hexo需要导入。
在这个文件下，头上插入如下代码即可:

> hexo = require('hexo');

**Comment by fenjuly** [comment]
It works! Thanks!
