### ISSUE TITLE
移动端多说评论插件无法显示

### ISSUE THREAD

**Issue by YanhaoMo** [iissnan/hexo-theme-next#389]
今天发现在手机端使用多说时，当没有登陆时多说插件可以正常显示，但是一旦登陆多说之后，多说评论插件就从页面上消失了。暂时不知道是什么原因造成的，就只在手机端有这种情况。
ps.手机是小米2

**Comment by ivan-nginx** [comment]
@YanhaoMo dont understand u, write in English if not solved. If solved, close it please.
