### ISSUE TITLE
图片的引用问题及其他

### ISSUE THREAD

**Issue by cokePanda** [iissnan/hexo-theme-next#39]
我在source文件夹下建了个imgs文件夹放一些小图片，在post中引用到，在主页下显示正常，但点进帖子（read more）是图片无法显示，是不是相对路径改变了？如何改动？谢谢
另外，初次建站，一些小东西不太明确

google_analytics: UA-xxxxxxxx-1
google_site_verification: googlexxxxxxxxxxxxx.html

应该是这样设置吧？
head上能否增加热门文章及推荐文章？
headband如何改动形状？
鼠标移动到链接划线效果如何改变颜色？
再次感谢

**Comment by jiangxy** [comment]
这是hexo的问题，建议看下这个：http://ibruce.info/2013/11/22/hexo-your-blog/
图片通过`/imgs/xxx.jpg`引用，不能写`imgs/xxx.jpg`
推荐系统要自己集成第三方的
自定义的样式可以改`source/css/_custom.styl`
google_site_verification那个html好像是要放到自己域名下并访问一次

**Comment by cokePanda** [comment]
谢谢解答，我再琢摸琢摸
那个html我放过并且访问过了
但有的说要一直保存在网站目录下
所以有点迷惑

**Comment by cokePanda** [comment]
追问一下，首页文章之间的分隔线颜色在哪儿定义的？我看有的中间还可以加一个小图案

**Comment by iissnan** [comment]
@jiangxy :+1: 

`google_site_verification: ` 这个的值不是验证HTML页面的地址，而是一串字符串值；当然，也可以将 Google 提供的那个 HTML 页面放置在 `next/source` 目录下来验证。

**Comment by iissnan** [comment]
@cokePanda 
文章分割线定义在 [source/css/components/post-expand.styl](https://github.com/iissnan/hexo-theme-next/blob/master/source/css/_component/posts-expand.styl) 中， `class` 名字是 `post-eof`。

在最近的一个[修改](https://github.com/iissnan/hexo-theme-next/commit/64fa5e1547c1cadff6e1436f38c8cdf6f7dcd894)中，我将中间的小图案去掉了。所以你看到的可能是旧的版本。

**Comment by iissnan** [comment]
正如  @jiangxy  所说，你可以将自定的样式写在 `_custom.styl` 文件中。 

```
// Handband
.handband { background: your-color; }

// Post separator
.post-expand .post-eof {
  background: your-color;
  height: 3px;
  // etc.
}

// Post title link color
.posts-expand .post-title-link {
  &::before { background-color: your-color; }
}

// Link color (Apples to global)
a:hover {
  border-bottom-color: your-color;
}
```

**Comment by cokePanda** [comment]
@iissnan 那按照你的意思 google_site_verification:应当是googlexxxxxxxxxxxxx.html里面的xxxxxxxxx了，不用带google开头吧？

**Comment by iissnan** [comment]
不是的。Google Webmaster tools 验证有几种方式： 

- [ ] HTML file upload
- [ ] Domain name provider
- [ ] Google Analytics
- [ ] Google Tag manger
- [x] HTML Tag

选择 HTML Tag 之后，应该可以看到一段代码类似：

```
<meta name="google-site-verification" content="VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0" />
```

代码里 `content` 的值就是 `google_site_verification` 所需要的值。

**Comment by cokePanda** [comment]
还有一个弱问题，页面各处的文字字体哪儿控制的？我的文章标题怎么有时是粗体，有时又不是？
谢谢

**Comment by iissnan** [comment]
标题的 `class` 是 `.post-title`，你可以全局搜索下看看。
