### ISSUE TITLE
Emoji表情支持

### ISSUE THREAD

**Issue by ZorgafChan** [iissnan/hexo-theme-next#390]
首先很感谢作者一直用心的更新这个主题。:clap:

最近突然发现这个主题好像不支持emoji表情

我不知难度大不大，但是十分希望能够添加这个功能

**Comment by iissnan** [comment]
看下 [这个 Tag Plugin](https://github.com/sergiolepore/hexo-tag-emojis) 是否是你需要的？

**Comment by ZorgafChan** [comment]
谢
