### ISSUE TITLE
文章内容的字体在手机浏览器上显示很小，可以在哪里改大呢？

### ISSUE THREAD

**Issue by oxwu** [iissnan/hexo-theme-next#392]
文章内容的字体在手机浏览器上显示很小，可以在哪里改大呢？

**Comment by jt-wang** [comment]
同问...如果没有接口的话，是否只能手动修改 css 了？

**Comment by djyde** [comment]
只能手动修改 css 了

**Comment by ivan-nginx** [comment]
@oxwu dont understand u, write in English if not solved. If solved, close it please.
