### ISSUE TITLE
使用Swiftype做搜索,但是提示找不到sitmap

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#393]
创建的时候提示找不到sitmap,创建完后一直indexing your site.  
集成后一直搜索不到结果`No results found for “sublime”`  

请问是否还需要做其他的配置?
还望指教,谢谢!

**Comment by MarcelArthur** [comment]
在站点_config.yml文件下修改你的URL,修改成你指定的blog域名。

**Comment by AlanCheen** [comment]
@MarcelArthur 
谢谢你的回复,不过我还是没有懂你的意思
是Hexo目录下的_config.yml中的 url 吗? 如果是这个的话,我已经配置过了呢!
`url: http://yifeiyuan.me
`

**Comment by AlanCheen** [comment]
@MarcelArthur 还望指导

**Comment by AlanCheen** [comment]
@iissnan 召唤一下作者看看   我的blog是 http://yifeiyuan.me

先谢过!

**Comment by iissnan** [comment]
@AlanCheen 我目前看到的现象是  Swiftype 报 json 文件 404。

```
GET http://s.swiftypecdn.com/install/v2/config/gF4xphELAeFT72brRn3E.json 404 (Not Found)
```

**Comment by AlanCheen** [comment]
@iissnan 
谢谢你的回复
实在不好意思,我是做android开发的,所以web的东西不懂.
你说的404估计是我的key不对,我以前配置的被我删掉了

**Comment by AlanCheen** [comment]
@iissnan 这里是我的博客项目 :  https://github.com/AlanCheen/alancheen.github.io

我在Hexo目录下的_config.yml中配置了url,但是在swiftype里创建的搜索引擎的时候一直提示找不到sitmap,也不知道如何添加sitemap,还望指导!

Thanks in advance!

**Comment by AlanCheen** [comment]
@iissnan  我做好了 关闭了吧

**Comment by iissnan** [comment]
第三方服务的一些问题，我也不是很了解。（因为我使用的过程好像都挺顺利的。。）

**Comment by AlanCheen** [comment]
@iissnan 没事啦 我解决了~

**Comment by sunby** [comment]
求问是怎么解决的，我也遇到这个问题。
