### ISSUE TITLE
多图的展示的方案

### ISSUE THREAD

**Issue by zhourongyu** [iissnan/hexo-theme-next#395]
看到之前有人提议过了 #295 
貌似有解决方案了？ 演示站点顶部图片样式...
文档里貌似没写，怎么实现图片的样式？ 或者说 是一个单独的分类里？

**Comment by iissnan** [comment]
有一个实现方案了，目前还在 `dev` 分支上。
使用了一个称为 `grouppicture` (别名`gp`) 的 `tag`，使用方式类似：

```
{% gp group-layout %}
  ![](/image-1.png)
  ![](/image-2.png)
  ![](/image-3.png)
  ![](/image-4.png)
  ![](/image-5.png)
{% endgp %}
```

其中 `group-layout` 通常的形式是 `5-1`，表示的是使用 5 张照片的 第二个 layout，这个 layout 形式如下：

```
□ □
  □
□ □
```

可用的  group-layout 就是 #295 里所列出的。

**Comment by zhourongyu** [comment]
是不能通过自定义layout的方式来控制么？感觉这样的方式不太好

**Comment by iissnan** [comment]
@zhourongyu 能否具体点，你期望的使用方式。例如写法，如何指定你想要的 layout 等？

**Comment by zhourongyu** [comment]
我的意思是能否通过自定义变量来解决。
比如预先约定好 type: photo 
这样在模板中直接判断如果是 photo 类型则以某种形式展示~ 像现在的示例那样。

不建议给用户提供个性化展示方案，每个人需求不同，没办法都满足。 
只要定义出一套展示方案即可，例如：图片 <4 张，取头一张做 title，如果 >=4 张 则像现在示例模板这种方式

这样的好处是：
* 使用简单，对内容不干扰，只是列表的展示方式不同，普通用户也很容易切换，只需要在Front-matter 区修改一行类型变量，不论是修改之前的还是写新文章改动都很小，就算换主题也不会影响
* 对于高级用户来说，可以抽取单独的模板样式供自己修改

**Comment by iissnan** [comment]
嗯，想法不错 :+1: 。我可以将现在 Tag Plugin 所做的事情，变成使用 Front-matter 来控制。这样既可以保留迁移性以及图片展示方案的可定制性

**Comment by zhourongyu** [comment]
恩，或者有办法能通过 Front-matter 控制自动给文章添加 Tag Plugin ？ 
[TranquiPeak](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme)  里的图片展示比较丰富吧。 能更灵活就好了

**Comment by HuberyLee** [comment]
@iissnan 能否为目前的图片展示添加一些新的特性？目前的方式是：

```
{% gp group-layout %}
  ![](/image-1.png)
  ![](/image-2.png)
  ![](/image-3.png)
  ![](/image-4.png)
  ![](/image-5.png)
{% endgp %}
```
内容页中只有图片，没有任何文字，能不能做到图片之间穿插文字，首页与目前的效果一样，展示的图片从文章中取（其中group为首页显示的图片数量，group小于文中所有的图片数），内容页与普通的文章一样？

```
{% gp 5-2 %}
  ![](/image-1.png)

  文字。。。

  ![](/image-2.png)
  ![](/image-3.png)

  文字。。。

  ![](/image-4.png)
  ![](/image-5.png)

  ![](/image-6.png)
  ![](/image-7.png)
{% endgp %}
```

**Comment by yhlfh** [comment]
请问利用 front-matter 来控制多图展示这个想法目前进展如何？我看代码里好像还没有？

**Comment by kk649287100** [comment]
图片只会按照layout的样式缩小，但是排列样式无法实现

**Comment by ivan-nginx** [comment]
@zhourongyu dont understand u, write in English if not solved. If solved, close it please.
