### ISSUE TITLE
Next顶部的导航栏 无法横排展示

### ISSUE THREAD

**Issue by MarcelArthur** [iissnan/hexo-theme-next#396]
类似于金字塔形状的blog名在最上层，导航在下面，无法横排展示导航栏

**Comment by iissnan** [comment]
是指 [Mist](http://theme-next.iissnan.com/five-minutes-setup.html#选择_Scheme) ?

**Comment by MarcelArthur** [comment]
嗯 感觉我终于弄懂点了.....T_T 就是Mist主题 但是把# scheme之前的 “ #  ”去掉 本地调试还是显示默认主题

**Comment by MarcelArthur** [comment]
@iissnan  重新更新了一下主题好了！ 0.0  谢谢！（真是蠢T_T自己了-
