### ISSUE TITLE
无法显示数学公式

### ISSUE THREAD

**Issue by zhengxiaowai** [iissnan/hexo-theme-next#397]
已经在主题设置中 mathjax: true  ，但是还是无法显示

**Comment by iissnan** [comment]
检查下是否 MathJax 脚本加载失败，或者是 公式的格式 未被支持（写错）

**Comment by zhengxiaowai** [comment]
是脚本加载失败了。。

**Comment by iissnan** [comment]
参考 #363 ，将 MathJax 引用转到 七牛 CDN 上
