### ISSUE TITLE
代码高亮功能没生效，还是原始markdown的模块引用的样式

### ISSUE THREAD

**Issue by DaisenHo** [iissnan/hexo-theme-next#398]
代码高亮功能没生效，还是原始markdown的模块引用的样式，我是用三个反引号包着的代码块

**Comment by iissnan** [comment]
看下站点目录下 `_config.yml` 中的 `highlight` 是否 enable。或者有改过默认的 markdown 渲染引擎吗？

**Comment by ShotoZheng** [comment]
> 看下站点目录下 `_config.yml` 中的 `highlight` 是否 enable。或者有改过默认的 markdown 渲染引擎吗？

我也有这个问题，未修改过markdown渲染引擎，比如下面我在markdown编辑的文本：
![](http://pxb1undrn.bkt.clouddn.com/小书匠/1567750584352.png)
在博客渲染出啦会导致格式错误：
![](http://pxb1undrn.bkt.clouddn.com/小书匠/1567750704747.png)
