### ISSUE TITLE
首页的图片不正常显示，查看图片引用发现引用地址不正确，但全文阅读却没有问题

### ISSUE THREAD

**Issue by blueyi** [iissnan/hexo-theme-next#399]
首页在点击阅读全文之前的图片引用地址竟然直接是根目录，hexo3.0之后就是在帖子同名目录放图片么，点击read more之后却能正常引用图片，谢谢

**Comment by blueyi** [comment]
@iissnan  高人，我查看了好久next相关文档，也没找到，请给个提示，谢谢

**Comment by iissnan** [comment]
不是很清楚你的问题

**Comment by blueyi** [comment]
这里有个详细些的说明，谢谢 @iissnan 
https://github.com/wzpan/hexo-theme-freemind/issues/34#issuecomment-147064677

**Comment by ivan-nginx** [comment]
@blueyi dont understand u, write in English if not solved. If solved, close it please.
