### ISSUE TITLE
目前的 home 下阅读问题

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#40]
在已关闭的 issue 中看到了阅读的问题，但是貌似不是我现在看到的情况，我的 `<!--more-->` 继续阅读和 title 之间只会显示一个标题，这个是我的 .md 文件里面的定义的问题么
![image](https://cloud.githubusercontent.com/assets/3365500/6572354/6cabbe3e-c74c-11e4-8e73-8b2508b838ab.png)

感谢作者~现在就差一个提升逼格的 homepage 了，真心要赞

**Comment by iissnan** [comment]
可以提供你文章的 md 文件内容吗？ 是否修改过 `template` ？

**Comment by mingmings** [comment]
没有修改过 template ，文章内容如下
![image](https://cloud.githubusercontent.com/assets/3365500/6591532/6b0d31ce-c7fc-11e4-8dbf-cb2cc0e694ac.png)

**Comment by iissnan** [comment]
那个 `description` 对你来说有特殊作用吗？ 正好，我在前一个修改中使用了 `description`。 见：https://github.com/iissnan/hexo-theme-next/commit/cd92817be4f18da8697ea4e16a89ae2cab71afd1

**Comment by iissnan** [comment]
详细见这个issue: https://github.com/iissnan/hexo-theme-next/issues/35

**Comment by mingmings** [comment]
tks ，给力
