### ISSUE TITLE
如何修改全局字体大小

### ISSUE THREAD

**Issue by blueyi** [iissnan/hexo-theme-next#400]
现在在字体太小了，而且还有点发虚，如何修改大一些，另外本主题哪里有更详细的文档，谢谢

**Comment by iissnan** [comment]
编辑 `source/css/_variables/custom.styl`，添加：

```styl
$font-size-base = 16px; // 默认是 16px 大小
$font-family-headings = Georgia, sans // 标题，修改成你期望的字体族
$font-family-base = "Microsoft YaHei", Verdana, sans-serif // 修改成你期望的字体族
```

文档见： http://theme-next.iissnan.com

**Comment by blueyi** [comment]
谢谢

**Comment by liguanghe** [comment]
@iissnan hello, I have changed: source/css/_variables/custom.styl 
$font-size-base = 20px;
and when $ hexo s the font is bigger, but $ hexo -g d , it not worked, how can i do that?
thanks

**Comment by ivan-nginx** [comment]
@liguanghe
```
hexo clean && hexo g && hexo d
```

**Comment by liguanghe** [comment]
@ivan-nginx thanks, I just tried, it not work quickly, I have wait for 20 mins to see.
