### ISSUE TITLE
安装说是缺少样式表

### ISSUE THREAD

**Issue by azyy** [iissnan/hexo-theme-next#401]
名称	图像描述	
hexo-theme-next-master	缺少样式表。   求解决~~

**Comment by iissnan** [comment]
嗯？ 能否再詳細一點，關於這個錯誤的信息

**Comment by azyy** [comment]
能不能给个联系方式 我现在还不会安装Hexo~~~~~好费劲儿

**Comment by iissnan** [comment]
将 hexo-theme-next-master 文件夹更名为 next，放置在 themes 目录下
