### ISSUE TITLE
两台电脑进行hexo

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#402]
网上很多教程都用了，并没有太方便的方法，不知道谁知道，说说你的方法吧

**Comment by chitanda** [comment]
git全站备份你的hexo文件夹。去掉public，插件等文件夹

**Comment by zhaoweiwang** [comment]
@chitanda 在网上看过你写的教程了，不管是osc还是github，都会出问题。

**Comment by zhaoweiwang** [comment]
@chitanda 我觉得你可以把之前那篇博文修改下，写得完善些

**Comment by wuxinxinggg** [comment]
http://pydog.gitcafe.io/2015/10/11/hexo-blog/ 这样不行吗？

**Comment by chitanda** [comment]
@zhaoweiwang 指的是什么问题？

**Comment by dracodoc** [comment]
感觉总是会很复杂，简单的方法可以这样，一台机器有全套设置，只在这台机器进行上传操作。其他机器只同步_post目录，只修改文章内容或者写新文章，最多本地预览，但从不上传，只能去同步_post目录，_post目录可以用版本控制的方法同步。

这样的逻辑比较清楚，不容易出问题，否则我觉得总是会很麻烦。

**Comment by callmewhy** [comment]
。。。pages 分支发布网站，master 分支保存网站源码，这么简单的东西为什么会有问题。。。说有问题结果还不说是什么问题。。。而且这种问题为什么不去 hexo 项目里问。。。

**Comment by luodaoyi** [comment]
可以试试这个中的自动持续集成[http://luodaoyi.com/2015/11/04/auto-github-pages/](http://luodaoyi.com/2015/11/04/auto-github-pages/)
