### ISSUE TITLE
如何隐藏文章顶部的图片

### ISSUE THREAD

**Issue by leejanfin** [iissnan/hexo-theme-next#403]
首先先支持下作者。
有个问题，好久没更新了，刚才更新了NexT主题，发现出现这个功能，但是从文章中提取出来的图片显示在顶部的话非常小，反而很不美观，而且个人感觉这个功能对我来说没什么用，请问有没有办法可以隐藏呢？配置文件中修改参数或者改源码？非常感谢！

**Comment by iissnan** [comment]
方便贴下文章的内容吗？（头部设置和部分文章内容即可）

**Comment by leejanfin** [comment]
http://leejanfin.xyz/2015/10/08/Node-webkit-first-try/
另外，没明白您括号里说的是什么意思。。。。

**Comment by iissnan** [comment]
大概清楚问题了。第一是你的文章里 Front-matter 部分是否有设置了 `photos`，例如：

```
title: {{ title }}
date: {{ date }}
photos: 
tags:
---
```

如果有 photos，把他去掉。详细见：https://github.com/iissnan/hexo-theme-next/issues/282

第二个问题是，你使用的版本应该是从 Release 里面下载的（0.4.4），还是比较旧，图片的样式有问题。
我刚发布了一个新的 release （0.4.5.1），你可以更新到那本版本上。

**Comment by ivan-nginx** [comment]
@leejanfin dont understand u, write in English if not solved. If solved, close it please.
