### ISSUE TITLE
代码有时候不会高亮，不知道是什么原因

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#404]
```C++
```
用的是上面这种格式插入代码块的，仓主知道原因吗

**Comment by iissnan** [comment]
猜测是未带有 `language identifier` 所导致的。例如 `ruby` 语言代码：

<pre>
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</pre>

两种解决方案：
1. 加上  `language identifier` 
2. 增加 `auto_detect: true` 到站点 _config.yml 的 `hilight` 部分，默认自动检测语言高亮是关闭的

#186

**Comment by gongjujun** [comment]
![image](https://cloud.githubusercontent.com/assets/12054470/10539044/5f306c88-742f-11e5-9f79-684634470d9b.png)
我设置了highlight_theme: night  但是还是不好使,什么原因

**Comment by iissnan** [comment]
@gongjujun 这样设置即可，没有生效可能是缓存的问题。

**Comment by seanhuang514** [comment]
@iissnan 你說的兩個做法我都有做了，但是還是沒有highlight，請問會是什麼問題呢
