### ISSUE TITLE
description 字体颜色修改

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#405]
在哪里可以修改？

**Comment by iissnan** [comment]
编辑 `source/css/_custom/custom.styl` 添加：

```ccc
.site-description { color: #fff; }
```

**Comment by zhaoweiwang** [comment]
谢谢仓主，颜色好看多了~
话说扩展栏中的其它项目怎么改颜色呢？
加了“.site-title { color: #FF8C00; }”没有改到title的颜色
