### ISSUE TITLE
作者有没有除了 Mist 之外的其他主题呢？图片能不能自动居中呢？

### ISSUE THREAD

**Issue by gaoryrt** [iissnan/hexo-theme-next#406]
只发现了
`hexo/themes/next/source/css/_schemes/Mist/index.styl ` 
一处可以修改啊。。
想问问还有没有除了 Mist 之外的其他主题供选择呢？
还有就是长度大于宽度的图片显示是居左的，并不好看

**Comment by gaoryrt** [comment]
http://gaoryrt.github.io  
修改悬浮 header的效果  
希望作者能提供更多的主题

**Comment by winterTTr** [comment]
#485 应该已经fix这个问题了
