### ISSUE TITLE
文章页不能显示多说评论,一直在加载状态,标签页却能显示正常

### ISSUE THREAD

**Issue by Gitzhaoyang** [iissnan/hexo-theme-next#414]
![_2015-10-12t16-56-40 015z](https://cloud.githubusercontent.com/assets/12080364/10433491/d9c4e674-7144-11e5-9cec-d4bd8fb81529.png)  这个是文章页,,左下角蓝色的在加载..

**Comment by Gitzhaoyang** [comment]
今天白天去看一下。已经自己好了。

**Comment by iissnan** [comment]
多说的服务不太稳定
