### ISSUE TITLE
关于小屏幕多说评论边距的问题

### ISSUE THREAD

**Issue by LjxPrime** [iissnan/hexo-theme-next#419]
在小屏幕上显示时，不知为何没有边距，感觉很别扭，不知是否是这么设计的？
我看那个多说Share就有边距的。

比如说：
![image](https://cloud.githubusercontent.com/assets/11004804/10505034/152e0004-733b-11e5-8a3b-608488004740.png)
如果是小屏幕：
![image](https://cloud.githubusercontent.com/assets/11004804/10505040/30b4bdae-733b-11e5-915d-b4ce6c826934.png)
希望能改进下，变成这样：
（突然GH抽风图传不上了，大大应该能明白。）

**Comment by iissnan** [comment]
已修复
