### ISSUE TITLE
可以有社交分享功能吗？

### ISSUE THREAD

**Issue by orangeclk** [iissnan/hexo-theme-next#42]
请问可以添加社交分享按钮吗？谢谢！

**Comment by iissnan** [comment]
我看看能否在  `0.4.0` 中添加。

**Comment by iissnan** [comment]
哪个第三方社交分享功能比较不错的？

**Comment by eurusd** [comment]
百度可以吗?

**Comment by clongbupt** [comment]
百度: http://share.baidu.com

jiathis: http://www.jiathis.com/

**Comment by lzlun129** [comment]
我直接用的多说的分享功能，觉得还行啊~ http://lizhuolun.com，我修改的[主题地址](https://github.com/lzlun129/my-hexo-next)

**Comment by iissnan** [comment]
JiaThis 貌似不会被 ABP 过滤掉，百度的会。考虑将目前百度的分享替换成 JiaThis的，位置将从侧栏挪到文章的底部。

**Comment by eurusd** [comment]
考虑将目前百度的分享替换成 JiaThis的，位置将从侧栏挪到文章的底部。 好事

**Comment by iissnan** [comment]
已在 0.4.3 版本中实现，位置在文章的末尾、评论的上方。
