### ISSUE TITLE
关于使用 Disqus 显示评论的问题

### ISSUE THREAD

**Issue by ihappyhacking** [iissnan/hexo-theme-next#420]
多说出了问题，不想再用了，所以转到 Disqus，但是配置好之后，文章列表没有显示评论数，点击文章之后的标题下面也没有，不过下面有发表评论的部分，请问还需要怎么设置吗？谢谢！

**Comment by LjxPrime** [comment]
同样的问题，求大大修复啦~

**Comment by LjxPrime** [comment]
看了下，代码应该没啥大问题，感觉是不是因为Disqus服务器国内访问不稳定的缘故啊。

**Comment by ihappyhacking** [comment]
> 看了下，代码应该没啥大问题，感觉是不是因为Disqus服务器国内访问不稳定的缘故啊。

不知道呢。。。感觉没那么不稳定吧

**Comment by geekrainy** [comment]
问题在于disqus在国内的访问速度不同，各个区域对于disqus的访问可能有不同的限制，应该过些阵子就好了。

**Comment by ihappyhacking** [comment]
@geekrainy 
你的博客用的是多说还是 Disqus？如果是 Disqus，那么文章列表能正常显示吗？

**Comment by LjxPrime** [comment]
@ihappyhacking 我挂代理之后显示基本正常了，偶尔加载不出来，看来估计就是服务器连接不稳定的问题了。

**Comment by ihappyhacking** [comment]
@LjxPrime  现在挂不挂代理，好像都出来了，不过，都不全，有些文章出不来

**Comment by LjxPrime** [comment]
@ihappyhacking 恩恩确实如此，它是用的disqus官方的那个count.js加载的，可能是在列表页面的时候请求较多中间有一些连接失败了。文章页面情况就好很多了，不过加载原理是一样的。看来想要速度还是得用多说。
PS今天多说官方发文说故障恢复了，就是不知到底怎么样，还会不会出问题。

**Comment by ihappyhacking** [comment]
@LjxPrime 可以重新打开多说配置看一下

**Comment by ihappyhacking** [comment]
@LjxPrime 我试了一下，文章列表评论数正常了，但是进入文章之后，文章底部的评论没有出来

**Comment by ihappyhacking** [comment]
@LjxPrime 只要有评论的文章，下面的评论就出不来，热评文章倒是可以了

**Comment by LjxPrime** [comment]
@ihappyhacking  看来还是得用disqus了 多说还是不稳定，我看讨论区里也是这么说/

**Comment by ihappyhacking** [comment]
@LjxPrime 恩，还是用 Disqus 好了

**Comment by idyllchow** [comment]
测试

**Comment by lipeng1667** [comment]
表示确实是因为GFW的问题，通过VPN访问，就可以正常显示；但是如果不开就显示不了。。。

**Comment by meilbn** [comment]
@lipeng1667 
是这样的，浏览器开启 Shadowsocks 就可以显示 disqus 的，不开显示不出来，看来又得转回多说了。。。

**Comment by Jialin28** [comment]
我在本地可以显示，通过网络访问就会无法显示

**Comment by Penguin-G** [comment]
我只有一篇文章不显示标题下面的评论...好忧伤
