### ISSUE TITLE
Hexo下NextT主题新建页面下如何放多个文章?

### ISSUE THREAD

**Issue by xiaomeixw** [iissnan/hexo-theme-next#421]
RT....貌似非home下的其他页面只显示一个.MD文件....不知主题是否支持随意新建一个页面放入多个文章？

**Comment by iissnan** [comment]
看起来不像是主题能处理的问题

**Comment by xiaomeixw** [comment]
@iissnan 貌似从知乎上的反馈，都认为这个是不是主题所能支持的...
http://www.zhihu.com/question/33324071   
知乎用户，复杂世界的冗余变量  所提供的方法，不能达到点开新建的页面后，和home页一样的展示效果，反倒提供的是和归档页同样的显示方式。希望新建的页面能提供和home主页一样的展示效果。
所以比较困惑...

**Comment by iissnan** [comment]
创造力无限~  确实通过 Alias 分类的方式可以做到。

如果你需要与 Home 页面一样的显示效果，可以尝试将 `source\layout\category.swig` 文件删除掉。
这样当请求分类时就会自动 fallback 到 `index.swig` 模板，也就是首页的展示形式。

**Comment by xiaomeixw** [comment]
@iissnan 谢谢iissnan的解答，我将尝试后，给予反馈...感谢了啊...

**Comment by Andywang089** [comment]
@xiaomeixw 也在寻求新建页面下添加文章的解决办法。知乎上的回答确实是统一在分类的页面了。并不是新建页面下如home页面的效果。

**Comment by Andywang089** [comment]
@iissnan 按你说的方法试了一下，好像不行呢

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
