### ISSUE TITLE
谷歌统计为0

### ISSUE THREAD

**Issue by mousycoder** [iissnan/hexo-theme-next#422]
配置了 google_analytics: UA-68959348-1

![image](https://cloud.githubusercontent.com/assets/6722977/10556510/6e027f98-74b7-11e5-9aa7-bf3e3aaffa78.png)

![image](https://cloud.githubusercontent.com/assets/6722977/10556511/917b81e0-74b7-11e5-93a7-4e45651a8195.png)

不知道什么原因 是墙的问题 还是代码问题

**Comment by iissnan** [comment]
我使用 Google Analytics 的实时数据概览，可以看到数据，说明代码本身应该没有问题

**Comment by mousycoder** [comment]
已经不用谷歌了

**Comment by horacehylee** [comment]
Please ensure your Google Analytics Default URL has a `/` at the end.
![image](https://user-images.githubusercontent.com/16369356/31582261-7d138db8-b1b1-11e7-9ed3-f2e79ee6a568.png)
