### ISSUE TITLE
求和hexo写作方式搭配的markdown编辑器

### ISSUE THREAD

**Issue by mousycoder** [iissnan/hexo-theme-next#423]
大家都用什么编辑器写，预览要求和hexo的markdown引擎差不多，本地的

**Comment by jcf94** [comment]
我用 haroopad ......虽然显示效果不能做到完全一样

**Comment by Acris** [comment]
个人在用https://stackedit.io/

**Comment by iissnan** [comment]
StackEdit 看起来不错

**Comment by nirvana6** [comment]
*  用atom和vim(配合vim-pandoc)作为编辑器；
*  用atom的markdown-preview-plus作为简单预览；
*  用hexo的127.0.0.1:4000本地服务器作为终极预览；
*  不存在一劳永逸的解决方案。

**Comment by tonydeng** [comment]
mou

**Comment by lixingcong** [comment]
haroopad 最好用，开源，跨平台

**Comment by mousycoder** [comment]
就用markdownpad2了 简单

**Comment by richdyang** [comment]
MWeb

**Comment by haoweiguang** [comment]
我用的mweb，还挺方便

**Comment by huangzhongzhang** [comment]
只可惜 mweb 不支持 Windows；不过 stackedit 看起来不错。
