### ISSUE TITLE
多说share可以出来，百度share不行

### ISSUE THREAD

**Issue by mousycoder** [iissnan/hexo-theme-next#425]
![image](https://cloud.githubusercontent.com/assets/6722977/10556839/1f5d0a72-74c4-11e5-83e5-d0493f663d9b.png)

需要 duoshuo_shortname和duoshuo_share:true

![image](https://cloud.githubusercontent.com/assets/6722977/10556843/5c026396-74c4-11e5-8b69-1a40343e848b.png)

但是我想 disqus_shortname + 百度分享 组合 貌似百度分享出不来，有人能帮忙下么？

**Comment by iissnan** [comment]
似乎是我去掉了百度分享，可以试试 JiaThis 分享

**Comment by mousycoder** [comment]
恩

**Comment by Nicksxs** [comment]
@iissnan JiaThis没有好看的图标呢
