### ISSUE TITLE
sidebar 如何放到左边

### ISSUE THREAD

**Issue by lengxingsky** [iissnan/hexo-theme-next#427]
sidebar 放到左边怎么改呢

**Comment by iissnan** [comment]
这个涉及的点有点多，一两句话可能解释不清楚。

**Comment by loseblue** [comment]
请问能否修改成可配置左右侧边栏？个人习惯左边侧边栏。谢谢！

**Comment by Ryan724** [comment]
care

**Comment by ivan-nginx** [comment]
@lengxingsky dont understand u, write in English if not solved. If solved, close it please.
