### ISSUE TITLE
swiftype 后台设置的样式无效

### ISSUE THREAD

**Issue by mousycoder** [iissnan/hexo-theme-next#428]
![image](https://cloud.githubusercontent.com/assets/6722977/10558110/7f8ddde0-74f6-11e5-974b-ddfa1bbbd345.png)

是不是代码里规定了搜索样式
![image](https://cloud.githubusercontent.com/assets/6722977/10558116/9e60514e-74f6-11e5-837f-de25ac82e4d6.png)

![image](https://cloud.githubusercontent.com/assets/6722977/10558118/a382c544-74f6-11e5-9489-1bc7e226106f.png)

是不是要修改这里的搜索样式 要改源代码。。

**Comment by iissnan** [comment]
NexT 没有对 Swiftype 搜索结果做任何样式处理，这些都是 Swiftype 本身的样式。

**Comment by mousycoder** [comment]
好了
