### ISSUE TITLE
Mathjax formula convert invalid in specific condition

### ISSUE THREAD

**Issue by waterblas** [iissnan/hexo-theme-next#429]
The following Mathjax conversions are right:

$$ \sum\limits_{n=1}^{N} x^n $$

$$ a_{t_i} $$

but they join in one formula, it turn wrong, e.g.:

$$ a_{t_i} = \sum\limits_{n=1}^{N} x^n $$

**Comment by iissnan** [comment]
Sorry, I have on idea about MathJax formula conversion.  It is a MathJax usage issue, not  a theme issue, right?

**Comment by waterblas** [comment]
Thanks, but it work when I use MathJax CDN alone to give an following example. So there may be some kind of conflict in the theme.

```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
</head>
<body>

$$ \sum\limits_{n=1}^{N} x^n $$

$$ a_{t_i} $$

$$ a_{t_i} = \sum\limits_{n=1}^{N} x^n $$

</body>
</html>
```

**Comment by iissnan** [comment]
It seems that MathJax syntax conflicts with Markdown, Please refer to #336.

**Comment by waterblas** [comment]
Yes, I try the convenient ways to solve it:
the origin MathJax:
```
$$ a_{t_i} = \sum\limits_{n=1}^{N} x^n $$
```
I replace `_` that convert  to italic in markdown with `\_` :
```
$$ a_{t\_i} = \sum\limits_{n=1}^{N} x^n $$
```
then the MathJax work out right.
