### ISSUE TITLE
Scheme:pisces主题侧边栏高度不能够自适应

### ISSUE THREAD

**Issue by Doublemine** [iissnan/hexo-theme-next#432]
如图所示：![](http://i13.tietuku.com/b6bff526b631e50a.png)
会发生部分文字遮挡，导致文字显示不完全。

**Comment by emotiony** [comment]
请问如何调出pisces主题呢

**Comment by gaoryrt** [comment]
这个是一开始的那个主题？

**Comment by emotiony** [comment]
默认主题现在变成这样了
![qq 20151020101047](https://cloud.githubusercontent.com/assets/1636616/10596106/e6f99654-7712-11e5-8e3f-4b8520d6b045.png)

**Comment by iissnan** [comment]
Pisces 还在开发中

**Comment by Doublemine** [comment]
@iissnan 好吧，期待更多功能。很乐意测试这个新主题

**Comment by iissnan** [comment]
@Doublemine OK. Nice.

**Comment by Doublemine** [comment]
@iissnan 增加一个阅读次数显示的小功能满足一下小小的虚荣心如何？这里是预览[](http://notes.xiamo.tk/)

**Comment by Doublemine** [comment]
@iissnan 增加一个阅读次数显示的小功能满足一下小小的虚荣心如何？这里是预览[http://notes.xiamo.tk/](http://notes.xiamo.tk/)

**Comment by iissnan** [comment]
@Doublemine 是用第三方服务吗？

**Comment by Doublemine** [comment]
使用的[https://leancloud.cn](https://leancloud.cn)提供了Javascript的开发SDK的服务，自己写了一个JS与leancloud后台交互，后台像这个样子![](http://i13.tietuku.com/4fca4d03f60ea728.png),算是第二方的吧。。

**Comment by Doublemine** [comment]
@iissnan 免费用户100万次响应请求每个月，个人博客应该够用了。

**Comment by iissnan** [comment]
:+1: 牛逼。意思是要使用 leancloud 自己搭建一个统计服务？

**Comment by Doublemine** [comment]
@iissnan 就是这个想法，浏览数据迁移貌似也比较方便呢

**Comment by lixingcong** [comment]
是在_config.yaml里面加入这句吗？

	Scheme:pisces

我下载的release 0.4.5.2加了这句，还是没开启pisces，编译报错。
