### ISSUE TITLE
Remove use_motion option

### ISSUE THREAD

**Issue by iissnan** [iissnan/hexo-theme-next#435]
Option `use_motion` is introduced in NexT 0.3.0. In this version, NexT just tries to do some experiment on motion design. In the subsequent releases, NexT still has some drawbacks caused by motion, so this option remains. Until [this commit ](https://github.com/iissnan/hexo-theme-next/commit/ef68830dd08a1261860afe980d6155442064fa31), I have rewritten motion related scripts to improve performance. 

I believe the performance of motion is now much better than previous releases and I think it is the time to remove the `use_motion` option. Moreover, I could focus on improving motion design other than maintaining fallback scripts everywhere.

If you have any question or concern about this changes, please comment or fire a new issue. Thanks.

-------

选项 `use_motion` 在 NexT 0.3.0 版本中引入，当时 NexT 试水一些动画效果。在后续的版本中，这些动画效果有一些性能上的问题，所以这个选项一直保留。为了解决这个问题，我重写了 动画相关的部分脚本，详细可以参看 [这个提交](https://github.com/iissnan/hexo-theme-next/commit/ef68830dd08a1261860afe980d6155442064fa31)。

在这之后，我相信动画的效果会比之前好，同时我也在考虑将 `use_motion` 移除掉。有理由相信，花费解决动画的问题比维护候选方案更为可取。

如果你有任何问题或者担忧，请在此 issue 下留言，或者新开 issue。谢谢

**Comment by geekrainy** [comment]
有个问题，在本地预览的时候，侧边栏打开的动画非常流畅，没有卡顿。但是当部署后打开侧栏时前几下会有明显的卡顿，然后也会变得流畅，是什么原因呢？

**Comment by iissnan** [comment]
猜测跟资源（比如图片）的加载速度有关系，动画是在 DOM ready 之后即开始执行。浏览器同时处理资源加载，排版及绘画，再加上动画，浏览器可能在不停的重排、重绘。

本地资源加载比较快，网络资源加载比较慢。简单来说，本地重排、重绘的频率可能低于网络。猜测如此。

**Comment by geekrainy** [comment]
谢谢解答！目前的字体图标采用新的Font Awesome。若库中没有的图标就无法显示。侧栏的Social链接有些有图标，有些没有有点维和呢！>_<

**Comment by iissnan** [comment]
嗯，这是比较麻烦的问题。 大多数 Icon Font 都未包含完整的 brand icons，FontAwesome 算是比较全的。目前还没有很好的解决方案。
