### ISSUE TITLE
图片的captio消失了

### ISSUE THREAD

**Issue by nirvana6** [iissnan/hexo-theme-next#436]
我一周以前开始使用Next作为我的hexo主题。今天更新了一下next主题，发现以前正文中图片的caption消失了（参见 http://bitwan.science/2015/10/21/ch2-1-9-Changing-the-case-geometry/ ）。

当我换回hexo默认主题landscape时，caption显示正常：
![selection_047](https://cloud.githubusercontent.com/assets/2957421/10631236/15757d3e-780f-11e5-8ad6-8240a82156ac.png)

我想请问工程师，next主题中有没有开启“显示图片caption”的选项？（我用next的主题作为研究报告的皮肤，caption用于正文中的引用指示——这是一个非常重要的功能）。

谢谢。

**Comment by iissnan** [comment]
在最近的一个修改中，对图片的 caption 做了调整。简单来说如下：

```
![Alt text](/path/to/img.jpg) 这种不会自动带上 caption
![Alt text](/path/to/img.jpg "Optional title") 这种会
```

详细见 [Pull Request 430](https://github.com/iissnan/hexo-theme-next/pull/430)。

------

如果嫌第二种写法比较麻烦，你可以更改 `source/js/fancy-box.js` 中，找到 `var imageTitle = $image.attr('title');` ，将其中的 `title` 改成 `alt` 即可。不过每次更新，都需要手动再改一次。

**Comment by nirvana6** [comment]
我选择第二种写法。http://bitwan.science/2015/10/21/ch2-1-9-Changing-the-case-geometry/  中的caption已经正常显示。

第二种写法比hack `source/js/fancy-box.js`好。因为用`title`作为caption比`alt`作为caption更加自然，也符合html的语义的规定。

谢谢。

**Comment by iissnan** [comment]
是一个 bug，请以 #437 为准。

**Comment by iissnan** [comment]
这个我先关闭掉了，Sidebar 无法自动展开在 #437 中跟踪。
