### ISSUE TITLE
sidebar 不能自动展开了

### ISSUE THREAD

**Issue by linguochi** [iissnan/hexo-theme-next#437]
之前用 tag v0.4.4 是可以的，现在更新到v.0.4.5.2就不行了。

**Comment by linguochi** [comment]
发现把触发时间搞长一点就可以了。

**Comment by iissnan** [comment]
谢谢反馈，已确认

**Comment by iissnan** [comment]
已修复。

如果你是通过下载 Release 的方式更新的，请等待 v0.4.5.3 版本。如果是 clone 的方式，可以现在就更新 master 分支最新的 commit 。

**Comment by nirvana6** [comment]
work perfectly !
