### ISSUE TITLE
主题头部 文章间隔 侧边栏

### ISSUE THREAD

**Issue by liuxudan** [iissnan/hexo-theme-next#44]
主题头部 文章间隔 侧边栏 能否参考和借鉴点这个主题http://xiu.160.me/?theme=navy
还是要谢谢作者。

**Comment by iissnan** [comment]
NexT 将在 0.4.0 中新增一个 紧凑版本，或许可以满足你需求 ：）

**Comment by liuxudan** [comment]
谢谢

**Comment by iissnan** [comment]
加了一个 版本，看看是否可以满足你的需求：[预览](http://notes.iissnan.com)

**Comment by liuxudan** [comment]
谢谢

**Comment by liuxudan** [comment]
很棒 真的很棒。
