### ISSUE TITLE
post和page中的代码高亮风格不一致问题

### ISSUE THREAD

**Issue by tonydeng** [iissnan/hexo-theme-next#440]
我在theme/next/_config.yml中配置了代码高亮为`night bright`。这个配置在post中是没有问题的。

但是我在page中也想加入代码的时候，却发现page中的代码高亮是`normal`。

不知道，是有别的设置方法吗？还是一个bug？

**Comment by iissnan** [comment]
是一个 Bug。多谢反馈，已修正，请更新到 master 分支最新的 commit。

**Comment by tonydeng** [comment]
哈哈，谢谢了，更新的真是迅速啊。

已经验证过了，没有问题，这个issue可以关闭了
