### ISSUE TITLE
主题的文章显示时的动画怎么去掉

### ISSUE THREAD

**Issue by giscafer** [iissnan/hexo-theme-next#441]
点击看文章感觉因为动画效果有点慢，像是网络不好，加载慢的样子，想去掉。

**Comment by iissnan** [comment]
修改主题配置，找到 use_motion 更改为 false

**Comment by giscafer** [comment]
动画时间播放快些在哪改，就是需要动画的时候，速度再快点

**Comment by nirvana6** [comment]
建议工程师能够在保留“动画”的同时，可以给出选项，让动画播放的稍微快一些。

**Comment by iissnan** [comment]
@giscafer `source/js/motion_global.js`  搜索 `duration`  和 `stagger`

**Comment by iissnan** [comment]
@nirvana6 正有此意。原本打算去除 `use_motion` 这个选项。

**Comment by giscafer** [comment]
嗯。谢谢

**Comment by habren** [comment]
@iissnan 将motion设置为false后，sidebar无法自动显示，这个问题应该如何解决

**Comment by giscafer** [comment]
@habren 去年有这问题，新版还没解决？？？我把动画去了

**Comment by habren** [comment]
@iissnan 更把主题更新到最新版，motion设置为true，sidebar可自动显示，但motion设置为false后，sidebar就不会自动显示了

**Comment by gecece** [comment]
还是没有修复吗，我刚刚pull最新代码，motion设置为false，sidebar还是不会自动显示。

**Comment by zhoujiealex** [comment]
同问 啥时候 可以修复 关闭动画的同时 还能保证侧边栏 自动弹出

**Comment by r12f** [comment]
同求这个功能，个人不太喜欢太多的动画，只是希望能尽快把页面显示出来。

**Comment by mapan2020** [comment]
同求

**Comment by francs** [comment]
同求这个功能，文章页面打开不希望有动画，如何设置？
