### ISSUE TITLE
pandoc图片的caption出现了两次

### ISSUE THREAD

**Issue by nirvana6** [iissnan/hexo-theme-next#443]
## 工作环境

* 我使用hexo-renderer-pandoc作为我的markdown渲染引擎；
* pandoc插入图片的语法是`![Geometry of the Walls](/img/changedGeometry.jpeg "Fig. Geometry of the Walls")`；
* 在 #436 中，按照您的建议，在 `source/js/fancy-box.js` 中，找到 `var imageTitle = $image.attr('title');` ，将其中的 `title` 改成 `alt`。（因为对于`block`形式的`image`，`pandoc`将`alt`作为`caption`，而无法将`title`作为`caption`）.

## 症状

* **使用next主题**：如网页 http://bitwan.science/2015/10/22/ch2-1-9-Changing-the-case-geometry/ 所示，所有的图片的caption都出现了两次。下图的蓝色方框标出了多余caption：

![next](https://cloud.githubusercontent.com/assets/2957421/10682754/6cd49b6a-796c-11e5-83f2-7fd2ae67199c.png)

* **使用hexo默认的landscape主题**：标题渲染正常。如下图绿色方框所示：

![landscape](https://cloud.githubusercontent.com/assets/2957421/10682789/cd581a98-796c-11e5-829d-dbf4fb5d7a3d.png)

## 问题分析

* **同样使用`hexo-renderer-pandoc`作为markdown渲染引擎**：landscape主题的图片caption渲染正常，next主题的图片的caption出现两次。说明`hexo-renderer-pandoc`正常工作；
* **对同一个markdown文档（ http://127.0.0.1:4000/2015/10/22/ch2-1-9-Changing-the-case-geometry/ ）进行处理**：landscape主题的图片caption正常，next主题的图片的caption出现两次。说明我的文档的语法是正确的（前提条件：按照 #436 的建议，将`$image.attr('title')`更改成`$image.attr('alt')` ).

## 初步判断

* 或许是next主题出现了问题。（但是由于我完全不懂javascript，因此没法精确定位问题）。

----------

**Postscript**
 
* 其实插入图片，我用的pandoc命令是`![Geometry of the Walls](/img/changedGeometry.jpeg "Fig. Geometry of the Walls"){#fig:geometry}`，其中最后的`{#fig:geometry}`是`pandoc-crossref`的交叉引用的`label`；
* 可是`pandoc-crossref`的这个`label`不影响pandoc图片命令的解析。我在landscape下也测试过，该交叉引用标记能正常工作；
* 即使我去掉`pandoc-crossref`的交叉引用标记，在next主题中，caption出现两次问题依然出现。

---------
希望工程师能解决这个问题。`Next`的界面和toc等布局非常适合科技文档的写作，如果能够和pandoc的markdown语法更好的兼容，一定能为文档的可读性加分不少。（毕竟，pandoc的markdown语法的表达能力强大的多）

**Comment by iissnan** [comment]
是 NexT 的问题。先给出解决方法：

1. 不用修改 `source/js/fancy-box.js`
2. 加一个样式来控制 pandoc markdown 所生成的 caption

----

NexT 使用 JavaScript 来检测文章里的图片。如果图片带有 `title` 属性，就会自动生成一个 `caption`（就是灰色字体带下划线的那个）。然后，pandoc markdown 也会自动给图片生成一个 caption，所以同时出现了两个。

在这种情况下，我建议使用 pandoc 生成即可，不用指定 "Optional title" 以避免 NexT 的自动生成。意即：

```
![alt text](image-path)
```

--- 

我将现在自动生成的 caption 的样式应用到 pandoc markdown 生成的那个上就可以了。

**Comment by nirvana6** [comment]
@iissnan 我照你的方法，去掉了"Optional title"，确实只有一个标题了（就是pandoc markdown生成的那个）——但是现在的caption不如以前的美观，也不能居中对齐了。

我是不是等你"将自动生成的caption的样式"修改好以后，我这边`git pull`更新一下就好了？

**Comment by iissnan** [comment]
我还没改 😅

**Comment by nirvana6** [comment]
@iissnan  没事儿，别有心理压力。我这边可以给我的开题报告写算例～ 不急。

**Comment by iissnan** [comment]
OK 了，更新下试试看

**Comment by nirvana6** [comment]
@iissnan yes! Well done ! work perfectly! 

需求响应得太快了～～

**Comment by nirvana6** [comment]
@iissnan 如果说还有什么缺憾的话，就是在网页中放大图片观看的时候，预览中没有了下面的caption提示。不过我可以接受，现在这样已经不错了。

**Comment by nirvana6** [comment]
其实我觉得NexT实现图片的caption的业务逻辑这样可能比较恰当：

* 如果`![alt](/path/to/img "optional title")`中没有`optional title`，则使用`alt`作为str_caption；
* 如果有`optional title`则将其作为caption的字符串str_caption（而放弃`alt`字段，将控制权交给网页编辑）；
* 将得到的str_caption作为图片的caption，进行渲染。

我直觉上感觉这种方式可以保留NexT默认的“以`Option title`作为caption”的方法，又能兼容pandoc的做法。

虽然我觉得pandoc用alt作为caption不太合理，但是如果想要完美地在“放大预览”中也显示pandoc的caption，也只能这样了。

------
当然更加彻底地方法是，只用`alt`来生成图片caption，与pandoc保持一直。这样就走回头路了。

唉，忽然想起了“中行独复”……

**Comment by iissnan** [comment]
实际上，NexT 是在页面渲染完成 ** 之后 **，使用 JavaScript 获取页面的图片，并根据图片自身的属性来决定是否加上 caption。也就是说，这种方式只能根据图片是否带有 `title` 来判断是否有 caption。对于写作者来说，利用这点就可以设定图片是否需要 caption。

然而不同的 markdown 解析器在解析 `![](/image)` 代码的时候生成的格式并不一直，例如此 issue 中，pandoc makrdown 解析器会使用图片的 alt 属性来生成一个 caption。这个 caption 是独立于图片的，NexT 自动处理的方式未能感知图片是否有额外的 caption（其实是可以感知的到，但是这样写太过于具体，下次你再换一个 markdown 解析器很有可能还会出问题），这就导致了两个 caption 同时存在的问题。

所以，你提到的业务逻辑还是会导致两个 caption 的存在：

1. NexT 生成的
2. pandoc markdown 生成的

**Comment by iissnan** [comment]
所以针对这个问题，比较好的方案就是使用 pandoc markdown 生成的 caption 即可（因为这个没法改），然后禁用掉 NexT 自动生成的功能。唯一的缺陷就是你所提到的，在图片 zoom in 后并不能显示 caption（因为没有经过 NexT 的处理）。

**Comment by wylu** [comment]
请问这个问题现在已经解决了吗，我这里出现了同样的问题。

![DeepinScreenshot_select-area_20190604102247](https://user-images.githubusercontent.com/19390318/58846708-c0e45180-86b2-11e9-851e-5c135234b15e.png)

```
hexo: 3.8.0
next: 7.1.0
```

**Comment by stevenjoezhang** [comment]
@wylu 请使用新版：https://github.com/theme-next/hexo-theme-next
