### ISSUE TITLE
如何添加百度统计啊？

### ISSUE THREAD

**Issue by zhujun2730** [iissnan/hexo-theme-next#444]
加了这个 baidu_analytics:  还是没有

**Comment by iissnan** [comment]
使用的统计 ID 是否正确，可以在 [NexT 文档](http://theme-next.iissnan.com/third-party-services.html#百度统计) 那确认下百度统计的 ID 是什么鬼

**Comment by zhujun2730** [comment]
我在_config.yml 加了这句话 baidu_analytics: 4c4d16253de7878425f9c3c37a 还是不行啊，还要把百度统计的JS代码复制到什么地方吗？

**Comment by iissnan** [comment]
似乎你配置了两个？

![20151023152415](https://cloud.githubusercontent.com/assets/32269/10686785/4299257c-799a-11e5-91b6-ef67e88529ee.png)

**Comment by Fedhaier** [comment]
想问一下楼上解决了没有，同样遇到这个问题了。

**Comment by iissnan** [comment]
@Fedhaier 通常是配置的问题，建议你再排查下配置是否正确
