### ISSUE TITLE
关于新的配置项

### ISSUE THREAD

**Issue by geekrainy** [iissnan/hexo-theme-next#445]
可以看到在主题内的_config.yml中增加了原来在站点中的_config.yml关于主题的内容。是否有意将站点的全局配置文件中的选项废除呢？

**Comment by iissnan** [comment]
噢，天哪。我忽略这一点了，主题的配置会覆盖掉站点中的配置。

实际上，我现在把全部的配置都写在 `source/next.yml` 下了 [关于 next.yml](https://github.com/iissnan/hexo-theme-next/issues/328)。这个文件会覆盖掉站点配置文件和主题配置文件中的同名设置。即：

```
站点配置 -> 主题配置 -> next.yml
```

我希望推的是使用 `next.yml`，得更新使用文档了。

感谢反馈，我现在将原先在建议写在站点配置中的选项从主题配置中挪除掉。

**Comment by iissnan** [comment]
已更新

**Comment by vinnyxiong** [comment]
@iissnan 
```
站点配置 -> 主题配置 -> next.yml
```

这句的意思是，对于同名的设置的优先级：next.yml > 主题配置 > 站点配置 吗？

**Comment by iissnan** [comment]
@vinnyxiong 是的
