### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by Phieo** [iissnan/hexo-theme-next#45]
![image](https://cloud.githubusercontent.com/assets/10499704/6652062/7870c64a-ca9b-11e4-9271-6e60689fc7e3.png)
这4个icon上面的为何是正方的矩形?和markdown内的为何不一样。

另外，创建了标签页，但是新建文章设置tags熟性后 标签页内好像没变化，
![image](https://cloud.githubusercontent.com/assets/10499704/6652083/69ddaa3e-ca9c-11e4-8de6-99b51d7c1b9d.png)

这张是从你们的demo截取的，我的问题是这个功能next主题没有提供吗？

**Comment by iissnan** [comment]
1. LOGO 背景默认是直角矩形，不过看来圆角还是蛮受欢迎，我考虑将这个加入默认的样式中：）
2. 标签页面是支持的。新建标签页面的内容应该有一个 `type` 属性，值为 `tags`。例如：

```
title: All tags
date: 2014-12-22 12:39:04
type: "tags"
---
```

**Comment by iissnan** [comment]
对了。LOGO 背景的圆角，只要在 `source/css/_custom.styl` 中加入：

```
.brand {
  border-radius: 4px 15px 4px 15px;
}
``` 

即可。

**Comment by Phieo** [comment]
@iissnan 好的 谢谢啦， 你们的主题是最棒嗒。

**Comment by iissnan** [comment]
:smile: 谢谢
