### ISSUE TITLE
文章目录太多的话，sidebar 不会滚动

### ISSUE THREAD

**Issue by gaoryrt** [iissnan/hexo-theme-next#452]
二级目录太多了，超出了浏览器的高度，这时候滚动页面，sidebar 的高亮就一直往下超出了可见的范围，sidebar 不能滚动，超出的部分就看不到了。

**Comment by tonydeng** [comment]
@iissnan 我也发现同样的问题

**Comment by ChenXiyu** [comment]
同样的问题.

**Comment by SPRING-Z** [comment]
同样的问题

**Comment by iissnan** [comment]
已修复。

TOC 内容溢出的问题早期处理过，方案即是采用上下箭头标识区域可滚动（因为滚动条无法做到所有浏览器的定制，默认的略丑）。这个方案因为脚本的重构导致失效。目前已修复。

另外，改进了 TOC 的显示方式，由原先显示激活标题下所有子标题更改成仅显示激活标题的最近一级子标题，从而保留足够的空间以尽量避免溢出的情况。

**Comment by ChenXiyu** [comment]
成功修改,谢谢

**Comment by gaoryrt** [comment]
谢谢
