### ISSUE TITLE
除了 desktop，tablet，mobile 之外是不是还有其他的大小

### ISSUE THREAD

**Issue by gaoryrt** [iissnan/hexo-theme-next#453]
在尝试修改 mist 主题，`hexo/themes/next/source/css/_schemes/Mist/_header.styl` 中menu标签，添加了`+mobile`,`+tablet` 但是 menu 栏在800*600屏幕下的显示没有改变，不知道这个在哪里修改。
具体看[这个页面](http://gaoryrt.github.io/2015/10/23/what-to-do/)，把浏览器的宽度改变一下，看 `menu` 的改变。

**Comment by iissnan** [comment]
除了 mobile, tablet, desktop 以外，还有一个 desktop-large。不过似乎跟你这个问题没有太大关系。

**Comment by gaoryrt** [comment]
非常感谢，就是这个`+desktop-large()`的定义
