### ISSUE TITLE
博主搬迁到另一台主机上的简单方法

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#456]
虽然这个问题很水，网上很多相关的经验谈。但试过之后都没有得到一个简便的方法。
目前都是在用台式机写，暂且没有多个客户端同时写的需求，所以我的需求变得很简单。很久才搬迁一次，而不是实现异端写博同步的需求。
文章好说，直接md文件全拷过来放在新的机子hexo路径下。问题主要是博客主题，修改了许多个性化的地方，以后难道是直接拷过去就好了？我记得当时是clone仓主的主题，而不是clone自己fork后的主题，会有问题吗？

**Comment by geekrainy** [comment]
我的方案是fork一份，建博主的远程分支，跟随更新。自己处理合并冲突。自己对主题的配置都还在，如果要在另一台电脑新建的话直接clone自己的fork版本。另外可以直接在hexo目录建立git仓库，推送到私有仓库。这样只需在新电脑上 npm install hexo-cli -g  ，然后 clone 私有仓库 clone 主题，最后npm install。一切OK。

**Comment by luodaoyi** [comment]
博主有没有用cdn啥的 我的 [github page](http://luodaoyi.com) 访问好慢

**Comment by zhaoweiwang** [comment]
@luodaoyi 没有。访问了你的主页，感觉并不慢

**Comment by luodaoyi** [comment]
这个我说一下 其实很简单具体看这里：[多主题切换](http://luodaoyi.com/2015/10/31/changehexo/)

**Comment by zhaoweiwang** [comment]
@luodaoyi 你的博文，一二级标题没有区别。建议写成Step1-N模式，毕竟是教程，步骤清不清晰，具不具体很重要。#非常感谢提供了一种思路，只是看不太明白而已

**Comment by luodaoyi** [comment]
@zhaoweiwang 额 我就是两分钟写了下  回头我详细编辑下

**Comment by luodaoyi** [comment]
好了我重新编辑了http://luodaoyi.com/2015/11/04/auto-github-pages/

**Comment by Kermit95** [comment]
关注，ubuntu挂了好多次，每次博客都要来回复制

**Comment by fangd123** [comment]
@geekrainy 我用的也是你的方法，不过感觉还是稍微有点麻烦，可能要加一个持续集成啥的。。
