### ISSUE TITLE
归档和首页的文章列表间距缩小方法？

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#458]
RT

**Comment by ohmycloud** [comment]
同问, 首页中的文章**之间**的间距太大了

`//  In Muse scheme, margin above and below the post separator
$post-eof-margin-top          = 20px  //  or 160px for more white space
$post-eof-margin-bottom       = 20px  //  or 120px for less white space`

是不是 Must 主题才可以

**Comment by ivan-nginx** [comment]
@zhaoweiwang dont understand u, write in English if not solved. If solved, close it please.
