### ISSUE TITLE
手机浏览NexT.Mist主题下的代码框里行号显示问题

### ISSUE THREAD

**Issue by isudox** [iissnan/hexo-theme-next#459]
PC上Mist主题渲染的代码狂行号显示正常，但手机端浏览就会有问题

**Comment by iissnan** [comment]
是什么手机？ 方便的话，把那段代码也提供一下

**Comment by isudox** [comment]
Nexus6 Chrome浏览器

markdown文件里的代码
```javascript
// example1.js
var vim_fan = true;
var emacs_fan = false;
function judge() {
    if (vim_fan && emacs_fan) {
        alert("You must be burned!");
    }
}
```

**Comment by gaoryrt** [comment]
ios 是这样的，safari 的`响应式设计`也看得到 
![屏幕快照](http://ww2.sinaimg.cn/large/a243ad6cjw1exengvthaxj20dw0iy411.jpg)

**Comment by HuberyLee** [comment]
最新的版本貌似是有这个问题，不光只在移动端行号与代码重叠的问题，在PC上有些代码也无法识别，没有行号 [http://www.huberylee.cn/2015/10/20/GNU-C常用扩展/](http://www.huberylee.cn/2015/10/20/GNU-C常用扩展/)

**Comment by iissnan** [comment]
@HuberyLee 你这个问题似乎跟 `highlight.js` 的渲染有关系，试试给那些行号不正确的代码指明代码块使用的语言试试

**Comment by gaoryrt** [comment]
感觉是代码块的 `+mobile()` 解析问题

**Comment by HuberyLee** [comment]
@iissnan 我不知道如何指定代码块使用的语言，还请指点一二，谢谢！

**Comment by isudox** [comment]
@HuberyLee 
>```java
>```

**Comment by maonx** [comment]
使用bash语言 确实也有这个问题 ，手机下行号要重叠的

**Comment by MBL-Quincy** [comment]
我的解决方法是将 `highlight.styl` 文件中把第 `54` 行的 `@line-number` 中的 `padding: 20px` 改为 `margin: 10px `。目前显示正常。也算是一个土方法吧。这个文件的具体路径是 `/next/source/css/_common/components`。

**Comment by lsl233** [comment]
请问 next.mist主题 怎么设置，我查了好久，都没关于mist的东西

**Comment by MBL-Quincy** [comment]
稳定版的主题里，`highlight.styl`文件在`next/source/css/_common/_vendor/highlight`目录下。第`75`行开始有关`line-number`的内容。
<img width="322" alt="2015-12-06 21 16 20" src="https://cloud.githubusercontent.com/assets/13364377/11613514/bdf00290-9c5e-11e5-9730-af069946a4cc.png">

**Comment by zhangjh** [comment]
@MBL-Quincy 我试了你的方法不行，我的方法是修改custom.styl (路径：source/css/_custom)
增加
.code {
    padding-left: 20px !important;
    background-color: black;
}

**Comment by bluestein** [comment]
if your theme is NeXT-Pisces, modify the file:
`themes\next-pisces\source\css\_common\components\highlight\highlight.styl`
@line54
**padding-right: 20px** -> **padding-right: 28px !important**

**Comment by ykqmain** [comment]
手机上所有代码行号都跟第一个字符重叠

**Comment by stevenjoezhang** [comment]
这个问题似乎在
https://github.com/iissnan/hexo-theme-next/commit/1985b7ecced0df4cfe2d9cf6337b40040d1ebf60#diff-ddaaf61bc40a2d092db6ddb0715dbde0
修复了
