### ISSUE TITLE
draft中的tags和categories 的将会被记录到tags和categories的数量上

### ISSUE THREAD

**Issue by ChenXiyu** [iissnan/hexo-theme-next#469]
如果我的draft里面有新的tag或者categories,那么在我还未发布draft之前,tags的数量和categories的数量将会加上他们.
比如:
我原本有16个tags,1个categories,
我的draft里面增加了3个tags,和1个categories,但是该draft还未发布.在渲染出来以后,点击tags/categories页面,将会看到数量统计上出现了19个tags/2个categories,但是实际只是显示了16个tags/1个categories,
不是大bug,但还是希望有时间能修改一下.谢谢.

**Comment by iissnan** [comment]
这是 Hexo 的 bug。

**Comment by ChenXiyu** [comment]
好吧,谢谢
