### ISSUE TITLE
description 会有两个，一个是主站的介绍，一个是自动截取的

### ISSUE THREAD

**Issue by SPRING-Z** [iissnan/hexo-theme-next#470]
这样会造成搜索引擎收录的时候文章都是主站的介绍

**Comment by SPRING-Z** [comment]
<meta name="description" content="胡编一通，乱写一气。猴赛雷。" />

<meta name="description" content="NexT 主题 快满一周岁了，值此之际，碎碎念一下（没有干货）。正如我在 V2EX 分享 时的介绍一样，NexT 的前身叫做 Notes。在做 Notes 主题的时候，基于当时的需求出发点，从好听上来讲是简洁，不好听就是简陋（真直接，脸红）。

**Comment by iissnan** [comment]
感谢反馈，已修正。
