### ISSUE TITLE
Feature Request: Upvote/Downvote support

### ISSUE THREAD

**Issue by hackjustu** [iissnan/hexo-theme-next#471]
I'm not sure whether it is possible to add the **upvote/downvote**(like stackoverflow) support in Hexo, since it only generates static files.  But it would be cool to have this feature if we could utilize some third party service.

**Comment by iissnan** [comment]
Unfortunately, it is impossible to do that in Hexo. And I don't know if there is a service provider that provides this feature. 

Any idea about it?
