### ISSUE TITLE
有没有办法只改变首页网址？

### ISSUE THREAD

**Issue by flashlab** [iissnan/hexo-theme-next#472]
我想把主页网址改成类似`abc.com/blog`，但其他链接照旧，即其他网页路径不变。如果只把站点配置改成
```
url: abc.com
root: /blog
```
生成的所有网页就都在子路径下了。求问有没有什么好办法呢？

**Comment by iissnan** [comment]
意思是：首页是 `abc.com/blog`，子页面是 `abc.com/:year/:month/:day/:title` 这样的路径结构？

是个比较奇怪的场景。

**Comment by flashlab** [comment]
恩，是有点怪...本意是想修改根域名页面（把博客首页挪到子域名）但是不改动其他网页目录结构，不知道可不可行。

**Comment by iissnan** [comment]
使用 Hexo 的 alias 试试。但默认的首页估计要手动删除。

**Comment by flashlab** [comment]
多谢建议:)
