### ISSUE TITLE
首页隐藏部分文章

### ISSUE THREAD

**Issue by imyip** [iissnan/hexo-theme-next#474]
首页隐藏文章 在 Post 里新增 `show`
然后通过`hide`控制,这样可以加上去吗?

我目前就这样做,看有没有更好的办法...

{% if post.show !== 'hide' %}
    {{ post_template.render(post, true) }}
{% endif %}

**Comment by iissnan** [comment]
确实有一个其他的方法，这个也够用。

是否仅在首页隐藏，如果选择了 category 或者 tag，对应的页面也会展示出来。

**Comment by iissnan** [comment]
另外，把 `show` 这个字段改名为 `visibility` 吧。

```
show: hide
```

感觉很奇怪。

**Comment by imyip** [comment]
@iissnan 对的,仅在首页隐藏.

**Comment by iissnan** [comment]
@imyip 那 OK。鉴于这个需求不是普遍的，所以建议你自定义下就行。

**Comment by imyip** [comment]
@iissnan 好得,谢谢.

**Comment by forwardkth** [comment]
首页隐藏文章 在 Post 里新增 show
然后通过hide控制,这样可以加上去吗?

我目前就这样做,看有没有更好的办法...

{% if post.show !== 'hide' %}
{{ post_template.render(post, true) }}
{% endif %}

/////////////////////////////////////////////////////////
具体是在哪个配置文件或者script里写呢？
