### ISSUE TITLE
Pisces站点首页评论数不显示

### ISSUE THREAD

**Issue by guovz** [iissnan/hexo-theme-next#475]
如题，效果如下：
![bug](https://cloud.githubusercontent.com/assets/4530355/10839813/0f220352-7f13-11e5-8e13-dfab42bce424.png)

看了一下作者的代码:
```swig
{% if page.comments%}
    {% include 'comments/duoshuo.swig' %}
    {% include 'comments/disqus.swig' %}
{% endif%}
```

首页不能存在comments变量，所以评论的script代码不会被加载，我将代码修改为:

```swig
{% if page.comments || is_home() %}
    {% include 'comments/duoshuo.swig' %}
    {% include 'comments/disqus.swig' %}
{% endif%}
```
首页评论数就显示成功了。

但是看到作者的博客上评论数是显示正常的，不知道是自己使用问题还是代码的BUG，希望作者帮忙看看尼，thanks

**Comment by iissnan** [comment]
嗯，是个 bug，请发一个 PR 给我，谢谢

**Comment by iissnan** [comment]
嗯，原来我已经 Fixed 这个问题了（ 5b666c ）。再次看了下，除了多加一个 多说 script 的请求以外，代码是可以正确运行的

**Comment by Doublemine** [comment]
我居然才发现这个bug，而且是每页文章评论数随机一个不显示。。

**Comment by iissnan** [comment]
@Doublemine  除了多加载一次多说的 script ，本身应该没有什么问题。comments 的控制代码有点分散，我觉得可以重构一下。

**Comment by Doublemine** [comment]
@iissnan 我也没看出来代码本身有什么问题，重构代码期待Pisces正式发布吧:)

**Comment by dzhai** [comment]
我的评论数也不显示 404 找不到对应的class
Error:101 Class or object doesn't exists.
