### ISSUE TITLE
fancybox能否正常使用？

### ISSUE THREAD

**Issue by makerdiary** [iissnan/hexo-theme-next#48]
halo，
主题配置好像有fancybox这一项，当实际使用fancybox的效果，点击图片没反应，不出现图片框，不知是不是我哪里设置有问题，求指导！！！

**Comment by iissnan** [comment]
Fancybox 目前只针对 Gallery 有效。

`GalleryPostExample.md`，指定 `photos` 属性。

```
title: "GalleryExample"
date: 2015-03-16 08:50:53
tags:
photos:
- http://hexo.io/logo.svg
---
```

**Comment by phyzhj** [comment]
"Fancybox 目前只针对 Gallery 有效。"是什么意思

**Comment by iissnan** [comment]
简单来说，就是 post 的 [Front-matter](http://hexo.io/docs/front-matter.html) 里包含 `photos` 字段时，Fancy 才会生效。

**Comment by liuxudan** [comment]
fancy可以生效  但是文章里图片太小了。 如何解决？
http://eurusd.cn/2014/2014-04-03/

**Comment by baininghan** [comment]
@iissnan @liuxudan 我也是同样的问题，[效果](http://baininghan.com/2015/03/29/c3p0/)

**Comment by iissnan** [comment]
@nullsheng 提交的一个 PR 更改 Gallery 展示的效果，我感觉还可以。https://github.com/iissnan/hexo-theme-next/pull/150
