### ISSUE TITLE
Pisces手机端浏览博文正文部分响应式问题

### ISSUE THREAD

**Issue by D12mnit** [iissnan/hexo-theme-next#480]
正文宽度仍然有问题，会超出手机屏幕无法正常浏览

**Comment by D12mnit** [comment]
自己把
.content-wrap{
    width: auto;
  }
改为了
.content-wrap{
    width: 100%;
  }
就没有问题了。。不知道是不是这个原因

**Comment by iissnan** [comment]
嗯，你的改法是对的。
