### ISSUE TITLE
首页文件部署问题

### ISSUE THREAD

**Issue by dzhai** [iissnan/hexo-theme-next#482]
使用Pisces主题生成的index.html 有50多k 但是在部署的时候 就变成10多k了,首页只有一篇文章的信息了

**Comment by iissnan** [comment]
`hexo s` 本地预览的时候是否有此问题？

另外，换成其他的 scheme 是否有这个问题？

**Comment by loveNight** [comment]
楼主搞定了吗？我也遇上这问题了。
昨晚还能正常用的，今天就不行了。

`hexo s`正常，但是public 文件夹下的index只有16K，里面只显示最新的一篇文章 。

**Comment by loveNight** [comment]
我摸索出了一个解决办法。这个问题发生在`hexo clean`后第一次`hexo g`，此时生成的index.html只显示最近的一篇文章。再运行一次`hexo g`就能生成正常的index.html了。

什么原因我也不清楚。

**Comment by dzhai** [comment]
最近没时间搞，直接修改的github上发布的index.html,把本地预览的内容直接copy

**Comment by woodwm** [comment]
我也遇到这个问题，有时新发布的文章在首页一直不显示。

**Comment by DemoJameson** [comment]
同有这个问题，反复 hexo g -d 解决了

**Comment by darcyWang** [comment]
Me too，但是我反复hexo g和hexo d没有用的，还是木有效果

**Comment by iissnan** [comment]
`hexo clean` 以及 `hexo d -g`，我一直这么使用，没有什么问题

**Comment by Cering** [comment]
同有这个问题，也是反复多次`hexo g`解决的，希望能排查下问题：）

**Comment by alviezhang** [comment]
同样的问题，第一hexo g首页信息不正常，需要再次运行hexo g

**Comment by yeziahehe** [comment]
同样遇到这个问题

**Comment by ForeverQ** [comment]
今天在使用 Pisces 的 scheme 时也遇到这个问题，必须反复 ```hexo g``` 后回归正常

**Comment by yqfang** [comment]
同样遇到这个问题，应该是markdown语法有些问题，但这种报错方式有点。。。，希望改进一下

**Comment by xwjdsh** [comment]
一样的问题，重复hexo g解决。

**Comment by Norcy** [comment]
同一个问题，hexo clean后连续输入2次hexo g解决

**Comment by Ethan-Zhang** [comment]
出现问题时，请查看`hexo s`和`hexo s -s`的结果是否一致

**Comment by wadekun** [comment]
我也刚遇到了这个问题。。

**Comment by xuie0000** [comment]
有谁如何解决了？
