### ISSUE TITLE
为啥生成的文章图片会跑到开头去一份

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#483]
如 http://taoyuanxiaoqi.com/2015/06/04/StraightenFunction/

我的配置如下：
lichaodeMacBook-Pro:blog lee$ hexo -version
hexo: 2.8.3
os: Darwin 14.5.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by iissnan** [comment]
有在 Front-matter 指定 photos 项吗？

**Comment by taoyuanxiaoqi** [comment]
@iissnan  并不知道 Front-matter 是什么 只是使用next主题 改改配置

**Comment by lucasleelz** [comment]
@iissnan  我也遇见这个问题。 请问在哪里设置？

**Comment by taoyuanxiaoqi** [comment]
@iissnan 查了下Front-matter  我的md里面是没有设置photos 的 好奇怪 问题还是存在

**Comment by taoyuanxiaoqi** [comment]
最新版本问题已经解决了 虽然不知道为什么
