### ISSUE TITLE
“2级标题”和“3级标题”看不出来有啥区别啊

### ISSUE THREAD

**Issue by nirvana6** [iissnan/hexo-theme-next#487]
仓主能不能把`3级标题`的字号或样式调整一下，使它与2级标题的区分度大一些呢？(这样能够使文档结构一目了然。）

实际上，在单一文档中，一般区分到3级目录就够了。甚至有一种说法：如果一个文档需要三级以上的题目，那么就说明这篇文章的结构不良。

![selection_053](https://cloud.githubusercontent.com/assets/2957421/10962364/8c44ea8e-83d2-11e5-8fe6-e1d0c09eecc0.jpg)

**Comment by iissnan** [comment]
目前每一级的字体有等差 2px 的大小差别，可能需要将这个差距稍微调整下

**Comment by nirvana6** [comment]
怎么调整？ 在哪里调整啊？

**Comment by ivan-nginx** [comment]
@nirvana6 dont understand u, write in English if not solved. If solved, close it please.
