### ISSUE TITLE
分类功能不完善

### ISSUE THREAD

**Issue by qq40660** [iissnan/hexo-theme-next#488]
点击无效，没有分类列表

**Comment by korvin101** [comment]
手动创建分类页面http://theme-next.iissnan.com/theme-settings.html#分类页面

**Comment by qq40660** [comment]
我发现不是这个原因@korvin101，修改/themes/next目录下的_config.yml,将menu节点下的categories这一项的注释去掉就可以了。

**Comment by korvin101** [comment]
@qq40660 不明白你的意思，我看了你的博客，本来就一个分类都没有，点击分类当然没有分类列表

**Comment by qq40660** [comment]
你看官方演示侧边栏那个分类是不是也点不了就知道了

**Comment by qq40660** [comment]
更正一下，这是设置问题不是功能问题

**Comment by korvin101** [comment]
官方演示没有显示分类栏目

**Comment by korvin101** [comment]
如果是你自己设置问题，就关了这个issue吧。

**Comment by qq40660** [comment]
我的问题是解决了，官方的演示站点可没解决，希望我的经历可以让其它人少走弯路，先关了

**Comment by qq40660** [comment]
我的问题是解决了，官方的演示站点可没解决，希望我的经历可以让其它人少走弯路，先关了

**Comment by korvin101** [comment]
明白了，之前还真没看到，新主题没有根据配置来动态的显示隐藏相应目录
