### ISSUE TITLE
为什么就能只能显示一篇文章列表

### ISSUE THREAD

**Issue by mkitby** [iissnan/hexo-theme-next#490]
发表有多篇文章，主页就只显示一篇，空间用的github pages， http://mkitby.com

**Comment by succlz123** [comment]
碰到同样问题,你可以试下这样
`hexo clean``hexo g``hexo server`看看本地是否正常
正常的话再`hexo g`1次
然后去看下public下的index文件是否正常
问题解决了,不过没明白为啥这样

**Comment by hackjustu** [comment]
请问你的问题解决了嘛？你的博客看上去挺正常的呀

**Comment by succlz123** [comment]
好像还是有问题 每次都必须要`hexo g`2次才正常,我是添加了swiftype后才这样的

**Comment by mkitby** [comment]
我也不知道修改了什么，所以重新清空的仓库，重新安装主题，然后就好了

**Comment by tkggitfk24** [comment]
@succlz123 谢谢，用了你说的方法，hexo g 2次就正常了

**Comment by FrozenYogurtPuff** [comment]
谢谢 遇到同样的问题 用上面的方法解决了
