### ISSUE TITLE
无法应用 Front-matter 的 updated？

### ISSUE THREAD

**Issue by nuomi1** [iissnan/hexo-theme-next#492]
hexo 官方文档中写到 Front-matter 有 updated 参数，但是 next 并没有应用。
在首页里只写着「发表于」，而没有「更新于」，希望增加这个功能。

**Comment by Haocen** [comment]
确实是。这个主题不支持显示文章更新的时间。相应的配置文件中不存在这个变量。

**Comment by magicse7en** [comment]
什么时候可以增加这个功能呢？

**Comment by alex4814** [comment]
+1

**Comment by saccohuo** [comment]
新版里面设置了这个之后，问题可以解决了么？
```
post_meta:
  updated_at: true
```

**Comment by chendaojin** [comment]
为什么我的显示是 “更新于：2017-10-10” 而不是 “更新于 2017-10-10” 呢，多了个冒号

**Comment by AlanLang** [comment]
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
我也是更新于后面会多一个冒号
如果看着不爽可以文件 `_macor/post.swing`  第86行
`<span class="post-meta-item-text">{{ __('post.modified') }}&#58;</span>`
改成
`<span class="post-meta-item-text">{{ __('post.modified') }}</span>`

**Comment by stevenjoezhang** [comment]
请使用新版本：https://github.com/theme-next/hexo-theme-next
已重构有关文章更新时间的逻辑

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x / v7.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
