### ISSUE TITLE
点击分类 分类页面是空的 

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#493]
我的配置如下：
lichaodeMacBook-Pro:blog lee$ hexo -version
hexo: 2.8.3
os: Darwin 14.5.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

如：http://taoyuanxiaoqi.com/categories/
在文章列表里单独点击文章的分类又是好的：
如：http://taoyuanxiaoqi.com/categories/%E6%B8%B8%E8%AE%B0/

**Comment by amoyiki** [comment]
看了你的github上的BLOG_SOURCE。你应该是没在source内创建一个categories文件夹，里面用建一个index.md，type: "categories"。配置文档有说到

**Comment by taoyuanxiaoqi** [comment]
@amoyiki 感谢你的回复！我的github上的BLOG_SOURCE已经过期早就不用了  呃 一会儿我就去把它干掉  本地使用的对应的文件夹和index文件是按照文档用命令生成的

**Comment by taoyuanxiaoqi** [comment]
找到问题了 按照文档用命令生成的index文件里边没有 type: "categories" 加上就好了
