### ISSUE TITLE
多说界面的分享按钮被发布按钮覆盖了

### ISSUE THREAD

**Issue by DemoJameson** [iissnan/hexo-theme-next#494]
登录后才会出现这种状况，博客地址：http://demojameson.com/2015/11/08/publish-ghost-blog/
![image](https://cloud.githubusercontent.com/assets/181192/11026845/34a2feae-86ea-11e5-8ff3-40d8d00ba703.png)

**Comment by luodaoyi** [comment]
这个是你自己多说的设置，你去多说网站的后台设置一下自定义的CSS即可

**Comment by DemoJameson** [comment]
谢谢提醒，的确是我自己多说设置的问题，因为使用了其它的外观
