### ISSUE TITLE
主题 - NexT.Pisces

### ISSUE THREAD

**Issue by non-player** [iissnan/hexo-theme-next#497]
我想知道博主的NexT.Pisces主题是否完成，有木有讨论社区

**Comment by non-player** [comment]
现在好像不能评论了？

**Comment by iissnan** [comment]
NexT 的 Gitter 地址 https://gitter.im/iissnan/hexo-theme-next。

哪里不能评论？

**Comment by non-player** [comment]
嗯嗯，谢谢博主，你的文章是不是把多说评论屏蔽掉了？

**Comment by iissnan** [comment]
没有啊，一直都是开着的

**Comment by non-player** [comment]
喔 ，我看见了 ，在chrom浏览器里面打开是有多说评论的，在QQ浏览器高速模式里面打开是没有的，我看控制台好像 js报错了，在chrom浏览器里面没有报错，谢谢博主解答。

**Comment by iissnan** [comment]
方便截图下报错的信息吗，多谢

**Comment by non-player** [comment]
错误是这个
![Uploading error.jpg…]()

XMLHttpRequest cannot load https://api.leancloud.cn/1.1/classes/Counter. The 'Access-Control-Allow-Origin' header contains multiple values 'http://notes.iissnan.com, *', but only one is allowed. Origin 'http://notes.iissnan.com' is therefore not allowed access.
(index):923 Error:-1 
(index):1 XMLHttpRequest cannot load http://notes-iissnan.duoshuo.com/api/threads/counts.json?threads=2015%2Fsom…isitor%2Cnonce%2Clang&referer=http%3A%2F%2Fnotes.iissnan.com%2F&v=15.11.10. The 'Access-Control-Allow-Origin' header contains multiple values 'http://notes.iissnan.com, *', but only one is allowed. Origin 'http://notes.iissnan.com' is therefore not allowed access.
(index):1 XMLHttpRequest cannot load http://notes-iissnan.duoshuo.com/api/threads/listPosts.json?thread_key=2015…read%2Clog%2CextraCss&referer=http%3A%2F%2Fnotes.iissnan.com%2F&v=15.11.10. The 'Access-Control-Allow-Origin' header contains multiple values 'http://notes.iissnan.com, *', but only one is allowed. Origin 'http://notes.iissnan.com' is therefore not allowed access.
(index):1 XMLHttpRequest cannot load http://s.swiftypecdn.com/install/v2/config/xWSYW1jSW_PiEKgkes91.json. The 'Access-Control-Allow-Origin' header contains multiple values 'http://notes.iissnan.com, *', but only one is allowed. Origin 'http://notes.iissnan.com' is therefore not allowed access.
3content.js:1 The current page is in:	zh-CN


图片上传老失败，对不起 博主

**Comment by non-player** [comment]
这是错误信息

**Comment by iissnan** [comment]
Pisces 已合并到 master
