### ISSUE TITLE
主题 - NexT.Pisces 侧栏头像问题

### ISSUE THREAD

**Issue by amoyiki** [iissnan/hexo-theme-next#498]
在主题 NexT.Pisces 中侧栏头像需要在不能写成`avatar: /images/avatar.jpg` 要改成`avatar: ../images/avatar.jpg`否则点击其他标签（about，tag等）显示不出图片来

**Comment by amoyiki** [comment]
又发现了在翻到文章第二页时候路径还是会错。目前我blog使用图片链接地址。

**Comment by baylin87** [comment]
图片链接地址怎么生成呀？？

**Comment by amoyiki** [comment]
@baylin87 在主题下的配置文件 _config.yml 中配置
> # Sidebar Avatar
> avatar: url地址，推荐把图片放到新浪图床上
