### ISSUE TITLE
移动端导航菜单问题

### ISSUE THREAD

**Issue by tongsucn** [iissnan/hexo-theme-next#499]
手机浏览器中触发导航菜单后，页面会被缩小一点点，并且整体可以左右滑动，做以下修改后bug被fix：

contribute path: https://github.com/tongsucn/hexo-theme-next/commit/d81a52499ffa7575196e63580ce6e703dbc82302

source/css/_common/_section/header.styl

**Comment by geekrainy** [comment]
作此修改后导航栏不居中了。
```css
padding-left: 20px;
```
