### ISSUE TITLE
分页导航到了第二页就没了

### ISSUE THREAD

**Issue by yanxyz** [iissnan/hexo-theme-next#50]
首页正常。到了第二页就没了分页导航，反而每个文章项后有上一文章，下一文章导航。
hexo 版本是 3.0.0
首页是正常的，而且你的博客也是正常的。

**Comment by iissnan** [comment]
能否提供你博客的相关信息。例如 `permalink` 设置， `hexo-generator-index` 等设置？

**Comment by mingmings** [comment]
@yanxyz 看下你的 `permalink` 设置的问题，我之前是按照 `category` ，结果也会出现你这样的情况，改成`year/` 之后就恢复了

**Comment by yanxyz** [comment]
@mingmings  还真的跟你说一样，将 `:title/`，改成 `:year/:title/`

**Comment by mingmings** [comment]
@yanxyz 这个是当时作者提醒我的，可能也和他目前还没有支持 `category` 有关可能，静观期待作者的 4.0 版本吧

**Comment by iissnan** [comment]
因为 NexT 使用了 Conditional Helpers，其中 `is_post()` 这个 helper 在特殊的 `permalink` 设置下工作的不太正常，所以导致一些使用到`is_post()` 的页面表现不正常。

以 `:permalink` 设置为 `:category/:title` 为例。

A: 为什么会出现首页有分页，第二页开始没有分页？
Q: 因为 `is_post()` 会错误的认为第二页 `example.com/page/2` 认为是 `true`，因为这个地址会通过 `:category/:title` 的校验。

A: 为什么在归档第二页开始会出现文章的内容，而不是文章的标题？
Q: `example.com/archive/page/2` 也会被认为是 post 。

**Comment by iissnan** [comment]
这个要彻底解决只能在 Hexo 本身做修改。 Hexo 上有一个 [issue](https://github.com/hexojs/hexo/issues/1088)

**Comment by yanxyz** [comment]
难怪看模板也看不出问题来。默认模板采用另一种方法来判断。
既然这样，这个 issue 我就关了。
