### ISSUE TITLE
当末页只有一篇文章时，刷新末页会影响该篇文章的阅读次数

### ISSUE THREAD

**Issue by zhaoyibo** [iissnan/hexo-theme-next#500]
用的是 Pisces scheme。
跳到最后一页，如果该页只有一篇文章（多于一篇时貌似不会出现这个问题），只刷新该页面（不点到文章里边去），阅读数就会加+1。

刚好作者博客目前的最后一页也是只有1篇博文，可以看一下这是不是个 bug  http://notes.iissnan.com/page/37/

**Comment by Doublemine** [comment]
@zhaoyibo 这是一个文章判断的问题，JS代码会判断当前页面有几个leancloud_visitors的类，如果为1，则认为是进入到了文章中，进行阅读量自增1的操作。暂时还没有想到什么其他方法来替代这个逻辑。请问你有什么好的建议么？

**Comment by zhaoyibo** [comment]
我对前端的东西并不熟悉，目前能想到的是：能否加上是否是 post 页的判断？

我稍微修改了一下 `lean-analytics.swig`：
```
      if ($('.leancloud_visitors').length == 1 && $('.post-nav-item').length > 0) {
        addCount(Counter);
      } else {
        showTime(Counter);
      }
```

`.post-nav-item` 只是我随便找了个，其实还并不能精确判断是否是 post（post 里的这个导航不知能否关闭？还有博主只有一盘博文的情况会导致 count 不累加吧）

**Comment by Doublemine** [comment]
@zhaoyibo 您提出的这种情况还没有经过测试，所以我还不能给出明确的答案。抱歉最近有点忙，您给的方案需要可能我得有时间才能进行测试调试，你可以和NexT作者iissnan沟通下看看能有什么办法确定到底是不是在post页面:)

**Comment by iissnan** [comment]
@zhaoyibo 多谢反馈。

Post 页面有一个具体的 css  类 `page-post-detail`，我想用这个来区分应该可以解决这个问题。

**Comment by zhaoyibo** [comment]
@iissnan 那用这个判断应该就没有问题了:)

**Comment by billjh** [comment]
同样，如果首页（整个博客）只有一篇文章，刷新首页也会影响文章阅读次数。

**Comment by ivan-nginx** [comment]
@zhaoyibo dont understand u, write in English if not solved. If solved, close it please.
