### ISSUE TITLE
markdown里面的"主标题""副标题"显示问题

### ISSUE THREAD

**Issue by liman123** [iissnan/hexo-theme-next#501]
##主标题
###副标题

 在博客里显示的还是这样子, 看不出大小写区分,不支持这个语法吗?

 但是我用Mou的预览功能的话就正常显示了(主标题会明显加粗加大, 副标题就比主标题小一点细一点)

**Comment by chitanda** [comment]
加空格看看
```
## 主标题
```

**Comment by gongjianhui** [comment]
## 与标题之间是要加空格的。
