### ISSUE TITLE
How to highlight bash syntax correctly?

### ISSUE THREAD

**Issue by hackjustu** [iissnan/hexo-theme-next#504]
请问主题使用的markdown engine是什么呢？如何在里面高亮bash或者shell的代码呢？
我尝试过 \`\`\`bash, \`\`\`sh, \`\`\`shell, \`\`\`zsh，但是render出来的结果都不正确... 例子如下图：

![example](http://i.imgsafe.org/609afa3.png)

http://hackjustu.ninja/2015/11/11/Diagnose-Network-Issues-traceroute-and-mtr/

谢谢这个这么棒的主题：）

**Comment by iissnan** [comment]
Markdown 渲染引擎是在 Hexo 设定的，默认的应该是 [marked](https://github.com/chjj/marked)。 代码的高亮，Hexo 使用的是 [highlight.js](https://highlightjs.org/)。我看了下你的文章，确实如你所说的 bash 的代码并未正确的高亮。我觉得这应该是 highlight.js 解析的问题（或者 highlight.js 使用时未正确配置）。

**Comment by hackjustu** [comment]
谢谢哈 我去研究一下怎么配置highlight.js ：）

**Comment by duchengyao** [comment]
最后怎么解决的呀，我的也出现了同样的情况

**Comment by owen8877** [comment]
求解决方案+1

**Comment by tkkcc** [comment]
同问

**Comment by ycfung** [comment]
这个问题还没有解决吗。。。
