### ISSUE TITLE
把所有没有分类的文章自动归类到uncategorized

### ISSUE THREAD

**Issue by hackjustu** [iissnan/hexo-theme-next#505]
能否有个uncategorized的类，自动把没有分类的文章都归到里面呢？

**Comment by meilinz** [comment]
同求这功能。

**Comment by iissnan** [comment]
虽然 Hexo 没有明确提供这个自动归类的功能，不过通过更改 post 默认的 layout 就可以实现。

简单来说，修改站点子目录下的 `scaffolds/post.md`，如下：

```
title: {{ title }}
date: {{ date }}
tags:
categories: uncategorized
---
```

这样当你每次使用 `hexo new title` 的时候，文章默认会归结到这个分类。

**Comment by iissnan** [comment]
对了，这个实现依赖于  `hexo new` 时使用的默认 layout。所以如果你修改了这个默认的 layout（更改了站点配置文件中的 `default_layout` 选项），请为新的 layout 增加 `categories: uncategorized` 即可。
