### ISSUE TITLE
设置sidebar: always，侧栏在文章页反而不展开

### ISSUE THREAD

**Issue by loveNight** [iissnan/hexo-theme-next#509]
在`\themes\next\layout/_scripts/pages/post-details.swig`文件里看到这段代码
```javascript
// Expand sidebar on post detail page by default, when post has a toc.
motionMiddleWares.sidebar = function () {
  var $tocContent = $('.post-toc-content');
  if (CONFIG.sidebar === 'post') {
    if ($tocContent.length > 0 && $tocContent.html().trim().length > 0) {
      displaySidebar();
    }
  }
};
```
if里加上always就能正常显示了。

**Comment by iissnan** [comment]
多谢反馈。应该是结构调整的时候修改到了这个地方

**Comment by duchengyao** [comment]
赞！

**Comment by duchengyao** [comment]
这个什么时候可以解决呀>_<

**Comment by loveNight** [comment]
自己手动解决啊

**Comment by duchengyao** [comment]
if (CONFIG.sidebar === 'post') {
改成
if (CONFIG.sidebar === 'post' || 'always') {
吗？

不太会这个语言＝ ＝

**Comment by loveNight** [comment]
if (CONFIG.sidebar === 'post' || CONFIG.sidebar === 'always')

**Comment by duchengyao** [comment]
么么哒！

**Comment by cinthisime** [comment]
不对，应该这样修改
/source/js/src/motion.js
<code>
    sidebar: function (integrator) {
      if (CONFIG.sidebar.display === 'always') {
        NexT.utils.displaySidebar();
      }
      integrator.next();
    }
</code>
/layout/_scripts/pages/post-details.swig 
<code>
    // Expand sidebar on post detail page by default, when post has a toc.
    NexT.motion.middleWares.sidebar = function () {
      var $tocContent = $('.post-toc-content');

      if (CONFIG.sidebar.display === 'post' || CONFIG.sidebar.display === 'always') {
        if ($tocContent.length > 0 && $tocContent.html().trim().length > 0) {
          NexT.utils.displaySidebar();
        }
      }
    };
</code>

**Comment by kepoon** [comment]
我试了，解决不了，但是，我用我的方法解决了：
在\themes\next\source\js\motion_global.js做如下修改：
    sidebarToggle: function (integrator) {
      sidebarToggleMotion.init();
      integrator.next();  
      if (CONFIG.sidebar === 'always') {
	//  模拟点击一下侧边栏按钮
        sidebarToggleMotion.clickHandler();
      }
    }
解决了！

**Comment by duchengyao** [comment]
@kepoon 这个棒！

**Comment by maoxiangyu** [comment]
@cinthisime 如果按照你这样修改之后打开tags和categories都会弹出sidebar，怎么修改让在这两个页面不弹出

**Comment by iissnan** [comment]
@maoxiangyu 将 `sidebar.display` 设置为 `post` 就不会在那两个页面展示
