### ISSUE TITLE
问一个关于categories和tags的问题？

### ISSUE THREAD

**Issue by fuhaiwei** [iissnan/hexo-theme-next#51]
该主题是否现在还不支持 categories?
hexo 3.0现在是否还不生成 tags/index.html?

**Comment by iissnan** [comment]
Category 还不支持。 `tags/index.html ` 需要手动去生成。

**Comment by WitNesS23** [comment]
小白求教如何手动生成tags/index.html

**Comment by iissnan** [comment]
```
hexo new page tags
```

**Comment by WitNesS23** [comment]
谢谢分享~

**Comment by iissnan** [comment]
已支持 categories，生成方法与 tags 类似。

**Comment by mingmings** [comment]
@iissnan 点赞

**Comment by fuhaiwei** [comment]
原来4.0已经发布了，已经更新，过程如下。
```
$ cd path/to/hexo
$ hexo new page tags
$ hexo new page categories
$ vim source/tags/index.md 
# 添加 type: "tags"
$ vim source/tags/categories.md
# 添加 type: "categories"
$ cd themes/next
# 提前备份好你的_config.yml
$ git pull
```

**Comment by iissnan** [comment]
@fuhaiwei  :+1:

**Comment by soomtong** [comment]
@fuhaiwei :+1:

**Comment by Anoxia** [comment]
@fuhaiwei 多谢

**Comment by zhengda** [comment]
```
$ cd path/to/hexo
$ hexo new page tags
$ hexo new page categories
$ vim source/tags/index.md 
### add line: type: "tags"
$ vim source/categories/index.md
### add line: type: "categories"
$ hexo d -g
```
做完之後產生的 /tags/index.html 裡面沒有顯示出所用的tag...

---
``` bash
node -v
v0.12.4

npm -v
2.10.1

hexo -v
hexo-cli: 0.1.6
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by fuhaiwei** [comment]
运行 hexo new page tags 命令后会产生 source/tags/index.md 这个文件，你要修改这个文件，在里面添加一句话type: "tags"。
类似于这样：

title: "tags"
date: 2015-03-24 08:58:02
type: "tags"
---

然后运行服务器即可访问tags页面了。

在 2015-05-29 06:22:57，"Leon Lin" <notifications@github.com> 写道：

$ cd path/to/hexo
$ hexo new page tags
$ hexo new page categories
$ vim source/tags/index.md 
### add line: type: "tags"
$ vim source/categories/index.md
### add line: type: "categories"
$ hexo d -g


做完之後產生的 /tags/index.html 裡面沒有顯示出所用的tag...

node -v
v0.12.4

npm -v
2.10.1

hexo -v
hexo-cli: 0.1.6
os: Windows_NT 6.1.7601 win32 x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by zhengda** [comment]
有用 hexo new page "tags" 產生 /tags/index.md ，並在 .md 裡加上 type: "tags"
寫的文章裡有使用 tag。
hexo d -g 後產生出的文章結尾有正確顯示 tag ，可是 /tags/index.html 裡沒有顯示所用的 tag 。

是hexo 3.1.1的bug嗎?

**Comment by mingmings** [comment]
@zhengda 如果你的站点实在子目录中，那么你的主题 config 里就 menu 就必须指定到子目录中来

**Comment by iissnan** [comment]
@zhengda 试试重新生成下看看有没有问题：

1. 删除 db.json
1. hexo clean
1. hexo g

**Comment by zhengda** [comment]
嗯... 删除 db.json 再 hexo clean就 Ok 了

**Comment by xjliao** [comment]
@iissnan 搞定  很好 thx

**Comment by xidui** [comment]
已搞定

**Comment by mrwangrj** [comment]
搞定！

**Comment by BlueWinters** [comment]
反复尝试了上面三个步骤之后
1.删除 db.json
2.hexo clean
3.hexo g

还是出现了訪問tags頁面是沒問題的，有問題的是使用的tag沒有顯示在頁面裡！！

**Comment by BlueWinters** [comment]
而且会出现中文乱码的情况：
\source\tags\index.md文件，修改title为中文标签，结果hexo s后，本地访问发现是乱码。。。

**Comment by asleep-tu** [comment]
categories页面访问正常，但是点击详细的分类显示404。
categories文件夹下存在index.html和详细分类的文件夹，且详细分类的文件夹下也有index.html。
这是什么问题

**Comment by zhengda** [comment]
It depends on the support of the theme you used. You will see the lack of support at categories/tags on many thems. For instance, the 'Minos' theme I used just cannot correctly generate tags/index.html, nonetheless, tags/yourtag/index.html works very well...

**Comment by YauLam** [comment]
为什么我按照上述操作，tags页面依旧不显示有哪些tag呢？谁知道是什么原因，麻烦告知

**Comment by MBTimY** [comment]
@YauLam 我按照操作已经可以正常的显示了，要删掉 db.json文件然后clean 然后再  hexo d -g ，就可以了 你在 nexo new page tags 这里的时候 我这里生成出来的index.md文件 生出出来以后我没有进去修改

**Comment by GARENFEATHER** [comment]
I've also fix it by adding type as @fuhaiwei said above
