### ISSUE TITLE
没有添加<!-- more-->标签的时候，不会在首页显示

### ISSUE THREAD

**Issue by duchengyao** [iissnan/hexo-theme-next#510]
突然发现我之前发的文章没有在首页显示，然后添加以后就可以了，为什么呢?

**Comment by iissnan** [comment]
奇怪的问题

**Comment by ghkk** [comment]
同样的问题，但是我加了也不行。第一天的时候不管怎么样，首页只显示第一篇文章，后来改了一次主题又改回来结果好了。现在首页又不随文章更新了。

**Comment by ghkk** [comment]
/(ㄒoㄒ)/~~，今天看的时候又好了，好奇怪、、、

**Comment by duchengyao** [comment]
是的是的，好奇怪>_<

**Comment by yuchen-lea** [comment]
我是为文章添加以后，本地预览无误之后deploy到github，结果首页只有最新的一篇文章。看了大家的答复，我决定睡一觉起来看看情况~

**Comment by duchengyao** [comment]
不是到是主题的问题，还是hexo的问题

**Comment by ivan-nginx** [comment]
@duchengyao dont understand u, write in English if not solved. If solved, close it please.
