### ISSUE TITLE
显示不出博客内容，一直显示 “正在等待fonts.lug.ustc.edu.cn 响应”

### ISSUE THREAD

**Issue by AsiamCn** [iissnan/hexo-theme-next#511]
打开http://notes.iissnan.com/时，也有同样的问题，是科大博客的服务挂掉了吗？
win10，chrome 46.0.2490.80 m (64-bit)

**Comment by wongloong** [comment]
恩。服务器挂掉了。。

**Comment by mpc2008cn** [comment]
我也发现了,把字体又改回google fonts的url了,感觉速度还行~
打开next主题下的`\layout\_partials\head.swig`
```
{% if theme.use_font_lato %}
  {% if config.language === 'zh-Hans' %}
	{# //fonts.lug.ustc.edu.cn/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext #}
    <link href='//fonts.googleapis.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  {% else %}
    <link href='//fonts.googleapis.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  {% endif %}
{% endif %}
```

**Comment by luodaoyi** [comment]
能替换成360的么

**Comment by luodaoyi** [comment]
刚才查了下 现在谷歌字体在大陆解析的是北京的服务器 速度很不错哦

**Comment by ferstar** [comment]
楼上正解， 解析到的是北京的服务器，速度很是不错，我已经改回去了
`layout/_partials/head.swig:33:`

**Comment by tonydeng** [comment]
建议可以使用360的CDN服务

**Comment by iissnan** [comment]
@tonydeng 360 不支持 https。既然 Google Fonts API 可以使用，我将只使用它。

**Comment by iissnan** [comment]
已修正

**Comment by blueyi** [comment]
@iissnan  如何修改掉这个google fonts的引用，或者直接放到本地推送到github可以吗？谢谢

**Comment by iissnan** [comment]
@blueyi Google Fonts 的引用定义在 [head.swig](https://github.com/iissnan/hexo-theme-next/blob/master/layout/_partials/head.swig#L32) 中，将这个地址换成别的即可

**Comment by blueyi** [comment]
@iissnan 嗯嗯，谢谢。是否可以将这句去掉，或者将引用的字体手动下载下来放在本地引用？

**Comment by blueyi** [comment]
@iissnan  查到如何修改了，谢谢！请问如何使符号“`”(即esc下面下个符合)之间的markdown内容支持高亮，或者与代码背景色保持一致，谢谢
