### ISSUE TITLE
Just a Q&A about the style of site-state div

### ISSUE THREAD

**Issue by winterTTr** [iissnan/hexo-theme-next#514]
Hi iissnan,

I am trying to use the "display: flex" to make the `site-state-item` dynamically arrange within the parent div. 

Currently, my change is ok under `pisces` scheme, but for other scheme, i found the parent div, which is `site-state` will be add style as this: `style="opacity: 1; display: block; transform: translateX(0px);"`

Could you give some hint about where this style is loaded/added, so that i can make my change compatible  with other scheme.

Thanks, 

-winterTTr

**Comment by winterTTr** [comment]
For detail about my change, i add one more div between each of `site-state-item` as a `site-state-item-seperator`, and make all of them average align within the `site-state` parent div. So the final effect will be like my personal site ( I have already apply the change to my site )  http://winterTTr.me

the change for my site is here:
https://github.com/winterTTr/winterTTr.github.io/commit/c38745bbcd54cfc341e4b16e167d765da567e9f5

But for other scheme, as the `display` of `site-state` div is set to `block` explicitly, so that my change cannot be compatible with existing scheme. 

So please help to show me where that explicit `style` for `site-item` comes from

**Comment by iissnan** [comment]
Hi @winterTTr 

The inline styles including `display` of `site-item` is added by [Velocity.js](http://julian.com/research/velocity/). There is a `showSidebar` function in `source/js/motion.js` which triggers the motion.

Velocity.js allows you to set `display` option before/after animation, you can find it [here](http://julian.com/research/velocity/#displayAndVisibility)

By the way, although flex is very easy to use, it is not supported by IE 9 and some android browsers.

**Comment by winterTTr** [comment]
Wow, that's right. i do not think about the compatibility of this flex layout. i may need to think about a classic way to resolve this layout quiz 😋

thanks very much for your answer
