### ISSUE TITLE
Markdown 代码高亮不支持其它语言

### ISSUE THREAD

**Issue by seirhsiao** [iissnan/hexo-theme-next#515]
我想在markdown使用clojure代码:

 ` `````clojure`
  (ns sample)

  (defn func
    [^Throwable x & y]
   (conj {} [:a (+ 1.1 x)]))

  (def variable
    @(future
       (if-let [x 5]
        true
       "false")))
` ````` `

如何自定义代码高亮支持 highlight.js 中其它小语种?

**Comment by iissnan** [comment]
可以先确认下 [highlight](https://highlightjs.org/) 是否支持

**Comment by seirhsiao** [comment]
highlight 已经支持clojure，是否需要把之前的代码高亮禁掉，有没有能兼容的方法?

**Comment by seirhsiao** [comment]
今天重新试了下,好像tomorrow theme 支持clojure.写法应该为：

 ` `````clojure`
code
 ` ````` `
和
 ` `````clojure-repl`
code
 ` `````
