### ISSUE TITLE
Next.Pisces-只有首页显示favicon

### ISSUE THREAD

**Issue by mpc2008cn** [iissnan/hexo-theme-next#519]
![favicon](https://cloud.githubusercontent.com/assets/11917818/11209043/a8571888-8d59-11e5-8460-3f7cedb41db8.png)

**Comment by iissnan** [comment]
我这边查看你的站点显示正常

**Comment by mpc2008cn** [comment]
@iissnan 又看了下确实好了,昨天按配置文件里说的把favicon放到source文件夹里,清缓存清cookie都无效,就提了,原来还是缓存的原因,生效慢啊:(
U can close it.Thanks!

**Comment by mpc2008cn** [comment]
缓存的原因
