### ISSUE TITLE
关于百度统计

### ISSUE THREAD

**Issue by taoyuanxiaoqi** [iissnan/hexo-theme-next#52]
百度统计3.0 似乎没有百度统计id这一说 翻了半天没有看到 只有获取代码 方法安装 
请教一下主题设置这个怎么破

**Comment by iissnan** [comment]
`baidu-analytics-id` 就是 `hm.js?` 后面的那串字符。
```
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?50c15455e37f70aea674ff4a663eef27";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
```

**Comment by vinyo** [comment]
<script type="text/javascript" id="hexo.configuration">
  var CONFIG = {
    scheme: '',
    analytics: {
      baidu: '608497c9867f83c273c5761b57feab19',
      google: ''
    },
    sidebar: 'post'
  };
</script>
额，最新版本F12调试百度统计不能用了。

**Comment by iissnan** [comment]
@vinyo 多谢反馈！在一个修改中，百度统计的脚本放置在外链的 JS 文件中。 我排查了一下没有找到问题的根本原因，因为统计的脚本在页面上看起来执行是正确的，但是百度统计会提示代码安装不正确。
我将统计的脚本改回直接嵌入在页面上，问题不存在了。

请更新下主题。
