### ISSUE TITLE
关于next主题对Markdown语法支持不完整的问题？

### ISSUE THREAD

**Issue by HeminWon** [iissnan/hexo-theme-next#524]
今天测试" - [ ] "这个做任务列表的语法无法实现，有解决方式么？

**Comment by normalhh** [comment]
经测试“ '''Bash “这种代码区块语法也无法支持，使用的是Mist这个Scheme

**Comment by iissnan** [comment]
NexT 并未提供任何 Markdown 解析的功能。使用哪款 Markdown 解析是在 Hexo 里配置的。

**Comment by ererermao** [comment]
@iissnan 你好，请问下markdown 的解析配置是在那里的。

**Comment by dark19940411** [comment]
@iissnan 同问md的解析配置如何弄？

**Comment by JohnTian** [comment]
@iissnan 同问md的解析配置如何弄？

**Comment by iissnan** [comment]
在 [Hexo Plugins](https://hexo.io/plugins/) 页面找到所需的 Markdown Renderer Plugin，根据 Plugin 的文档做配置即可。通常的步骤是：

1. 卸载 Hexo 自带的 Markdown 渲染器 `npm uninstall --save hexo-renderer-marked`
1. 安装所需的 Markdown Renderer Plugin
1. 在站点的配置文件 `_config.yml` 中配置 Plugin 的选项 （Plugin 的项目中有选项说明）

至于能否使用 `- []` 这种 TODO 列表，最终得看所选的 Renderer Plugin 是否支持。

**Comment by stduolc** [comment]
你们现在用的什么render?
