### ISSUE TITLE
在线预览的那个版本有下载的地方吗？

### ISSUE THREAD

**Issue by QzhouZ** [iissnan/hexo-theme-next#529]
目前版本是0.4.5.2,在线预览的版本是0.5.2?
在线预览的那个版本有下载的地方吗？

**Comment by QzhouZ** [comment]
有人知道嘛~

**Comment by fewtime** [comment]
是 Pisces 吗，你切换到 Pisces 分支就可以了

**Comment by QzhouZ** [comment]
@fewtime 
下载了这个版本貌似没什么改变，如何设置可以像在线预览http://notes.iissnan.com/这样的布局呀

**Comment by 644792799** [comment]
https://github.com/iissnan/hexo-theme-next/issues/558
