### ISSUE TITLE
可以支援facebook comment plugin嗎?

### ISSUE THREAD

**Issue by tomroy** [iissnan/hexo-theme-next#530]
請問可以支援facebook的comment plugin嗎?
https://developers.facebook.com/docs/plugins/comments

**Comment by mcknote** [comment]
https://github.com/lsmoura/hexo-fbcomments
不知道這能不能用？

**Comment by hydai** [comment]
我做了一個 PR #925 將 Facebook comments plugin 整合進去來解決這個問題。

不知道我在該 PR 裡的處理是否符合你的需求？
