### ISSUE TITLE
有个需求，可否鼠标滚动文章目录显示，改成默认有文章目录全部展开

### ISSUE THREAD

**Issue by liSNS** [iissnan/hexo-theme-next#531]
首先赞一个，真的很不错。我大多写笔记，经常忘了会翻来看看，可能会记得某个文章目录某一段，我希望能默认文章目录全部展开 方便改嘛？

**Comment by iissnan** [comment]
默认都展开的话，有可能目录会超出屏幕的高度

**Comment by liSNS** [comment]
是的。我一般目录很少，我改改方便吗 ？谢谢

**Comment by zoakerc** [comment]
自定义样式 `custom.styl` 中加入一行 `.post-toc .nav .nav-child { display: block; }` 即可

**Comment by dc1y** [comment]
能否考虑在目录过长时，在目录的右侧显示滚动条？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
