### ISSUE TITLE
為何訪問速度奇慢呢

### ISSUE THREAD

**Issue by myhongkongzhen** [iissnan/hexo-theme-next#534]
您好，非常喜歡您製作的主題，非常簡潔，但是不論是本地localhost:4000還是發佈網站上，訪問速度奇慢，打開首頁，幾乎需要1分鐘的時間，即使是在本地，也是這樣，不知是我操作有誤，還是主題包含了太多JS，CSS素材所累？

**Comment by iissnan** [comment]
本地若打开同样非常慢，应该不是资源文件（CSS、JS）多导致的问题。可以使用 Google Chrome 的 Network Panel 看下什么请求占用太多的时间。

**Comment by Cering** [comment]
看看主题的_config.yml文件里`use_font_lato: false`这项是不是false
如果是true的话，会加载google的Lato字体？反正没翻墙的话会特别慢。。。
之前同为这个问题纠结了好久。。。

**Comment by myhongkongzhen** [comment]
@Cering 哇塞，真的哎，把您說的這個屬性改為false之後，無論是本地還是部署以後，頁面簡直就是秒開！THX！

**Comment by Cering** [comment]
@myhongkongzhen ，不客氣哈，我也剛用這個主題不久，還在學習中：）

**Comment by eurusd** [comment]
那用什么字库代替呢？关闭后字体不好看呢。

**Comment by myhongkongzhen** [comment]
@eurusd 那個 我都用的 是  "Courier New" , MingLiU 這兩個字體，英文是前面的，中文是後面的那個
我喜歡這兩個字體。所以自己修改了樣式文件，把所有字體的地方都換成了這兩個。
你也可以手動替換自己喜歡的字體，或者將你喜歡的字體下載到本地加載，應該就會快了。
