### ISSUE TITLE
为什么我本地显示是正常的，deploy之后，首页只能显示一篇文章呢

### ISSUE THREAD

**Issue by la413972057** [iissnan/hexo-theme-next#535]
有时候会遇到这种情况

**Comment by la413972057** [comment]
我试了下，hexo d -g，更新了就好了。也不知道什么原因导致的这种情况。

**Comment by onlyxxp** [comment]
在根目录， 把  db.json  删除， 再hexo clean。  就解决了

**Comment by HuberyLee** [comment]
我前几天也遇到过这个问题，应该是你最近发的文章的markdown文件有问题，一处最近发的文章试试

**Comment by la413972057** [comment]
@onlyxxp 好的，下次再出现这种问题，我试试看这种方法。谢谢：）

**Comment by la413972057** [comment]
@HuberyLee 我现在按照自己的方法也显示正常了，并没有修改md文件。下次遇到这种状况的时候我也会试试你说的办法，总之谢谢啦：）

**Comment by zhaoyibo** [comment]
我也遇到过这种问题，删了 db.json 并且 hexo clean 后问题依旧。
然后在第一次 hexo s 的时候本地看也是首页只有一篇，再次 hexo s 看就好了。

**Comment by yeziahehe** [comment]
那么这个问题现在具体应该怎么解决？

**Comment by la413972057** [comment]
@yeziahehe 看了你的issue，我也觉得是主题本身的问题。
