### ISSUE TITLE
试了好久，favicon.ico都设置失败

### ISSUE THREAD

**Issue by Michael728** [iissnan/hexo-theme-next#539]
我在next主题文件夹下的source目录里边放了favicon.ico的图片，像素16*16，然后，在主题配置（不是博客）的_config.yml文件中，这么写的：
favicon: /favicon.ico
然而，博客上面的图标还是没换……

**Comment by crossingmay** [comment]
不是在主题文件夹，而是在站点下的source目录下。还有，请强制刷新。我用的chrome，遇到了类似的问题，强制刷新之后就可以载入了。

**Comment by Michael728** [comment]
我现在是解决问题了，我是放在next主题source\images目录下，同时，在主题配置文件里这么写的：
favicon: images/favicon

**Comment by QiJunHu** [comment]
@Michael728    我也遇到同样问题，按照你的办法解决了

**Comment by snowluliang** [comment]
你先把图片在线修改成16*16的,然后保存起来,复制到source目录下,并将其重命名为favicon.ico,然后双击打开看一下,在部署上去,hexo d -g  就可以看到了,亲测有效

**Comment by hezhipengzipp** [comment]
@Michael728 是放在next主题source\images目录下，同时，在主题配置文件里这么写的：
favicon: images/favicon.ico ,是这样的，我试过没问题了

**Comment by ivan-nginx** [comment]
@hezhipengzipp `source/favicon.ico` in root Hexo dir.

**Comment by rjosodtssp** [comment]
我的问题是ico尺寸太大，改成16的就好了

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
