### ISSUE TITLE
新版本功能提议

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#54]
看到作者你的博客首页已经出来了，不知道按照你规划的博客设计，是否有考虑友链的功能呢？

**Comment by mingmings** [comment]
感谢作者分享这个主题，另外想请问一下如何实现你的多个域名访问不同的内容呢，例如你这边 `http://iissnan.com/` 是你的博客，`http://iissnan.com/progit/` 是你的 pro git 书籍，这种不同域名访问不同内容在 github page 上如何实现？

**Comment by iissnan** [comment]
`0.4.0` 没有计划加友链，不过应该不是个难事。

多个站点的设置其实很容易，假设 GitHub 帐号是 `foobar`，域名是 `foobar.com` ，通过以下配置就行：

1. github.foobar.io 绑定主域名 `foobar.com`
2. 其他的仓库（例如 `progit`）通过 `gh-pages`  分支存储站点内容，通过 `foobar.com/ + 仓库名` 就可以直接访问。

**Comment by mingmings** [comment]
@iissnan 你的意思是，我的站点是 `http://mingmings.org`,  别名是  `blog.mingmings.org`，如果我想设置一个和你类似的，比如 `A.mingmings.org`，或者是 `B.mingmings.org` 这样加上博客总公共三个站点，如果用分支存储站点内容的话，`gh-pages` 存储一个，也只有两个站点内容呢，我看你的 `pro git` 是单独的一个仓库，域名的设置是在根目录下的那个 cname 里？感觉我理解错的样子

**Comment by iissnan** [comment]
@mingmings 是这样子的：

当你的 `mingmings.org` 作为 `mingmings.github.io` 仓库的自定义域名，你的其他仓库都会自动挂载到这个域名下。

以我的为例子：

我将域名 `iissnan.com` 绑定到我的 `iissnan.github.com` 这个仓库上。

然后，我的其他仓库（注意，是仓库）都可以通过 `http://iissnan.com/仓库名` 来访问。所以，`progit` 仓库就可以通过 `http://iissnan.com/progit` 来访问了。你可以试试在你 GitHub 的帐号下建一个 `atest` 仓库，推送一个 `index.html` 到这个新建仓库的 `gh-pages` 分支上，然后通过 `http://mingmings.org/atest` 访问试试。

**Comment by jiangxy** [comment]
这是github pages绑定域名的两种方式，绑定裸域名或二级域名
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

你的`A.mingmings.org`和`B.mingmings.org`可以绑定到不同repo的gh-pages上，设置DNS的CNAME记录，同时在repo中添加CNAME文件即可

或者直接绑定裸域名，通过`mingmings.org/A`、`mingmings.org/B`来访问不同repo的gh-pages

**Comment by mingmings** [comment]
@iissnan  @jiangxy  感谢两位的耐心解答，瞬间明白

**Comment by iissnan** [comment]
@jiangxy :+1:

**Comment by zhugexiaobo** [comment]
@iissnan @jiangxy 如果我没有创建 `name.github.io` 仓库，能否用两个顶级域名 `A.com` 和 `B.com` 分别绑定 `github.com/name/repoA` 跟 `github.com/name/repoB` 呢？
有没有不使用2个 Github 帐号实现这个效果的方法呢？希望能指点一下，不胜感激。

**Comment by mingmings** [comment]
@zhugexiaobo 就只要一个 github 账号就可以了，你可以参考下我的这篇[博文](http://mingmings.org/2015/github-page-%E5%A4%9A%E7%AB%99%E7%82%B9%E9%83%A8%E7%BD%B2/)，当时就是请教了作者和上面那个哥们，然后总结的

**Comment by zhugexiaobo** [comment]
@mingmings 不是的，我说的是两个顶级域名，不是二级，也不是子目录。

**Comment by mingmings** [comment]
域名的绑定无所谓啊，你直接在 repo 下新建一个 CNAME ，里面写上你的顶级域名就可以了，而后在域名解析商那里设置你的解析

**Comment by zhugexiaobo** [comment]
@mingmings 我试过了。第二个顶级域名 `B.com` 设置了 `name.github.io` 的 CNAME 之后，只能解析到 `name.github.io`，不会访问 `github.com/name/repoB` 下的 GP。

**Comment by mingmings** [comment]
@zhugexiaobo 纳尼我去试试

**Comment by GreatGarlic** [comment]
@zhugexiaobo 请问是否解决了CNAME绑定两个顶级域名的问题？

**Comment by ruijun** [comment]
@mingmings 你好，上面给的博文链接打不开了，能否重新发下
