### ISSUE TITLE
头像本地设置没效果

### ISSUE THREAD

**Issue by linking123** [iissnan/hexo-theme-next#541]
远程链接能出来，本地的两种都出不来呢，generate和server都出错。

**Comment by linking123** [comment]
自问自答：
以下官方配置方法：
侧边栏头像
编辑 站点配置文件，新增字段 avatar， 值设置成头像的链接地址。
其中，头像的链接地址可以是：
完整的互联网 URL，例如：https://avatars1.githubusercontent.com/u/32269?v=3&s=460
站点内的地址，例如：
/uploads/avatar.jpg 需要将你的头像图片放置在 站点的 source/uploads/（可能需要新建uploads目录）
/images/avatar.jpg 需要将你的头像图片放置在 主题的 source/images/ 目录下。

我的问题：
主题下放置/images/avatar.jpg，只在首页有效；其他页面不能显示头像。

我的解决方式：
看到generate后public的index.html中头像的链接example: ../tags/images/avatar.jpg，尝试在站点source下的每个文件夹里放置/images/avatar.jpg，起效了。不知道有没有更好的方式，先记录下。

**Comment by fewtime** [comment]
有尝试 hexo clean 和 hexo g 吗？ 

我是用 /uploads/avatar.jpg 这个方法，一开始首页都不能显示，后来 clean 下就可以了。

**Comment by mritd** [comment]
@fewtime 推荐图片放在 upyun  或者 七牛CDN

**Comment by Ericxiaoshuang** [comment]
我的也是这个问题，头像怎么都不显示

**Comment by YanHuiLi** [comment]
关于这个问题，大家要注意，我们在设置头像的时候，那个source站点指的是 自带主题下的站点。

**Comment by blackdusts** [comment]
我的头像也是出不来，然后我就想既然原来的那张avater.gif能够显示，那就把这张图删掉，把我的图片改名叫avater.gif替换他，结果就显示出来了。

**Comment by Xiankai-Wan** [comment]
尝试了在images和uploads路径下面，也尝试了链接式的和gif，但是都没有成功，有没有其他解决方案呢？

**Comment by Xiankai-Wan** [comment]
想和所有遇到这个问题的小伙伴提个醒吧，我之前也遇到了这个问题，使用了以上大家提供的方法都没有成功，最后发现原来是这一句代码我习惯性的在最开始的地方按下了tab，也就是前面空了四个空格，导致格式不正确，当我改成顶格之后就可以了。不知道有没有也是因为这个导致图片无法加载的小伙伴，在这里提个醒吧，希望大家注意一下可能因为这个导致的。希望所有人都顺顺利利啦～

**Comment by milk2we** [comment]
解决方法：是因为图片的格式的问题导致的。修改图片格式为RGB模式。就可以了。

**Comment by Jeffchal** [comment]
已经尝试过： hexo clean ， 路径用" "引起来 ，更改为jpg后缀（图片也是RGB格式）， 还是不显示，甚至连圆形框都没有。

**Comment by kentcc88** [comment]
以上的都试了一遍，都不行啊，究竟怎么弄？

**Comment by linking123** [comment]
@kentcc88@Jeffchal 不知道你们解决没？！

我的思路是，看页面链接是什么，然后倒着去找问题。

这个issue还在更新啊！
希望解决的多在这里留下解决方法，以让后来人少走弯路！

**Comment by stevenjoezhang** [comment]
@kentcc88 @linking123 请使用新版：https://github.com/theme-next/hexo-theme-next
