### ISSUE TITLE
文章内容中的图片会出现在文章的顶部~

### ISSUE THREAD

**Issue by lucasleelz** [iissnan/hexo-theme-next#545]
我发现这个问题 已经有人提过了~ 但实际上仍然没有解决这个问题，
上面有说到
title: {{ title }}
date: {{ date }}
photos: 
tags:
---
是因为出现了photos。 
当我没有出现photos时，首页列表确实不会出现，点击每一篇文章，却会在文章顶部出现文章内容的所有图片。
当我写上photos:nil的时候，文档顶部就只是会出现一个图裂的图片并不会出现大量的图片。

请问作者如何做到文章顶部不要有文章内容图片？

**Comment by Vienta** [comment]
同样遇到这个问题  快解决啊

**Comment by Haocen** [comment]
@lucasleelz 希望能提供链接和 md 文件，我可以试试修复。

**Comment by iissnan** [comment]
同样的问题有：#483 #403 。

奇怪的是只有在文章的 Front-matter 里包含 `photo` 或者 `photos`，NexT 才会在文章顶部显示图片。
那也就是在某些情况下，即时没有明确设置这两个字段中的一个，也会有其他的条件触发 post 包含 `photos`。

我去翻了 Hexo 的源码，没有看到对 post.photos 字段进行特殊处理。所以还没有找到能重现的情况。

如 @Haocen 所说，@lucasleelz @Vienta 最好能提供下文章的 md 文件，便于查找问题的所在。

**Comment by Vienta** [comment]
我的blog备份在这: https://bitbucket.org/Vienta/blog  里面有具体的md文件

**Comment by Haocen** [comment]
@Vienta 未能在 Hexo 3.2 和最新的 Next 主题中重现。
请指明具体是哪篇文章并提供出错页面的截图。

**Comment by Vienta** [comment]
@Haocen  
![2016-03-15 5 23 06](https://cloud.githubusercontent.com/assets/1928338/13763481/6919917a-ea81-11e5-9511-c97d4944cfa3.png)

你说道的版本包提醒了我，我将所有的都升为最新版后是ok的

**Comment by Haocen** [comment]
@Vienta 好吧。麻烦关闭这个问题。

**Comment by iissnan** [comment]
那看起来是旧版本存在的问题，但还不清楚这个问题是具体的原因是什么。我先关闭掉这个问题，有新的重现我们再具体分析

**Comment by lucasleelz** [comment]
抱歉我昨天没有看到邮件。

hexo
hexo: 2.8.3
os: Darwin 15.3.0 darwin x64
http_parser: 2.5.0
node: 4.2.2
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d


node_modules
    "hexo-deployer-git": "0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.1.0",
    "hexo-renderer-stylus": "^0.1.0”

我发现如果这几个模块用0.1 以上版本 hexo g 的时候就会自动报错。      目前来看不知道是否是因为这几个模块的问题。

next 是拉取github上最新master分支。

http://lucasleelz.github.io/2015/11/20/iOS-DaybyDay1-UIKit-Dynamics/ <http://lucasleelz.github.io/2015/11/20/iOS-DaybyDay1-UIKit-Dynamics/>

**Comment by iissnan** [comment]
@lucasleelz 谢谢。我去测试下 Hexo 2.8.3 这个版本，你可以试试升级下 Hexo

**Comment by lucasleelz** [comment]
你好，刚刚通过升级到3.2。0 确实可以解决这个问题。 那么就应该是hexo的问题。在 2016年3月16日，下午12:47，Vi <notifications@github.com> 写道：@lucasleelz 谢谢。我去测试下 Hexo 2.8.3 这个版本，你可以试试升级下 Hexo —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by iissnan** [comment]
@lucasleelz :+1:
