### ISSUE TITLE
建议增加开关控制sidebar的动画效果

### ISSUE THREAD

**Issue by clude** [iissnan/hexo-theme-next#546]
在配置“sidebar: always”后，侧边栏能保持出现，但每次都是延迟弹出，这样的用户体验不一定就是最佳，建议增加配置参数，可开关该动画效果

**Comment by Cering** [comment]
+1，同觉得动画效果有点慢，希望能提供下解决思路。
在主题配置文件中_config.yml中已经设成`use_motion: false`了，但这样sidebar默认就不会自动打开，打开时还是会有动画。
看了半天代码，没找到在哪里改，做后台的面对css伤不起啊。。。

**Comment by JGINGIT** [comment]
+1， 调了半天侧边栏都不自动打开，原来是之前设置了 `use_motion: false`

**Comment by ThinerZQ** [comment]
看完楼上，豁然开朗。

**Comment by duchengyao** [comment]
动画只是有点慢嘛，我都吃完饭了，还没自动弹出来 >_<
use_motion:已经是true了
我用的是mist主题

**Comment by ivan-nginx** [comment]
@clude dont understand u, write in English if not solved. If solved, close it please.
