### ISSUE TITLE
highlight.styl - color: color-link;

### ISSUE THREAD

**Issue by m3t** [iissnan/hexo-theme-next#547]
I was [linting](http://csslint.net/) a part of theme's css output and voila:

```
Expected (<color> | inherit) but found 'color-link'
```

It's the undefined (typo? `$link-color`?) variable in [highlight.styl (Line 91)](https://github.com/iissnan/hexo-theme-next/blob/28d0283e36d56b4d37839aca4633ab3537ffa83d/source/css/_common/_vendor/highlight/highlight.styl#L91)

![image](https://cloud.githubusercontent.com/assets/12968867/11616205/9148540a-9c76-11e5-9493-9d4f647b501a.png)

**Comment by iissnan** [comment]
It seems `color-link` is an old variable name. `$link-color` should be used.

**Comment by iissnan** [comment]
`.gist` related styles are removed.
