### ISSUE TITLE
侧边栏无法自动打开

### ISSUE THREAD

**Issue by JetYoung** [iissnan/hexo-theme-next#548]
在主题配置文件中设置了 sidebar = always 或者 sidebar = post 侧边栏都无法自动打开。我的post是有目录的，进入post后发现侧边栏的颜色会变，但是仍然无法自动打开

**Comment by SueJue** [comment]
更新到最新的版本就没有问题了

**Comment by zhitaocai** [comment]
我这边已经是新版本还是不行

**Comment by Ethan-Zhang** [comment]
#659

**Comment by zhitaocai** [comment]
@Ethan-Zhang 的改动可以解决这个问题，因为master还没有合并过去，所以自己手动改了，测试可以，赞
