### ISSUE TITLE
想请问一下 我的首页文章默认全部居中显示 怎么设置可以让文章靠左显示？

### ISSUE THREAD

**Issue by santong** [iissnan/hexo-theme-next#55]
谢谢啦

**Comment by liuxudan** [comment]
喜欢居中。。。。

**Comment by liuxudan** [comment]
咱俩都是喜欢简约的主题

**Comment by santong** [comment]
@liuxudan 额 居中有时会造成排版错乱问题 听影响体验的。。

**Comment by santong** [comment]
问题貌似解决了 但会不会是一个BUG 
因为之前不熟悉markdown语法
一篇文章 之前用HTML 的body标签并且设置了
    text-align=center
所以整个页面都变成居中显示了 
想请教下 为什么一篇文章的属性设置会影响到index页面？

**Comment by iissnan** [comment]
猜测是 浏览器在兼容错乱的 HTML 结构导致的一些怪异的表现。

**Comment by santong** [comment]
@iissnan  哦哦 谢谢 还想请教下 NexT下怎么加多说评论 我无论按照多说的官方教程或是自己Google的都没找到解决方案 v2的帖子如下 
https://www.v2ex.com/t/178189
谢谢啦

**Comment by santong** [comment]
@iissnan  哦哦 谢谢 还想请教下 NexT下怎么加多说评论 我无论按照多说的官方教程或是自己Google的都没找到解决方案 v2的帖子如下 
https://www.v2ex.com/t/178189
谢谢啦

**Comment by iissnan** [comment]
只要在站点的 `_config.yml` （主题的 `_config.yml` 也可以）中添加多说的配置就可以：

```
duoshuo_shortname: your-duoshuo-shortname
```

[见 NexT Wiki](https://github.com/iissnan/hexo-theme-next/wiki/%E8%AE%BE%E7%BD%AE%E5%A4%9A%E8%AF%B4-DISQUS%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F)

**Comment by santong** [comment]
@iissnan 谢谢！ 解决了！
