### ISSUE TITLE
移动端浏览代码行数和代码重叠问题

### ISSUE THREAD

**Issue by ferstar** [iissnan/hexo-theme-next#555]
如图, 代码和行号重叠在一起~
![screenshot_2015-12-13-19-48-34](https://cloud.githubusercontent.com/assets/2854276/11766815/c3c65bf0-a1d2-11e5-8efd-f14d18fd7dde.png)

**Comment by icyleaf** [comment]
我这边也出现了这样的问题，iPhone 6s

![website](https://cloud.githubusercontent.com/assets/17814/11862960/f0e9a902-a4ca-11e5-9225-7d7c1372489f.jpg)

**Comment by zhangjh** [comment]
我的方法是修改custom.styl (路径：source/css/_custom)
增加
.code {
    padding-left: 20px !important;
    background-color: black;
}
