### ISSUE TITLE
请问如何在菜单页面下添加评论呢？

### ISSUE THREAD

**Issue by rdmclin2** [iissnan/hexo-theme-next#557]
例如我添加了一个关于的菜单，想要在下面添加disqus评论，应该如何操作？

**Comment by NatLee** [comment]
如果是配置在站點下面source的話

記得要在站點下的_config.yml加
# Disqus
disqus_shortname: yourname

**Comment by rdmclin2** [comment]
@NatLee 这个配置了的，只是新建的菜单页面没有评论

**Comment by iissnan** [comment]
@rdmclin2 新建的页面，在有配置 `disqus_shortname` 的情况下会自动加载评论。除非在页面上使用 `
comments: false` 关闭掉

也有可能是你所使用的 NexT 版本比较旧

**Comment by ivan-nginx** [comment]
@rdmclin2 dont understand u, write in English if not solved. If solved, close it please.

**Comment by rdmclin2** [comment]
@ivan-nginx sovled with new version
