### ISSUE TITLE
如何配置像http://notes.iissnan.com/ 这样的布局呢

### ISSUE THREAD

**Issue by fastercoder** [iissnan/hexo-theme-next#558]
在线预览http://notes.iissnan.com/ 的布局很NICE ，如何配置呢，菜单在左边，文章在右边显示

**Comment by wens07** [comment]
我也想知道, 我是冲着预览中的主题来的; 下载后发现不是啊? 要怎么配置嘛; scheme改下貌似不行

**Comment by fastercoder** [comment]
是呀 换了scheme不行, checkout出的pisces也不行

**Comment by amoyiki** [comment]
checkout Pisces分支，然后更改配置文件的主题就行了

**Comment by wens07** [comment]
恩, 谢谢楼上, 已经在配置中

**Comment by fastercoder** [comment]
楼上的 你配置好了没

**Comment by wens07** [comment]
首页大致像preview那样了, 你怎么样?

**Comment by fastercoder** [comment]
怎么checkout Pisces分支呢？求指导

**Comment by wens07** [comment]
用git啊; git clone https://github.com/iissnan/hexo-theme-next.git -b pisces theme/next
然后配置主题成pisces

**Comment by fastercoder** [comment]
好的，谢了，我试试

**Comment by fastercoder** [comment]
为什么我的还是默认的样式呢 scheme 也改为pisces了 
http://forevercoder.com/

**Comment by wens07** [comment]
你可能哪里没设置好吧? 用上面的命令checkout--pisces分支到theme/next 文件夹,  next主题中config那个scheme改成pisces; 而hexo生成的blog下的config主题设置成next;  这样你本地测试下, 应该就行了吧

**Comment by fastercoder** [comment]
本地hexo server 测试都没问题 ，部署到github上就不行了

**Comment by wens07** [comment]
可以的吧, 你看我的. http://wens07.github.io/

**Comment by fastercoder** [comment]
终于搞定了，可以放心睡觉了

**Comment by yqfang** [comment]
@fastercoder 我的也是啊，本地server没问题，为啥部署到github上就不行了呢？

**Comment by 644792799** [comment]
@yqfang 怎么解决的  同问题

**Comment by 644792799** [comment]
问题解决了  来帮助其他入坑的同学 
运行一次 hexo clean 然后再发布就行了

**Comment by iissnan** [comment]
Pisces 已经合并到 master 分支，在主题里配置 scheme 即可。近期会修复一些 bug，然后 release 新版。
