### ISSUE TITLE
在pisces主题下, 大家无序列表显示正常嘛?

### ISSUE THREAD

**Issue by wens07** [iissnan/hexo-theme-next#559]
我看其他主题下也是用hexo默认的hexo-render-marked渲染; 无序列表前面的那个实心点或空圈都能正确显示啊, 我这里好像不行啊

**Comment by zhaoyibo** [comment]
我这儿也一样

**Comment by winterTTr** [comment]
恩，我的也是

**Comment by LeoiOS** [comment]
+1

**Comment by hjin1987** [comment]
+1

**Comment by hjin1987** [comment]
base.styl  56行修改一下：ul { list-style: disc; } 就好了。

**Comment by wens07** [comment]
恩, 好像真的可以显示出实心点, 路径* /css/_common/scaffolding/
谢谢楼上的, 不懂前端

**Comment by wens07** [comment]
顺便问下楼上的大大, 那个首页上分割各个文章的那根线想长点在那边改啊

**Comment by LeoiOS** [comment]
@huain 
thank u

**Comment by huain** [comment]
@wens07   css/_common/components/post/post-eof.styl  第5行：width:  自己改宽点就行了。

**Comment by wens07** [comment]
@huain  非常感谢热心的大神！

**Comment by xcatliu** [comment]
@iissnan 为什么 ul 要被设置成 none 呢？
https://github.com/iissnan/hexo-theme-next/blob/pisces/source/css/_common/scaffolding/base.styl#L56

**Comment by geekrainy** [comment]
@xcatliu 既然放在base.styl里就说明是给全局用的。导航这些会用到。
@fantasticfears 修改放在 `source/css/_common/components/post/post-expand.styl`比较合理。

**Comment by fantasticfears** [comment]
@geekrainy `Mist` 放在 `base.styl` 里，我就照着平级的目录改了。Next 的设计思路和 CSS 组织的原则是怎么样的呢？

**Comment by byenow** [comment]
@huain 终于解决了，感谢

**Comment by iissnan** [comment]
已修复，见  #688
