### ISSUE TITLE
Category count incorrect

### ISSUE THREAD

**Issue by adityarb88** [iissnan/hexo-theme-next#560]
The categories count that you see on the sidebar is incorrect. I created a website using this theme: http://takeradi.github.io/categories/ and if you look at the sidebar, the counts are incorrect. In the below images, you see only 5 categories but the count that you see is 8

![image](https://cloud.githubusercontent.com/assets/1426805/11864194/55e69cc4-a44f-11e5-8cff-cead4856fe5c.png)

![image](https://cloud.githubusercontent.com/assets/1426805/11864196/5e3bf220-a44f-11e5-868d-e830b4a3487c.png)

**Comment by iissnan** [comment]
Try to run `hexo clean`
