### ISSUE TITLE
relative_link: true问题

### ISSUE THREAD

**Issue by lisaac** [iissnan/hexo-theme-next#568]
当开启相对路径的时候，主题中leancloud上报的路径会出错，请赐教如何修改

**Comment by polarlights** [comment]
也遇到了相同问题，默认主题使用的是`partial`，next 使用的是`include`，所以在渲染的时候，应该是不一样的。nodejs 不懂，所以期待@iissnan可以看下。谢谢

**Comment by ivan-nginx** [comment]
@lisaac dont understand u, write in English if not solved. If solved, close it please.
