### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by dcardosods** [iissnan/hexo-theme-next#57]
Hi,

In my _config.yml the language is set to the default, but my site is rendered using zh-Hanz.
Is there any setting I'm missing?

**Comment by iissnan** [comment]
It's wired. Could you please try `hexo clean` and leave the `language` option to blank? 

If it does not work as well, maybe you can try:

1. Set the `language` to `zh-Hans` and generate.
2. Clean the generate with `hexo clean`.
3. Set the `language` back to blank and generate again.

**Comment by dcardosods** [comment]
I tried your suggestions and did some other tests:

Leaving the `language` option to blank fallbacks to the last language in the folder (`zh-Hans` in this case). I also deleted the `zh-Hans` file and it fallbacks to `fr-FR`.
The solution was to set `language` to `default`, but I ended up finding a possible bug on Hexo and will report on its repository.

Thanks!

**Comment by 794485409** [comment]
1、update language to en
2、hexo clean
3、is ok
