### ISSUE TITLE
NexT.Pisces中文章目錄错误

### ISSUE THREAD

**Issue by loseblue** [iissnan/hexo-theme-next#570]
网站地址：http://loseblue.github.io/2015/12/23/RFC3095-ROHC/

在4.3.1. Compressor states 时继续向下时文章目錄错误，一个字母一行。

**Comment by iissnan** [comment]
层次太多，嵌套的 ol 宽度被削减了太多导致

**Comment by iissnan** [comment]
针对这个问题做了两个处理：

1. 减少 ol 的嵌套 padding
2. 文章目录项不换行，超出隐藏（由于 Hexo 的 toc 辅助函数并未输出 title 属性，因此这个隐藏之后被隐藏的内容就无法看到，我打算给 Hexo 提交一个修改 toc 辅助函数的 pr）

至于目录高度超过屏幕可视范围的问题请参见 #629
