### ISSUE TITLE
请问如何再添加一个新页面

### ISSUE THREAD

**Issue by xiaofeima1990** [iissnan/hexo-theme-next#572]
我想利用next 除了about tag 之外多添加几个页面 比如photo  tech 等， 但显示错误，请问具体怎样添加好呢？多谢！

**Comment by hackjustu** [comment]
我尝试通过在source文件夹里增添“reading”文件夹，并修改主题配置文件，增加一行“  reading: /reading
”来添加页面。虽然页面添加成功，可惜主页现实的页面名字是“Menu.reading”而不是“Reading”。

**Comment by skyue** [comment]
我也是，前面带有Menu前缀，这个要怎么调整？

**Comment by skyue** [comment]
哈哈，已经搞定。
在`/next/languages`文件夹中找到你使用的语言文件，比如我用的是`zh-Hans.yml`。
打开后，在`menu`下新增你添加的页面即可。

**Comment by iissnan** [comment]
`hexo new page xxx` 不可以吗？

**Comment by Haocen** [comment]
请务必阅读 Hexo 使用说明： https://github.com/hexojs/hexo

**Comment by xiaofeima1990** [comment]
多谢！新技能get！

在 2016年1月13日 下午6:14，skyue <notifications@github.com>写道：

> 哈哈，已经搞定。
> 在/next/languages文件夹中找到你使用的语言文件，比如我用的是zh-Hans.yml。
> 打开后，在menu下新增你添加的页面即可。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iissnan/hexo-theme-next/issues/572#issuecomment-171241777>
> .
>



-- 




马国轩
guoxuan ma
nanjing university

**Comment by gongchunru** [comment]
@hackjutsu 你好，你解决了吗？我也遇到了同样的问题。

**Comment by sevencai** [comment]
@gongchunru 看下你config里的language配置的是什么语言，然后到theme地下去找到对应语言的配置，点击去把你的页面的文字配置在这个语言.yml中即可。
