### ISSUE TITLE
多个行内公式无法正确显示

### ISSUE THREAD

**Issue by er1iang** [iissnan/hexo-theme-next#573]
参见链接
http://erliang.me/2015/12/29/%E9%9B%86%E6%88%90%E7%94%B5%E8%B7%AF%E8%AE%BE%E8%AE%A1/

**Comment by tsstss123** [comment]
遇到了同样的问题...GG

**Comment by tsstss123** [comment]
解决了
参见
http://segmentfault.com/q/1010000003987383/a-1020000003987577
