### ISSUE TITLE
无法显示标签页面

### ISSUE THREAD

**Issue by samuelyao314** [iissnan/hexo-theme-next#575]
hexo g 命令后。 查看目录内容：

samuel@localhost:~/blog$ ll .deploy_git/tags/
total 0
drwxrwxr-x 2 samuel samuel 23 Dec 30 11:48 Go/
drwxrwxr-x 2 samuel samuel 23 Dec 30 11:48 Server/

hexo d 发布到github page后。 点击http://samuelyao314.github.io/，标签。跳转链接为 http://samuelyao314.github.io/tags/,  出现404页面。

**Comment by naiyu** [comment]
我的也是出现404页面，不知道你解决这个问题没有

**Comment by iissnan** [comment]
hexo clean 下，重新 hexo g

**Comment by iissnan** [comment]
Close this issue due to a lack of further information. Reopen it if you have any questions.
