### ISSUE TITLE
New Demand

### ISSUE THREAD

**Issue by LeoiOS** [iissnan/hexo-theme-next#576]
如果我想在上下滑动网页的时候，让目录这一部分一直在左边显示，有办法实现吗？不要见怪哈，不会js路过~~
如下图：
![image](http://7xl8ia.com1.z0.glb.clouddn.com/QQ20151230-1%402x.png)

**Comment by LeoiOS** [comment]
😄😄

**Comment by iissnan** [comment]
已实现
