### ISSUE TITLE
请教如何控制评论显示？

### ISSUE THREAD

**Issue by ningkaikok** [iissnan/hexo-theme-next#582]
比如我新建一个about页面，希望不加载评论列表，应该在那地方修改？

**Comment by loseblue** [comment]
在模版的头上加入
`comments: false`

例如我的tag
```
title: All tags
date: 2015-12-16 17:05:24
type: "tags"
comments: false
---
```

**Comment by iissnan** [comment]
请参阅：[如何关闭新建页面的评论功能？](http://theme-next.iissnan.com/faqs.html#setting-page-comments)
