### ISSUE TITLE
手机浏览代码块行号和代码重叠

### ISSUE THREAD

**Issue by imperio-wxm** [iissnan/hexo-theme-next#590]
![Uploading image.png…](http://i4.tietuku.com/3dd68845339d6305.png)

**Comment by mezipstream** [comment]
我也遇到了同样的问题, 添加代码时, 使用代码区块的方式(换行再加一个TAB)就不显示行号了, 但是这样还有一个问题, 就是代码关键字也不高亮显示了. 很困扰..

**Comment by ivan-nginx** [comment]
@imperio-wxm dont understand u, write in English if not solved. If solved, close it please.
