### ISSUE TITLE
在pisces中如何把文章间的距离改小呢？ 

### ISSUE THREAD

**Issue by Yaccc** [iissnan/hexo-theme-next#591]
![b2fb45a5-dfdb-46ae-97b9-9eaddedb6fb2](https://cloud.githubusercontent.com/assets/5906306/12220544/bd82b8b2-b7b0-11e5-931e-66cd191d1df0.png)

如上图所示，文章件距离太大了，是否有参数配置能改小？或者改哪个css能起作用呢？

**Comment by amoyiki** [comment]
更改 主题路径下\source\css\_common\_component\posts-expand.styl 中
```xml
.posts-expand {
  .post-eof {
    display: block;
    //文章间距
    margin: 60px auto 50px;
    width: 8%;
    height: 1px;
    background: $grey-light;
    text-align: center;
  }
}
```

**Comment by Yaccc** [comment]
@amoyiki 非常感谢，那么文章头部的距离能否改小呢？

**Comment by ivan-nginx** [comment]
@Yaccc dont understand u, write in English if not solved. If solved, close it please.

**Comment by Eminem-x** [comment]
> 更改 主题路径下\source\css_common_component\posts-expand.styl 中
> 
> ```
> .posts-expand {
>   .post-eof {
>     display: block;
>     //文章间距
>     margin: 60px auto 50px;
>     width: 8%;
>     height: 1px;
>     background: $grey-light;
>     text-align: center;
>   }
> }
> ```

若版本不一致，可以在路径下 `themes\next\source\css\_common\components\post\post-expand.styl` 文件中，
直接添加原回答的代码，然后根据需要调节间距即可。
