### ISSUE TITLE
主题里有没有相关的配置把读取的 URL 改成其他站呢

### ISSUE THREAD

**Issue by cielpy** [iissnan/hexo-theme-next#592]
现在生成的网站里的资源都读取了主站的地址，比如我的网站是 http://imciel.com 生成的文件里 js 路径为 http://imciel.com/vendors/fancybox/source/jquery.fancybox.pack.js
前面的路径用了主站的 URL，如果我想让主题相关的文件都用另外一个 URL，比如 http://imciel.qiniucdn.com 然后加载js 的时候去读取http://imciel.qiniucdn.com/vendors/fancybox/source/jquery.fancybox.pack.js ，有什么便捷的文件配置吗？

**Comment by cielpy** [comment]
把主题配置文件的 static 文件参数直接改为了 CDN 地址，不知道这样做是对的吗？
# Static files
vendors: http://xxxclouddn.com/vendors
css: http://xxxclouddn.com/css
js: http://xxxclouddn.com/js
images: http://xxxclouddn.com/images

**Comment by iissnan** [comment]
没什么副作用，只要文件在 cdn 上有就可以。
