### ISSUE TITLE
代码缩进和高亮问题

### ISSUE THREAD

**Issue by mezipstream** [iissnan/hexo-theme-next#593]
我所知道的插入代码可以使用两种方式, 一种是使用 ``` 包裹代码, 一种是换行再使用TAB写代码区块. 如果我使用 三个点 包裹代码的方式, 会显示行号以及代码关键字的高亮, 向这样:
![](http://ww2.sinaimg.cn/large/6c766f0djw1ezvv3gy9toj20co046q37.jpg)

但是我添加代码时代码缩进是4个空格, 但是发表后的显示效果确实缩进8个空格.

如果使用第二种方式插入代码区块, 正常显示缩进, 但是这是没有代码行号和关键字高亮.

实在很困惑, 请各路大神给点思路, 谢谢!!!

**Comment by dafeinayius** [comment]
同有问题，解决了吗

**Comment by at2008** [comment]
可能是代码编辑器的问题
