### ISSUE TITLE
Table of Contents 没有跟随页面滚动

### ISSUE THREAD

**Issue by xcatliu** [iissnan/hexo-theme-next#595]
主题：NexT.Pisces

当页面比较长的时候，Table of Contents 应该跟随页面滚动，这样更有用。

而且 Table of Contents 中会跟随滚动自动展开多级目录，如果滚到下面看不到 Table of Contents，那自动展开就没有意义了。

**Comment by iissnan** [comment]
已修正

**Comment by xcatliu** [comment]
大赞！
