### ISSUE TITLE
main.css 生成不了

### ISSUE THREAD

**Issue by sunaiwen** [iissnan/hexo-theme-next#6]
你好，

`hexo generate` 之后，发现 css 目录下并没有生成 main.css
我以为是 `hexo-renderer-stylus` 没装的原因，装了再 generate 发现 main.css 还是没生成。

我的安装步骤是：

1. 先 clone 代码到 themes 文件夹
2. 然后改 `_config.yml` 中 theme 字段为 next
3. `hexo generate`

这是我博客目录的 `package.json`：

```json
{
  "name": "hexo-site",
  "version": "2.8.3",
  "private": true,
  "dependencies": {
    "hexo-renderer-ejs": "*",
    "hexo-renderer-jade": "^0.1.0",
    "hexo-renderer-less": "^0.1.2",
    "hexo-renderer-marked": "*",
    "hexo-renderer-sass": "0.0.3",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-renderer-swig": "^0.1.0"
  },
  "devDependencies": {}
}
```

是不是装少了哪个插件？有空帮看下，谢啦~

**Comment by iissnan** [comment]
你好 @sunaiwen，

`hexo-renderer-stylus` 0.2目前还是Beta版本，我猜测跟Hexo 2.8不兼容。所以，你可以将这个依赖包的版本更改为`'*'`。如下：

```
"hexo-renderer-stylus": "*",
```

另外，`swig`是Hexo默认支持的模板引擎，所以不需要（也没有）`hexo-renderer-swig`这个包。我建议你将这个依赖去掉。

在以上修改完成后，再次执行下`npm install`。确认`hexo-renderer-stylus`是`0.1.0`稳定版。

**Comment by sunaiwen** [comment]
装上 `hexo-renderer-stylus` *0.1.0* 之后一切都正常了！谢谢！:smile:
