### ISSUE TITLE
社交链接不显示，被adblock给屏蔽了

### ISSUE THREAD

**Issue by qizhihere** [iissnan/hexo-theme-next#60]
social links一直不出来，找了半天以为是没设置好，结果发现是adblock把.social-info类给屏蔽了。建议修改一下类名 :-)
![被adblock屏蔽了~](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/adblock_blacklist.png)

**Comment by qizhihere** [comment]
另外，可否考虑一下给侧边栏的日志、标签和头像都加上链接，虽然自己加起来也很简单，不过更新后就没有了。这个主题很棒，希望越来越完善。

**Comment by qizhihere** [comment]
另外，两点建议：
1. 可否给侧栏的一些元素加上链接？
2. 忽然发现好多斜线(⊙o⊙)？
![好多斜线](http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/too_many_slashes.png)

**Comment by iissnan** [comment]
Thanks. Will take a look at.

**Comment by iissnan** [comment]
看了下 adblock 的[过滤文件](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt)，过滤的范围还挺广的。在 `dev` 分支改了名字，等待合并。

另外你最后那个截图中多个斜线我没有重现。

**Comment by iissnan** [comment]
侧边栏的链接会加上。

**Comment by qizhihere** [comment]
ok，多谢了～
关于多个斜线的问题，可能是我设置的问题，我再看看吧。
