### ISSUE TITLE
移动端没有适配

### ISSUE THREAD

**Issue by chenyfsysu** [iissnan/hexo-theme-next#608]
你好，很感谢提供了这么漂亮的主题。在测试最新版本的next时候发现主题在移动端显示不太正常，访问博主你的网页在移动端能够正确显示，是否是新版本主题忽视了移动端显示呢？

**Comment by Titzanyic** [comment]
已经找到原因，version 0.4.5.1没有此问题呢，version 0.4.5.2存在此问题。你选择下载0.4.5.1版本就可以了。

**Comment by NeilRon** [comment]
**我也是**

请问有办法在最新版本通过修改少量代码修正么？

**Comment by cinthisime** [comment]
参考：https://github.com/iissnan/hexo-theme-next/pull/605/files

**Comment by cinthisime** [comment]
或者把
source/css/_variables/base.styl
第174~175行改为相对大小即可
```
$content-desktop                   = 70%
$content-desktop-large          = 80%
```

**Comment by argsno** [comment]
还没修复吗，今天更新了一下，不能用

**Comment by NeilRon** [comment]
我大概两个两三个礼拜前pull了之后就好了

**Comment by yinzm** [comment]
谢谢 @cinthisime，我用的V0.5.0版本的主题，按照第一种解决方案，确实有效。

**Comment by qq291462491** [comment]
> 谢谢 @cinthisime，我用的V0.5.0版本的主题，按照第一种解决方案，确实有效。

第一种方案是什么方案？

**Comment by yinzm** [comment]
@qq291462491 
https://github.com/iissnan/hexo-theme-next/pull/605/files 照着这个文件改

**Comment by yinzm** [comment]
> 第一种方案是什么方案？
对着这个文件改即可 https://github.com/iissnan/hexo-theme-next/pull/605/files

**Comment by qq291462491** [comment]
@yinzm +1 可以了，感谢

**Comment by feivorid** [comment]
很赞   以解决 问题 ；
