### ISSUE TITLE
如何更新？ 菜鸟提问题

### ISSUE THREAD

**Issue by liuxudan** [iissnan/hexo-theme-next#61]
更新

cd themes/next
git pull

不会更新主题  如何操作 谢谢

**Comment by mingmings** [comment]
这个就是更新

**Comment by liuxudan** [comment]
在GIT中如何操作啊？  如何用啊?

**Comment by iissnan** [comment]
如果 git 不熟悉的话，我想最简单的方法是：

1. 备份 `_config.yml`，`_custom.styl` 以及你修改过的其他文件
1. 删除掉 `themes/next` 目录
1. 重新 `clone` 一份。`git clone https://github.com/iissnan/hexo-theme-next themes/next`
1. 比对你修改的文件与主题对应的文件，将修改应用回去。

**Comment by minoscc** [comment]
git不想用的话～ 就用release版吧～ 也没必要老是更新

**Comment by iissnan** [comment]
@minoscc :+1:  我把这个方式写进 README 好了。

**Comment by mlick** [comment]
git pull 更新老是更新到主目录里，不知道如何才能更新到themes/next

**Comment by mlick** [comment]
@iissnan  感觉这种方式会更好一点
```
cd themes/next
git init
git remote add origin https://github.com/iissnan/hexo-theme-next
git pull
```
