### ISSUE TITLE
图片自动旋转了

### ISSUE THREAD

**Issue by iTofu** [iissnan/hexo-theme-next#613]
图片链接如下：
http://7xl8ia.com1.z0.glb.clouddn.com/Beijing5AM.JPG
![image](http://7xl8ia.com1.z0.glb.clouddn.com/Beijing5AM.JPG)
当 new 一篇文章，hexo s 后发现该图被旋转了？不是本地的原因，hexo d 也这样。

**Comment by LeoiOS** [comment]
如图，单独在浏览器中打开是正常的

**Comment by Haocen** [comment]
可能是 EXIF 信息导致的，处理一下图片再上传试试。

**Comment by monster-gump** [comment]
不知道博主解决了问题没 我感觉是长宽自适应的问题？之前也遇到过- -

**Comment by ivan-nginx** [comment]
@iTofu dont understand u, write in English if not solved. If solved, close it please.

**Comment by CalvinNeo** [comment]
i think the easiest way is you open the image and do some editing, then use your modified copy
