### ISSUE TITLE
侧栏不自动打开

### ISSUE THREAD

**Issue by spring-z** [iissnan/hexo-theme-next#614]
设置了display: post 没有效果

**Comment by NathanYbx** [comment]
对

**Comment by SPRING-Z** [comment]
改成 sidebar: post 就好了，这应该是还没来得及更新。

**Comment by renzifeng** [comment]
我的改成 sidebar: post 怎么还是不行

**Comment by throneclay** [comment]
我的改成 sidebar: post 也是不行啊

**Comment by Fengxq2014** [comment]
Mist scheme下侧边栏不自动打开，display: post，idebar: post都不行啊

**Comment by Flowsnow** [comment]
Mist scheme下我的侧边栏不自动打开，display: post，idebar: post都不行啊

**Comment by Flowsnow** [comment]
Mist scheme下侧边栏不自动打开，display: post不行啊

**Comment by Fengxq2014** [comment]
https://github.com/iissnan/hexo-theme-next/issues/633
可以看看这个

**Comment by Ethan-Zhang** [comment]
#659

**Comment by IanHua** [comment]
sidebar: hide
亲测可行

**Comment by ivan-nginx** [comment]
@SPRING-Z dont understand u, write in English if not solved. If solved, close it please.
