### ISSUE TITLE
请问如何设置read more?

### ISSUE THREAD

**Issue by runshenzhu** [iissnan/hexo-theme-next#62]

**Comment by goxofy** [comment]
?

**Comment by mingmings** [comment]
@goxofy 是的，`markdown` 里 加上个这串，默认就只会显示 `<!--more-->` 之上的内容了

**Comment by iissnan** [comment]
或者，在 markdown 头部的 Front-matter 里面加入 `description` 字段。优先会使用 `description` 字段的内容。

**Comment by eurusd** [comment]
没懂

**Comment by wongxingjun** [comment]
阅读全文的黑色按钮怎么开启？

**Comment by polarlights** [comment]
实现如这个主题的 Readme 样式是否方便？ http://litten.github.io

**Comment by BiggerGao** [comment]
You can find the key 'auto_excerpt:' in _config.yml of next's theme.Then set enable true,length express the length of abstract.After setting like this:
auto_excerpt:
  enable: true
  length: 150

**Comment by zsmlinux** [comment]
@BiggerGao but it not change it't lines

**Comment by BiggerGao** [comment]
@zsmlinux I don't understand ur mean.

**Comment by ChaosSoong** [comment]
为什么我在  文章.md  中加入之后,在首页起作用了,点击阅读全文后,以下的内容也不会显示了

**Comment by bartontang** [comment]
想问下，为什么本地hexo s 显示都是OK的，hexo d提交github后却是显示不全的，内容都不显示，就头像出来了，谢谢~！

**Comment by ygcaicn** [comment]
首页文章与文章间的区分度太小了，还有就是题目的文字还不如一级标题明显呢，，不合常理，望改进！

## `按下Ctrl点击->` [ `Gang blog`](http://blog.cumtpn.com/)

望指导更优的配置！

**Comment by CallMeSirLiu** [comment]
好使 ，description 字数太少了

**Comment by kuyeduwu** [comment]
`<!--more-->` 正解

**Comment by chenHongbin** [comment]
@kuyeduwu  这个要放在哪里呢？如何使用呢？

**Comment by CallMeSirLiu** [comment]
@chenHongbin 直接在博客里面写就行了，这样在列表里面就能看到，
<img width="697" alt="github" src="https://cloud.githubusercontent.com/assets/7090699/21974029/4574a5dc-dbff-11e6-9f2c-f78f10bc379f.png">
![more](https://cloud.githubusercontent.com/assets/7090699/21974030/45996caa-dbff-11e6-958b-64965443ad78.png)

**Comment by kuyeduwu** [comment]
@chenHongbin 在用文本编辑器编辑文章正文的时候直接使用就行，楼上的图片更直观。

**Comment by wendingp** [comment]
我本来可以加这行显示阅读全文的, 下了个插件然后就用不了了, 因为那个插件好像要删除原装 markdown 怎么重装 hexo markdown呢

**Comment by HowieMen** [comment]
在你需要折叠起来的地方插入

> 

即可

**Comment by TodLorry** [comment]
![2017-07-05 7 52 58](https://user-images.githubusercontent.com/12815340/27863679-de08f02a-61bd-11e7-9730-67339a3a65d3.png)
为什么我的分类数量明明是1个，缺显示“共有分类5个“呢

**Comment by HowieMen** [comment]
你好，很抱歉我也不太清楚为什么会这样显示。

2017年7月5日 20:09，"TodLorry" <notifications@github.com>写道：

[image: 2017-07-05 7 52 58]
<https://user-images.githubusercontent.com/12815340/27863679-de08f02a-61bd-11e7-9730-67339a3a65d3.png>
为什么我的分类数量明明是1个，缺显示“共有分类5个“呢

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/iissnan/hexo-theme-next/issues/62#issuecomment-313084427>,
or mute the thread

**Comment by haobangpig** [comment]
@nlpjoe I don't think it works well, cause it will display some code not naturally, the 
 will be the best answer in here.

**Comment by haobangpig** [comment]
```
<!--more-->
```
is the best answer

**Comment by ivan-nginx** [comment]
> is the best answer

Yes, it is.

**Comment by coolBoyGym** [comment]
前面各位提到的方法都试过了，个人认为最好用的还是在文章的合适位置添加****这种方法，不过有一点需要注意的是，必须将主题目录下配置文件里的**scroll_to_more**这个选项设置为**false**，这样当用户点击阅读全文时，可以跳转到全文的开始位置，而不是直接跳到我们所设置的****所在的位置，个人感觉这样可以给读者更好地阅读体验，推荐大家使用。

**Comment by coolBoyGym** [comment]
前面各位提到的方法都试过了，个人认为最好用的还是在文章的合适位置添加锚点(也就是)这种方法，不过有一点需要注意的是，必须将主题目录下配置文件里的**scroll_to_more**这个选项设置为**false**，这样当用户点击阅读全文时，可以跳转到全文的开始位置，而不是直接跳到我们所设置的锚点所在的位置，个人感觉这样可以给读者更好地阅读体验，推荐大家使用。

**Comment by mutouyu** [comment]
如果想截断文章，在首页显示文章摘录，可以试试在主题配置文件_config.yml中添加：
auto_excerpt:
  enable: true
  length: 150 #默认截取的长度为 150 字符
已经试过了，很好用

**Comment by xiaohupei** [comment]
配置文件配置后不行，文章中用 也不行，奇怪了
auto_excerpt:
enable: true
length: 150

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)**.
There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by mojitoming** [comment]
> 前面各位提到的方法都试过了，个人认为最好用的还是在文章的合适位置添加锚点这种方法，不过有一点需要注意的是，必须将主题目录下配置文件里的**scroll_to_more**这个选项设置为**false**，这样当用户点击阅读全文时，可以跳转到全文的开始位置，而不是直接跳到我们所设置的锚点所在的位置，个人感觉这样可以给读者更好的阅读体验，推荐大家使用。感谢 @CallMeSirLiu

正好需要这个设置～Thanks a lot～！
