### ISSUE TITLE
集成常用社交媒體的分享按鈕

### ISSUE THREAD

**Issue by hackjustu** [iissnan/hexo-theme-next#621]
可以在生成的網頁集成一些常用的社交媒體分享按鈕麼？ 比如像這樣https://www.addthis.com/get/sharing 。

只需要在html頁面插入一小段JS代碼就可以了。

本來想自己修改然後發個pull request，可惜不知道要修改哪個文件...

**Comment by Jasonnor** [comment]
预设有支援[JiaThis](http://www.jiathis.com/)等Share第三方服务，可以参考[这里](http://theme-next.iissnan.com/third-party-services.html #JiaThis)

不过Addthis的确挺好看，对英文使用者也比较友善

不知道@iissnan有没有加入这个扩展的想法？

**Comment by hackjustu** [comment]
谢谢 @Jasonnor 。我注意到JiaThis了，不清楚它有没有分享到Facebook、Twitter、Google+这些功能。还有，JiaThis的图标风格实在有点... 我还是喜欢AddThis的设计。

**Comment by flashlab** [comment]
@hackjustu [here](https://github.com/iissnan/hexo-theme-next/search?utf8=%E2%9C%93&q=jiathis)

**Comment by hackjustu** [comment]
@iissnan 已经提交了pull request了：）
https://github.com/iissnan/hexo-theme-next/pull/660
