### ISSUE TITLE
不能高亮 LaTeX 代码

### ISSUE THREAD

**Issue by SteveWang1007** [iissnan/hexo-theme-next#622]
作者你好，我在尝试写一些LaTeX代码
``` tex
\usepackage{enumerate}
\begin{document}
This is a latex example
    \begin{enumerate}[(a)]
    \item this is a item example
        \item this is another item example
    \end{enumerate}
\end{document}
```

highlight.js 应该是支持TeX 的, 但是好像并不识别指定的语言。

**Comment by iissnan** [comment]
highlight.js 支持，Theme 的主题没有加上 Tex 的相关 class。我把几个可能用到的 class 都加上去了。

**Comment by iissnan** [comment]
![tex-hl](https://cloud.githubusercontent.com/assets/32269/13774708/541a9a08-eadb-11e5-91e7-6e13cd48a088.png)
![tex-hl-night](https://cloud.githubusercontent.com/assets/32269/13774733/92db1556-eadb-11e5-826e-878641556775.png)

**Comment by RuiqiangJiao** [comment]
加载宏包之后还是显示代码，未能在文中调用宏包的功能。这个不可实现吗?

**Comment by SteveWang1007** [comment]
测试成功了 感谢 @iissnan 。 @RuiqiangJiao 你是想问关于 enumerate 这个宏包的问题还是关于 next 这个主题的问题？ 我不是很理解你的问题。

**Comment by RuiqiangJiao** [comment]
如果我在markdown中需要某个宏包的功能，比如
\usepackage{mhchem}
\begin{equation}
\ce{2H2 + O2 ->[\text{燃烧}] 2H2O2}
\end{equation}
可以实现吗?

在2016-03-17 08:53:31，SteveWang1007notifications@github.com写道：

测试成功了 感谢 @iissnan 。 @RuiqiangJiao 你是想问关于 enumerate 这个宏包的问题还是关于 next 这个主题的问题？ 我不是很理解你的问题。

**Comment by RuiqiangJiao** [comment]
还有一个问题，0.5版本在打开用mathjax时，刚开始显示的是latex代码，反映一会之后，才显示公式的，以前的版本直接显示公式，这是怎么回事?

**Comment by iissnan** [comment]
@RuiqiangJiao NexT 并未解析你的 Latex 代码，只是单纯的展示。MathJax 的问题应该跟网络速度有关联。
