### ISSUE TITLE
Mist 主题手机显示

### ISSUE THREAD

**Issue by sdir** [iissnan/hexo-theme-next#623]
最新的0.5 mist 主题，在手机上显示不能自适应

**Comment by sdir** [comment]
在header-inner,main-inner,footer-inner的+mobile中加入width: auto;感觉作者是还没写完整。

**Comment by chendaojin** [comment]
请问一下是在哪个文件里修改

**Comment by chendaojin** [comment]
main-inner里面没有+mobile，它的width设置的是$content-desktop，我将width设置为auto就可以了。不知道会不会有什么其他后果。。

**Comment by jasonhzy** [comment]
1、source/css/_schemes/Mist/_header.styl  .header-inner  +mobile 添加width: auto;
2、source/css/_schemes/Mist/index.styl  .footer-inner  +mobile 添加width: auto; 
3、 source/css/_common/outline/outline.styl .main-inner 添加+mobile() { width: auto; }

**Comment by zhezhang007** [comment]
都改成width: auto了，还是不行。

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
