### ISSUE TITLE
主页只显示一篇文章

### ISSUE THREAD

**Issue by MaxineCaulfield** [iissnan/hexo-theme-next#628]
commit记录：
https://github.com/MaxineCaulfield/maxinecaulfield.github.io/commit/f9842593e42febfaa6a9ac1fc794fa6ef05d7475

单单只是修改了头像文件，hexo g重新生成后的index主页却只有一篇文章，其余两篇却给删除了。这是什么原因导致的呢？

**Comment by Eamonnzhang** [comment]
试试以下命令：
hexo clean
hexo g
hexo g  
hexo d

**Comment by MaxineCaulfield** [comment]
谢谢 原来需要重新生成2次

**Comment by chenjuntong** [comment]
@MaxineCaulfield 请问需要两次hexo g的原因是什么呢？有一次g就可以的方法吗？

**Comment by lixingcong** [comment]
我的是第二页只显示一篇文章。。。
悲剧，换回next主题

**Comment by lijundong** [comment]
两次生成，问题解决了，谢谢

**Comment by iissnan** [comment]
是使用最新的 NexT 版本出现这个问题吗？

**Comment by lijundong** [comment]
不是最新版本，今天更新了，可以了，谢谢
