### ISSUE TITLE
toc_list_number: false 不起作用？

### ISSUE THREAD

**Issue by goxofy** [iissnan/hexo-theme-next#63]
把 toc_list_number设置为false之后，右边栏还是显示“当前文章没有目录”

顶部也是两栏，一个文章目录，一个站点概况

**Comment by mingmings** [comment]
@goxofy 在主题的配置文件里也得关掉，默认主题的 `toc_list_number: true`，你得改掉

**Comment by goxofy** [comment]
@mingmings 你好，您指的是landscape这个主题的配置文件？我看这个主题的_config.yml里面没有 toc_list_number 这一项啊。。。

然后我只是把NexT 的配置文件里的toc_list_number改成了false，没找到其他哪个地方还有这个设置。。

**Comment by mingmings** [comment]
@goxofy  就是 `next` 主题里的这个开关改成了 `false` ，然后你可以在站点的配置文件里在定义 `toc_list_number` 成 `false`，最后还不生效，检查下你的 `markdown` 的前几行里的 `toc` 是不是设置成了 `true`

**Comment by iissnan** [comment]
`toc_list_number` 只是设置是否自动添加目录的数字索引，不是用于控制是否显示 `toc`。

**Comment by goxofy** [comment]
那这个toc 是在哪里进行控制的啊，就是只让侧边栏显示站点概况那一项，不需要显示目录

然后还有个问题，就是为啥我的归档点开之后直接就是全文显示，不是那种树状的只显示文章题目的样式。。

这是我的站  http://hexo.tink.im ,麻烦帮忙看看，首页边栏感觉样式有问题。。

**Comment by iissnan** [comment]
@goxofy `:permalink` 目前不支持 `/:tile` 或者 `/:category/:title` 这种形式的。详见：https://github.com/iissnan/hexo-theme-next/issues/50

**Comment by iissnan** [comment]
另外， `toc` 目前没有开放设置去关闭。

**Comment by goxofy** [comment]
也就是说如果我想不显示toc的话需要手动去改生成的页面了？

**Comment by iissnan** [comment]
改主题的样式文件或者模板

**Comment by goxofy** [comment]
好的，谢谢！

**Comment by goxofy** [comment]
研究了半天还是不懂怎么改。。前端真是一点也不明白。要是后面版本能加上toc开关就好了

**Comment by iissnan** [comment]
我会考虑加一个选项。

**Comment by goxofy** [comment]
感谢！

**Comment by gaoryrt** [comment]
同样建议增加 toc 开关

**Comment by iissnan** [comment]
Master 分支最新修改（[13afdba](https://github.com/iissnan/hexo-theme-next/commit/13afdba0fefb1f885a0edeed92801363cd475874) ）已新增 `toc` 设置项，具体设置说明如下：

```yml
toc:
  # 是否启用 TOC
  enable: true # false

  # 是否自动添加 TOC  索引 （原 toc_list_number 设置项）
  number: true # false
```

另外，`toc_list_number` 设置项已废除。
