### ISSUE TITLE
markdown unordered list 解析不了

### ISSUE THREAD

**Issue by cielpy** [iissnan/hexo-theme-next#630]
用的最新的版本 https://github.com/iissnan/hexo-theme-next/commit/5398924d034f95bc689871d84cddce5b1e7c0c1b

![image](https://cloud.githubusercontent.com/assets/3138493/12535830/8648efe4-c2cb-11e5-973f-3d78a34aaa17.png)
本地预览和用别的主题试了下，都是可以正常解析的
用 next 生成的网页中是这样的
![image](https://cloud.githubusercontent.com/assets/3138493/12535834/ab92842c-c2cb-11e5-91c0-2cd587339e1d.png)

**Comment by KwenString** [comment]
是作者设定的省略了,  你 cd 到 next/source/css 用 ag 搜索看看
```
_common/scaffolding/base.styl
56:ul { list-style: none; }

_schemes/Mist/_base.styl
14:ul li { list-style: circle; }

_schemes/Pisces/_menu.styl
18:  list-style: none;
```

**Comment by cielpy** [comment]
哦哦，谢谢

**Comment by caiyongmin** [comment]
我昨天也奇怪这个问题，最后自己加上了。

**Comment by iissnan** [comment]
已修复 #688
