### ISSUE TITLE
可以用instantClick加快访问

### ISSUE THREAD

**Issue by shinelinxx** [iissnan/hexo-theme-next#632]
http://kevinsfork.info/2015/02/25/hexo-speedup-instantclick/
效果不错。

**Comment by Acris** [comment]
为了加一个功能，要去改一堆代码去适应这个新功能，而且可能还有无法预料的BUG，感觉有点不值啊。
我之前也尝试过用instantClick，然后因为要去解决一堆后遗症而放弃了...我现在博客访问也不算慢，https://blog.mrx.one/ 不过要是@iissnan 能加上并且解决后遗症那是再好不过的啦

**Comment by shinelinxx** [comment]
@Acris 确实，你的博客很快。除了把动画去了，有用别的加速吗？
