### ISSUE TITLE
ios手机端Safari测试，网页显示不正常

### ISSUE THREAD

**Issue by skycrown** [iissnan/hexo-theme-next#634]
我用移动端Safari浏览器测试网页，只显示大体框架，但是没有文字，我的网站是skycrown.github.io，不知道大家遇到过同样的问题吗？

**Comment by ixiusama** [comment]
并没有显示不正常呀。
ios 9.2

**Comment by skycrown** [comment]
哦，那可能浏览器是旧版的原因

**Comment by songyibin** [comment]
@skycrown 我的网站在移动端上显示不适应，能给我你的源代码试试吗？我的网站是songyibin.github.io。

**Comment by jframe9** [comment]
现在的版本在7.4以后还是有这个问题

**Comment by stevenjoezhang** [comment]
7.4以后只支持iOS 13和macOS 10.15
