### ISSUE TITLE
blog/categories/XXX/ 404错误

### ISSUE THREAD

**Issue by wmhjeremy** [iissnan/hexo-theme-next#635]
blog/categories/XXX/ 有的分类标签能打开，但是有的分类标签打开了显示404 File not found 有知道什么原因的吗？先谢谢了。

**Comment by zoakerc** [comment]
via：[标签和分类页面的统计数据不正确](http://theme-next.iissnan.com/faqs.html#标签和分类页面的统计数据不正确)

**Comment by wmhjeremy** [comment]
@zoakerc 按照那样做过，但是也是没有解决~

**Comment by wmhjeremy** [comment]
@zoakerc 我发现 只要 hexo d 之后，打开db.json后，就是这样子了{"meta":{"version":1,"warehouse":"1.0.2"},"models":{"Asset":[],"Cache":[],"Category":[],"Data":[],"Page":[],"Post":[],"PostAsset":[],"PostCategory":[],"PostTag":[],"Tag":[]}}

**Comment by zoakerc** [comment]
我的博客执行 `hexo g && hexo d` 后 `db.json` 内容如下：
```json
{
	"meta": {
		"version": 1,
		"warehouse": "1.0.3"
	},
	"models": {
		"Asset": [],
		"Cache": [],
		"Category": [],
		"Data": [],
		"Page": [],
		"Post": [],
		"PostAsset": [],
		"PostCategory": [],
		"PostTag": [],
		"Tag": []
	}
}
```
但是我的博客网站的链接和分类是没有问题的，你可以发一个你的博客网站标签链接上来反馈这个问题，看看是否能够重现。

---

发一个我用的 win环境下 `hexo clean.bat` 文件，放于hexo 根目录下执行。
```cmd
@echo off
:: 删除 .deploy_git public 目录
rd /s /q .deploy_git public
del db.json
del debug.log
exit
```
清理完成之后，再试试  `hexo g -f && hexo d`

**Comment by iissnan** [comment]
更新下主题，然后执行 `hexo clean` 后再看下是否有问题。

**Comment by wmhjeremy** [comment]
@iissnan 恩，已经好了，谢谢作者。

**Comment by jeekwong** [comment]
@wmhjeremy @iissnan 
我也遇到这个问题，我按上述命令操作后，在本地打开blog/categories/XXX/ 全部正常，每个点击都OK。
但当我部署到github后，有若干个blog/categories/XXX/ 404错误，不是全部404，😫

**Comment by wmhjeremy** [comment]
@jeekwong 之前的版本是这样的，作者更新了版本后，我这边更新后就没发现这个问题了

**Comment by iissnan** [comment]
@jeekwong 删除掉 `.deploy_git` 再部署试试

**Comment by JslinSir** [comment]
mac环境下 按照上述操作没用
