### ISSUE TITLE
Hexo + github 搭建的个人博客添加的多说评论插件 设置分享后点击“+分享到” 竟然跳转了

### ISSUE THREAD

**Issue by jasonhzy** [iissnan/hexo-theme-next#636]
Hexo + github 搭建的个人博客添加的多说评论插件 设置分享后点击“+分享到” 竟然跳转了，提示“缺少service参数”

**Comment by iissnan** [comment]
这是 多说 的 BUG，.ds-share 底下的 a 点击事件都有注册，但没有排除 “+分享到” 这个 a。
