### ISSUE TITLE
上传显示的主题风格与本地预览的不一致

### ISSUE THREAD

**Issue by zhangleijuly** [iissnan/hexo-theme-next#637]
本地Muse上传后显示Mist
本地Mist上传后显示Pisces
本地Pisces上传后显示Muse
hexo s本地预览一切正常
原因不明

**Comment by dxjia** [comment]
@zhangleijuly 我也遇到这个情况，原因是中途更换过主题，在public目录下生成的静态文件可能混乱了，我使用下面的步骤重新生成后解决了。

> 先删除public目录
> npm install hexo
> npm install
> hexo g -d

**Comment by zhangleijuly** [comment]
@dxjia 多谢，我已经解决了
