### ISSUE TITLE
1月26号的版本（441092）主题Pisces的样式已经改坏了

### ISSUE THREAD

**Issue by myoss** [iissnan/hexo-theme-next#638]
我用hexo重新初始化了一个博客，然后把next主题克隆下来，主题代码里只修改了：scheme: Pisces

下面是本地预览的效果：

![qq 20160127170403](https://cloud.githubusercontent.com/assets/6986459/12608628/22bb9b3a-c518-11e5-8149-9d59c33db93c.png

**Comment by geekrainy** [comment]
把这个提交回退https://github.com/iissnan/hexo-theme-next/pull/612/files

**Comment by Haocen** [comment]
@geekrainy 退回该修改的话，会使得 Mist 主题不能在移动设备屏幕上自适应显示。
可能要加个判断。

**Comment by iissnan** [comment]
请更新至最新版本。
