### ISSUE TITLE
commit 版本5398924d034f95bc689871d84cddce5b1e7c0c1b中，sidebar的配置无效。

### ISSUE THREAD

**Issue by Seitran** [iissnan/hexo-theme-next#640]
commit 版本5398924d034f95bc689871d84cddce5b1e7c0c1b中，sidebar的配置无效。
必须将这段配置全部注释掉，然后使用旧有的配置sidebar: post才可以。

新版的配置如下，对post页是无效的。
sidebar:
  # Sidebar Position, available value: left | right
  position: left
  #position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  display: post
  #display: always
  #display: hide
  #display: remove

**Comment by NeilRon** [comment]
谢谢

**Comment by Abraxas101** [comment]
请问，旧版的sidebar配置在哪里可以找到？

**Comment by wujiyu115** [comment]
这个sidebar怎么不自动弹出来了,要点击一下才出来,旧版本是post加载完后sidebar会自动出来的

**Comment by iissnan** [comment]
最新的版本已经修正，请更新。
