### ISSUE TITLE
两种语言

### ISSUE THREAD

**Issue by lengyueyang** [iissnan/hexo-theme-next#641]
问一下，next 主题可以设置两种语言吗？
中文和英文的

**Comment by lengyueyang** [comment]
可以在中英文之间切换

**Comment by Haocen** [comment]
网站是静态的……

**Comment by lengyueyang** [comment]
嗯，这个我知道，我看到hexo官网的博客用的是light主题，支持中英文切换，所以问一下，谢谢了

**Comment by Haocen** [comment]
Hexo 官网应该是多生成了一份页面在对应语言的目录下。但也不是所有页面都有双语版本。

**Comment by ixiusama** [comment]
所以是不支持是吧，还想写个双语的 Blog 呢。

**Comment by Haocen** [comment]
你可以考虑为 Hexo 增加此功能，如通过浏览器 JavaScript 来判断来访者浏览器所设置的语言，然后重定向或修改页面上的对应元素。
简单重定向的话开发难度不是很大，就是你每次都得生成两份博客。
静态博客系统一般就只能是这样了。

**Comment by lengyueyang** [comment]
谢谢Haocen的提议，这个方法可以试一下

**Comment by RayJune** [comment]
@lengyueyang 请问一下现在有实现双语切换功能吗：>
