### ISSUE TITLE
如何扩大pices的文章宽度

### ISSUE THREAD

**Issue by Yaccc** [iissnan/hexo-theme-next#643]
![image](https://cloud.githubusercontent.com/assets/5906306/12694274/7955bc62-c763-11e5-88c7-0e13bb03b18a.png)
如图所示，我想如果能扩宽红线处的文章宽度，时候又可以调节的css或者配置呢？

万分感谢！

**Comment by NatLee** [comment]
不知道是不是
## \themes\next\source\css\_schemes\Pisces\_layout.styl
可以在裡面找找看

**Comment by Yaccc** [comment]
@NatLee 额，其实我不是很懂前端呢。也看不懂现在的高级css了，/(ㄒoㄒ)/~~

**Comment by NatLee** [comment]
不知道這是不是你要的 :+1: 
https://github.com/iissnan/hexo-theme-next/issues/124

**Comment by Yaccc** [comment]
@NatLee 这个只适合next主题，如果我按照这个改的话，文章左边会把栏目*遮掉*，就是左边会拉伸，并不是右边

**Comment by myoss** [comment]
pices主题全屏显示，[显示效果](http://myoss.github.io/)，如果符合你的需求请参考：[代码](https://github.com/myoss/hexo-theme-next)

**Comment by Yaccc** [comment]
@myoss 非常感谢，不知道你是改动是否很大呢？还是说修改几处css就行了

**Comment by myoss** [comment]
自己看吧，3个文件，[链接](https://github.com/myoss/hexo-theme-next/commit/ef87a48c169589aa1a512261abce967bfb3a6c9f)

**Comment by Yaccc** [comment]
@myoss 好的，非常感谢！！

**Comment by bhpike65** [comment]
@myoss 这样不大好看了，能不主页面的时候还是原来那样，进文章页面之后才全屏呢？
