### ISSUE TITLE
主页文章数量不完整（文件修改后）

### ISSUE THREAD

**Issue by cnbleu** [iissnan/hexo-theme-next#645]
next主题非常棒，第一次见到就立即换上了，感谢@iissnan的分享。

由于我是把Hexo作为服务器来使用的，所以每次文章有添加或者修改的时候，都是直接通过脚本去更新服务器上的对应文件。最初这个脚本执行的非常好，但我发现最近情况有点不一样：
1. 只要我修改了已经存在的文档，重新上传到服务器覆盖更新后，就无法在首页找到文章的入口了（其他的正常）；
2. 我可以在归档里面找到，而且可以正常打开。

我使用的是pisces（这款样式非常棒！）。

在此附上我出问题的博客：http://www.cnbleu.com
以及使用的自动更新脚本：https://github.com/cnbleu/HexoUp

**Comment by shuaitq** [comment]
我也有遇到，有的时候重启hexo就好了，有的时候修改一下文件就好了。不知到是哪里出错了。

**Comment by cnbleu** [comment]
@shuaitq 我现在重启也不可以。。切换成其他的theme就没问题了

**Comment by Jasonnor** [comment]
执行hexo clean或删除.deploy资料夹后在进行部署，不知道能不能解决问题？

**Comment by cnbleu** [comment]
@Jasonnor 我停止了hexo进程后，反复多次clean、generate之后才正常

**Comment by iissnan** [comment]
去除设置置顶的 script 后，这个问题应该修正了。请更新下主题，重新生成下试试。

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
