### ISSUE TITLE
配置 disqus 的 short_name 后，无法正常 load disqus

### ISSUE THREAD

**Issue by polarlights** [iissnan/hexo-theme-next#646]
按照 wiki 设置了`disqus_shortname`，但是有个奇怪的现象是提示`We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.`，不知道@iissnan 是否在本地或者部署到 github page 后，是否有遇到此类问题？谢谢

**Comment by polarlights** [comment]
Re: 写错一个字母，调试一个下午……

**Comment by Foucsing** [comment]
我也是出现这个问题，但是检查没发现写错字母，，，

**Comment by polarlights** [comment]
@Foucsing  你可以把你的项目推到 github，可以帮你看下

**Comment by GongchuangSu** [comment]
@Foucsing 同样的问题，问题解决没？

**Comment by justyouhappy** [comment]
同问
