### ISSUE TITLE
自动摘要不展示图片

### ISSUE THREAD

**Issue by coolrc136** [iissnan/hexo-theme-next#648]
开启`auto_excerpt`后自动生成的摘要里只会在首页展示文章开头150个字，不能展示我放在文章最前面的图片，但是`<!--more-->`标签却可以展示图片

**Comment by urzone** [comment]
+1

**Comment by hackjustu** [comment]
有意思 我一般只用

**Comment by iissnan** [comment]
是的，目前 `auto_excerpt` 暴力的将 html tag 都过滤掉。或许可以用正则匹配第一个 `img` 标签，并将其保留下来。

**Comment by iissnan** [comment]
建议使用  的方式，除了可以精确控制需要显示的摘录内容以外， 这种方式也可以让 Hexo 中的插件更好的识别。
