### ISSUE TITLE
标题里面如果有Promise关键字，会导致页面显示出错！

### ISSUE THREAD

**Issue by xtutu** [iissnan/hexo-theme-next#649]
http://www.xtutu.me/helloworld/
可以在这里调试。

就是因为md文件里面有这个标题。
```js
# Promise
```
chrome没问题，IE之类的浏览器会报错：
![qq 20160203110226](https://cloud.githubusercontent.com/assets/12950709/12771630/982c63de-ca65-11e5-83db-fa3f166fc07f.jpg)

麻烦能够修复下。也许是hexo的问题。

**Comment by iissnan** [comment]
已修复。

**Comment by xtutu** [comment]
幸苦啦

**Comment by iissnan** [comment]
此问题应该已经修复，若再次发现请 reopen 或者重新提一个 ticket，谢谢。
