### ISSUE TITLE
首页设定

### ISSUE THREAD

**Issue by ShallYan** [iissnan/hexo-theme-next#65]
next主题感觉很赞，想请问一下，它是否支持设定首页呢？比如我想博客已进入首先显示的是某个page，如about。有这个问题的原因是我想把博客首页设置成自己的简历，然后可以通过上面的home什么的进入博客，谢谢啦。

**Comment by mingmings** [comment]
@ShallYan 作者下个功能就会实现，耐心等等

**Comment by ShallYan** [comment]
@mingmings OK，thanks
