### ISSUE TITLE
首页评论数显示问题

### ISSUE THREAD

**Issue by VoidSun** [iissnan/hexo-theme-next#653]
@iissnan 博主麻烦看下首页评论数显示问题，找了很久也没找到把哪一个改错了。在issues里面找了好几遍也没有类似的问题，麻烦了！灰常感谢！
![qa](https://cloud.githubusercontent.com/assets/9758422/12807438/2a5353b4-cb4a-11e5-8de6-8b39db4f2c1f.png)

**Comment by iissnan** [comment]
你多说的 shortname 可能设置错了，或者是你在模板里有改到这个 

```
http://voidsun.duoshuo.com/xxx
你的变成了
http://http://voidsun.duoshuo.com/.duoshuo.com
````

**Comment by VoidSun** [comment]
谢谢博主的耐心解答，非常喜欢next主题！

**Comment by vitahlin** [comment]
@iissnan @VoidSun 
你好，我也出现了这个问题，但是我的多说应该设置没错，上网查了下，多说shortname就是xxxx.duoshuo.com，里面的xxxx就是你的多说shortname吧，是否是因为设置了中文显示，但是zh-Hans.yml文件里面没有增加对应的翻译的问题？如果是的话，应该增加哪个单词的翻译，可否告知，谢谢。

**Comment by vitahlin** [comment]
我尝试用了Google Chrome的开发者模式，发现页面会打印出如下错误:
![1af2962f-b5a6-4139-b8f9-60bb3b48f500](https://cloud.githubusercontent.com/assets/6998610/20826942/79798ab0-b8a9-11e6-9403-d16f9e5657b2.png)

看这边显示的链接是vitah.duoshuo.com.duoshuo.com，我的多说域名是vitah.duoshuo.com，但是我在主题配置文件里面设置的duoshuo_shortname是vitah，不知道还需要改动哪里，有建议吗？谢谢。

**Comment by vitahlin** [comment]
重新下载安装后，不出现console log错误，但还是会显示两条竖线，应该是之间的评论数目不显示。看了下，其他博客的一些主题显示正常，网页源代码里面 ：
```c
<span id="/blog/Hexo之旅-三-：Hexo博客个性化及NexT主题配置.html" class="leancloud_visitors" data-flag-title="Hexo之旅(三)：Hexo博客个性化及NexT主题配置">
               &nbsp; | &nbsp;
               <span class="post-meta-item-icon">
                 <i class="fa fa-eye"></i>
               </span>
               <span class="post-meta-item-text">阅读次数 </span>
               <span class="leancloud-visitors-count"></span>
              </span>
```

而我的页面源代码：
```c

              <span class="post-comments-count">
                <span class="post-meta-divider">|</span>
                <a href="/posts/51475956/#comments" itemprop="discussionUrl">
                  <span class="post-comments-count ds-thread-count" data-thread-key="posts/51475956/" itemprop="commentCount"></span>
                </a>
              </span>
```
是否是这个原因？
