### ISSUE TITLE
請問為何next.muse主題的文章在手機無法自適應

### ISSUE THREAD

**Issue by kintsuicris** [iissnan/hexo-theme-next#655]
rt, 文章無法自適應，但是側邊欄之類的沒有問題。
請問是設置的問題嗎？？

**Comment by cinthisime** [comment]
参考: https://github.com/iissnan/hexo-theme-next/pull/612
但是这个修改会导致在pisces下布局错乱。

**Comment by FredXue** [comment]
同样的问题，请问有什么解决办法？

**Comment by FredXue** [comment]
@cinthisime  似乎只有main-inner中的max-width被改成了width。

**Comment by iissnan** [comment]
已测试最新版本的代码可以正确适配，请更新
