### ISSUE TITLE
修改站点title

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#66]
你好，请问一下，如果是调整这个黑色的形状，是配置文件么，还是样式文件
![image](https://cloud.githubusercontent.com/assets/3365500/6841322/5076084a-d3c3-11e4-92af-489f340b70f1.png)

**Comment by iissnan** [comment]
在样式文件里，`_custom.styl`。

**Comment by mingmings** [comment]
@iissnan tks
