### ISSUE TITLE
请问如何取消移动端适配,或者可否进行切换???

### ISSUE THREAD

**Issue by wbing-xu** [iissnan/hexo-theme-next#662]
目前用的是pisces, 在平板上使用时也会给切换到移动端,那样看着效果不怎么样.想切换成和电脑上一样

然后我查了下mobile,试着修改 source/js/src/utils.js 中判断是否移动设备的函数中修改,直接改成return false, 但是没有作用,不懂前端......

所以想问下这要如何修改呢?

**Comment by iissnan** [comment]
布局是通过 CSS 的 Media Query （检测设备的宽度）来实现的，并非 JavaScript 控制。在这种情况下貌似是很难做取消或者切换。
