### ISSUE TITLE
table元素在手机端造成页面被撑开

### ISSUE THREAD

**Issue by zhanfang** [iissnan/hexo-theme-next#663]
改table的父元素为改为可滚动元素，如下：

	.posts-expand .post-body {
		text-align: justify;
		overflow: scroll;
	}
具体信息链接: http://zhanfang.github.io/2016/02/15/hexo-bug/

**Comment by iissnan** [comment]
我在想让 table 自动适应比更改 `post-body` 会更合适一点

**Comment by iissnan** [comment]
另外，设置 `overflow` 为 `scroll` 后，即使容器可以容纳的下内容，浏览器还是会显示滚动条。

![ss-20160308104847](https://cloud.githubusercontent.com/assets/32269/13590557/b7b21a8e-e51b-11e5-9b40-12c2a93af8fe.png)

**Comment by Haocen** [comment]
已提交修复 #718 。
