### ISSUE TITLE
给自己的博客打个广告,压缩next博客代码

### ISSUE THREAD

**Issue by zhangjh** [iissnan/hexo-theme-next#665]
next主题经hexo编译后生成的静态文件代码有很多多余的空白,不知道是hexo的原因还是next的原因,不过貌似我修改过next的源码没起作用.

我用gulp优化了一下,有需要的可以参考下.

[使用gulp精简优化hexo博客](http://www.5941740.cn/2016/02/19/%E4%BD%BF%E7%94%A8gulp%E7%B2%BE%E7%AE%80hexo%E5%8D%9A%E5%AE%A2%E4%BB%A3%E7%A0%81/)

**Comment by cinthisime** [comment]
good job

**Comment by ixiusama** [comment]
呃..然而您并没有说要怎么才能使用它呢？至少我没有看到具体的使用方法。

**Comment by flashlab** [comment]
[hexo-all-minifier](https://github.com/unhealthy/hexo-all-minifier) is enough

**Comment by zhangjh** [comment]
@flashlab 嗯，看看去，尝试下有没有用

**Comment by zhangjh** [comment]
@ixiusama 没写清楚吗？照着博客里的“优化实践”部分自己试下呢，我只是分部分来说了，没有把所有部分放在一起。你可以看这儿吧，[我的博客的源文件](https://github.com/zhangjh/hello-blog/blob/master/gulpfile.js)

**Comment by zoakerc** [comment]
@zhangjh 可以参考我的这篇文章：https://zoakerc.com/archives/minify-static-resources-in-hexo-by-gulp-plugins/

**Comment by iissnan** [comment]
多谢分享，加了 `Optimization` Label，方便想要做优化的人查询。

**Comment by zhangnew** [comment]
@ghost 网站挂了
