### ISSUE TITLE
教程文档内的tab页怎么写的？

### ISSUE THREAD

**Issue by ybdengzheng** [iissnan/hexo-theme-next#666]
* 在教程文档内有的内容步骤一，二，三采用tab页的方式感觉很好。但是我在markdown语法里面没有找到怎么写tab。能告诉我怎么写的吗？
* 有没有考虑增加时序图，流程图，UML等语法的支持？
* katex比mathjax效率更高，建议更换。

**Comment by iissnan** [comment]
1. 使用 tab 感觉是比较繁琐的一个过程，在文档站点我写了一个 tag，Markdown 本身不支持。
2. 图表语法可以看看是否有其他的 Markdown Parser 可以支持
3. 不太清楚 Katex 和 MathJax 的写法是否相同，如果不相同可能会导致已在使用 MatxhJax 的文章失效，我建议你可以自己切换到 Katex。

**Comment by ybdengzheng** [comment]
非常感谢回答。能给我看看你的tag怎么写的吗？学习一下。

**Comment by iissnan** [comment]
请参看 [Tab filter](https://github.com/iissnan/theme-next/blob/master/themes/luminosa/scripts/tab.js)。需要注意的是，这个 filter 所输出的内容是基于 [Semantic UI](http://semantic-ui.com/) 的，就是还需要结合Semantic UI 这个 UI 框架。

**Comment by ybdengzheng** [comment]
非常感谢，搞定了。
