### ISSUE TITLE
问下手机上能不能也显示sidebar的文章目录

### ISSUE THREAD

**Issue by q6413260** [iissnan/hexo-theme-next#667]

**Comment by ivan-nginx** [comment]
@q6413260 dont understand u, write in English if not solved. If solved, close it please.

**Comment by thqy39** [comment]
后来怎么解决的？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
