### ISSUE TITLE
如何实现页面加载中的过渡动画

### ISSUE THREAD

**Issue by wendaosanshou** [iissnan/hexo-theme-next#669]
刚看到一处有过渡动画的博客，是页面没加载完成前先加载过渡动画，觉得效果很好。请问大家知道是怎么实现的吗。
[ceoimon.com](http://ceoimon.com/)

**Comment by guiyanakuang** [comment]
通过域名搜到https://github.com/ceoimon/ceoimon.github.io
/js/antimoderate.js 配合svg图片吧_(:зゝ∠)_

**Comment by iissnan** [comment]
简单的实现原理：

1. 新增一个动画层（可以是 GIF 图片 或者 样式控制的节点）
2. 隐藏主体内容
3. 在资源加载完毕时触发事件，隐藏动画层，并显示主题内容。

细节会比较多。

**Comment by Haocen** [comment]
酷是挺酷的，但一个静态网站动画如果太多的话就失去速度快这个优势了……

**Comment by Haocen** [comment]
@wendaosanshou 出于对这个动画实现本身的兴趣我稍微研究了下，作者使用的不是普通的动画，而是利用 CSS 实现的 SVG 动画，实现起来并不麻烦：
> http://mooc.guokr.com/post/614671/
