### ISSUE TITLE
【bug】最新的NexT.Pisces主题进入文章后，侧边栏目录显示错误【已找到解决方法】

### ISSUE THREAD

**Issue by vinnyxiong** [iissnan/hexo-theme-next#671]
最新的NexT.Pisces主题进入文章后，整个页面会向左偏移，而且侧边栏的文章目录显示不出来。哪位大神帮忙修复一下这个bug？
bug预览： http://vinnyxiong.github.io/blog/2016-02-22-hello-world.html
非常喜欢nexT主题，而这几个子主题中最喜欢Pisces主题。

**Comment by midiao** [comment]
你好，我想问一下Pisces主题怎么启用？

**Comment by vinnyxiong** [comment]
@midiao 在主题配置文件_config.yml中，将Pisces主题打开，其实默认是注释掉了，把默认的注释掉就行了

# Schemes
#scheme: Muse
#scheme: Mist
scheme: Pisces

**Comment by vinnyxiong** [comment]
终于找到解决这个问题的方法。
将主题配置文件_config.yml中的`sidebar:`改为隐藏的就行了，`display: hide`。
其实这个`display`属性主要是针对另外两个scheme的。
相应的，`position: left`属性也仅对`Pisces`主题有效。

**Comment by never615** [comment]
我试用Pisces，一打开网站，页面内容就自动靠左了。。。

**Comment by vinnyxiong** [comment]
@never615 把display属性设置为 hide

**Comment by panzhitian** [comment]
我还奇怪怎么style会自己加了个`padding-right: 320px`，以为是更新带进的bug
