### ISSUE TITLE
文章标题文字字体怎么修改

### ISSUE THREAD

**Issue by coderluo** [iissnan/hexo-theme-next#672]
我的博客标题文字字体好像有问题

**Comment by iissnan** [comment]
具体是什么问题？

**Comment by Haocen** [comment]
@iissnan 不如设置一个 `ISSUE_TEMPLATE` 吧。现在的问题报告往往都缺少必要的信息。
https://github.com/blog/2111-issue-and-pull-request-templates
@coderluo 请添加截图和出现问题的链接，以便我们帮助你解决问题。 GitHub 现在支持拖拽上传截图和文件了。

**Comment by ivan-nginx** [comment]
@coderluo dont understand u, write in English if not solved. If solved, close it please.
