### ISSUE TITLE
谷歌字体被墙问题head.swig改成360的CDN

### ISSUE THREAD

**Issue by vinyo** [iissnan/hexo-theme-next#676]
\themes\next\layout\_partials\head.swig
32行改成
<link href="//fonts.useso.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">

**Comment by geekrainy** [comment]
目前谷歌的字体库在中国大部分地区已经解除屏蔽，用360的字体库不支持https。
