### ISSUE TITLE
NexT.Pisces主题能否把侧边栏显示到右侧？

### ISSUE THREAD

**Issue by skycrown** [iissnan/hexo-theme-next#677]
Pisces主题中侧边栏始终在左侧，想更改到右侧，该怎样设置，更改主题配置文件中 position: right，并不起作用，该怎么做？ @iissnan

**Comment by iissnan** [comment]
更改 `position: right` 设置是正确的，如果没作用，就是 bug。

**Comment by skycrown** [comment]
哦，原来是我把上面的sidebar用#注释掉了，所以下面改position就无效了，不好意思，是我弄错了~
