### ISSUE TITLE
mist主题在手机上浏览内容区没有自动缩放，为固定的 700px

### ISSUE THREAD

**Issue by oblank** [iissnan/hexo-theme-next#679]
RT
需像header那像在小屏幕上让 .menu-inner 宽度变成自适应

**Comment by azone** [comment]
我也遇到了这个问题，求修复！

**Comment by iissnan** [comment]
PR #681 应该修复这个问题了，请更新

**Comment by zhezhang007** [comment]
#681 修改完，同时加上 padding: 0px；
.container .main-inner {
  +mobile() {
    width: auto;
    padding: 0px;
}
}

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
