### ISSUE TITLE
CNAME相关

### ISSUE THREAD

**Issue by zmwu** [iissnan/hexo-theme-next#68]
关联域名时要在仓库下建一个CNAME文件，如果在github上写的话，下一次更新就不见了，那样域名访问会找不到。如果在本地写的话，似乎部署不上来，怎么解决呢？谢谢

**Comment by iissnan** [comment]
将 CNAME 放到站点的 `source` 目录下就行。

**Comment by zmwu** [comment]
谢谢 明白了
