### ISSUE TITLE
建议加入文字首行缩进

### ISSUE THREAD

**Issue by panzhitian** [iissnan/hexo-theme-next#680]
中文首行缩进感觉可以提供更佳的阅读体验，如果用全角空格或者转义符，一个是书写不便，二是可能会在压缩的时候删掉，所以还是要从css入手。

**Comment by iissnan** [comment]
这个自定义下就行。修改 `source/css/_custom/custom.styl` 文件，新增：

```
.post-body p { text-indent: 2em; }
```

**Comment by panzhitian** [comment]
@iissnan 这个我知道，只是建议加默认而已

**Comment by maxchendt** [comment]
有个问题，不知道如何解决？就是启用了之后，本来是一个段落，中间插入了一行代码用 blockcode 的方式显示，然后就麻烦了，单个段落被分成两个段落了，blockcode 之后的部分，被处理成新的段落，从而被首行缩进。
TeX中可以用 \noindent{} 来实现后半部分的不缩进。

**Comment by maxchendt** [comment]
https://github.com/xtfly/hugo-theme-next/issues/1#issuecomment-246600886 解决特定段落不缩进

**Comment by lumos0314** [comment]
> 这个自定义下就行。修改 `source/css/_custom/custom.styl` 文件，新增：
> 
> ```
> .post-body p { text-indent: 2em; }
> ```

引用部分不想缩进怎么办呀~

**Comment by svandex** [comment]
更新后没有了_custom文件夹和custom.styl文件啊，这个功能能不能增加到config里

**Comment by stevenjoezhang** [comment]
@svandex `custom.styl`这个功能还在，现在改为了`custom_file_path`
