### ISSUE TITLE
归档不起作用

### ISSUE THREAD

**Issue by zhangxiaochen** [iissnan/hexo-theme-next#682]
我的归档按要求设置好了之后一直不起作用，主题中的config中设置如下：

> menu:
>   home: /
>   categories: /categories
>   #about: /about
>   archives: /archives
>   tags: /tags
>   #commonweal: /404.html

HEXO的config设置如下：

> tag_dir: /source/tags
> archive_dir: /source/archives
> category_dir: /source/categories
> 
> archive_generator:
>   per_page: 20
>   yearly: true
>   monthly: true

新建的archives页面内容如下：

> title: 归档
> date: 2015-10-12 21:29:42
> type: "archives"
> comments: false

我的博客地址，归档没用任何内容
http://zhangxiaochen.top/

**Comment by iissnan** [comment]
归档页面不需要手工去创建

**Comment by zhangxiaochen** [comment]
原来如此，多谢
