### ISSUE TITLE
求助：怎么让友情链接，一行一个链接

### ISSUE THREAD

**Issue by wens07** [iissnan/hexo-theme-next#684]
恩，由于不懂前端，所以想请路过的前端大神帮个忙，NexT.Pisces主题下那个分享链接怎么一个链接一行啊，现在貌似这个链接标题字数稍微多点就会分成两行了(尤其是英文字母的情况)，可以看看链接的图片，更好的理解我的意思
[链接名字被分行](http://7xq5br.com1.z0.glb.clouddn.com/%E5%8F%8B%E6%83%85%E9%93%BE%E6%8E%A5.png)

**Comment by iissnan** [comment]
嗯，确实有这个问题。目前友情链接使用的样式与 social sites 的相同，我会将其设置成单行的。

**Comment by iissnan** [comment]
已重新设定有请链接的样式，请更新主题

**Comment by Zeecoders** [comment]
更新主题后，友情链接还是会一行显示两个。。
