### ISSUE TITLE
评论区公式显示问题

### ISSUE THREAD

**Issue by ruiqiangJiao** [iissnan/hexo-theme-next#685]
将hexo\themes\next\layout_scripts\third-party\comments\duoshuo.swg中的
(document.getElementsByTagName('head')[0]
改成:
(document.getElementById('footer')
结果之前评论区的结果不显示了,怎么解决

**Comment by RuiqiangJiao** [comment]
评论区公式不显示了成了代码

**Comment by Haocen** [comment]
@RuiqiangJiao 自行修改主题模板导致的问题应该不属于 Bug 。你可以选择恢复这个文件到官方版本。
你可以选择提交相关功能请求，描述你需要的功能。

**Comment by RuiqiangJiao** [comment]
你好，我测试了一下，4.5版本可以在多说系统的评论区可以显示mathjax编辑的公式，5.0测试不行，不知如何解决!

在2016-03-15 02:40:11，Haocennotifications@github.com写道：

@RuiqiangJiao 自行修改主题模板导致的问题应该不属于 Bug 。你可以选择恢复这个文件到官方版本。
你可以选择提交相关功能请求，描述你需要的功能。

**Comment by Haocen** [comment]
@RuiqiangJiao 你可以做个回退测试，看一下是那次提交之后导致评论不能显示 mathjax 公式，然后我可以帮你修改这处代码，以便应用在最新版本的 NexT 上。但是能否合并到主分支要看作者能否同意，因为这个毕竟说不上是个 bug 。

**Comment by RuiqiangJiao** [comment]
好的，谢谢!

在2016-03-16 16:39:48，Haocennotifications@github.com写道：

@RuiqiangJiao 你可以做个回退测试，看一下是那次提交之后导致评论不能显示 mathjax 公式，然后我可以帮你修改这处代码，以便应用在最新版本的 NexT 上。但是能否合并到主分支要看作者能否同意，因为这个毕竟说不上是个 bug 。

**Comment by RuiqiangJiao** [comment]
在4.5.1中的多说评论区可以显示用mathjax的数学公式，5.0.0刷新好几次还是latex代码。

在2016-03-16 16:39:48，Haocennotifications@github.com写道：

@RuiqiangJiao 你可以做个回退测试，看一下是那次提交之后导致评论不能显示 mathjax 公式，然后我可以帮你修改这处代码，以便应用在最新版本的 NexT 上。但是能否合并到主分支要看作者能否同意，因为这个毕竟说不上是个 bug 。

**Comment by Haocen** [comment]
@RuiqiangJiao 具体是哪个提交？
> https://github.com/iissnan/hexo-theme-next/commits/master/layout/_scripts/third-party/comments/duoshuo.swig
这个是多说评论插件的修改历史，应该是其中一个修改导致了无法显示 mathjax 。

**Comment by ivan-nginx** [comment]
@ruiqiangJiao dont understand u, write in English if not solved. If solved, close it please.
