### ISSUE TITLE
请问next.muse主题中能否并排显示图片

### ISSUE THREAD

**Issue by kba977** [iissnan/hexo-theme-next#686]
有时候写博客有并排显示图片的需求，网上搜了好久没有找到解决方案， 我想要的效果类似于下面demo这种样子 [demo](https://mmistakes.github.io/hpstr-jekyll-theme/sample-post-images/)，求解决方案

**Comment by wucangeo** [comment]
我也有这样的需要，这可能得从[fancybox](http://fancybox.net/) 解决了。

**Comment by iissnan** [comment]
之前有做了一个试验性的图片排版方案，但是由于太难使用一直没有公开。我在想做一个类似 Markdown table 的 tag plugin 来支持这个特性。无论是图片或者文字都可以按照 table 的方式排版。

一个 Workaround 是使用 table..

**Comment by woshijpf** [comment]
同问这个问题，我也想知道 NexT.Pisces 主题中什么时候可以添加同一行中可以显示多张图片的功能，并且可以控制每张图片的大小尺寸

**Comment by ruijun** [comment]
同样有图片并排的需求。 

另外@woshijpf 可以使用
```
<img src="im.png"  width = "300" height = "200" />
``
来控制图片尺寸大小

**Comment by ivan-nginx** [comment]
@kba977 dont understand u, write in English if not solved. If solved, close it please.
