### ISSUE TITLE
点开文章后样式有问题，整页左移。

### ISSUE THREAD

**Issue by superqbb** [iissnan/hexo-theme-next#689]
整页左移，站点概述 ，目录模块会不见了，但是作者的博客是正常的。
http://natsumi.me/ 
具体请看我的博客。

**Comment by geekrainy** [comment]
PR #688 已修复，待 Merge.

**Comment by iissnan** [comment]
已 Merge，请更新

**Comment by vinnyxiong** [comment]
https://github.com/iissnan/hexo-theme-next/issues/671
