### ISSUE TITLE
首页分页有问题

### ISSUE THREAD

**Issue by ShomyLiu** [iissnan/hexo-theme-next#690]
```
index_generator:
  per_page: 5
```
按照教程这样设置， 只有第一页正常是5篇文章，但是从第2页开始，每一页只显示了一篇文章(有4篇没有显示)。 我想问一下，还有其他地方需要设置吗？
具体问题复现请看我的博客:  https://shomyliu.github.io

**Comment by ShomyLiu** [comment]
往前翻了翻issue, 找到了i个解决方法，就是每次 ``hexo g`两次。。。这个是为什么呢

**Comment by geekrainy** [comment]
hexo clean后再生成试试

**Comment by ShomyLiu** [comment]
@geekrainy   每次deploy都会clean的， 就是需要两次 g, 不知道为什么。。。

**Comment by geekrainy** [comment]
我这里没有这个问题，更新下hexo和依赖模块试试？

**Comment by Ethan-Zhang** [comment]
看一下_config.yml里面这一项`auto_detect: true`有没有写对吧，反馈这个的人挺多的，感觉是fork了某个错误的模板

**Comment by ShomyLiu** [comment]
@Ethan-Zhang  对，我也是`true` ，应该不是这个问题吧

**Comment by ShomyLiu** [comment]
@geekrainy  试过了--- 应该不是hexo问题，因为其他主题不能复现该问题

**Comment by iissnan** [comment]
应该是我在开发 “置顶” 功能时引入的 sticky filter 导致的问题。已将此文件移除。

**Comment by iissnan** [comment]
可以再试试看有没有问题

**Comment by ShomyLiu** [comment]
去掉了置顶就可以了，谢谢啦，忘记close了
