### ISSUE TITLE
4k屏效果太差

### ISSUE THREAD

**Issue by willin** [iissnan/hexo-theme-next#692]
![qq20160301-1](https://cloud.githubusercontent.com/assets/1890238/13416834/9c687456-dfa0-11e5-9242-5abff2b2b2d7.png)

**Comment by iissnan** [comment]
好 :sparkles: 的屏幕。Pisces 在其下看来好寒碜，有什么建议吗？

**Comment by willin** [comment]
宽度100%，margin的边距最大150px，sidebar宽度固定，content自适应宽度

**Comment by willin** [comment]
哦对了，还有一个比较普遍的问题，就是在4K屏下大多数网站的字都太小了。
字体单位可以用em，rem之类的。

**Comment by Haocen** [comment]
@willin 这个应该是 Win 系统目前的普遍问题。一些没有为高分辨率屏幕优化的本地程序界面也会显示的过于迷你。
我的做法是调整 DPI 并设置浏览器默认放大倍数。

**Comment by willin** [comment]
@Haocen 
谢谢，用的不是Windows；
而且这么小的字我看习惯了，屏幕中可以放置更多的内容，我不喜欢把页面缩放。

**Comment by Haocen** [comment]
@willin 唔，是 4k 屏幕的 Mac 啊。暂时不知道除了缩放之外的解决方法。你提议用 em 作为单位，实际上也就是用了浏览器字体的相对尺寸而已。如果不嫌麻烦，可以安装 Tampermonkey ，然后在所有你访问的网站上应用一个自定义的样式表。
具体信息可以看这里：
http://stackoverflow.com/questions/23683439/gm-addstyle-equivalent-in-tampermonkey

**Comment by LeoiOS** [comment]
请问这是什么显示器？

**Comment by willin** [comment]
AOC 便宜

**Comment by jcf94** [comment]
好可怕的分辨率......(⊙o⊙)

**Comment by ivan-nginx** [comment]
@willin dont understand u, write in English if not solved. If solved, close it please.

**Comment by willin** [comment]
4K screen works badly @ivan-nginx

**Comment by ivan-nginx** [comment]
@willin my anser in #1077.
