### ISSUE TITLE
表格内容多导致页面排版变形问题

### ISSUE THREAD

**Issue by imperio-wxm** [iissnan/hexo-theme-next#695]
当用markdown的表格时
|title|title|title|
|-----|----|-----|
|table|table|table|

如果表格中，内容比较多，会导致页面排版变形
PC端不明显，mobile端十分明显

![](http://7tt05h.com1.z0.glb.clouddn.com/wxmimperioIMG_0121.PNG)
![](http://7tt05h.com1.z0.glb.clouddn.com/wxmimperioIMG_0122.PNG)

**Comment by imperio-wxm** [comment]
图片失效了，补了一下图
这个Bug有人能解决吗？

**Comment by Haocen** [comment]
@imperio-wxm 可否发链接出来？我也怀疑是 CSS 某处宽度定义的有些问题。

**Comment by imperio-wxm** [comment]
@Haocen  blog链接吗？wxmimperio.tk 出现问题的文章：Spark 历史记录 Web 监控 [Spark JobHistory Web UI]

我试了一下，当markdown表格中的内容一多久会出现这种问题，内容少的时候不会

**Comment by Haocen** [comment]
初步判断是 table 相关的样式表有问题。
模拟 Nexus 5 访问的时候 table 尺寸出错了：
<img width="188" alt="table" src="https://cloud.githubusercontent.com/assets/10842569/13733039/cadc5ac4-e963-11e5-89ea-0325a0b3babb.png">

已找到解决方案：
需要为 table 样式增加以下两个属性：
word-wrap: break-word;
table-layout: fixed;

**Comment by imperio-wxm** [comment]
@Haocen 代码放在custom.styl的.code{}里可以吗？我放在了那里，好像不起作用，要放在tables.styl？

**Comment by Haocen** [comment]
@imperio-wxm CSS 的作用原则是最后加载的样式才能生效，大概是这个原因吧。

**Comment by imperio-wxm** [comment]
@Haocen 忘记加.table{}，已解决，非常感谢！！
