### ISSUE TITLE
是否考虑支持汉字标准格式 han-css

### ISSUE THREAD

**Issue by jingsam** [iissnan/hexo-theme-next#698]
[汉字标准格式](https://css.hanzi.co/) 是一套印刷品般的汉字排版框架，能否考虑在未来的版本中支持一下？

**Comment by iissnan** [comment]
看起来是个大工程

**Comment by jingsam** [comment]
跟据帮助文档，启用这个库似乎不难。

**Comment by Haocen** [comment]
@jingsam 要不试着实现一下然后提交一个合并请求吧。

**Comment by ivan-nginx** [comment]
@jingsam #1598.
