### ISSUE TITLE
能不能加个关于的样式支持?

### ISSUE THREAD

**Issue by HogwartsRico** [iissnan/hexo-theme-next#7]
能不能加个关于的样式支持,默认不显示,但是new page的时候可以有样式支持(logo和文字替换)就行.不知道在哪里加,望指点.,告诉我我自己改也可以.     

 ![pic](http://ww2.sinaimg.cn/large/6ff04438gw1eowgdfxxmcj20bv06igln.jpg)

**Comment by iissnan** [comment]
已添加上去了，新建一个`about`页面以及在主题设置中对菜单设置下即可。
完成设置之后，主题就会自动显示关于的链接（包含图标和文字），效果如图：

![2015-02-03 22 10 15](https://cloud.githubusercontent.com/assets/32269/6021799/64e2b690-abf3-11e4-81b3-9004c11a1f2f.png)

自定义：

- 图标设置。如果你需要修改图标，可以在这个文件中修改：
    https://github.com/iissnan/hexo-theme-next/blob/master/source/css/_section/header.styl
    设置下`.menu-item-about a::before {`的`background`。

- 文本设置。文本的设置在`languages`目录下。

**Comment by HogwartsRico** [comment]
作者速度真快，谢谢了

**Comment by iissnan** [comment]
:smiley:

**Comment by mingmings** [comment]
@iissnan 请问 `about me` 中增加评论的时候，之前在 `issue` 中看到了，但是现在怎么都找不到了，在 `about me` 的 `index.md` 增加一段代码是么

**Comment by iissnan** [comment]
See: https://github.com/iissnan/hexo-theme-next/issues/34

**Comment by mingmings** [comment]
@iissnan 感谢

**Comment by dangbo** [comment]
@iissnan 想要自定义一下图标 不知道怎么修改 看了前面的回答也没有解决＝ ＝

**Comment by iissnan** [comment]
@dangbo 修改 `menu_icons` 配置。

假设你所添加的是 `something: /something`，那么在 `menu_icons` 下同样添加一个 `something`:

```
menu_icons: 
  enable: true
  something: icon_name
```

这里的 `icon_name` 是指 [Font Awesome](http://fontawesome.io/icons/) 里面某一个 icon 的名字。

**Comment by dangbo** [comment]
非常感谢！
