### ISSUE TITLE
請問一台電腦可以開兩個不同的hexo博客嘛？

### ISSUE THREAD

**Issue by kintsuicris** [iissnan/hexo-theme-next#700]
我用了github的一個倉庫並且買了域名搭建了一個hexo的博客
用了next主題

想知道我能不能再開一個倉庫再搭一個hexo？
那樣的話，本地域名會不會衝突？
有成功在一台電腦開兩個hexo的朋友嗎？

**Comment by iissnan** [comment]
再开一个仓库搭一个 Hexo， 可以。
不同的博客绑定不同的域名，或者其中一个绑定到子域名上。

**Comment by kintsuicris** [comment]
@iissnan 那請問如何避免在本地的hexo會發生衝突？

**Comment by iissnan** [comment]
两个博客在不同的目录下不会有冲突

**Comment by kintsuicris** [comment]
@iissnan 喔喔這樣，在新的目錄下面還需要install hexo嗎？

**Comment by iissnan** [comment]
`npm install -g hexo-cli` 安装 hexo 全局命令。

然后根据你的需求，可以使用 Hexo 生成不同的站点，命令:

```
# cwd: ~/Documents/
hexo init blog
cd blog
npm install

# cwd: ~/Documents/
hexo init blog2
cd blog2
npm install
```

**Comment by Haocen** [comment]
和使用 Hexo 相关的问题可以去这里寻求答案：
> https://github.com/hexojs/hexo
