### ISSUE TITLE
搜索栏不能显示搜索icon？

### ISSUE THREAD

**Issue by aarondx** [iissnan/hexo-theme-next#704]
弄了好久，一直不能显示搜索icon.

**Comment by iissnan** [comment]
已修复，谢谢反馈

**Comment by dannyjiajia** [comment]
搜索icon 位置错了～ 没对齐

**Comment by flashlab** [comment]
搜索框已经取消，不应该显示了呀

**Comment by dannyjiajia** [comment]
我说的搜索菜单,如果打开menu_icons,搜索菜单和搜索icon的位置有问题

**Comment by Haocen** [comment]
@flashlab 
确实错位了。如图：
<img width="413" alt="misplaced" src="https://cloud.githubusercontent.com/assets/10842569/13727082/e5579240-e8b1-11e5-96b4-c27b92990ec2.png">
scheme: Mist

**Comment by ybdengzheng** [comment]
我的默认图标都没有，请问怎么启用呢？

在 2016年3月13日 13:24:27, Haocen (notifications@github.com) 写到:

@flashlab
确实错位了。如图：

scheme: Mist

**Comment by flashlab** [comment]
@Haocen 修正 :smile: #721

**Comment by iissnan** [comment]
@ybdengzheng Mist Scheme 在最近的版本里才开放了图标，请更新一下主题。若有其他问题，再开 issue。
