### ISSUE TITLE
侧边栏头像尺寸能自己定义吗？

### ISSUE THREAD

**Issue by xiahei** [iissnan/hexo-theme-next#706]
rt。

**Comment by iissnan** [comment]
没有开放自定义头像大小的选项，可以通过 CSS 自己定义下

**Comment by jerrybendy** [comment]
@xiahei   `source/css/_common/components/sidebar/sidebar-author.styl`，修改`.site-author-image`类，我自己网站就是改的圆形加半透明边框

**Comment by xiahei** [comment]
@jerrybendy get…THX!
