### ISSUE TITLE
如何使``(即csc下面的符号)修饰的内容背景色与代码背景色一致

### ISSUE THREAD

**Issue by blueyi** [iissnan/hexo-theme-next#709]
如图所示，希望1处与2处背景色一致，谢谢
![12](https://cloud.githubusercontent.com/assets/6254020/13625174/c0358bee-e5ef-11e5-910f-6e5febe080dd.png)

**Comment by iissnan** [comment]
`code` 的样式定义在 `source/css/_common/components/highlight/highlight.styl` 中。根据你的需求，你可以修改为：

```styl
code
  word-break: break-all;
  background: highlight-background
  text-shadow: 0 1px #fff
  padding: 0 0.3em
```

其中，`highlight-background` 是 code block 使用的背景颜色，不同代码配色，这个值不同。
