### ISSUE TITLE
请问如何设置favicon.ico

### ISSUE THREAD

**Issue by raighneweng** [iissnan/hexo-theme-next#71]

**Comment by iissnan** [comment]
将 favicon.ico 放在站点的 source 目录下就可以。

**Comment by raighneweng** [comment]
那图像必须是16*16像素的么？

发自翁浩

**Comment by iissnan** [comment]
可以是 `16×16, 32×32, 48×48, 64×64`

**Comment by mingmings** [comment]
@iissnan 我发觉在站点的source下放置了一个 png 的图片，尺寸已调整 48*48或者36*36，貌似仍然看不到，不知道为什么

**Comment by iissnan** [comment]
@mingmings 要配置下 `favicon: /xxx.png`

**Comment by mingmings** [comment]
@iissnan 这个肯定已经配置了的

**Comment by iissnan** [comment]
@mingmings http://mingmings.org/super.png 链接 404 了，貌似图片没有传上去？

**Comment by mingmings** [comment]
@iissnan sorry，我的错，忘了自己站点在 subdirectory 中了，图片路径忘了加路径了，已更正，感谢

**Comment by hezhipengzipp** [comment]
@iissnan @mingmings 加什么路径？我已经放在source目录下了，favicon: /favicon.ico这个配置是在主题目录下对吧
