### ISSUE TITLE
今天博客打开速度非常慢

### ISSUE THREAD

**Issue by Jeffrey95** [iissnan/hexo-theme-next#711]
另外今天打开所有next主题的博客速度都很慢，手机端上也一样。
通过chrome查看好像是google字体库的问题
![padding](http://7xjfag.com1.z0.glb.clouddn.com/%E6%8D%95%E8%8E%B71.PNG)
非常长的时间都是在`padding`状态

**Comment by iissnan** [comment]
Highlight.js 支持 C++ 的语法高亮，明确指定下语言试试

```
```c++
#include <cstdio>
```

**Comment by geekrainy** [comment]
是字体库的问题，今天字体库加载不出来。

**Comment by Jeffrey95** [comment]
@iissnan 之前已经指定语言
我尝试审查元素，发现对应元素的class是`meta-keyword`而不是`keyword`
而`higtlight.styl`中并没有设置`meta-keyword`的相关样式
我尝试在`.pre`添加
```css
.meta-keyword
    color: highlight-green
```
现在已经可以正常高亮。
不过我不知道为什么，我查看别人生成的class是`keyword`，而我的是`meta-keyword`
可能与hexo版本有关？

**Comment by houzi-** [comment]
@Jeffrey95 确实是，真坑爹！

**Comment by chhzhangs** [comment]
字体库改一下，改为useso:`{% if theme.use_font_lato %}
  <link href="//fonts.useso.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
{% endif %}`

**Comment by iissnan** [comment]
@Jeffrey95 代码解析的语言是否正确，在 HTML 源代码里可以看到，比如：

```
<figure class="highlight js">
```

其中，`js` 即是 highlight 检测到并使用的语言。

**Comment by HaloWang** [comment]
<img width="988" alt="2016-03-10 4 16 08" src="https://cloud.githubusercontent.com/assets/7344724/13649095/d9b810fa-e676-11e5-8f84-90f0d317ef3f.png">
@chhzhangs 请问这段代码在哪里设置啊？😰

**Comment by jeekwong** [comment]
@HaloWang  在\themes\next\layout\_partials\head.swig文件中。
可以看看这篇博文：[链接](http://lovenight.github.io/2015/11/10/Hexo-3-1-1-%E9%9D%99%E6%80%81%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E6%8C%87%E5%8D%97/#替换字体库网址)

**Comment by wjd1218** [comment]
国内用google的服务太不稳定，我已经换成360的代理了。

**Comment by ybdengzheng** [comment]
开两会，大家理解一下。

-- 
----------------------------------------------------------


在 2016年3月10日 13:17:17, ColinWang (notifications@github.com) 写到:

国内用google的服务太不稳定，我已经换成360的代理了。

**Comment by mritd** [comment]
说实话。。。难道你们都不爬墙吗？ 我表示 完全无影响。。。 24小时爬墙中。。。

**Comment by wjd1218** [comment]
关键是你的博客要给别人看的话，别人的机器不一定有梯子呀。

**Comment by Jeffrey95** [comment]
@iissnan 你可以看看[我的这篇博客](http://blog.qiujinfeng.com/2016/02/03/Codeforces-341-div2-A-Wet-Shark-and-Odd-and-Even/)

我审查元素看的确是`<figure class="highlight cpp">`、
但是我审查`#include`的时候
```html
<span class="meta-keyword">include</span>
```
我参考了一下别人同样是next的主题的代码块，例如[这篇](http://colinwang.cn/2016/03/06/ReverseBinaryTree/)里的`public`关键字
他生成的是
```html
<span class="keyword">public</span>
```
我单独在`highlight.styl`中添加了上去，目前能正常高亮。
只是我不明白为什么会有这种差异~

**Comment by iissnan** [comment]
@Jeffrey95 我看了下 highlight.js 对于 c++ 语言的解析设置，其中 `include` 是会被解析成预处理关键字（meta keyword），所以这个行为应该是正确的。而 `public` 是被明确定义为 关键字。

**Comment by iissnan** [comment]
参见这行代码：[highlight.js c++ language definition](https://github.com/isagalaev/highlight.js/blob/master/src/languages/cpp.js#L48)

**Comment by Dev-Wiki** [comment]
我的也好慢...看图吧
![screenshot_1](https://cloud.githubusercontent.com/assets/12946956/13729361/3f600026-e96e-11e5-9697-f7ae23862334.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12946956/13729363/43627de8-e96e-11e5-8cde-ca3bb7ce353c.png)

**Comment by Haocen** [comment]
@Jeffrey95 如果有多个问题，请分开提交，而不是通过修改标题的方式改变讨论内容，否则容易误导其他用户，谢谢。
@geekrainy @HaloWang @colinwjd 博客语言设置成简中后， Next 应该已经默认使用 360 字体库了，不存在你们说的问题，请参见：
https://github.com/iissnan/hexo-theme-next/wiki/Changelog#0452

**Comment by iissnan** [comment]
@Haocen :+1: 

NexT 字体的引用改变了好几次，不过最新的版本确实是只使用 Google 的 Fonts API。Wiki 的内容过期了，很抱歉我没即时更新。NexT 初期内置了 Lato Font，后面有反馈说英文字体缺失的情况，但 Lato Font 有 merge 过一次 pr 更新，所以我不清楚是更新前还是更新后导致字体缺失的情况。干脆就换成外链的形式，外链的形式也是麻烦不断，比如稳定性、多协议支持等。所以我现在正在考虑换回内置的形式，采用最初的 Lato Font。

**Comment by iissnan** [comment]
关闭此 Issue，字体的问题另外再讨论。
