### ISSUE TITLE
禁止首页文章标题加载评论数量

### ISSUE THREAD

**Issue by kop-still** [iissnan/hexo-theme-next#715]
主题是Muse，评论是disqus，加载disqus非常慢，不想在标题下加载comments的count数字

**Comment by kop-still** [comment]
已修改源码解决
next很赞

**Comment by GooZy** [comment]
@kop-still 请问是修改源码的哪一部分，我也想禁止TAT，试了好久都没找到办法。

**Comment by kop-still** [comment]
@GooZy /layout/_third-party/comments/disqus.swig 注释掉加载count.js那一行 看源码page.comments属性可配置 好长时间不玩博客了 我不保证是正确的 你需要自己试一下 我也是刚刚凭记忆看了一下源码

**Comment by GooZy** [comment]
我决定放弃了，就让那一格空着吧TAT谢谢 :)

**Comment by GooZy** [comment]
解决了。使用这篇[文章](http://www.vitah.net/posts/20f300cc/#%E6%96%87%E7%AB%A0%E8%AF%84%E8%AE%BA%E6%95%B0%E7%9B%AE%E4%B8%8D%E6%98%BE%E7%A4%BA)，关闭了评论数，后面和我有相同需求的可以看看= =

**Comment by Flygar** [comment]
@GooZy 参考了你给出的那篇文章，可是还是不能关闭TAT

**Comment by GooZy** [comment]
@Flygar 要不换个评论系统>_<
