### ISSUE TITLE
Pisces主题，搜索图标错位

### ISSUE THREAD

**Issue by Panl** [iissnan/hexo-theme-next#717]
![image](https://cloud.githubusercontent.com/assets/3842675/13729768/029c799e-e978-11e5-85bc-b3cb1cd08090.png)

**Comment by ybdengzheng** [comment]
我的默认图标都不显示。

**Comment by colinwjd** [comment]
#716 应该是修复这个问题的，作者还没有合并。

**Comment by Haocen** [comment]
#704 也已提及。

**Comment by gardonlee** [comment]
同样的问题

**Comment by BUPTLdy** [comment]
同错位

**Comment by flashlab** [comment]
已修正 #721

**Comment by Panl** [comment]
@flashlab thank you
