### ISSUE TITLE
关于即将在 0.5 中支持的 Typicons ，我提议改为支持 Fontello 。

### ISSUE THREAD

**Issue by Haocen** [iissnan/hexo-theme-next#722]
出于如下几点考虑：
- [x] Fontello 支持直接在官网上定制需要的图标，无需自行在本地生成，可以拖拽上传 SVG 文件。
- [x] Fontello 已经包含所有 Typicons 图标。参见： http://typicons.com/more/resources/

如果作者同意的话，我可以提交 PR ，因为我已经自行实现了对 Fontello 的支持（和 Font Awesome 共存）。

**Comment by iissnan** [comment]
早期有一个功能可以自己选择需要的 font icon（使用的是 iconmoon），但我觉得过程太过繁琐了，最后替换成了 FontAwesome。而 Typicons 是那个功能的一部分，所以这个支持我并没有打算添加进来。

FontAwesome 包含了大部分的图标应该可以满足大部分用户的使用场景。若说需要支持额外的 Font Icon，我想最好是能够通过在 `_config.yml` 中配置就可以，而不用用户去额外做其他的操作（例如复制 font，更改 CSS，更改模板 等）。

**Comment by Haocen** [comment]
明白了。是 history 文档没更新…
