### ISSUE TITLE
[bug?]pisces从mobile拉到desktop布局导航栏高度错误

### ISSUE THREAD

**Issue by flashlab** [iissnan/hexo-theme-next#723]
目测是`\themes\next\source\js\src\schemes\pisces.js`下，sidebar的padding-bottom值在页面加载完之后就固定住的缘故。

**Comment by iissnan** [comment]
嗯，目前仅在页面加载完成之后更改一次，我想切换不同的布局不是一个 common case。

**Comment by flashlab** [comment]
Agree.
