### ISSUE TITLE
请问创建分类页后如何添加分类呢

### ISSUE THREAD

**Issue by whx4J8** [iissnan/hexo-theme-next#726]
分类页面已经创建好了。然后如何创建分类和文章的关联呢，分类页面需要自己写样式吗？麻烦大大了

**Comment by Haocen** [comment]
@whx4J8 写文章的时候添加分类然后重新生成页面就行了。默认自带样式，觉得不好看可以自己写。

**Comment by whx4J8** [comment]
好的，谢谢

**Comment by whx4J8** [comment]
我创建文章时
只生成了
---
title: hexo next 添加为文章添加分类
date: 2016-03-16 08:12:43
tags:
---

默认好像没有分类的标签，需要手动添加
categories:
这个加到wiki的教程里是不是好一些，昨天就因为这个一直找不到文章和分类的关联。。

**Comment by iissnan** [comment]
在使用文档中添加了使用 `categories` 的例子，以及 Hexo 的官方文档链接：
http://theme-next.iissnan.com/theme-settings.html#categories-page

**Comment by whx4J8** [comment]
好的，谢谢

**Comment by crayon-xin** [comment]
scaffolds目录下，是新建页面的模板，执行新建命令时，是根据这里的模板页来完成的，所以可以在这里根据你自己的需求添加一些默认值，比如categories，希望能帮到你

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
