### ISSUE TITLE
请问如何 enable fb-like

### ISSUE THREAD

**Issue by mcknote** [iissnan/hexo-theme-next#727]
我想在 post 中加 fb-like button，翻了一下代码发现这段

`{% if not is_index and theme.facebook_sdk.enable and theme.facebook_sdk.like_button %}
            &nbsp; | &nbsp;
            <div class="fb-like" data-layout="button_count" data-share="true"></div>
          {% endif %}`

请问要怎么启用？谢谢。

**Comment by iissnan** [comment]
我没有使用过。你可以参考下这个 [Pull Request](https://github.com/iissnan/hexo-theme-next/pull/410) 以及 [Facebook JavaScript SDK](https://developers.facebook.com/docs/javascript)

**Comment by mcknote** [comment]
了解，谢谢
另外如果有人要加 Facebook Badge，直接把两段代码添加在 _macro 里的 sidebar.swig 就行。

**Comment by iissnan** [comment]
不太清楚 Facebook Badge 是什么，不过你可以将你的方案发 pr 给我，最好描述下使用方式，方便有需要的用户。谢谢

**Comment by mcknote** [comment]
好的，Facebook Badge 是用来宣传 Facebook Page 的小工具，如果想加到 Sidebar，需要按照以下步骤：

1. 去 https://developers.facebook.com/docs/plugins/page-plugin 为专页申请 Badge
2. 我的参数是 Tabs timeline; Width 250; Height 420
3. 点 Get Code 以后会出现两段代码，一段 Include the JavaScript SDK on your page once，一段  Place the code for your plugin wherever you want
4. 把第一段贴在 sidebar.swig 开头（{% macro render(is_post) %} 后），第二段贴在 </section> 前即可

**Comment by iissnan** [comment]
@mcknote 多谢
