### ISSUE TITLE
更新主题后首页不居中展示

### ISSUE THREAD

**Issue by cnbleu** [iissnan/hexo-theme-next#728]
### Expected behavior (预期行为)
网站加载中及加载后的效果保持一致，具体为：网站首页完整加载完毕后能够居中展示，且个人信息相关展示不应该出现在网站的最底部。

### Actual behavior (实际行为)
网站首页完整加载完毕后，没有居中展示且个人信息的展示出现在了网站的最底部。

### Steps to reproduce the behavior (重现步骤)
打开网站：http://www.cnbleu.com

### NexT Version, NexT Scheme
NexT Version:
  - [ *] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [ ] Mist
  - [* ] Pisces

### Other Information (Like Browser, System, Screenshots)
Browser: chrome
System: OSX 10.11.2

**Comment by Haocen** [comment]
看这个 #671

**Comment by cnbleu** [comment]
@Haocen 解决方案有效，多谢！

**Comment by iissnan** [comment]
@cnbleu 谢谢，Bug 描述很清楚。这个问题我刚修正了，也可以更新下主题。

具体见 [Bug: Layout of Pisces is broken when sidebar.display is 'always' ](https://github.com/iissnan/hexo-theme-next/commit/3e284b049d369a55018890c2877a6af4b4c35fc6)

**Comment by cnbleu** [comment]
@iissnan 刚刚验证了下，有效。
