### ISSUE TITLE
如何载入/source文件夹里的html文件？(已解决）

### ISSUE THREAD

**Issue by w-zx** [iissnan/hexo-theme-next#729]
### Expected behavior (预期行为)
想用blog做一个demo的地址列表，想把demo本身（html和css）也放在pages的空间里，也就是hexo的/source文件夹，在文章中插入链接"/.../xxx.html"想直接跳转到demo页面，之前用pacman主题时没有问题。

### Actual behavior (实际行为)
但是换成next后，我想打开的html会变成博客的一部分，载入了主题的css，也载入了自己定义的css，发现html也被改写了，而且在本地显示正常的页面也出现了边距不正确的现象（重现地址的头像的下边距消失了，左侧图像也错位了）不知道这个的原因是什么，求解答。

### Steps to reproduce the behavior (重现步骤)
**发现是静态html生成时就被修改了，怀疑是使用hexo步骤出错，重新生成（但是我的确生成过几遍...当时没有用啊）后已不再出现。**
### NexT Version, NexT Scheme

NexT Version:
  - [x] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [x] Muse
  - [x] Mist
  - [x] Pisces

**Comment by Haocen** [comment]
不要在生成静态文件之前插入额外的无关文件。

**Comment by flashlab** [comment]
#31 #359
