### ISSUE TITLE
利用百度 Echarts + jQuery 2.2.1 生成博客时 Echarts 图片无法显示

### ISSUE THREAD

**Issue by tommyjiang** [iissnan/hexo-theme-next#730]
### Expected behavior (预期行为)

Echarts 图片正常显示
### Actual behavior (实际行为)

Echarts图片无法显示，Chrome的Console报错

``` javascript
Uncaught TypeError: Cannot read property 'RunSequence' of undefined motion.js?v=0.5.0:224 
NexT.motion.middleWares.logo @ motion.js?v=0.5.0:224
NexT.motion.integrator.next @ motion.js?v=0.5.0:180
NexT.motion.integrator.bootstrap @ motion.js?v=0.5.0:183
(anonymous function) @ bootstrap.js?v=0.5.0:41
i @ index.js?v=2.2.1:2
j.fireWith @ index.js?v=2.2.1:2
n.extend.ready @ index.js?v=2.2.1:2
J @ index.js?v=2.2.1:2
```

使用默认的 `Landscape` 主题没问题，应该是 `NexT` 的问题。
### NexT Version, NexT Scheme

NexT Version:
- [X] Master
- [ ] Latest Release
- [ ] Old version -

NexT Scheme:
- [ ] Muse
- [ ] Mist
- [X] Pisces
### Other Information (Like Browser, System, Screenshots)

无

**Comment by Haocen** [comment]
是否是 jQuery 命名空间冲突？
给个出问题的链接看看。

**Comment by tommyjiang** [comment]
感谢回复，链接如下：http://tommyjiang.github.io/2015/12/28/Trip-2015/

**Comment by Haocen** [comment]
由于网络限制我无法重现你的问题，因为我的网络无法访问托管在百度域名下的资源，但你可以自己先把主题设置中的 motion 改为 false 试试，或许可以解决问题。

**Comment by tommyjiang** [comment]
非常感谢，确实解决了。我去学习下 `motion` 的相关文档。

**Comment by iissnan** [comment]
这个错误是 VelocityJS 抛出来的，猜测是跟 ECharts 有冲突。

**Comment by tommyjiang** [comment]
请问 `motion` 这个 js 文件的具体作用是？如果不影响我就设为 `false` 吧。

**Comment by iissnan** [comment]
页面动画效果，如果使用 Pisces Scheme 就没有影响。其他的 Scheme 可能侧栏会失效（？不确定）

**Comment by tommyjiang** [comment]
好的，我先用 `Pisces` 吧，谢谢。有机会我从头学学 js。

**Comment by ivan-nginx** [comment]
@tommyjiang dont understand u, write in English if not solved. If solved, close it please.
