### ISSUE TITLE
文章目录

### ISSUE THREAD

**Issue by LiaoPon** [iissnan/hexo-theme-next#734]
在目录跟随屏幕滚动,只能显示一级标签,二级和三级不能跟着滚动,而且目录长度太长的时候,不可以完整显示
链接地址：
http://liaopon.github.io/2016/03/18/Java%E5%BC%80%E5%8F%91%E4%B8%AD%E7%9A%8423%E7%A7%8D%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E8%AF%A6%E8%A7%A3/#more

图:
![fm27 cd8 a e kns cncg](https://cloud.githubusercontent.com/assets/10516978/13879327/ded3e78a-ed51-11e5-8ed6-c55c8f9c92aa.png)

**Comment by LiaoPon** [comment]
在其他问题中，没有发现我这个问题

**Comment by Haocen** [comment]
这好像是一个已知的问题。而且需要依赖 Hexo 的改进才行。

**Comment by iissnan** [comment]
目录过长已在 #629，定位不准确还没碰到过

**Comment by iissnan** [comment]
See #629
