### ISSUE TITLE
为什么内容区块和footer离得这么远

### ISSUE THREAD

**Issue by gardonlee** [iissnan/hexo-theme-next#736]
###  如图，标签页和分类页的内容背景和footer背景离得好远，是bug么
 #![bug](http://7xr868.com1.z0.glb.clouddn.com/0319bug%2Fbug.png)
#

**Comment by iissnan** [comment]
嗯.. 看起来要给 content 区域设置一个 `min-height`

**Comment by iissnan** [comment]
加了一个 700 的最小高度，请更新下主题

**Comment by gardonlee** [comment]
### 分类页每一项可以横向排列么，或者就像标签页那样排列？？
![1](https://cloud.githubusercontent.com/assets/15051896/13981165/56c35bb2-f11d-11e5-970f-eea014b17a4e.png)

**Comment by iissnan** [comment]
分类不像标签，他有层次关系。我还没有想好如何去处理分类，暂时先这样吧。后续可能会重新设计。另外有其他问题，再开 issue，我先关闭掉这个 issue 了
