### ISSUE TITLE
多说分享无法安装

### ISSUE THREAD

**Issue by tangbotony** [iissnan/hexo-theme-next#738]
### Expected behavior (预期行为)
多说分享功能能够正常使用

### Actual behavior (实际行为)
无法安装，Hexo启动报错：
FATAL bad indentation of a mapping entry at line 95, column 2:
     duoshuo_share: true
     ^
YAMLException: bad indentation of a mapping entry at line 95, column 2:
     duoshuo_share: true

### NexT Version, NexT Scheme

NexT Version:
  - [ ] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [ ] Mist
  - [ ] Pisces

**Comment by iissnan** [comment]
```yml
FATAL bad indentation of a mapping entry at line 95, column 2:
duoshuo_share: true
```

这个错误说明的你的 _config.yml 配置文件缩进有问题，认真检查写这行的缩进
