### ISSUE TITLE
如何实现没有文章标题等信息的图片布局

### ISSUE THREAD

**Issue by gardonlee** [iissnan/hexo-theme-next#739]
### 在您博客里看到这种布局，没有标题等信息 ，很好奇怎么实现的？

![2](https://cloud.githubusercontent.com/assets/15051896/13903507/3f73b896-eeb9-11e5-9b3a-32466823b5a5.png)

**Comment by iissnan** [comment]
是一个试验性的功能

**Comment by ivan-nginx** [comment]
@gardonlee dont understand u, write in English if not solved. If solved, close it please.
