### ISSUE TITLE
如何调整打开一篇文章时候不自动弹出sidebar？

### ISSUE THREAD

**Issue by bluebeach** [iissnan/hexo-theme-next#74]

**Comment by bluebeach** [comment]
首先感谢作者的主题！

**Comment by iissnan** [comment]
目前 Sidebar 还不支持自定义，后续的版本中会开放配置：

1. 禁用 Sidebar
2. 在 Post 页面自动弹出
3. 一直显示

**Comment by bluebeach** [comment]
个人拙见在文章详情页中可以自动弹出sidebar，然后点击下文章空白的部分，sidebar自动隐藏。这样的体验是不是好一点

**Comment by baininghan** [comment]
@bluebeach 你这给作者出难题。。

**Comment by iissnan** [comment]
我之前考虑过这么处理。之所以没做是因为侧边栏在文章页面是有文章目录导航的功能，也就是说跟内容有一定的关联。

假设 Sidebar 失去焦点后自动收缩，以下场景就可能比较混淆：
当鼠标选择文章的内容的时候，会让 sidebar 自动收缩，这会出发文章位置的改变。我觉得这个体验是不好的。

**Comment by eurusd** [comment]
侧边栏不要动了，原有的很好。  侧边栏地址链接加 target="_black" 就OK了

**Comment by wizchenpeng** [comment]
themes\next\layout\_scripts\pages\post-details.swig 将这个文件的最后的部分修改下，找到以下代码：

    var $tocContent = $('.post-toc-content');
    if ($tocContent.length > 0 && $tocContent.html().trim().length > 0 && isDesktop()) {
    setTimeout(function () {
         $('.sidebar-toggle').trigger('click');
    }, 800);
    }

注释掉就可以了.

**Comment by iissnan** [comment]
新版可以定义 Sidebar 的行为：

```yml
sidebar: post       # 默认，在文章页面自动展开
sidebar: always   # 一直显示
sidebar: hide       # 不展示，可以通过侧栏按钮展开
```
