### ISSUE TITLE
新建文章编写之后中文乱码问题

### ISSUE THREAD

**Issue by Flowsnow** [iissnan/hexo-theme-next#740]
Mist主题使用hexo命令新建文章时若标题中没有出现中文，但是在文章内容中出现中文，则会出现中文乱码。比如
```
hexo new "shell express"
```
然后在这个md文件中编写中文内容，关闭后再打开那么所有的中文都会用问号代替。

但如果在标题中加入中文，比如
```
hexo new "shell的express"
```
然后在该md文件中编写中文，不会出现中文乱码。

这是因为hexo 新建文章的时候会根据标题指定文章内容的编码格式吗？（我试过手动修改格式，没有任何效果）

**Comment by iissnan** [comment]
换一个编辑器试试

**Comment by zhishengzhang** [comment]
请问解决了吗？

**Comment by Flowsnow** [comment]
没有解决，我每次创建一个md文件的时候都需要先在文件名称中加上中文，这样文件的编码才支持中文。后面即使删掉这些中文也不影响文件格式，即不会出现乱码问题。iissnan提供的换编辑器的方法根本不可行。 @zhishengzhang @iissnan

**Comment by zhishengzhang** [comment]
@Flowsnow 我在尝试修改系统编码格式或者hexo安装包的文件编码格式，希望可以解决。

**Comment by Flowsnow** [comment]
@zhishengzhang 感觉这两种修改都不是很好，这个已经不是主题的关系了，已经是hexo的问题。如果可以了，请告知

**Comment by zhishengzhang** [comment]
@Flowsnow 
1 `vim ~/.vimrc`
2 插入内容
:set encoding=utf-8
:set fileencodings=ucs-bom,utf-8,cp936
:set fileencoding=gb2312
:Set termencoding=utf-8
3 保存文件.vimrc
![tm](https://cloud.githubusercontent.com/assets/8622157/18700287/f5c8a1e8-8008-11e6-801c-c7ebd3c4d24f.png)

**Comment by daohewang** [comment]
@zhishengzhang   
你这样写有用么，我按照上面的步骤码了一遍，无效，求解！！！！  
😢

**Comment by broderickwang** [comment]
@daohewang 你的中文解决了吗？我new 中文的时候，还是乱码啊

**Comment by broderickwang** [comment]
![image](https://user-images.githubusercontent.com/6623292/29502103-21811cb2-8660-11e7-9695-7e30eeb4fe2a.png)
为什么会这样？

**Comment by Flowsnow** [comment]
我之前那个问题是在windows上用typora编写md文件时typora自身的问题，后来typora升级后就没有出现这个问题了@broderickwang
