### ISSUE TITLE
cnzz没有显示。

### ISSUE THREAD

**Issue by crazy-canux** [iissnan/hexo-theme-next#746]
### Expected behavior (预期行为)

站长统计

### Actual behavior (实际行为)

什么都没有

### Steps to reproduce the behavior (重现步骤)
添加到cnzz-analytics.swig
{% if theme.cnzz_siteid %}

  <div style="display: none;">
    <script src="http://s95.cnzz.com/z_stat.php?id={{ theme.cnzz_siteid }}&web_id={{ theme.cnzz_siteid }}" language="JavaScript"></script>
  </div>

{% endif %}

### NexT Version, NexT Scheme

NexT Version:
  - [ ] Master
  - [yes ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ yes] Muse
  - [ ] Mist
  - [ ] Pisces

### Other Information (Like Browser, System, Screenshots)
在cnzz上能看到有统计。
但是博客页面没有东西。

**Comment by iissnan** [comment]
See: https://github.com/iissnan/hexo-theme-next/pull/712

**Comment by crazy-canux** [comment]
原来是这样啊，谢谢！
