### ISSUE TITLE
构建的博客上面有条莫名的黑边

### ISSUE THREAD

**Issue by chn-yang** [iissnan/hexo-theme-next#748]
### Expected behavior (预期行为)
没黑边

### Actual behavior (实际行为)
有黑边

[cnyang.xyz](http://cnyang.xyz)

### NexT Version, NexT Scheme

NexT Version:
  - [ ] Master-

NexT Scheme:
  - [  ] Pisces-

### Other Information (Like Browser, System, Screenshots)

chrome 49,win10,
[Screenshots](http://7xs3v8.com1.z0.glb.clouddn.com/sc.jpg)

**Comment by colinwjd** [comment]
正常就是有黑边的啊！

**Comment by chn-yang** [comment]
原来如此,感谢你的回复..

**Comment by iissnan** [comment]
如果要去掉，就修改 source/css/_custom/custom.styl 文件，添加 

```css
.headband { display: none; }
```

**Comment by chn-yang** [comment]
谢谢大神!

**Comment by mapan2020** [comment]
.\next\source\css\_common\components\header\headerband.styl 文件
.headband {
  height: $headband-height;
  background: $headband-bg;
}
还是这个问题，请问 高度和背景颜色 这两个变量应该在哪里设置呢？
