### ISSUE TITLE
请问如何在 page 页面显示文章索引目录？

### ISSUE THREAD

**Issue by twiceyuan** [iissnan/hexo-theme-next#75]
之前默认主题 page 页和 post 一样在设置 toc 属性为 true 时会显示文章索引目录，next 主题该如何修改来让它显示？

**Comment by iissnan** [comment]
toc 目前只应用在 post details 页面上。你可以在 [page.swig](https://github.com/iissnan/hexo-theme-next/blob/master/layout/page.swig) template中修改，让其作用在 Page 上。还有相关的样式和脚本，改动可能会挺多的。

**Comment by twiceyuan** [comment]
原来如此，感谢答复
