### ISSUE TITLE
移动端访问，标签和关于页面右侧会有白边。宽度不为100%

### ISSUE THREAD

**Issue by UtopiaScript** [iissnan/hexo-theme-next#751]
![img_8486](https://cloud.githubusercontent.com/assets/10824667/14007481/2bd435da-f1b2-11e5-825c-eface65ed2cd.PNG)
标签和分类数目也有问题

**Comment by UtopiaScript** [comment]
标签和分类数目是没有clean的问题

**Comment by hackjustu** [comment]
+1

**Comment by ivan-nginx** [comment]
@UtopiaScript dont understand u, write in English if not solved. If solved, close it please.
