### ISSUE TITLE
请问是否有办法让首页显示某个页面，而不是文章列表？

### ISSUE THREAD

**Issue by Thulof** [iissnan/hexo-theme-next#754]
比如将一个About页面设为首页

**Comment by Haocen** [comment]
这个应该是 Hexo 实现的部分。和主题无关。

**Comment by mcknote** [comment]
不裝 index-generator 然後在 source 底下建個 index.md，裡面寫 permalink: /index.html 不知道可不可行

**Comment by iissnan** [comment]
最简单的方法就是直接改写 `index.swig` 模板文件。
