### ISSUE TITLE
Break word 样式影响了移动设备上英文文章显示效果

### ISSUE THREAD

**Issue by Haocen** [iissnan/hexo-theme-next#756]
### Expected behavior (预期行为)
文章按照单词换行。

### Actual behavior (实际行为)
文章从任意位置换行。

### Steps to reproduce the behavior (重现步骤)
可在任意英文文章上重现。
![screenshot_20160324-123200](https://cloud.githubusercontent.com/assets/10842569/14048211/2e9ae058-f283-11e5-9ea2-3ac6bf37116d.png)

有关联的文件：
hexo-theme-next/source/css/_common/components/post/post-title.styl
hexo-theme-next/source/css/_common/components/post/post.styl

当时加入 word-break: break-all; 应该是为了防止页面被撑开。不知道有没有更好的解决方法，让文章优先按照单词换行，否则才从任意位置换行。

### NexT Version, NexT Scheme

NexT Version:
  - [x] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [x] Mist
  - [ ] Pisces

### Other Information (Like Browser, System, Screenshots)
Mobile Chrome for Android.

**Comment by iissnan** [comment]
嗯，就是为了解决被撑开的问题，虽然暴力，但是很有效。不知道是否有更好的方法

**Comment by Haocen** [comment]
我最近花了很多时间研究 bootstrap ，它的解决方案是允许表格在较窄的显示设备上横向滚动。我抽空做下修改看看，如果理想的话就提交上来。

**Comment by urzone** [comment]
同样纠结这个问题啊，英文文章在手机端显示的时候，常常把单词切割了，一部分在上一行末尾，一部分在下一行开头，这个很麻烦啊，能解决一下么？

**Comment by Haocen** [comment]
@urzone 不好意思啊。最近有点忙。目前的话，似乎只要对 <code> 和 <table> 元素支持横向滚动就足够了。我应该这两天能够提交一个修改。

**Comment by Haocen** [comment]
@urzone 我有一个好消息和一个坏消息。
好消息是，只需要修改：
hexo-theme-next/source/css/_common/components/post/post.styl
这个文件，将：
word-break: break-all;
改为：
word-break: break-word;
就可以了。
对于表格内容太长撑开页面的问题，可以修改：
hexo-theme-next/source/css/_common/scaffolding/tables.styl
将：
word-break: break-word;
改为：
word-break: break-all;
就可以解决目前遇到的问题。

坏消息是，目前 next 两处需要使用 word-break: break-all; 的地方，一处是 `<table>` 一处是 `<code>` 这两者如果需要实现水平滚动，需要被包裹在其他元素当中，比如 `<p>` 或者 `<div>` 才行，这个涉及到对页面生成模板的修改，也不清楚会不会引致其他问题。

**Comment by Haocen** [comment]
#844

**Comment by urzone** [comment]
哇哦，辛苦兄台了，感谢提供的信息，多谢！！！

**Comment by urzone** [comment]
经过修改，单词不会被截断，但是在手机端不会显示为 justfy 的对齐了？
例如：

![screen shot 2016-04-24 at 01 12 22](https://cloud.githubusercontent.com/assets/11997420/14762949/cdb8d4f4-09b9-11e6-94c0-2cb18ee37a03.png)

**Comment by Haocen** [comment]
@urzone 不知为何只有 Pisces 主题的 `post-body` 是 justify 对齐。这个要问一下作者。
相关文件：
source/css/_schemes/Pisces/_posts.styl

**Comment by Master-Wang** [comment]
@Haocen  Thx a lot for your advice!
