### ISSUE TITLE
设置sidebar.display=remove无法完全删除sidebar

### ISSUE THREAD

**Issue by singular78** [iissnan/hexo-theme-next#758]
### Expected behavior (预期行为)

完全删除sidebar
### Actual behavior (实际行为)

依然存在
### Steps to reproduce the behavior (重现步骤)

muse主题，设置_config.yml中sidebar.display=remove
### NexT Version, NexT Scheme

NexT Version:
  - [ ] Master
  - [ x] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [ x] Mist
  - [ ] Pisces

### Other Information (Like Browser, System, Screenshots)
这因该是个bug，将改_layout.swig中的 {% if theme.sidebar !== 'remove' %}修改为
{% if theme.sidebar.display !== 'remove' %}即可实现完全删除sidebar

**Comment by HanderWei** [comment]
Pisces主题也是无法移除侧边栏，无论是 display: hide 还是 display: remove

**Comment by iissnan** [comment]
已修复
