### ISSUE TITLE
“友情链接”4个汉字不能显示……

### ISSUE THREAD

**Issue by 24suixinsuoyu** [iissnan/hexo-theme-next#764]
### NexT Version, NexT Scheme

NexT Version:
  - [ ] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [ ] Mist
  - [ ] Pisces

**Comment by 24suixinsuoyu** [comment]
突然发现是因为【links_title】中少写了字母s，粗心大意惹麻烦啊…

**Comment by 24suixinsuoyu** [comment]
友情链接部分，如果能三个一排三个一排就好了，显得很整齐。单排的话，数量一多就显得很冗长

**Comment by Haocen** [comment]
@24suixinsuoyu 如果问题已经解决了烦请关闭。
