### ISSUE TITLE
Mist主题如何使图片默认居中

### ISSUE THREAD

**Issue by liyuan989** [iissnan/hexo-theme-next#765]
Mist主题图片默认left，这让插入的小图片看起来很难看

试过在img，.post-body img，.posts-expand img，.fancybox img里面加上text-align = center均不起作用

请问有什么方法可以让Mist主题的图片默认居中？

**Comment by Haocen** [comment]
直接在编辑文章的时候计入 html tag 就行。
报告问题请按照要求的格式来，否则很难获得帮助。

**Comment by liyuan989** [comment]
@Haocen 
修改https://github.com/iissnan/hexo-theme-next/blob/master/source/css/_schemes/Mist/_posts-expanded.styl 30行可解决
```
.post-body img {margin: 0 auto;}
```

**Comment by xirong** [comment]
@liyuan989 👍  更改了样式后好了，最简单的方法解决掉了这个问题。
