### ISSUE TITLE
关于新版中的Mist

### ISSUE THREAD

**Issue by luffr** [iissnan/hexo-theme-next#767]
希望在新版中的Mist 延续v0.4.5.2的设计，特别是菜单栏不要加入图标，那样子菜单栏会失去简洁。Pisces的菜单栏有图标显示，不会显得怪异，但是Mist 的菜单栏出现图标，真的不简洁，也不美观，Mist 和Pisces的菜单栏是不同特点的，横向与纵向。
另外在v5.0.0之前（v5.0.0我还没升级）的版本，搜索的样式也改变了，v0.4.5.2时代，搜索是在输入关键词、按下enter之后才会弹出swiftype的窗口，但是在v5.0.0之前的版本，点击搜索就弹出了，个人觉得Mist在v0.4.5.2的设计最简洁美观，希望采纳。
感谢你做出了NexT这个作品，谢谢。

**Comment by iissnan** [comment]
多谢反馈。

关于菜单的图标，实际上你可以通过设置将其去掉：

```yml
menu_icons:
  enable: false
```

为了保持一致性（代码层面），我将 Mist 的搜索栏跟其他的 Scheme 调成一样，算是牺牲定制细节从而保证可维护性的一个妥协。暂时应该不会再动，若你确实需要，可以参考 [这个修改](https://github.com/iissnan/hexo-theme-next/commit/4ded3334005e511458482ba66139265686556d14) 自己定制下。

**Comment by yun-percy** [comment]
讲真，搜索栏比搜索按钮好很多，现在的搜索按钮需要2次操作。比较烦。
