### ISSUE TITLE
Archive 页面能否只显示时间和标题？

### ISSUE THREAD

**Issue by FreemanHsu** [iissnan/hexo-theme-next#77]
感觉Archives罗列标题更好，Landscape中配置archive为1就是罗列标题，next中似乎不行？
edit: 看到demo 似乎可以…… 不明白哪里配置错了 囧
edit2: 仔细检查了一下，发现archive页面相关的css似乎没载进来

**Comment by iissnan** [comment]
应该是 `permalink` 的问题，NexT 不支持 `:title` 以及 `:category/:title` 这种 permalink。见：https://github.com/iissnan/hexo-theme-next/issues/50。
