### ISSUE TITLE
0.5.0后<code>样式有问题

### ISSUE THREAD

**Issue by chitanda** [iissnan/hexo-theme-next#771]
`code`标签内单行显示的内容由于`text-shadow`的存在变得非常的刺眼

### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/8258592/14171782/55036b50-f767-11e5-948f-4f5878d8a5ba.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/8258592/14171790/5a0c3b86-f767-11e5-8c54-e68d2acfd4cc.png)
#### 对应区块的css
![image](https://cloud.githubusercontent.com/assets/8258592/14171977/712ecaa8-f768-11e5-957f-8c829e3959fc.png)

### NexT Version, NexT Scheme

NexT Version:
  - [x] Master 
  - [x] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [x] Muse
  - [x] Mist
  - [x] Pisces

### Other Information (Like Browser, System, Screenshots)
只有把`highlight_theme`改成`normal`才正常。
![image](https://cloud.githubusercontent.com/assets/8258592/14171950/48010c0e-f768-11e5-9baa-6de5060afb64.png)
#### 对应的css：
![image](https://cloud.githubusercontent.com/assets/8258592/14172011/97a9e3e8-f768-11e5-9a48-685fcc1cc553.png)

**Comment by iissnan** [comment]
我记得有一个 issue 提到 `code` 的样式需要跟所使用的 highlight theme 一致。刚才试着改过去，发现多个黑色块夹在文本里面看起来有点重口，因此还是恢复成之前的样式。

**Comment by chitanda** [comment]
已更新。现在看起来好多了，谢谢
![image](https://cloud.githubusercontent.com/assets/8258592/14214436/98d88e24-f86f-11e5-987d-ab28d4f2b77b.png)

**Comment by ifelseboyxx** [comment]
我怎么还有这问题？ 不是已经修复了吗？

**Comment by Shens998** [comment]
我也遇到这个问题，版本是5.1。是不是5.1也是这个原因?
