### ISSUE TITLE
social_icon如果设置为false的话name也不显示了

### ISSUE THREAD

**Issue by chitanda** [iissnan/hexo-theme-next#772]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/8258592/14172935/949e027e-f76d-11e5-8037-402f227f1787.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/8258592/14172923/88dfe2ea-f76d-11e5-9976-7a6ebd4aec44.png)

### NexT Version, NexT Scheme

NexT Version:
  - [x] Master
  - [ ] Latest Release
  - [ ] Old version -

NexT Scheme:
  - [ ] Muse
  - [x] Mist
  - [ ] Pisces

### Other Information (Like Browser, System, Screenshots)
看了下是`sidebar.swig`的代码逻辑有点小问题。71行开始的代码：
```
        <div class="links-of-author motion-element">
          {% if theme.social %}
            {% for name, link in theme.social %}
              <span class="links-of-author-item">
                <a href="{{ link }}" target="_blank">
                  {% if theme.social_icons.enable %}
                    <i class="fa fa-{{ theme.social_icons[name] || 'globe' }}"></i> {{ name }}
                  {% endif %}
                </a>
              </span>
            {% endfor %}
          {% endif %}
        </div>
```
一旦false了，name也就没了。所以将`name`移出`if判断`即可。
已提交PR

**Comment by chitanda** [comment]
我看之前有人提到过这个bug：
https://github.com/iissnan/hexo-theme-next/issues/525

**Comment by iissnan** [comment]
已 Merge，谢谢
