### ISSUE TITLE
更新后出现错误

### ISSUE THREAD

**Issue by gardonlee** [iissnan/hexo-theme-next#774]
求解决！！！
更新0.5版本后，hexo-g出现错误，提示主题不能被加载， 主题配置文件错误！

**Comment by chitanda** [comment]
你应该贴下错误日志。。我下午才从0.4.5跳到0.5.0，一切正常。。

**Comment by gardonlee** [comment]
![1](https://cloud.githubusercontent.com/assets/15051896/14179398/969cab74-f791-11e5-8fb1-e2abbee4cd17.png)

**Comment by gardonlee** [comment]
看到主题配置文件多了好多东西
![2](https://cloud.githubusercontent.com/assets/15051896/14179496/de193dfa-f791-11e5-933a-8869a8279af3.png)

**Comment by iissnan** [comment]
文件冲突了，解决下冲突就行

**Comment by Haocen** [comment]
@gardonlee 如果你不懂得使用版本管理软件，可以在这里学习:
https://git-scm.com/documentation
