### ISSUE TITLE
高亮bug

### ISSUE THREAD

**Issue by gardonlee** [iissnan/hexo-theme-next#775]
### Actual behavior (实际行为)

![default](https://cloud.githubusercontent.com/assets/15051896/14180290/feb2a9ae-f794-11e5-95ef-2dbf694baa6a.png)

### NexT Version, NexT Scheme

- NexT Version:

  - 0.50

- NexT Scheme:

  - Pisces

- 高亮主题：

  - night blue

**Comment by iissnan** [comment]
See #771
