### ISSUE TITLE
Reward 引起样式变形

### ISSUE THREAD

**Issue by luffr** [iissnan/hexo-theme-next#777]
### Actual behavior (实际行为)

问题一
在使用打上赏功能后，下面的点击前一篇文章（ <Hello World!）的文字和箭头变成居中了，而不是左对齐，查看后一篇文章的话是正常的，打赏功能的贡献者的博客也有这样的情况。我的博客出现的情况，打赏功能贡献者的博客的情况，把打赏功能注释掉又正常了，不知问题出在哪里。

问题二
赏字和背景圆圈没有上下居中### Steps to reproduce the behavior (重现步骤)
### NexT Version, NexT Scheme

NexT Version:
- [ ] Master
- [ ✔] Latest Release
- [ ] Old version -

NexT Scheme:
- [ ] Muse
- [ ✔] Mist
- [ ] Pisces

**Comment by ivan-nginx** [comment]
@luffr dont understand u, write in English if not solved. If solved, close it please.
