### ISSUE TITLE
reward 功能在手机上的现实问题

### ISSUE THREAD

**Issue by luffr** [iissnan/hexo-theme-next#778]
### Expected behavior (预期行为)

在手机浏览器上看博文，点击“赏”，展开二维码，赏字背景色变色，再点击，收起，背景色恢复
### Actual behavior (实际行为)

再点击，收起，没有回复颜色
### NexT Version, NexT Scheme

NexT Version:
- [ ] Master
- [✔ ] Latest Release
- [ ] Old version -

NexT Scheme:
- [ ] Muse
- [✔ ] Mist
- [ ] Pisces

**Comment by luffr** [comment]
@habren 不知道这个算不算问题？

**Comment by dkylin** [comment]
我也遇到了相同的问题，当点击收起之后，“赏”字没有恢复颜色。此时再点击一下屏幕其他地方，“赏”字会恢复颜色。感觉有点诡异！

**Comment by ivan-nginx** [comment]
@luffr dont understand u, write in English if not solved. If solved, close it please.
