### ISSUE TITLE
請問為什麼無法使用markdown的流程圖、甘特圖之類的圖表？

### ISSUE THREAD

**Issue by kintsuicris** [iissnan/hexo-theme-next#779]
### Expected behavior (预期行为)
按照網上的實例，應該是正確的markdown語法，如下：
gantt
        dateFormat  YYYY-MM-DD
        title Adding GANTT diagram functionality to mermaid
        section A section
        Completed task            :done,    des1, 2014-01-06,2014-01-08
        Active task               :active,  des2, 2014-01-09, 3d
        Future task               :         des3, after des2, 5d
        Future task2               :         des4, after des3, 5d
        section Critical tasks
        Completed task in the critical line :crit, done, 2014-01-06,24h
        Implement parser and jison          :crit, done, after des1, 2d
        Create tests for parser             :crit, active, 3d
        Future task in critical line        :crit, 5d
        Create tests for renderer           :2d
        Add to mermaid                      :1d

### Actual behavior (实际行为)
但是在hexo裡無法顯示正確的圖表，而是文本。

**請問是Hexo不支持還是next主題不支持呢？？**

**Comment by iissnan** [comment]
这看起来不是标准的 Markdown，你可能需要为 Hexo 安装这种风格 Markdown （假若有）的插件。
