### ISSUE TITLE
next主题如何在首页摘要里显示文章图片？

### ISSUE THREAD

**Issue by xuqianzheng** [iissnan/hexo-theme-next#780]
### 就像下面这样：

![image](https://cloud.githubusercontent.com/assets/7781982/14198712/dc6f9dd6-f80f-11e5-82b1-6709b5859508.png)

**Comment by iissnan** [comment]
如果你知道怎么设置文章摘录，我相信这个不是个问题。

因此请先看下文档如何设置 文章摘录（阅读全文）：[常见问题 - NexT 使用文档](http://theme-next.iissnan.com/faqs.html)

**Comment by xuqianzheng** [comment]
现在设置了摘要，但是首页摘要里只显示了文字，未显示图片。如何将图片也显示在摘要里？

**Comment by iissnan** [comment]
```
段落一

![图片](/path-to-image)

段落二 

<!-- more -->
```

`<!-- more -->` 以上的内容可以任意写

**Comment by aqiongbei** [comment]
虽然这个问题关闭了,但是我觉得还有有必要再答一下.我按照 @iissnan 的方法并没有实现在首页出现图片.在查找了三四个小时之后,最终从HEXO官网得到了解决方法.[解决首页不能出现图片问题](https://hexo.io/zh-cn/docs/asset-folders.html).希望可以帮到更多的人.

**Comment by aliveaway** [comment]
如何在首页摘要显示图，正文不显示图
