### ISSUE TITLE
如何设置侧边栏默认在左侧显示

### ISSUE THREAD

**Issue by JeffXue** [iissnan/hexo-theme-next#781]
版本 0.4.5.2

scheme：mist

设置saidebar: always ，但是实际并没有一直显示侧边栏

另外怎么样设置侧边栏一直在左侧显示？

**Comment by iissnan** [comment]
0.4 版本的 Mist 并不支持如此设置（5.0 实际上也不支持），这个功能预计会在 5.0.1 中。

**Comment by jiexishede** [comment]
现在能在左边显示了吗， 我改了配置文件，在左显示，但是网页仍然在右边显示了。
