### ISSUE TITLE
NexT主题下的两种搜索服务的问题？

### ISSUE THREAD

**Issue by dkylin** [iissnan/hexo-theme-next#784]
NexT主题有两种搜索服务：Swiftype和微搜索。
现在Swiftype收费了。而且好贵，表示暂时已经放弃。
微搜索免费，准备使用微搜索，却发现现在微搜索里面创建不了引擎。返回500错误。好多天了都是这样。
不知道大神们有没有其他的解决方案？

**Comment by iissnan** [comment]
试试 https://github.com/iissnan/hexo-theme-next/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2

**Comment by dkylin** [comment]
@iissnan 我按照这个方法尝试了一下，的确是可以进行站内搜索，但是我的是搜索按钮，不是输入框，但我点击搜索按钮的时候，搜索界面闪一下就消失了。必须是要我点击搜索按钮然后拖动鼠标才可以显示出搜索界面而不消失。请问这是正常的吗？

**Comment by flashlab** [comment]
更新到最新版本试试

**Comment by dkylin** [comment]
NexT主题已更新到5.0。之前的问题已解决。感谢大神们的帮助。 @flashlab @iissnan

**Comment by seanlook** [comment]
@iissnan 
Swiftype 已经不提供免费的了，基础版最低 $299/mo，是不是可以考虑从next中去掉了。

有没有考虑过集成 谷歌自定义搜索（https://cse.google.com/cse/all）

**Comment by cttin** [comment]
@iissnan 你好。我想问下我设置了之后可以搜索到。但是无法跳转到正确的页面是怎么回事呢。我不是很清楚什么原因。能麻烦帮忙看看么。谢谢了。cttin.github.io

**Comment by youngxhui** [comment]
@cttin 我也遇到了同意的问题

**Comment by youngxhui** [comment]
@cttin 将配置写成下面格式
``` yml
search:
  path: search.xml
  field: all
  format: html
  limit: 10000
```

**Comment by Twor** [comment]
@youngxhui 你好 为什么我改了还是出错   FATAL duplicated mapping key at line 75, column -104:
    search:
    ^
YAMLException: duplicated mapping key at line 75, column -104:
    search:
    ^
    at generateError (D:\blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (D:\blog\node_modules\hexo\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)

**Comment by iissnan** [comment]
@Twor 配置文件中有重复的 `search`，找出来合并下（或删除其中一个）就行。
