### ISSUE TITLE
[建议]要不要把浏览器自动判断电话号码去掉

### ISSUE THREAD

**Issue by chitanda** [iissnan/hexo-theme-next#785]
目前主要是针对EDGE浏览那个神经的匹配。。他们 的规则好像考虑的比较多，chrome都不会匹配到的软件版本号到EDGE上就成电话号码了，比如·`Chrome 47.0.2526.106`这么一个版本号
而这个问题对于next主题而言，最主要的是出在`多说评论显UA`这个功能上，其他浏览器倒也没啥，唯独chrome刷版本刷的飞起然后js里又是截取的完整版本号，所以容易被误判。
### Expected behavior (预期行为)

 ![image](https://cloud.githubusercontent.com/assets/8258592/14225707/ca196758-f8fe-11e5-92af-f00769cbd1a4.png)

### Actual behavior (实际行为)

![image](https://cloud.githubusercontent.com/assets/8258592/14225704/c4fc2efe-f8fe-11e5-9945-2866c1b23d4f.png)

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔ Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  ✔ All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

亲测加个meta头就可以去掉。
```
<meta name="format-detection" content="telephone=no">
```
**但是这个meta头是通用的，会影响到手机浏览器上真正的号码识别。**所以仅当一个建议供参考。

**Comment by chitanda** [comment]
同样付个edge上看这个帖子的图：
![image](https://cloud.githubusercontent.com/assets/8258592/14225728/6b4bce22-f8ff-11e5-9bbd-4413bd45f572.png)

**Comment by jerrybendy** [comment]
@chitanda  这个感觉还是不要限制的好

**Comment by iissnan** [comment]
全局限制范围太广，一个 workaround 是针对多说 UA 的样式以及链接做处理就好。

**Comment by chitanda** [comment]
@iissnan @jerrybendy  
确实我也感觉全局范围大了，但是由于这个是浏览器事件，css应该限制不了。。感觉另一个处理办法可能是js给出的UA不那么细致？但又感觉也有点欠妥。。

**Comment by iissnan** [comment]
试试这个 IE 的私有 attribute [x-ms-format-detection](https://msdn.microsoft.com/en-us/library/dn337007(v=vs.85).aspx)

[参考](https://msdn.microsoft.com/en-us/library/dn265018(v=vs.85).aspx#Controlling phone number detection)

**Comment by chitanda** [comment]
@iissnan 想想还是算了。。IE禁了估计又要影响WP了。。就这样好了。
