### ISSUE TITLE
发现博客打开慢，看了看是谷歌字体的问题

### ISSUE THREAD

**Issue by luozongtong123** [iissnan/hexo-theme-next#786]
请问怎么更改为其他的字体源

**Comment by huiwang** [comment]
@luozongtong123 请问您是依据什么推断出来是字体的问题？

**Comment by iissnan** [comment]
@luozongtong123  在 5.0.0 中需要更改模板 `layout/_partials/head.swig`，搜索 `fonts.googleapi`，替换成你需要使用的 cdn

**Comment by luozongtong123** [comment]
@huiwang 昨天我发现很慢，分析性能后发现这个请求
https://fonts.googleapis.com/css?family=Lato:300,400,700,400italic&subset=latin,latin-ext
占用很大时间。
今天看又正常了。很奇怪

**Comment by luozongtong123** [comment]
@iissnan 谢谢

**Comment by ifyour** [comment]
@luozongtong123 

替换成这个吧：
`https://fonts.useso.com/css?family=Open+Sans:300,400,600&subset=latin,latin-ext`

**Comment by chitanda** [comment]
google字体我记得国内其实不墙的。。但是有时候又确实是被这个字体拖累了。很奇怪。

**Comment by huiwang** [comment]
给大家推荐一个工具，测试网页加载性能的，我刚测了一下我的博克，有如下结果。我是在法国测得，我的瓶颈在baidu的push和share代码，我觉得我有必要优化一下啊。

http://tools.pingdom.com/fpt/#!/eBVFVg/http://hui-wang.info/2016/02/25/%E5%BD%93%E7%A8%8B%E5%BA%8F%E5%91%98%E8%80%81%E4%BA%86/

![image](https://cloud.githubusercontent.com/assets/720508/14244929/49e7c7d0-fa5e-11e5-8bdc-9112ccce67c0.png)

**Comment by iissnan** [comment]
后续版本会开放一些字体的自定义，感兴趣的可以先看看这个 [commit](https://github.com/iissnan/hexo-theme-next/commit/f9a101c71328e68abceab3a4f2ee55958f65591f)

**Comment by njzhenghao** [comment]
还有个gstatic也是慢的出奇，在哪里替换呢
![](http://ww3.sinaimg.cn/large/6a8b44dbjw1f2p1die98hj20l001kwf0.jpg)

**Comment by wonderffee** [comment]
现在useso也停止服务了
