### ISSUE TITLE
support csp header script-src 'self'

### ISSUE THREAD

**Issue by timkuijsten** [iissnan/hexo-theme-next#79]
Currently there is a lot of inline javascript. In order to support [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives) (and mitigate XSS) the content should be split by type. Html content should only contain html and JavaScript should be put in .js files and not be mixed within the html.

Would you guys consider a pull request where I have moved all inline javascript into separate .js files?

So i.e. layout/_scripts/fancy-box.swig would be changed from:

    {% if theme.fancybox %}
      <script type="text/javascript" src="{{ url_for(theme.vendors) }}/fancybox/source/jquery.fancybox.pack.js"></script>
      <script type="text/javascript">
        $(document).ready(function() {
          $(".fancybox").fancybox();
        });
      </script>
    {% endif %}

to something like:

    {% if theme.fancybox %}
      <script type="text/javascript" src="{{ url_for(theme.vendors) }}/fancybox/source/jquery.fancybox.pack.js"></script>
      <script type="text/javascript" src="{{ url_for(theme.vendors) }}/fancybox_loader.js"></script>
    {% endif %}

and source/vendors/fancybox_loader.js would contain:

        $(document).ready(function() {
          $(".fancybox").fancybox();
        });

This would enable the browser to enforce stronger and simpler rules on what to parse and prevents some commonly used XSS techniques. Using CSP and separation of concerns is generally a good thing imho.

**Comment by iissnan** [comment]
That's right. Could you please issue a pull request of your changes. Thanks in advanced.

**Comment by timkuijsten** [comment]
Shall I continue with the other layout scripts like I did with fancy-box https://github.com/timkuijsten/hexo-theme-next/commit/c7c72c94ee72867ac4a81cd021581b305b94dac4 and bootstrap.scrollspy https://github.com/timkuijsten/hexo-theme-next/commit/37e866512c3489bae7e95cb5589e70018bfe2353?

**Comment by iissnan** [comment]
Hi @timkuijsten. Could you please put those scripts into `source/js` directory instead of `vendors/csp`。

**Comment by iissnan** [comment]
One more thing, I am wondering if we can combine some scripts into one to reduce additional HTTP Request?

**Comment by timkuijsten** [comment]
I'll move from csp to the js dir.

What about using something to concatenate and minimize on deployment so that production is fast, and deployment is easier to spot bugs with separate js files? Not sure if it's possible to hook a concat and minimize script into hexo deployment though.

I'm not sure what to do with the swig in this code: https://github.com/timkuijsten/hexo-theme-next/commit/a66ccbcbde579683b27bde36c3df7d2ea6832823#diff-dc23ad32d834481d60378dd2f933cbe1L48. You have any suggestions?

**Comment by timkuijsten** [comment]
update: I'm successfully running the current set of patches on my personal blog where I've changed the Content-Security-Policy header from:

     default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self' data:

to:

    default-src 'self'; img-src 'self' data:

I still have to convert the comments templates, pages and mathjax.swig. And I still hope you have a good advice for https://github.com/timkuijsten/hexo-theme-next/commit/a66ccbcbde579683b27bde36c3df7d2ea6832823#diff-dc23ad32d834481d60378dd2f933cbe1L48 as mentioned before.

**Comment by timkuijsten** [comment]
Maybe it's possible to merge the work that is already done and functioning? This offers stricter csp for those that don't include any analytics or other tracking services.

You can see the above commits running in production on https://blog.netsend.nl/

**Comment by iissnan** [comment]
Yes. Please send out your modifications. Thanks.

**Comment by timkuijsten** [comment]
Alright, see https://github.com/iissnan/hexo-theme-next/pull/152.
