### ISSUE TITLE
NexT.Pisces：Markdown块引用出现黑底黑字bug

### ISSUE THREAD

**Issue by ifyour** [iissnan/hexo-theme-next#790]
- 更新到`NexT.Pisces`主题后，块引用内容出现黑底黑字，影响阅读。

- 用鼠标选中文字时，才会显示内容。
- 重现： 编辑 markdown 时，选中文字按 Table 一下增加块引用

- 截图：
<img width="682" alt="2016-04-04 16 29 43" src="https://cloud.githubusercontent.com/assets/15377484/14242169/78a50fe6-fa82-11e5-952a-2a6af624d150.png">

**Comment by ifyour** [comment]
```
# Code Highlight theme
highlight_theme: night eighties

# Theme version
version: 5.0.0
```

**Comment by iissnan** [comment]
已修复，请更新到 master 分支最新版本。

**Comment by iissnan** [comment]
@seanlook

**Comment by seanlook** [comment]
good job
