### ISSUE TITLE
关于自己实现hexo主题

### ISSUE THREAD

**Issue by QAQMiao** [iissnan/hexo-theme-next#791]
您好，我刚刚用hexo搭建了一个博客，作为一个前端，我想自己去设计博客的样式，然后用hexo提供的后端，但是我现在不太清楚该从哪里入手，或者说应该修改哪里。请问有什么教程或者资源可以参考么？

**Comment by iissnan** [comment]
https://hexo.io/zh-cn/docs/themes.html
