### ISSUE TITLE
disqus isn't working..

### ISSUE THREAD

**Issue by yuuuxt** [iissnan/hexo-theme-next#792]
### Expected behavior (预期行为)

disqus works
### Actual behavior (实际行为)

"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."
### Steps to reproduce the behavior (重现步骤)

set disqus_shortname, 
added trusted domains on disqus, 
generate static file;
using nginx, set path to the public folder; 

disqus isn't working, but duoshuo works.
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master ✔  
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse (haven't tested)
-  Mist ✔  
-  Pisces ✔  
### Other Informations (Like Browser, System, Screenshots)

firefox, chrome

**Comment by iissnan** [comment]
Please refer to [Disqus Help](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)

**Comment by yuuuxt** [comment]
I did read it, tried to create a new site in disqus and use the new short name, but it doesn't work. The name of the article is just hello world, no non-ascii characters. 

not sure what goes wrong. Duoshuo works. 

more info about hexo blog:
I clone the blog repo to the VPS, and generate the static file there, set the nginx path to the generated public folder, and it seems to be working well. 

If it's not reproducible, leave it there, thx :)

**Comment by chy9002** [comment]
I had same issue earlier, Disqus requires disqus_url must has http/https, add it in the url will be work.

**Comment by yuuuxt** [comment]
@chy9002 exactly. 

modify disqus.swig under /layout/_scripts/third-party/comments/, 
before: var disqus_url = '{{ page.permalink }}';
after: var disqus_url = 'http://'+'{{ page.permalink }}';

Then things are working. I'm not sure if it's the right way to let it work, please check it @iissnan 
one more thing, the comment counter is not working though.

**Comment by iissnan** [comment]
@yuuuxt Or you can just remove the `disqus_url` variable.

**Comment by brucexiejiaming** [comment]
Removing `disqus_url` works for me.

**Comment by GongchuangSu** [comment]
Removing  the `disqus_url` variable works for me too.

**Comment by ivan-nginx** [comment]
@yuuuxt solved?

**Comment by yuuuxt** [comment]
@ivan-nginx manually, see " yuuuxt commented on 22 May 2016"

**Comment by ivan-nginx** [comment]
@yuuuxt close it?
