### ISSUE TITLE
更喜欢之前的版本，可以把之前的版本也放出来吗？

### ISSUE THREAD

**Issue by iuunhao** [iissnan/hexo-theme-next#794]
更喜欢之前的版本，可以把之前的版本也放出来吗？

**Comment by jcf94** [comment]
之前的版本在 github 的 releases 里面，或者你对 git 熟悉的话，也可以使用 git 命令直接回滚到以前任意一个时刻的版本。

**Comment by iuunhao** [comment]
好的，谢谢
