### ISSUE TITLE
back-to-top 在safari下无法显示

### ISSUE THREAD

**Issue by XMT611** [iissnan/hexo-theme-next#795]
和 #735 问题相似
应该是utils.js里的问题

不知道如何修改呢？

**Comment by XMT611** [comment]
在safari的console内获取window.pageYOffset 都是正常的可以获得相应的数据
就是不知道为什么js不生效

对了，在chrome和firefox测试下都是正常的可以在滚动50px之后出现

**Comment by iissnan** [comment]
我测试了 Safari 9.1 和 Technical Preview 都可以正常 work。

**Comment by XMT611** [comment]
@iissnan 感谢回复。。。。我试了试depoly到git上然后访问网页发现safari是正常work的，但是自己本地启动server然后在localhost下调试safari就永远无法出现。。。。好奇怪的问题

**Comment by iissnan** [comment]
确实有点奇怪

**Comment by cnrting** [comment]
我也碰到这个奇怪问题，原来用着好好的，某天发现返回顶部按钮不见了，可是在PC端却是有的，不知道作者为什么要加这个样式，貌似没啥用，留个爪印吧，注释掉下面的就可以了，可以参考一下
```
/*
@media (min-width: 768px) and (max-width: 991px) {
  .back-to-top {
    display: none !important;
  }
}
@media (max-width: 767px) {
  .back-to-top {
    display: none !important;
  }
}*/
```

**Comment by stevenjoezhang** [comment]
@cnrting 已经在新版本修复了，请移步这里：https://github.com/theme-next/hexo-theme-next
