### ISSUE TITLE
升级到最新的0.5.0版本代码高亮有问题

### ISSUE THREAD

**Issue by seanlook** [iissnan/hexo-theme-next#796]
安装hexo-theme-next的0.5.0版本后，凡是 ``` 显式高亮代码的片段都正常：
```
` ` `
      select * from percona.checksums where master_cnt <> this_cnt OR master_crc <> this_crc OR 
      ISNULL(master_crc) <> ISNULL(this_crc) \G
` ` `
```
![hexo-next-highlight-ok](https://cloud.githubusercontent.com/assets/9251710/14277129/5fa14bc2-fb54-11e5-95df-9f97524ff62b.png)

四个空格键`    `的方式高亮的代码都看不清：

```

      select * from percona.checksums where master_cnt <> this_cnt OR master_crc <> this_crc OR 
      ISNULL(master_crc) <> ISNULL(this_crc) \G

```
![hexo-next-highlight](https://cloud.githubusercontent.com/assets/9251710/14277130/5fd2d976-fb54-11e5-8fcf-8b320074e0e1.png)

Mist,Muse,Pisces 都受影响

**Comment by iissnan** [comment]
#790
