### ISSUE TITLE
“关于”页面的标题一直是英文“About”

### ISSUE THREAD

**Issue by S-X-ShaX** [iissnan/hexo-theme-next#797]
按照http://www.arao.me/2015/hexo-next-theme-optimize-base/#more修改了标题格式。可是我的“关于”页面的标题却一直是“About”而不是中文的”关于“啊。我用的是zh-Hans的languange。还在这个文件的title部分正确添加了about: 关于。可是还是不见效。

**Comment by ifyour** [comment]
修改博客目录下`source/about`的`index.md`

**Comment by S-X-ShaX** [comment]
里面是默认的title:
about，按理说这样他不是会去zh-Hans文件里寻找title:下面的about值吗，我已经正确设定了为关于，可还是不管用啊

On Tue, Apr 5, 2016, 21:16 Willard Wang <notifications@github.com> wrote:

> 修改博客目录下source/about的index.md
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/iissnan/hexo-theme-next/issues/797#issuecomment-205797781>
>
-- 

请叫我喵 | S-X-ShaX
A Dreamer,
From Inbox by Gmail.

**Comment by mritd** [comment]
其实我看半天 也没搞懂 你们在讨论什么。。。。

**Comment by S-X-ShaX** [comment]
就是浏览器顶端的标题，“关于”页面的标题总是英文而不是中文。

On Tue, Apr 5, 2016, 22:08 mritd <notifications@github.com> wrote:

> 其实我看半天 也没搞懂 你们在讨论什么。。。。
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/iissnan/hexo-theme-next/issues/797#issuecomment-205825664>
>
-- 

请叫我喵 | S-X-ShaX
A Dreamer,
From Inbox by Gmail.

**Comment by iissnan** [comment]
设置在 about/index.md 中  `title` 为你想要的值即可，这个地方没有做翻译。

```yml
title: 关于
```

**Comment by S-X-ShaX** [comment]
好吧，我明白啦。那以后会不会添加上翻译呢？

**Comment by iissnan** [comment]
不会，翻译反而增加了限制
