### ISSUE TITLE
如何给Mist添加阅读数量呢?

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#798]
请教一下如何给Mist添加阅读数量呢?

在Pisces下的阅读数量效果 如何添加到Mist上呢?

万分感谢!

**Comment by iissnan** [comment]
设置并启用 LeanCloud 后所有 Scheme 都可以显示“阅读数”，若未生效可能是你正在使用的主题版本过低，升级后试试。

[LeanCloud 阅读数设置](http://theme-next.iissnan.com/getting-started.html#leanclound-page-views)

**Comment by AlanCheen** [comment]
@iissnan 好的 今天晚上回去试试  谢谢

**Comment by AlanCheen** [comment]
可以是可以  但是 关于 等页面又没了
