### ISSUE TITLE
5.0.0中的baidu_push如何使用？

### ISSUE THREAD

**Issue by 80imike** [iissnan/hexo-theme-next#799]
只需将_config.xml中baidu_push: false设成true? 
看官方示例都要填一个token的？
这个在那里设置？

**Comment by iissnan** [comment]
你看的可能是 [百度云推送](http://push.baidu.com/)。这个 push 是指站长平台的 [自动推送工具](http://zhanzhang.baidu.com/college/courseinfo?id=267&page=2#h2_article_title19)

**Comment by 80imike** [comment]
@iissnan
我就是看的这个推送， 这里的例子  

1）curl推送示例
将要提交的url数据写入一个本地文件，比如urls.txt，每个url占一行，然后调用curl命令：
curl -H 'Content-Type:text/plain' --data-binary @urls.txt
"http://data.zz.baidu.com/urls?site=www.example.com&token=edk7yc4rEZP9pDQD"
使用php、python、java等可以参照这个过程推送结构化数据。

是要一个token的

@iissnan  你的意思baidu_push: true 就可以用了？

**Comment by iissnan** [comment]
那是主动推送

**Comment by iissnan** [comment]
`biadu_push: true` 就可以了。

**Comment by 80imike** [comment]
@iissnan 谢谢  已明白
