### ISSUE TITLE
怎样能在Mist博文中插入的图片下方增加「图片描述」呢？只有图片略显单调……

### ISSUE THREAD

**Issue by 24suixinsuoyu** [iissnan/hexo-theme-next#800]
文档编辑器我用的是Macdown，好像不支持加入图片描述。简书也支持Markdown语法，就可以在图片下方添加图片描述。

**Comment by geekrainy** [comment]
图片要加title属性。

**Comment by 24suixinsuoyu** [comment]
懂了，多谢~~

**Comment by iissnan** [comment]
另外也需要开启 Fancybox。

**Comment by 24suixinsuoyu** [comment]
额，对这个Fancybox还不熟悉，回头google一下。还有个问题，怎样让插入的图片居中而不是默认的左对齐呢？图片左对齐然而图片描述居中，看着让人挺不舒服的

**Comment by Explorare** [comment]
@24suixinsuoyu 
```
.post-body .image-caption {
    margin: 10px auto 15px;
    text-align: center;
    font-size: $font-size-base;
    color: $grey-dark;
    font-weight: bold;
    line-height: 1;
}
```
>\source\css\_common\components\post\post.styl Line 18

Change `center` to `left`.

**Comment by 24suixinsuoyu** [comment]
thanks

**Comment by ZHJ0125** [comment]
您好，我使用的是`Gemini`样式，默认是显示图片描述的。
我不想让它显示图片描述，请问有什么办法可以设置不显示吗？
谢谢 ☺

**Comment by ZHJ0125** [comment]
> 另外也需要开启 Fancybox。

您好，我使用的是Gemini样式，我不想让它显示图片描述，请问有什么办法可以设置不显示吗？
谢谢 ☺

**Comment by ZHJ0125** [comment]
已经解决，参考了这篇博客：https://wylu.github.io/posts/7bd83fc5/
谢谢大家！
