### ISSUE TITLE
阅读计数。对比LeanCloud和不蒜子

### ISSUE THREAD

**Issue by carpliyz** [iissnan/hexo-theme-next#801]
### Expected behavior (预期行为)
阅读次数统计

### Actual behavior (实际行为)
目前使用的是LeanCloud统计

### Steps to reproduce the behavior (重现步骤)

增加不蒜子统计，见[**不蒜子**](http://busuanzi.ibruce.info/ )
只需要几行代码

#### 引入脚本
```
<script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js">
</script> 
```
####    添加到文章指定位置 应该是。。不会写代码😁
```
<span id="busuanzi_value_page_pv"><i class="fa fa-spinner"></i></span> Hits
```
  
  
  
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
加一个配置不难，有感兴趣的话可以给我提 PR

**Comment by mcknote** [comment]
前天用 Pingdom 測試，發現不蒜子的 js 載入時間特長，想說也用不到這個功能，就先拿掉了。不過安裝起來確實很容易。

**Comment by panzhitian** [comment]
不蒜子读取数据的速度是比较慢，能自建服务器的话可能会更好用

**Comment by geekrainy** [comment]
Leancloud的可靠性应该要比不蒜子好。

**Comment by carpliyz** [comment]
刚才测了一下，读取js的速度还可以呀。
PR https://github.com/iissnan/hexo-theme-next/pull/808   只有几行代码，并且默认使用

用不蒜子 主要是避免再注册一个Leancloud了，话说eancloud 的功能真的蛮多的。


而且不蒜子的js放在七牛，速度应该不慢，如果说速度慢，可能是七牛的原因，七牛[问答社区](https://segmentfault.com/qiniu) 很多人反映这几天云存储速度慢＝＝

**Comment by panzhitian** [comment]
我也提交了个#809 主要是提高可定制性，将某页面的pv也加入，但是因为不蒜子不支持在主页显示，所以只能在文章页可见。可能有点dirty，上传后缩进也乱了。。。

**Comment by iissnan** [comment]
已合并 @panzhitian 的版本，多谢大家的努力。

**Comment by carpliyz** [comment]
@iissnan 合并之后测试一下。  **底部**的样式＝＝
![屏幕快照 2016-04-10 00.49.02.png](https://ooo.0o0.ooo/2016/04/09/570933910a27a.png)
![屏幕快照 2016-04-10 00.48.52.png](https://ooo.0o0.ooo/2016/04/09/57093391222d0.png)

**Comment by panzhitian** [comment]
兼容性还是差点，我只在Pisces上测试了。
css那里还需增加条件，明天再fix。

**Comment by yusmile** [comment]
@carpliyz  那可以同时在一个博客上启用LeanCloud和不蒜子 两套统计吗？会不会冲突？

**Comment by neroshare** [comment]
@panzhitian 添加什么条件需要，我也用的pisces,试了试统计不出数字
