### ISSUE TITLE
请问Hello标题前面有一个小小的button，怎么改回来

### ISSUE THREAD

**Issue by errorlife** [iissnan/hexo-theme-next#802]
### Expected behavior (预期行为)
Hello标题前面没有一个小小的button

### Actual behavior (实际行为)

![image](https://cloud.githubusercontent.com/assets/16152382/14323022/776ecc36-fc51-11e5-8511-747c1121b95a.png)

### Steps to reproduce the behavior (重现步骤)

对比了配置文件，好像没有改变什么。
是站点配置文件的问题吗
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by errorlife** [comment]
@iissnan 大神有空帮我看看咯

**Comment by iissnan** [comment]
我记得在某一个版本的 文章标题有加一条竖线，后面去掉了。你所使用的是新版本吗？

**Comment by errorlife** [comment]
@iissnan  不是呢。我使用的是：version: 0.4.5.2。只是一开始没有竖线的，后来不知道搞了什么就。。

**Comment by iissnan** [comment]
可以考虑升级下主题

**Comment by errorlife** [comment]
感谢😊
