### ISSUE TITLE
Sidebar Improvements for Desktop

### ISSUE THREAD

**Issue by iissnan** [iissnan/hexo-theme-next#803]
### Expected behavior (预期行为)

Sidebar could be placed in the left/right for all schemes.
Sidebar could be displayed without animation.
### Actual behavior (实际行为)

Sidebar could not be placed in left for Muse and Mist scheme.
Sidebar could not be displayed without animation.
### NexT Informations

NexT Scheme:
-  All schemes

**Comment by ivan-nginx** [comment]
Implemented in [NexT v7.3.0](https://github.com/theme-next/hexo-theme-next/releases/tag/v7.3.0) ([#951](https://github.com/theme-next/hexo-theme-next/pull/951))
