### ISSUE TITLE
social link 添加 instagram 排版出错

### ISSUE THREAD

**Issue by meritozh** [iissnan/hexo-theme-next#810]
主题为`NexT.Pisces`
就多了一个字符，8位的`facebook`就没问题。
希望调整下`sidebar`宽度，支持9个字符长度。

**Comment by meritozh** [comment]
建议给`social`也添加`enable`属性，可以只显示`icon`，不显示`link label`

**Comment by iissnan** [comment]
多谢反馈

**Comment by iissnan** [comment]
文本换行的已经处理了。隐藏 Label 的 requirement 暂不做支持
