### ISSUE TITLE
友情链接显示不全

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#811]
以前的版本友情链接的显示是类似标签云,但是现在显示是垂直的了,pull了新代码就这样了,不知道哪里错误,可以帮忙看一下么?  http://yifeiyuan.me  非常感谢

**Comment by iissnan** [comment]
是在 5.0.0 的一个版本中做了调整，我发现有不同的使用场景，或许需要增加一个配置选项。可以自行定义是水平或者垂直排列。

**Comment by AlanCheen** [comment]
那是要等下一个版本了么？

**Comment by mritd** [comment]
同问。。很丑现在。。。。

![原友链](http://7xrp5k.com1.z0.glb.clouddn.com/2016-04-12_160946.png)

![新友链](http://7xrp5k.com1.z0.glb.clouddn.com/2016-04-12_160959.png)

**Comment by AlanCheen** [comment]
不知作者如何打算?  @iissnan

**Comment by iissnan** [comment]
5.0.1 近期会更新

**Comment by AlanCheen** [comment]
好的 谢谢

**Comment by mritd** [comment]
请问 5.0.1 修复了么？

**Comment by mritd** [comment]
每个友链前面的 小圆点 去掉了么？

**Comment by missyun** [comment]
同问，怎么设置不是竖排列。谢谢

**Comment by ivan-nginx** [comment]
@AlanCheen dont understand u, write in English if not solved. If solved, close it please.
