### ISSUE TITLE
wechat_subscriber 如何使用?

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#812]
新pull了代码,很惊喜得看到 了 wechat_subscriber 的配置,看了官方文档,并没有提到,所以 想请教一下

wechat_subscriber 的图片应该放在主题目录,还是站点目录呢?

我都尝试了,但是效果没有出来,还望指导!

非常感谢!

**Comment by AlanCheen** [comment]
看到文档了..

**Comment by AlanCheen** [comment]
还是不知道应该放在哪个目录下- -  可否告知一下呢？

好吧 原谅我这么笨。。。

**Comment by iissnan** [comment]
将图片放置在站点目录的 `source/uploads` 里。如果站点是在子目录下，要写成类似 `/blog/uploads/path-to-qrcode`

**Comment by AlanCheen** [comment]
好的 谢谢回复  今晚回家试试

**Comment by AlanCheen** [comment]
谢谢 可以了
