### ISSUE TITLE
侧栏icon和标题过长显示的问题

### ISSUE THREAD

**Issue by bytecho** [iissnan/hexo-theme-next#813]
### Expected behavior (预期行为)
Pisces主题下,添加stackoverflow链接时，icon和标题在同一行

### Actual behavior (实际行为)
icon把stackoverflow挤到下一行,是否是因为限制了条目宽度的问题？

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master

NexT Scheme:
  -  Pisces

**Comment by meritozh** [comment]
#810

**Comment by iissnan** [comment]
Refer to #810
