### ISSUE TITLE
Uncaught TypeError: NexT.utils.needAffix is not a function

### ISSUE THREAD

**Issue by HaloWang** [iissnan/hexo-theme-next#814]
在本地 `$ hexo s` 没有任何问题
`$ hexo g` 上传到 Github Pages，点击阅读更多进入某个页面就报错了😰
比如下面这篇博客
http://halowang.github.io/2016/03/09/introduction-of-Halo/#more
npm hexo next 都是最新版

**Comment by iissnan** [comment]
`utils.js` 里面少了两个函数。试试先 `hexo clean` 下，再不行将 `.deploy_git` 目录删除后重新 deploy.

**Comment by HaloWang** [comment]
😂直接重装了一遍 hexo，已解决 ~
