### ISSUE TITLE
5.0 版本样式有问题，导致整个页面空白

### ISSUE THREAD

**Issue by kraaas** [iissnan/hexo-theme-next#817]
![20160410141246](https://cloud.githubusercontent.com/assets/11005827/14408406/5082a28c-ff26-11e5-835d-5675095860e8.png)

**Comment by iissnan** [comment]
应该是脚本报错了。试试 hexo clean 后重新生成

**Comment by iissnan** [comment]
#814

**Comment by ivan-nginx** [comment]
@kraaas dont understand u, write in English if not solved. If solved, close it please.
