### ISSUE TITLE
有关TAG自动生成问题

### ISSUE THREAD

**Issue by Jermic** [iissnan/hexo-theme-next#82]
![2015-04-03 1 38 11](https://cloud.githubusercontent.com/assets/5131979/6969564/3cf8ce3a-d9a2-11e4-8351-9d52bbcf8f1e.png)  按照标签云的设置配置了，但是这个地方没有自动生成，，请问一下这个是还需要安装其它插件么？还是其它的什么问题？

**Comment by smilexiamo** [comment]
关键字后面要留一个 空格

**Comment by venidic** [comment]
我的标签云也是这个样子，包括 分类，也是按照设置配置的，而且在type后也加了空格，可是最后访问的页面都是这个样子的，请问这是什么原因呢？应该怎么解决呢？谢谢

**Comment by eurusd** [comment]
title: 标签
date: 2015-03-23 17:14:37
type: "tags"
---

**Comment by Jermic** [comment]
在 tags/index.md   中   最后一行添加  ---

**Comment by venidic** [comment]
谢谢各位，问题已解决
