### ISSUE TITLE
为什么放到服务器上。全变了。

### ISSUE THREAD

**Issue by errorlife** [iissnan/hexo-theme-next#820]
###这是本地版

![2 2](https://cloud.githubusercontent.com/assets/16152382/14426522/29d72c50-0022-11e6-83cc-7e848ca29ca4.png)

###这是服务器版
![2 1](https://cloud.githubusercontent.com/assets/16152382/14426521/29d30ca6-0022-11e6-94c8-82c1c4ef2b13.png)
已经重新生成public，上传到服务器了
1. 旧版本的标题前的一个小button出来了。
2. 整个页面变宽了。

@iissnan  大神有空帮帮看看。

**Comment by errorlife** [comment]
两张图颠倒了

**Comment by panzhitian** [comment]
css缓存？是否用了cdn，试下更新缓存，或者修改`version`让其校验

**Comment by mritd** [comment]
你需要 Docker 。。。

**Comment by errorlife** [comment]
@panzhitian  没有用cdn。请问后两步怎么操作

**Comment by errorlife** [comment]
@mritd  ==、大兄弟，别闹

**Comment by errorlife** [comment]
已经解决，原来是旧版本残留文件
@panzhitian @mritd

**Comment by errorlife** [comment]
感谢两位
