### ISSUE TITLE
reward的图片应该放在哪里?

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#822]
又来打扰了,请问reward的图片应该放在哪里?具体路径是哪里?文档里写得不是很清楚,还望解答 谢谢

**Comment by gardonlee** [comment]
@AlanCheen 随便放，只要指定好路径；或者你直接放在七牛里，粘贴URL即可，我就是这样干的

**Comment by AlanCheen** [comment]
@gardonlee 好的 我去试试

**Comment by AlanCheen** [comment]
谢谢
