### ISSUE TITLE
添加站点统计后移动端footer样式错乱

### ISSUE THREAD

**Issue by gardonlee** [iissnan/hexo-theme-next#823]
@iissnan 
# Expected behavior (预期行为)

在移动端应该像web端一样，footer离content有距离：
![web](https://cloud.githubusercontent.com/assets/15051896/14431447/4b53aabe-0038-11e6-96c1-a8716ebb3f33.png)

或者像没有添加不蒜子统计一样：
![default](https://cloud.githubusercontent.com/assets/15051896/14431473/7095a89a-0038-11e6-9f85-c6772bc713bc.png)
### Actual behavior (实际行为)

添加不蒜子统计后，在移动端，footer好像无padding-top，web端正常：
![footer-bug](https://cloud.githubusercontent.com/assets/15051896/14431525/a340757c-0038-11e6-8eab-6f711614a88d.png)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔ Master **5.0.1**
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by panzhitian** [comment]
如果自定义文字足够长换行的话，还会溢出。感觉一个简单的功能挖了不少坑。

**Comment by panzhitian** [comment]
@iissnan Pisces移动端边距缩小了，其它两个保持了150px不会有问题。
```
.main {
  clearfix();
  +tablet() {
    padding-bottom: 100px;
  }
  +mobile() {
    padding-bottom: 100px;
  }
}
```
看来要弄个接口，不然会动到主体。

**Comment by ivan-nginx** [comment]
@gardonlee dont understand u, write in English if not solved. If solved, close it please.
