### ISSUE TITLE
<MathJax>可以实现行内代码不能实现行间代码！

### ISSUE THREAD

**Issue by veya2ztn** [iissnan/hexo-theme-next#826]
### Expected behavior (预期行为)

下述代码包含了MathJax在行间的使用`$$ $$`和行内的使用`$ $`

``` markdown
### Mathtype in List
+ Transverse Ising model
  $$
  H=-\sum_{i=1}^N (\sigma_{i}^x \sigma_{i+1}^x+g \sigma_{i}^z)
  $$
###Mathtype between lines
$$
H=-\sum_{i=1}^N (\sigma_i^x \sigma_{i+1}^x+g \sigma_i^z)
$$
### Mathtype inline in list
+ the particle has only two state $\left| \uparrow \right\rangle$ and $\left| \downarrow \right\rangle$, which means that $\sigma^z \left| \uparrow \right\rangle =1 \left| \uparrow \right\rangle$
```

预期的行为应当是

![](http://7xseg9.com1.z0.glb.clouddn.com/16-4-13/42807939.jpg)
### Actual behavior (实际行为)

![](http://7xseg9.com1.z0.glb.clouddn.com/16-4-13/47478637.jpg)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

 ✔   Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
  ✔   Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

不仅仅是不能显示的问题，即使是显示代码 ，在很多代码里面都产生了`_`符号的丢失，比如`\sigma_i`变成了`\sigmai`, `c_i`变成 `ci` 我查了一下生成的网页的html代码 发现`c_i` 被标签`<em>i</em> c`所替代 不知道怎么回事

**Comment by veya2ztn** [comment]
系统是windows
我也测试了除了next以外的其他theme
同样发现这个现象，所以这似乎是hexo的通病？

**Comment by tangbotony** [comment]
凡是\sum_{i=1}^n这种句子，都需要写成sum_i^n，不能再加括号{}了，然后在后面说明i的取值范围就行，不要问我怎么知道的，我一个一个测试的，弄了好久，都是泪啊。。。。可以看看我弄的这个：http://forwell.me/2016/04/15/basic-knowledge-about-probability/

**Comment by veya2ztn** [comment]
@tangbotony 额 谢谢。
但是问题似乎不仅仅在于\sum_i 变成了 \sumi
还有在求和内部的 \sigma_i 变成了 \sigmai
以及，我看着你弄的网页  数学代码处理的很好 和我写的有什么不同？

**Comment by tangbotony** [comment]
@veya2ztn  ，建议你写latex的时候，直接在线写，边写边测试，这样的话就能够知道怎么写对，怎么写不对了...Hexo对公式的处理非常的不好，我就是一边写一边看网站的显示的，所以知道怎么写网站能够显示正常，怎么写网站显示不正常。
目前我就知道凡是\sum_{i=1}^n这种句子，都需要写成sum_i^n
同一个latex语句里面不能出现多个等号，否则就无法显示，所以我最后的那个公式分成了三部分显示
![Uploading 5FE3DF15-E459-48A0-BC2D-D2CE1253647D.png…]()

**Comment by iissnan** [comment]
我不太清楚 MathJax，是否跟 MathJax 的配置有关系，NexT 目前使用的是：

```js
MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
        processEscapes: true,
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
      }
    });
```

与 `inlineMath` 的设定是否有关联？
@veya2ztn @tangbotony

**Comment by seisman** [comment]
遇到了同样的问题。根据 https://github.com/hexojs/hexo/issues/524 的说法，是hexo默认的`marked`的问题。目前的解决办法是换用 `hexo-renderer-pandoc` 。

**Comment by veya2ztn** [comment]
@tangbotony @iissnan @seisman @Vinnl @earthday 我找到一个方法，在所有的 _ 前加 \ 就正常了。我想问一下能否用js在markdown渲染之前把所有$$...$$内部的 _ 前面全部加一个 \ ?

**Comment by veya2ztn** [comment]
或者用 {% math %}\begin{aligned}.............\end{aligned}{% endmath %} 来代替$$..........$$

**Comment by veya2ztn** [comment]
@tangbotony @iissnan @seisman @Vinnl @earthday  我想我已经完美解决这个问题了 如我所说，可以用js在markdown渲染前将所有的$$..$$替换成 {% math %}\begin{aligned}.............\end{aligned}{% endmath %} 
方法如下
在你所写的.md文本的正文最后加入下面这段话
`<script>

'use strict';

var restr = /$$([\s\S]*?)$$/g;

document.body.innerHTML = document.body.innerHTML.replace(restr,'{% math %}\begin{aligned}$1\end{aligned}{% endmath %}')

</script>
`
然后你就可以肆意的贴数学公式了，这个方法的好处是，你可以用一些比较优秀的markdown编辑器将文本写好(因为这些编辑器一般支持mathjex不支持KaTeX,但是hexo用的math插件支持后者)，然后原封不动的交给hexo。 谢谢大家一直以来的关注~~

**Comment by WrRan** [comment]
@veya2ztn 要在.md文本的正文最后加的那段代码是什么？我没看到= =

**Comment by littlebeandog** [comment]
@veya2ztn 
按照你说的替换`$$`完美解决.
但是你提供的script并不会生效呀- -求解

**Comment by WrRan** [comment]
我找到一种解决方案，之所以显示不出数学公式，是因为Markdown渲染器与之冲突，使用如下命令可以解决：
```bash
npm uninstall hexo-renderer-marked --save
npm install hexo-renderer-kramed --save
```

该解决方案在[如何处理Hexo和MathJax的兼容问题](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/)中被提出。
希望对你们有所帮助。
👍

**Comment by pfchai** [comment]
应该是下划线`_`解析的时候的问题，有一种解决办法是公式中出现下划线`_`的时候，都用`\_`代替

**Comment by hangsz** [comment]
按照这个链接做就可以了，很简单。
http://blog.csdn.net/emptyset110/article/details/50123231

**Comment by ivan-nginx** [comment]
@veya2ztn dont understand u, write in English if not solved. If solved, close it please.

**Comment by CHENXCHEN** [comment]
hi 我写了个插件用来解决这个问题，基于`markdonw-it`的md解析器
在解析md的时候就直接将其直接渲染成katex的html格式，需要额外引入katex.css即可。。
支持katex的行内以及整行渲染
(hexo-renderer-markdown-it-plus)[https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus]

**Comment by ivan-nginx** [comment]
@CHENXCHEN can u show some live demo with this plugin?

**Comment by CHENXCHEN** [comment]
@ivan-nginx hi, u can see this plugin demo in [hexo-renderer-markdown-it-plus-plugin-demo](https://chchc.me/hexo-article/2017/07/27/hexo-renderer-markdown-it-plus-plugin-demo/)
