### ISSUE TITLE
 NexT.Pisces 侧边栏 “标签”和“分类”无法使用

### ISSUE THREAD

**Issue by royrs** [iissnan/hexo-theme-next#828]
### Expected behavior (预期行为)
在 NexT.Pisces主题中，打开“标签”和“分类”功能，在主页会侧边栏会显示两个选项，点击进入相应页面。

### Actual behavior (实际行为)
在主体设置中打开后，主页面有两个标签显示，但点击显示404错误。

![](http://7xq0c3.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160414161336.jpg)

生成的public文件夹内有**categories**和**tags**两个文件夹

但是 文件夹内结构如下：
![](http://7xq0c3.com1.z0.glb.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160414161359.jpg)

缺少index.html文件。删除主题重装主题依然如此。

### Steps to reproduce the behavior (重现步骤)
如上所说

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release   ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces           ✔

### Other Informations (Like Browser, System, Screenshots)
chrome浏览器，win7系统

**Comment by panzhitian** [comment]
http://theme-next.iissnan.com/theme-settings.html#categories-page

**Comment by royrs** [comment]
感谢楼上，新加页面后，怎么将已有的数据，添加到该页面呢？

**Comment by royrs** [comment]
已经解决了，谢谢楼上
