### ISSUE TITLE
不能通过导航菜单创建相册文章

### ISSUE THREAD

**Issue by happyxiaofan** [iissnan/hexo-theme-next#831]
### Expected behavior (预期行为)

可以通过导航菜单创建相册文章
### Actual behavior (实际行为)

不能通过导航菜单直接创建相册文章
### Steps to reproduce the behavior (重现步骤)
1. 在scaffolds下创建photo.md：

```
layout: { { layout } }
title: { { title } }
date: { { date } }
tags: 
photos: 
- 

---
```
1. 通过hexo new page books创建新的导航菜单books，并修改index.md文件，发现即使使用相册的语法设置Front-matter，打开仍然不能创建相册文章
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master

NexT Scheme:
- Mist

**Comment by yusmile** [comment]
你找到解决方案了吗？

**Comment by ivan-nginx** [comment]
@happyxiaofan dont understand u, write in English if not solved. If solved, close it please.
