### ISSUE TITLE
为什么首页不是摘要信息呢？

### ISSUE THREAD

**Issue by jwangkun** [iissnan/hexo-theme-next#834]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Haocen** [comment]
你没有提供任何有效的信息。

**Comment by iissnan** [comment]
http://theme-next.iissnan.com/faqs.html#read-more
