### ISSUE TITLE
categories或者tags中存在中文时，本地没有问题，deploy以后无法build,所有文件的编码格式为UTF-8

### ISSUE THREAD

**Issue by YJunKang** [iissnan/hexo-theme-next#837]
windows 10 系统下
使用next主题，在本地调试时，没有任何问题
使用hexo d 指令发布到github后，由于categories和tag中含有中文
导致无法部署，请问如何解决

**Comment by tkvern** [comment]
Change your system coding format to UFT-8

**Comment by YJunKang** [comment]
我的所有文件格式都是utf-8的，还是出现问题

**Comment by geekrainy** [comment]
不是 next 主题的问题。同样有中文。我没有这个现象。

**Comment by geekrainy** [comment]
应该是你使用的编辑器编辑 MD 文件的时候不是以UTF-8保存所致。

**Comment by YJunKang** [comment]
文件编码的确为utf8，我仔细看了一下，问题是当tags或者categories中包含中文时，在public相对应的目录下生成的文件路径会出现乱码，不是内容中出现乱码

**Comment by mmrxia** [comment]
楼主可以新建md文件，设置编码问utf-8，然后将之前的内容粘贴过来试试看。

**Comment by iissnan** [comment]
在 Hexo 仓库看看有没有类似的 issue.

**Comment by ivan-nginx** [comment]
@YJunKang dont understand u, write in English if not solved. If solved, close it please.

**Comment by rupigcute** [comment]
剛剛自己找到一個解決方案也寫在這裡好了，也許以後幫到別人也說不定呢。
如果你發現 hexo s 沒有問題，而電腦生成的tag/categories文件夾和文件也沒有出現亂碼，只是上傳時候出現了Write EIO error, 也就是無法顯示你的中文Tag/categories，你可以下載Git for Windows.
然後在你的Hexo目錄裡面點擊右鍵選擇Git bash here, 之後再cmd裡面輸入，hexo clean, hexo d, 就可以成功上傳具有中文的Tags/Categories了。
