### ISSUE TITLE
设置始终显示侧栏后，进入没有目录的文章后侧栏不展开

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#838]
### Expected behavior (预期行为)

进入每个页面后，侧栏都会自动划出
### Actual behavior (实际行为)

只有在各个主页面及使用了Markdown的标题（即在侧栏会显示为自动生成的目录）的文章中会出现侧栏，普通没有小标题（目录）的文章页侧栏不弹出。
### Steps to reproduce the behavior (重现步骤)

侧栏设置always后随意书写不包含标题的文章发布后即可发现。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
- ✔Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  ✔Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

例如
http://sxshax.xyz/2016/04/12/Corner-Tree/
没有小标题不会显示侧栏
而
http://sxshax.xyz/2016/04/04/hello-world/
有小标题会显示侧栏。

**Comment by S-X-ShaX** [comment]
这个问题没有解决方案吗？

**Comment by ivan-nginx** [comment]
@AlynxZhou dont understand u, write in English if not solved. If solved, close it please.

**Comment by AlynxZhou** [comment]
@ivan-nginx Thank you, this has been fixed already, I'll close it.
