### ISSUE TITLE
如何使用busuanzi?

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#839]
请问busuanzi 的统计怎么加? 并没有看到详细的指导~
而且貌似busuanzi现在注册不了呢!

**Comment by panzhitian** [comment]
Read the docs carefully.
http://theme-next.iissnan.com/third-party-services.html#analytics-busuanzi

**Comment by AlanCheen** [comment]
@panzhitian 
谢谢回复,我配置如下,但是没有看到什么效果~

busuanzi_count:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: 本站访客数
  site_uv_footer: 人次
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: 本站总访问量
  site_pv_footer: 次
  # custom pv span for one page only
  page_pv: true
  page_pv_header: 本文总阅读量
  page_pv_footer: 次

**Comment by XavierXia** [comment]
@AlanCheen ,我也遇到了这个问题
@iissnan 求解，多谢。

**Comment by panzhitian** [comment]
- 更新源码
- hexo clean清除旧文件
- 检查html和css是否有相关资源
- 检查浏览器是否拦截js等
