### ISSUE TITLE
Categories Issues

### ISSUE THREAD

**Issue by jacinzhang** [iissnan/hexo-theme-next#840]
分类页面的分类按钮没有左对齐，似乎也没有右对齐，请问这个能调成左对齐么？？？
![ddd](https://cloud.githubusercontent.com/assets/9859965/14748477/7fd33a86-08ec-11e6-817e-f6f325742c4d.png)

**Comment by iissnan** [comment]
缩进代表的是子分类项

**Comment by wencaistorm** [comment]
![default](https://cloud.githubusercontent.com/assets/16088038/16120819/7e64020a-3413-11e6-9967-401fe161158c.png)
1. 我不能直接在硬盘上删除文章吗？
2. 有一个分类的文章我直接删了，这个分类个数就比实际的多1，怎么办？

**Comment by iissnan** [comment]
Run `hexo clean`.
