### ISSUE TITLE
页面完全空白,什么都不显示

### ISSUE THREAD

**Issue by otherfish** [iissnan/hexo-theme-next#842]
### Expected behavior (预期行为)

调试social links的邮件链接的font-awesome的icons图标显示(实际只有一个原点和文字),于是我手动更新了5.0.1的源码
### Actual behavior (实际行为)

在没有看到调试效果前网页完全空白不显示任何内容
![qq 20160423185524](https://cloud.githubusercontent.com/assets/12808134/14760972/05566046-0985-11e6-83c9-bda3a9ca1c82.jpg)
### Steps to reproduce the behavior (重现步骤)
1. 下载5.0.1.zip源码,解压缩到themes文件夹下面
2. 先备份_config.yml文件
3. 重命名为next
4. 运行`hexo clean` 与 `hexo g` 命令
5. 上传public下的文件到服务器上
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  √Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  √  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

控制台报错:

![qq 20160423190340](https://cloud.githubusercontent.com/assets/12808134/14761006/3503489e-0986-11e6-9d4c-4dce8360af37.jpg)

**Comment by Haocen** [comment]
修改主题配置文件 # Script Vendors. 这个部分的配置。这是新增的 CDN 功能。

**Comment by iissnan** [comment]
@otherfish 把主题下的的 _config.yml 贴出来看看。

@Haocen Script Vendors 没有配置，会 fallback 到本地的版本，不会出现空的情况。

**Comment by otherfish** [comment]
@issnan
```
# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )
menu:
  home: /
  #categories: /categories
  about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html
  guestbook: /guestbook
 
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Hexo,next"

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Icon fonts
# Place your font into next/source/fonts, specify directory-name and font-name here
# Avialable: default | linecons | fifty-shades | feather
#icon_font: default
icon_font: fifty-shades
#icon_font: feather
#icon_font: linecons

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night


# MathJax Support
mathjax:


# Schemes
scheme: Mist


# Sidebar, available value:
#  - post    expand on posts automatically. Default.
#  - always  expand for all pages automatically
#  - hide    expand only when click on the sidebar toggle icon.
#sidebar: post
#sidebar: always
sidebar: hide


# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true


# Automatically add list number to toc.
toc_list_number: true

# Automatically Excerpt
auto_excerpt:
  enable: false
  length: 150

# Use Lato font
# Note: this option is avialable only when the language is not `zh-Hans`
use_font_lato: true

# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
# avatar
avatar: /images/mei.jpg
## DO NOT EDIT THE FOLLOWING SETTINGS
## UNLESS YOU KNOW WHAT YOU ARE DOING

# Use velocity to animate everything.
use_motion: true

# Fancybox
fancybox: true

# Static files
vendors: vendors
css: css
js: js
images: images

# Theme version
version: 0.4.5.1


# Social links
social:
  email: mailto:webmaster.xxx.net

social_icons:
  enable: true
  email: envelope
```

**Comment by zerosoul** [comment]
我也遇到了同样的情况，一旦开启use_motion，页面就一片空白，但是看源码内容都在的。我估计是哪儿opacity 设置为0 了，然后没变过来。

**Comment by ZhaiHaiSheng** [comment]
我遇到同样的问题, 也是空白..后来发现开始是用vpn下载的, 可能文件不完整.
然后同样的步骤再做一遍, 正常了... 而且, 命令行中体现的文件数远远大于第一次下载的.
结论,,,得益于我们伟大的GFW...如果你发现出错了, 请重下一遍所需文档...

**Comment by monster-gump** [comment]
请问解决了吗 @otherfish 我也突然出现了这个问题
@iissnan @ZhaiHaiSheng 我是国外的网络，理论上不该有这个原因的
前两天都还可以正常使用，今天 update 了一个新文章就突然跪了，reset 回之前的版本也不 work

**Comment by patricorgi** [comment]
@monster-gump 今天早上我也遇到这个问题。到现在还没解决，本底 hexo s 命令可以看到正常的页面，部署到 GitHub Pages 上就是空白，但是页面中的链接却可以点击（鼠标指到空白处会变成小手图标说明可以点击）。难道是 GitHub 那边的问题？

**Comment by ydeng11** [comment]
我也遇到了相同的问题，请问有大神解决了吗？

**Comment by kk649287100** [comment]
看来我不是第一个

**Comment by patricorgi** [comment]
目前的解决方案就像前几楼说的，在主题配置文件里把 use_motion 那一项设置为 false，站点可以正常限时了，但是有些功能还是不正常，比如说侧边栏无法呼出。

**Comment by johanzhu** [comment]
看来我也不是第一个。。。早上更新文章突然后全部空白了。。。

**Comment by caiyue1993** [comment]
今天早上更新文章时我也遇到了同样的问题

**Comment by jzy476731162** [comment]
我是中午更了一下.然后也白屏了.沃日啊搞事情!设置use_motion也无效

**Comment by iissnan** [comment]
今天碰到的应该是 GitHub Pages 的调整导致的。

**Comment by skyJinc** [comment]
有解决方案吗？

**Comment by iissnan** [comment]
今天碰到的可以参考 #1214 以及 [解决方法](https://github.com/iissnan/hexo-theme-next/issues/1214#issuecomment-258093158)

**Comment by xmsx** [comment]
同求

**Comment by guoyiang** [comment]
@iissnan 能否发布一个新的版本稳定版本？我通过增加.nojekyll文件的办法解决了，之后才发现改目录的方案。

**Comment by newleidy** [comment]
+1 遇到了 嘤嘤嘤~

**Comment by stegosauruscui** [comment]
在本地也是同样的问题

**Comment by yanlee26** [comment]
我也遇到同样的问题，掉坑里了，求教大神解救

**Comment by yanlee26** [comment]
我也遇到同样的问题，掉坑里了，求教大神解救

**Comment by JasonSi** [comment]
找到同盟了。。我也。。

**Comment by ivan-nginx** [comment]
@otherfish dont understand u, write in English if not solved. If solved, close it please.
