### ISSUE TITLE
设置menu在新页面打开链接

### ISSUE THREAD

**Issue by pod4g** [iissnan/hexo-theme-next#846]
我在menu上添加了一个新的菜单项，叫pod4g，当点击时，跳转到我的github地址。请问如何在新窗口中跳转到该地址？也就是说指定a标签为target="_blank"

![next-menu-set](http://7xt9n8.com2.z0.glb.clouddn.com/nextmenu.png)

**Comment by mrfeiii** [comment]
同问

**Comment by Coderakang** [comment]
在你的next的配置文件的menu里
menu:
  pod4g:  /+你的github地址

**Comment by wghglory** [comment]
+1

**Comment by yzgqy** [comment]
+1

**Comment by ivan-nginx** [comment]
@pod4g dont understand u, write in English if not solved. If solved, close it please.

**Comment by wghglory** [comment]
He wants to add a new item called "pod4g" in the navigation bar. And when clicking that item, the browser should open a new tab for it instead of loading the page directly. It's like using `<a href="#" target="_blank">new item</a>`

**Comment by ivan-nginx** [comment]
@wghglory alright, thanks for translate! This is already backloged for Next feature, but:
1. For now may use `extlink` tag wich may open links in new winows, but it's work with BASE64 encrypt/decrypt format.
2. Also may use external Hexo plugins like [hexo-autonofollow](https://github.com/liuzc/hexo-autonofollow).

**Comment by ivan-nginx** [comment]
Added `extlinks` on sidebar author links in [NexT v6.0.4 release](https://github.com/theme-next/hexo-theme-next/releases/tag/v6.0.4) in [this pull](https://github.com/theme-next/hexo-theme-next/pull/99).

Already worked under standart links in sidebar author links with `target="_blank"` & `noopener` attributes. Need to refactor some things.

**Comment by yannxia** [comment]
@ivan-nginx  it's cool, thanks for your help..

for example
```
menu:
  home: / || home
  about: /about/ || user
  #categories: /categories/ || th
  archives: /archives/ || archive
  wiki: http://wiki.yannxia.top/ || wikipedia-w
```
most of time, we want to open a new tab for `http://wiki.yannxia.top/` , I hope this could help you

**Comment by ivan-nginx** [comment]
I understand what needed. Need more time to refactor some API.

**Comment by stevenjoezhang** [comment]
It has been fixed in https://github.com/theme-next/hexo-theme-next/pull/476
Try NexT v6.x
