### ISSUE TITLE
减少http请求的一个思路

### ISSUE THREAD

**Issue by panzhitian** [iissnan/hexo-theme-next#848]
##### Actual behavior (实际行为)
因为作者的模块化开发，网站主页就有大概18个http请求，要求其作出修改并不现实，只能是自身来定制。优化方向有几个：
- 合并成单一资源文件
- JS，css等外链转成inline输出
- blob

##### Expected behavior (预期行为)
我的一个想法是使用 [nginx-http-concat](https://github.com/alibaba/nginx-http-concat) 模块来合并必要文件的请求：
```
{% if theme.concat %}
  {%set vendors_combo = url_for(theme.vendors._internal) + '/??' + js_vendors|join(',') %}
  <script type="text/javascript" src="{{ vendors_combo }}"></script>
{% else %}
  {% for name, internal in js_vendors %}
    {% set internal_script = url_for(theme.vendors._internal) + '/' + internal %}
    <script type="text/javascript" src="{{ theme.vendors[name] | default(internal_script) }}"></script>
  {% endfor %}
{% endif %}
```
因为局限性（需要服务器支持）和缺点（文件依赖），仅作讨论。
详细（不完整）见： https://github.com/panzhitian/hexo-theme-next/commit/8ff0cf3dd6ce4f3ff234206e38f81d49480c1bac

**Comment by Haocen** [comment]
随便选一个 CDN 服务不好吗？况且随着 HTTP 2 来临这应该已经不构成问题了。

**Comment by panzhitian** [comment]
@Haocen 首先要备案以及坑钱般的主机，有多少人会用到国内的cdn。好了，算你用上了，没有足够的访问量基本上就是回源，再说哪个cdn有http2了？都用了支持的浏览器了？那就不用了，用cloudflare，面向国内访客的话，不被墙已经很好了，谈什么用户体验，那是自娱自乐，在本地建就可以了。根本是在于很多用户是追求免费&“装比”，一般都是在github部署，或许用的是国内coding，基本上处处受阻好吧。
