### ISSUE TITLE
5.0.1自定义字体不生效

### ISSUE THREAD

**Issue by 80imike** [iissnan/hexo-theme-next#850]
### Expected behavior (预期行为)

自定义字体不生效
http://theme-next.iissnan.com/faqs.html#custom-font
### Actual behavior (实际行为)

5.0.1 版本按以下方法自定义字体不生效，5.0.0版本是可以的
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
- Latest Release   ✔ 
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist ✔
-  Pisces

**Comment by 80imike** [comment]
我看到5.0.1配置文件有变化，应该是在

global:
    # external: true will load this font family from host.
    external: true
    family: Lato

定义吧

但有个问题如果要像5.0这样
 $font-family-headings = Georgia, sans, 'PT Serif', 'STZhongsong', '华文中宋', 'Microsoft Yahei', serif, Verdana, sans-serif

定义多个字体，该如何写呢？

**Comment by iissnan** [comment]
我试了下这种方式还是有效的。

修改 `source/css/_variables/custom.styl` 文件，不是 `source/css/_custom/custom.styl`

**Comment by 80imike** [comment]
@iissnan 我是修改的source/css/_variables/custom.styl文件 不过不生效
先用新版方法改了 谢谢！

**Comment by gobraves** [comment]
我也是修改的source/css/_variables/custom.styl文件,但不生效

**Comment by MyLeoLan** [comment]
我的也不生效，只有logo项是正常的，其他项修改都无变化，host是默认的。具体原因不知道？

**Comment by suarezzz** [comment]
@MyLeoLan 
我的是只改了配置文件就可以了
不过也不会立即就生效，可能需要清一下缓存什么的

**Comment by MyLeoLan** [comment]
@suarezzz 感谢回答，我找到原因啦，是因为引用的字体在www.google.com/fonts里找不到，或者是付费的字体，也不用在source/css/_variables/custom.styl里添加，直接改主题配置文件就行。

**Comment by iissnan** [comment]
Closed as outdated. Reopen it if you still have issue on this.
