### ISSUE TITLE
标签和分类页面无标签云和分类列表

### ISSUE THREAD

**Issue by lovejoy** [iissnan/hexo-theme-next#852]
### Expected behavior (预期行为)
tags/ 显示标签云

### Actual behavior (实际行为)
tags路径不显示标签云 但是tags/xxx 却是有显示的

### Steps to reproduce the behavior (重现步骤)
代码在https://github.com/lovejoy/lovejoy.github.com 的hexo分支

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔ Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
 ✔  All schemes
  -  Muse
  -  Mist
  ✔ Pisces

### Other Informations (Like Browser, System, Screenshots)
nvm 安装的node环境 4.3.2 版本
hexo 3.2.0
hexo-cli 1.0.1
hexo g无报错
![image](https://cloud.githubusercontent.com/assets/469764/14857375/a3e2cb04-0cce-11e6-9bd9-518c3ef8ff4e.png)

![image](https://cloud.githubusercontent.com/assets/469764/14857365/9da6790c-0cce-11e6-874c-19753dbcbb1c.png)

**Comment by lovejoy** [comment]
求问这个可以怎么查下原因

**Comment by myloften** [comment]
@lovejoy 我也是这个问题，请问你解决了吗？

**Comment by lovejoy** [comment]
@myloften 并木有解决 求 @iissnan 解答啊

**Comment by Jim-Zenn** [comment]
我也有这个问题

**Comment by Jim-Zenn** [comment]
http://theme-next.iissnan.com/theme-settings.html

**Comment by madordie** [comment]
总有些看了教程也没发现问题的，比如我。。特作备注，给那些像我一样没一眼看出问题的同学。。

```
title: 标签
date: 2014-12-22 12:39:04
# 此处`type`为新加的，且必须加
type: "categories"
---
```

**Comment by giswt** [comment]
现在这个问题解决了吗？我的总标签不能显示，但分标签的index.html是正常的
