### ISSUE TITLE
建议调整动画顺序

### ISSUE THREAD

**Issue by lanthree** [iissnan/hexo-theme-next#853]
使用 NexT.Pisces
为什么载入页面的时候，先放边栏的动画，再放载入主体文章的动画？
不应该优先主体文章吗？

**Comment by mmrxia** [comment]
楼主可以根据个人使用习惯和爱好做调整啊。

**Comment by ivan-nginx** [comment]
@lanthree dont understand u, write in English if not solved. If solved, close it please.
