### ISSUE TITLE
为什么用了hero clear 之后主页 404

### ISSUE THREAD

**Issue by zachary05** [iissnan/hexo-theme-next#854]
为什么用了hero clear 之后主页 404

**Comment by mmrxia** [comment]
你的意思是使用了 hexo clean 命令吧？
clean命令会清楚部署和public目录，本地4000端口应用因缺少文件打开自然会出现404的情况。

**Comment by ivan-nginx** [comment]
@zachary05 dont understand u, write in English if not solved. If solved, close it please.
