### ISSUE TITLE
Set ACL for new LeanCloud Counter object

### ISSUE THREAD

**Issue by billjh** [iissnan/hexo-theme-next#858]
Please refer to this commit
https://github.com/billjh/hexo-theme-next/commit/cebd027a121c3387c8bd4aea14aedf9bd934663a

解释：
如果使用 LeanCloud Counter来为文章计数，当写好新的文章的时候，第一次访问会创造新的 count object。但是默认的 ACL 会阻止 Public 写入，导致读取写入都有问题。应该要手动调整权限。

Ref:
https://leancloud.cn/docs/acl_guide-js.html#ACL_权限管理

**Comment by iissnan** [comment]
看了下文档，似乎目前的 Counter 并未设置 ACL 属性，只要有 AppId 和 AppKey，所有人都可以读写。

Ref:
https://leancloud.cn/docs/acl_quick_start-js.html

**Comment by billjh** [comment]
文档上确实是这么说的呢。默认应该是可以读写。

但是前两天我新开博客的时候发现文章阅读计数不能显示，就上LeanCloud查了下数据，看到给我新建的object ACL全部是
```
ACL: {"*":{"read":true,"write":false}}
```
我就自己根据ACL的[API Doc](https://leancloud.cn/api-docs/javascript/symbols/AV.ACL.html)手动改权限设置，就可以正确显示了。

**Comment by iissnan** [comment]
加 ACL 的配置是否会引入其他的问题？ 若没有的话，能否将你的修改发 pr 给我，谢谢
