### ISSUE TITLE
代码块的附加网址链接在暗色主题下不清晰

### ISSUE THREAD

**Issue by DoraJDJ** [iissnan/hexo-theme-next#859]
### Expected behavior (预期行为)
代码块的附加网址在暗色主题下文字颜色为亮色

### Actual behavior (实际行为)
实际显示为暗色，跟文章中的链接差不多，在暗色背景下完全看不清

### Steps to reproduce the behavior (重现步骤)
在文章内插入带附加网址的代码块，例如下面截图所使用的代码：
```
{% codeblock 使用request库解决GZip压缩过的页面的解决方案 lang:javascript https://cnodejs.org/topic/545de1e1a68535a174fe51b5#545dec00a68535a174fe51c3 参考自：CNode %}
request({
    url: '<Url>',
    headers: {
        'User-Agent': '<User agent>',
        'Accept-Encoding': 'gzip, deflate' // <==
    },
    gzip: true // <==
}, function(err, res, body) {
    // Handling response...
});
{% endcodeblock %}
```
然后将代码高亮主题切换为`night eighties`

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

✔  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
✔  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
代码高亮主题：
```
highlight_theme: night eighties
```

截图：（右上角的“参考自：CNode”很难看清）
![](http://img.cirno.biz/di/VY40/选区_032.png)

**Comment by iissnan** [comment]
Fixed
