### ISSUE TITLE
如何在文章之间加入分割线或其他的标志

### ISSUE THREAD

**Issue by eyesfrog** [iissnan/hexo-theme-next#863]
### Expected behavior (预期行为)

想要文章之间有较明显的分隔
### Actual behavior (实际行为)

文章之间的界限不太明显
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by jcx70100** [comment]
这个问题有方案吗？我也觉得文章分割的那个短线看上去不舒服，不知道怎么修改

**Comment by ivan-nginx** [comment]
@eyesfrog dont understand u, write in English if not solved. If solved, close it please.

**Comment by AlynxZhou** [comment]
修改`themes/next/source/css/_common/components/post/post-eof.styl`这个文件，找到里面这么一段：

```
.posts-expand {
  .post-eof {
    display: block;
    margin: $post-eof-margin-top auto $post-eof-margin-bottom;
    width: 8%;
    height: 1px;
    background: $grey-light;
    text-align: center;
  }
}
```

然后把那个`width: 8%;`改成你想要的宽度百分比就好啦，或者写在custom.styl覆盖。如果`hexo g`没效果就先`hexo clean`一下。

别问喵怎么发现的……chrome审查元素找到那个是一个div class="post-eof"然后就去翻css，一个`ag -i .post-eof themes/next/source/css/`就出来啦……别的也可以这样找吧。

@ivan-nginx I told them way to custom, you can close this issue.

**Comment by ivan-nginx** [comment]
@AlynxZhou thank's!
