### ISSUE TITLE
插入外链音乐时音乐框的大小显示不正常

### ISSUE THREAD

**Issue by ghost** [iissnan/hexo-theme-next#865]
### Expected behavior (预期行为)

音乐框只占行宽的三分之一左右，行间距紧凑。
### Actual behavior (实际行为)

音乐框占满一整行，并且行间距很大。
### Steps to reproduce the behavior (重现步骤)

在旧版本(0.X)中没有问题，在最新版本中有问题。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  [x]  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  [x]  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

Chrome, Win10
![default](https://cloud.githubusercontent.com/assets/18607292/15019002/a6922e28-124e-11e6-8911-464a90903d3b.PNG)

**Comment by iissnan** [comment]
Fixed.

**Comment by Edenharder** [comment]
I update to the newest version but the bug is still there.

**Comment by iissnan** [comment]
我看 oppontion 现在的博客里显示是正常的

**Comment by Edenharder** [comment]
@iissnan 你是看的test那个博文吧？那里他是用的embed，[关于这篇](http://oppontion.github.io/about/)是用的iframe，我这里看宽度仍是不正常的。

**Comment by oppontion** [comment]
@iissnan 确实还有一点问题，用iframe的时候虽然行间距正常了，但是长度不对，无法自行修改，总是占满一整行。

**Comment by iissnan** [comment]
宽度不做限制

**Comment by Edenharder** [comment]
@iissnan  我說的寬度應該是 @oppontion 說的長度，總是佔滿一行，無法自己修改。

**Comment by Edenharder** [comment]
我用了一個比較極端的解決方案，即在`source/js/src/utils.js`中刪除對`'music.163.com'`的支持。這需要刪去`68,  109-118`行。這樣就能自己調控 iframe 的 height 和 width 了。

**Comment by szhgoldeneye** [comment]
@iissnan 正常引用后音乐框的宽度在pc网页端大了很多，手机端正常，尝试修改引用iframe的height为0后，pc网页端显示大小就正常了，但手机端显示就出问题

**Comment by leofee** [comment]
我也发现这个问题了，我的解决方案是给播放器加一个div ,然后css 控制其宽高～

**Comment by szhgoldeneye** [comment]
@leofee 你更新一下最新版本 好像解决了这个问题

**Comment by weqeo** [comment]
@szhgoldeneye 并没有啊，我现在行宽还是不能控制的。。。

**Comment by otherfish** [comment]
the same issue, the new version, 
`0.5.0.1`
![snipaste20161028_212350](https://cloud.githubusercontent.com/assets/12808134/19807965/16a09b6e-9d55-11e6-8d43-05df5f739c61.png)

the old version,
`0.4.5.1`
![snipaste20161028_212654](https://cloud.githubusercontent.com/assets/12808134/19808045/76c7c54e-9d55-11e6-9a4d-f8d819344c5c.png)

**Comment by ivan-nginx** [comment]
@iissnan dont understand u, write in English if not solved. If solved, close it please.
