### ISSUE TITLE
为什么在首页的文章markdowm 格式显示不正确？？

### ISSUE THREAD

**Issue by ganjmeng** [iissnan/hexo-theme-next#868]
### Expected behavior (预期行为)

按正常的markdowm效果显示
### Actual behavior (实际行为)

显示不正确

[我的地址](http://ganmmeng.cn)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master

NexT Scheme:
-  All schemes

**Comment by iissnan** [comment]
使用 `<!-- more -->` 替代 `auto_excerpt`

**Comment by ganjmeng** [comment]
解决了，多谢！

**Comment by ivan-nginx** [comment]
@ganjmeng dont understand u, write in English if not solved. If solved, close it please. Thank's!
