### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by ifhw** [iissnan/hexo-theme-next#872]
代码块中包含如下语句，就无法高亮了
使用```cpp ```高亮

`Point p1(1,1), p2(4,5);`

在这里是可以的:

``` cpp
    Point p1(1,1), p2(4,5);
```

下面是对比图：
![高亮](http://7xjpcz.com1.z0.glb.clouddn.com/Image_highlight.png)
![不高亮](http://7xjpcz.com1.z0.glb.clouddn.com/Image_nohighlight.png)

**Comment by iissnan** [comment]
应该与这个问题类似 #644

**Comment by ifhw** [comment]
也看到针对c++语言，还有别的高亮问题，有说是highlight.js的问题。说9.2版就修复了。https://github.com/isagalaev/highlight.js

我想问这个怎么更新？有用吗？

**Comment by iissnan** [comment]
站点更目录执行 `npm update` 一下，看能否拿到新的 highlight.js (9.3.0)，然后再试试。

**Comment by ifhw** [comment]
看了一下版本是 highlight.js@9.3.0。问题依然存在。

**Comment by zlc1994** [comment]
可以把hexo自带的hightlight关掉，然后改用google-code-prettify来实现高亮，具体可以看这片文章https://liuzhichao.com/2016/hexo-use-prettify-to-highlight-code.html，修改YourNextThemeFolder/layout/_layout.swig这个文件就行了。

**Comment by ivan-nginx** [comment]
@ifhw dont understand u, write in English if not solved. If solved, close it please. Thank's!
