### ISSUE TITLE
当 标题是 jquery时会出现问题

### ISSUE THREAD

**Issue by maiff** [iissnan/hexo-theme-next#873]
### Expected behavior (预期行为)

当标题是jquery时会自动创建一个jquery的id，导致页面的透明度一直是0。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@maiff dont understand u, write in English if not solved. If solved, close it please. Thank's!
