### ISSUE TITLE
菜单首字母大写

### ISSUE THREAD

**Issue by atjason** [iissnan/hexo-theme-next#874]
### Expected behavior (预期行为)

菜单字符串应该和“/themes/next/languages/zh-Hans.yml”中定义的一致。
### Actual behavior (实际行为)

首字母变为大写，如 iPhone > IPhone
### Steps to reproduce the behavior (重现步骤)
- 设置 hexo 语言和 zh-hans
- 创建名为 iPhone 的 Page
- 在 -config.xml 的 menu: 中增加 iPhone: /iPhone.html
- 在 /themes/next/languages/zh-Hans.yml 中增加 iPhone: iPhone 记录
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 3.2.0

✔  -  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse

✔  -  Mist
-  Pisces

**Comment by atjason** [comment]
另外，全局配置中大小写相关的配置如下：

# Writing
titlecase: false # Transform title into titlecase
filename_case: 0

**Comment by DaZuo** [comment]
The same issue. +1. @iissnan

**Comment by iissnan** [comment]
已修复，谢谢反馈

**Comment by ivan-nginx** [comment]
@atjason dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by atjason** [comment]
@ivan-nginx If I use 'iPhone' as top menu's title, it will be 'IPhone', i.e., 'i' > 'I' for first letter.

This issue was reported with NexT Version: 3.2.0, not sure latest version fixed or not.

**Comment by ivan-nginx** [comment]
@atjason can u plase check last version and if it solved, close issue?

**Comment by atjason** [comment]
@ivan-nginx Sorry, I changed a lot with that version, hard to update in short time.

**Comment by ivan-nginx** [comment]
So. i think what issue was solved and close it. U can always open new issue anyway.

**Comment by ivan-nginx** [comment]
#1904.
