### ISSUE TITLE
关于多说分享

### ISSUE THREAD

**Issue by jm1231** [iissnan/hexo-theme-next#875]
点了多说分享到微信的图标后弹出一个二维码，然后手机扫码之后一直会弹出来说 被多人举报是色轻内容 ==，这是什么情况？？明明刚写好的文章。

**Comment by Haocen** [comment]
@jm1231 这个应该去找多说反馈吧。

**Comment by Zhangjingwang1993** [comment]
我的分享也出现了类似的问题 , 你解决了吗 囧

**Comment by jm1231** [comment]
@Zhangjingwang1993 没有呢

**Comment by iocharset** [comment]
骚年们啊，这个和主题无关，把你们的站点配置文件中的url改成自己的域名就行了，不要用默认yoursite.com。
