### ISSUE TITLE
disqus 不能load的一种可能分析和解决方案

### ISSUE THREAD

**Issue by forwardkth** [iissnan/hexo-theme-next#876]
更新主题以后，disqus在新建的post上无法load，但是以前的post上load正常

网上的一个文章 http://webcache.googleusercontent.com/search?q=cache:UnY-n6LaBqgJ:www.xlgps.com/article/171989.html+&cd=6&hl=zh-CN&ct=clnk&gl=se
 给了我启发。

于是我更改了主题 layout script
disqus.swig 中的disqus_url 为自己的域名，于是问题解决了。

我觉得这可能是个潜在的bug

//////////////////////////////////////////////////////////////////////////////
{% if not (theme.duoshuo and theme.duoshuo.shortname) and not theme.duoshuo_shortname %}

  {% if theme.disqus_shortname %}

    <script type="text/javascript">
      var disqus_shortname = '{{theme.disqus_shortname}}';
      var disqus_identifier = '{{ page.path }}';
      var disqus_title = '{{ page.title }}';
      var disqus_url = 'http://forwardkth.github.io';  #这里修改为自己的域名

      function run_disqus_script(disqus_script){
        var dsq = document.createElement('script');
        dsq.type = 'text/javascript';
        dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/' + disqus_script;
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      }

      run_disqus_script('count.js');
      {% if page.comments %}
        run_disqus_script('embed.js');
      {% endif %}
    </script>
  {% endif %}

{% endif %}

**Comment by iissnan** [comment]
你的站点配置文件里的 `url` 字段是填写什么？

**Comment by forwardkth** [comment]
站点配置文件的url我是留空的，因为不确定应该填什么。升级主题以前那里也是留空的，但是disqus没有出现问题。所以现在这个情况比较不解 : )

**Comment by iissnan** [comment]
我会把 `disqus_url` 这个变量去掉，有 `disqus_identifier` 就可以。至于页面的链接，Disqus 会自动取 `window.location.href`，Hexo 生成的都是静态的页面，这个值也是正确的。

**Comment by iissnan** [comment]
噢，对了，你的问题可能是应该是 `url` 未配置导致的。`url` 未配置导致 `page.permalink` 拿到的值不正确，从而影响了 Disqus 的加载。

> Please note that an absolute URL is required for the this.page.url variable. Using a relative URL for this variable may prevent Disqus from loading successfully on the page.

**Comment by forwardkth** [comment]
好 谢谢答疑 ：）

**Comment by forwardkth** [comment]
Hi iissnan,请问站点配置文件url应该设置成什么呢？  我留空的时候是 url /，如果填上自己的域名，disqus又会出现一个问题，就是在一篇post上的评论也会出现在其他的post上

**Comment by forwardkth** [comment]
加上站点配置文件 url 域名以后就正常了

**Comment by Mr-LiuDC** [comment]
我用的最新版 NexT.Pisces v5.1.3，正确配置了Disqus，也确定文章前部分的format正确，为什么有的文章可以正常加载显示出Disqus，而有些文章不能加载出Disqus。

**Comment by jeremykid** [comment]
我也是有一样的问题， 前面几篇文章的disqus 可以显示， 后面的文章不能加载disqus

**Comment by liian2018** [comment]
url配置ip可以吗
