### ISSUE TITLE
主题在hexo执行命令时出现tags与显示的计数存在差异问题

### ISSUE THREAD

**Issue by huangxok** [iissnan/hexo-theme-next#878]
### Expected behavior (预期行为)

![1](https://cloud.githubusercontent.com/assets/7628834/15177227/99c17b4c-17a1-11e6-8a14-25b07a18602c.png)
### Actual behavior (实际行为)

![2](https://cloud.githubusercontent.com/assets/7628834/15177302/deef11ac-17a1-11e6-95d3-739c1ed0a1ff.png)
### Steps to reproduce the behavior (重现步骤)

初始化时将hellow-word.md删除后
hexo new "test"
文件在source/_post中
然后修改 test.md的头部信息
如 ---
     title:  xxxxx
     date: xxxxxx
     tags:
        - xxx
        - yyy
     categories: 
        - zzz
    ---
然后执行hexo g
启动本地服务 hexo s ,默认url  ---- localhost:4000
第一次不会存在问题
接着进行第二次修改头部信息
如 ---
     title:  xxxxx
     date: xxxxxx
     tags:
        - nnnn
        - mmm
     categories: 
        - kk
    ---
接着执行
hexo clean
hexo g
再次 查看本地服务地址
会在之前的tags的计数上进行增加 比如第一次的tags 为2个 categories为1个
修改后就变为 tags为4 categories为2
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master  (master分支)
-  Latest Release  
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces (出现bug的模式)
### Other Informations (Like Browser, System, Screenshots)

chorme-version：50  
system： win10

**Comment by iissnan** [comment]
第二次修改之前停止本地 Server，修改后 `hexo clean` 重新启动试试

**Comment by huangxok** [comment]
OK~，今天开机又试了一遍，工作正常，这个产生的原因什么？

**Comment by huahuayu** [comment]
我也遇到这个了，修改文章标签数量后tags页面计数不对，包括categories也是一样。按@iissnan 给的方法操作过后就正确了

**Comment by ivan-nginx** [comment]
@huangxok dont understand u, write in English if not solved. If solved, close it please. Thank's!
