### ISSUE TITLE
Sidebar 的 Category

### ISSUE THREAD

**Issue by lazywei** [iissnan/hexo-theme-next#88]
先感謝作者做出了這麼好的主題！

當我在 `next/_config.yml` 底下註釋掉 `category` 時，首頁上方的「分類」連結會消失，但是 sidebar 的不會，這樣會造成一點小困擾
![image](https://cloud.githubusercontent.com/assets/2840571/7000511/42846c44-dc57-11e4-8356-4ae5a0a6b45b.png)

不知道能不能支援若沒有定義 category link 時就自動隱藏？
謝謝！

**Comment by iissnan** [comment]
如果没有定义 category link 时，侧栏的那个地方是没有链接，但不会隐藏

**Comment by alviezhang** [comment]
但是博客没有分类，侧边栏却有分类，感觉有点怪。

**Comment by lazywei** [comment]
的確，這樣有點怪



-- Chih-Wei (Bert)
