### ISSUE TITLE
楼主 怎么能修改 标题的高亮效果 和 markdown 的‘这个语法的’高亮效果？跪求

### ISSUE THREAD

**Issue by ganjmeng** [iissnan/hexo-theme-next#880]
### Expected behavior (预期行为)

想自定义成其他颜色
### Actual behavior (实际行为)

![image](https://cloud.githubusercontent.com/assets/12026835/15209553/40df0d82-1864-11e6-85ba-8c1c170da3b3.png)
![image](https://cloud.githubusercontent.com/assets/12026835/15209580/6ea76bf6-1864-11e6-8b94-fc41875f25e2.png)

`想修改这个高亮效果`
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔ -  Master
-  Latest Release
-  Old version - 

NexT Scheme:
  ✔ -  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by ganjmeng** [comment]
还有第二个问题就是   首页列表的  阅读次数 一直都是1.。。怎么解决

**Comment by iissnan** [comment]
`code` 标签的样式定义在 `highlight.css` 中：

```stylus
code {
  padding: 2px 4px;
  word-break: break-all;
  color: $code-foreground;
  background: $code-background;
  border-radius: $code-border-radius;
  font-size $code-font-size;
}
```

根据你的需要，修改其中变量的值（定义在 `_variables/base.styl` 中）。

第二个问题信息不够，无法判断。

**Comment by shmys** [comment]
第二个高亮效果可以用**行内代码**高亮，将高亮内容用一对“`”包裹起来即可，这个符号需要在半角英文状态下输入，位置一般在Tab键的上方（注意与单引号的区别）。
比如这样：
![2016090901](https://cloud.githubusercontent.com/assets/9512618/18366787/a989c7f2-764a-11e6-9c39-0b7af99f855a.jpg)
![2016090902](https://cloud.githubusercontent.com/assets/9512618/18366788/a9da122a-764a-11e6-97b7-5a220b7c4e14.jpg)

**Comment by ivan-nginx** [comment]
@ganjmeng dont understand u, write in English if not solved. If solved, close it please. Thank's!
