### ISSUE TITLE
Font Awesome 版本低

### ISSUE THREAD

**Issue by yzlnew** [iissnan/hexo-theme-next#882]
### Expected behavior (预期行为)

例如社交图标使用`Google Plus`，应该得到新的`G+`图标
### Actual behavior (实际行为)

显示的是旧版的，和 Font Awesome 官网的显示效果不符
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
  ✔  Latest Release
-  Old version - 

NexT Scheme:
  ✔  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by iissnan** [comment]
`5.0.1` 内置 FontAwesome 的版本是 `4.4.0`，官网是 `4.6.x`。实际上，你可以更改 fontawesome 的引用来获取最新的版本，见 [文档](http://theme-next.iissnan.com/advanced-settings.html)。

```yml
vendors:
  fontawesome: //maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css
```

主题内置的版本将在 `5.1.0` 中更新。
