### ISSUE TITLE
功能实现：隐藏和显示部分文字

### ISSUE THREAD

**Issue by ganyuanda** [iissnan/hexo-theme-next#883]
在博文中，写有问题和答案，我想隐藏答案，设置一个按钮。读者如果知道答案的话，就不用按那个按钮了，如果不知道，可以点开查看。这个功能在wordpress里可以实现，参考 http://www.wpbeginner.com/plugins/how-to-show-and-hide-text-in-wordpress-posts-with-the-toggle-effect/ 

请问这个功能在NexT里可以实现不？

**Comment by iissnan** [comment]
可以，使用自定义的 [Tag Plugin](https://hexo.io/zh-cn/docs/tag-plugins.html)

**Comment by ganyuanda** [comment]
谢谢IIssnan, 可惜我比较驽钝，进你给的链接，学习了很久，也没有找到解决办法。能不能再给点提示。谢谢！

**Comment by Ianwu0812** [comment]
既有標籤似乎沒有這樣功能，issnan意思是自訂標籤？
ganyuanda <notifications@github.com> 於 2016年5月13日 週五 下午9:23寫道：

**Comment by ganyuanda** [comment]
网上乱搜一通，好像jquerry可以容易实现，参考http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_toggle 
@iissnan @lanwu0812 请问这是一种实现方法吗？

**Comment by Ianwu0812** [comment]
ganyuanda
方向沒錯，你可以試試

ganyuanda <notifications@github.com> 於 2016年5月14日 週六 下午5:59寫道：

**Comment by ganyuanda** [comment]
@Ianwu0812 谢谢！由于我对Jquery几乎一无所知，能不能再给点提示？谢谢！
