### ISSUE TITLE
使用google字体影响了网页加载效率

### ISSUE THREAD

**Issue by lexiaoyao20** [iissnan/hexo-theme-next#886]
这个主题做得不错，就是性能太低了，每打开一个页面都要老半天，有点受不了，不知道大大能否改进一下~~

**Comment by panzhitian** [comment]
最起码要提供加载的日志吧。一般来说是默认的lato字体可能会出问题。

**Comment by weiwosuoai** [comment]
我用这个主题，加载页面也很慢，但是作者本人的博客很快，不知道作者能否将优化的方案告诉下，很喜欢这个主题 ...

**Comment by lexiaoyao20** [comment]
@weiwosuoai @panzhitian 
我用的这里：[issues 49](https://github.com/iissnan/theme-next-docs/issues/49) 的方法解决了问题

**Comment by ganyuanda** [comment]
致@lexiaoyao20 

1. 对一个开源项目，你的这个标题，很不地道。特别是对一个GitHub上最受欢迎，也许是整个Hexo平台上，最受欢迎的主题，你的标题也太不符合实际情况了。

2. 我觉得iissnan对这个项目，不管是写代码，维护，制作使用文档，都是鲜有的用心，请不要以这种态度，对待一个这么好的一个开源项目的所有者，维护者。

3. 开源项目的所有者，iissnan没有义务回答你的问题，Ta的回答取决于你的问题的合理性。你的问题问得很糟糕，没有人愿意回答的。

4. 你的这个标题对于初用hexo和这个主题的人，具有很大的误导性。希望你能修改一下标题。我这样说是有私心的，因为我的两个朋友看了我的博客后，对Hexo和NexT产生了很大的兴趣，我不希望你的标题挫伤了他们的积极性。谢谢，拜托了！！！

**Comment by weiwosuoai** [comment]
@lexiaoyao20 
谢谢你的回答，O(∩_∩)O~

**Comment by lexiaoyao20** [comment]
@ganyuanda 

首先，我并没有任何贬低这个主题以及维护这个主题的大牛们的意思。同时，我是非常喜欢这个主题，如果不是希望这个主题越来越好，我也不会傻乎乎的到这里来提问了。

其次，确实我是遇到问题才来提问的，我在本地打开博客，差不多都要加载一分钟。 刚开始确实是没找到原因。

最后，我非常认同你的建议，是我描述有问题。对此，给大家带来了不便我深表歉意。

**Comment by InFaNg** [comment]
其实可以关闭Google字体，只要在主题配置文件中搜索 font: ，把enable的值改为 false。
顺便安利下我的这篇文章 http://www.gfwsb.com/2016/improveNexTspeed.html
