### ISSUE TITLE
atom.xml  error: " EntityRef: expecting ';' "

### ISSUE THREAD

**Issue by Keystion** [iissnan/hexo-theme-next#889]
![image](https://cloud.githubusercontent.com/assets/2408287/15272098/1edcfea8-1a9c-11e6-8ddf-65113c5f92af.png)

http://blog.webclown.net/atom.xml

这需要怎么解决呢

**Comment by ivan-nginx** [comment]
@Keystion dont understand u, write in English if not solved. If solved, close it please. Thank's!
