### ISSUE TITLE
大大，如何让 ‘分类’ 页面的排列和 ‘标签’ 页面的排列一样，都是横向排列呢？

### ISSUE THREAD

**Issue by weiwosuoai** [iissnan/hexo-theme-next#890]
大大，如何让 ‘_分类_’ 页面的排列和 ‘_标签_’ 页面的排列一样，都是横向排列呢？‘分类’ 页面的排列是**纵向**的呢。

**Comment by djyde** [comment]
可以自己重写 category page http://theme-next.iissnan.com/theme-settings.html#categories-page
