### ISSUE TITLE
Support Apple launcher icons

### ISSUE THREAD

**Issue by seisman** [iissnan/hexo-theme-next#891]
### Expected  and Actual behavior

The website of SeisMan supports apple launcher icons, while the iissnan's note does not.
![img_0007](https://cloud.githubusercontent.com/assets/3974108/15273058/1db47586-1a53-11e6-968d-798d1bd1eba0.png)
### Steps to reproduce the behavior (重现步骤)

Go to http://notes.iissnan.com/ and add it as a bookmark on Safari.
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
- ✔  Latest Release
-  Old version - 

NexT Scheme:
- ✔  All schemes
-  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

The source code of github:

```
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
```

References: 
1. Apple icons: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
2. website to generate icons of different size: http://iconifier.net/

**Comment by seisman** [comment]
Useful website: http://realfavicongenerator.net/

**Comment by Jatstar** [comment]
+1

**Comment by iissnan** [comment]
Just place the icons with correct name (prefixed with `apple-touch-icon` and `apple-touch-icon-precomposed`)  in the root directory of your site, it would works in iOS Safari. No HTML needed.

I am not sure that do browsers in Android Platform recognize this or not.

**Comment by ivan-nginx** [comment]
@seisman solved?
