### ISSUE TITLE
如何自定义生成的连接为https://

### ISSUE THREAD

**Issue by ifhw** [iissnan/hexo-theme-next#893]
### Expected behavior (预期行为)

所有页面以及文章的内容均呈现https链接
### Actual behavior (实际行为)

文档访问的方式是相对访问，所以首页如果设成https://了，文章内容也会是https链接
但是主题生成的页面的链接不是。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
5.0.1

NexT Scheme:
-  Mist

**Comment by djyde** [comment]
『主题生成的页面的链接』是指？

**Comment by ifhw** [comment]
比如about,categories等。

-------- 原始邮件 --------
发件人： Randy <notifications@github.com>
日期: 2016/6/3  14:21  (GMT+08:00)
收件人： iissnan/hexo-theme-next <hexo-theme-next@noreply.github.com>
抄送： HenryFong <ifhw@outlook.com>, Author <author@noreply.github.com>
主题： Re: [iissnan/hexo-theme-next] 如何自定义生成的连接为https:// (#893)

『主题生成的页面的链接』是指？

---

**Comment by ivan-nginx** [comment]
@ifhw dont understand u, write in English if not solved. If solved, close it please. Thank's!
