### ISSUE TITLE
配置文件重命名

### ISSUE THREAD

**Issue by willin** [iissnan/hexo-theme-next#894]
将 `_config.yml` 重命名，如 `_config.yml.sample` 这样就方便用 `git submodule`进行引用和升级了。

P.S.

我在源码 https://github.com/iissnan/hexo-theme-next/blob/master/scripts/merge-configs.js 中看到有合并配置的代码，也试着在主题目录下 建立一个 `_data`目录写主题配置，但好像不是这么用的。

**Comment by panzhitian** [comment]
`../hexo_rootdir/source/_data/next.yml`

**Comment by willin** [comment]
哦。。。为什么要放在这个位置啊？

**Comment by 20015jjw** [comment]
@willin 因为这么放解决了submodule的引用问题了

**Comment by ivan-nginx** [comment]
@willin dont understand u, write in English if not solved. If solved, close it please. Thank's!
