### ISSUE TITLE
类别排序（order of categories)

### ISSUE THREAD

**Issue by ganyuanda** [iissnan/hexo-theme-next#896]
### Expected behavior (预期行为)

类别按照拼音字母排序
### Actual behavior (实际行为)

看不出排序的规则
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

   ✔ -  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
  ✔  -  Pisces
### Other Informations (Like Browser, System, Screenshots)

![next-cat-order](https://cloud.githubusercontent.com/assets/18499648/15345139/1a7bf9e6-1cdf-11e6-9f5b-f671faa6493c.png)

**Comment by ivan-nginx** [comment]
@ganyuanda dont understand u, write in English if not solved. If solved, close it please. Thank's!
