### ISSUE TITLE
本地搜索打开缓慢

### ISSUE THREAD

**Issue by mritd** [iissnan/hexo-theme-next#897]
### Expected behavior (预期行为)

点击搜索弹出搜索框
### Actual behavior (实际行为)

点击后无反应，实际后台下载 search.xml，时间可能长达2~10s
### Steps to reproduce the behavior (重现步骤)

刷新浏览器缓存，首次点击搜索按钮
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
-  Latest Release
-  Old version - 

NexT Scheme:
  ✔  All schemes
-  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

<img width="1329" alt="2016-05-18 9 04 08" src="https://cloud.githubusercontent.com/assets/13043245/15359683/fd9dd066-1d3c-11e6-9b60-34d8505c2929.png">

建议是否可以在主页加载时，后台直接下载 search.xml，避免点击搜索时懒加载导致的高延迟问题？

**Comment by mritd** [comment]
突然想到一个小想法。。。个人博客的 图片全部放在 upyun  CDN 里，我发现里面可以放 HTML。。。可以把整站放进去。。。但是目前没找到 绑定自定义域名后如何设置默认的访问文件，现在想 在源站的 nginx 上配置规则，默认访问只返回主页，其他一切资源 301重定向到 upyun。。。这样可以实现基本全站 CDN 加速

**Comment by panzhitian** [comment]
曾经折腾过：https://blog.poonchit.im/2016/02/15/hexo-next-speedup-qiniu/
这只是改了除html的静态资源，真正全站cdn还是需要备案，即绑定域名，然后直接cname就可以了。

**Comment by flashlab** [comment]
@mritd 最初的版本在加载search.xml过程中图标是会转动的（可以参考我的博客），后来跟搜索栏一起精简掉了。你可以试着生成小一些的search.xml来加快响应。

**Comment by mritd** [comment]
@panzhitian 我试了一下 upyun 的，确实需要域名备案。。。好蛋疼，我在想 在 源站 nginx 全部301重定向是否可行。。。域名刚刚转出到  Godaddy。。。虽然备案过，不过看着备案我就不爽

**Comment by amao12580** [comment]
遇到同样的问题，请教如何精简search.xml？？

**Comment by Maples7** [comment]
+1

**Comment by flashlab** [comment]
我是稍微修改了下插件，在读取content时删除所有html标签，此外可以通过只索引摘要来减小体积。

**Comment by liqiang311** [comment]
现在文章越来越多，本地搜索功能打开要2秒中，有没有解决方法呢？谢谢。

**Comment by mritd** [comment]
.....我换了 jekyll，感觉还是 jekyll 大法不错
