### ISSUE TITLE
文章标题含有C#时 # 不能显示，生成部署时也会出错

### ISSUE THREAD

**Issue by WeikuiWang** [iissnan/hexo-theme-next#898]
### Expected behavior (预期行为)

在文章标题中显示 C#
### Actual behavior (实际行为)

 执行hexo g 命令时该文件就未成功生成，字母C后面的内容都没有了。仍然能部署完成，但网页中点击该该文章标题时内容页面提示找不到。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  ✔Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  ✔Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

应该是对特殊字符的读取问题

**Comment by ivan-nginx** [comment]
@WeikuiWang dont understand u, write in English if not solved. If solved, close it please. Thank's!
