### ISSUE TITLE
代码高亮无效

### ISSUE THREAD

**Issue by yangxiaoge** [iissnan/hexo-theme-next#899]
麻烦 大神支招!!

语法:

![](http://upload-images.jianshu.io/upload_images/1798697-bc79e8dd9d28ba4d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

效果如下:

![](http://upload-images.jianshu.io/upload_images/1798697-c8658bb74da5ec14.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by yangxiaoge** [comment]
``` cpp

 ```

**Comment by zjbao123** [comment]
同样遇到了该问题= =

**Comment by yangxiaoge** [comment]
```
代码块
```

我更新了下主题就好了

**Comment by hunao0221** [comment]
解决了我，我的也是白底黑字

**Comment by yangxiaoge** [comment]
在`主题` `_config.yml` 文件中 `highlight_theme`改成 `night blue`或者别的,  然后代码块这么写

![daimakuai.png](http://naxiexiaojiyi1.qiniudn.com/daimakuai.png?e=1464594918&token=1JBeQi3vz7kUmQlsAf00FRntxudo01dbWsLMQT30:GjtsqQcGeIbFnyXtbgbM_R8CDb0=)

**Comment by hunao0221** [comment]
在主题 _config.yml 文件中 highlight_theme改成 night blue或者别的,
我是这样写的，但字体还是清一色的白，背景颜色会变

**Comment by yangxiaoge** [comment]
还有, 在你的 `根目录`主题 加上 
highlight:	#代码块的设置
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

**Comment by hunao0221** [comment]
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
然后hexo g出错

yang.jianan <notifications@github.com>于2016年5月30日周一 下午3:07写道：

**Comment by yangxiaoge** [comment]
一个节点下的
![11.png](http://naxiexiaojiyi1.qiniudn.com/11.png?e=1464596977&token=1JBeQi3vz7kUmQlsAf00FRntxudo01dbWsLMQT30:2ew8go3aQdOg2PgoOTJId3eluqw=) @hunao0221

**Comment by hunao0221** [comment]
如你所说的设置，hexo g会有下面这样的错误
![image](https://cloud.githubusercontent.com/assets/11972530/15642900/cbb5ba98-267c-11e6-911f-4d71f34f17bf.png)
但是当我这样写

![image](https://cloud.githubusercontent.com/assets/11972530/15642971/3ddaa610-267d-11e6-978f-123ef3046282.png)

这样代码会高亮

**Comment by yangxiaoge** [comment]
这个我就不懂了，要请作者看看了。
或者，把配置保存下，重新下载主题。

**Comment by RangoLee** [comment]
~~~objective-c
code
~~~
这样的 代码 部署到 github 也是无法高亮显示 求解

**Comment by Detachment** [comment]
Javascript 也遇到同样的问题，有人能帮忙解答下吗？

**Comment by Cao-Yu** [comment]
我也遇到同样的问题了……各种搜都没有结果

**Comment by imzyf** [comment]
尝试在 `package.json` 删除关于 highlight 的那行，然后就可以了，但不知道为什么。

**Comment by ivan-nginx** [comment]
@yangxiaoge dont understand u, write in English if not solved. If solved, close it please. Thank's!
