### ISSUE TITLE
文章目录文字显示不全

### ISSUE THREAD

**Issue by Dwayneten** [iissnan/hexo-theme-next#900]
### Expected behavior (预期行为)

sidebar 里的文章目录如果某一栏文字比较多而至于一行容纳不下的话就换行显示。
### Actual behavior (实际行为)

进入文章页面后， sidebar 里的文章目录如果某一栏文字比较多， 会溢出 sidebar 显示不了。
### Steps to reproduce the behavior (重现步骤)

在某篇博文设置较长的（≥15 中文字符）标题， 使其出现在 sidebar 的文章目录作为快速导航。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  ✔  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  ✔  Pisces
### Other Informations (Like Browser, System, Screenshots)

Chrome, Windows.

**Comment by Dwayneten** [comment]
看了代码好像是 feature， 似乎是处理成溢出部分用 "..." 来表示， 但实际上只能看见第一个 "."

**Comment by aixiu** [comment]
要真的是溢出换行的话那真的太丑了，影响整体美观，还是本身的用“…”表示就好。

**Comment by ivan-nginx** [comment]
@Dwayneten dont understand u, write in English if not solved. If solved, close it please. Thank's!
