### ISSUE TITLE
mathjax支持出错

### ISSUE THREAD

**Issue by spencerpomme** [iissnan/hexo-theme-next#902]
### Expected behavior (预期行为)
预期渲染出正确的公式

### Actual behavior (实际行为)
实际上没有渲染出来，而是直接显示了Latex代码

### Steps to reproduce the behavior (重现步骤)
在post中输入下列Latex代码：
$$\begin {eqnarray*}
 \large O(\normalsize \frac{cn}{4}\cdot(1+\sum_{h=1}^{\lg(n)} \frac{h}{2^{h-1}})\large)\normalsize
 &=&\large O(\normalsize\frac{cn}{4}\cdot(1+\sum_{h=0}^{\infty} \frac{h}{2^{h}})\large) \\
 &=&\large O(\normalsize\frac{cn}{4}\cdot(1+2)\large)\\ \\
 &=&\large O(\normalsize\frac{3cn}{4}\large)\\ \\
 &=&\large O(\normalsize n \large)
\end {eqnarray*}$$

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

 ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔   Pisces

### Other Informations (Like Browser, System, Screenshots)

<img width="681" alt="2016-05-20 11 17 42" src="https://cloud.githubusercontent.com/assets/10029658/15432550/46beec1c-1ee1-11e6-875c-010589cb5d75.png">

**Comment by spencerpomme** [comment]
http://spencerpomme.github.io/2016/05/19/heapsort/#more
具体可以查看该页，求帮助

**Comment by seisman** [comment]
在 https://github.com/iissnan/hexo-theme-next/issues/826 有讨论过

**Comment by spencerpomme** [comment]
��������������

**Comment by spencerpomme** [comment]
Thanks a lot
