### ISSUE TITLE
add_this dosen't work

### ISSUE THREAD

**Issue by chy9002** [iissnan/hexo-theme-next#906]
### Expected behavior (预期行为)
显示Addthis

### Actual behavior (实际行为)
出现相关代码，但是未显示Addthis

### Steps to reproduce the behavior (重现步骤)

1. 取消add_this_id注释
2. 填入id

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist ✔
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

[site](colincai.com)

**Comment by seisman** [comment]
进 add_this 的网站，然后在"tools"->"share buttons"下打开并设置分享按钮才可以使用。默认情况下分享都是关闭的。

**Comment by hackjustu** [comment]
嗯 需要去add_this的网站进行配置。注意不是所有分享方案都可以使用，经过测试，可以完美使用**侧栏**和**底栏**两个方案。

**Comment by chy9002** [comment]
谢谢大家的回答，已解决
