### ISSUE TITLE
字数统计

### ISSUE THREAD

**Issue by willin** [iissnan/hexo-theme-next#907]
### Expected behavior (预期行为)

前几天升了5.1.0，发现之前用主题改的字数统计什么的都没了。
建议加到主题中，通过配置进行控制。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  5.1.0

NexT Scheme:
-  All schemes
### Other Informations (Like Browser, System, Screenshots)

https://github.com/willin/hexo-wordcount

单篇字数、阅读时间预计和总字数统计

由于工作繁忙，所以没有什么时间折腾了，抱歉。

**Comment by asdf2014** [comment]
我也遇到了~~ http://yuzhouwan.com/2017/04/07/Linux/

**Comment by ivan-nginx** [comment]
@willin dont understand u, write in English if not solved. If solved, close it please. Thank's!
