### ISSUE TITLE
index.md页面如何能够在侧边栏出现文章的目录

### ISSUE THREAD

**Issue by oscar0715** [iissnan/hexo-theme-next#909]
### Expected behavior (预期行为)

自己新建了一个menu菜单项techonology后，在source文件夹下新建/techonology文件夹，并添加index.md
在网站上打开该index.md页面时，侧边栏不会像一般post一样出现两栏，一栏是table of content，一栏overview。
怎么修改可以达到使index页面也能和post一样出现两栏呢？
### Actual behavior (实际行为)

在网站上打开该index.md页面时，侧边栏，不会像一般post一样出现两栏，一栏是table of content，一栏overview。实际只会出现overview一栏

求问大神们怎么解决呢？

**Comment by lixin4306ren** [comment]
front-matter里添加layout: post即可

例如：

title: about
date: 2016-08-02 14:34:03
comments: false

layout: post

**Comment by yusmile** [comment]
@lixin4306ren   请问front-matter在哪里修改呢？

**Comment by oscar0715** [comment]
@lixin4306ren 
front-matter就是每个post的开头的地方。例如这样：
![image](https://cloud.githubusercontent.com/assets/5731592/22701906/08ad0948-ed2d-11e6-9ec3-3dffd305e601.png)

**Comment by yusmile** [comment]
@oscar0715  谢谢回复，我还想请问下：
1.这个front-matter，能否在哪里统一修改制定模板吗？
2.如果可以的话，总共有哪些可选项呢？（官方文档里 好像有些网页一直点击无法跳转）

**Comment by ivan-nginx** [comment]
@oscar0715 dont understand u, write in English if not solved. If solved, close it please. Thank's!
