### ISSUE TITLE
百度统计js代码添加失败

### ISSUE THREAD

**Issue by wayneshawn** [iissnan/hexo-theme-next#91]
发现部分html添加百度统计js代码失败。其中成功的一部分tags项为空，失败的均为tags:后面有内容的。是否有人碰到相同的问题？

**Comment by iissnan** [comment]
能否提供你的地址？

**Comment by wayneshawn** [comment]
wayneshawn.github.io

**Comment by iissnan** [comment]
已修复 :smile:

**Comment by wayneshawn** [comment]
谢谢！

2015-04-13 14:11 GMT+08:00 Vi <notifications@github.com>:
