### ISSUE TITLE
在source/_posts下新建文章目录

### ISSUE THREAD

**Issue by ybbz** [iissnan/hexo-theme-next#914]
### Expected behavior (预期行为)

避免因_posts下文章过多导致的浏览不便

### Actual behavior (实际行为)

url出现问题

### Steps to reproduce the behavior (重现步骤)

在_posts下新建目录history，在history目录下新建文章2016-05-27-test-dir.md。depoly之后，文章可以在博客中显示，但是url变成了http://blog.***.com/2016/05/27/history-2016-05-27-test-dir/

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by djyde** [comment]
It's not an issue of theme
