### ISSUE TITLE
修改标题在手机端显示大小

### ISSUE THREAD

**Issue by skycrown** [iissnan/hexo-theme-next#915]
### Expected behavior (预期行为)

我用的是Pisces主题，发现在手机端，从二级标题开始，字体就很小，比正文字体还小，如果用到四级标题，那就更小了。想请问，怎样修改手机端各级标题显示的大小呢? @iissnan 

NexT Version:
-  Master

NexT Scheme:
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

![skycrown net](https://cloud.githubusercontent.com/assets/8112882/15627880/c402ceac-2524-11e6-8c21-437ac0671b2b.png)
我的网站是skycrown.net

**Comment by ivan-nginx** [comment]
@skycrown dont understand u, write in English if not solved. If solved, close it please. Thank's!
