### ISSUE TITLE
页面无法显示

### ISSUE THREAD

**Issue by hunao0221** [iissnan/hexo-theme-next#919]
忘了设置了什么属性，就这样了
![image](https://cloud.githubusercontent.com/assets/11972530/15634514/9a3ec22c-25f8-11e6-9018-dd1834652375.png)

**Comment by panzhitian** [comment]
浏览器检查哪个资源没有加载完成或者语法出错。

**Comment by seisman** [comment]
我在用 `hexo-browsersync` 插件实现网页自动刷新时遇到了类似的问题，个别页面无法显示，类似你这样。查看网页源码发现源码前面还正常，到某个地方就开始乱码，导致body，html没有闭合标签，故而显示出错。不知道你是不是类似的原因，仅供参考。

**Comment by hunao0221** [comment]
好的，谢谢，已解决

Dongdong Tian <notifications@github.com>于2016年5月31日周二 13:06写道：

**Comment by Kermit95** [comment]
@hunao0221 我也遇到了这个问题，请问怎么解决的？
