### ISSUE TITLE
用https访问，点归档或标签，自动跳到http是怎么回事

### ISSUE THREAD

**Issue by zhgcao** [iissnan/hexo-theme-next#920]
### Expected behavior (预期行为)

如：https://zhgcao.github.io，希望不管点击站内的任何链接，都保持是https
### Actual behavior (实际行为)

但点击归档或标签链接时，却转为http协议了，绿色小锁消失了，再点站内链接一直是http
环境：Github + HEXO + NexT
可能是哪里有问题？

谢谢
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by panzhitian** [comment]
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by GeorgioWan** [comment]
**方法一、**用 JS redirect
**方法二、**如果有使用 CloudFlare，可設置 Page Rule

我目前是用 **方法二**，感覺比較適當一點
[參考一下 konklone 的討論串](https://gist.github.com/konklone/9968713)

**Comment by ivan-nginx** [comment]
@zhgcao dont understand u, write in English if not solved. If solved, close it please. Thank's!
