### ISSUE TITLE
博客的总访问人数和文章的阅读人数是否可以显示?

### ISSUE THREAD

**Issue by RivenDarry** [iissnan/hexo-theme-next#926]
如何能集成出这两个功能呢?

**Comment by lengthmin** [comment]
http://theme-next.iissnan.com/third-party-services.html#analytics-busuanzi

文档中有：
不蒜子统计
阅读次数统计（LeanCloud)

**Comment by RivenDarry** [comment]
感谢!

**Comment by ivan-nginx** [comment]
@RivenDarry dont understand u, write in English if not solved. If solved, close it please. Thank's!
