### ISSUE TITLE
是否考虑为移动设备添加【返回顶部】功能？

### ISSUE THREAD

**Issue by amao12580** [iissnan/hexo-theme-next#927]
NexT.Pisces在PC端是支持返回顶部功能的，按钮在网页右下角。但在手机端，就没有这个按钮了。

### Expected behavior (预期行为)
支持移动设备浏览时返回顶部。

### Actual behavior (实际行为)
目前还不支持。

### Steps to reproduce the behavior (重现步骤)
1.用手机或其他移动设备进入：<a target="_blank" href="http://amao12580.github.io/">http://amao12580.github.io/</a>，随便选一篇文章浏览，没有返回顶部功能。
![issuse](https://cloud.githubusercontent.com/assets/4270177/15769114/81d11ab0-298a-11e6-80dd-5a275d179423.png)

2.也可以用PC端chrome打开，按F12，再按Ctrl+Shift+M，模拟移动设备浏览，你可以选择：Galaxy S5

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master：5.0.1

NexT Scheme:
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)

手机是魅蓝Note2自带浏览器，webkit内核，不过应该跟平台无关。

**Comment by djyde** [comment]
你可以在 `back-to-top.styl` 里修改

```styl
  +mobile() {
    display: none;
  }
```

把 `display: none;` 注释掉即可。

至于是否要默认为显示，要问 @iissnan

**Comment by djyde** [comment]
另外 @iissnan 能不能给我个处理 issue 的权限？

**Comment by iissnan** [comment]
@djyde Collaborator Invitation has been sent.

**Comment by djyde** [comment]
@iissnan Cool. How do you think about this issue? Should it be configable?

**Comment by iissnan** [comment]
I don't think it is necessary to add `back to top` button on mobile devices. Because:

1. Mobile devices has very limited space.
1. Mobile devices with touch functionality could scroll up to top easily than desktop devices.
