### ISSUE TITLE
next主题，主题 永久地址 不支持 permalink: :title.html 有何办法？

### ISSUE THREAD

**Issue by eurusd** [iissnan/hexo-theme-next#93]
谢谢

**Comment by iissnan** [comment]
不用 **重复** 并且 **到处** 发吧。。 :sweat:

- https://github.com/iissnan/hexo-theme-next/issues/92
- https://github.com/iissnan/hexo-theme-next/issues/90
- https://github.com/iissnan/hexo-theme-next/issues/89
- https://github.com/iissnan/hexo-theme-next/issues/87
- https://github.com/hexojs/hexo/issues/1180

**Comment by iissnan** [comment]
已支持 `:title.html` 或者 `:category/:title/` 或者 `:title` 等 permalink。

**Comment by eurusd** [comment]
谢谢，不好意思。我可以删掉吗？

**Comment by Xuanwo** [comment]
并不能删掉，请及时close

**Comment by eurusd** [comment]
如何close?

**Comment by eurusd** [comment]
permalink: :title.html  有一个头痛的问题，所有生成的文章，全跑根目录了。 很乱，有办法吗？

为了不乱只好设置成permalink: post/:title.html 文章全在post目录

**Comment by iissnan** [comment]
如果是自己的服务器，可以考虑在 HTTP 服务器做 rewrite
