### ISSUE TITLE
打赏功能在本地和在线显示样式不一样

### ISSUE THREAD

**Issue by qiaoer2017** [iissnan/hexo-theme-next#930]
#### 本地显示是这样的：

![本地](http://upload-images.jianshu.io/upload_images/1767852-c2b0aac73dd998fa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
#### 上传到Github上，是这样的：

![在线](http://upload-images.jianshu.io/upload_images/1767852-a34de3c883d80381.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
#### 我用的浏览器是Safari。

太难看了，我还是不要打赏了。😶

**Comment by hunao0221** [comment]
同样的情况

**Comment by djyde** [comment]
打赏这个功能的样式的确写得有点问题

**Comment by wilcosheh** [comment]
试试 hexo clean, hexo d -g

**Comment by Kico-Yu** [comment]
你好，请问这个问题有解决的方案吗？

**Comment by SnailTyan** [comment]
同样的问题

**Comment by ivan-nginx** [comment]
@qiaoer2017 dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by juventusryp** [comment]
使用
hexo clean
hexo d -g
解决
