### ISSUE TITLE
远程仓库无法备份theme/next主题的问题

### ISSUE THREAD

**Issue by w4lle** [iissnan/hexo-theme-next#932]
### Expected behavior (预期行为)
新建分支post用于存放配置文件，预期可以备份theme/next目录下的配置内容

### Actual behavior (实际行为)
实际上并没有，这就导致我删除本地的项目之后，无法还原当时的配置文件，还要重新配置？

**Comment by djyde** [comment]
不是很懂你的意思。。。

**Comment by w4lle** [comment]
![qq20160606-0 2x](https://cloud.githubusercontent.com/assets/7310246/15810485/b86f642a-2bd1-11e6-9bea-c8c603e9ba35.png)

用github Pages + hexo 搭建的博客，theme/next 没有上传到github仓库，导致我删除了本地仓库后从github拉取项目不能还原我的主题配置。这是为什么？

**Comment by djyde** [comment]
这个并不是主题的问题

**Comment by w4lle** [comment]
那是什么问题呢？
我现在没办法还原我的主题配置了，该怎么办呢。

**Comment by w4lle** [comment]
另外我看了一下别人用hexo next主题搭建的博客的github仓库，theme/next 都是上面那张图提交状态。
theme/next是个子仓库，但是子仓库并没有跟随主仓库一起push到远程仓库啊。

**Comment by djyde** [comment]
https://github.com/djyde/blog

![image](https://cloud.githubusercontent.com/assets/914329/15811239/5d367672-2bd9-11e6-99ef-6e558b1f4670.png)

**Comment by w4lle** [comment]
对，我说的就是这个问题，如果你换电脑或者删除了本地仓库，怎么恢复next文件夹的？

**Comment by w4lle** [comment]
就是因为theme/next是个子项目的原因
建议作者增加一条提示，手动增加submodule
不然像我把本地仓库删了，主题又做了很多修改，无法通过远程仓库恢复
再重新配真的挺麻烦的。

**Comment by iissnan** [comment]
若仅要同步主题配置，可以考虑使用 [这种方法](https://github.com/iissnan/hexo-theme-next/issues/328)；而如果对主题做定制的话，单单使用 submodule 也无法将你的提交同步到远程，这种情况需要使用 fork + submodule。

**Comment by w4lle** [comment]
用的fork + subtree
建议作者在说明文档中更新下怎么同步修改到远程，以免别人再踩坑。

**Comment by tyrionyu** [comment]
@w4lle fork + subtree 具体怎么用呀！我是菜鸟不太会用。

**Comment by tyrionyu** [comment]
@w4lle 如果某天开发者更新了主题，要怎么更新过来。

**Comment by xiaobai050** [comment]
我用临时构建git主题仓库的方式，感觉还好，写了篇分享。
http://zhangnai.xin/2018/11/11/hexo-theme-upgrade/
