### ISSUE TITLE
归档页面日志列表字体和整体大小、风格不一致

### ISSUE THREAD

**Issue by wongxingjun** [iissnan/hexo-theme-next#935]
### Problems(问题)

归档页面日志列表字体和整体大小、风格不一致，怎么改一下？
![qq 20160608152523](https://cloud.githubusercontent.com/assets/6941795/15886281/b13693ae-2d8e-11e6-9b65-17508ee82c16.png)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master ✔  
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes ✔  
-  Muse
-  Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@wongxingjun dont understand u, write in English if not solved. If solved, close it please. Thank's!
