### ISSUE TITLE
文章页面的文章目录只显示首个标题同级别的，其他级别的不显示，不能显示多级标题目录

### ISSUE THREAD

**Issue by laneypeng** [iissnan/hexo-theme-next#936]
首次出现的是一级标题，就只显示一级的。若首次出现二级标题，则只显示二级标题。没有形成那种多级标题目录，请问是什么问题？谢谢

**Comment by xovel** [comment]
目录生成依赖于hexo的helpers中的toc.js(`...\blog\node_modules\hexo\lib\plugins\helper\toc.js`)

注意：**标题不能跨级别**。请仔细检查文章的目录级别。

**Comment by ivan-nginx** [comment]
@laneypeng dont understand u, write in English if not solved. If solved, close it please. Thank's!
