### ISSUE TITLE
希望可以禁止用户选中代码高亮里面的行号

### ISSUE THREAD

**Issue by linjinying** [iissnan/hexo-theme-next#937]
### 前言
感谢前辈作了这么精致的hexo主题，非常的nice！

### Expected behavior (预期行为)
我觉得绝大多数的情况下，代码行号应该只是辅助显示的作用，希望可以禁止用户选中代码高亮里面的行号（-webkit-user-select: none;）

### Actual behavior (实际行为)
可以选中

### Steps to reproduce the behavior (重现步骤)
选中代码

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔

**Comment by amao12580** [comment]
关注这个问题，希望在highlight_theme增加设置

**Comment by shliujing** [comment]
是这个问题吗？
![](http://7xncbk.com1.z0.glb.clouddn.com/16-7-7/92783415.jpg)

我想去掉行数，但是不知道怎么去掉?

**Comment by shliujing** [comment]
@iissnan

**Comment by springjk** [comment]
@shliujing see #1049

**Comment by iissnan** [comment]
已更新，谢谢
