### ISSUE TITLE
怎样让next支持Latex,像MathJax一样，最近写论文要用到

### ISSUE THREAD

**Issue by bsqql123** [iissnan/hexo-theme-next#938]
比如下面代码
$$
\frac{\partial u}{\partial t} = h^2 \left( \frac{\partial^2 u}{\partial x^2} + \frac{\partial^2 u}{\partial y^2} + \frac{\partial^2 u}{\partial z^2}\right)
$$
如何把它正确显示

**Comment by aixiu** [comment]
如果next现在不支持，你可以找个支持的解析器，解析出来，截高清图，在nexo写文章时，插入图片。。暂时解决问题。

**Comment by bsqql123** [comment]
@aixiu 谢谢你的建议，不过突然发现原来next自带MathJax支持，在主题配置文件里
在Third Party Services Settings里有个
mathjax:
  enable: ture
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
就可以使用latex了

**Comment by Tveek** [comment]
自带的不好用

**Comment by LucienXian** [comment]
mathjax.js 会Failed to load resource: the server responded with a status of 403 () 
我开启之后
