### ISSUE TITLE
手机端访问，视频不能自适应

### ISSUE THREAD

**Issue by iczbl** [iissnan/hexo-theme-next#94]
文章里包含youtube视频，在手机端不能自适应分辨率，请问有何办法？

**Comment by iissnan** [comment]
我还没试过视频，我会找个时间测试下。

**Comment by iissnan** [comment]
你使用什么设备？我在 iPhone 5s 上测试 Youtube 的视频可以正确自适应。

**Comment by iczbl** [comment]
android4.2.2原生浏览器和chrome beta 43.0.2357.78都无法自动适应，其他手机浏览器没有测试，
使用的是youtube默认的宽高，`<iframe width="560" height="315" src="https://www.youtube.com/embed/-YGDyPAwQz0" frameborder="0" allowfullscreen></iframe>`

**Comment by iczbl** [comment]
@iissnan 
sorry，我可能描述错了，我的意思是播放器的窗口超出了屏幕范围，能通过左右拖动显示整个播放器窗口，宽高比正常。但能不能将播放器的底边宽度自动缩放到屏幕宽度，从而能完整地显示视频?

**Comment by iissnan** [comment]
@iczbl 可以使用 Hexo 的 [youtube tag plugin](http://hexo.io/docs/tag-plugins.html#Youtube) 来嵌入 Youtube 视频，通过这种方式嵌入的视频是支持屏幕自适应的：

```
{% youtube zxr8VpClcW8 %}
```

**Comment by iczbl** [comment]
非常感谢

**Comment by eurusd** [comment]
有办法加载优酷视频吗？
