### ISSUE TITLE
如何使生成的博客文章的链接，与文章的Title不同，分离开来

### ISSUE THREAD

**Issue by caelanyang** [iissnan/hexo-theme-next#940]
### Expected behavior (预期行为)
http://xxxxxx.info/2016/06/10/name-of-blog-article
想要文章的链接与文章的标题分离，即链接里面是英文，但是文章的标题依旧是汉字，这样就不会出现下面那种看着很乱的链接了

### Actual behavior (实际行为)
浏览器显示包含文章的标题，汉字，复制或者转发就变成这种：
http://xxxxxx.info/2016/06/10/%E4%BD%BF%E7%94%A8ProGuard%E7%BC%A9%E5%87%8F%E4%BB%A3%E7%A0%81%E5%92%8C%E8%B5%84%E6%BA%90%E4%BB%A5%E5%8F%8A%E6%B7%B7%E6%B7%86%E4%BB%A3%E7%A0%81/
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  ✔  Pisces

**Comment by xovel** [comment]
链接名字是对应的**文件名**，而文章的title是在md文件中直接指定的。本来就不一样。

**Comment by iissnan** [comment]
@xovel 正解

**Comment by caelanyang** [comment]
。。。。。好吧，原来是这样啊。
![image](https://cloud.githubusercontent.com/assets/15037850/16065186/f437b858-32da-11e6-95b1-fb2f22ed43cc.png)
我把这里改成etitle,然后在文章开头的部分加上 etitle:abcd，然后生成的链接就是...2016/06/10/abcd/，自己胡乱摸索竟然也解决了，谢谢你的回答
