### ISSUE TITLE
关于目录的一个问题：指定文章禁用右侧的目录

### ISSUE THREAD

**Issue by xovel** [iissnan/hexo-theme-next#943]
~~翻遍了issue愣是没找到处理方案。~~

目的：指定某一篇文章，文章里面有`hx`形式的标题，常规情况下会生成一个目录放在右侧的侧边栏。但是某些场景下，我并不需要这个目录显示。又不想去掉正文中的`hx`标签。但侧边栏还是要留着。。。

求教如何去实现？

~~是不是这个需求有点奇葩了？~~

**Comment by lzhr** [comment]
自己写一个special-layout ？
post.swig片段：
```
{% block sidebar %}
  {{ sidebar_template.render(true) }}
{% endblock %}
```

**Comment by lzhr** [comment]
sidebar.swig片段：
```
{% set display_toc = is_post and theme.toc.enable %}

      {% if display_toc %}
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap" >
            {{ __('sidebar.toc') }}
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview">
            {{ __('sidebar.overview') }}
          </li>
        </ul>
      {% endif %}
```

**Comment by xovel** [comment]
@lzhr
~~I just solved this by using a special front-matter: `notoc: true`~~
~~。。。习惯了英文~~

多谢提点，问题已解决。

`..\layout\_macro\sidebar.swig`中将
```
{% set display_toc = is_post and theme.toc.enable %}
```
这一句改成：
```
{% set display_toc = is_post and theme.toc.enable and !page.notoc %}
```
如果需要禁用目录，在对应的Front-Matter部分添加一个`notoc: true`就行了。

**Comment by ivan-nginx** [comment]
@xovel dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by xovel** [comment]
@ivan-nginx  Well, it is done already.
