### ISSUE TITLE
_config.yml中没有找到language项

### ISSUE THREAD

**Issue by chengyi818** [iissnan/hexo-theme-next#946]
### Expected behavior (预期行为)
我刚使用Next,在主题配置文件中没有找到language这一项,我自己添加了一项,并设置为zh-Hans

### Actual behavior (实际行为)
网页显示的语言随机变化.

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master ✔
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces ✔

**Comment by aixiu** [comment]
# Site下的
language: zh-Hans
有的，就是最上边第10行左右。

**Comment by chengyi818** [comment]
@aixiu 我的版本是5.0.1,并没有看到.我的临时解决办法就是把languages下面其他的语言都删了,就保留了我自己想要的.

**Comment by lengxing** [comment]
其实我也碰到了这个问题，好像最新的配置文件里面是没有语言项目配置的

**Comment by djyde** [comment]
确实缺少默认配置

**Comment by djyde** [comment]
@chengyi818 @lengxing 只要在 `blog/_config.yml` 设置一下 language 即可。

@iissnan 没有填写默认语言是经过考虑的还是忘了写？

**Comment by lengxing** [comment]
@djyde 这个配置项目应该怎么写，我按照给出的说明里面设置了，但是依然不生效，而且修改后已经clean过重新生成的，很困惑，能不能给个可以使用的具体配置，不胜感激

**Comment by djyde** [comment]
@lengxing 在全局（不是主题）的 `_config.yml` 增加一行:

```yml
language: zh-Hans
```

**Comment by lzhr** [comment]
两个配置文件，一个是根目录的站点配置，一个是主题下的主题配置文件
http://theme-next.iissnan.com/getting-started.html#select-language
![qq 20160618000814](https://cloud.githubusercontent.com/assets/6972978/16156952/13f527ba-34e9-11e6-8cac-8262ee640fa1.jpg)

**Comment by lzhr** [comment]
@lengxing 
https://hexo.io/zh-cn/docs/configuration.html
http://theme-next.iissnan.com/getting-started.html
注意区分两个配置文件
![12131](https://cloud.githubusercontent.com/assets/6972978/16157040/83a5789e-34e9-11e6-9254-e27f22ec552e.jpg)

**Comment by Mezy** [comment]
有的，如楼上所说
languge的修改是在站点全局配置文件中而不是主题配置文件中，
你应该修改这个目录的_config.yml
<img width="190" alt="default" src="https://cloud.githubusercontent.com/assets/14347794/16288746/d2c62b44-3921-11e6-92a7-23e0dd57a4af.png">


在代码第10行处
<img width="252" alt="langugeset" src="https://cloud.githubusercontent.com/assets/14347794/16288812/644e170c-3922-11e6-8eec-a71db6dc2a58.png">


---
找不到language是打开了主题目录的_config.yml
<img width="192" alt="default" src="https://cloud.githubusercontent.com/assets/14347794/16288761/f086ade8-3921-11e6-87d8-6635cfceb588.png">

**Comment by abshawn** [comment]
正解

**Comment by jabber** [comment]
最新的版本，把zh-Hans改成了zh-CN，找了我两个小时……

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
