### ISSUE TITLE
关于语言代码的问题

### ISSUE THREAD

**Issue by marionette-curtain** [iissnan/hexo-theme-next#954]
在NexT的languages文件夹中.代表中文的文件名为zh-Hans.yml.这意味着在站点配置文件中的languages处必须写zh-Hans.但是根据Hexo官方文档的要求此处应为两个字母的ISO-639-1码.在wikipedia上查询后得知中文的ISO-639-1码为zh.所以是否可以将zh-Hans.yml文件改名为zh.yml以符合官方文档的要求?

**Comment by marionette-curtain** [comment]
如果写zh就会使用de....可是我看不懂德语啊....

**Comment by qhxin** [comment]
想用简中就用zh-Hans啊，有什么好纠结的。。。

**Comment by marionette-curtain** [comment]
强迫症.....

**Comment by ivan-nginx** [comment]
@marionette-curtain dont understand u, write in English if not solved. If solved, close it please. Thank's!
