### ISSUE TITLE
如何让 NexT 不默认启用 Mathjax?

### ISSUE THREAD

**Issue by MaoKwen** [iissnan/hexo-theme-next#955]
Mathjax 好像略微有点拖慢网页的速度, 
我看了[这篇文章](http://lukang.me/2014/mathjax-for-hexo.html)
但是没有找到他所说的 `after_footer.ejs`,
请问我该怎么做? 谢谢

**Comment by MaoKwen** [comment]
解决了, 修改 `mathjax.swig`, 在里面再嵌套一层 `{% if (page.mathjax) %}` `{% endif %}`, 然后在想要开启 mathjax 的页面前加入 'mathjax: true'

**Comment by ChestnutHeng** [comment]
怎么在开启 mathjax 的页面前加入 'mathjax: true' ? 在md里吗
