### ISSUE TITLE
文章excerpt 配置

### ISSUE THREAD

**Issue by FraserYu** [iissnan/hexo-theme-next#956]
在主题配置文件中看到： 

Automatically scroll page to section which is under  mark.
scroll_to_more: true

Automatically Excerpt. Not recommand.
Please use  in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 250

可是不推荐用， 那个  在什么位置怎么用？

**Comment by xovel** [comment]
`scroll_to_more: true`是直接截取文章中的`<!--more-->`之前的内容。

`excerpt`是强行截取指定数量的文本。

使用`<!--more-->`更加方便，可控度也高。放在所写文章的合适位置即可。

不过个人建议直接在Front-matter中指定`description`。

**Comment by FraserYu** [comment]
非常感谢.  这个地方真好。
