### ISSUE TITLE
代码高亮无效！

### ISSUE THREAD

**Issue by Cao-Yu** [iissnan/hexo-theme-next#957]
已经在配置文件中选择了代码高亮主题，其他一切正常，只有代码高亮是无效的，黑底灰字，没有其他颜色。

**Comment by xovel** [comment]
#899  #644

**Comment by Cao-Yu** [comment]
在我提问之前 我已经阅读过这两个问题了。然而并没有解决问题不是吗？

发自我的 iPhone

**Comment by Cao-Yu** [comment]
我已经找到问题的原因了，因为的代码块写的是swift语言，没有分号。加上分号以后就有代码高亮的效果啦。所以我建议随着现在高级语言的普及，可否尝试着增加识别无分号程序的功能呢？并且我很愿意在您的指导下贡献自己的力量来完成这个功能

**Comment by iissnan** [comment]
@Cao-Yu 代码的高亮是借助于 [Highlight.js](https://highlightjs.org/) 实现的，估计其对 Swift 的支持不是很好。这个在主题内无能为力。

**Comment by Cao-Yu** [comment]
好吧，谢谢您

**Comment by Vernsu** [comment]
@Cao-Yu  .md中有没有标注代码是Swift语言的？
```swift
your swift code
```
