### ISSUE TITLE
试着改改样式，sidebar里的GitHub等链接居中是不是好一点

### ISSUE THREAD

**Issue by yorbit** [iissnan/hexo-theme-next#959]
不知道这里是不是有研究过，如果是特意这样排版的，请不要介意，就当我分享一次想法:smile:
### Expected behavior (预期行为)

配置自己主题的时候，放了2个链接试试效果，发现sidebar最下面是向左对齐的，上面都是居中，不对称好不舒服啊
<img width="239" alt="before" src="https://cloud.githubusercontent.com/assets/14347794/16329992/c60811f4-3a18-11e6-83fd-f483ee510afa.png">
### Actual behavior (实际行为)

于是用控制台找找样式在哪里，给这里样式的text-align: left; 改成 center;
<img width="264" alt="position" src="https://cloud.githubusercontent.com/assets/14347794/16330044/24da5fd4-3a19-11e6-85cf-8022a3e31b76.png">
这是下面的链接居中的效果
<img width="241" alt="after" src="https://cloud.githubusercontent.com/assets/14347794/16330074/5770b1e6-3a19-11e6-8eae-4deef1ac48b1.png">
### Steps to reproduce the behavior (重现步骤)

hexo clean
hexo g
hexo s
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version: 5.0.1
-  Master
-  Latest Release
-  Old version - 

NexT Scheme: Pisces
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by aixiu** [comment]
这种不影响整体效果的东西，自己改改就好了，

**Comment by TypeLee** [comment]
你是怎么设置的，我的设置完了就是这个样子
http://oby215rza.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20160821123950.png

**Comment by ivan-nginx** [comment]
@yorbit dont understand u, write in English if not solved. If solved, close it please. Thank's!
