### ISSUE TITLE
 swiftype 站内搜索的样式

### ISSUE THREAD

**Issue by mingmings** [iissnan/hexo-theme-next#96]
使用了 `swiftype` 样式，也看到了 merger 过来的作者推荐使用国内的一款站内搜索工具，都挺好的，但是貌似在精简主题下，样式非常赞，但是放到了标准主题下，样式很奇特的说
![image](https://cloud.githubusercontent.com/assets/3365500/7059959/b8d8d302-deab-11e4-992f-3d7d530f4bf8.png)
希望能针对标准主题进行样式进行调整呢，谢谢了

**Comment by mingmings** [comment]
@iissnan 另外，好像没看到怎么启用 Mist 主题呢，下载 release 版本之后，看到里面的配置文件里的确有 `scheme: Mist` ，但是启用了却没有效果

**Comment by iissnan** [comment]
搜索框的样式估计得重新弄下。 注释掉 `scheme` 无法启用 Mist 主题吗？ 执行下 `hexo clean` 再试试。

**Comment by mingmings** [comment]
@iissnan tks，已修复
