### ISSUE TITLE
分享到微信被转码，页面白屏的问题（解决思路，求实现代码）

### ISSUE THREAD

**Issue by InteractionDesignWiki** [iissnan/hexo-theme-next#961]
适用于有两个域名的人，一个国内备案的域名，一个未备案的域名

分享时候替换URL中的域名，两个域名都要CNAME到博客里。

我看了一下Jiathis和百度分享都有自定义URL这个选项，但是有个问题我不知道怎么解决就是 只替换当前页面中的域名部分，而不是固定分享主域名。

例如：
当前URL：abc.co/123/12312/5.html  (没有备案）
分享到微信：123.com/123/12312/5.html （备案过）

代码不是很精通不知道怎么改分享代码，求大牛看看是否可行。我有两个域名其中一个备案了

另外，这个方式我在天猫APP上看到了他们实现了，分享到微信的域名是 laiwang.com  H5页面域名是m.tmall.com

**Comment by ivan-nginx** [comment]
@InteractionDesignWiki dont understand u, write in English if not solved. If solved, close it please. Thank's!
