### ISSUE TITLE
能否增加支持在单个文章、或页面中覆盖是否出现侧栏的选项？

### ISSUE THREAD

**Issue by atjason** [iissnan/hexo-theme-next#964]
您好，
这是个需求，不是 issue.
- 能否增加支持在单个文章、或页面中覆盖是否出现侧栏的选项？
- 能否增加支持页面中出现侧栏的选项？

谢谢。

**Comment by atjason** [comment]
更新：

> 能否增加支持页面中出现侧栏的选项？

找到方案了，只要在文章开头增加这个选项就可以了：layout: post

**Comment by ivan-nginx** [comment]
@atjason dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by atjason** [comment]
Close this issue as found walk around.
