### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by Hermera** [iissnan/hexo-theme-next#965]
Github的邮件是这样说的……  

The page build failed with the following error:

The submodule `themes/next` was not properly initialized with a `.gitmodules` file. For more information, see https://help.github.com/articles/page-build-failed-missing-submodule.

现在访问是无尽404……有没有人能告诉我是什么问题？

**Comment by iissnan** [comment]
你是怎么进行 deploy 到 GitHub Pages ？

**Comment by Hermera** [comment]
我重新安装了hexo，这个问题已经自己消失了…………
谢谢！

**Comment by xdoupd** [comment]
我也遇到了上面同样的问题，现在还没有找到解决方法，本地预览没问题，我是在博客根目录下进行 hexo d 的，这个问题需要怎么解决？重装hexo之后问题依旧存在 @Hermera @iissnan 
![image](https://cloud.githubusercontent.com/assets/5766864/23887851/3fb14848-08bf-11e7-8e06-90c559f345f0.png)
