### ISSUE TITLE
文章中存在链接时前面的文字间距问题

### ISSUE THREAD

**Issue by Kyson** [iissnan/hexo-theme-next#966]
### Expected behavior (预期行为)

文章中存在链接，前面的文字间距不应该调整，而是链接换行
### Actual behavior (实际行为)

似乎是为了链接不换行，导致链接前面的文字间距调整变宽了。
### Steps to reproduce the behavior (重现步骤)

一个链接前面加一些文字即可
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master  
-  Latest Release    ✔
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces          ✔
### Other Informations (Like Browser, System, Screenshots)

windows chrome

**Comment by amao12580** [comment]
![problem](https://cloud.githubusercontent.com/assets/4270177/16477024/9f1f1928-3ec0-11e6-9d21-c9d3903fb091.png)
这个问题如何解决？？？？？？

**Comment by lzx1413** [comment]
同问

**Comment by amao12580** [comment]
@lzx1413 貌似无解了，得改源码

**Comment by ivan-nginx** [comment]
@Kyson dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by Kyson** [comment]
@ivan-nginx 
thx for reply!

Text spacing is too large when it contains some link,like following:

![](https://cloud.githubusercontent.com/assets/4270177/16477024/9f1f1928-3ec0-11e6-9d21-c9d3903fb091.png)

**Comment by ivan-nginx** [comment]
@Kyson can u give live demo on this?
