### ISSUE TITLE
“分类”“标签”“关于”页面中正文部分没有动画

### ISSUE THREAD

**Issue by AlynxZhou** [iissnan/hexo-theme-next#967]
### Expected behavior (预期行为)

所有的元素应该**像文章中的元素一样**，依次按动画出现。
### Actual behavior (实际行为)

上述三个页面内只有和其他页面中相同的元素有动画，**中间的主要内容并没有动画**。
### Steps to reproduce the behavior (重现步骤)

自己建立一个博客并书写若干内容，访问上述三个页面。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

   ✔ Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
  ✔  Pisces
### Other Informations (Like Browser, System, Screenshots)

浏览器是Google Chrome 51.0.2704.36

系统是Gentoo Linux

**Comment by aixiu** [comment]
自定义页面的好像都没有。

**Comment by ivan-nginx** [comment]
@AlynxZhou dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by AlynxZhou** [comment]
@ivan-nginx Maybe too late, I mean that I find only words in posts have animation, when open tag/category/about page, they have no animation at all, I think having animation maybe better?

**Comment by ivan-nginx** [comment]
@AlynxZhou in posts swig templates in earlier branches titles not present. I was addied it there a year ago (or about) with description on each post. If u want add animation or anything else, u may do it in `source/css/_common/components/post/*`. I think need to see how animation work in simple post articles and duplicate it to pages. Pull requests are always welcome!

**Comment by AlynxZhou** [comment]
Got it, closed.
