### ISSUE TITLE
wechat-subscriber.swig 模板文件中存在元素 style 属性字符错误

### ISSUE THREAD

**Issue by JounQin** [iissnan/hexo-theme-next#968]
### Expected behavior (预期行为)
`display: block;`

### Actual behavior (实际行为)
`display: block；`

### Steps to reproduce the behavior (重现步骤)
直接打开该文件即可查看

### NexT Informations
这导致使用 `gulp-posthtml` 进行 html 压缩时报错而压缩失败

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  ✔  Latest Release
  ✔  Old version - 

NexT Scheme:
  ✔  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by xovel** [comment]
It's an errata. @iissnan

**Comment by JounQin** [comment]
fixed
