### ISSUE TITLE
手机端菜单区域搜索按钮点击无效

### ISSUE THREAD

**Issue by JounQin** [iissnan/hexo-theme-next#969]
### Expected behavior (预期行为)
点击打开搜索层或手机端不展示搜索按钮

### Actual behavior (实际行为)
展示搜索按钮，但无法点击

### Steps to reproduce the behavior (重现步骤)
使用智能手机或 Chrome 模拟

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  ✔  Master
  ✔  Latest Release
  ✔  Old version - 

NexT Scheme:
  ✔  All schemes
  -  Muse
  -  Mist
  -  Pisces

### Other Informations (Like Browser, System, Screenshots)
使用 localSearch 插件，`$('.popup-trigger')` 挂载的是 `mousedown` 方法，手机端自然没有，所以点击无效，更换为 `click` 即可。

**Comment by bourne7** [comment]
你好！请问 **$('.popup-trigger')** 是在哪里呢? 这个listener 是属于 这个主题的还是属于 hexo 的呢？ 谢谢！

**Comment by bourne7** [comment]
哇咔咔，找到了。。在 next主题文件夹/layout/_scripts/_third-party/localsearch.swig  O(∩_∩)O

**Comment by flashlab** [comment]
@JounQin 方便说下手机型号和浏览器吗？在我这里是正常的。

**Comment by JounQin** [comment]
@bourne7 *NexT* 主题的 `localsearch` 功能挂载的

@flashlab iPhone 6，Safari / QQ 浏览器

另外，实际操作了一下，仅将 `mousedown` 改为 `click` 也是不够的，因为 `a` 标签上 `href` 属性的 `#`，需要改成 `javascript:;` 以阻止页面跳转事件，手机上的 `click` 事件才能生效。

**Comment by flashlab** [comment]
@JounQin 可以帮忙提交个补丁修复下吗？

**Comment by JounQin** [comment]
fixed
