### ISSUE TITLE
TOC锚点初始化失败？

### ISSUE THREAD

**Issue by ivanberry** [iissnan/hexo-theme-next#974]
TOC跳转链接应该是与文章标题对应的，但是md渲染后文章标题并没有对应id

期望：

``` md
## 标题 //mardown title
```

``` html
<h2 id="标题">标题</h2>
```

查看源码后，应该不是js部分有错误，js部分只是取出响应属性值，并取得offset

``` js
  $('.post-toc a').on('click', function (e) {
    e.preventDefault();
    var targetSelector = NexT.utils.escapeSelector(this.getAttribute('href')); //undefined
    var offset = $(targetSelector).offset().top; //理所当然就报错了

    hasVelocity ?
      html.velocity('stop').velocity('scroll', {
        offset: offset  + 'px',
        mobileHA: false
      }) :
      $('html, body').stop().animate({
        scrollTop: offset
      }, 500);
  });
```

是md渲染出来的问题？

线上地址，可以查看我的地址：[任意文章](https://tabgre.com)

**Comment by JasonSi** [comment]
你是用markdown-it渲染的嘛，我也遇到这个问题了0.0

**Comment by ivanberry** [comment]
对，对，就是它，难道是它的问题！！

**Comment by JasonSi** [comment]
是的
官方markdown-it好像拒绝实现这个功能，就是不渲染heading的id导致锚点失效

所以我改造了一下hexo-markdown-it……

——Jason

> 在 2016年8月12日，23:16，Tab <notifications@github.com> 写道：
> 
> 对，对，就是它，难道是它的问题！！ 
>

**Comment by JasonSi** [comment]
https://github.com/celsomiranda/hexo-renderer-markdown-it/issues/40

**Comment by wuxubj** [comment]
[我的博客](http://www.wuxubj.cn/)没有这样的问题啊，点击文章内小标题都会跳转到文章对应位置。
如果确定markdown语法没有问题，那么可能是生成html时出了问题，建议重新安装Hexo。

**Comment by JasonSi** [comment]
@wuxubj  不是。。真的是markdown-it的实现有差别。 默认Marked插件是没有问题的，因为他GFM支持的不太好，我就换成了Markdown-it，但是他不生成标题的id导致无法获取锚点。

**Comment by ivan-nginx** [comment]
@ivanberry dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by khiav223577** [comment]
It's [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)'s bug.
