### ISSUE TITLE
关于无序列表中加入代码块后显示的问题

### ISSUE THREAD

**Issue by ShenZeshu** [iissnan/hexo-theme-next#976]
### Expected behavior (预期行为)

``````
* aaa

    ``` 
    public class
    ```
* bbb
    * aaaa
    * bbbb
    * cccc
``````

无序列表中的某一项(aaa)下加入代码块后，随后的一项(bbb)应该正常显示。
### Actual behavior (实际行为)

(bbb)会被`<p>`包裹，会空出一段。
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
  ✔-   Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
  ✔-  Muse
-  Mist
-  Pisces
### Other Informations (Like Browser, System, Screenshots)

![2016-07-05 22 03 36](https://cloud.githubusercontent.com/assets/14882592/16587623/237d60ee-42fe-11e6-8d8c-e05907ae6032.png)

**Comment by ivan-nginx** [comment]
@ShenZeshu dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by michaelHL** [comment]
Same here. Seemed like a bug, but you can use the raw [`code block tag`](https://hexo.io/docs/tag-plugins.html#Code-Block) instead.
