### ISSUE TITLE
请问博主，next或者hexo，链接站内文章的方法？

### ISSUE THREAD

**Issue by shliujing** [iissnan/hexo-theme-next#978]
我现在用的是markdown绝对地址来链接本站的其他文章。

```
绝对地址
[点击这里查看这篇文章](http://www.iamlj.com/2015/07/markdown-learning-by-maxiang)

是否有xx相对地址
[点击这里查看这篇文章]( xx markdown-learning-by-maxiang)

的方法？
```
@iissnan

**Comment by shliujing** [comment]
找到了，是可以的。使用
```
[点击这里查看这篇文章](../markdown-learning-by-maxiang)即可
```
但是会出现一共问题，那就是url中时间错误的问题：
譬如当前文章是a.com/2016/1/1/a.html，文章内引用[b](../b.html)，则会跳转到a.com/2016/1/1/b.html。
前提是b.html也是同日写的才行

**Comment by xovel** [comment]
~~标题有错别字阿喂...~~

~~`Markdown`的链接语法本来就支持相对地址，请仔细阅读相关文档。~~

关于引用站内文章的链接，可以使用以下语法：
```text
{% post_link markdown-learning-by-maxiang 点击这里查看这篇文章 %}
```

- `markdown-learning-by-maxiang`是你的文章名称。*如果文章不存在，这段代码将会被直接忽略。*
- `点击这里查看这篇文章`是该链接的标题。*如果置空，则自动提取文章的标题。*

ps：这个功能跟主题无关。

**Comment by shliujing** [comment]
@xovel 回答的非常好，非常感谢！

虽然这语法背离了markdown语法，不过可以解决url时间地址问题，也方便了不少。

**Comment by shliujing** [comment]
@xovel 不好意思，又遇到问题了。。。
请问加页内锚点如何解决？比如定位到标题“功能介绍”
{% post_link markdown-learning-by-maxiang/#功能介绍 功能介绍 %}

失效。

**Comment by xovel** [comment]
> 如果文章***不存在***，这段代码将会被直接忽略。

你的`_post`目录下并没有`markdown-learning-by-maxiang/#功能介绍`这样名字的文章，于是就被忽略了。

如果需要定位到页内锚点，可以直接使用该文章的相对地址。
```text
[功能介绍](/2016/7/11/title.html#功能介绍)
```

**Comment by shliujing** [comment]
@xovel 回答的真严谨，哈哈。
我刚也查到了，这个问题上，hexo对时间url方面支持还不够有好。
先用着这个吧，至少以后换域名还是可以用的，换时间就蛋疼了0 0.

**Comment by sdsy888** [comment]
> 标题有错别字阿喂...
> 
> `Markdown`的链接语法本来就支持相对地址，请仔细阅读相关文档。
> 
> 关于引用站内文章的链接，可以使用以下语法：
> 
> ```
> {% post_link markdown-learning-by-maxiang 点击这里查看这篇文章 %}
> ```
> * `markdown-learning-by-maxiang`是你的文章名称。_如果文章不存在，这段代码将会被直接忽略。_
> * `点击这里查看这篇文章`是该链接的标题。_如果置空，则自动提取文章的标题。_
> 
> ps：这个功能跟主题无关。

请问这里的 `post_link`是有什么特殊含义吗？还是仅仅指_post 文件夹下的内容？ 谢谢~

刚刚尝试发现在`_post`文件夹下的名为`2019`子文件夹下面的内容可以通过把2019加到文章名前面引用成功，类似这样：
```
{% post_link 2019/我的文章名称 点击这里查看这篇文章 %}
```

**Comment by stevenjoezhang** [comment]
@sdsy888 `post_link` 是这个tag的标识符，无需更改

请使用新版：https://github.com/theme-next/hexo-theme-next

**Comment by hfksalj** [comment]
> > 标题有错别字阿喂...
> > `Markdown`的链接语法本来就支持相对地址，请仔细阅读相关文档。
> > 关于引用站内文章的链接，可以使用以下语法：
> > ```
> > {% post_link markdown-learning-by-maxiang 点击这里查看这篇文章 %}
> > ```
> > 
> > 
> > 
> > * `markdown-learning-by-maxiang`是你的文章名称。_如果文章不存在，这段代码将会被直接忽略。_
> > * `点击这里查看这篇文章`是该链接的标题。_如果置空，则自动提取文章的标题。_
> > 
> > ps：这个功能跟主题无关。
> 
> 请问这里的 `post_link`是有什么特殊含义吗？还是仅仅指_post 文件夹下的内容？ 谢谢~
> 
> 刚刚尝试发现在`_post`文件夹下的名为`2019`子文件夹下面的内容可以通过把2019加到文章名前面引用成功，类似这样：
> 
> ```
> {% post_link 2019/我的文章名称 点击这里查看这篇文章 %}
> ```

It helps me a lot!
