### ISSUE TITLE
能否修改页面的背景色呢？

### ISSUE THREAD

**Issue by ethan-funny** [iissnan/hexo-theme-next#98]
感觉白色的背景有些亮，不知可否修改背景色？

**Comment by eurusd** [comment]
白色很好 很简约 为什么要改???

**Comment by iissnan** [comment]
@ethan-funny 可以，在 `source/css/_variables/base.styl` 中：

```
// Background color for <body>
$body-bg-color                = white
```

**Comment by chineselzh** [comment]
@iissnan 感谢带来这么优秀的主题！建议增加一个暗系的色彩搭配，就像简书的`白天`与`夜晚`模式一样，我觉得[http://ppting.me/2015/01/26/change-jacman-theme/](http://ppting.me/2015/01/26/change-jacman-theme/)这个配色不错，但那个jacman主题又不如next。。。

**Comment by eurusd** [comment]
我还停留在next 4.0  新更新打开页面，如标签页面 ，就会失去侧边栏。
真心感谢带来 这么好的主题。

**Comment by chineselzh** [comment]
@iissnan Theme in theme想法太棒了，期待暗系色彩！呵呵。。。

**Comment by iissnan** [comment]
暗色主题将在 `0.5.0` release，见：https://github.com/iissnan/hexo-theme-next/wiki/Changelog

**Comment by wa-ri** [comment]
我在 ``` theme/source/css/_variables/base.styl ``` 中：
```
// Background color for <body>
$body-bg-color                = $grey-dark
```
修改颜色属性后发现没有任何改变，```hexo g```时显示：
```
$ hexo g
INFO  Start processing
INFO  Files loaded in 547 ms
INFO  0 files generated in 650 ms
```
没有文件生成？
