### ISSUE TITLE
首页是否可以指定特定的page

### ISSUE THREAD

**Issue by Jatstar** [iissnan/hexo-theme-next#980]
非常喜欢这个主题
尤其是归档的时间轴，想使用 归档 作为首页，请问应该如何修改？

**Comment by xinnyu** [comment]
同问

**Comment by kagomemiao** [comment]
把主题内layout文件夹的index.swig重命名备份，新建一份index.swig
把archives.swig的{% block content %}标签的内容copy覆盖index.swig的{% block content %}标签后的内容
再把archive的{% block script_extra %} copy添加到新的index.swig最下方

我是选择去掉了<span class="archive-move-on">和<span class="archive-page-counter">
只显示归档文章

**Comment by xinnyu** [comment]
@kagomemiao 谢谢，搞定了，不过我替换的时候出了点问题
需要把这一行也替换掉：`{% import '_macro/post-collapse.swig' as post_template %}`

**Comment by kagomemiao** [comment]
@xinnyu 没错，我忘记提了 不好意思

**Comment by ivan-nginx** [comment]
@Jatstar dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by mapan2020** [comment]
我有同样的想法自定义主页，但我也想去掉page页面的渲染。
---
换句话说就是在`Hexo g`之后，`public`文件夹下，没有`page`文件夹
应该怎么实现呢？
