### ISSUE TITLE
你好，我用的是next-mist主题，设置副标题后显示不出来，要怎么修改？

### ISSUE THREAD

**Issue by andybroker** [iissnan/hexo-theme-next#986]
你好，我用的是next-mist主题，设置副标题后显示不出来，要怎么修改？

**Comment by ivan-nginx** [comment]
@andybroker dont understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by weishijun14** [comment]
use mist theme, and set a subtitle , but it does not display on the website, why?

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new feature, **please, close this issue and [create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/cn/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.

**Comment by loremwalker** [comment]
打开`themes/next/source/css/_schemes/Mist/_logo.styl` 将 `.site-subtitle { display: none; }`注释掉

**Comment by loremwalker** [comment]
@andybroker 打开`themes/next/source/css/_schemes/Mist/_logo.styl` 将 `.site-subtitle { display: none; }`注释掉
