### ISSUE TITLE
除首页之后的分页，都会消失

### ISSUE THREAD

**Issue by his1devil** [iissnan/hexo-theme-next#99]
如题，首页分页点击到其他page页面，分页消失，出现前后文章选择样式，没有分页，求教

**Comment by iissnan** [comment]
估计跟你的 permalink 设置有关，更新下主题再试试。见：https://github.com/iissnan/hexo-theme-next/issues/93

**Comment by his1devil** [comment]
非常感谢，permalink设置为:category/:title 会出现这个错误
