### ISSUE TITLE
在iPhone6上预览的时候字体模糊

### ISSUE THREAD

**Issue by zeewane** [iissnan/hexo-theme-next#990]
### Expected behavior (预期行为)

使用手机的页面预览的时候字体清楚
### Actual behavior (实际行为)

使用iPhone5模拟的时候清楚，但是iPhone6的时候就是模糊的
### Steps to reproduce the behavior (重现步骤)

使用chrome浏览器，F12打开开发者工具，选择移动端，选择iPhone6
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release✔
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces✔
### Other Informations (Like Browser, System, Screenshots)
- winowes 10586
- chrome 51.0.2704.106 64bit

**Comment by ivan-nginx** [comment]
@zeewane dont understand u, write in English if not solved. If solved, close it please. Thank's!
