### ISSUE TITLE
文章预览中代码行号排成一行超出页面.

### ISSUE THREAD

**Issue by zhou-fei** [iissnan/hexo-theme-next#992]
### Expected behavior (预期行为)

在首页每个文章的预览的那几行中,代码预览的行号不应该超出页宽
### Actual behavior (实际行为)

在首页每个文章的预览的那几行中,代码预览的行号超出页宽,例子如
巴拉拉巴拉巴拉巴拉巴拉 最近使用天气预报接口很不如意啊，稳定的要收费，免费的又不稳定, 记录下自己的做法…… 1. 根据网络请求获得当前城市的ID,方法,额,百度吧.或者直接搜天气咯. 2. 根据百度搜索天气预报第一条获得的数据，进去http://www.weather.com.cn/weather1d/101020100.shtml进行网页抓取 3. 根据今天的白天和夜晚得到的数据进行组合,具体要显示哪些信息,由自己根据需求拼在一起. 4. 代码如下： 1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253package`前面的数字排成一行超出页宽` name.zhoufei.weather;im 
### Steps to reproduce the behavior (重现步骤)

插入代码,代码前面的文章内容要小,预览的文章能够预览到代码块
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by Zhou-Fei** [comment]
http://helloworld.zhoufei.name/

可以看首页预览下

**Comment by Zhou-Fei** [comment]
文章代码我用代码块改了,用

        ```java
              a(){}
        ```
的方法不对, 图如下:
<http://source.zhoufei.name/Screenshot%20from%202016-07-16%2018-45-34.png>

**Comment by Zhou-Fei** [comment]
disqus 首页0评论不显示 ,,,,

<http://source.zhoufei.name/Screenshot%20from%202016-07-16%2019-43-27.png>

**Comment by ivan-nginx** [comment]
@zhou-fei dont understand u, write in English if not solved. If solved, close it please. Thank's!
