### ISSUE TITLE
pagination 分页问题

### ISSUE THREAD

**Issue by suregm** [iissnan/hexo-theme-next#993]
### Expected behavior (预期行为)

分页正常。
### Actual behavior (实际行为)

index和categories页有多篇文章形成分页时，第一页下方有大量空白，中间页没有数据显示，最后一页显示正常。
### Steps to reproduce the behavior (重现步骤)

Theme - NexT.Mist
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  ✔ Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  ✔ Mist
-  Pisces

**Comment by ivan-nginx** [comment]
@suregm dont understand u, write in English if not solved. If solved, close it please. Thank's!
