### ISSUE TITLE
如何在网页底部增加备案信息呢？

### ISSUE THREAD

**Issue by ChangingFond** [iissnan/hexo-theme-next#995]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -   Master  
  -  Latest Release  ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces  ✔

**Comment by Javen205** [comment]
在   主题layout >_partials>footer.swig中最下面添加
```
<div style="text-align:center;width:100%;height:50">
  备案信息：xxxxxx
<div>
```
