### ISSUE TITLE
点击阅读全文文章跳到最底部

### ISSUE THREAD

**Issue by cconecode** [iissnan/hexo-theme-next#996]
### Expected behavior (预期行为)

使用  的方式来截取文章，点击阅读全文，文章跳到开头部分
### Actual behavior (实际行为)

点击阅读全文，文章跳到最底部
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Master
-  Latest Release
-  Old version - 

NexT Scheme:
-  All schemes
-  Muse
-  Mist
-  Pisces

**Comment by aixiu** [comment]
点击阅读全文，默认是在你添加的位置为最顶。

**Comment by clatisus** [comment]
@aixiu 请问如何修改跳转到最顶呢？

**Comment by supertiny99** [comment]
的位置貌似是有锚点了。。
不过想点击直接从最上面开始。有什么好办法吗

**Comment by ivan-nginx** [comment]
@cconecode dont understand u, write in English if not solved. If solved, close it please. Thank's!
