### ISSUE TITLE
建议增加social_icons知乎和豆瓣的图标

### ISSUE THREAD

**Issue by gpj008** [iissnan/hexo-theme-next#997]
建议增加social_icons知乎的图标，我不懂前端技术，也没在next文件夹下找到这些图片的来源，据我所知目前豆瓣和知乎的图标都是没有的，如果能加上就再好不过了，谢谢！

**Comment by aixiu** [comment]
这些图片要引用库有才行，引用库没有收录，那就只能想别的办法了

**Comment by xovel** [comment]
`Map a menu item to a specific FontAwesome icon name`

~~知乎和豆瓣的图标似乎不在 FontAwesome 的当前版本里面。~~

**Comment by shliujing** [comment]
一种解决方案。
将知乎和豆瓣的图标灰化，传到cdn上，通过在class里通过url调用。

**Comment by Maples7** [comment]
https://www.zhihu.com/question/43310056

**Comment by jackzzj** [comment]
目前还是不支持嘛？

**Comment by iissnan** [comment]
FontAwesome 4.7 也未引入，估计悬。

**Comment by simon-xia** [comment]
<i class="fa " aria-hidden="true">知</i> 替代？

**Comment by ivan-nginx** [comment]
NexT is rebased into [organization](https://github.com/theme-next) [repo](https://github.com/theme-next/hexo-theme-next).
If you want new **feature**, **fix**, or **support**, **[create new in NexT v6.x repo](https://github.com/theme-next/hexo-theme-next/issues)** (**desirable in English**).

There is instructions on [English](https://github.com/theme-next/hexo-theme-next/blob/master/docs/UPDATE-FROM-5.1.X.md) or [Chinese](https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/UPDATE-FROM-5.1.X.md) how to update from v5.1.x to v 6.0.x

You also may read [this](https://github.com/iissnan/hexo-theme-next/issues/2061) for details.
